### DISCUSSION TITLE
graphql/codegen/docs/config-reference/codegen-config

### DISCUSSION THREAD

**Discussion by giscus** [dotansimha/graphql-code-generator#10184] [Docs Discussions]
# graphql/codegen/docs/config-reference/codegen-config

Learn how to configure GraphQL Code Generator to generate code from your GraphQL schema and documents.

https://the-guild.dev/graphql/codegen/docs/config-reference/codegen-config

**Comment by skurihara-cw** [comment]
https://the-guild.dev/graphql/codegen/docs/config-reference/codegen-config#dry-run-mode

Does the dry run topic work?

When I run the --help command, I don't see the `--check` option.

```
yarn graphql-codegen --help
yarn run v1.22.22
$ /Users/hoge/node_modules/.bin/graphql-codegen --help
Options:
      --help         Show help                                         [boolean]
      --version      Show version number                               [boolean]
  -c, --config       Path to GraphQL codegen YAML config file, defaults to
                     "codegen.yml" on the current directory             [string]
  -w, --watch        Watch for changes and execute generation automatically. You
                     can also specify a glob expression for custom watch list.
  -r, --require      Loads specific require.extensions before running the
                     codegen and reading the configuration [array] [default: []]
  -o, --overwrite    Overwrites existing files                         [boolean]
  -s, --silent       Suppresses printing errors                        [boolean]
  -e, --errors-only  Only print errors                                 [boolean]
      --profile      Use profiler to measure performance               [boolean]
  -p, --project      Name of a project in GraphQL Config                [string]
  -v, --verbose      output more detailed information about performed tasks
                                                      [boolean] [default: false]
  -d, --debug        Print debug logs to stdout       [boolean] [default: false]
✨  Done in 0.98s.
```

**Comment by Diluka** [comment]
Is this really compatible with the `.graphqlrc` configuration file?

```yml
projects:
  default:
    schema: ./schema.graphql
  xxx:
    schema: ./libs/xxx/schema.graphqls
    documents:
      - "./libs/xxx/graphql/*.graphql"
      - "!**/playground.graphql"
    extensions:
      codegen:
        generates:
          ./libs/xxx/src/generated/index.ts:
            plugins:
              - typescript
              - typescript-operations
              - typescript-graphql-request
```

```
npx graphql-codegen -c .graphqlrc.yml -p xxx 

✖ Invalid Codegen Configuration!
  Please make sure that your codegen config file contains the "generates" field, with a specification for the plugins you need.
  It should looks like that:
  schema:
  - my-schema.graphql
  generates:
  my-file.ts:
  - plugin1
  - plugin2
  - plugin3
```
