### DISCUSSION TITLE
[Plugin Request] Mongoose models?

### DISCUSSION THREAD

**Discussion by dandv** [dotansimha/graphql-code-generator#3859] [General] [answered]
Background: I saw in #179 that @blissi mentioned a mongoose template. Where can one find that? I don't see mongoose among the examples in the [live demo](https://graphql-code-generator.com/#live-demo), or among [the plugins](https://graphql-code-generator.com/docs/plugins/).

Mongoose is quite popular, so I'm surprised there's no generator for it. Do people use something else? There are a 6+ [libraries trying to unify the definitions between TypeScript classes and mongoose models](https://stackoverflow.com/questions/34482136/mongoose-the-typescript-way/61154023#61154023) so it seems there would definitely be a need for a mongoose generator.

**Comment by myhendry** [comment]
@dandv I understand if you were to add in typescript-mongodb under plugins, it will type your mongoose models

**codegen.yml**
```
overwrite: true
schema: "http://localhost:4000/graphql"
documents: null
generates:
  src/__generated__/types.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
      - "typescript-mongodb"
  ./graphql.schema.json:
    plugins:
      - "introspection"

```

**Comment by dotansimha** [comment]
We currently don't have a Mongoose plugin, we have a plugin for generating model types for the basic `mongodb` NodeJS driver (to be used with generics). It allow you to define directives over your schema and get a models types according to those.

**Comment by amarquez914** [comment, marked as answer]
I was able to find a plugin from a repo: [link](https://github.com/MartinPavlik/graphql-codegen-mongoose-schema) for generating mongoose models directly from the graphql schema. What would this repo require in order to be added to codegen as an official plugin?

**Reply by dotansimha** [reply]
I guess, we need @martinpavlik collaboration :) If he wants to share that with the community, it can be wrapped as a codegen plugin package.

**Reply by MartinPavlik** [reply]
Ah, I'm not happy about the way how it's written, but if I remember well, I created a newer version that I never pushed to GitHub, gonna check later today and will let u know 🍺

**Reply by MehrdadKhnzd** [reply]
@MartinPavlik Any updates on this?

**Reply by MartinPavlik** [reply]
I found it, but ... it's not finished and it can't be used as a plugin right away, but maybe it's not as shi*ty as the previous version :smile:

Check it here https://github.com/MartinPavlik/graphql-codegen-mongoose-schema/tree/next

It was the first (and also last) time when I used the visitor pattern, so it is quite messy and full of console.logs, but it somehow works. I think that this would make more sense work on than the version that is in master branch.

### Example

Input: https://github.com/MartinPavlik/graphql-codegen-mongoose-schema/blob/next/input-schema-mtg.graphql 
Output: https://github.com/MartinPavlik/graphql-codegen-mongoose-schema/blob/next/generated-code.ts (:vomiting_face:  :vomiting_face:  :vomiting_face: but after few manual changes it is usable)

Feel free to fork/PR/whatever, I might help during this weekend :beers:

**Reply by hoffnung8493** [reply]
are there any updates on this? I would love to use mongoose plugin.

**Reply by hoffnung8493** [reply]
Actually, I just found this blog post about configuring maps for custom models. And it works as expected!
https://the-guild.dev/blog/better-type-safety-for-resolvers-with-graphql-codegen

**Reply by amarquez914** [reply]
@hoffnung8493 I've been trying to get this to work but still running into issues, are you able to share an example that you managed to get working?

**Reply by hoffnung8493** [reply]
@adam1658 Sure, below is how my codegen.yaml looks like

```
overwrite: true
schema:
  - src/graphql/**/schema.ts
documents: null
generates:
  ./src/graphql/__generatedTypes__.ts:
    plugins:
      - add:
          content: "import { MyContext } from './context'"
      - typescript
      - typescript-resolvers
    config:
      contextType: MyContext
      useIndexSignature: true
      mappers:
        Chat: ../models#ChatDoc
        ChatMessage: ../models#ChatMessageDoc
```

And inside models/index.js (or just models.js) I have

```
import { Document, Schema, model, Model } from 'mongoose'
export interface ChatDoc extends Document {
  id: string
  name: string
  type: ChatType
  cohortId?: string
  organizationId?: string
  teamId?: string
  pinnedTopUserIds: string[]
  pinnedTop?: boolean
  userIds: string[]
  messageLast?: ChatMessageDoc
  messages?: ChatMessageDoc[]
  createdAt: Date
  updatedAt: Date
  setPinnedTop(userId?: string): void
}
```
And make sure
1. that the path of the mappers are with respect to the generated types(in my case `__generatedTypes__.ts` its not with respect to the `codegen.yml` file and 
2. to add the name of the mapping interface on the path as `#ChatDoc`. This part is not a comment.

**Reply by evsar3** [reply]
@hoffnung8493 That's exacly what I was looking for! Thank you!

I was wondering how amazing it could be if you can set an expression for the `mappers` like:
```yaml
overwrite: true
schema:
  - src/graphql/**/schema.ts
documents: null
generates:
  ./src/graphql/__generatedTypes__.ts:
    plugins:
      - add:
          content: "import { MyContext } from './context'"
      - typescript
      - typescript-resolvers
    config:
      contextType: MyContext
      useIndexSignature: true
      mappers:
        path: ../models
        pattern: "{{type}}Doc"
```

This could extinguish any need for a Mongoose plugin
