### DISCUSSION TITLE
Best way to handle large types file

### DISCUSSION THREAD

**Discussion by JClackett** [dotansimha/graphql-code-generator#3970] [General]
Hi!

I was wondering what the best way to handle a large generated type file is?

My current file is around 13000 lines, is there a way to minify it, skip formatting etc?

My config is:

```
schema: http://localhost:5000/graphql
documents: ./src/**/*.{ts,tsx}
overwrite: true
generates:
  ./src/lib/graphql.tsx:
    config:
      withHooks: true
      withComponent: false
      withHOC: false
      withMutationFn: false
      addDocBlocks: false
      scalars:
        DateTime: string
        BigInt: number
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
```
