### DISCUSSION TITLE
How would I go about generating the appropiate types for my resolvers with federation?

### DISCUSSION THREAD

**Discussion by gmencz** [dotansimha/graphql-code-generator#4058] [General] [answered]
This is my codegen.yml:
```yml
schema: './src/graphql/schema.graphql'
documents: null
generates:
  src/graphql/generated.ts:
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
    config:
      federation: true
```

However, there's no __resolveReference generated for my entities types so I have to manually type that which isn't ideal whatsoever, is my config missing something?
