### DISCUSSION TITLE
Generate DocumentNode for the schema when building servers

### DISCUSSION THREAD

**Discussion by affanshahid** [dotansimha/graphql-code-generator#4067] [General] [answered]
I'm building a GraphQL server using `apollo-server`. I have multiple schema files and I was wondering if there was some way I could generate a typescript variable which contains the `DocumentNode` for the entire schema?

So similar to what `@graphql-codegen/typescript-document-nodes` does but for the schema instead. I know I can do this in a couple of steps, i.e generate a file for the merged then read that file but I want a method where I don't need the graphql files after running the build.

**Comment by dotansimha** [comment, marked as answer]
It should be pretty simple, you can create something like that as a custom plugin:

```js
// my-plugin.js
const { printSchema, parse } = require('graphql');

module.exports = {
  plugin: (schema) => {
     const schemaStr = printSchema(schema);
     const schemaNode = parse(schemaStr);

     return `export const schema = ${JSON.stringify(schemaNode)}`;
  }
}
```

Then use it in codegen:

```yml
schema: "src/**/*.graphql" # point here to all your schema pieces, codegen will merge it for you
generates:
  ./schema.ts:
     plugins:
       - ./my-plugin.js
```

@affanshahid 

For more info about custom plugins: https://graphql-code-generator.com/docs/custom-codegen/index
