### DISCUSSION TITLE
Schema Definition with custom scalars from AWS Amplify

### DISCUSSION THREAD

**Discussion by ChrisSargent** [dotansimha/graphql-code-generator#4311] [General] [answered]
I'm trying to generate Typescript typings from some schema files used with AWS Amplify. An example type is like this:

```graphql
type Record {
  id: ID
  createdBy: ID
  created: AWSTimestamp
  modified: AWSTimestamp
}
```

I have tried setting my config.yml as follows:

```yml
overwrite: true
schema: "amplify/backend/api/blockgraph/schema/*.graphql"
generates:
  src/generated/graphql.ts:
    config:
      scalars:
         AWSTimestamp: string
    plugins:
      - "typescript"
```

Trying to run the codegen, I get the error, `Error: Unknown type: "AWSTimestamp"`.

If I add `scalar AWSTimestamp` to the graphql file, it does compile correctly. But I'm wondering if I can avoid having to add the scalar to the graphql file and instead import some file from Amplify (I'm quite new to Graphql so not sure if this can even be done)?

**Comment by ChrisSargent** [comment, marked as answer]
I see Amplify has this file, https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-codegen/awsAppSyncDirectives.graphql, so I guess if I 'imported' that, it would include those definitions. Seems like this should be done in the 'documents' part of the config. However, this is a globally installed node_module so not certain how to reference it.

Edit - seems to work by including the file as an extra `schema` file

**Reply by dotansimha** [reply]
Exactly, this should be part of the `schema`. You need to tell codegen to load that part of the schema because Amplify adds it behind the scenes for you.

You can either copy and have it as a local file, or point directly to GitHub this way: 

```yaml
schema:
  - my-schema.graphql
  - github:aws-amplify/amplify-cli#master:packages/amplify-codegen/awsAppSyncDirectives.graphql
```

**Reply by ChrisSargent** [reply]
Great, yes thanks. For now I made a local copy of the file though I might switch to including `amplify-codegen` as a devDependency and referencing the file that way.

**Reply by amcdnl** [reply]
FYI - this no longer works and it seems they have removed that file too

**Reply by dotansimha** [reply]
I think the content of that file has been moved to this file: https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-codegen-appsync-model-plugin/src/scalars/supported-directives.ts

So it should be now: 

```yaml
schema:
  - my-schema.graphql
  - github:aws-amplify/amplify-cli#master:packages/amplify-codegen-appsync-model-plugin/src/scalars/supported-directives.ts
```

**Reply by amaingot** [reply]
> I think the content of that file has been moved to this file: https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-codegen-appsync-model-plugin/src/scalars/supported-directives.ts
> 
> So it should be now:
> 
> ```yaml
> schema:
>   - my-schema.graphql
>   - github:aws-amplify/amplify-cli#master:packages/amplify-codegen-appsync-model-plugin/src/scalars/supported-directives.ts
> ```

I found that including the scheme that way caused me issues. I saved [this file](https://github.com/aws-amplify/amplify-cli/blob/fe8ee8cff355a826fa9ccddcf0fad8a200a081af/packages/amplify-codegen/awsApppSyncDirectives.graphql) locally and included it in my `codegen.yaml` like so:

```yaml
schema:
  - "amplify/backend/api/{API_NAME}/build/schema.graphql"
  - "awsAppsyncDirectives.graphql"

```

**Reply by tombuckley91** [reply]
Before this file gets moved again!


```scalar AWSDate
scalar AWSTime
scalar AWSDateTime
scalar AWSTimestamp
scalar AWSEmail
scalar AWSJSON
scalar AWSURL
scalar AWSPhone
scalar AWSIPAddress
scalar BigInt
scalar Double

directive @aws_subscribe(mutations: [String!]!) on FIELD_DEFINITION

# Allows transformer libraries to deprecate directive arguments.
directive @deprecated(reason: String!) on INPUT_FIELD_DEFINITION | ENUM

directive @aws_auth(cognito_groups: [String!]!) on FIELD_DEFINITION
directive @aws_api_key on FIELD_DEFINITION | OBJECT
directive @aws_iam on FIELD_DEFINITION | OBJECT
directive @aws_oidc on FIELD_DEFINITION | OBJECT
directive @aws_cognito_user_pools(
  cognito_groups: [String!]
) on FIELD_DEFINITION | OBJECT
```

**Reply by cameronembling** [reply]
Create a file `aws.gql` co-locate it with your generated schema or typed schema `schema.gql` with the following:

```
scalar AWSTime
scalar AWSDateTime
scalar AWSTimestamp
scalar AWSEmail
scalar AWSJSON
scalar AWSURL
scalar AWSPhone
scalar AWSIPAddress
scalar BigInt
scalar Double

directive @aws_subscribe(mutations: [String!]!) on FIELD_DEFINITION

# Allows transformer libraries to deprecate directive arguments.
directive @deprecated(reason: String!) on INPUT_FIELD_DEFINITION | ENUM

directive @aws_auth(cognito_groups: [String!]!) on FIELD_DEFINITION
directive @aws_api_key on FIELD_DEFINITION | OBJECT
directive @aws_iam on FIELD_DEFINITION | OBJECT
directive @aws_oidc on FIELD_DEFINITION | OBJECT
directive @aws_cognito_user_pools(
  cognito_groups: [String!]
) on FIELD_DEFINITION | OBJECT
```

Codegen config

```yaml
schema: 
  - ./path-to-your-schema-files/schema.gql
  - ./path-to-your-schema-files/aws.gql
generates:
  ./src/types/schema.ts:
    config:
      scalars:
        AWSDateTime: Date
        AWSEmail: string
        AWSJSON: string
        AWSURL: string
        AWSTimestamp: string
    plugins:
      - typescript
      - typescript-operations
      - typescript-resolvers
 ```
