### DISCUSSION TITLE
How to bundle a typescript definition into an NPM package

### DISCUSSION THREAD

**Discussion by vestimir** [dotansimha/graphql-code-generator#4538] [General] [answered]
We have a couple of independent graphql services build in Elixir and I'm trying to add a client npm package for each of those. I'm using codegen to create a `src/index.tsx` file and then I try to compile it to JS with `tsc`. 

This is my codegen.yml:

```yml
overwrite: true
schema: "../schemas/public-schema.graphql"
documents: "src/**/*.graphql"
generates:
  src/index.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withHooks: true
      withHOC: false
      withComponent: false
```

and `package.json`:

```json
{
  "scripts": {
    "generate": "graphql-codegen --config codegen.yml",
    "build": "tsc"
  },
  "dependencies": {
    "graphql": "^15.3.0"
  },
  "peerDependencies": {
    "@apollo/react-common": "^3.1.4",
    "@apollo/react-hooks": "^4.0.0"
  },
  "devDependencies": {
    "@apollo/react-common": "^3.1.4",
    "@apollo/react-hooks": "^4.0.0",
    "@graphql-codegen/cli": "1.17.7",
    "@graphql-codegen/introspection": "1.17.7",
    "@graphql-codegen/typescript": "1.17.7",
    "@graphql-codegen/typescript-operations": "1.17.7",
    "@graphql-codegen/typescript-react-apollo": "1.17.7",
    "@types/apollo-codegen": "^0.20.3",
    "@types/react": "^16.9.44",
    "typescript": "^3.9.7"
  }
}
```

When running the build with `tsc` I get the following error:

```
node_modules/@apollo/react-common/lib/context/ApolloConsumer.d.ts:2:26 - error TS2307: Cannot find module 'apollo-client' or its corresponding type declarations.

2 import ApolloClient from 'apollo-client';
```

I'm a bit new to the whole typescript/codegen thingy – can you please advise how to proceed?
