### DISCUSSION TITLE
How to provide env file in .graphqlrc.yml

### DISCUSSION THREAD

**Discussion by Salehjarad** [dotansimha/graphql-code-generator#4587] [General] [answered]
I tride to use **dotenv/config** as requirement in the file but it's give me an error **"could not be found"** 

i have an **"env"** file in a **config folder**, but i did add **_".env"_** i the root dir, but still not working :(

.graphqlrc.yml
```yml
projects:
  require: dotenv/config
  default:
    schema: ./prisma/prisma.yml
    extensions:
      codegen:
        generates:
          ./src/generated/prisma.graphql:
            plugins:
              - schema-ast

```

prisma.yml

```yml
endpoint: ${env:PRISMA_ENDPOINT}
datamodel: datamodel.graphql
secret: ${env:PRISMA_SECRET}

```
