### DISCUSSION TITLE
Import types preset not importing types

### DISCUSSION THREAD

**Discussion by MadDeveloper** [dotansimha/graphql-code-generator#4830] [General] [answered]
Hi all, and first of all thank a lot for your job!

I think I am facing an issue with the `import-types` preset, as types are just not imported at all in other generated types files.
Here is my `codegen.yml` file:

```yml
schema: ./src/**/*.graphql

hooks:
  afterAllFileWrite:
    # Format files
    - prettier --write

generates:
  # Schema types
  ./src/graphql/schema-types.ts:
    config:
      scalars:
        Date: Date
    plugins:
      - typescript

  # Resolvers types
  ./src/graphql/resolvers-types.ts:
    preset: import-types
    presetConfig:
      typesPath: ./schema-types
    plugins:
      - typescript-resolvers

  # Models types
  ./src/database/models-types.ts:
    preset: import-types
    presetConfig:
      typesPath: ./../graphql/schema-types
    plugins:
      - typescript-mongodb:
          dbTypeSuffix: Database
          dbInterfaceSuffix: Database
          enumsAsString: false
```

In `./src/graphql/resolvers-types.ts` and `./src/database/models-types.ts` files I can see the use of `Types.` or other types/interfaces declared in `./src/graphql/schema-types.ts`, but there is no import on this.

Am I doing something wrong?

**Context :**

```json
{
    "@graphql-codegen/cli": "1.17.10",
    "@graphql-codegen/import-types-preset": "1.17.9",
    "@graphql-codegen/typescript": "1.17.10",
    "@graphql-codegen/typescript-resolvers": "1.17.10",
    "@graphql-codegen/typescript-mongodb": "1.17.8"
}
```

Is it a version problem/incompatibility?

Thank you for your help.
