### DISCUSSION TITLE
Monorepo use import-types

### DISCUSSION THREAD

**Discussion by ITSWYoo** [dotansimha/graphql-code-generator#4874] [General] [answered]
```bash
- common
  - generated
- serivce
  - generated
```

* codegen.yml
```yml
overwrite: true
schema: '../server/graphql/schema/**/*.gql'
documents: '../(common|service)/graphql/documents/**/*.gql'
generates:
  ../common/generated/graphql.ts:
    plugins:
      - add: // DO NOT EDIT DIRECTLY
      - add: /* eslint-disable */
      - typescript
      - typescript-operations
  generated/graphql.ts:
    preset: import-types
    presetConfig:
      typesPath: common/generated/graphql
    plugins:
      - add: // DO NOT EDIT DIRECTLY
      - add: /* eslint-disable */
      - typescript-react-apollo
    config:
      gqlImport: '@apollo/client#gql'
      withHooks: true
      withComponent: false
      withHOC: false
      reactApolloVersion: 3
      documentVariableSuffix: DocumentQuery
  generated/fragmentMatcher.json:
    plugins:
      - fragment-matcher
    config:
      apolloClientVersion: 3
```
* log
![image](https://user-images.githubusercontent.com/16359727/95452837-d6ebdb80-09a4-11eb-8379-deb7571ee806.png)

help me plz : (
