### DISCUSSION TITLE
How to use import-types & typescript-resolver

### DISCUSSION THREAD

**Discussion by ITSWYoo** [dotansimha/graphql-code-generator#4877] [General]
```yml
generates:
  types.ts:
    plugins:
      - typescript
  resolvers.ts:
    preset: import-types
    presetConfig:
      typesPath: types.ts
    plugins:
      - typescript-resolvers
```

but `resolver.ts` is not import types

![image](https://user-images.githubusercontent.com/16359727/95506602-13422a80-09eb-11eb-91de-59ac11e063c8.png)

help me plz
