### DISCUSSION TITLE
Why do descriptions not get set with hashtag (#) when config commentDescriptions ist true?

### DISCUSSION THREAD

**Discussion by jwittekind** [dotansimha/graphql-code-generator#4926] [General] [answered]
When i set my config property commentDescriptions to true, all my comments and descriptions in the generated schema.graphql remain """

Unfortunately my phpstorm graphql plugin is unable to parse those descriptions and throws errors in my IDE.

I'm trying to find a workaround by setting
descriptions: false 
schemaDescription: false

the """ descriptions are still appearing in my generated schema.graphql afterwards

```
# codegen.yml
overwrite: true
generates:
    libs/core/graphql/schema.graphql:
        schema:
            - http://my-graphql-api.com/graphql
        plugins:
            - schema-ast
        config:
            descriptions: false
            includeDirectives: true
            commentDescriptions: true
            declarationKind:
                union: type
                type: interface
                input: interface
                scalar: interface
                arguments: interface
                interface: interface
            clientSchema: ./libs/core/graphql-local/local-schema.graphql
```
