### DISCUSSION TITLE
generated types using interfaces

### DISCUSSION THREAD

**Discussion by kcornn** [dotansimha/graphql-code-generator#4982] [General] [answered]
hello! my project schema is trying to utilize interfaces as below:

```
interface IFoo {
  foo: String!
}

type Foo implements IFoo {
  foo: String!
  test: String!
}
```

and the generated type being like

```
export type Foo = IFoo & {
  __typename?: 'Foo';
  foo: Scalars['String'];
  test: Scalars['String'];
};
```

codegen.yml:

```
config:
      avoidOptionals: true
      namingConvention: keep
    plugins:
      - typescript
      - typescript-resolvers:
          defaultMapper: Partial<{T}>
```

would anyone know of a config in `codegen.yml` that would have the resulting type truly extend `IFoo` instead of using `&`? (i get then when using the default `codegen.yml` here as well as the `codegen.yml` mentioned above https://graphql-code-generator.com/#live-demo)

any suggestions would be appreciated! :)
