### DISCUSSION TITLE
typescript-operations, I want to use query result interface

### DISCUSSION THREAD

**Discussion by SmileJayden** [dotansimha/graphql-code-generator#4990] [General] [answered]
![image](https://user-images.githubusercontent.com/54968271/97288839-c20ab580-1889-11eb-9bf0-2de5246ac21a.png)

I want to use code in other script file, so I try to export that blue-roomed part. I try to find plugin config option which can export that blue part separately, but I cannot find.

Crying and eating mustard, I import this by `export type Publication = Omit<GetPublicationQuery['publication'], '__typename'>;` this way.

Is there any way to import/export that blue part directly from generated file?

thanks in advance! 

Below is my codegen.yml
```
generates:
  lib/generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      reactApolloVersion: 3
      avoidOptionals: true
      withHooks: false
      withHOC: false
      withComponent: false
      skipTypename: false
      exportFragmentSpreadSubTypes: true
      flattenGeneratedTypes: true
      documentMode: graphQLTag
```
