### DISCUSSION TITLE
Don't generate Scalars and Maybe for typescript

### DISCUSSION THREAD

**Discussion by ywongweb** [dotansimha/graphql-code-generator#5051] [Q&A] [answered]
Given a GraphQL definition of:
```
nextBranchIds: [String]!
```

codegen outputs:
```
nextBranchIds: Array<Maybe<Scalars['String']>>
```

===================

**Anyone knows if there is a way to make it output the below, thanks.**
```
nextBranchIds: Array<string>
```

**Comment by dotansimha** [comment, marked as answer]
You can use `preResolveTypes: true`. It removes some of that, but not all. We hope to improve that in the future!

**Reply by ciekawy** [reply]
With the below config (I'm using `preResolveTypes: true`) I still see `Maybe<Scalars<>>` everywhere in the types...

```
schema: ./schema.graphql
documents: src/app/**/*.graphql
config:
  preResolveTypes: true
generates:
  ./src/app/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-apollo-angular
    config:
      preResolveTypes: true
```
