### DISCUSSION TITLE
Different operation types with same name?

### DISCUSSION THREAD

**Discussion by jrnxf** [dotansimha/graphql-code-generator#5132] [Q&A] [answered]
Is it possible to have different operations with the same name? I have my project structured as so:

```
qraphql/
├─ fragments/
├─ queries/
│  ├─ games.gql
├─ mutations/
├─ subscriptions/
│  ├─ games.gql
```

Within `queries/games.gql` I have:

```
query Games {
  games {
    id
  }
}
```

and within `subscriptions/games.gql` I have:

```
subscription Games {
  games {
    id
  }
}
```

Now when I try to run the graphql-codegen I get `Not all operations have an unique name`. Earlier I had my operation names specific with `GamesQuery` and `GamesSubscription`, but that generated types like `GamesQueryQuery` and `GamesSubscriptionSubscription`, so I thought removing the operation suffix would solve the issue but then encountered this.

Am I missing a config somewhere?

This is what I currently have:
```
schema:
  http://localhost:8080/v1/graphql:
    headers:
      x-hasura-admin-secret: ${HASURA_GRAPHQL_ADMIN_SECRET}
documents:
  - ./src/**/*.gql
overwrite: true
generates:
  ./src/types.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      skipTypename: false
      withHooks: true
      withHOC: false
      withComponent: false
  ./graphql.schema.json:
    plugins:
      - introspection
```
