### DISCUSSION TITLE
Got [object Object] instead of property name in generated typescript types file

### DISCUSSION THREAD

**Discussion by thangkieu** [dotansimha/graphql-code-generator#5225] [Q&A] [answered]
Hi all,

I'm facing an issue while generate graphql
```
export type CommitmentAttributesFragment = (
  { __typename?: 'CommitmentType' }
  & Pick<CommitmentType, '[object Object]' | '[object Object]' | '[object Object]' | '[object Object]' | '[object Object]' | '[object Object]' | '[object Object]'>
  & { refCurrency?: Maybe<(
    { __typename?: 'RefCurrencyType' }
    & Pick<RefCurrencyType, '[object Object]' | '[object Object]' | '[object Object]'>
  )>, refApprovingAuthority?: Maybe<(
    { __typename?: 'RefApprovingAuthorityType' }
    & Pick<RefApprovingAuthorityType, '[object Object]' | '[object Object]'>
  )> }
);
```
all the props are [object Object] instead of prop name such as: id, name,...
I'm not sure whether it is BE bug or graphql generator itself, does anyone face the same issue? I need your help please.

packages
```
"graphql": "15.3.0",
"@graphql-codegen/cli": "1.17.8",
"@graphql-codegen/introspection": "1.17.8",
"@graphql-codegen/typescript": "1.17.9",
"@graphql-codegen/typescript-operations": "1.17.8",
"@graphql-codegen/typescript-react-apollo": "2.0.6",
```
codegen.yml
```
overwrite: true
generates:
  ./src/__generated__/types.tsx:
    schema:
      - 'url':
          headers:
            Authorization: 
            Referer: 
    documents:
      - '../pipeline/src/**/*.{graphql,gql}'
      - '../staff-tracker/src/**/*.{graphql,gql}'
      - '../compass/src/**/*.{graphql,gql}'
      - '../people-pipe/src/**/*.{graphql,gql}'
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withComponent: false
      withHOC: false
      withMutationFn: false
      withHooks: false
```

My teammate can generate it without any issue.

Thank you so much
