### DISCUSSION TITLE
Any documentation on how to get this working with apollo-upload-client?

### DISCUSSION THREAD

**Discussion by joshbedo** [dotansimha/graphql-code-generator#5320] [Q&A] [answered]
Can't seem to get this working with apollo-upload-client. any documentation around connecting the two?

**Comment by ardatan** [comment]
I don't think any special configuration needed for uploading.

**Comment by joshbedo** [comment]
Can't seem to use the `Upload Scalar` type even when it's defined in `codegen.yml`. For example the below example complains it can't find `Upload` so I tired adding it to codegen. I've also seen someone suggest using a `File` scalar if it's for the client but that doesn't seem to work either.

```
mutation uploadFile($file: Upload!) {
  uploadFile(file: $file) {
    url
  }
}
```

```
overwrite: true
schema: "http://localhost:4000/graphql"
documents: "src/gql/*.graphql"
generates:
  src/gql/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withHOC: false
      withComponent: false
      withHooks: true
      reactApolloVersion: 3
      scalars:
        Upload: FileUpload
```
