### DISCUSSION TITLE
Setup of typescript-react-apollo and typed-document-node

### DISCUSSION THREAD

**Discussion by deckchairlabs** [dotansimha/graphql-code-generator#5325] [Q&A] [answered]
Hello!

Just trying to use the document output generated by `typed-document-node` in my generated Apollo hooks. The relevant codegen config  and generated hook output is below.

```yaml
generates:
  app/src/generated/operations.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typed-document-node"
    config:
      flattenGeneratedTypes: true
      preResolveTypes: true
  
  app/src/generated/graphql.ts:
    config:
      documentMode: "external"
      importDocumentNodeExternallyFrom: "./operations"
      importOperationTypesFrom: "Operations"
    plugins:
      - "typescript-react-apollo"
```

```ts
export function useBootstrapQuery(
  baseOptions?: Apollo.QueryHookOptions<
    Operations.BootstrapQuery,
    Operations.BootstrapQueryVariables
  >
) {
  return Apollo.useQuery<
    Operations.BootstrapQuery,
    Operations.BootstrapQueryVariables
  >(Operations.Bootstrap, baseOptions)
}
```

The problem I'm having is that the `typescript-react-apollo` plugin isn't adding the `Document` suffix to `Operations.Bootstrap`.

Is there a configuration option I'm missing?

Thank you in advance!
