### DISCUSSION TITLE
Can a step in codegen.yml wait for another one to finish?

### DISCUSSION THREAD

**Discussion by borekb** [dotansimha/graphql-code-generator#5529] [Q&A] [answered]
We have a `codegen.yml` like this:

```yaml
generates:
  schema.graphql:
    schema: ./graphql-server/index.ts
    plugins:
      - schema-ast

  clientTypes.ts:
    schema: ./schema.graphql
    documents: ./gqls/*.ts
    plugins:
      - typescript
      - typescript-operations
```

It sort of works, mostly after `schema.graphql` has been generated once, but if I delete this file the codegen will fail.

Is something like this possible?

```yaml
generates:
  schema.graphql:
    schema: ./graphql-server/index.ts
    plugins:
      - schema-ast

  clientTypes.ts:
    # Name of the step that should finish first:
    dependsOn: schema.graphql
    
    schema: ./schema.graphql
    documents: ./gqls/*.ts
    plugins:
      - typescript
      - typescript-operations
```
