### DISCUSSION TITLE
Generate resolver return types of the same shape as the client graphql query/mutation

### DISCUSSION THREAD

**Discussion by trompx** [dotansimha/graphql-code-generator#5637] [Q&A] [answered]
Hello,

**TL;DR**: I would like to generate the resolver return types that match the queries and mutations I execute client side but don't know if this is possible?

---

I started using graphql-code-generator but am having an issue with my return response types when trying to return non full model, but only partial.

User model:
```ts
@ObjectType({ implements: BaseEntity })
export class User extends BaseEntity {
  @Field({ nullable: true })
  name?: string;

  @Field({ nullable: true })
  job?: Job;
}
```

Job model:
```ts
@ObjectType({ implements: BaseEntity })
export class Job extends BaseEntity {
  @Field()
  name: string;

  @Field()
  category: string;
}
```

Client side I execute a query that should return:
```graphql
fragment User on User {
  id
  name
  job {
    name
  }
}

query GetUsers {
  getUsers {
    ...User
  }
}

```

In my resolver I do a raw query that return exactly the data returned by the graphql query.
```ts
  @Query(() => [User], { nullable: true })
  getUsers(): Promise<User[]> {
    // Sql query that returns all users with only their id, name and job name.
    return users =  ...
  }
```

The problem is as I return User[] from the promise, it excepts a full User entity, thus throwing the error: **Cannot return null for non-nullable field Job.category.**
It tried to return `UserFragment[]` instead generated via typescript-resolver, but I get the following error **'UserFragment' only refers to a type, but is being used as a value here.**. Besides in most of my queries, I return multiple fragments + partial data from other models and I'd like to just auto generate the type for the whole query.

I don't know if I am missing something but it doesn't seem that codegen generated types directly for the whole GetUsers query, something like `GetUsersResponseType`, am I right? So do I have to always create **partial object types** so that I can use it in my resolvers?

Thanks in advance for the help.

**Comment by dotansimha** [comment, marked as answer]
You can use `mappers` configuration and use any kind of type/class that you wish. see: https://the-guild.dev/blog/better-type-safety-for-resolvers-with-graphql-codegen

**Reply by trompx** [reply]
Thanks for the useful resource @dotansimha.
After reading the article, I'm not sure if it supports my usecase.

As explained before, let's say I have:
```graphql
# ./src/graphql/user/fragments/ApiUser.graphql
fragment ApiUser on User {
  id
  name
  job {
    name
  }
}

# ./src/graphql/role/fragments/ApiRole.graphql
fragment ApiRole on Role {
  id
  name
}

# ./src/graphql/user/queries/apiUsers.graphql
query ApiUsers {
  apiUsers {
    ...ApiUser
    ...ApiRole
  }
}
```

codegen.yml:
```yml
schema: http://localhost:4000/graphql
documents:
  - ./src/**/*.graphql
overwrite: true
generates:
  ../server/src/types/resolversTypes.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-resolvers"
    config:
      mappers:
        ApiUsers: ./src/graphql/user/queries/apiUsers#ApiUsers
        # Would also like to do:
        # ApiUser: ./src/graphql/user/fragments/ApiUser#ApiUser
```
Running codegen, the only thing it adds is `import { ApiUsers } from './src/graphql/user/queries/apiUsers';` to the generated resolversTypes but with the error `'ApiUsers' is declared but its value is never read.`.

I'd like to get the **type directly from my .graphql (queries, mutations and fragments)** files without redeclaring the types, and use it like:
```ts
  import ApiUsers from ../server/src/types/resolversTypes.ts:
  @Query(() => ApiUsers, { nullable: true })
  apiUsers(): Promise<ApiUsers> {
    // Sql query that returns all users with only their id, name and job name + their roles (id + name)
    return users =  ...
  }
```

Is tihis supported or I have to create a new file to declare a response type of the exact same shape as what my graphql queries/mutations/fragments return to use it in my codegen.yml as a mapper?
