### DISCUSSION TITLE
typescript-resolvers plugin subscription function have any types

### DISCUSSION THREAD

**Discussion by p-98** [dotansimha/graphql-code-generator#5661] [Q&A] [answered]
I am using the typescript-resolvers plugin to generate the types for the resolvers.

In my schema I have
```
type Subscription {
    addedBook(input: AddedBookInput!): Book!
}
```
so I tried to define my resolvers somwhat like this
```ts
const resolvers: IResolvers = {
    ...
    Subscription: {
        addedBook: {
            subscribe: ...,
            resolve: (source, args, context, info) => ...
        },
    }
}
```

I would normally expect `subscribe` and `resolve` to be fully typed but they are of type any.

Interestingly when looking in the generated file, `addedBook` is of type `SubscriptionResolver`, which is a wrapper around the following type:
```ts
export type SubscriptionObject<TResult, TKey extends string, TParent, TContext, TArgs> =
  | SubscriptionSubscriberObject<TResult, TKey, TParent, TContext, TArgs>
  | SubscriptionResolverObject<TResult, TParent, TContext, TArgs>;
```
When I comment out one of the two `Subscription*Object` types, suddenly my functions have types. I first thought `SubscriptionSubscriberObject` to be more precise since it also types the `source` parameter, but it actually gives it the following type:
```ts
(parameter) source: {
    addedBook: ResolverTypeWrapper<IBookModel>;
}
```
which is wrong. It would have to be `(parameter) source: ResolverTypeWrapper<IBookModel>`, which I checked by returning source (and everything worked fine, except for the linter and ts throwing type errors).

My codengen.yml:
```yml
overwrite: true
schema: "./server/src/schema.graphql"
generates:
    ./server/src/types/graphql.ts:
        config:
            contextType: ./models#IContext
            typesPrefix: I
            useIndexSignature: true
            mappers:
                Author: ./models#IAuthorModel
                Book: ./models#IBookModel
        plugins:
            - "typescript"
            - "typescript-resolvers"
```

Can someone explain this to me?

Thanks in advance
