### DISCUSSION TITLE
With apollo plugin, it doesn't tree-shake properly

### DISCUSSION THREAD

**Discussion by baeharam** [dotansimha/graphql-code-generator#5719] [Q&A] [answered]
When I generate types with Apollo client 3.0, I can use plugin option called `apolloReactHooksImportFrom` and I specified this as `@apollo/client/react` for tree-shaking. But, graphql-code-generator generates `import * as Apollo from '@apollo/client';` line even if it is not used in code. How can I remove this line?

```typescript
/* src/generated/graphql.tsx */

import * as Apollo from '@apollo/client'; // This is not used, but it is generated automatically.
import * as ApolloReactHooks from '@apollo/client/react';
```

**My configuration**

```yaml
overwrite: true
schema: './schema.graphql'
documents: 'src/**/queries.ts'
generates:
  src/generated/graphql.tsx:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      onlyOperationTypes: true
      preResolveTypes: true
      pureMagicComment: true
      apolloReactHooksImportFrom: '@apollo/client/react'
      gqlImport: 'graphql-tag'
      withResultType: false
```
