### DISCUSSION TITLE
Output does not generate namespaces any more

### DISCUSSION THREAD

**Discussion by mbrochh** [dotansimha/graphql-code-generator#5725] [Q&A]
Let's say I have some code like this in a React app:

```
import gql from 'graphql-tag'
import { useQuery } from '@apollo/client'

const query = gql`
  query DummyViewQuery {
    currentProfile {
      id
    }
  }
`
```

Before v1 my codegen config looked like this:

```
overwrite: true
schema: 'schema.json'
documents: ['src/fragments.ts', 'src/queries.ts', 'src/**/*.tsx']
generates:
  src/generated/graphql.tsx:
    plugins:
      - 'typescript-common'
      - 'typescript-client'
      - 'typescript-server'
      - 'typescript-react-apollo'
      - 'fragment-matcher'
```

After the upgrade to v1, now my config looks like this:

```
overwrite: true
schema: 'schema.json'
documents: ['src/fragments.ts', 'src/queries.ts', 'src/**/*.tsx']
generates:
  src/generated/graphql.tsx:
    config:
      globalNamespace: true
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
```

When I run `gql-gen --config codegen.yml`, that `DummyViewQuery` from above will end up in the generated file like this:

```
export type DummyViewQueryQuery = (
 )
```

Before v1 it got generated like this:

```
export namespace DummyViewQuery {
  ...
  export type Query = {
```

Basically, I guess what I would like to know is if there is some setting that would allow me to get the generated output with namespaces again, as it used to be.
