### DISCUSSION TITLE
Duplicated Typings

### DISCUSSION THREAD

**Discussion by Manubi** [dotansimha/graphql-code-generator#5817] [Q&A] [answered]
Hi,
I am fetching the schema from a postGraphile backend. But the thing is I get several duplicate errors in the `types.generated.ts`
I am trying to get the urql useHooks to generate. :)

Do yo have any advice how to fix it? Thanks!

```
overwrite: true
schema: "http://localhost:3000/api/graphql"
documents:
  - "src/graphql/*.graphql"
generates:
  src/graphql/types.generated.ts:
    plugins:
      - typescript
  ./:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: src/graphql/types.generated.ts
    plugins:
      - typescript-operations
      - typescript-urql
config:
  namingConvention:
    enumValues: keep
  scalars:
    DateTime: "string"
    JSON: "{ [key: string]: any }"
```
```
package.json
  "devDependencies": {
    "@graphql-codegen/cli": "1.21.3",
    "@graphql-codegen/near-operation-file-preset": "^1.17.13",
    "@graphql-codegen/plugin-helpers": "^1.18.4",
    "@graphql-codegen/typed-document-node": "^1.18.4",
    "@graphql-codegen/typescript": "^1.21.1",
    "@graphql-codegen/typescript-operations": "1.17.15",
    "@graphql-codegen/typescript-urql": "^2.0.5",
    "@tailwindcss/postcss7-compat": "^2.1.0",
    "@types/react-router-dom": "^5.1.7",
    "autoprefixer": "^9.8.6",
    "postcss": "^7",
    "tailwindcss": "npm:@tailwindcss/postcss7-compat"
  }
```
