### DISCUSSION TITLE
Please make sure that your codegen config file contains either the "schema" field

### DISCUSSION THREAD

**Discussion by softshipper** [dotansimha/graphql-code-generator#5901] [Q&A] [answered]
Hi all 

Running `npm run codegen` command I have got the following error message:

```
  ✖ Parse configuration
    → Invalid Codegen Configuration!
    Generate outputs
  Invalid Codegen Configuration!

        Please make sure that your codegen config file contains either the "schema" field 
        or every generated file has its own "schema" field.
        
        It should looks like that:
        schema:
          - my-schema.graphql

        or:
        generates:
          path/to/output:
            schema: my-schema.graphql
```

the content of the `codegen.yml`:
```
overwrite: true
generates:
  ./generated/provider.ts:
    documents: "graphql/providers/**/*.graphql"
    schema: "http://localhost:4000"
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
  ./graphql.schema.json:
    plugins:
      - "introspection"
```
What am I doing wrong?   

Thanks
