### DISCUSSION TITLE
C# decimals

### DISCUSSION THREAD

**Discussion by bugproof** [dotansimha/graphql-code-generator#5936] [Q&A] [answered]
I would like to generate C# code that supports `Decimal` scalar. Is it possible?

**Comment by bugproof** [comment, marked as answer]
Ok, I think I figured it out...
https://www.graphql-code-generator.com/docs/plugins/c-sharp

It was just not documented that well :)

```
generates:
  src/main/c-sharp/my-org/my-app/Types.cs:
    plugins:
      - c-sharp
    config:
      scalars:
        Decimal: decimal
```
