### DISCUSSION TITLE
react hooks not being created?

### DISCUSSION THREAD

**Discussion by acomito** [dotansimha/graphql-code-generator#5969] [Q&A] [answered]
My package.json

```
{
  "name": "js",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@graphql-codegen/cli": "^1.20.1",
    "@graphql-codegen/typescript": "^1.21.0",
    "@graphql-codegen/typescript-operations": "^1.17.14",
    "@graphql-codegen/typescript-react-apollo": "^2.2.1",
    "@graphql-codegen/typescript-resolvers": "^1.18.2",
    "graphql": "^15.5.0"
  },
  "scripts": {
    "codegen": "yarn graphql-codegen"
  }
}


```

and yml

```
overwrite: true
schema: 'http://localhost:8080/graphql'
generates:
  backend/src/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-resolvers
    hooks:
      afterOneFileWrite:
        - prettier --write
  frontend/src/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: true
    hooks:
      afterOneFileWrite:
        - prettier --write

```

It creates the files and types but no hooks. Any ideas?

**Comment by acomito** [comment, marked as answer]
Ah, the documents field is required to get the hooks

```
overwrite: true
schema: 'http://localhost:8080/graphql'
documents: 'frontend/src/ApolloClient/*/*'
generates:
  backend/src/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-resolvers
    hooks:
      afterOneFileWrite:
        - prettier --write
  frontend/src/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: true
    hooks:
      afterOneFileWrite:
        - prettier --write

```
