### DISCUSSION TITLE
Is there a way to specify `enumValues` while using `graphql-modules` preset?

### DISCUSSION THREAD

**Discussion by mm-wang** [dotansimha/graphql-code-generator#5984] [Q&A]
Hello! I'm using the code generator with the `graphql-modules` preset, and trying to set up a resolver that will return a different value for an enum. If I use `enumValues` and map to the enum that I want, the resolver is generated in the `baseTypesPath` file but not in the `filename` file for each module. Given that, I suspect I'd have to import that type in from the `baseTypesPath` file. Is that the way to do it? Is there another way to specify `enumValues` while using that preset?

**Comment by dotansimha** [comment]
Hi @mm-wang ! 
When dealing with `typescript-resolvers` plugin (it's the one that graphql-modules preset uses internally), you should use `mappers` to configure external types. It's more robust and fits better when you need to customize a type.

We have a standard for creating `mappers` and it also automatically manages the imports for you.

Here are a few examples:

```yml
config:
  mappers: 
     MyEnum: './file#Test' # type Test from ./file
     MyType1: string # map to a custom primitive 
     MyType2: 'MyNamespace.MyType' # map to namespace
     MyType3: '{}' # map to an inline TS type
     MyType4: 'A | B' # map to multiple types
     MyType5: 'libphonenumber-js#PhoneNumber as ParsedPhoneNumber'  # super custom mapping
```


Basically, anything you specify before `#` will be the source of the import, and the identifier comes after the `#`.  If you use an explicit name without a source, you can use `add` plugin in addition, in order to add custom imports:

```yaml
      ./server/src/modules/:
        preset: graphql-modules
        presetConfig:
          baseTypesPath: ../generated-types/graphql.ts
          filename: generated-types/graphql.ts
          encapsulateModuleTypes: namespace
        config:
          mappers:
              MyCustom: 'JustIdentifier'
        plugins:
          - add:
              content: |
                import { JustIdentifier } from "custom";
          - typescript
          - typescript-resolvers
```

You can read more here:
- https://www.graphql-code-generator.com/docs/plugins/typescript-resolvers#use-your-model-types-mappers
- https://the-guild.dev/blog/better-type-safety-for-resolvers-with-graphql-codegen

**Reply by mm-wang** [reply]
Thank you so much for this great overview! I appreciate the fast response! I have tried implementing this both only with `config → mappers` and `plugins → add`, and I think the main issue is still that I get the type from the baseTypesPath file, and not from the file within each module. 

So, expanding on the `JustIdentifier` example, assuming it's a file in `myModule → enums → custom`, say that I have the following setup:

```
- src
    - generated-types
        - graphql.ts
    - modules
        - myModule
            - enum
                - custom.ts # file with the custom enum types
            - resolvers.ts
            - generated-types
                - types.ts # generated types for the module
```
and a .yml file of
```
generates:
  ./src/modules/:
    config:
      useIndexSignature: true
      mappers:
        custom: ../src/modules/myModule/enum/custom#JustIdentifier
    preset: graphql-modules
    presetConfig:
      baseTypesPath: ../generated-types/graphql.ts # types for entire schema
      filename: generated-types/types.ts # types for each module
      encapsulateModuleTypes: namespace
    plugins:
      - typescript
      - typescript-resolvers
```
then I get that `JustIdentifer` exists in the top level resolvers, but not in the module as part of the resolvers.

This means that I import my external types from the `.../generated-types/graphql.ts` file instead of from the module. I was hoping for some more customization on the module by module basis. But I can import my external types from the larger file, so in the meantime I can go ahead.
