### DISCUSSION TITLE
graphql-code-generator with dynamic typescript typeDefs

### DISCUSSION THREAD

**Discussion by Manest** [dotansimha/graphql-code-generator#6028] [Q&A] [answered]
My condegen.yml looks like that:

```
overwrite: true
schema:
  - 'src/graphql/projects/typeDefs.ts' 
generates:
  src/models/graphql.ts:
    plugins:
      - 'typescript'
```

I have a file containing some schemas :

```
   const typeDefs = /* GraphQL */ `
(...)
      extend type RootSubscription {
        update(key: String): String
      }
(...)
    `;
```
This use case work well. That generate the typing correctly.

Now if I have some dynamic stuff like that:

```
 const typeDefs = /* GraphQL */ `
(...)
      extend type RootSubscription {
        ${OPERATION_TYPE.UPDATE}(key: String): String
      }
(...)
    `;
```
graphql-code-generator is failling with this error :

```
Failed to load schema from src/graphql/projects/typeDefs.ts: 
        Syntax Error: Expected Name, found "(".
        GraphQLError: Syntax Error: Expected Name, found "(".
```

Any idea how to make it works?

Thanks
