### DISCUSSION TITLE
generating code without custom scalars

### DISCUSSION THREAD

**Discussion by FBurner** [dotansimha/graphql-code-generator#6106] [General]
Hi, is it possible to generate code without custom scalars and the maybe type its rather irritating than helpful?

**Comment by akafaneh** [comment]
What do you mean without custom scalar?

Regarding the `Maybe` type you can always override it into whatever you like, the following config override the `Maybe` to just return the type as is, no `null` or `undefined`
```yml
generates:
 path/to/file.ts:
   plugins:
     - typescript
   config:
    #maybeValue: T | null | undefined
     maybeValue: T
```
