### DISCUSSION TITLE
Custom scalar that maps to arbitrary type?

### DISCUSSION THREAD

**Discussion by spencerwilson** [dotansimha/graphql-code-generator#6181] [Q&A] [answered]
Hello,

I'm wondering if there's a way to use `@graphql-codegen/cli`'s custom scalar support with an arbitrary, non-globally-defined type. E.g.,
```yaml
config:
  scalars:
    Foo: MyExoticScalar  # not just `any`, or `string`, etc.
```

But when compiled, `tsc` rejects the resulting .ts file due to
```
src/generated/graphql.ts:15:9 - error TS2304: Cannot find name 'MyExoticScalar'.

15   Foo: MyExoticScalar;
          ~~~~~~~~~~~~~~
```

Alternatively, if I omit the `ScalarsMap` shown above altogether, the default behavior is akin to if I'd given the following `ScalarsMap`:
```yaml
config:
  scalars:
    Foo: any
```

...which is unappealing for reasons of being weakly typed.

Is there some `@graphql-codegen/cli` config I'm missing that would "teach" it add some `import` statements to emitted TypeScript modules so that they contain all the names they need to in order to be valid? Thanks in advance.

**Comment by dotansimha** [comment, marked as answer]
@spencerwilson sure! we support a format like this: 

```yaml
scalars:
  Upload: 'graphql-upload#FileUpload'
```

(it's `PACKAGE_NAME#IDENTIFIER_NAME`)

In more complex use-cases, you can use the identifier name and use `add` plugin, for example:

```yaml
config:
  MyGqlType: 'A'
plugins:
  - add:
      content: "import A from 'somewhere'";
  - typescript
```
