### DISCUSSION TITLE
graphql generated types in separate package

### DISCUSSION THREAD

**Discussion by woss** [dotansimha/graphql-code-generator#6186] [Q&A]
I'm using the monorepo where my client and other microservices use the same `graphql` package. to get the best out of the TS i compile the `ts` files to get the declaration files which fail if I don't have the `@apollo/client` installed.  On the other hand if I have the `@apollo/client` installed in the `graphql` package then the react based client app fails with the following error:

```
Uncaught Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an <ApolloProvider>, or pass an ApolloClient instance in via options.
```

What should I do?

My current flow is when I change the `LocalSchema` i install the `@apollo/client` then build the files then uninstall it. this is painful, really painful :) 

Source code files provided below:

the codegen.yml looks like this:

```yml
overwrite: true
schema:
  - '../../client/app/src/graphql/LocalSchema.graphql'
  - '../../../data/schema.graphql'
documents: '../../**/src/**/*.graphql'
config:
  scalars:
    Datetime: 'string'
    JSON: '{ [key: string]: any }'
generates:
  index.tsx:
    plugins:
      - add:
          content: '/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */'
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withHOC: false
      withComponent: false
      withHooks: true
      withMutationFn: true
      withRefetchFn: true
  nodes.ts:
    plugins:
      - add:
          content: '/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yml` */'
      - typescript
      - typescript-operations
      - typescript-document-nodes
      - typescript-graphql-request
    config:
      # noGraphQLTag: false
      rawRequest: true
```
and the structure looks like this:

```bash
❯ tree -L 1
.
├── codegen.yml
├── index.d.ts
├── index.js
├── index.js.map
├── index.tsx
├── node_modules
├── nodes.d.ts
├── nodes.js
├── nodes.js.map
├── nodes.ts
├── package.json
├── README.md
├── tsconfig.json
└── tsconfig.tsbuildinfo
```
