### DISCUSSION TITLE
Missing typeof Scalars from repo graphql-scalars?

### DISCUSSION THREAD

**Discussion by dan-lutd** [dotansimha/graphql-code-generator#6377] [Q&A]
I get a gen-types.ts with the imports
```
import { GraphQLDateTime } from 'graphql-scalars';
import { GraphQLEmailAddress } from 'graphql-scalars';
import { GraphQLJSON } from 'graphql-scalars';
```
but shows them as unused until next step

And the Scalars
```
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  Date: any;
  DateTime: GraphQLDateTime;
  EmailAddress: GraphQLEmailAddress;
  JSON: GraphQLJSON;
  JSONObject: any;
  URL: any;
};
```
it throws the type error in VSCode 
`'GraphQLDateTime' refers to a value, but is being used as a type here. Did you mean 'typeof GraphQLDateTime'? ts(2749)`

So I can change them to 
```
  DateTime: typeof GraphQLDateTime;
  EmailAddress: typeof GraphQLEmailAddress;
  JSON: typeof GraphQLJSON;
```

  
   ```
const apollo = new ApolloServer({
      typeDefs: schema, 
```

My codegen.yaml :
```
  overwrite: true
  schema: ["./src/global/**/schema/*.ts","./src/features/**/*.schema.ts"]
  documents: null
  config: 
    defaultMapper: any
    useIndexSignature: true
    scalars:
        DateTime: graphql-scalars#GraphQLDateTime
        EmailAddress: graphql-scalars#GraphQLEmailAddress
        JSON: graphql-scalars#GraphQLJSON
  generates:
    src/gen-types.ts:
      plugins: 
        - typescript
        - typescript-resolvers
```
