### DISCUSSION TITLE
Cannot find Fragment

### DISCUSSION THREAD

**Discussion by TomWebbio** [dotansimha/graphql-code-generator#6462] [Q&A]
Hi,

I've been struggling to implement the code generator because whenever I split my graphql files up into fragments, the generated code gives Typescript errors that it cannot find the fragment.

![image](https://user-images.githubusercontent.com/48241143/128868562-d7845fac-afaa-4d06-9d97-d9939c2bb4c5.png)

![image](https://user-images.githubusercontent.com/48241143/128868971-b09c8659-fa61-40f8-bb9b-5e990a0066c3.png)

Does anyone know how I can fix this? My graphql files look like this:

home-page.graphql:
```
query GetHomePage {
	homePage {
		...HomePageFields
	}
}
```
home-page.fragment.graphql:
```
fragment HomePageFields on HomePage {
	id
	title
	locale
}
```

My codegen.yml file looks like this:

```
overwrite: true
schema: 'http://strapi.tst.gelderland.nl/api/graphql'
documents:
  - 'api/queries/**/*.graphql'
generates:
  api/graphql.tsx:
    plugins:
      - typescript
      - typescript-operations
      - apollo-next-ssr
      - fragment-matcher
    config:
      reactApolloVersion: 3
      withHOC: false
      preResolveTypes: true
      flattenGeneratedTypes: true
hooks:
  afterAllFileWrite:
    - prettier --write
```
