### DISCUSSION TITLE
GraphQL code generator not generating code

### DISCUSSION THREAD

**Discussion by CrispenGari** [dotansimha/graphql-code-generator#6538] [General]
I've a `codegen.yml` that looks a follows:

```yml
overwrite: true
schema: http://localhost:3001/graphql
documents: "./src/graphql/**/*.graphql"
generates:
./src/generated/graphql.tsx:
  plugins:
    - typescript
    - typescript-operations
    - typescript-react-apollo
  config:
    withHooks: true
```

I have a  script in the package.json that looks as follows:

```json
  "scripts": {
...
    "generate": "graphql-codegen"
  }
```

This is my folder structure:

```
- root
     - package.json
     - codegen.yml
     - src
         - generated
         - graphql
            - mutations
               - login.grahql
            - queries
```
The `login.grahql` looks as follows:

```grahql
query{
  user{
    username
    createdAt
    email
    id
    isLoggedIn
    fullName
    firstName
    lastName
  }
}
```
When i run

```shell
$ yarn generate
```
I get
```shell
yarn run v1.22.10
$ graphql-codegen
Done in 12.10s.
```
But I don't see any generated `code`. I was following [the docs](https://www.graphql-code-generator.com/docs/plugins/typescript-react-apollo). What may be possibly my problem. 

### And also when I try to add the `config`  `withHooks` in the `yml` file as follows my VsCode will be mad at me saying `Property  is not allowed.yaml-schema: https://www.graphql-code-generator.com/config.schema.json`

```yml
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
      config:
        withHooks: true # Property  is not allowed.yaml-schema: https://www.graphql-code-generator.com/config.schema.json
```

**Comment by dotansimha** [comment]
You have an indentation issue with `config`, it should be:

```
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withHooks: true
```
