### DISCUSSION TITLE
Partial Schema Resolution ☀️

### DISCUSSION THREAD

**Discussion by mattcogent** [dotansimha/graphql-code-generator#6572] [Q&A] [answered]
Hey there 👋

I'm working with a Federated Graph and schema is large. I am generating types for a React app using apollo. Is it possible to only generate GraphQL schema types based on my frontend documents? My goal is to reduce the size of the generated graphql file and only use what we need.

Here is my codegen file 👇
```
overwrite: true
schema: 'http://localhost:8080/graphql'
documents: 'src/@graphql/**/*.graphql'
generates:
  src/@graphql/index.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withHooks: true
      federation: true
```

Thanks
