### DISCUSSION TITLE
no operationName in query

### DISCUSSION THREAD

**Discussion by JoakimThorne** [dotansimha/graphql-code-generator#6580] [Q&A] [answered]
Hi,

Im trying to implement hooks using this generator. 
I run msw for testing but it cant find the queries correctly since when I generate my hooks and types I dont get a operationName. 
So all my queries only fire with the schema and the variables in the body. 
msw needs operationName to map the request.

my settings

```
overwrite: true
schema: 'http://localhost:8080/api/v2/graphql'
documents: 'src/**/*.graphql'
generates:
    src/generated/graphql.ts:
        plugins:
            - 'typescript'
            - 'typescript-operations'
            - 'typescript-react-query'
            - add:
                  content: "import { endpointUrl } from '../graphql-endpoint-config';"
        config:
            exposeQueryKeys: true
            fetcher:
                endpoint: 'endpointUrl'

```
