### DISCUSSION TITLE
Generating operations for C#

### DISCUSSION THREAD

**Discussion by chanan** [dotansimha/graphql-code-generator#6666] [General]
Hi,

I am trying to create a "generic" client for GraphQL API, not based on any specific "gql" queries. Is there a way to generate C# Operations based on the queries in the Query and Mutation types in the schema.grqphql?

i.e. something like this in the `codegen.yml`:

```
generates:
  Types.cs:
    schema: schema.graphql
    plugins:
      - c-sharp
    config:
      emitRecords: true
      namespaceName: Marketron
  Operations.cs:
    schema: schema.graphql
    documents: schema.graphql
    plugins:
      - c-sharp-operations
    config:
      namespaceName: Marketron

```

Where `schema.graphql` looks in part something like this:

```
type Company {
  # The id field is the same as CompanyGuid
  id: ID!
  companyName: String
  ...snip...
}

type Query {
  # Lists all the companies
  companies: [Company]
  ...snip...
}
````

My `Types.cs` is as expected. `Operations.cs` is blank because it expects to find documents with `gql` tags. So my questions is is there a way for the generator to create a `GetCompanies` based on the `Query` type in the `schema.graphql`?
