### DISCUSSION TITLE
Custom Fetcher params not visible

### DISCUSSION THREAD

**Discussion by Sahejmaharjan1** [dotansimha/graphql-code-generator#6739] [Q&A]
The generated ts file doesn't contain the given params in custom fetcher.
codegen.yml
```
schema:
  - ${GRAPHQLENDPOINT}:
documents: './src/**/*.graphql'
generates:
  ./src/generated/graphql.ts:
    plugins:
      - add:
          content: &comment '/* eslint-disable */'
      - typescript
      - typescript-operations
      - typescript-react-query
    config:
      fetcher: '../clients/customFetcher#fetcher'
```

customFetcher.ts
```
export function fetcher<TData, TVariables>(
  query: string,
  variables?: TVariables,
  authMode: keyof typeof GRAPHQL_AUTH_MODE = GRAPHQL_AUTH_MODE.AMAZON_COGNITO_USER_POOLS
) {
  return async (): Promise<TData> => {
    const operation = {
      ...graphqlOperation(query, variables),
      authMode: authMode,
    };
    const response = (await AmplifyAPI.graphql(operation)) as GraphQLResult<any>;
    return response.data;
  };
}
```
the generated ts file
```
export const useSignUpMutation = <TError = unknown, TContext = unknown>(
  options?: UseMutationOptions<SignUpMutation, TError, SignUpMutationVariables, TContext>
) =>
  useMutation<SignUpMutation, TError, SignUpMutationVariables, TContext>(
    (variables?: SignUpMutationVariables) =>
      fetcher<SignUpMutation, SignUpMutationVariables>(SignUpDocument, variables)(),
    options
  );
```
In above generated ts file the useSignUpMutation only takes options as a param.. how to get the specific params given in the customFetcher.. how to get this?

```
export const useSignUpMutation = <TError = unknown, TContext = unknown>(
  options?: UseMutationOptions<SignUpMutation, TError, SignUpMutationVariables, TContext>,
  authMode: keyof typeof GRAPHQL_AUTH_MODE = GRAPHQL_AUTH_MODE.AMAZON_COGNITO_USER_POOLS
) =>
  useMutation<SignUpMutation, TError, SignUpMutationVariables, TContext>(
    (variables?: SignUpMutationVariables) =>
      fetcher<SignUpMutation, SignUpMutationVariables>(SignUpDocument, variables,authMode)(),
    options
  );
```
