### DISCUSSION TITLE
Why fragments are ignored

### DISCUSSION THREAD

**Discussion by bclermont** [dotansimha/graphql-code-generator#6785] [General]
`codegen.yml`:

```yaml
schema:
  - http://$$$:8080/v1/graphql:
generates:
  ./src/api/generated.ts:
    documents:
      - ./src/**/*.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      enumsAsTypes: true
      useImplementingTypes: true
      arrayInputCoercion: false
      skipTypeNameForRoot: true
      declarationKind: interface
      onlyOperationTypes: true
      exportFragmentSpreadSubTypes: true
      documentNode: documentMode | documentNodeImportFragments
      withRefetchFn: true
      dedupeOperationSuffix: true
      omitOperationSuffix: true
      experimentalFragmentVariables: true
      strictScalars: true
      skipTypename: true
      nonOptionalTypename: true
      dedupeFragments: true
      InlineFragmentTypeOptions: combine
```

`myfile.graphql`:

```graphql
fragment Attendance on agent_location_attendance {
  location {
    name
  }
  locationID: location_id
  end
  hold
  id
  start
}

query ListMyAttendances {
  previous: agent_location_attendance(
    order_by: { id: desc }

    where: { end: { _is_null: false } }
  ) {
    ...Attendance
  }
  current: agent_location_attendance(
    order_by: { id: desc }
    limit: 1
    where: { end: { _is_null: true } }
  ) {
    ...Attendance
  }
}
```

i expect something like this:

```typescript
export type Attendance = {
  __typename: "agent_location_attendance";
  end?: string | null | undefined;
  hold: boolean;
  id: number;
  start: string;
  locationID: number;
  location: { __typename: "location"; name: string };
};

export type ListMyAttendances = {
  previous: Array<Attendance>;
  current: Array<Attendance>;
};
```

but I get:

```typescript
export type Attendance = {
  __typename: "agent_location_attendance";
  end?: string | null | undefined;
  hold: boolean;
  id: number;
  start: string;
  locationID: number;
  location: { __typename: "location"; name: string };
};

export type ListMyAttendances = {
  previous: Array<{
    __typename: "agent_location_attendance";
    end?: string | null | undefined;
    hold: boolean;
    id: number;
    start: string;
    locationID: number;
    location: { __typename: "location"; name: string };
  }>;
  current: Array<{
    __typename: "agent_location_attendance";
    end?: string | null | undefined;
    hold: boolean;
    id: number;
    start: string;
    locationID: number;
    location: { __typename: "location"; name: string };
  }>;
};
```

why it don't use it's own types? I tried countless of combination of settings in `codegen.yml`
