### DISCUSSION TITLE
__typename always defined

### DISCUSSION THREAD

**Discussion by bclermont** [dotansimha/graphql-code-generator#6789] [General]
`codegen.yml`:

```yaml
schema:
  - http://$$$:8080/v1/graphql:
generates:
  ./src/api/generated.ts:
    documents:
      - ./src/**/*.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      enumsAsTypes: true
      useImplementingTypes: true
      arrayInputCoercion: false
      skipTypeNameForRoot: true
      declarationKind: interface
      onlyOperationTypes: true
      exportFragmentSpreadSubTypes: true
      documentNode: documentMode | documentNodeImportFragments
      withRefetchFn: true
      dedupeOperationSuffix: true
      omitOperationSuffix: true
      experimentalFragmentVariables: true
      strictScalars: true
      skipTypename: true
      nonOptionalTypename: true
      dedupeFragments: true
      InlineFragmentTypeOptions: combine
```

`myfile.graphql`:

```graphql
fragment Attendance on agent_location_attendance {
  location {
    name
  }
  locationID: location_id
  end
  hold
  id
  start
}
```

i expect something like this:

```typescript
export type Attendance = {
  end?: string | null | undefined;
  hold: boolean;
  id: number;
  start: string;
  locationID: number;
  location: { name: string };
};
```

but I get:

```typescript
export type Attendance = {
  __typename: "agent_location_attendance";
  end?: string | null | undefined;
  hold: boolean;
  id: number;
  start: string;
  locationID: number;
  location: { __typename: "location"; name: string };
};
```

Why I get all those `__typename` if I have:

- `skipTypeNameForRoot: true`
- `skipTypename: true`
