### DISCUSSION TITLE
Unknown type despite having custom scalar specified

### DISCUSSION THREAD

**Discussion by halindraprakoso** [dotansimha/graphql-code-generator#6807] [Q&A]
Hello everyone, I need help.
I'm running introspection with hasura, but keep having this error:
```
✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/codegen.ts
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
❯ Generate ./graphql.schema.json
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate

Found 2 errors

  ✖ ./graphql.schema.json
    AggregateError: GraphQL Document Validation failed with 4 errors;
      Error 0: GraphQLDocumentError: Unknown type "date".
      Error 1: GraphQLDocumentError: Unknown type "jsonb".
      Error 2: GraphQLDocumentError: Unknown type "geography".
      Error 3: GraphQLDocumentError: Unknown type "jsonb".

  ✖ src/codegen.ts
    AggregateError: GraphQL Document Validation failed with 4 errors;
...(same error)
```

my codegen.yml is:
```
schema: 'http://.../v1/graphql'
overwrite: true
documents: 'src/routes/graphql/**/*.gql'
generates:
  src/codegen.ts:
    plugins:
      - typescript:
          scalars:
            date: string
            geography: string
            jsonb: string
      - typescript-operations
      - graphql-codegen-svelte-apollo
    config:
      clientPath: 'src/client'
      skipTypename: false
      withHooks: true
      withHOC: false
      withComponent: false
      defaultScalarType: string
  ./graphql.schema.json:
    plugins:
      - introspection

```
I tried to move the `scalars:` on the `config:` but got the same error.
I have asked around but still couldn't fix it.
