### DISCUSSION TITLE
How to make return type of resolvers partial?

### DISCUSSION THREAD

**Discussion by mrctrifork** [dotansimha/graphql-code-generator#6872] [Q&A]
Hi I am using this configuration file:

```yml
overwrite: true
schema: "src/**/*.(resolver|type).ts"
documents: null
generates:
  src/graphql/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
    config:
      typesSuffix: GQL
      resolverTypeSuffix: Resolver
```

Works fine but it's really annoying to cast `as any as TypeGQL` every time I want to delegate a property of the returned object to another resolver.

I've also tried adding the option:

```yml
config:
  defaultMapper: Partial<{T}>
```

But that also modifies the parameters of my resolvers to be `Partial<Parent>` or something like that.

How do I go about making _only_ the return type of the resolver Partial?
