### DISCUSSION TITLE
Multiple GraphQL APIs into single generator

### DISCUSSION THREAD

**Discussion by guibirow** [dotansimha/graphql-code-generator#6964] [General] [answered]
Hi All,

I've been looking for a way to run a single generator sourcing multiple graphql APIs and generating a single output to be consumed by our mobile app.

We currently have multiple systems providing GraphQL endpoints, but we do not yet have an API Gateway with federation to serve these into a single endpoint. it is on our backlog to do so, but we don't have the capacity just now to get it up and running.

I've noticed the generator support multiple schemas, but I coudn't find how I can set it up each schema route the GraphQL to a different endpoint.

Is this possible?
or there are any other way to achieve this on client side?

**Comment by ardatan** [comment, marked as answer]
If you want to merge those schemas;
```
schema: 
  - ONE_SCHEMA_POINTER
  - TWO_SCHEMA_POINTER
generates:
   some-file.ts: # This file would contain results of merged schema
      plugins:
         - typescript  
```

Or if you want to generate different types for each so they will be handled seperately
```
generates:
   first-schema.ts:
      schema: ONE_SCHEMA_POINTER
      plugins:
         - typescript  
   first-schema.ts:
      schema: TWO_SCHEMA_POINTER
      plugins:
         - typescript  
```

**Reply by guibirow** [reply]
Thanks a lot, I will have a look on it to see which one fits better.

I am okay to merge the schemas if their definitions can point to different endpoints when requesting the data.

**Reply by hymair** [reply]
@ardatan We have the same exact case as OP. But I was wondering if it's possible to use a different `typesPrefix` for each schema?

I'd like to prefix all types from TWO_SCHEMA_POINTER
```yml
schema: 
  - ONE_SCHEMA_POINTER
  - TWO_SCHEMA_POINTER
generates:
   some-file.ts: # This file would contain results of merged schema
      plugins:
         - typescript  
```
