### DISCUSSION TITLE
Keep getting error when trying to fetch schema

### DISCUSSION THREAD

**Discussion by Poolshark** [dotansimha/graphql-code-generator#6972] [Q&A] [answered]
Hi!

I have followed the installation instruction on the website but unfortunately I can't get this to work. I keep getting
```
undici.Request is not a constructor
TypeError: undici.Request is not a constructor
```

#### My `codegen.yml` looks like:
```yml
overwrite: true
schema:
  - ${REACT_APP_GRAPHQL_ENDPOINT}/graphql:
      headers:
        Dg-Auth: ${REACT_APP_API_KEY}
        Content-Type: application/json
generates:
  ./data/schema.graphql:
    plugins:
      - schema-ast
    config:
      skipDocumentsValidation: false
      includeDirectives: true
      flattenGeneratedTypes: true
```

#### I have installed
```json
"devDependencies": {
    "@graphql-codegen/cli": "^2.2.2",
    "@graphql-codegen/introspection": "^2.1.0",
    "@graphql-codegen/schema-ast": "^2.3.0"
}
```
and 
```json
"dependencies": {
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "@types/jest": "^26.0.15",
    "@types/node": "^12.0.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "graphql": "^16.0.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "4.0.3",
    "typescript": "^4.1.2",
    "web-vitals": "^1.0.1"
  }
```

And I am running `yarn graphql-codegen --config codegen.yml -r dotenv/config `

Can anyone help me with this? I have used `graphql-codegen` in older projects and it still works there! I have also tried to figure out the problem and it seems that `undici` is not a dependency anymore?

Cheers!
