### DISCUSSION TITLE
Wrapping entire schema into a single type.

### DISCUSSION THREAD

**Discussion by fibonacid** [dotansimha/graphql-code-generator#6982] [Q&A]
Hello, i'm trying to make a type safe testing using the approach explained in [Mocking a schema using introspection](https://www.graphql-tools.com/docs/mocking#mocking-a-schema-using-introspection).

I was able to generate the types for the resolvers prop of addMocksToSchema using the `typescript-resolvers`.
With that i was able to swap the generic `IResolvers` type with the `Resolvers` which is specific to my schema.

Now i would like to do the same with the type `IMocks`, although i don't know where to find or how to generate a type that wraps every schema type generated by the `typescript` plugin.

Here is my codegen configuration if that can help.
```yaml
overwrite: true
schema:
  - https://${SHOPIFY_STORE}.myshopify.com/api/2021-10/graphql.json:
      headers:
        "X-Shopify-Storefront-Access-Token": ${SHOPIFY_STOREFRONT_TOKEN}
documents: "./graphql/**/*.gql"
generates:
  ./__generated__/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
      - "typescript-resolvers":
          defaultMapper: Partial<{T}>

```
Thanks in advance
