### DISCUSSION TITLE
How to define custom scalars with kotlin plugin ?

### DISCUSSION THREAD

**Discussion by zDudaHang** [dotansimha/graphql-code-generator#7057] [Q&A]
Hi !

In the project I'm working on, we have some scalars associated with `java.time` classes like `LocalDateTime` and `Instant`, and I wanted to map them to these classes with the `scalars` config, but the `java.time` classes are not imported. I tried using the `add` plugin to add an `import java.time.*`, but the `import` ended up on top of the package definition, causing an error

Am I configuring the plugin correctly? I have been working on this package a little while ago 

My schema:
```
(...)
scalar LocalDateTime
scalar Instant
scalar Long

input AppointmentQueryInput {
    userId: Long
    time: LocalDateTime
}
(...)
```

The `codegen.yml`:
```
(...)
    plugins:
      - kotlin
    config:
      listType: List
      scalars:
        Long: Long
        LocalDateTime: java.time#LocalDateTime
        Instant: java.time#Instant
```

The generated class:
```
data class AppointmentQueryInput(
    val time: LocalDateTime? = null,
    val userId: Long? = null
) {
  constructor(args: Map<String, Any>) : this(
      args["time"] as LocalDateTime?,
      args["userId"] as Long?
  )
}
```

Thank you for your help!

PS. Thank you for this package! :heart:
