### DISCUSSION TITLE
near-operation-file settings

### DISCUSSION THREAD

**Discussion by hyusetiawan** [dotansimha/graphql-code-generator#7087] [Q&A] [answered]
I am trying to generate a typing file per query using near-operation-file but somehow I cannot get it to work. Here are my issues:
1. whenever i run the codegen, it also process the generated files so it looks like this:
<img width="456" alt="Screen Shot 2021-11-24 at 2 04 03 PM" src="https://user-images.githubusercontent.com/1062920/143318400-e9c4fbc2-0988-4fbe-b807-75799f0d12a9.png">
2. the generated file path import is using relative, `import * as Types from '../../../types/base';` whereas I want it to be "types/base" since I already have that mapping in my tsconfig

here is my config:
```
schema: http://localhost:4001/graphql
documents: 'src/**/!(*.d).{ts,tsx}'
hooks:
    afterAllFileWrite:
        - prettier --write
generates:
    ./src/:
        preset: near-operation-file
        presetConfig:
            baseTypesPath: types/base
            extension: .gen.ts
        config:
            namingConvention:
                enumValues: keep
            withHooks: true
            gqlImport: urql#gql
        plugins:
            - typescript-operations
            - typescript-urql
            - add:
                  content: '/* eslint-disable */'
    ./src/types/base.ts:
        plugins:
            - typescript
```

thank you!
