### DISCUSSION TITLE
Prettier doesn't work because afterAllFileWrite pass paths without quotes

### DISCUSSION THREAD

**Discussion by nik-tolstik** [dotansimha/graphql-code-generator#7088] [Q&A]
**Command**
```shell
graphql-codegen
```

**Error Log**
```shell
[error] No files matching the pattern were found: "C:/Users/username/Desktop/My".
[error] No files matching the pattern were found: "Projects/project/src/app/components/example/duck/operations.generated.ts".
```

**Description of problem**
Works on all OS platfroms. Prettier doesn't work with absolute paths that have spaces without wrapped double quotes
Run the following script without the double quotes of the path and you will get an error message `prettier --write <path with inner spaces>`. `afterAllFileWrite` passes the absolute paths without double quotes. 

**My actual solutions**
- Solution 1
1. I remove hook `afterAllFileWrite`
2. Rewrite script in `package.json`:
```json
"generate": "graphql-codegen && prettier --write \"src/**/*.generated.{ts,d.ts}\""
```

- Solution 2
Remove the gaps in the path to your project.
For example:
_C:/Users/username/Desktop/**My Projects**/project/src/app/components/example/duck/operations.generated.ts_ -> 
_C:/Users/username/Desktop/**my-projects**/project/src/app/components/example/duck/operations.generated.ts_

**Expected behavior**
Prettier should overwrite all generated files without errors. My solution is bad because it is not optimized and unsafe.

**Environment:**
- NodeJS: 16.13.0
- OS: Windows 11
- `package.json`
```json
    "prettier": "2.4.1",
    "@graphql-codegen/add": "3.1.0",
    "@graphql-codegen/cli": "2.3.0",
    "@graphql-codegen/near-operation-file-preset": "2.2.2",
    "@graphql-codegen/typescript": "2.4.1",
    "@graphql-codegen/typescript-graphql-files-modules": "2.1.0",
    "@graphql-codegen/typescript-operations": "2.2.1",
```
- `codegen.yml`
```yml
# Path to root schema.
schema: schema.gql
# Specify where all queries and mutations are located.
documents: src/**/*.gql
generates:
  # Generate root TypeScript interfaces based on `schema.gql`.
  src/schema.generated.ts:
    plugins:
      - typescript
      - add:
          content: "/* eslint-disable */"
    config:
      skipTypename: true
  # Tell TypeScript what is exported from `operations.gql` files.
  src/env.generated.d.ts:
    plugins:
      - typescript-graphql-files-modules
      - add:
          content: "/* eslint-disable */"
  # Generate TypeScript interfaces for every query and mutation.
  src/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: schema.generated.ts
    plugins:
      - typescript-operations
      - add:
          content: "/* eslint-disable */"
    config:
      skipTypename: true
# Prettify generated files.
hooks:
  afterAllFileWrite:
    - prettier --write
```
