### DISCUSSION TITLE
Unexpected token P in JSON at position 0

### DISCUSSION THREAD

**Discussion by deadcoder0904** [dotansimha/graphql-code-generator#7152] [Q&A] [answered]
I get an error when using GraphQL Codegen:

> Unexpected token P in JSON at position 0

In Network Tab, it shows:

> POST body missing, invalid Content-Type, or JSON object has no keys.

This is when I use it like:

```ts
const { isLoading, isError, data, error } = useGetCurrentUserQuery()

if (isLoading) return <Loading />

if (isError) return <Error error={error} />
```

It loads the `Error` component & gives me the error mentioned above.

My `codegen.yml` file looks like:

```yml
schema: ./src/server/graphql/schema.graphql
documents:
  - '**/*.graphql'
  - '!/src/server/graphql/schema.graphql'
generates:
  src/client/graphql/types.generated.ts:
    plugins:
      - typescript
  ./:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: src/client/graphql/types.generated.ts
    plugins:
      - add:
          content: &comment "/* DO NOT EDIT! this file was generated by graphql-codegen */\n/* eslint-disable */"
      - typescript-operations
      - typescript-react-query
    config:
      fetcher:
        endpoint: '`${process.env.NEXT_PUBLIC_BASE_URL}/api`'
```

I want to use `ky` for this as well but I didn't find an example of `graphql-codegen` with `ky`. I even searched for `axios` but couldn't find it. Is there an easy way to use `ky` since I like the API?

And how do I fix this?

I even tried putting the following under `fetcher` but that didn't work either:

```yml
fetchParams:
          headers:
            credentials: include
            content-type: 'application/json'
```

**Comment by deadcoder0904** [comment, marked as answer]
I think I put `credentials: include` & it started working:

```yml
    config:
      fetcher:
        endpoint: '`${process.env.NEXT_PUBLIC_BASE_URL}/api`'
        fetchParams:
          headers:
            credentials: include
            content-type: application/json
```

Although, would love to know how to use `ky` but I don't think I need it in auto-generated code. It does come with quite some goodies over fetch.
