### DISCUSSION TITLE
Codegen for graphql-request with custom scalars

### DISCUSSION THREAD

**Discussion by dodomorandi** [dotansimha/graphql-code-generator#7249] [Q&A]
I am having problems trying to use a [custom scalar](https://www.graphql-scalars.dev/docs/quick-start) with `typescript-graphql-request`.

I implemented the custom scalar [using official code as a reference](https://github.com/Urigo/graphql-scalars/blob/master/src/scalars/Timestamp.ts) and I used `typescript-resolvers`, adding the custom scalar in the config in the following way:
```yml
schema: ./src/schema.graphql
generates:
  ./src/graphql.ts:
    documents:
      - './src/query.graphql'
    plugins:
      - typescript
      - typescript-resolvers
      - typescript-operations
      - typescript-graphql-request
    config:
      rawRequest: true
      extensionsType: unknown
      defaultScalarType: unknown
      mappers:
        Money: "./scalars/money#MoneyResolver"
      scalars:
        Money: "./scalar-types#Money"
```

However, it looks like that the resolver of `Money` is not used to create a GraphQL query (I expected the function `serialize` to be called) -- it is consistent with the call to `client.rawRequest` which, if I am not wrong, doesn't have a way to pass resolvers around. The generated part is something like the following:
```typescript
export function getSdk(
  client: GraphQLClient,
  withWrapper: SdkFunctionWrapper = defaultWrapper,
) {
  return {
    Dummy(
      variables: DummyQueryVariables,
      requestHeaders?: Dom.RequestInit["headers"],
    ): Promise<{
      data?: DummyQuery | undefined;
      extensions?: unknown;
      headers: Dom.Headers;
      status: number;
      errors?: GraphQLError[] | undefined;
    }> {
      return withWrapper(
        (wrappedRequestHeaders) =>
          client.rawRequest<DummyQuery>(
            DummyDocumentString,
            variables,
            { ...requestHeaders, ...wrappedRequestHeaders },
          ),
        "Dummy",
      );
    },
  };
}
```

Am I missing something obvious? Is it just a matter of better documenting a combination of features (codegen+scalars+graphql-request)? Or there is a real issue that should be opened?

Note that my workaround is something I would really like to avoid: `money.serialize() as unknown as Money`. As you can imagine, this makes all the static typing & codegen pretty useless for that specific context...
