### DISCUSSION TITLE
Generated file throws typescript error when importing the GQL into component to use

### DISCUSSION THREAD

**Discussion by alukaschewski** [dotansimha/graphql-code-generator#7275] [Q&A]
I am using Angular (13) and NestJS with GraphQL and Apollo and i have recently been running into a typescript error when importing the GQL into a component and i have never had an issue with this before until now
**Package versions:**
```
"@nestjs/graphql": "^9.1.2",
"graphql": "15.7.2",
"@graphql-codegen/cli": "2.3.0",
"@graphql-codegen/typescript": "2.4.1",
"@graphql-codegen/typescript-apollo-angular": "3.3.1",
"@graphql-codegen/typescript-operations": "2.2.1",
"@graphql-codegen/typescript-resolvers": "2.4.2",
"typescript": "~4.4.3"
```

**Codegen**
```
overwrite: true
generates:
  libs/whatever/graphql/src/lib/generated/generated.ts:
    schema: apps/nestjs/src/schema.graphql
    documents:
      - libs/whatever/graphql/src/**/*.graphql
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-resolvers"
      - "typescript-apollo-angular"
```

**Resolver**
```
import { Query, Resolver } from '@nestjs/graphql';

@Resolver()
export class MyResolver {
    @Query(() => [String], { name: 'myStringArray' })
    async getMyStringArray(): Promise<string[]> {
        return ['One', 'Two'];
    }
}
```

**GraphQL**
```
query MyStringArray {
    result: myStringArray
}
```

**Component**
```
import { Component } from '@angular/core';

import { MyStringArrayGQL } from '@whatever/graphql';

@Component({
    selector: 'star-wars-sandbox-home',
    templateUrl: './home.component.html',
    styleUrls: ['./home.component.scss'],
})
export class HomeComponent {
    constructor(private myStringArrayGQL: MyStringArrayGQL) {}
}
```

**Simply running the angular app + nestjs app will throw this error:**

```
Error: libs/whatever/graphql/src/lib/generated/generated.ts:146:5 - error TS4114: This member must have an 'override' modifier because it overrides a member in the base class 'Query<MyStringArrayQuery, Exact<{ [key: string]: never; }>>'.

146     document = MyStringArrayDocument;
```

Any and all help is much appreciated!
