### DISCUSSION TITLE
near-operation-file preset  doesn't add fragment import

### DISCUSSION THREAD

**Discussion by AndrzejSala** [dotansimha/graphql-code-generator#7313] [Q&A]
I have the following entry in `generates` in my graphql.codegen.yml:
```
  ./libs/:
    plugins:
      - typescript-operations
      - typescript-react-apollo
    documents: ./libs/components/src/**/*.graphql
    preset: near-operation-file
    presetConfig:
      extension: .generated.tsx
      baseTypesPath: ~@tutoring/graphql-schema-types
      importAllFragmentsFrom: '~@tutoring/graphql-schema-fragments'
```

my operation file:
```
mutation SendChatMessage(
  $sessionId: ID!
  $text: String
  $image: S3FileInput
  $sequence: Int
) {
  sendChatMessage(
    input: {
      sessionId: $sessionId
      text: $text
      image: $image
      sequence: $sequence
    }
  ) {
    ...chatMessageFragment
  }
}
```

And generated .tsx:
```
import * as Types from '@tutoring/graphql-schema-types';

import {gql} from '@apollo/client';
import * as Apollo from '@apollo/client';
const defaultOptions = {};
export type SendChatMessageMutationVariables = Types.Exact<{
  sessionId: Types.Scalars['ID'];
  text?: Types.Maybe<Types.Scalars['String']>;
  image?: Types.Maybe<Types.S3FileInput>;
  sequence?: Types.Maybe<Types.Scalars['Int']>;
}>;

export type SendChatMessageMutation = {
  readonly sendChatMessage?: Types.Maybe<{}>;
};

export const SendChatMessageDocument = gql`
  mutation SendChatMessage(
    $sessionId: ID!
    $text: String
    $image: S3FileInput
    $sequence: Int
  ) {
    sendChatMessage(
      input: {
        sessionId: $sessionId
        text: $text
        image: $image
        sequence: $sequence
      }
    ) {
      ...chatMessageFragment
    }
  }
  ${ChatMessageFragmentFragmentDoc}
`;
export type SendChatMessageMutationFn = Apollo.MutationFunction<
  SendChatMessageMutation,
  SendChatMessageMutationVariables
>;
```

I wonder why in `generated.tsx` there is no import with fragments, even if I added in codegen
`importAllFragmentsFrom: '~@tutoring/graphql-schema-fragments'`

I suppose to have something like:
`import * as Fragments from '@tutoring/graphql-schema-fragments';`
and use it like
`  ${Fragments.ChatMessageFragmentFragmentDoc}`
