### DISCUSSION TITLE
Import external types to my graphql-schema.tsx

### DISCUSSION THREAD

**Discussion by AndrzejSala** [dotansimha/graphql-code-generator#7315] [Q&A]
I would like to import my separately generated `types.ts` to my `graphql-schema.tsx` instead of generating them again in this file. 
I tried to use `add` plugin to add needed import statements, but now all types are covered behind `Types.`

generate entry:
```
  ./libs/graphql-schema/src/lib/graphql-schema.tsx:
    documents: ./libs/graphql-schema/src/**/*.graphql
    plugins:
      - add:
          content: 
            - 'import * as Types from "@tutoring/graphql-schema-types";'
            - 'export * from "@tutoring/graphql-schema-types";'
      - typescript-react-apollo
      - typescript-operations
    config:
      withHooks: true
      preResolveTypes: false
      skipTypename: true
      immutableTypes: true
      namingConvention:
        typeNames: change-case#pascalCase
        enumValues: change-case#upperCase
```

Any ideas?
