### DISCUSSION TITLE
Import only needed types @graphql-codegen/typed-document-node

### DISCUSSION THREAD

**Discussion by diegoserranor** [dotansimha/graphql-code-generator#7440] [Q&A]
Hello,

I am setting up @graphql-codegen/typed-document-node in my project.
Following this guide: https://www.graphql-code-generator.com/docs/guides/react#apollo-and-urql

My `codegen.yml` is pointing to .graphql documents for the queries I need, but the generated file includes all possible types in the schema. This is all right at the moment as the file should not impact the bundle too much.

However, for proper documentation of only the used types, what would be the right configuration to make it import only types for the operations defined in the `documents` field.

```
schema: http://localhost:3060/graphql
documents: './src/graphql/*.graphql'
generates:
  ./src/graphql/generated-types.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
```
