### DISCUSSION TITLE
How to use generated react-query hooks in a third party folder on a big project

### DISCUSSION THREAD

**Discussion by kevinmamaqi** [dotansimha/graphql-code-generator#7511] [Q&A]
I have generated the hooks using:

```
overwrite: true
schema: "./src/source/schema.graphql"
documents: "./src/source/documents/**/*.graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      # - typed-document-node
      - typescript-react-query
    config:
      fetcher:
        endpoint: "'/api/graphql'"
```
        
In a shared folder to user those in my react apps, having the following structure:

```
- /app1/src/components
- /app2/src/components
- /lib/graphql-types/generated.ts
```

How can I import the hooks without the following error:

`Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:`

We are not using a yarn monorepo or similar, and I'm afraid we can't
