### DISCUSSION TITLE
Need help getting schema to load from ES Module

### DISCUSSION THREAD

**Discussion by kaysond** [dotansimha/graphql-code-generator#7517] [Q&A]
I have a monorepo set up in vscode with `server` and `client` packages.

I'm using `graphql-code-generator` in my `client` package. This is my setup:

`codegen.yaml`:
```yaml
hooks:
  afterAllFileWrite:
    - prettier --write
schema: ./schema.ts
require:
  - ts-node/register
documents: ./src/**/*.graphql
generates:
  src/types.gen.ts:
    - typescript
  src/:
    preset: near-operation-file
    presetConfig:
      extension: .gen.tsx
      baseTypesPath: types.gen.ts
    plugins:
      - typescript-operations
      - typed-document-node
    config:
      withHooks: true
```

`./schema.ts`:
```typescript
import { schema } from '@qda/server';

export default schema;
```

In the `server` package, `schema` is generated from type-graphql's `buildSchema`:
```typescript
export const schema = await buildSchema({
  resolvers: [Resolvers],
  dateScalarMode: 'timestamp'
});
```
and when I check the type reported in VSCode, it's `(alias) const schema: GraphQLSchema`

It seems like everything is set up properly, but I get the following error when running `graphql-codegen`:
```
Failed to load schema for "src/"
        Failed to load schema from ./schema.ts:


      Unable to find any GraphQL type definitions for the following pointers:

          - ./schema.ts

        Error:
      Unable to find any GraphQL type definitions for the following pointers:

          - ./schema.ts

    at prepareResult (C:\backup\QCSD\node_modules\@graphql-tools\load\index.js:561:15)
    at loadTypedefs (C:\backup\QCSD\node_modules\@graphql-tools\load\index.js:527:12)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.loadSchema (C:\backup\QCSD\node_modules\@graphql-tools\load\index.js:612:21)
    at async loadSchema (C:\backup\QCSD\node_modules\@graphql-codegen\cli\bin.js:495:24)
    at async C:\backup\QCSD\node_modules\@graphql-codegen\cli\bin.js:1034:65

        GraphQL Code Generator supports:
          - ES Modules and CommonJS exports (export as default or named export "schema")
          - Introspection JSON File
          - URL of GraphQL endpoint
          - Multiple files with type definitions (glob expression)
          - String in config file

        Try to use one of above options and run codegen again.
```

What am I doing wrong?
