### DISCUSSION TITLE
How to use the CLI?

### DISCUSSION THREAD

**Discussion by vndre** [dotansimha/graphql-code-generator#7596] [Q&A]
I'm trying to create a typed sdk but I'm having a hard time understanding how.

`codegen.yml`:
```
overwrite: true
schema: ${API_URL}
documents: ./graphql/test.query.graphql
generates:
  ./utils/sdk.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
```

`graphql/test.query.graphql`:
```
query hellooo {
  hello {
    name
  }
}
```

output of running `env-cmd graphql-codegen --config ./framework/codegen.yml`:
```
 Unable to find any GraphQL type definitions for the following pointers:
        
          - ./graphql/test.query.graphql
```
