### DISCUSSION TITLE
How to import a specific type when using the near-operation-file plugin?

### DISCUSSION THREAD

**Discussion by giopetris** [dotansimha/graphql-code-generator#7605] [Q&A]
I'm looking to a way to specify a single type that should be imported from the code generated by the `near-operation-file` plugin. It imports types like `import * as Types from '~/types'`. I can configure the import path or the name of the namespace variable (`Types`), but I don't see a way to tell it to import a specific thing like `import { AdminTypes } from '~/types'`. 

Here's part of the codegen config that generates it:

```
...
generates:
  apps/frontend/src/app:
    preset: near-operation-file
    presetConfig:
      extension: '.gql.ts'
      baseTypesPath: '~/types'
    plugins:
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      reactApolloVersion: 2
      immutableTypes: false
      declarationKind: 'interface'
      documentMode: 'documentNode'
      withComponent: false
      withHOC: false
      withHooks: true
    hooks:
      afterOneFileWrite:
        - prettier --write
```
