### DISCUSSION TITLE
Migration typescript-operations 1.18.4 > 2.*

### DISCUSSION THREAD

**Discussion by arsonik** [dotansimha/graphql-code-generator#7651] [Q&A]
Hey there 
Quick questions I have no idea how to configure the codegen to output the same or at least not that `| {}` type.
The query 
```graphql
query eventBySlug($slug: ID!) {
    model(slug: $slug) {
        ... on ListViewableEvent {
            viewed
        }
    }
}
```
Generated types 
BEFORE
```ts
export type EventBySlugQuery = {
    readonly model?: Maybe<
        | Pick<ListEvent, 'viewed'>
        // [...] all the matching interfaces
        | Pick<SubscriberEvent, 'viewed'>
    >;
};
```
AFTER
````ts
export type EventBySlugQuery = {
    readonly model?:
        | { readonly viewed: boolean }
        // [...] all the matching interfaces
        | { readonly viewed: boolean }
        | {} // << But Why this new type 🤨 
        | null;
};
````

So what's bugging me is that last `| {}`

My codegen looks like 
```yaml
plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
    config:
      inlineFragmentTypes: combine
```

Thanks !!
