### DISCUSSION TITLE
Trying to use codegen for Cloudflares graphql api

### DISCUSSION THREAD

**Discussion by alexbjorlig** [dotansimha/graphql-code-generator#7754] [Q&A]
I'm trying to use codegen for the cloudflare API.

```yml
  ./src/queries-cloudflare/generated.ts:
    schema:
      - https://api.cloudflare.com/client/v4/graphql:
          headers:
            Authorization: Bearer <token>
    documents: ./src/queries-cloudflare/**/*.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-document-nodes
```

But when I try to generate the types, I get this error:

```
Something went wrong Type mutation must define one or more fields.
```

Is something wrong with my codegen.yml - or is Cloudflare "wrong"?
