### DISCUSSION TITLE
Splitting or sharing types between two plugins

### DISCUSSION THREAD

**Discussion by harrygr** [dotansimha/graphql-code-generator#7796] [Q&A]
I'm trying to use graphql-code-generator with both [TypeScript GraphQL-Request](https://www.graphql-code-generator.com/plugins/typescript-graphql-request) and [TypeScript Urql](https://www.graphql-code-generator.com/plugins/typescript-urql).

Both these plugiuns require types from the [Typescript](https://www.graphql-code-generator.com/plugins/typescript) and [TypeScript Operations](https://www.graphql-code-generator.com/plugins/typescript-operations) plugins, but they seem to generate their own fragments.

This means that when I try to generate a single file like so:

```
// ...
generates:
  src/generated/graphql.ts:
      - "typescript"
      - "typescript-operations"
      - "typescript-graphql-request"
      - "typescript-urql"
```

I end up with two set of fragments that declared twice resulting in `Cannot redeclare block-scoped variable 'FooDocument'`.

One solution might be to have the output from `typescript` and `typescript-operations` in one file (say `generated/types.ts`) and have different separate files for `typescript-graphql-request` and `typescript-urql` that import what they need from `types.ts`, but I'm not sure how to achieve this.

Has anyone done anything similar to the above?

**Comment by harrygr** [comment]
OK, this is one way I've kinda achieved this:

```
generates:
  src/generated/types.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
  src/generated/graphqlRequest.ts:
      - "add": 
          content: "import * as G from './types'"
      - "typescript-graphql-request":
          typesPrefix: "G."
  src/generated/graphqlUrql.ts:
      - "add": 
          content: "import * as G from './types'"
      - "typescript-urql":
          typesPrefix: "G."
```

Basically used the `add` plugin to manually an an import from the `types` file. This might hard code-splitting/bundle sizing for front end assets but it seems to do the trick. I'd still be keen to hear any alternative approaches.
