### DISCUSSION TITLE
Is it possible to mix plugins targeting both frontend and backend environment without query duplication?

### DISCUSSION THREAD

**Discussion by astik** [dotansimha/graphql-code-generator#7847] [Q&A] [answered]
I'm trying to use code generator in a Next.js context.
I have need for frontend and backend (through getServerSideProps) calls through Apolo client.
I'm planning to define:

```
overwrite: true
schema: graphql/schema.graphql
documents:
  - 'graphql/*.gql'
hooks:
  afterAllFileWrite:
    - 'prettier --write'
generates:
  ./graphql/types.generated.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-graphql-apollo'
      - 'typescript-react-apollo'
```

Problem is between `typescript-graphql-apollo` and  `typescript-react-apollo` which create duplicate of my GQL query in gql tag:

``` 
export const GetFoobarDocument = gql`
  query GetFoobar($myUuid: ID!) {
    foobar(myUuid: $myUuid) {
      foo
      bar
    }
  }
`;
```

One of those export is create by each of the 2 plugins.

Am i missing something?
Is it possible to have both declaration (hook and SDK) in a single file without rewriting what is generated?

**Comment by astik** [comment]
Nevermind .. potentially a duplicate of https://github.com/dotansimha/graphql-code-generator/discussions/7796 ='(

**Comment by astik** [comment, marked as answer]
I confirm it is a duplicate, here is my solution using the technic describe in the original post:
```
overwrite: true
schema: graphql/schema.graphql
documents:
  - 'graphql/*.gql'
hooks:
  afterAllFileWrite:
    - 'prettier --write'
generates:
  ./graphql/types.generated.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
  ./graphql/client-backend.generated.ts:
    plugins:
      - 'add':
          content: "import * as G from './types.generated'"
      - 'typescript-graphql-apollo':
          typesPrefix: 'G.'
  ./graphql/client-react.generated.ts:
    plugins:
      - 'add':
          content: "import * as G from './types.generated'"
      - 'typescript-react-apollo':
          typesPrefix: 'G.'
```
