### DISCUSSION TITLE
I need help using directives

### DISCUSSION THREAD

**Discussion by D3C0RU5** [dotansimha/graphql-code-generator#7879] [Q&A]
I have a question regarding directives, my backend is already working and returns queries as it should, but I don't know how to proceed in the frontend, if I put directive in the query directly it works fine, but I need a value to be passed in the directive that informs the language used.

Can someone help me?

![image](https://user-images.githubusercontent.com/55204235/170136933-ec65ad0b-9634-45dd-85dd-cd9de0bf6cd4.png)

seachCandidates.ts
```
import { gql } from '@apollo/client';

export default gql`
  directive @locale(lang: LocaleEnum) on FIELD_DEFINITION

  query SearchCandidates($filters: SearchCandidateFilter!) {
    searchCandidates(filters: $filters) @locale(lang: en) {
      candidates {
        candidate {
          id
          name
          image
          positionTitle
          cltSalary
          pjSalary
          usdSalary
          lastApprovedTime
          city {
            id
            name
          }
          summary
          workRemote
          localWorkPreference
          experiences {
            id
            company
            startDate
            endDate
            currentJob
          }
          skills {
            id
            level {
              value
              text
            }
            mainTech
            technology {
              id
              name
            }
          }
          educations {
            id
            institution
            educationStatus
            endYear
          }
          candidateFocus {
            id
            focus {
              id
              description
            }
            experienceLevel {
              value
              text
            }
            order
          }
          candidateCities {
            id
            order
            city {
              id
              name
            }
          }
        }
        lastBidSent {
          id
          status
          createdAt
          companyUser {
            id
            name
          }
        }
        isFavorite
        lastTimeViewed
      }
      totalFilteredCount
    }
  }
`;
```
codegen.yml
```
schema: "http://localhost:3000/graphql"
documents: "src/**"
overwrite: true

generates:
  src/lib/generated/graphql/index.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withHOC: false
      withComponent: false
      withHooks: true
      avoidOptionals:
        field: true
      maybeValue: "T"
      skipTypename: true
```
