### DISCUSSION TITLE
Environment variables & CI/CD Integration

### DISCUSSION THREAD

**Discussion by UgRoss** [dotansimha/graphql-code-generator#7893] [Q&A]
Hey 👋

Could you please help me to integrate Codegen & ENV variables with CI/CD?

For example, I have a command to generate typings locally:

```json
"codegen": "DOTENV_CONFIG_PATH=.env.local graphql-codegen --config codegen.yml -r dotenv/config",
```

Then inside the `codegen.yml`:

```yml
overwrite: true
schema: ${GRAPHCMS_PROJECT_API}
documents: 'src/**/*.graphql'
....
```

However, this won't work on the CI side because `.env.local` doesn't exist there. I wonder if there is a way to configure codegen to read ENV variables from CI?

Thanks!
