### DISCUSSION TITLE
gql-tag-operations-preset removes useFragment code for no reason

### DISCUSSION THREAD

**Discussion by kevin-meyers** [dotansimha/graphql-code-generator#7907] [Q&A] [answered]
Hello! I was just poking around on the frontend making some small fixes when I ran `npm run generate` (my codegen command) and it destroyed the useFragment function:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/37648386/171724385-62ab65af-b3da-4e06-90f6-df443a934cc7.png">

Now it fails everywhere it was used:
<img width="718" alt="image" src="https://user-images.githubusercontent.com/37648386/171726041-283762c5-7419-4728-9d7d-77c38ba427c7.png">

My codegen file is this:
```yaml
schema: http://localhost:8080/v1/graphql
documents:
  - 'src/**/*.tsx'
  - '!src/generated/**/*'
generates:
  ./src/generated/:
    preset: gql-tag-operations-preset
    presetConfig:
      augmentedModuleName: '@apollo/client'
      fragmentMasking: true
```

also if I `git checkout` the fragment function file so it goes back to the old way and run `npm run generate` again it adds semicolons to every line???
<img width="267" alt="image" src="https://user-images.githubusercontent.com/37648386/171725267-3ece5ecd-652d-4f81-84ef-ceff0225bc54.png">

My only idea is to just copy the working useFragment code and move it to a file I manage and pull it from there

Er I just realized its also deleting all the"...Fragment" gqls and some of the "...Query" ones too, I have no idea whats going on!
