### DISCUSSION TITLE
How do I enable autocomplete in .graphql files?

### DISCUSSION THREAD

**Discussion by mwjaco** [dotansimha/graphql-code-generator#8007] [Q&A] [answered]
Here is my codegen.yml
```
overwrite: true
schema: REDACTED
documents: "src/**/*.graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - "add":
          content: "/* eslint-disable */"
      - "typescript"
      - "typescript-operations"
      - "typed-document-node"
      - "fragment-matcher"
    config:
      maybeValue: "T"
  ./graphql.schema.json:
    plugins:
      - "introspection"

```

When I write queries inside `.graphql` files, `@graphql-eslint/eslint-plugin` is able to use my `graphql.schema.json` to alert me when I have a typo in my fields, but VS Code does not offer any autocomplete suggestions for me.

How do I turn this on? If the linter can figure out my schema for me, is there a `graphql-code-generator` plugin which can suggest fields for me?  I have researched many plugins now but I cannot find one that achieves this.
