### DISCUSSION TITLE
How to avoid generating @Injectable section on graphql-codegen for angular

### DISCUSSION THREAD

**Discussion by rajaa1985** [dotansimha/graphql-code-generator#8041] [Q&A]
How to avoid generating @Injectable section on graphql-codegen for angular

**codegen.yaml**
```
schema: http://localhost:3002/graphql
documents: "src/graphql/*.gql"
generates:
    ./graphql/schema.graphql:
        plugins:
            - schema-ast
    ./src/service/schema.ts:
        plugins:
            - typescript
            - typescript-operations
            - typescript-apollo-angular
```

**In the following code I need only gql constant. So how can I avoid generating @Injectable related class code below**

**Generated code**
```
export const AppDetailDocument = gql`
     query app_detail() {
      app_detail() {
          id
          name
      }
  }`;

@Injectable({
    providedIn: 'root'
  })
  export class AppDetailGQL extends Apollo.Query<AppDetailQuery, AppDetailQueryVariables> {
    document = AppDetailDocument;
    
    constructor(apollo: Apollo.Apollo) {
      super(apollo);
    }
  }


```
