### DISCUSSION TITLE
Optional variables generate with InputMaybe instead of Maybe

### DISCUSSION THREAD

**Discussion by lockykeaney** [dotansimha/graphql-code-generator#8082] [Q&A]
I have this front end query that takes in 2 potential values, but both are optional as they will be resolved on the back end:
```
query PersonalDetails($UserProfileId: Int, $UserProfileEntityId: Guid) {
  UsersGroup {
    UserProfile(UserProfileId: $UserProfileId, UserProfileEntityId: $UserProfileEntityId) {
      CreatedDate
    }
  }
}
```
When the generator runs through the schema (which is an external document that I get from a backend that I don't maintain), it creates a type `Maybe`, but the query variables type in the `generated.ts` file is trying to use `Types.InputMaybe<>` which does not exist in the schema file:

![Screen Shot 2022-07-12 at 10 59 15 am](https://user-images.githubusercontent.com/12781843/178386714-13cc6886-da35-4a0e-af58-139972d9a502.png)

From what I can find around other issues and posts, `InputMaybe` is use define when an input can be optional, whereas `Maybe` is for the optional outputs.

I tried adding it as [global type that copied the generated one), which stopped the VS code warning but still can't build.](https://github.com/dotansimha/graphql-code-generator/issues/7774#issuecomment-1134355955) 

Is there a config setting for the YAML file I need to add so I can force that type to generate?
```
schema: ${REACT_APP_Base_GraphQL_Schema}
documents: './src/**/*.graphql'
generates:
  src/schema.d.ts:
    plugins:
      - typescript
  src/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: ./schema.d.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
```

I have tried adding
```
config:
      inputMaybeValue: 'Maybe<T>'
&
config:
      inputMaybeValue: T | null | undefined
```
from [this issue reply](https://github.com/dotansimha/graphql-code-generator/issues/7774#issuecomment-1173833449) but they also look to be the default values from the plugin anyway, which leads me to think that there is a config setting where I have to enable the generation of the `InputMaybe` type. Or is it something that comes from the schema and can't be generated without it?

The current project I'm working on is quite large and proprietary, so I can't share big chucks of code and information. I don't feel like it would be a library issue, but an edge case for my particular use, so I only need to understand what is trying to happen in the generation and why.
