### DISCUSSION TITLE
type-graphql Plugin with postgraphile graphql server

### DISCUSSION THREAD

**Discussion by appcoders** [dotansimha/graphql-code-generator#8099] [Q&A]
Using a postgraphile GraphQL server and generating with plugin type-graphql:

```
overwrite: true
schema: "http://localhost:4500/graphql"
documents: definitions.graphql
hooks:
  afterAllFileWrite:
    - prettier --write
generates:
   src/generated/sdk.ts:
        plugins:
            - typescript
            - typescript-operations
            - typescript-graphql-request
   src/generated/types.ts:
        plugins:
            - typescript-type-graphql

```
The generated file sdk.ts works fine without errors.

The generated file types.ts  has plenty of errors:
- Class 'Node' used before its declaration.
- 'any' only refers to a type, but is being used as a value here.
- 'Query' only refers to a type, but is being used as a value here.
- Cannot find name 'Cursor'.
- Cannot find name 'UUID'.

What do I need to change on postgraphile or graphql-gen config to make this work?

Thank you very much.

deps:
```
"graphql": "^15",
"graphql-fields": "^2.0.3",
"graphql-request": "4.2",
"graphql-scalars": "^1.17.0",
"graphql-tag": "^2.12.6",
"tslib": "^2.4.0",
"type-graphql": "^1.1.1",
"@graphql-codegen/cli": "^2.8.1",
"@graphql-codegen/typescript": "^2.7.1",
"@graphql-codegen/typescript-graphql-request": "^4.5.1",
"@graphql-codegen/typescript-operations": "^2.5.1",
"@graphql-codegen/typescript-type-graphql": "^2.3.1",
```
<img width="977" alt="CleanShot 2022-07-15 at 11 16 04" src="https://user-images.githubusercontent.com/4519870/179194412-44bb81e5-e516-4ca4-941f-f84595903bbd.png">
