### DISCUSSION TITLE
Cannot read property 'name' of undefined when compiling a mutation

### DISCUSSION THREAD

**Discussion by alucardu** [dotansimha/graphql-code-generator#8104] [Q&A]
I have a `graphql/mutations/session.mutation.gql` file:
```
mutation CreateSession {
  createSession
}
```

```
// codegen.yml
overwrite: true
schema: "http://localhost:4000/graphql"
documents: "**/*.{gql,graphql}"
generates:
  src/generated/queries.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
```
When I run `graphql-codegen --config codegen.yml`  I get the error: 

> Cannot read property 'name' of undefined

If I comment out the mutation the codegen compiler works without error.
