### DISCUSSION TITLE
Input with default value is optional in generated type

### DISCUSSION THREAD

**Discussion by bennyk8y** [dotansimha/graphql-code-generator#8118] [Q&A]
Hi, for this schema:
```
type User {
  name: String
}

input GetUserArgs {
   offset: Int = 0
}

type Query {
  getUsers(getUsersArgs: GetUserArgs): [User]
}
```
And this codegen configuration:

```
overwrite: true
schema:
  - src/schema.graphql
generates:
  src/__generated__/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
```

Outputs 
```typescript
export type GetUserArgs {
   offset?: InputMaybe<Scalars['Int']>;
}
```

where InputMaybe defined as 
```
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
```

I dont understand why `offset` is optional and nullable in that case?
Changing to Int! does not help as it stays optional.
