### DISCUSSION TITLE
Failed to load schema [pls help]

### DISCUSSION THREAD

**Discussion by nirmaanlabs** [dotansimha/graphql-code-generator#8127] [Q&A]
I am trying to generate typescript types from my graphql schema

If I use this website it works perfectly fine [website](https://transform.tools/graphql-to-typescript)

here is my codegen.yml
```
schema: schema.graphql
generates:
  ./src/generated.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
```
if I run `npm run generate` it give following error
![image](https://user-images.githubusercontent.com/102367759/180238218-9bbb618c-d042-448f-a809-3fddbca02fc5.png)

here is my schema
[schema.zip](https://github.com/dotansimha/graphql-code-generator/files/9160154/schema.zip)
