### DISCUSSION TITLE
How do I make a Fragment use the generated Fragment type?

### DISCUSSION THREAD

**Discussion by jackdh** [dotansimha/graphql-code-generator#8141] [Q&A]
Hello,

My codegen generates this:

```typescript
export type InputsFragmentFragment = {
	__typename?: "InputRows";
	id: number;
	month: any;
	estimatedRuns: number;
};

export type ReportWeekFragmentFragment = {
	__typename?: "ReportWeekModel";
	id: number;
	inputRows: Array<{
		__typename?: "InputRows";
		id: number;
		month: any;
		estimatedRuns: number;
	}>;
};
```

How can I get it to reuse the generated Fragment as a type like below?

```typescript
export type ReportWeekFragmentFragment = {
	__typename?: "ReportWeekModel";
	id: number;
	inputRows: Array<InputsFragmentFragment >;
};
```

`codegen.yml`

```yml
overwrite: true
schema: "http://localhost:58909/graphql/"
documents: "src/**/*.graphql"
generates:
  ./src/generated/schema.graphql:
    plugins:
      - "schema-ast" # Dump schema to local file.

  ./src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"

  ./src/generated/graphql.schema.json:
    plugins:
      - "introspection"

  ./src/fragment-matcher.ts:
    plugins:
      - "fragment-matcher"
```
