### DISCUSSION TITLE
Generating resolver types for multiple resolver files

### DISCUSSION THREAD

**Discussion by seanlennaerts** [dotansimha/graphql-code-generator#8146] [Q&A] [answered]
Let's say I have a project with the following structure:
```
src/
├── user/
│   ├── user.model.ts
│   ├── user.resolver.ts
│   └── user.graphql
└── todo/
    ├── todo.model.ts
    ├── todo.resolver.ts
    └── todo.graphql
```
I would like to generate resolver types for both `user.resolver.ts` and `todo.resolver.ts`. I've tried it with graphql-modules and that works great but I saw this line in the graphql-modules preset [docs](https://www.graphql-code-generator.com/plugins/presets/graphql-modules-preset#using-without-graphql-modules):

> you can set useGraphQLModules: false in your preset configuration to generate fully agnostic types that are based on folder structure only.

and would prefer a solution that let's me just generate types without migrating everything to use the graphql-modules framework.

This is my codegen.yml:
```yml
overwrite: true
schema: 'src/**/*.graphql'
documents: null
generates:
  src/generated/:
    preset: graphql-modules
    presetConfig:
      baseTypesPath: ../__generated__/graphql.ts
      filename: __generated__/module-types.ts
      useGraphQLModules: false
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
```

After running this it only creates the base types in `src/__generated__/graphql.ts`. Has anyone else had success with this? Am I on the right track?

I created this repl.it that reproduces the scenario described. Can be helpful for those that want to fork and play around: https://replit.com/@seanlenny/graphql-codegen-with-multiple-resolver-files

**Comment by seanlennaerts** [comment, marked as answer]
Had a mistake in the codegen.yml:
```yml
...
generates:
  src/: # should be src/
    preset: graphql-modules
    presetConfig:
      baseTypesPath: ./__generated__/graphql.ts # adjust relative path
```
