### DISCUSSION TITLE
Multiple Introspection

### DISCUSSION THREAD

**Discussion by davidkhierl** [dotansimha/graphql-code-generator#8180] [Q&A] [answered]
Is it possible to generate two introspection? my project setup uses two different schema. one is for public consumer and the other one is for admin.

I managed to generate the two schema `.ts` file, but now I'm stuck on the introspection

**Comment by charlypoly** [comment, marked as answer]
Hi @davidkhierl,

it is not well documented, but the `schema` option of your `codegen.yml` can take an array of multiple schemas:

> You can specify either a single schema or multiple, and GraphQL Code Generator will merge the schemas into a single schema.

The following would work:

```yml
schema:
  - http://localhost:3000/graphql:
      headers:
        Authorization: YOUR-TOKEN-HERE
  - http://localhost:3001/graphql:
      headers:
        Authorization: YOUR-TOKEN-HERE  
```

or 

```yml
schema:
  - http://localhost:3000/graphql
  - http://localhost:3001/graphql
```

Also, `schema` can be specified both at the root level and output-file level: https://www.graphql-code-generator.com/docs/config-reference/schema-field#multiple-schemas-and-client-side-schema.

Let me know if it helped.

**Reply by davidkhierl** [reply]
Oh hey @charlypoly from the chat! 😃 thank you for the reply!

Yes I finally made the schema works and it generates the files.

I have question when using the root level. how can I tell to separate the output file or in that case I should put it on the output-file level?
```yaml
schema:
  - http://localhost:3000/graphql
  - http://localhost:3001/graphql
```

Now I'm doing the introspection like so

```yaml
  ./src/graphql/generated/public-graphql.schema.json:
    schema:
      - "http://localhost:3000/graphql":
          headers:
            Authorization: YOUR-TOKEN-HERE
    plugins:
      - "introspection"

  ./src/graphql/generated/admin-graphql.schema.json:
    schema:
      - "http://localhost:3001/graphql":
          headers:
            Authorization: YOUR-TOKEN-HERE
    plugins:
      - "introspection"
```

Is this correct? the files is being generated somehow but the command line outputs `exit with code 1`
