### DISCUSSION TITLE
Plugin to generate GQL file for the schema

### DISCUSSION THREAD

**Discussion by alamothe** [dotansimha/graphql-code-generator#8225] [General] [answered]
Hello,
I'm looking for a simple plugin to generate a GQL file for the whole schema for documentation purposes. Is there such a thing?

**Comment by charlypoly** [comment, marked as answer]
Hi @alamothe,

The [`@graphql-codegen/schema-ast`](https://www.graphql-code-generator.com/plugins/other/schema-ast) plugin will generate a `schema.graphql` file from a schema, with the example configuration:

```yaml
# …
schema:
  - 'http://localhost:3000/graphql'
  - './src/**/*.graphql'
  - 'scalar MyCustomScalar'
generates:
  path/to/file.graphql:
    plugins:
      - schema-ast
```

Is it what you are looking for? 👀
