### DISCUSSION TITLE
[gql-tag-operations-preset] Using gql'' instead of gql('') will not include fragment

### DISCUSSION THREAD

**Discussion by yicru** [dotansimha/graphql-code-generator#8246] [Q&A]
## Fragment is included in the request
```typescript
const SampleFragment = gql(/* GraphQL */ `
  fragment Sample_sample on Sample {
    key
  }
`)

const ExampleGraphqlPageQuery = gql(/* GraphQL */ `
  query ExampleGraphqlPageQuery {
    sample {
      ...Sample_sample
    }
  }
`)
```

## Fragment is not included in the request
```typescript
const SampleFragment = gql`
  fragment Sample_sample on Sample {
    key
  }
`

const ExampleGraphqlPageQuery = gql`
  query ExampleGraphqlPageQuery {
    sample {
      ...Sample_sample
    }
  }
`
```

***

# Question

Is there a difference between the two?
We are using the augmentedModuleName option and the babel plugin and I think that is the cause.

```yml:codegen.yml
schema: ${NEXT_PUBLIC_GRAPHQL_URL}
documents:
  - 'src/**/*.{tsx,ts}'
  - '!src/lib/graphql/**/*'
generates:
  src/lib/graphql/gql:
    preset: gql-tag-operations-preset
    presetConfig:
      augmentedModuleName: '@urql/core'
    config:
      arrayInputCoercion: true
      enumsAsConst: true
      strictScalars: true
```

```javascript:babel.config.js
const { babelPlugin } = require('@graphql-codegen/gql-tag-operations-preset')

module.exports = {
  plugins: [[babelPlugin, { artifactDirectory: './src/lib/graphql/gql' }]],
  presets: ['next/babel'],
}
```

|  package  |  version  |
| ---- | ---- |
|  @graphql-codegen/cli  |  "2.11.6" |
|  @graphql-codegen/gql-tag-operations-preset  |  "1.5.4" |
| urql |  "2.2.3" |
| next |  "12.2.4" |
