### DISCUSSION TITLE
GraphQL Code Generator takes a lot of time to generate the result

### DISCUSSION THREAD

**Discussion by nandita1** [dotansimha/graphql-code-generator#8293] [Q&A] [answered]
It takes almost 70-80 seconds for the code generation to happen whereas Apollo codegen used to take only 15 seconds.
Here is my codegen.yaml file. Can anyone please tell me a way around this
```
schema: src/gql/schema.json
documents:
  - 'src/**/*.tsx'
  - '!src/generated/**/*'
generates:
  ./src/possibleTypesData.ts:
    plugins:
      - fragment-matcher
      - add:
          content: |
            /** THIS FILE IS AUTO-GENERATED **/
            /** DO NOT EDIT **/
            /* eslint-disable */
            /* tslint:disable */
  ./src/types.ts:
    plugins:
      - typescript
      - typescript-operations
      - add:
          content: |
            /** THIS FILE IS AUTO-GENERATED **/
            /** DO NOT EDIT **/
            /* eslint-disable */
            /* tslint:disable */
    config:
      namingConvention: keep # Keeps naming as-is
      avoidOptionals: # Avoids optionals on the level of the field
        field: true
      nonOptionalTypename: true # Forces `__typename` on all selection sets
      skipTypeNameForRoot: true # Don't generate __typename for root types
      scalars:
        Long: number
        UUID: string
        DateTime: string
        LocalTime: string
        Duration: string
        Void: void
        URL: URL
      immutableTypes: true
      declarationKind: 'interface'
      dedupeOperationSuffix: true
      onlyOperationTypes: true
      prettify: false
```

**Comment by ardatan** [comment]
We cannot tell much because it depends on your schema's size, environment etc. That's why, we always ask for details and a reproduction repo or sandbox on GitHub, CodeSandbox or StackBlitz.
You can find the details here we need in order to help you
https://github.com/dotansimha/graphql-code-generator/issues/new?assignees=&labels=&template=bug_report.yml

**Reply by nandita1** [reply]
I don’t think it’s helpful even if I send you a sandbox link in this case. This is production code and I can’t share it. But the main thing where it is taking time is in Loading the documents. But it doesn’t happen with Apollo codegen. Do you think I can optimise it in any way? Also, isn’t there any caching mechanism you have in place where you don’t generate the types if the schema hasn’t changed?

**Comment by charlypoly** [comment, marked as answer]
We did follow up with @nandita1 in private since performance is most of the time a project-specific topic; **however, we recommend the following for large-scale projects:**

- if you are facing some performances issue, try the codegen profile to narrow down where the time is spent before reaching out to us: https://www.the-guild.dev/graphql/codegen/docs/advanced/profiler
- for large Schemas, we recommend disabling validation and running validations outside of codegen (ex, with [GraphQL Inspector](https://www.the-guild.dev/graphql/inspector)) by adding the  `skipDocumentsValidation` config flag as follows:

```yaml
schema: schema.graphql
documents:
  - src/**/*.ts
generates:
  src/generated/schema.ts:
    config:
      skipDocumentsValidation: true
    plugins:
      - "schema-ast"
  src/generated/types.ts:
    plugins:
      - typescript
    config:
      skipDocumentsValidation: true
      useTypeImports: true
      nonOptionalTypename: true
      scalars:
        JSON: unknown
        Number: number
```

- also, for projects having a high number to parse for operations, we recommend ensuring that the `documents` is properly narrowing the glob expression
