### DISCUSSION TITLE
Missing random types from 'typescript-operations' plugin

### DISCUSSION THREAD

**Discussion by jeggy** [dotansimha/graphql-code-generator#8308] [Q&A] [answered]
I just moved from `apollo-tooling` to `graphql-codegen` in a huge project and now everything is compiled into a single file, which I don't have a problem with, but it seems like it's sometimes just misses some operations via the `typescript-operations` plugin. The exported file is about 40+k lines.

I can't figure out what it is I'm doing wrong and adding `--verbose` or `--debug` doesn't bring any useful information.

I for example have this query defined in a `tsx` file 
```typescript
const RemoveSegmentationCodeMutation = gql`
  mutation RemoveSegmentationCode(
    $id: Int!,
  ) {
    removeSegmentationCode(personId: $id)
  }
`;
```

and after running `graphql-codegen` it still won't be added to my exported file.

My configuration looks like this:
```yml
generates:
  src/gql/typings.tsx:
    config:
      namingConvention: keep
      exportFragmentSpreadSubTypes: true
      inlineFragmentTypes: combine
      nonOptionalTypename: true
    plugins:
      - "typescript"
      - "fragment-matcher"
      - "typescript-react-apollo"
      - "typescript-operations"
```
