### DISCUSSION TITLE
Split typescript types from resolvers

### DISCUSSION THREAD

**Discussion by remko79** [dotansimha/graphql-code-generator#8375] [Q&A] [answered]
I have a big set of files with different types and resolvers and for several reasons, I'd like to split up the generated typescript files for the graphql types from the resolvers, so let's say we have this schema and resolvers (very simplified):
```
type User {
  id: ID!
  uuid: String
  name: String
}

type UserContent {
  data1: String
  data2: String
}

type Query {
    getUser: User
    getUserContent: UserContent
}

const resolvers: Resolvers = {
  Query: {
    getUser: () => new UserModel({...}),
    getUserContent: () => new UserContent({...}),
  }
}
```

Now currently I generate one big file for typescript:
```
overwrite: true
schema:
  - 'src/graphql/**/schema.ts'
generates:
  src/generated/graphql.d.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
```
But I'd like to split it, something like :
```
overwrite: true
schema:
  - 'src/graphql/**/schema.ts'
generates:
  src/generated/graphql_types.d.ts:
    plugins:
      - "typescript"
  src/generated/graphql_resolvers.d.ts:
    plugins:
      - "typescript-resolvers"
```
In this case the `graphql_types.d.ts` file is fine, but the `graphql_resolvers.d.ts` file doesn't know anything about the previously generated types, so that file is invalid. Is there any way to resolve that easily or another way to do this?
