### DISCUSSION TITLE
Fetcher generated multiple times for preset near-operation-file

### DISCUSSION THREAD

**Discussion by john-persson-polestar** [dotansimha/graphql-code-generator#8526] [General]
Hi,

I have setup `typescript-react-query` with the `near-operation-file` preset which gives me a problem with the fetcher function.

If you're not familiar `near-operation-file` is a preset which outputs the generated file right next to the source `.graphql` file.
As it turns out the fetcher function gets generated multiple times at the top of each output file.
is there any way around this that I'm missing?

Here is my full `codegen.yml`:

``` yml
overwrite: true
schema:
  - ${NEXT_PUBLIC_DATO_API_URL}:
      headers: { Authorization: "Bearer ${NEXT_PUBLIC_DATO_TOKEN}" }
      credentials: include
      content-type: application/json
generates:
  ./@types/graphql.generated.ts:
    plugins:
      - "typescript"
  ./graphql.schema.json:
    plugins:
      - "introspection"
  ./:
    documents: "./**/*.graphql"
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: ./@types/graphql.generated.ts
    plugins:
      - "typescript-operations"
      - "typescript-react-query"
    config:
      fetcher:
        endpoint: ${NEXT_PUBLIC_DATO_API_URL}
        fetchParams:
          headers: { Authorization: "Bearer ${NEXT_PUBLIC_DATO_TOKEN}" }
          credentials: include
          content-type: application/json
```

Thank you for an amazing library!

Best,
/John
