### DISCUSSION TITLE
graphql/codegen/plugins/typescript/typescript-vue-apollo

### DISCUSSION THREAD

**Discussion by giscus** [dotansimha/graphql-code-generator#8619] [Docs Discussions]
# graphql/codegen/plugins/typescript/typescript-vue-apollo

GraphQL Code Generator Documentation

https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-vue-apollo

**Comment by szatesz** [comment]
When will it be compatible with Vue 3? The @vue/composition-api package is not required in Vue 3 for Ref.

**Reply by szatesz** [reply]
Just import { Ref } from 'vue';

**Reply by productdevbook** [reply]
this

```
schema: ../../apps/nestjs/schema.graphql
# schema: http://localhost:4000/graphql
generates:
  ../../apps/vue-web/src/graphql/vue/index.ts:
    plugins:
      - add: { content: '// THIS FILE IS GENERATED, DO NOT EDIT!' }
      - add: { content: '/* eslint-disable eslint-comments/no-unlimited-disable */' }
      - add: { content: '/* tslint:disable */' }
      - add: { content: '/* eslint-disable */' }
      - add: { content: '// @ts-nocheck' }
      - typescript
      - typescript-operations
      - typescript-apollo-client-helpers
      - typescript-vue-apollo
      - named-operations-object
    config:
      enumsAsTypes: true
      withCompositionFunctions: true
      vueApolloComposableImportFrom: '@vue/apollo-composable'
      vueCompositionApiImportFrom: vue
```
