### DISCUSSION TITLE
Duplicate Identifier in src/**/graphql.ts

### DISCUSSION THREAD

**Discussion by hitchcliff** [dotansimha/graphql-code-generator#8709] [Q&A] [answered]
Hi Guys, I'm getting tons of Duplicate Identifiers Errors in graphql.ts file.

`package.json`:
```

  "scripts": {
    "gql": "graphql-codegen --config codegen.yml"
  },

    "@graphql-codegen/cli": "2.15.0",
    "@graphql-codegen/client-preset": "1.2.1",
    "@graphql-codegen/typescript": "^2.8.3",
    "@graphql-codegen/typescript-compatibility": "^2.1.5",
    "@graphql-codegen/typescript-operations": "^2.5.8",
    "@graphql-codegen/typescript-urql": "^3.7.3",
```
`codegen.yml`:
```
overwrite: true
schema: "http://localhost:4000/graphql"
documents: "./src/graphql/**/*.graphql"
generates:
  ./src/gql/:
    preset: "client"
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-urql"

```

`src/graphql/mutations/login.graphql`
```
mutation Login($options: LoginInput!) {
  login(options: $options) {
    errors {
      field
      message
    }
    user {
      id
      username
      createdAt
      updatedAt
    }
  }
}
```

I ran `yarn gql` to generate mutation hooks to fetch my API but NextJS is giving me nasty errors (screenshots below). I am not sure what's causing it, anybody can help?

<img width="906" alt="Screenshot_25" src="https://user-images.githubusercontent.com/44961093/206204449-e850ae8d-c730-4da4-b85b-20f985c5ac4d.png">
<img width="732" alt="Screenshot_26" src="https://user-images.githubusercontent.com/44961093/206204468-b48fce97-5bc9-4f86-9b6c-120e024f5051.png">

**Comment by hitchcliff** [comment, marked as answer]
the problem in here seems to be related to `codegen.yml`

```
overwrite: true
schema: "http://localhost:4000/graphql"
documents: "src/graphql/**/*.graphql"
generates:
  ./src/gen/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - urql-introspection
      - typescript-urql
```

i removed the `preset: "client"` and changed generates to `./src/gen/graphql.ts` 

seems to be working now...
