### DISCUSSION TITLE
Generated operations files don't include *.js extension in ESM project

### DISCUSSION THREAD

**Discussion by JumBay** [dotansimha/graphql-code-generator#8710] [Q&A] [answered]
I did follow the doc here https://the-guild.dev/graphql/codegen/docs/getting-started/esm-typescript-usage, but the generated file don't include `*.js` extension in the import line

Here is my test repository https://github.com/JumBay/test-codegen and the codegen config file 
https://github.com/JumBay/test-codegen/blob/main/.graphqlrc.yml. 

If anyone see what's wrong?

**Comment by ardatan** [comment, marked as answer]
@JumBay Codegen configuration in `.graphqlrc.yml` should be under `codegen:`.
So it needs to be;
```ymlschema: https://countries.trevorblades.com/
documents:
  - ./src/**/*.graphql
extensions:
  codegen:
    emitLegacyCommonJSImports: true
    generates:
      ./src/generated/types.ts:
        plugins:
          - typescript
          - typescript-operations
      ./src/:
        preset: near-operation-file
        presetConfig:
          extension: .generated.ts
          baseTypesPath: generated/types.ts
        plugins:
          - typescript-operations
          - typed-document-node
```
