### DISCUSSION TITLE
Why is sort not a normal config ?

### DISCUSSION THREAD

**Discussion by erwan-joly** [dotansimha/graphql-code-generator#8727] [Q&A]
Hi, I'm trying to understand why sort is not on the same position as other config in the yml file.

Here two variants that seems to works:
```
sort: false
generates:
    ./src/graphql/_generated.tsx:
        schema: ".."
        documents: ['graphql/**/*.gql']
        plugins:
            - typescript
            - typescript-operations
            - typescript-react-apollo
            - typescript-resolvers
            - typescript-apollo-client-helpers
            - typescript-validation-schema
        config:
        ...
``` 
and 
```
config:
      sort: false
generates:
    ./src/graphql/_generated.tsx:
        schema: ".."
        documents: ['graphql/**/*.gql']
        plugins:
            - typescript
            - typescript-operations
            - typescript-react-apollo
            - typescript-resolvers
            - typescript-apollo-client-helpers
            - typescript-validation-schema
        config:
        ...
``` 

However this variant doesn't  work and I believe other configuration looks a lot more like that
```

generates:
    ./src/graphql/_generated.tsx:
        schema: ".."
        documents: ['graphql/**/*.gql']
        plugins:
            - typescript
            - typescript-operations
            - typescript-react-apollo
            - typescript-resolvers
            - typescript-apollo-client-helpers
            - typescript-validation-schema
        config:
            sort: false
```
