### DISCUSSION TITLE
Where can I find the query name ? (React and Apollo Client)

### DISCUSSION THREAD

**Discussion by blatoo** [dotansimha/graphql-code-generator#8783] [Q&A] [answered]
Hi all,

I am using React with Apollo Client, and my `codegen.yml` is: 
https://the-guild.dev/graphql/codegen

```
generates:
  src/generated/graphql.tsx:        
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo`
  ```

After running codegen, I successfully get all `use...Mutation()`s, for example `useCreateJobMutation()` to create a job:

```
const [createJobMutation, { data, loading, error }] = useCreateJobMutation()
```

After running the `createJobMutation`, I want to **update** the `Job` query, but I can't find the object of`JobQuery`...(It has only `JobQuery` type, but I can not pass the type to the `update: ` )

In CreateJob.tsx:
```
import {JobQuery} from '../generated/graphql';  // Why here is only "JobQuery" type, but not object????

...
    createJobMutation(
      {
       variables: {...},
       update: (cache, {data}) =>{
        cache.writeQuery({
            query: JobQuery,  # Error!!! It is type, but not object...  -_-"
            ...
        })}
      } 
    )
...

```

The problem is, I can not find the `JobQuery` object, what I get from the `src/generated/graphql.tsx` is only the JobQuery Type.

How can I do it correctly?
