### DISCUSSION TITLE
Minifying GQL in production build

### DISCUSSION THREAD

**Discussion by RadomirNowak** [dotansimha/graphql-code-generator#8990] [Q&A]
Hey everyone
In my current project we're using graphql-codegen to generate types based on hosted schema.
We use `graphql-tag` to write our queries in files like `gql.ts`, for example:
```
export const getOrganizationQuery = gql`
   query getOrganization....
`;
```

I've just analyzed our production build and its **huge**, and my assumption is that its mainly because all gql queries inside of `index.js` are not minified, so all whitespaces etc. are preserved.

Now I believe that just by minifying these gql statements we'd take down the size of the bundle by **a lot**. The question that I have is how or which options in `codegen.yml`, or which plugins would allow me to do that?

Below I'll post a snippet of our `codegen.yml`. Any help appreciated, thanks!!

```
documents:
  - src/**/(gql|queries|mutations|fragments).ts
  - src/**/(gql|queries|mutations|fragments)/*.ts
generates:
src/generated-types/graphql.types.tsx:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
      - 'add'
    config:
      withHooks: true
      withComponent: false
      withHOC: false
      content: |
        import { ISO8601DateTimeString } from 'utils/gql-date-scalar-type';
      strictScalars: true
      scalars: *custom_scalars
      preResolveTypes: false
      experimentalFragmentVariables: true
      exportFragmentSpreadSubTypes: true
      mergeFragmentTypes: true
      dedupeFragments: true
      inlineFragmentTypes: 'combine'
      maybeValue: 'T | null | undefined'
```
