### DISCUSSION TITLE
Implicit "any" type in generated .ts files?

### DISCUSSION THREAD

**Discussion by olalonde** [dotansimha/graphql-code-generator#9112] [Q&A] [answered]
Getting those errors after generating and trying to compile with typescript:

```typescript
src/api/graphql/generated/client/gql.ts:5:7 - error TS7034: Variable 'documents' implicitly has type 'any[]' in some locations where its type cannot be determined.

5 const documents = [];
        ~~~~~~~~~

src/api/graphql/generated/client/gql.ts:21:11 - error TS7005: Variable 'documents' implicitly has an 'any[]' type.

21   return (documents as any)[source] ?? {};
             ~~~~~~~~~

```

My `codegen.yaml`:

```yaml
overwrite: true
schema: "./src/api/graphql/schema.graphql"
documents: null
generates:
  ./src/api/graphql/generated/client/:
    preset: "client-preset"
  ./src/api/graphql/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
    config:
      enumsAsConst: true
```

Is it normal? Any way to get tsc to compile those files?
