### DISCUSSION TITLE
Enabling generation of useXXXXXMutation() creates duplicate xxxxxDocument consts

### DISCUSSION THREAD

**Discussion by ptheofan** [dotansimha/graphql-code-generator#9262] [Q&A]
### The Goal
I want to have typed graphql mutations and queries to save me from myself. The generator creates some wonderful functions such as `useLoginWithCredentialsMutation` from code such as this.
```graphql
  mutation loginWithCredentials($input: LoginInput!) {
    authLogin(input: $input) {
      accessToken,
      refreshToken,
      userId,
    }
  }
```

### The Issue
These wonderful `usexxxxMutation` functions are generated when i use the plugin `typescript-vue-apollo`. However using the preset `client` as well creates duplicate constants.

Enabling both the preset and the plugin I get the document generated in both string and AST format
```ts
export const LoginWithCredentialsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"LoginWithCredentials"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"input"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"LoginInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"authLogin"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"input"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"accessToken"}},{"kind":"Field","name":{"kind":"Name","value":"refreshToken"}},{"kind":"Field","name":{"kind":"Name","value":"userId"}}]}}]}}]} as unknown as DocumentNode<LoginWithCredentialsMutation, LoginWithCredentialsMutationVariables>;

export const LoginWithCredentialsDocument = gql`
    mutation LoginWithCredentials($input: LoginInput!) {
  authLogin(input: $input) {
    accessToken
    refreshToken
    userId
  }
}
    `;
```

Of course, this does not work hence `const LoginWithCredentialsDocument` is declared twice.

I have tried several options and combinations in the `codegen.yml` file but with no luck

```yaml
overwrite: true
schema: './schema.graphql'
documents:
  - './src/**/*.graphql.ts'
generates:
  ./src/graphql/:
    preset: 'client'
    config:
      useDeduplication: true
      constEnums: true
      enumsAsConst: true
      enumsAsTypes: true
      immutableTypes: true
      useImplementingTypes: true
      vueCompositionApiImportFrom: vue
      useTypeImports: true
      withCompositionFunctions: true
      gqlImport: vue-apollo/graphql
    plugins:
# Disable vue-apollo and generation will not create duplicate consts BUT the useLoginWithCredentialsMutation is also not generated.
      - 'typescript-vue-apollo'
```
