### DISCUSSION TITLE
How can I separate schema types from operation types?

### DISCUSSION THREAD

**Discussion by nathanhae** [dotansimha/graphql-code-generator#9347] [Q&A]
I'm working on a monorepo typescript/nextjs/apollo project with two main app packages and a third "shared" package for common components. I would like to extract basic schema types into a separate "types" file in the shared package so that they are not duplicated across packages, and then allow each individual package (including "shared") to define .graphql files with their own unique operations. I'm attempting to do this with the import-types preset like so:

```yaml
overwrite: true
schema: 'https://schema.com'
generates:
  packages/shared/api/types.ts:
    plugins:
      - 'typescript'
  packages/shared/api/index.ts:
    preset: import-types
    presetConfig:
      typesPath: ./types
    documents: 'packages/shared/**/*.graphql'
    plugins:
      - 'typescript-operations'
      - 'typescript-react-apollo'
  packages/foo/api/index.ts:
    preset: import-types
    presetConfig:
      typesPath: shared
    documents: 'packages/foo/**/*.graphql'
    plugins:
      - 'typescript-operations'
      - 'typescript-react-apollo'
  packages/bar/api/index.ts:
    preset: import-types
    presetConfig:
      typesPath: shared
    documents: 'packages/bar/**/*.graphql'
    plugins:
      - 'typescript-operations'
      - 'typescript-react-apollo'
```

This _almost_ works except that the operation types generated by 'typescript-react-apollo' are incorrectly referenced as though they are defined in types.ts, even though they are (correctly) defined in the main api file.

Can anybody think of a workaround for this, or a way to make a custom plugin that fixes the problem? I've been playing around with the plugin API, but it seems like there isn't a good way to modify the output of previous plugins/presets, unless i'm missing something. Help!
