### DISCUSSION TITLE
near-operation-file outputs unusable filename

### DISCUSSION THREAD

**Discussion by AndreasPB** [dotansimha/graphql-code-generator#9463] [Q&A] [answered]
Hi :wave: 

I'm having issues with the `near-operation-file`-plugin in my sveltekit project.

I'd like to generate the interfaces of my query from a `+page.svelte`-file, but that outputs a `+page.generated.ts`-file, which isn't allowed by sveltekit (the `+` prefix is reserved)

Is there a way to define what the entire output file is going to look like?

This is the way my `codegen.yml` is currently setup:
```yml
schema: "http://127.0.0.1:5001/graphql/v3"
documents:
  - "**/*.{graphql,gql,svelte}"
generates:
  src/lib/graphql/types.ts:
    plugins:
      - typescript

  src/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: types.ts
    plugins:
      - typescript-operations
```
