### DISCUSSION TITLE
error:  Multiple exports of name 'HttpMethod'

### DISCUSSION THREAD

**Discussion by rushairer** [dotansimha/graphql-code-generator#9504] [Q&A]
Versions:
```json
        "@graphql-codegen/cli": "^4.0.1",
        "@graphql-codegen/fragment-matcher": "^5.0.0",
        "@graphql-codegen/introspection": "^4.0.0",
        "@graphql-codegen/schema-ast": "^4.0.0",
        "@graphql-codegen/typed-document-node": "^5.0.0",
        "@graphql-codegen/typescript": "^4.0.0",
        "@graphql-codegen/typescript-graphql-files-modules": "^2.2.1",
        "@graphql-codegen/typescript-operations": "^4.0.0",
        "@graphql-codegen/typescript-react-apollo": "^3.3.7",
        "@graphql-codegen/urql-introspection": "^2.2.1",


        "eslint-plugin-import": "^2.27.5",


```

Config:
```yaml
overwrite: true
schema:
    - https://xxxxx:
          headers:
              Authorization: Bearer xxxxxx
documents: 'graphql/**/*.graphql'
generates:
    src/services/graphql.tsx:
        config:
            withHooks: true
        plugins:
            - 'typescript'
            - 'typescript-operations'
            - 'typescript-react-apollo'
```
Command:
```bash
graphql-codegen --config graphql/codegen.yml && eslint src/services/graphql.tsx --fix
```
Got Error:
```bash
........   /src/services/graphql.tsx
  562:13  error  Multiple exports of name 'HttpMethod'  import/export
  588:13  error  'HttpMethod' is already defined        @typescript-eslint/no-redeclare
  588:13  error  Multiple exports of name 'HttpMethod'  import/export
```

How to fix it?  Thanks!
