### DISCUSSION TITLE
Plugin typescript-mock-data doesn't resolve Apollo Fragments

### DISCUSSION THREAD

**Discussion by eppisapiafsl** [dotansimha/graphql-code-generator#9900] [Q&A]
Hi there! 

I'm integrating the plugin typescript-mock-data in a React Native project that uses Apollo and Codegen; the plugin generates the file with the mocks but doesn't resolve/import the fragment properly.

It looks like it uses the `__typename` property over the declared type, which I guess is the expected because that is the value in the Query Document 😓 .

Is there a way to configure it to use the Fragment types instead?

| Schema Fragment | Code Gen Import |
| --- | --- |
| ![Screenshot 2024-03-14 at 4 58 25 PM](https://github.com/dotansimha/graphql-code-generator/assets/82107248/f2ffd508-6ea4-42e2-b7d2-f4573f45ecb6) | ![Screenshot 2024-03-14 at 4 20 53 PM](https://github.com/dotansimha/graphql-code-generator/assets/82107248/25b18e60-b9d0-4425-9e41-3218f3516176) |

### codegen

```
  src/modules/async/schema.ts:
    plugins:
      - add: *top-comment
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      skipTypename: false
      apolloReactHooksImportFrom: "./codegen.apollo.module"
      withHooks: true
  src/TestMocks/generated-apollo-mocks.ts:
    plugins:
      - typescript-mock-data:
          typesFile: "src/modules/async/schema"
          enumValues: upper-case#upperCase
          typeNames: keep
          addTypename: true
          enumsAsTypes: true
          prefix: apolloMock
          scalars:
            AchvAchievement: AchvAchievementFragment
```

### Package json

"@graphql-codegen/cli": "5.0.0",
"@graphql-codegen/typescript": "4.0.1",
"@graphql-codegen/typescript-operations": "4.0.1",
"@graphql-codegen/typescript-react-apollo": "3.3.7",
"@graphql-codegen/typescript-resolvers": "4.0.1",
"graphql-codegen-typescript-mock-data": "3.7.1",

Thank you
