### DISCUSSION TITLE
What does client-preset do?

### DISCUSSION THREAD

**Discussion by UchihaYuki** [dotansimha/graphql-code-generator#9983] [Q&A]
The doc goes:
> We recommend using [a client preset](https://the-guild.dev/graphql/codegen/plugins/presets/preset-client) that has a recommended configuration for the client applications.

> The client-preset provides typed GraphQL operations (Query, Mutation and Subscription) by perfectly integrating with your favorite GraphQL clients:

I started to use graphql-code-generator several years ago, back then I only needed to provide plugins in a file called `codegen.yml`, for example:
```
...
  ts/graphql/api.codegen.ts:
    schema: "http://localhost:6004/api"
    documents: "./ts/graphql/*.gql"
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-graphql-request"
```
And it's enough, so what does client-preset do here?

Do I still need those plugins if I use client-preset? or Can I ignore it?
