### DISCUSSION TITLE
Which plugins should I use with `graphql-ws` client?

### DISCUSSION THREAD

**Discussion by UchihaYuki** [dotansimha/graphql-code-generator#9985] [Q&A]
I haven't found a plugin designed specifically for this client. So I use the following plugins instead:
```
  ts/graphql/api.codegen.ts:
    schema: "http://localhost:6004/api"
    documents: "./ts/graphql/*.gql"
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-graphql-request"
```
So I have to write some boilerplate code myself as followings:
```
import { createClient, SubscribePayload } from "graphql-ws";
import { Observable } from "rxjs";
import {
  PassphraseLoginMutation,
  PassphraseLoginMutationVariables,
  PassphraseLoginDocument,
  GoogleLoginMutation,
  GoogleLoginMutationVariables,
  GoogleLoginDocument,
} from "./api.codegen";

const client = createClient({
  url: `wss://${location.hostname}/api`,
});

function toObservable<Value>(payload: SubscribePayload) {
  return new Observable<Value>((observer) =>
    client.subscribe(payload, {
      next: (data) => observer.next(data as Value),
      error: (err) => observer.error(err),
      complete: () => observer.complete(),
    })
  );
}

export const api = {
  passphraseLogin(variables: PassphraseLoginMutationVariables) {
    return toObservable<PassphraseLoginMutation>({
      query: PassphraseLoginDocument,
      variables
    });
  },
  googleLogin:(variables: GoogleLoginMutationVariables) {
    return toObservable<GoogleLoginMutation>({
      query: GoogleLoginDocument,
      variables
    });
  },
};
```
The problem is both `PassphraseLoginDocument` and `GoogleLoginDocument` are DocumentNode not string:
```
export const PassphraseLoginDocument = gql`
    mutation passphraseLogin($passphrase: String!) {
  passphraseLogin(passphrase: $passphrase)
}
    `;
export const GoogleLoginDocument = gql`
    mutation googleLogin($googleIdToken: String!) {
  googleLogin(googleIdToken: $googleIdToken)
}
    `;
```
What's your recommend for me? Thank you!
