### ISSUE TITLE
Generating new file doesn't overwrite existing

### ISSUE THREAD

**Issue by RadAcademy** [dotansimha/graphql-code-generator#1001]
Generating of the new graphql file does not overwrite the previous file. I have to manually delete the old to allow the plugin to generate a fresh new one.

My codegen.yml
```
schema:
  - "http://localhost:4000/graphql"
documents:
  - "src/client/graphql/**/*.graphql"
config: {}
generates:
  src/client/app/core/graphql/graphql.ts:
    config: {}
    plugins:
      - "typescript-common"
      - "typescript-client"
      - "typescript-apollo-angular"
require: []
```

The expected behavour before was it would overwrite the old file?

**Comment by dotansimha** [comment]
Hi @RadAcademy ! 

Please try to add `overwrite: true` to your configuration:

```
schema: "http://localhost:4000/graphql"
documents: "src/client/graphql/**/*.graphql"
generates:
  src/client/app/core/graphql/graphql.ts:
    plugins:
      - typescript-common
      - typescript-client
      - typescript-apollo-angular
overwrite: true
```
