### ISSUE TITLE
Getting 'Cannot find namespace' Error

### ISSUE THREAD

**Issue by vdiaz1130** [dotansimha/graphql-code-generator#1042]
Current Setup

    graphql-code-generator: ^0.15.0
    graphql-codegen-typescript-apollo-angular: 0.15.0
    graphql-codegen-typescript-common: 0.15.0
    dir `./workspace/api/` contains graphql server (running on `localhost:4000`)
    dis `./workspace/client/libs/api/src/lib/auth/graphql/` contains `loginMutation.graphql`

./workspace/client/codegen.yml

    schema:
        - "../api/src/schema.graphql"
    documents: ["./libs/api/src/lib/auth/graphql/**/*.graphql"]
    config:
        avoidOptionals: true
    generates:
        ./libs/api/src/lib/auth/graphql/generated/types.ts:
            plugins:
                - typescript-apollo-angular
    require: []

loginMutation.graphql

    mutation login {
        login(email: "foo@test.com", password: "testtest") {
            token
            user {
                email
                firstName
            }
        }
    }

Running gql-gen creates this file (by the way I have to manually delete the generated file each time; np will use rimraf)

gql-gen command output:

    gql-gen
        ✔ Parse configuration
        ✔ Generate outputs

Generated ./libs/api/src/lib/auth/graphql/generated/types.ts

    import { Injectable } from '@angular/core';
    import * as Apollo from 'apollo-angular';
    
    import gql from 'graphql-tag';
        
    @Injectable({
      providedIn: 'root'
    })
    export class LoginGQL extends Apollo.Mutation<Login.Mutation, Login.Variables> {
      document: any = gql`
        mutation login {
          login(email: "foo@test.com", password: "testtest") {
            token
            user {
              email
              firstName
            }
          }
        }
      `;
    }

The problem is TypeScript is not compiling because of `Login.Mutation` and `Login.Variables`. Getting error `Cannot find namespace 'Login'` - it has no idea where `Login` comes from and neither do I.

I tried using schema URL...

    schema:
      - "http://localhost:4000"

Any ideas? Am I missing something?

Thanks!

**Comment by dotansimha** [comment]
Hi @vdiaz1130 ! 

The `typescript-apollo-angular` plugin goes together with `typescript-common` and `typescript-client`. Change your config to: 

```
schema: ../api/src/schema.graphql
documents: "./libs/api/src/lib/auth/graphql/**/*.graphql"
config:
    avoidOptionals: true
generates:
    ./libs/api/src/lib/auth/graphql/generated/types.ts:
        plugins:
            - typescript-common
            - typescript-client
            - typescript-apollo-angular
```
