### ISSUE TITLE
Watch mode not working

### ISSUE THREAD

**Issue by swcarlosrj** [dotansimha/graphql-code-generator#1048]
**Describe the bug**
Watch mode is not working neither with chokidar nor watchman, always it's 'Watching for changes...' 

**To Reproduce**
1. Clone repository: git clone -b graphql-ts https://github.com/swcarlosrj/SpaceX-API.git
2. Install dependencies & start server: yarn && yarn start
3. Generate types: yarn generate

**Expected behavior**
Auto generate types everytime that I change any file 

**Environment:**
 - OS: macOS Mojave 10.14.2 (18C54)
 - Codegen: 0.15.0
 - Node: 10.10.0

**Additional context**
I've tried with all possible confs (--watch, without nodemon, etc), I couldn't make it work

Don't hesitate to reach out if you'd need any info related!

**Comment by dotansimha** [comment]
Thanks @swcarlosrj ! We'll look into it

**Comment by kamilkisiela** [comment]
```yml
# codegen.yml
schema: http://localhost:4000/graphql
overwrite: true
watch: true
generates:
  ./src/graphql/types/types.d.ts:
    plugins:
      - typescript-common
      - typescript-server
      - typescript-resolvers

```

Watch mode works with file system, with files that are related to schema and documents. What you have is a url of a server. We don't have a polling mechanism that would introspect the schema in an interval.

@dotansimha
