### ISSUE TITLE
No React components or queries are generated

### ISSUE THREAD

**Issue by tomitrescak** [dotansimha/graphql-code-generator#1058]
**Describe the bug**

No React components or queries are generated.

**To Reproduce**

This is the codegen.yaml file:

```yaml
schema: 'http://localhost:4000/graphql'
generates:
  src/generated/graphql.tsx:
    plugins:
      - 'typescript-common'
      - 'typescript-client'
      - 'typescript-react-apollo'
```

The introspection is generated correctly as can be seen in the first file of this gist:

https://gist.github.com/tomitrescak/5375ceaffb637b2fb598f9e6f541ee49

Yet, the output of the generation are only **Input** files and **Enums**. See the same gist below.

Command used to produce this is:

```
gql-gen --config codegen.yml
```

All my queries are difined in *ts and *.tsx files with graphql-tag.

**Expected behavior**

I expected to see generated queries and mutations and react components.

**Schema/Documents**
If possible and relevant, please provide your GraphQL schema and GraphQL documents.

Above.

**Environment:**
 - OS: Mac
 - Codegen: Latest
 - Node: 10.9.0

**Additional context**
