### ISSUE TITLE
TypeError: Cannot read property 'onType' of undefined

### ISSUE THREAD

**Issue by alexandru-tomescu** [dotansimha/graphql-code-generator#1068]
**Describe the bug**
TypeError: Cannot read property 'onType' of undefined

**To Reproduce**
codegen.yml:

```
schema: 
  - http://localhost:4000/gql
  - src/gql/my-client-schema.graphql
documents: src/gql/**/*.{ts,tsx}
overwrite: true
generates:
  ./src/generated/gqlTypesAndComponents.tsx:
    plugins:
      - time
      - add: "// THIS IS A GENERATED FILE, DO NOT EDIT IT!"
      - typescript-common:
          interfacePrefix: "I"
      - typescript-client
      - typescript-react-apollo

```

Client schema: 
```
type AuthState {
  authenticated: Boolean
  token: String
}

type Query {
  getAuthState: AuthState
}

type Mutation {
  changeAuthState: AuthState
}

```

Mutations:
```
const SET_LOCAL_AUTH_STATE = gql`
  mutation ChangeAuthState {
    changeAuthState @client {
      ...authFragments
    }
  }
  fragment authStateFragment on AuthState {
    authenticated
    token
  }
```

Queries: 
```
const GET_LOCAL_AUTH_STATE = gql`
  query getAuthState {
    getAuthState @client {
      ...authStateFragment
    }
  }
  fragment authStateFragment on AuthState {
    authenticated
    token
  }
`;
```

defaults on Apollo:
```
{
  auth: {
    __typename: 'AuthState',
    authenticated: false,
    token: null
  }
}
```

**Expected behavior**
To generate TS and React Components

**Environment:**
 - OS: MacOs Mojave
 - Codegen: 0.15.0
 - Node: v9.11.2
