### ISSUE TITLE
[TypeScript Common] Support schemaNamespace config

### ISSUE THREAD

**Issue by tomitrescak** [dotansimha/graphql-code-generator#1070]
**Describe the bug**

schemaNamespace has no effect on output code

**To Reproduce**

```
overwrite: true
documents:
  - './src/modules/**/*.ts'
  - './src/modules/**/*.tsx'
schema: 'http://localhost:4000/graphql'
generates:
  src/generated/graphql.tsx:
    config:
      noNamespaces: true
      enumsAsTypes: true
    plugins:
      - 'typescript-common'
      - 'typescript-client'
      - 'typescript-react-apollo'
  cypress/fixtures/graphql.d.tsx:
    config:
      enumsAsTypes: true
      schemaNamespace: 'MyNamespace'
    plugins:
      - 'typescript-common'
      - 'typescript-client'
```

**Expected behavior**
the export namespace is present

**Schema/Documents**
If possible and relevant, please provide your GraphQL schema and GraphQL documents.

**Environment:**
 - OS: Mac
 - Codegen: Latest
 - Node: 10
