### ISSUE TITLE
[TypeScript Resolvers] How to use contextType?

### ISSUE THREAD

**Issue by steida** [dotansimha/graphql-code-generator#1090]
I have tried almost everything but contextType still does not work as expected. Is there any example?

Inside my types.tx Context is properly imported, but in the resolver, there is a plain object.

**Comment by kamilkisiela** [comment]
Could you provide an example / small reproduction?

https://github.com/dotansimha/graphql-code-generator/blob/7154c52e9e80664a8f1806d1e3cb1381d0254bba/packages/plugins/typescript-resolvers/tests/typescript-resolvers.spec.ts#L204-L280

**Comment by ctrlplusb** [comment]
I got my implementation working. Important to note that the import of the `.ts` file containing your context should be relative to the "generate" output `.ts` file specified in your `codegen.yml`.

```yaml
overwrite: true
schema: 'src/schema.graphql'
documents: null
generates:
  src/generated/graphql.ts:
    config:
	  # ensure this path is relative to "src/generated/graphql.ts"
      contextType: ../context#MyContext
```

And then your context file should be of similar format:

```typescript
// src/context.ts
export interface MyContext {
  username: string;
}
```

**Comment by dotansimha** [comment]
@steida, I'm closing for now, feel free to re-open if it's still relevant.

**Comment by jsphweid** [comment]
@steida  For what it is worth, it will still default to a {} all around unless you name it something other than Context it appears.

That was my problem at least. Here is my codegen.yml. Notice the "MyContext" renaming.:

```
schema: ./src/graphql/index.ts
require:
  - ts-node/register
overwrite: true
generates:
  __generatedTypes__.ts:
    plugins:
      - add: '// THIS IS A GENERATED FILE, DO NOT MODIFY'
      - add: '// tslint:disable'
      - add: "import { Context as MyContext } from './src/graphql/context';"
      - typescript-common
      - typescript-server
      - typescript-resolvers
    config:
      contextType: MyContext
````

**Comment by kettanaito** [comment]
Alternatively, you can also point to the exact exported type as a value of the `config.contextType` property, without having to use the `add` plugin:

```yml
generates:
  ./schema.ts:
    config:
      contextType: ./Context#MyContext
    plugins:
      - typescript
      - typescript-operations
      - typescript-resolvers
```

Given then there's a `Context.ts` file relative to the generated `schema.ts`:

```ts
// Context.ts
export interface MyContext {
  foo: 'bar'
}
```

Now in your resolvers you can access a type-safe context:

```js
getResources(root, args, context) {
  context.foo // "bar"
}
```
