### ISSUE TITLE
Watch mode not working as expected

### ISSUE THREAD

**Issue by swcarlosrj** [dotansimha/graphql-code-generator#1095]
**Describe the bug**
Watch mode is either not watching or not overwriting over the changes made

**To Reproduce**

Clone repository:
`git clone -b graphql-ts https://github.com/swcarlosrj/SpaceX-API.git`
Install deps & start server:
`yarn && yarn start`
Generate types:
`yarn generate`
Change any file into schema folder

**Expected behavior**
Auto generate types & overwrite the current types everytime that I change any file

**Environment:**

OS: macOS Mojave 10.14.2 (18C54)
Codegen: 0.15.2
Node: 10.10.0

**Additional context**
With the current codegen.yml config,  it doesn't watch although it generated correctly the types
```
schema: src/graphql/schema/index.ts
overwrite: true
watch: true
require:
  - ts-node/register
generates:
  ./src/graphql/types/types.d.ts:
    config:
      contextType: ./context#MyContext
    plugins:
      - typescript-common
      - typescript-server
      - typescript-resolvers
``` 

Instead with this codegen.yml config,  it doesn't generate correctly the types although it seems to be watching 
```
schema: src/graphql/schema/**/*.ts
overwrite: true
watch: true
require:
  - ts-node/register
generates:
  ./src/graphql/types/types.d.ts:
    config:
      contextType: ./context#MyContext
    plugins:
      - typescript-common
      - typescript-server
      - typescript-resolvers
```
