### ISSUE TITLE
[Flow Resolvers] typesPrefix is not applied in generated Resolver interface

### ISSUE THREAD

**Issue by BohdanTkachenko** [dotansimha/graphql-code-generator#1113]
**Describe the bug**
When specifying typesPrefix it adds prefix to args type, like `TQueryTestArgs`, but it does not add it to same type specified in generated Resolver, so instead it generates `QueryTestArgs`.

**Schema**
```graphql
type Query {
  test(a: String!): String!
}
```

**Config**
```yaml
schema: schema.graphql
overwrite: true
generates:
  ./types.flow.js:
    plugins:
      - flow
      - flow-resolvers
    config:
      typesPrefix: T
```

**Expected types generated**
```js
export type TQueryTestArgs = {
  a: string
};

export interface TQueryResolvers<Context = any, ParentType = TQuery> {
  test?: Resolver<string, ParentType, Context, TQueryTestArgs>;
                                              ^^^
}
```

**Actual types generated**
```js
export type TQueryTestArgs = {
  a: string
};

export interface TQueryResolvers<Context = any, ParentType = TQuery> {
  test?: Resolver<string, ParentType, Context, QueryTestArgs>;
                                              ^^^
}
```
