### ISSUE TITLE
Option to generate type definitions side by side with *.gql files

### ISSUE THREAD

**Issue by furier** [dotansimha/graphql-code-generator#1116]
It would be awesome if there was a option to just generate fragments and services side by side with the *.gql files.

This example
```
[Component A]
  - query.gql
[Component B]
  - query.gql
```
resulted in this output.
```
[Component A]
  - query.gql
  - query.ts
[Component B]
  - query.gql
  - query.ts
```
Then i could define an angular component's specific fragments without worrying about naming collisions, like I needed to do here because some other component's grapql query had a fragment defined with the name `location`, and the same goes for query and mutation names.
```
fragment locationSelect on Location {
  id
  name
}

query GetPositionModalData {
  locations: locationsConnection(pagesize: -1) {
    edges {
      node {
        ...locationSelect
      }
    }
  }
}
```

**Comment by furier** [comment]
What about something like this? Where you just place a generated file side by side with every match from `documents`. It would be just the same as if you manually added every single file under `generates`, but that is tedious to do with hundreds of files, unless i build a tool to generate the config. :P which when I think about it I could do...

```
schema:
  - schema.json
overwrite: true
config:
  avoidOptionals: false
generates:
  './src/app/**/*.ts':
    documents:
      - './src/app/**/*.gql'
    plugins:
      - 'typescript-common'
      - 'typescript-client'
      - 'typescript-apollo-angular'
```

To begin with it could be a requirement that you cant use stuff in the `*.gql` file that is not defined within the file, so every file would be self contained, no references to other stuff, just imports like `gql` and `gql-tag` and other stuff required by the typescript generated client to work.
