### ISSUE TITLE
Many Type is not defined.

### ISSUE THREAD

**Issue by Pruxis** [dotansimha/graphql-code-generator#1155]
**Describe the bug**
When types are generated the Maybe type is not included.

**To Reproduce**
1. Use the following config:
```
overwrite: true
schema: './src/schema.ts'
generates:
  src/types/generated.ts:
    - add: '// THIS IS A GENERATED FILE, DO NOT EDIT IT!'
    - 'typescript-server'
    - 'typescript-resolvers'
require:
  - ts-node/register
```
2. Include typedefs & resolver and create executableSchema.
3. Run codegen.

**Expected behavior**
All types are correctly genereted except for the Maybe type, that one is missing.

**Schema/Documents**
Ofcourse create an executableSchema from the following.
```
export const typeDefs: DocumentNode = gql`
  type Field {
    id: ID!
    testId: ID!
  }

  type Query {
    FieldsByTest: [Field!]
  }
`;

export const resolver = {
  Query: {
    FieldsByTest: (_) => {
      return [];
    },
  },
};
```

**Environment:**
 - OS: Mac OS 10.12.6
 - Codegen: ^0.15.2
 - Node: 10.14.1
