### ISSUE TITLE
mutate returns Observable<any>

### ISSUE THREAD

**Issue by tuurbo** [dotansimha/graphql-code-generator#1209]
**Describe the bug**
Using plugin ```graphql-codegen-typescript-apollo-angular```
```this.cartGQL.fetch()``` correctly returns ```Observable<ApolloQueryResult<Cart.Query>>```, but ```this.addItemGQL.mutate(payload)``` returns ```Observable<any>``` but should return type

```
{
  data: AddItem.Mutation,
  errors: ...
  ...
}
```

**To Reproduce**

codegen.yml
```yml
schema:
  - "http://localhost:4000/api/graphql"
documents:
  - "./src/**/*.graphql"
overwrite: true
config: {}
generates:
  ./src/generated/gql-types.ts:
    config: {}
    plugins:
      - "typescript-common"
      - "typescript-client"
      - "typescript-apollo-angular"
require: []
```
run ```gql-gen```

**Expected behavior**
```ts
return this.addItemGQL.mutate(payload)
    .pipe(
        tap((res) => {     // <-------- shouldn't be any
            console.log('res', res.data.addItem);
        }),
    );
```

**Schema/Documents**
```gql
mutation AddItem($productId: Int!, $quantity: Int!) {
    addItem(productId: $productId, quantity: $quantity) {
        item {
            ...CartItemFields
            product {
                name
                slug
                short_desc
                price
                image {
                    thumbnail
                }
            }
        }
        quantity
    }
}
```

**Environment:**
 - OS: Windows 10
 - Codegen: 0.16.0
 - Node: 10.11.0

**Additional context**
