### ISSUE TITLE
Cannot read property 'Symbol(Symbol.iterator)' of undefined

### ISSUE THREAD

**Issue by uwinkler** [dotansimha/graphql-code-generator#1240]
Running code-gen gives me this error message:

```
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/generated/apolloComponents.tsx
      ✖ Load GraphQL schemas
        → Cannot read property 'Symbol(Symbol.iterator)' of undefined
        Load GraphQL documents
        Generate
```

I guess i miss a package, but which one?

This is my package.json:

```
  "devDependencies": {
    "@types/faker": "4.1.5",
    "@types/jest": "23.3.13",
    "@types/react": "16.7.21",
    "@types/react-dom": "16.0.11",
    "faker": "4.1.0",
    "graphql-code-generator": "^0.16.0",
    "jest": "23.6.0",
    "node-fetch": "2.3.0",
    "ts-jest": "23.10.5",
    "tslint": "5.12.1",
    "typeorm": "0.2.11",
    "typescript": "3.2.2",
    "graphql-codegen-typescript-common": "0.16.0",
    "graphql-codegen-typescript-client": "0.16.0",
    "graphql-codegen-typescript-react-apollo": "0.16.0"
  },
  "dependencies": {
    "apollo-cache-inmemory": "^1.4.2",
    "apollo-client": "^2.5.0-alpha.10",
    "apollo-link-context": "^1.0.12",
    "apollo-link-error": "^1.1.5",
    "apollo-link-http": "^1.5.9",
    "graphql": "^14.1.1",
    "graphql-tag": "^2.10.1",
    "ioredis": "^4.5.1",
    "postmark": "^2.2.4",
    "react": "^16.7.0",
    "react-apollo": "^2.4.0",
    "react-dom": "^16.7.0",
    "rxjs": "^6.3.3"
  }
}
```

**Additional context**

**Comment by ardatan** [comment]
Could you share your `codegen.yml` file as well?

**Comment by uwinkler** [comment]
```
overwrite: true
schema: "http://localhost:4000/graphql"
documents: "**/*.graphql"
generates:
  src/generated/apolloComponents.tsx:
    plugins:
      - "typescript-common"
      - "typescript-client"
      - "typescript-react-apollo"
```
