### ISSUE TITLE
gql-gen with no schema in root throws error

### ISSUE THREAD

**Issue by syndesis** [dotansimha/graphql-code-generator#1284]
**Describe the bug**
Configuration file without a `schema` in the root throws an error:
```
  ✖ Parse configuration
    → Cannot read property 'length' of undefined
    Generate outputs
Cannot read property 'length' of undefined
Cannot read property 'length' of undefined
```

**To Reproduce**
1. Use a codegen.yml similar to this:

```
overwrite: true
generates:
    src/generated/api-graphql.ts:
        schema: "https://api.example.com/graphql"
        documents: "src/app/graphql/api/*.graphql"
        plugins:
            - "typescript-common"
            - "typescript-client"
            - "typescript-apollo-angular"
    src/generated/auth-graphql.ts:
        schema: "https://api.example.com/auth"
        documents: "src/app/graphql/auth/*.graphql"
        plugins:
            - "typescript-common"
            - "typescript-client"
            - "typescript-apollo-angular"
    ./graphql.schema.json:
        plugins:
            - "introspection"
```

2. Run the following command: `gql-gen --config codegen.yml`

**Expected behavior**
Generate schema files without throwing error.

**Environment:**
 - OS: OSX
 - Codegen: 0.16.0
 - Node: 10.15.0
