### ISSUE TITLE
Types not generated from schema

### ISSUE THREAD

**Issue by shauns** [dotansimha/graphql-code-generator#1289]
**Describe the bug**
When running `gql-gen --config codegen.yml`, I get an (almost) empty `types.ts`, even though there are plenty of types in my schema.

**To Reproduce**
1. Use below as schema (from the readme actually, to rule out issues with my own schema)
```graphql
type Author {
  id: Int!
  firstName: String!
  lastName: String!
  posts(findTitle: String): [Post]
}

type Post {
  id: Int!
  title: String!
  author: Author!
}

type Query {
  posts: [Post]
}

schema {
  query: Query
}
```

2. No documents as server side
3. Running `yarn codegen`, where `codegen` defined as `"gql-gen --config codegen.yml"`

**Expected behavior**
I'd expect to see types for Post and Author.

**Schema/Documents**
codegen.yml
```yaml
overwrite: true
schema: "./schema.graphql"
generates:
  ./generated/types.ts:
    plugins:
      - "typescript-common"
```

**Environment:**
 - OS: MacOS
 - Codegen: 0.16.1
 - Node: 10.11
