### ISSUE TITLE
doesn't keep typeNames namingConvention

### ISSUE THREAD

**Issue by shinyaohira** [dotansimha/graphql-code-generator#1297]
**Describe the bug**
Although I use `keep` namingConvention for typeNames, PascalCase type references were generated.

**To Reproduce**
1. Use non-PascalCase input in schema.

```
input sample_input {
    id: String!
}

type Query {
    sample(sampleInput: sample_input!): String
}
```

2. Use namingConvention as `keep` in codegen.yml.

```
overwrite: true
schema: "http://server/"
documents: null
generates:
  types.ts:
    plugins:
      - typescript-common:
          namingConvention:
            typeNames: keep
      - typescript-server:
```

3. Run the following command: `gql-gen --config codegen.yml`

```
export interface sample_input {
  id: string;
}

export interface SampleQueryArgs {
  sampleInput: SampleInput; // <- PascalCase!
}
```

**Expected behavior**

```
export interface sample_input {
  id: string;
}

export interface SampleQueryArgs {
  sampleInput: sample_input;
}
```

**Environment:**
 - OS: macOS
 - Codegen: 0.16.1
 - Node: 10.15.0

**Comment by dotansimha** [comment]
@shinyaohira Can you please try to move the `namingConvention` config to the root of the yaml?

```
overwrite: true
schema: "http://server/"
config:
  namingConvention:
    typeNames: keep
generates:
  types.ts:
    plugins:
      - typescript-common
      - typescript-server
```
