### ISSUE TITLE
Simple quotes at config: namingConvention: enumValues

### ISSUE THREAD

**Issue by gtsopour** [dotansimha/graphql-code-generator#1318]
**Is your feature request related to a problem? Please describe.**
Is that possible that we could produce the Enums with simple quotes?

`export enum Language {
  EN = 'EN',
  DE = 'DE',
  FR = 'FR',
  IT = 'IT'
}`

instead of

`export enum Language {
  EN = "EN",
  DE = "DE",
  FR = "FR",
  IT = "IT"
}`

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dotansimha** [comment]
@gtsopour thank you for opening this issue!
Actually, it's not related to `namingConvention`.
`namingConvention` changes the way the names of the enum values are being generated. 
If you wish to get an output with single quote instead of double quote, please consider to add `prettier` to your project, and add a prettier config. The codegen will make sure to run `prettier` before writing the file, and it will apply your code-style preferences to the output :)

**Comment by alexcibotari** [comment]
hello @dotansimha, can you please show an example how to integrate prettier.

**Comment by dotansimha** [comment]
@alexcibotari just make sure to install `prettier` as a dependency, that's it.

**Comment by DarkLite1** [comment]
I've stumbled upon this issue with same question on how to get single quotes instead of double quotes in the graphql code generated files. It appears that by default the `prettier` config is not applied. For this to happen you need to add a so called hook. 

`graphql-codegen.yml` example file:

```yml
overwrite: true
schema: "http://localhost:5000/"
documents: "src/**/*.graphql"
hooks:
  afterAllFileWrite:
    - prettier --write
generates:
  src/graphql/generated/operations.ts:
    plugins:
    - add: '/* eslint-disable */'
    - "typescript"
    - "typescript-operations"
    - "typescript-vue-apollo"

  src/graphql/generated/fragment-matcher.ts:
    - "fragment-matcher"

  ./graphql.schema.json:
    plugins:
    - "introspection"
```

And of course the `prettier.js` file in the root of your project where you indicate that you don't want double quotes:
```js
module.exports = {
    singleQuote: true,
    semi: false,
    tabWidth: 2,
    trailingComma: "es5",
    arrowParens: "always",
    printWidth: 80,
}
```
