### ISSUE TITLE
Do not enforce tsx if only hooks used

### ISSUE THREAD

**Issue by FredyC** [dotansimha/graphql-code-generator#1337]
**Is your feature request related to a problem? Please describe.**
Since Hooks don't use the JSX, there is no need to enforce the extension.

**Describe the solution you'd like**
If I specify configuration like this, it should be possible to use `*.ts` file.

```yml
noHOC: true,
noComponents: true,
withHooks: true,
```
