### ISSUE TITLE
Unable to get hooks generated

### ISSUE THREAD

**Issue by rishispeets** [dotansimha/graphql-code-generator#1366]
**Describe the bug**
I'm unable to get a file generated that includes hooks. I've validated the .yml syntax and tried to play with turning off and on options like noHOC and noComponent. I'm trying to only generate the hooks.

**To Reproduce**
1. Use attached codegen.yml with all deps installed
2. Run `gql-gen --config codegen.yml`

**Expected behavior**
A generated file that does not include components or HOCs.

**Schema/Documents**
*codegen.yml*
```
overwrite: true
schema: "http://localhost:4000/graphql"
documents: "**/*.graphql"
generates:
  src/generated/graphql.tsx:
    config:
      noNamespaces: true
    plugins:
      - typescript-common
      - typescript-client
      - typescript-react-apollo:
          noHOC: true
          noComponent: true
          withHooks: true

  ./graphql.schema.json:
    plugins:
      - "introspection"
```

generated *graphql.tsx*:
```
export type Maybe<T> = T | null;

export interface BookInput {
  title: string;

  authors: string[];

  categories?: Maybe<string[]>;

  tags?: Maybe<string[]>;

  subtitle?: Maybe<string>;

  page_count?: Maybe<number>;

  publisher?: Maybe<string>;

  publish_date?: Maybe<string>;

  description?: Maybe<string>;

  isbn?: Maybe<string>;

  image_links?: Maybe<ImageLinkInput>;

  google_link?: Maybe<string>;

  amazon_link?: Maybe<string>;

  goodReads_link?: Maybe<string>;
}

export interface ImageLinkInput {
  thumbnail?: Maybe<string>;

  small?: Maybe<string>;

  medium?: Maybe<string>;

  large?: Maybe<string>;
}

// ====================================================
// Documents
// ====================================================

export type UserInfoQueryVariables = {
  email: string;
};

export type UserInfoQueryQuery = {
  __typename?: 'Query';

  getUserInfo: UserInfoQueryGetUserInfo;
};

export type UserInfoQueryGetUserInfo = {
  __typename?: 'User';

  email: string;

  id: string;

  books: Maybe<UserInfoQueryBooks>;
};

export type UserInfoQueryBooks = {
  __typename?: 'UserBooksConnection';

  edges: Maybe<UserInfoQueryEdges[]>;
};

export type UserInfoQueryEdges = {
  __typename?: 'UserBooksEdge';

  cursor: string;

  node: Maybe<UserInfoQueryNode>;
};

export type UserInfoQueryNode = {
  __typename?: 'Book';

  title: string;

  authors: string[];

  categories: Maybe<string[]>;

  tags: Maybe<string[]>;

  isbn: Maybe<string>;

  image_links: Maybe<UserInfoQueryImageLinks>;
};

export type UserInfoQueryImageLinks = {
  __typename?: 'ImageLink';

  thumbnail: Maybe<string>;
};

import * as ReactApollo from 'react-apollo';
import * as React from 'react';

import gql from 'graphql-tag';

// ====================================================
// Components
// ====================================================

export const UserInfoQueryDocument = gql`
  query UserInfoQuery($email: String!) {
    getUserInfo(email: $email) {
      email
      id
      books {
        edges {
          cursor
          node {
            title
            authors
            categories
            tags
            isbn
            image_links {
              thumbnail
            }
          }
        }
      }
    }
  }
`;
export class UserInfoQueryComponent extends React.Component<
  Partial<ReactApollo.QueryProps<UserInfoQueryQuery, UserInfoQueryVariables>>
> {
  render() {
    return (
      <ReactApollo.Query<UserInfoQueryQuery, UserInfoQueryVariables>
        query={UserInfoQueryDocument}
        {...(this as any)['props'] as any}
      />
    );
  }
}
```

**Environment:**
 - OS: Ubuntu Linux
 - Codegen: 0.16.1
 - Node: 10.15.0
