### ISSUE TITLE
Allow for insecure requests

### ISSUE THREAD

**Issue by Anthonyzou** [dotansimha/graphql-code-generator#137]
Hey,

It would be great if we could have a flag to allow for endpoints with self signed certificates or allow us to add our own CA when fetching from a URL.

**Comment by dotansimha** [comment]
@Anthonyzou I think we can completely ignore certificated because this is a development tool.
What do you think?

**Comment by dotansimha** [comment]
Done in 0.8.11

**Comment by CarloPalinckx** [comment]
@dotansimha It looks like there is a regression on this, or I might be doing something wrong?
```
    ❯ Generate ./xxxxx/src/__generated__/index.tsx
      ✖ Load GraphQL schemas
        → request to https://localhost:4000/ failed, reason: self signed certificate
        Load GraphQL documents
        Generate
```
My config:

```
config: &config
  withHooks: true
  withComponent: false
  withHOC: false 
  transformUnderscore: true
  immutableTypes: true
  nonOptionalTypename: true
  apolloReactHooksImportFrom: 'react-apollo-hooks'
  apolloReactCommonImportFrom: 'react-apollo'

plugins: &plugins
  - add: |
      // tslint:disable
      // ⚠️  This file is autogenerated! ⚠️ 
      // Changing this file will end badly, be wary.
  - "typescript"
  - "typescript-operations"
  - "typescript-react-apollo" 

overwrite: true
schema: "https://localhost:4000/"
generates:
  ./xxxxx/src/__generated__/index.tsx:
    documents: "packages/backoffice-configuratorlists/src/**/*.graphql"
    config: *config
    plugins: *plugins
  ./yyyyyy/src/__generated__/index.tsx:
    documents: "packages/storefront/src/**/*.graphql"
    config: *config
    plugins: *plugins
```
