### ISSUE TITLE
 → Must provide Source. Received: {}

### ISSUE THREAD

**Issue by jerlam06** [dotansimha/graphql-code-generator#1387]
**Describe the bug**
I get this error when I run gql-gen: "Must provide Source. Received: {}"

```
> Generate src/generated/graphql.ts
      × Load GraphQL schemas
        → Must provide Source. Received: {}
```

Here is my codegen.yml:

````
schema: './src/graphql/schema.graphql'
generates:
  src/generated/graphql.ts:
    plugins:
      - 'typescript-react-apollo'
````

What does "Must provide Source" mean?

**Comment by dotansimha** [comment]
Hi @jerlam06 !
Can you please share your schema file? It looks like it's not being loaded correctly.

**Comment by jerlam06** [comment]
Hi @dotansimha, thanks for the answer.
Well it is really huge, about 10k lines. It was extracted from hasura. So I guess some syntax in the file isn't rigth?

**Comment by dotansimha** [comment]
Yeah, I think so. Can you please try to copy/paste it into https://astexplorer.net and see if you are getting an error?

**Comment by dotansimha** [comment]
And also, any chance you can create a repo with a minimal reproduction? This way I'll be able to test it locally. Thanks!

**Comment by dotansimha** [comment]
@jerlam06 can you also try this config?
```yml
schema: src/graphql/schema.graphql
generates:
  src/generated/graphql.ts:
    plugins:
      - typescript-react-apollo
```
