### ISSUE TITLE
[graphql-code-generator] 0.18.0 does not generate client specific types

### ISSUE THREAD

**Issue by FuNn1esT** [dotansimha/graphql-code-generator#1425]
**Describe the bug**

graphql-code-generator 0.18.0 will not generate client-specific types from `ts` file

**To Reproduce**

1. Use `schema.gql` as schema

```gql
# schema.gql
schema {
  query: Query
}

type Query {
  me: User
  user(id: ID!): User
  allUsers: [User]
}

enum Role {
  USER
  ADMIN
}

type User {
  id: ID!
  username: String!
  email: String!
  role: Role!
}
```

2. Use `test.gql` and `test.ts` as documents

```gql
# test.gql
query findUser($userId: ID!) {
  user(id: $userId) {
    ...UserFields
  }
}

fragment UserFields on User {
  id
  username
  role
}
```

```ts
// test.ts
import { gql } from 'apollo-boost';

export const testQuest = gql`
  query findUser($userId: ID!) {
    user(id: $userId) {
      ...UserFields
    }
  }

  fragment UserFields on User {
    id
    username
    role
  }
`;
```

3. Use `codegen.yml` as config

```yml
# codegen.yml
overwrite: true
schema: 'schema.gql'
generates:
  types-from-gql.ts:
    documents: 'test.gql'
    config:
      noNamespaces: true
    plugins:
      - typescript-common
      - typescript-client
  types-from-ts.ts:
    documents: 'test.ts'
    config:
      noNamespaces: true
    plugins:
      - typescript-common
      - typescript-client
```

4. Run the following command: `gql-gen --config codegen.yml`

**Expected behavior**

generated file `types-from-ts.ts` should be the same as `types-from-gql.ts`

when the graphql-code-generator version is 0.17.0 it works well, but when the version is 0.18.0 the `types-from-ts.ts` does not generate client-specific types

`package.json` file

```diff
{
  "scripts": {
    "codegen": "gql-gen --config codegen.yml"
  },
  "devDependencies": {
-   "graphql-code-generator": "^0.17.0",
+   "graphql-code-generator": "^0.18.0",
    "graphql-codegen-typescript-client": "^0.18.0",
    "graphql-codegen-typescript-common": "^0.18.0",
    "typescript": "^3.3.3333"
  },
  "dependencies": {
    "apollo-boost": "^0.3.1",
    "graphql": "^14.1.1"
  }
}
```
`types-from-ts.ts` file

```diff
// types-from-ts.ts
export type Maybe<T> = T | null;

export enum Role {
  User = "USER",
  Admin = "ADMIN"
}

-// ====================================================
-// Documents
-// ====================================================
-
-export type FindUserVariables = {
-  userId: string;
-};
-
-export type FindUserQuery = {
-  __typename?: "Query";
-
-  user: Maybe<FindUserUser>;
-};
-
-export type FindUserUser = UserFieldsFragment;
-
-export type UserFieldsFragment = {
-  __typename?: "User";
-
-  id: string;
-
-  username: string;
-
-  role: Role;
-};
```
