### ISSUE TITLE
typescript-graphql-files-modules generates conflicts when using same .graphql file names

### ISSUE THREAD

**Issue by elado** [dotansimha/graphql-code-generator#1436]
**Describe the bug**

`typescript-graphql-files-modules` only considers the file name, not the full path, and generates `declare module '*/{filename}'`. If there are multiple files with the same name, e.g. `query.graphql`, multiple `declare module '*/query.graphql'` are generated, which creates conflicts on the return types.

**To Reproduce**

The following file structure:

```
- src
  - A
    - index.tsx
    - query.graphql
  - B
    - index.tsx
    - query.graphql
```

Generates

```ts
declare module '*/query.graphql' {
    import { DocumentNode } from 'graphql';
    const defaultDocument: DocumentNode;
    const AQuery: DocumentNode;

    export { AQuery };

    export default defaultDocument;
}

declare module '*/query.graphql' {
    import { DocumentNode } from 'graphql';
    const defaultDocument: DocumentNode;
    const BQuery: DocumentNode;

    export { BQuery };

    export default defaultDocument;
}
```

yaml config:

```yml
overwrite: true
schema: schema.graphql
documents: 'src/**/*.graphql'
generates:
    src/types/gql-gen/tsd.d.ts:
        plugins:
            - 'typescript-graphql-files-modules'
```

**Expected behavior**

To generate full file paths:

```ts
declare module 'src/A/query.graphql' {
    import { DocumentNode } from 'graphql';
    const defaultDocument: DocumentNode;
    const AQuery: DocumentNode;

    export { AQuery };

    export default defaultDocument;
}

declare module 'src/B/query.graphql' {
    import { DocumentNode } from 'graphql';
    const defaultDocument: DocumentNode;
    const BQuery: DocumentNode;

    export { BQuery };

    export default defaultDocument;
}
```

and prevent conflicts.
