### ISSUE TITLE
typescript-react-apollo - component definitions are not generated when documents are defined within ts file

### ISSUE THREAD

**Issue by Hotell** [dotansimha/graphql-code-generator#1449]
**Describe the bug**
When documents reside within 'ts' files, which are defined via standard ```
const = GET_FOO = gql`query Foo{}`
```, no React components are generated. If I extract those queries to separate files `.gql` it works.

**To Reproduce**
1. Use './schema.json' as schema
2. Use './src/**/*.{ts,tsx}' as documents
3. Run the following command: `gql-gen generate`

```
schema: './schema.json'
documents: './src/**/*.{ts,tsx}'
overwrite: true
generates:
  ./src/components.tsx:
    config:
      noNamespaces: true
    plugins:
      - typescript-common
      - typescript-client
      - typescript-react-apollo
```

**Expected behavior**
generate React components when `ts` files are used as documents

**Schema/Documents**

```ts
// src/queries.ts
import { gql } from 'apollo-boost'

export const SIGNUP = gql`
  mutation Signup($email: String!, $password: String!) {
    signup(input: { email: $email, password: $password }) {
      email
      password
      errors {
        field
        messages
      }
    }
  }
`
export const UPGRADE_REQUEST = gql`
  mutation UpgradeRequest($name: String) {
    upgradeRequest(input: { name: $name }) {
      name
    }
  }
`

export const GET_ACCOUNT = gql`
  query GetAccount {
    account {
      name
      email
      phoneNumber
      type
      upgradeRequest {
        name
        phoneNumber
        personalId
        citizenship
        address {
          id
          zipcode
          street
          location
          text
          city
        }
      }
    }
  }
`
```

**Environment:**
 - OS: macOs
 - Codegen: 0.18.0
 - Node: 8

**Additional context**

**Comment by dotansimha** [comment]
Hi @Hotell ! 
We noticed this issue before, and it seems like it's the same issue as: https://github.com/dotansimha/graphql-code-generator/issues/1425 

Please refer to the suggested solution there. 

In your case, adding the following to your config file should do the trick:
Thanks @shlomiatar , I think you are right. A few weeks ago, @kamilkisiela added the ability to pass configuration to `graphql-tag-pluck` (https://github.com/dotansimha/graphql-code-generator/blob/master/packages/utils/plugins-helpers/src/yml-config-types.ts#L52-L60).

You can now specify a custom `modules` definition and tell `graphql-tag-pluck` where are you importing from:

```yml
pluckConfig:
  modules: 
    - name: "apollo-boost"
      identifier: "gql"
schema: schema.graphql
generates: // ...
```
