### ISSUE TITLE
Question: How to save remote schema into graphql file ?

### ISSUE THREAD

**Issue by revskill10** [dotansimha/graphql-code-generator#1480]
**Describe the bug**
This is not a bug, but i'm confused with the deprecation of `introspection-template`.
With `introspection-template`, i could see `gql-gen` save the remote schema into a `graphql` file.
But now, i couldn't find any options to save the remote schema into local graphql file.

**To Reproduce**

My `codegen.yml` is
```yml
schema:
  - https://myremote-graphql-server.com/graphql:
overwrite: true
generates:
  ./typings/edu.d.ts:
    schema: ./schemas/server.graphql
    plugins:
      - typescript-common
      - typescript-client
```
