### ISSUE TITLE
[TypeScript-Resolvers] Same imported type for different GraphQL types

### ISSUE THREAD

**Issue by ardatan** [dotansimha/graphql-code-generator#1498]
Before 1.0.0, it was working as expected.

codegen.yml
```yml
mappers:
   Admin: ./entities/UserEntity#UserEntity
   User: ./entities/UserEntity#
```

Result
```ts
import { UserEntity, UserEntity } from './entities/UserEntity'; 
```

And this causes `Duplicate identifier 'UserEntity'.` error.
