### ISSUE TITLE
fragment-matcher error in 1.0.0

### ISSUE THREAD

**Issue by leebenson** [dotansimha/graphql-code-generator#1502]
In v1.0.0, fragment-matcher errors where in 0.18.0 it was working:

**codegen.yml** (snippet)

```yml
ui/src/graphql/fragments.tsx:
  documents: ui/src/**/*.graphql
  plugins:
    - fragment-matcher
```

**package.json**

```json
"@graphql-codegen/cli": "^1.0.0",
"@graphql-codegen/fragment-matcher": "^1.0.0",
"@graphql-codegen/typescript": "^1.0.0",
"@graphql-codegen/typescript-operations": "^1.0.0",
"@graphql-codegen/typescript-react-apollo": "^1.0.0",
```

**Error:**

>   ✖ ui/src/graphql/fragments.tsx
    Unable to load template plugin matching 'fragment-matcher'.
    Reason: 
      Unexpected token {
