### ISSUE TITLE
how to define custom scalars?

### ISSUE THREAD

**Issue by mdestagnol** [dotansimha/graphql-code-generator#1532]
When using the typescript plugin, I can't find any documentation specifying how to define custom scalars? They seem to simply be generated as type "any".

Is there a way to define custom scalars types? I'm opening a new issue since it seems that the previous answers are outdated and not working anymore.

Thx for your help!

**Comment by mdestagnol** [comment]
Forget about my question, this is now part of the plugin typescript-operations and described here: https://graphql-code-generator.com/docs/plugins/typescript-operations.

**Comment by dotansimha** [comment]
@mdestagnol yeah it's part of all plugins actually. Note that if you are using it, you should pass the `scalars: {}` config for all plugins in the same file.

**Comment by mdestagnol** [comment]
Thx for the additional info @dotansimha.

Related question: how would you do to define custom types? For example if you want to do something like:

```config:
  scalars:
    UInt: NonNegativeInt```

Any idea? thx a lot!

**Comment by dotansimha** [comment]
@mdestagnol If your scalars is defined this way in your schema:
```
scalar UInt
```

Then you can add this to your configuration:
```
config:
  scalars:
    UInt: number
```

And you can also use a custom identifier (and if you need, you can add `import {} ...` using `add` plugin .

**Comment by arvinsim** [comment]
I have already defined something like this

```
 config:
      scalars:
        Long: number
        BigDecimal: number
```

But I still get errors

```
 Type "Long" not found in document.
        Error: Type "Long" not found in document.
```

**Comment by dotansimha** [comment]
@arvinsim do you have `Long` scalar defined in your GraphQL schema? You must have it existing in your schema, and then you can map it to a TypeScript type.

**Comment by finaxar-arthur** [comment]
@dotansimha You are right. Adding the scalar definitions below in my `schema.graphql` solved the issue

```
scalar Long
scalar BigDecimal
```

**Comment by tamsanh** [comment]
For anyone trying to add custom scalars that use a custom enum or interface, you can use the aforementioned configuration to use one's own custom type in combination with the [`add`](https://www.graphql-code-generator.com/docs/plugins/add) plugin to inject the import for the custom type at the top of the page.

```
yarn add -D @graphql-codegen/add
```

Ex:
```
schema:
  - ./temp/all.graphql
generates:
  ./src/backend/app.ts:
    plugins:
      - typescript
      - add:
            content: "import BankCode from './BankCode'"
    config:
      scalars:
        BankCode: BankCode
```

This will result in a graphql file that imports my bank code enum, and replaces its `any` type in the scalar map.
