### ISSUE TITLE
Cant use ts file to be the document source in 1.x

### ISSUE THREAD

**Issue by jackypan1989** [dotansimha/graphql-code-generator#1555]
**Describe the bug**
At version 1.x, we cant use ts file to be the document source.

**To Reproduce**

1. not working with .ts file
```javascript
export default gql`
  query ClinicsQuery($query: MyQuery) {
    clinics(query: $query) {
      docs {
        id
        name
      }
    }
  }
`
```

2. working with .gql file
```graphql
query ClinicsQuery($query: MyQuery) {
  clinics(query: $query) {
    docs {
      id
      name
    }
  }
}
`
```

```yml
schema: ./packages/src/server/graphql/**/*.graphql
documents: ./packages/src/client/graphql/**/*.ts
overwrite: true
generates:
  ./packages/src/graphql/types.ts:
    plugins:
      - typescript
      - typescript-operations
  
```

**Expected behavior**
Both ts and gql file can parse to types.

**Environment:**

- OS: MacOS
- `@graphql-codegen/...`: 1.0.3
- NodeJS: 10.x

**Comment by wrod7** [comment]
thanks for starting this issue. im having the same problem.

i switched to .gql files for now

**Comment by dotansimha** [comment]
@jackypan1989 @wrod7 Where do you import `gql` from?

**Comment by jackypan1989** [comment]
We use apollo-boost's gql

ref: https://github.com/apollographql/apollo-client/tree/master/packages/apollo-boost

**Comment by dotansimha** [comment]
@jackypan1989 @wrod7 can you please try to add the following to your `codegen.yml` file?

```yml
pluckConfig:
  modules: 
    - name: "apollo-boost"
      identifier: "gql"
```

**Comment by wrod7** [comment]
@dotansimha that works for me 

```
schema:
  - http://localhost:4000/
overwrite: true
documents:
  - "./src/**/graphql.ts"
pluckConfig:
  modules:
    - name: "apollo-boost"
      identifier: "gql"
generates:
  src/generated/apolloComponents.tsx:
    plugins:
      - add: "/* tslint:disable */"
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withComponent: true
      withHooks: true
      withHOC: false
```

![image](https://user-images.githubusercontent.com/7082435/54927530-b6565080-4ee8-11e9-9225-33edf66362ee.png)
the generated file has errors tho. not sure why its adding " & Pick<" to my login mutation and MeQuery
