### ISSUE TITLE
[Typescript] Generated QueryVariables filed with default Value not optional

### ISSUE THREAD

**Issue by roman-may** [dotansimha/graphql-code-generator#1590]
**Describe the bug**
If you provide a default value for a query variable, the generated field in the query variable type is mendatory instead of optional. 

It worked before with version "0.12.6".

**To Reproduce**
Steps to reproduce the behavior: Provide a default value in a query.

1. My GraphQL schema:
I can provide it if its necessary.

2. My GraphQL operations:
```graphql
# ../search.graphql

query SEARCH($query: String!, $limit: Int = 9, $offset: Int = 0) {
  search(query: $query) {
    pages(limit: $limit, offset: $offset) {
      total
    }
  }
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: 'http://localhost:4000/api/graphql'
documents: ['**/*.graphql']
generates:
  lib/@graphql/types/generated.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
    config:
      skipTypename: true
      namingConvention:
        typeNames: change-case#pascalCase
        enumValues: keep
```

**Expected behavior**

Variable is optional in type.

**Environment:**

- OS: Windows 10
- `@graphql-codegen/cli`: 1.0.3
- `@graphql-codegen/typescript`: 1.0.3
- `@graphql-codegen/typescript-operations`: 1.0.3
- NodeJS: 10.15.0

**Additional context**

**Comment by dotansimha** [comment]
@roman-may It think @kamilkisiela fixed it recently, can you please try `1.0.6`?

**Comment by roman-may** [comment]
@dotansimha You're right. I did not realize there was an update. Thank you for the fast reply!

**Comment by ken0x0a** [comment]
I still have this issue 1.0.7...

I've just tried to upgrade from v0.18 => 1.0.7, and I cannot resolve errors by tsc.
Is this error comes back in 1.0.7 ?

```yml
  ./src/__generated__/graphql-codegen.tsx:
    documents:
      - graphql/query/**/*.gql
    plugins:
      - add: *header
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - ./codegen-plugins/hoc-name.ts
      # - typescript-compatibility # => more error by tsc
    config:
      avoidOptionals: true
      strict: true
      scalars:
        BigInt: string
        BigFloat: string
        Cursor: string
        Datetime: string
        JSON: any
        # JSON: { [key: string]: any } # => [object Object] ERROR!!
        UUID: string
      # __options for react-apollo__
      withHOC: true
      withComponent: false
      # noGraphQLTag: true # => error
```

```json
  "devDependencies": {
    "@graphql-codegen/add": "1.0.7",
    "@graphql-codegen/cli": "1.0.7",
    "@graphql-codegen/fragment-matcher": "1.0.7",
    "@graphql-codegen/schema-ast": "1.0.7",
    "@graphql-codegen/time": "1.0.7",
    "@graphql-codegen/typescript": "1.0.7",
    "@graphql-codegen/typescript-operations": "1.0.7",
    "@graphql-codegen/typescript-react-apollo": "1.0.7",
    "@graphql-codegen/typescript-resolvers": "1.0.7",
    "graphql": "14.1.1",
    "jest": "24.5.0",
    "lodash": "4.17.11",
    "prettier": "1.16.4",
    "ts-node": "8.0.3",
    "tsconfig-paths": "3.8.0",
    "typescript": "^3.3.3"
  }
```
