### ISSUE TITLE
The TIME plugin is throwing an exception: moment_1.default is not a function

### ISSUE THREAD

**Issue by ebeltran1981** [dotansimha/graphql-code-generator#1600]
**Describe the bug**
I did add the latest (1.0.6) **time** plugin to my gqlgen.yml file. When run the cli it throws an error: **TypeError: moment_1.default is not a function**

**To Reproduce**

- run graphql-codegen --config gqlgen.yml

1. My `codegen.yml` config file:

```yml
overwrite: true
schema: "https://localhost:8080/graphql"
generates:
  ./src/gql-gen/myfile.ts:
    plugins:
      - add:
          - "/* tslint:disable */"
          - "// THIS IS A GENERATED FILE, DO NOT EDIT IT!"
      - time
      - typescript
      - typescript-operations
      - typescript-apollo-angular
      - fragment-matcher
    config:
      avoidOptionals: false

```

**Expected behavior**
Not to fail and see the time in the generated file.

**Environment:**

- OS: macOS
- `@graphql-codegen/time`: 
- NodeJS: 10

**Additional context**
I did fork the code and switch the momentjs import to:` import * as moment from 'moment'` and it worked.

any suggestion?
