### ISSUE TITLE
Cannot import schema from TypeScript file

### ISSUE THREAD

**Issue by stevenmusumeche** [dotansimha/graphql-code-generator#1606]
Thank you so much for your work on this project.  It is truly wonderful.

I am following the documentation at https://graphql-code-generator.com/docs/getting-started/schema-field#javascript-export

I am currently using my project's URL as the schema, and it works perfectly, which tells me that the schema is valid.  I am now trying to use a TS file instead of a URL.  I specified the require field as documented:

```yml
require:
  - ts-node/register
schema: ./server/graphql/index.ts
overwrite: true
generates:
  # using .ts instead of .d.ts so we can import enums from it
  ./server/types/graphql.ts:
    config:
      noNamespaces: true
      # ...etc
    plugins:
      - add: "/**\n * THIS IS A GENERATED FILE, DO NOT MODIFY DIRECTLY\n */\n"
      - typescript-common
      - typescript-server
      - typescript-resolvers
```

However, I get the following error: `SyntaxError: Unexpected identifier` when running `gql-gen`.  It is choking on ES6 imports and exports, which are valid TypeScript.

```ts
import gql from 'graphql-tag'
// ...etc

export const schema = `...etc`
```

What am I missing to allow using a TypeScript file for my schema?

**Comment by stevenmusumeche** [comment]
For others that might stumble upon this issue, here is how I solved it.

First, I created a "loader" file that will be used for the `schema` field in `gql-gen.yml`.  That file will import the schema from your TypeScript files and then export it. 

```
/**
 * This file is used to export the GraphQL schema in a format that gql-gen
 * can understand.  All it is doing is importing the schema from the "real"
 * place (server/graphql/index.ts) and re-exporting it.
 */

const getBabelConfig = require('../../bin/utils/getBabelConfig')
const serverExtensions = require('../../bin/utils/serverExtensions')

/**
 * Allow on-the-fly babel transformation of server code when generating types.
 */
require('@babel/register')(
  Object.assign(getBabelConfig(), {
    extensions: serverExtensions
  })
)

const { schema } = require('../graphql/index.ts')
const { makeExecutableSchema } = require('apollo-server-koa')

module.exports = {
  schema: makeExecutableSchema({ typeDefs: schema })
}
```

**Comment by dotansimha** [comment]
@stevenmusumeche I think adding `ts-node/register` should do the trick.
We are using `graphql-toolkit` for automatically load the schema from any input, so it might be an issue with it.

**Comment by DonaldWebb** [comment]
I have been using default export on .ts with ts-node/register for a couple of months, it works well.
Remember to add ts-node as a dev dependency.
``` console
npm install --save-dev ts-node
```

``` yml 
overwrite: true
watch: true
schema:
  - "./src/schema/schema.ts"
documents: null
generates:
  src/generated/generated-models.tsx:
    config:
      contextType: "@src/index#IContext"
      optionalType: "undefined"
      scalars:
        Date: Date
        DateTime: Date
        Time: Date
        Upload: File
    plugins:
      - add: "// tslint:disable max-line-length"
      - "typescript-common"
      - "typescript-server"
      - "typescript-resolvers"
  ./graphql.schema.json:
    plugins:
      - "introspection"
require:
  - "ts-node/register/transpile-only"
```
