### ISSUE TITLE
Fragment on union type gives error schemaType.getInterfaces is not a function

### ISSUE THREAD

**Issue by jonaskello** [dotansimha/graphql-code-generator#1624]
**Describe the bug**
Fragment on union type gives error schemaType.getInterfaces is not a function

**To Reproduce**

There is a [reproduction repo here](https://github.com/jonaskello/graphql-codegen-issue1)

1. My GraphQL schema:

```graphql
type Query {
  fooBar: [FooBar!]!
}

union FooBar = Foo | Bar

type Foo {
  id: ID!
}

type Bar {
  id: ID!
}
```

2. My GraphQL operations:

```graphql
query {
  fooBar {
    ...FooBarFragment
  }
}

fragment FooBarFragment on FooBar {
  ... on Foo {
    id
  }
  ... on Bar {
    id
  }
}
```

3. My `codegen.yml` config file:

```yml
schema:
  - "schema.graphql"
overwrite: true
generates:
  generated.ts:
    documents: "query.graphql"
    plugins:
      - "typescript"
      - "typescript-operations"
```

**Expected behavior**
To genereate without error.

**Environment:**

- OS: MacOS 10.13.6
- `@graphql-codegen/...`: 1.0.6
- NodeJS:
