### ISSUE TITLE
Extended union type not extended in joined schema

### ISSUE THREAD

**Issue by jonaskello** [dotansimha/graphql-code-generator#1625]
**Describe the bug**

Extended union type not extended in joined schema.

**To Reproduce**

There is a [reproduction repo here](https://github.com/jonaskello/graphql-codegen-issue2).

1. My GraphQL schema:

**schema1.ts**
```ts
import gql from "graphql-tag";

export const schema1 = gql`
  type Query {
    fooBar: [FooBar!]!
  }

  union FooBar = Foo | Bar

  type Foo {
    id: ID!
  }

  type Bar {
    id: ID!
  }
`;
```

**schema2.ts**
```ts
import gql from "graphql-tag";

export const schema2 = gql`
  extend union FooBar = Zoo

  type Zoo {
    id: ID!
  }
`;
```

**schema-join.ts**
```ts
import { buildSchemaFromTypeDefinitions } from "graphql-tools";

import { schema1 } from "./schema1";
import { schema2 } from "./schema2";

export default buildSchemaFromTypeDefinitions([schema1, schema2]);
```

2. My GraphQL operations:

```graphql
query {
  fooBar {
    ... on Foo {
      id
    }
    ... on Bar {
      id
    }
  }
}
```

3. My `codegen.yml` config file:

```yml
schema:
  - "schema-join.ts"
require: "ts-node/register"
overwrite: true
generates:
  generated.ts:
    documents: "query.graphql"
    plugins:
      - "typescript"
      - "typescript-operations"
```

**Expected behavior**
The extended union should be generated as:

```ts
export type FooBar = Foo | Bar | Zoo;
```

**Environment:**

- OS: MacOS 10
- `@graphql-codegen/...`: 1.0.6
- NodeJS: v10.15.3

**Additional context**
