### ISSUE TITLE
Generate components for react-apollo in separated files

### ISSUE THREAD

**Issue by andfs** [dotansimha/graphql-code-generator#1646]
**Is your feature request related to a problem? Please describe.**

To avoid merges, I'd want to generate the react-apollo components in different files. For example. One component per file.

**Describe the solution you'd like**
It'll be great to have a config option to generate components in different files.

**Describe alternatives you've considered**
The output file name could accept a regex string, so the files could have a rule for their names.

**Additional context**
Could be something like that:

```
generates:
  differentFiles: true
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    overwrite:
      - true
```
