### ISSUE TITLE
[ typescript-operations] NamingConvention Breaking Change

### ISSUE THREAD

**Issue by roman-may** [dotansimha/graphql-code-generator#1651]
I'm not sure if this is a Bug or if it was planned, but the namingConvention changes from 1.0.4 to 1.0.5 were breaking for the typescript-operations plugin.

We use the following .yml:
```
overwrite: true
schema: 'http://localhost:4000/graphql'
documents:  ['pages/**/*.graphql']
generates:
  lib/@graphql/types/generated.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
    config:
      skipTypename: true
      namingConvention:
        typeNames: change-case#pascalCase
        enumValues: keep
```

At version 1.0.4 the Query:
```
query GET_USER($userId: Int!) { .... }
```
would result in Types like GetUserQuery and GetUserQueryVariables. 
After Version 1.0.5 the generated types are Get_UserQuery and Get_UserQueryVariables.
Even if i use a custom name converter, I can only change the single parts, not the underscore. 

I think this is because of the changes of convertNameParts function in the visitor-plugin-common/src/utils.ts.
