### ISSUE TITLE
Agnualr error with codegen and @client directive

### ISSUE THREAD

**Issue by dauledk** [dotansimha/graphql-code-generator#1654]
**Describe the bug**
I can't generate code for a query, that looks for a client field.

**To Reproduce**

1. My GraphQL schema (client):

```graphql
extend type Query {
    visibilityFilter: String
  }
```

2. My GraphQL operations:

```graphql
query visibilityFilterQuery {
    visibilityFilter @client
}
```

3. My `codegen.yml` config file:

```yml
schema: http://localhost:1337/graphql
documents: ./src/**/*.graphql
generates:
  ./src/app/eddy/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-apollo-angular
config:
  ngModule: ../eddy.module#EddyModule
```

**Expected behavior**
When I run: `graphql-codegen`, I expect a service generated for `visibilityFilterQuery`. But I get the following error: 

```
./src/app/eddy/generated/graphql.ts
    AggregateError: 
        GraphQLDocumentError: Cannot query field "visibilityFilter" on ty
pe "Query".
```

**Environment:**

- OS: 
- `@graphql-codegen/typescript-apollo-angular 1.0.6`: 
- NodeJS: v10.12.0

**Additional context**
The codegen works for all "normal" server side queries, AND "inline" client queries.

**Comment by dotansimha** [comment]
@dauledk 
It looks like you didn't include your client-side schema as part of the codegen schema.
You should have a client-side schema file, for example `client-schema.graphql` with the following content:

```
directive @client on FIELD

extend type Query {
    visibilityFilter: String
}
```

Then, provide it to your codegen configuration:

```
schema: http://localhost:1337/graphql
documents: ./src/**/*.graphql
generates:
  ./src/app/eddy/generated/graphql.ts:
   schema: client-schema.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-apollo-angular
config:
  ngModule: ../eddy.module#EddyModule
```

This way, the codegen will merge both schemas, and the documents will get validated against the merged schema.
