### ISSUE TITLE
Generate react-apollo components from operations in .tsx files

### ISSUE THREAD

**Issue by JAFong** [dotansimha/graphql-code-generator#1661]
I'd like to colocate my GraphQL operations with my React components.  So instead of defining a query in a corresponding `.graphql` file, I would like to use `graphql-tag` to define the same query within a `.tsx` file instead.

I receive the following error
```
  ✖ src/generated/graphql.tsx
    SyntaxError: Unexpected token (1:1)
```

Using this config:
```
overwrite: true
schema: 'http://localhost:3000/graphql'
documents: '**/*.tsx'
generates:
  src/generated/graphql.tsx:
    plugins:
       - add: "/**\n * THIS IS A GENERATED FILE, DO NOT MODIFY DIRECTLY\n */\n"
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'

```
