### ISSUE TITLE
Error: was filtered because it contains an invalid GraphQL document definition

### ISSUE THREAD

**Issue by appsolutegeek** [dotansimha/graphql-code-generator#1667]
Hi,

Can you tell me what is wrong here ? I run the codegen. And I get lots of errors, but my graphql files are fine as far as i know.

File "libs/feature/keyset/src/graphql/schema/mutation.graphql" was filtered because it contains an invalid GraphQL document definition!
File "libs/feature/keyset/src/graphql/schema/query.graphql" was filtered because it contains an invalid GraphQL document definition!

here is my codegen.xml

```
overwrite: true
schema: "http://localhost:3015/graphql"
documents:
  - "libs/**/*.graphql"
generates:
  libs/shared/models/src/lib/graphql/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"

  tmp/graphql/client-models/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-apollo-angular"

  ./graphql.schema.json:
    plugins:
      - "introspection"

```

I don't quite understand the error. 

Can I provide more details ?

**Comment by dotansimha** [comment]
@appsolutegeek can you please share the content of `libs/feature/keyset/src/graphql/schema/mutation.graphql`? 

You are specifying those files in `documents: "libs/**/*.graphql"` and those files seems to contain GraphQL schema content, any reason for that?

**Comment by appsolutegeek** [comment]
I am running it like so 

```
    "generate:graphql-types": "graphql-codegen --config config.yml"
```

**Comment by appsolutegeek** [comment]
```
type Mutation {
    setKeySetCompromised(keySetId: ID!): KeySet
    setKeySetUncompromised(keySetId: ID!): KeySet
    reserveKeySet(keyGroupId: ID!): KeySet
    seedKeySet(keySetId: ID!, keySetSeedInput: KeySetSeedInput!): KeySet
}
```

I basically have a querry, mutation and types in each feature directory

**Comment by appsolutegeek** [comment]
this is for that feature

![image](https://user-images.githubusercontent.com/2370364/55717290-49b77780-59f9-11e9-992b-799531fe61a2.png)

**Comment by dotansimha** [comment]
@appsolutegeek 
The content there is a schema content, and you are loading it using `documents:` section.
How is your project constructed? do you have client and server in the same project?
And if you have the schema locally, you can load it locally without the need to load it from the remote endpoint.

**Comment by appsolutegeek** [comment]
HI, yes I have a angular app and also a server. I am using 2 x generations. 

```
generates:
  libs/shared/models/src/lib/graphql/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"

  tmp/graphql/client-models/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-apollo-angular"
```

The angluar is placed into tmp, and this is copied across to the angular app when needed.

Each feature has a query and mutation and also the relevant types..

everything has a .graphql extension.

**Comment by dotansimha** [comment]
Great, and why do you use `"http://localhost:3015/graphql"` for the schema? if you have it locally, you can load it from there (then, you don't have to start the server each time in order to generate). 

The fact that you used a very broad `glob` pattern causes it to load also the files that it shouldn't, that's why you are getting those warnings.

I think, in your project, the codegen config file should look like that:

```
overwrite: true
schema: "libs/**/*.graphql"
generates:
  libs/shared/models/src/lib/graphql/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"

  tmp/graphql/client-models/graphql.ts:
    documents: "tmp/**/*.graphql"
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-apollo-angular"

  ./graphql.schema.json:
    plugins:
      - "introspection"
```

This way, all `.graphql` files from `lib` is getting loaded as schema, and all `.graphql` files from `/tmp` are loaded as operations documents.
