### ISSUE TITLE
Unable to find fragment matching then name

### ISSUE THREAD

**Issue by LawJolla** [dotansimha/graphql-code-generator#1692]
**Describe the bug**
When a fragment is imported into a query, the following is returned:

```
 graphql-codegen --config codegen.yml
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/generated/graphql.tsx
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Unable to find fragment matching then name "DealFragment"! Please make sure it's loaded.


 Found 1 error

  ✖ src/generated/graphql.tsx
    Error: Unable to find fragment matching then name "DealFragment"! Please make sure it's loaded.
```

**To Reproduce**

1. My GraphQL schema:

```graphql
type Query {
   deals: [Deal!]
}

type Deal {
   id: ID!
}
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "../admin-server-nexus/src/generated/schema.graphql"
documents:
  - "src/containers/**/*.tsx"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
```

**Expected behavior**
Compile generated types

**Environment:**

- OS: MacOS 10.14.4
- `@graphql-codegen/...`: 1.0.7 
- NodeJS: 11.11

**Additional context**
The following works when placed in the same file...

```
// query.tsx
...
const DealFragment = gql`
  fragment DealFragment on Deal {
   id
  }
`

const DEALS = gql`
  query deals {
    deals {
      ...DealFragment
    }
  }
  ${DealFragment}
`
```

But when `DealFragment` is imported, it returns the above error.  e.g.

```
// dealFragment.tsx
...
export const DealFragment = gql`
  fragment DealFragment on Deal {
   id
  }
`

// query.tsx
import { DealFragment } from "./dealFragment"
...

const DEALS = gql`
  query deals {
    deals {
      ...DealFragment
    }
  }
  ${DealFragment}
`
```

Thank you for the brilliant work with this project!  It's helped me a ton.
