### ISSUE TITLE
There should be an explicit option to exclude documents or schemas

### ISSUE THREAD

**Issue by slikts** [dotansimha/graphql-code-generator#1698]
Related to #1229

Currently the way to exclude files is by using glob patterns (for example, like so: `src/**/!(*.spec).{tsx,graphql}`), but it's complex and doesn't scale well with the number of exceptions that may be necessary in more legacy code bases. It would be useful if there was a separate config option to exclude files; something like:
```yaml
documents:
  - "src/**/*.{tsx,graphql}"
  exclude: "*.spec.*"
```
