### ISSUE TITLE
Cannot read property 'name' of null

### ISSUE THREAD

**Issue by iEricKoh** [dotansimha/graphql-code-generator#1731]
**Describe the bug**
I have a file that was doing mutation which cause the error:
```
> graphql-codegen --config codegen.yml

  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./src/__generated__/index.tsx
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Cannot read property 'name' of null


 Found 1 error

  ✖ ./src/__generated__/index.tsx
    TypeError: Cannot read property 'name' of null
```

**To Reproduce**

1. My GraphQL schema:

This's the only file under `- src/apollo/mutations/**/*.{ts,tsx}`.
Everything works fine if I remove this file.

```
import gql from 'graphql-tag'

export const UPDATE_SELECT_SKU = gql`
  mutation updateSelectedSKU($id: Float!, $sku: String!) {
    updateSelectedSKU(id: $id, sku: $sku) @client
  }
`

```

2. My `codegen.yml` config file:

```
schema: 
  - 'http://localhost:4000'
  - ./src/apollo/schemas/*.ts
config:
  strict: true
  skipTypename: false
  immutableTypes: true
  typesPrefix: I

  withHooks: true
generates:
  './src/__generated__/index.tsx':
    documents: 
      - src/apollo/mutations/**/*.{ts,tsx}
    plugins:
     - 'typescript'
     - 'typescript-operations'
     - 'typescript-react-apollo'

```

After I tried several times, I figure out the error is from the plugin `typescript-operations`.
But some types will be missing if I get rid of the plugin.
