### ISSUE TITLE
Document how to use environment variables in `.yml` config file

### ISSUE THREAD

**Issue by dukedave** [dotansimha/graphql-code-generator#1737]
**Is your feature request related to a problem? Please describe.**

Hardcoding `YOUR-TOKEN-HERE` when specifying the schema with a **[URL](https://graphql-code-generator.com/docs/getting-started/schema-field#url)** may require checking secrets in to version control (in `codegen.yml`) to use `graphql-codegen` on a CI server.

**Describe the solution you'd like**

Be able to pass headers in via the CLI, or support variables in YAML.

**Describe alternatives you've considered**

1. Checking in `codegen.yml` with a placeholder, and using `sed` to insert the secret.
1. Using the `--header` switch.

**Additional context**

It appears a `--header` switch was supported, but [was removed](https://github.com/dotansimha/graphql-code-generator/issues/860) on 0.14.0 😞 

Prisma support variables in YAML [like this](https://github.com/prisma/graphql-config/blob/4c09eef3b97ebfbde6aa3710dfcfb1fe845f6d60/specification.md#referencing-environment-variables).

**Comment by revskill10** [comment]
I don't even know who created `yaml` format instead of just using `json`. What a bad invention, which leads to cascade bad practices :(

**Comment by dotansimha** [comment]
@revskill10 We support JSON config as well :)
@dukedave you can use environment variables to pass it, see this: https://github.com/dotansimha/graphql-code-generator/pull/1368

**Comment by dukedave** [comment]
@dotansimha great! Should I do a PR to update the docs?

**Comment by dotansimha** [comment]
@dukedave It would be great :)

**Comment by Pomazan-Bogdan** [comment]
Hey.
Necessary solution, as I use closure points
I did not go in all the issue how to specifically transfer the header in the yml file

**Comment by dotansimha** [comment]
Docs are updated now: https://graphql-code-generator.com/docs/getting-started/codegen-config#environment-variables

**Comment by Pomazan-Bogdan** [comment]
> ```yaml
> headers: 
>   x-hasura-admin-secret: ${MYKEY}
>   content-type: ${CONTENT_TYPE:application/json}
> ```

Not Work(
`TypeError: Cannot create property 'source' on string 'Unable to download schema from remote: Missing Authorization header in JWT authentication mode'`

**Comment by Pomazan-Bogdan** [comment]
```
overwrite: true
schema: https://graphql.ecoalition.org.ua/v1/graphql
headers:
  - x-hasura-admin-secret: {1PocfEqWXPPMX***}
  - content-type: ${CONTENT_TYPE:application/json}
documents: "src/**/*.graphql"
generates:
  src/graphql/index.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
  src/graphql/fragments.tsx:
    plugins:
      - fragment-matcher
```

**Comment by dotansimha** [comment]
@Pomazan-Bogdan it looks like you need to specify `Authorization` header but you didn't... please make sure what is the name of the headers that you need to pass.

**Comment by Pomazan-Bogdan** [comment]
x-hasura-admin-secret ))

**Comment by dotansimha** [comment]
@Pomazan-Bogdan can you try this way? 
```yml
headers:
  x-hasura-admin-secret: {1PocfEqWXPPMX***}
  content-type: ${CONTENT_TYPE:application/json}
```

**Comment by Pomazan-Bogdan** [comment]
not work too

**Comment by dotansimha** [comment]
@Pomazan-Bogdan my bad, can you try this? 

```yml
schema:
  - https://graphql.ecoalition.org.ua/v1/graphql:
      headers:
        x-hasura-admin-secret: {1PocfEqWXPPMX***}
        content-type: ${CONTENT_TYPE:application/json}
```

**Comment by Pomazan-Bogdan** [comment]
@dotansimha 
`   TypeError: Cannot create property 'source' on string 'Unable to download schema from remote: invalid x-hasura-admin-secret/x-hasura-access-key'`

**Comment by Pomazan-Bogdan** [comment]
= 
`{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "access-denied"
      },
      "message": "invalid x-hasura-admin-secret/x-hasura-access-key"
    }
  ]
}`

**Comment by Pomazan-Bogdan** [comment]
error in value key

**Comment by Pomazan-Bogdan** [comment]
"@graphql-codegen/cli": "^1.4.0", О_о

**Comment by dotansimha** [comment]
Can you try with the explicit values? 

```yml
schema:
  - https://graphql.ecoalition.org.ua/v1/graphql:
      headers:
        X-Hasura-Admin-Secret: PUT_SECRET_HERE
        Content-Type: application/json
```

also, does an introspection request works for you? with tools like GraphQL Playground (or Postman)

**Comment by Pomazan-Bogdan** [comment]
@dotansimha 
This format works!
Thank.

**Comment by Pomazan-Bogdan** [comment]
I think this should be mentioned separately in the documentation.

**Comment by dotansimha** [comment]
@Pomazan-Bogdan 
It's documents in our website: https://graphql-code-generator.com/docs/getting-started/schema-field#url

**Comment by Pomazan-Bogdan** [comment]
add to documents line "Content-Type: application/json"  as sample?) 


I mean that I saw the documentation, but I couldn’t understand what to do.
Without the second line. and not abstract, not perceived (

**Comment by dotansimha** [comment]
@Pomazan-Bogdan The example just shows how to add any header, not specific ones. 
I even think you can remove `Content-Type: application/json` because the HTTP request that the codegen does it an introspection, which is already JSON.

**Comment by thendra** [comment]
Can someone also please update the docs on how to turn on DEBUG and VERBOSE modes? It currently says to set them as environment variables in the  but how to do that is unclear at the moment :) https://graphql-code-generator.com/docs/getting-started/codegen-config/#debug-mode

**Comment by ardatan** [comment]
Setting environmental variables depend on your OS. Let's say on POSIX(Mac, Linux etc) environments you can set an environmental variable only for that command like below;
```sh
DEBUG=1 yarn graphql-codegen
```

**Comment by thendra** [comment]
Brilliant, thanks!

**Comment by ian-maurmann** [comment]
> I don't even know who created `yaml` format instead of just using `json`. What a bad invention, which leads to cascade bad practices :(

Sidenote for the history books: 
Yaml was released in 2001. Douglas Crockford released json in 2002.

**Comment by mvilrokx** [comment]
I know this issue is closed but if somebody lands here to figure out why their Headers aren't picked up, even though you configured them in your `.yml` config file, it seems that correct indentation is the key to get this working. I am using Hasura and require a `x-hasura-admin-secret` Header in my setup but I could not get it to work, no matter what instructions I followed (which is how I ended up here). The only thing that worked for me was to have 2 tabs indentation in front of `headers`, i.e. this works:

```yaml
schema:
  - ${SCHEMA_PATH}:
      headers:
        x-hasura-admin-secret: ${HASURA_ADMIN_SECRET}
```

This _does not_ work:
```yaml
schema:
  - ${SCHEMA_PATH}:
    headers:
      x-hasura-admin-secret: ${HASURA_ADMIN_SECRET}
```

This would produce `Failed to load schema from http://localhost:8080/v1/graphql,headers:` 

As you can see, the actual value of `headers` is missing.
