### ISSUE TITLE
TypeScript React Apollo makes `variables` prop required on Mutation components 

### ISSUE THREAD

**Issue by dislick** [dotansimha/graphql-code-generator#1741]
When generating mutation components the `variables` prop is now always required, which resulted in a lot of type exceptions in our code base.

This GraphQL mutation:

```graphql
mutation addPersonMutation($name: String!) {
  addPerson(name: $name) {
    id
    name
  }
}
```

is generated like this:

```typescript
export const AddPersonMutationComponent = (
  props: Omit<
    Omit<
      ReactApollo.MutationProps<
        AddPersonMutationMutation,
        AddPersonMutationMutationVariables
      >,
      'mutation'
    >,
    'variables'
  > & { variables: AddPersonMutationMutationVariables }, // variables should be optional for Mutations
) => (
  <ReactApollo.Mutation<
    AddPersonMutationMutation,
    AddPersonMutationMutationVariables
  >
    mutation={AddPersonMutationDocument}
    {...props}
  />
);
```

My `codegen.yml` config file:

```yml
overwrite: true
schema: 'http://localhost:3000/graphql'
documents:
  - 'src/**/*.query.graphql'
  - 'src/**/*.mutation.graphql'
generates:
  src/generated/graphql.tsx:
    plugins:
      - typescript
      - typescript-operations
      - 'typescript-react-apollo'
    config:
      scalars:
        Date: number
      noGraphQLTag: false
```

It's maybe related to PR #1687
