### ISSUE TITLE
Incorrect scalar translation of index signature for TypeScript

### ISSUE THREAD

**Issue by kapral18** [dotansimha/graphql-code-generator#1753]
**Describe the bug**

When overwriting `Date` scalar in `codegen.yml` in gatsby project, I get incorrect translation of `JSON: { [key: string]: any }` index signature to `JSON: [object Object]` in TypeScript. https://graphql-code-generator.com/docs/plugins/typescript#usage-example

**To Reproduce**

1. My GraphQL schema:

https://raw.githubusercontent.com/kapral18/karenjs.com/TS/schema.json

2. My GraphQL operations:

https://github.com/kapral18/karenjs.com/tree/TS

3. My `codegen.yml` config file:

```yml
schema: http://localhost:8000/___graphql
documents:
    - ./src/**/*.{ts,tsx}
    - ./node_modules/gatsby-*/**/*.js
generates:
    ./src/types/generated/index.ts:
        config:
            immutableTypes: true
            avoidOptionals: true
            scalars:
                Date: string
                JSON: { [key: string]: any }
        plugins:
            - typescript
            - typescript-operations

```

**Expected behavior**
`JSON: { [key: string]: any }` should be correctly translated into `JSON: { [key: string]: any }` type in `src/types/generated/index.ts`

**Environment:**

- OS: macOS 10.14.4
- `@graphql-codegen/...`:         
	"@graphql-codegen/cli": "1.1.0",
    "@graphql-codegen/typescript": "1.1.0",
    "@graphql-codegen/typescript-operations": "1.1.0",
- NodeJS: 10.15.3
