### ISSUE TITLE
TypeScript compaibility plugin issues with inline fragments since 1.1.1

### ISSUE THREAD

**Issue by OneCyrus** [dotansimha/graphql-code-generator#1775]
**Describe the bug**
since typescript compatibility 1.1.1 we have the following issue. with 1.1.0 it works fine.

 → Cannot read property 'type' of undefined**

```
[17:24:49] Parse configuration [started]
[17:24:49] Parse configuration [completed]
[17:24:49] Generate outputs [started]
[17:24:49] Generate ./Scripts/shared/api/api.ts [started]
[17:24:49] Generate ./Scripts/shared/fragmentTypes.json [started]
[17:24:49] Load GraphQL schemas [started]
[17:24:49] Load GraphQL schemas [started]
[17:24:49] Load GraphQL schemas [completed]
[17:24:49] Load GraphQL schemas [completed]
[17:24:49] Load GraphQL documents [started]
[17:24:49] Load GraphQL documents [started]
[17:24:49] Load GraphQL documents [completed]
[17:24:49] Load GraphQL documents [completed]
[17:24:49] Generate [started]
[17:24:49] Generate [started]
[17:24:50] Generate [failed]
[17:24:50] → Cannot read property 'type' of undefined**
[17:24:50] Generate ./Scripts/shared/api/api.ts [failed]
[17:24:50] → Cannot read property 'type' of undefined**
[17:24:50] Generate [completed]
[17:24:50] Generate ./Scripts/shared/fragmentTypes.json [completed]
[17:24:50] Generate outputs [failed]
```

**To Reproduce**

graphql-codegen --config codegen.js

[schema.txt](https://github.com/dotansimha/graphql-code-generator/files/3121934/schema.txt)

2. My GraphQL operations:

```graphql
query fetchServerAnalyticsData($uid: String!) {
  process {
    servers(where: { uid: $uid }) {
      uid
      sources
      active
      principalName
      systemClass
      systemType
      getHostVirtualMachines {
        id
        uid
        host
        displayName
        storage
        sources
        vmType
        active
        vCenterName
        vmVersion
        dataCenterName
        collector
        monitoringGroup
      }
      imacs {
        ... on ServerChangeImac {
          __typename
          requestedAt
          mutatedBy
          mutationContext
          ticketNumber
          note
          active
          cIState
          customer
          patchWindow
          primaryOwner
          region
          systemClass
          businessModules
          description
          isVisibleToCustomer
          isManagedByGIA
          infrastructure
          serviceWindowPft
          serviceWindowApp
          comment
          investmentNumbers
          contractNumbers
          assetNumbers
          assignedServices
        }
        ... on ServerDecomImac {
          requestedAt
          ticketNumber
          mutatedBy
          mutationContext
          note
          __typename
        }
        ... on ServerSetupImac {
          mutatedBy
          mutationContext
          requestedAt
          ticketNumber
          note
          imacId
          archId
          currentState
          __typename
          backupPolicy
          explanation
          region
          description
          platformDistributionComment
          platformInstallComment
          satComment
          networkComment
          platformConfigComment
          serverType
          networkVlan
          hostname
          ip
          subnetMask
          defaultGateway
          vlan
          vlanId
          domain
          primaryDns
          secondaryDns
          computeCluster
          storageSystem
          passwordSaved
          customer
          patchWindow
          businessModules
          primaryOwner
          secondaryOwner
          requestedBy
          scomUser
          sccmUser
          scepUser
          scsmUser
          visionAppUser
          backupUser
          serverSize {
            name
            cpu
            memory
            disk
          }
          sla {
            application
            platform
          }
          systemClass
        }
      }
    }
  }
}

```

3. My `codegen.js` config file:

```yml
process.env.VERBOSE = true;
process.env.DEBUG = true;

module.exports = {
  schema: "intro.json",
  documents: ["Scripts/**/*.graphql"],
  config: {
    strict: true,
    namingConvention: {
      default: "change-case#pascalCase",
      enumValues: "change-case#upperCase"
    }
  },
  overwrite: true,
  generates: {
    "./Scripts/shared/api/api.ts": {
      config: {
        resolvers: false
      },
      plugins: ["typescript", "typescript-operations", "typescript-compatibility"]
    },
    "./Scripts/shared/fragmentTypes.json": {
      plugins: ["fragment-matcher"]
    }
  }
};

```

**Expected behavior**
no error while building and a api.ts file

**Environment:**

- OS: 
- `@graphql-codegen/...`: 1.1.1
- NodeJS: v10.13.0

**Additional context**
excluding the grapqhl documents creates the api. it looks like the issue is in combination with the inline fragments.
