### ISSUE TITLE
GraphQL alias support

### ISSUE THREAD

**Issue by elie222** [dotansimha/graphql-code-generator#1787]
Are aliases supported?

For example:

```gql
  query GetTopBarData {
    iosUsers: platformUsers(platform: "ios") {
      users
      percentageFull
    }
    androidUsers: platformUsers(platform: "android") {
      users
      percentageFull
    }
    webUsers: platformUsers(platform: "web") {
      users
      percentageFull
    }
  }
```

But the generated types file only includes:

```ts
export type Query = {
  platformUsers?: Maybe<PlatformData>
}
```

I'd like to access `data.androidUsers`, but only `data.platformUsers` is a known type.

I am not making use of `.graphql` files. Just `graphql-tag` within a TS file. Not sure if that effects how the types are generated.

**Comment by dotansimha** [comment]
Hi @elie222,
The `extend type Query` is the base type that comes from your `typescript` plugin, and based on your GraphQL schema types.
You need to add `typescript-operations` and then it will generate a type for your specific `GetTopBarData` query, which fields with aliased fields pointing to the `Query['platformUsers']` fields.

**Comment by jiaoqiqi** [comment]
Hi @dotansimha I had the similar issue when using alias with directive like this , but after generate the type , there only has `username` field in my fragment type bu not in the query result type, do you have any suggestions on this?

```
fragment MyFragment {
 name
 username: name
}

query myQuery{
 ...MyFragment
}
```

And my part of `codegen.yml` looks like this
```
documents: "src/**/*.graphql"
generates:
  src/graphql/types/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      omitOperationSuffix: true
      preResolveTypes: true
```
