### ISSUE TITLE
Not generating types for queries

### ISSUE THREAD

**Issue by marcosfede** [dotansimha/graphql-code-generator#180]
Hi, I'm trying to generate types for my queries using [this](https://github.com/marcosfede/ts-react-apollo-starter/blob/swapi/package.json#L31) command (tried some other variations as well), But its only generating types based on my schema and not the queries I make in my react components (output [here](https://github.com/marcosfede/ts-react-apollo-starter/blob/swapi/src/graphql-types.d.ts))
I expect to also see some types matching the `allPeople` query inside `allPeople.graphql`. What am I doing wrong? Thanks!

**Comment by rdemetrescu** [comment]
This "It seems like you provided a GraphQL schema instead of GraphQL document" warning happened to me too, when I upgraded graphql package version from 0.12.3 to 0.13.0

**Comment by appsolutegeek** [comment]
I have just installed it now, and I am using

    "apollo-server-express": "^1.3.2",

I am getting the same issues, server-side generation of schema types works great but the client side generation of *.graphql file, does not.

I am using the following command

`gql-gen --url http://localhost:3000/graphql --template ts --out ./src/typings \"./**/*.graphql\"`

**Comment by jmca** [comment]
Same issue here. Error seems to throw on `"graphql": "^0.13.1"`, not on `0.12.3`.

**Comment by FredyC** [comment]
See https://github.com/dotansimha/graphql-code-generator/issues/181#issuecomment-368255835

**Comment by dotansimha** [comment]
Please update to the latest version of the codegen, it should work now with 0.13 :)

**Comment by dotansimha** [comment]
@JohannesHoppe try to wrap your glob selector with "...", your command should be something like that:

```
gql-gen --schema https://api.angular.schule/graphql --template graphql-codegen-typescript-template --out ./src/app/graphql-types.ts "./src/**/*.ts"
```

(and your probably need to escape it if you are putting it inside `package.json`). It happens because your file system resolves the `*` before `glob` gets it, and it does not support features like `**` (for recursive lookup)

**Comment by JohannesHoppe** [comment]
Many thanks. You saved my day (or better: night)! 😅 

👍 👍 👍

**Comment by bardhyliis** [comment]
For anyone who stumbled upon this now:
Here's what worked for me:

codegen.yml, when Types are not generated:
```
overwrite: true
schema: "http://localhost:5000/graphql"
documents: "src/**/*.graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript-apollo-angular"
```

codegen.yml, when types are generated correctly:
```
overwrite: true
schema: "http://localhost:5000/graphql"
documents: "src/**/*.graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-apollo-angular"
```
