### ISSUE TITLE
typescript-react-apollo & typescript-resolvers plugin collision

### ISSUE THREAD

**Issue by yoavain-sundaysky** [dotansimha/graphql-code-generator#1800]
Trying to generate both resolvers & react-apollo in the same config result in a file with error.
The following line appears twice:
```typescript
export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
```

**To Reproduce**

1. My GraphQL schema:
test.graphql
```graphql
schema {
	query: Query
	mutation: Mutation
}

type Query {
	_: Boolean
}
type Mutation {
	_: Boolean
}
type Test {
	id: ID!
	created: String!
	updated: String!
	name: String!
	description: String
}

extend type Query {
	tests: [Test]
	test(id: ID!): Test
}
```

2. My GraphQL operations:
testQuery.graphql
```graphql
query getTest($id: ID!) {
	test(id: $id) {
		id
		name
		description
	}
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema:
  - test.graphql
documents:
  - testQuery.graphql
generates:
  ./graphqlGeneratedTypes/graphql.tsx:
    config:
      typesPrefix: "Gql"
      namingConvention:
        typeNames: change-case#pascalCase
        enumValues: change-case#upperCase
      immutableTypes: true
    plugins:
      - typescript
      - typescript-operations
      - typescript-resolvers
      - typescript-react-apollo
```

**Expected behavior**
A valid typescript file

**Environment:**

- OS: Windows
- `@graphql-codegen/...`: 1.1.1
- NodeJS: 10.15.3

**Additional context**

**Comment by dotansimha** [comment]
Just to be sure - you are using both on the same output file because you implement GraphQL schema on the client side, right?

**Comment by yoavain-sundaysky** [comment]
I have a project with both the server and client, and I tried to generate all types to the same output file.
I guess this isn't such a common use case, as most project will have the server and client separated.
I guess I could create 2 separate output files, one for the server, and one for the client.

**Comment by dotansimha** [comment]
@yoavain-sundaysky Just separate it like that:

```
overwrite: true
schema: test.graphql
generates:
  ./client/graphql.tsx:
    config:
      typesPrefix: "Gql"
      namingConvention:
        typeNames: change-case#pascalCase
        enumValues: change-case#upperCase
      immutableTypes: true
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
generates:
  ./server/graphql.ts:
    documents: testQuery.graphql
    config:
      typesPrefix: "Gql"
      namingConvention:
        typeNames: change-case#pascalCase
        enumValues: change-case#upperCase
      immutableTypes: true
    plugins:
      - typescript
      - typescript-resolvers
```

Because it's not a good idea to merge them, but you can use the codegen to generate more than one file at a time.
