### ISSUE TITLE
Missing properties

### ISSUE THREAD

**Issue by majdi** [dotansimha/graphql-code-generator#1804]
**Describe the bug**
Hello, I generate all typescript definition from my schema.graphql in a package called `@project/graphql` that I published. In another project, I install the package to have the following code:

```js
import { ApolloServer, Config } from 'apollo-server'
import schema from '@project/graphql' // that handle my typescript types + schema

const config: Config = {
  schema
}

const server = new ApolloServer(config)
server.listen(port).then(({ url }) => {
  console.log('GraphQL API is running at %s in %s mode', url, env)
})
```

Everything works but on typescript check I have an error on config:
```bash
Type 'typeof import("(...)/project/generated/graphql")' is missing the following properties from type 'GraphQLSchema': astNode, extensionASTNodes, getQueryType, getMutationType, and 8 more.ts(2740)
types.d.ts(31, 5): The expected type comes from property 'schema' which is declared here on type 'Config'
```

Note that generated/graphql is the file generated by codegen.

**To Reproduce**

1. My GraphQL schema:

```graphql
# source: http://localhost:8686/graphql
# timestamp: Wed May 01 2019 22:50:02 GMT+0200 (Central European Summer Time)

type Mutation {
  _empty: String
}

type Query {
  hello: String
}

type Subscription {
  _empty: String
}
```

2. My GraphQL operations:

```graphql
# Not yet
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: 'http://localhost:8686'
documents: 'generated/schema.graphql'
generates:
  generated/graphql.d.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-resolvers'
```

**Environment:**

- OS: MacOS
- `@graphql-codegen/...`:  ^1.1.3
- NodeJS: v11.1.0

Thank you :)

**Comment by dotansimha** [comment]
@majdi `documents` is for your queries/mutations/fragments/subscriptions, and not for schemas.
Also, you are mixing 2 plugins that usually don't go together.
`typescript-operations` is for documents (operations) and should be used in client-side env. 
`typescript-resolvers` is for resolvers signature  and should be used in server-side env. 

Also, what does `generated/schema.graphql` contains? 

You should use either a static schema from `.graphql` file:

```
overwrite: true
schema: my-schema.graphql
generates:
  generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
```

Or, use an endpoint for your schema:

```
overwrite: true
schema: http://localhost:8686
generates:
  generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
```

And, if you are using a client-side environment, it should be something like that:

```
overwrite: true
schema: http://localhost:8686
documents: src/**/*.graphql
generates:
  generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
```
