### ISSUE TITLE
Specify default environment variable values in codegen.yml

### ISSUE THREAD

**Issue by steebchen** [dotansimha/graphql-code-generator#1812]
It would be awesome if you could specify a default value for environment variables, like you can usually do with yaml files such as in docker:

```yaml
version: '3'

services:
  lb:
    image: nginx:latest
    environment:
      PASSWORD: "${PASS:-secret}"
```
