### ISSUE TITLE
Export multiple files from client generators

### ISSUE THREAD

**Issue by mxstbr** [dotansimha/graphql-code-generator#1815]
**Is your feature request related to a problem? Please describe.**

When generating client-side components (e.g. with the react-apollo or upcoming urql generators), all the query components and hooks are put into a single file.

That is bad news for code-splitting, as many of these components might only be used on a single page but now all of them will always be bundled on every page.

**Describe the solution you'd like**

It would be great if I could generate one file next to every query I have. For example:

```yaml
documents: "src/**/*.graphql"
generates:
  whatever.tsx:
    config:
      relativeFiles: true
    plugins:
      - "typescript-urql"
```

This would now create a component file next to every `.graphql` file in my project, and I could import them each individually.
