### ISSUE TITLE
Errors encountered while loading schema files are silently ignored

### ISSUE THREAD

**Issue by Myrannas** [dotansimha/graphql-code-generator#1833]
**Is your feature request related to a problem? Please describe.**

Sorry if this duplicates another issue - I couldn't find something which matched this particular problem that was still open.

My team is using graphql-codegen to generate types from our node service. As part of generating types we are transpiling our typescript code using `ts-node/register`.

If there is any compilation issue / or an issue actually running the code the code generation command fails without actually showing the error. Instead it shows the following:

```
$ graphql-codegen
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./src/types.d.ts
      ✖ Load GraphQL schemas
        → All found files for glob expression "./src/schema.ts" are not valid or empty, please check it and try again!
        Load GraphQL documents
        Generate


 Found 1 error

  ✖ ./src/types.d.ts
    Error: All found files for glob expression "./src/schema.ts" are not valid or empty, please check it and try again!


Something went wrong

```

**Describe the solution you'd like**
If an error is encountered when trying to load the schema it'd be great if it was displayed.

**Describe alternatives you've considered**
We have considered running `tsc` with no emit turned on as part of our command to actually run the codegen command. This is much slower as it means we are effectively compiling everything twice.

**Additional context**
Our config is:
```
overwrite: true
schema: ./src/schema.ts
require:
  - ts-node/register/transpile-only
generates:
  ./src/types.d.ts:
    plugins:
      - add: '/* tslint:disable */'
      - typescript
      - typescript-resolvers
...
```
