### ISSUE TITLE
Angular client mutation types not working

### ISSUE THREAD

**Issue by steebchen** [dotansimha/graphql-code-generator#1837]
**Describe the bug**
When using the apollo-angular client, types are not generated properly for mutations.

No `.data` found:

![Selection_053](https://user-images.githubusercontent.com/5013932/57394943-1833f680-71c7-11e9-8321-f320107bc13b.jpg)

Meanwhile, it works perfectly with queries:

![Selection_060](https://user-images.githubusercontent.com/5013932/57395089-81b40500-71c7-11e9-8e2a-7fed9598eb75.jpg)

For mutations, I now have to manually set the type to get correct types:

![Selection_049](https://user-images.githubusercontent.com/5013932/57395154-a90ad200-71c7-11e9-9241-970fdc375710.jpg)

**To Reproduce**

1. My GraphQL schema:

```graphql
type Mutation {
	register(input: RegisterInput!): RegisterPayload!
}

input RegisterInput {
	email: String!
	password: String!
}

interface AuthPayload {
	session: Session!
	user: User!
}

type RegisterPayload implements AuthPayload {
	session: Session!
	user: User!
}
```

2. My GraphQL operations:

```graphql
mutation Register($input: RegisterInput!) {
	register(input: $input) {
		session {
			id
			token
		}

		user {
			...UserAttributes
		}
	}
}

fragment UserAttributes on User {
	id
	createdAt
	firstName
	lastName
}
```

3. My `codegen.yml` config file:

```yml
schema:
  - ${API_ENDPOINT}
documents: src/**/*.graphql
overwrite: true
generates:
  src/app/graphql/graphql.generated.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-apollo-angular
    config:
      immutableTypes: true
      namingConvention:
        enumValues: change-case#upperCase
      scalars:
        Time: Date
```

**Expected behavior**
The `res` parameter in the first screenshot should have correct types.

**Environment:**

- OS: linux
- "@graphql-codegen/cli": "^1.0.0",
- "@graphql-codegen/typescript": "^1.0.0",
- "@graphql-codegen/typescript-apollo-angular": "^1.1.3",
- "@graphql-codegen/typescript-operations": "^1.0.0",
- NodeJS: v10.15.0
