### ISSUE TITLE
Missing Maybe type when using only typescript-operations

### ISSUE THREAD

**Issue by webberwang** [dotansimha/graphql-code-generator#1845]
**Describe the bug**
When using only `typescript-operations` plugin, the generated file is missing `type Maybe`

![2019-05-12_01-41-15](https://user-images.githubusercontent.com/26264925/57579859-18e2bc00-7457-11e9-99bf-9527e7b66103.png)

**To Reproduce**

1. My GraphQL schema:

```graphql
# Could be any
```

2. My GraphQL operations:

```graphql
# Could be any
```

3. My `codegen.yml` config file:

```yml
schema: 'http://localhost:4000/graphql'
documents:
  - src/models/container--update.graphql
generates:
  ./src/types.ts:
    plugins:
      #      - typescript
      - typescript-operations
    config:
```

**Expected behavior**
Expect `type Maybe` to be at top of file.

**Environment:**

- OS: macOS 10.14.4
- `@graphql-codegen/cli: 1.1.3`: 
- NodeJS: v11.12.0

**Additional context**
I think this was intentional, because normally you would generate with `typescript` plugin. But I think being able to separate GraphQL schema type & document types is a good idea.
