### ISSUE TITLE
Duplicate identifier 'Omit'

### ISSUE THREAD

**Issue by veeramarni** [dotansimha/graphql-code-generator#1851]
**Describe the bug**
 
With the following configuration, we get Omit twice.

```
export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
```
**To Reproduce**

3. My `codegen.yml` config file:

```yml
schema: 
  - "./servers/backend-server/src/api/root-schema.graphqls"
  - "./packages/fullstack-graphql-schema/src/**/*.graphql"
  - "./packages/fullstack-client-state/src/**/*.graphql"
documents: 
  - "packages/fullstack-client-state/src/**/*.gql"
generates:
  typings/graphql.d.ts:
    plugins:
      - typescript-graphql-files-modules
  packages/fullstack-client-state/src/graphql/models.ts:
    config:
        noNamespaces: true
        contextType: ./interfaces/context#MyContext
        withMutationFn: false
        withHOC: false
        withComponent: false
    plugins:
      - add: |
          /* tslint:disable */
      - typescript
      - typescript-operations
      - typescript-resolvers
      - typescript-react-apollo
```

**Expected behavior**

Shouldn't add duplicate `Omit`

If I remove `typescript-resolvers`, we don't have the issue. But we want `typescript-resolvers` for resolvers on the client side.

**Environment:**
