### ISSUE TITLE
How to load TypeScript schema (.ts) with custom path imports defined in tsconfig.json?

### ISSUE THREAD

**Issue by fabis94** [dotansimha/graphql-code-generator#1874]
I've got a schema.ts like this:
```ts
import { makeExecutableSchema } from "graphql-tools";
import typeDefs from "~/graphql/typeDefs/typeDefs";

/**
 * GraphQL Schema used by this server
 */
export default makeExecutableSchema({
  typeDefs
  // resolvers
});
```

For some reason the generator fails to load it. The default error outputted to the console tells me nothing of use - "Unable to find matching files for glob: packages/backend/src/graphql/schema.ts". I attached a debugger to the process and arrived at the real place where an error is thrown and found out the actual error: Cannot find module ~/graphql/typeDefs/typeDefs. 

I bet this is because of the custom path. Now, in my project TypeScript knows how to resolve these because of the tsconfig.json that defines these in the "paths" property, but how do I make  the codegen also read the same config so it understands the paths? I know of the "tsconfig-paths" package that could help me with this, but I'm not sure how to use it in this case. I added it to require and specified the --project argument, but it doesn't seem to work.

Here's my codegen.yml:
```yml
overwrite: true
schema: packages/backend/src/graphql/schema.ts
generates:
  packages/backend/src/graphql/generated/types.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
require:
  - ts-node/register
```

**Comment by ardatan** [comment]
```
overwrite: true
schema: packages/backend/src/graphql/schema.ts
generates:
  packages/backend/src/graphql/generated/types.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
require:
  - ts-node/register
  - tsconfig-paths/register
```
Adding tsconfig-paths/register should work. Could you try that?

**Comment by fabis94** [comment]
Didn't work, unfortunately, I had already tried that. Added the 'require' entry and added --project packages/backend/tsconfig.sjon to the command as well. I stepped through the debugger and saw it load in the config, but it doesn't work correctly for some reason. I think it's because it requires the absolute path of the schema.ts file, which might not be supported (it calls require("C:\Code\proj\packages\backend\src\graphql\schema.ts"), as none of the path rewrites apply to it obviously. I'm not sure what's the reason, but I'm fairly confident this could be replicated with any TypeScript repo that uses custom paths.

**Comment by dotansimha** [comment]
@fabis94 I think the issue here is not the `require`, is the fact that you need to provide `--project`. 
The `tsconfig-paths` looks for `tsconfig.json` in `process.cwd`, and in this case it's your root directory, and not `packages/backend/`. 
Instead specifying `--project`, try to specify it using environment variables: `TS_NODE_PROJECT=packages/backend/tsconfig.json` (see https://www.npmjs.com/package/tsconfig-paths#with-ts-node).

**Comment by fabis94** [comment]
@dotansimha The project file is definitely loaded in correctly, I saw it load the correct paths from my config while debugging.

**Comment by dotansimha** [comment]
I see. @fabis94 . Any chance you can create a small reproduction repo? I will help us to fix it faster :)

**Comment by fabis94** [comment]
@dotansimha I tried doing so and to my surprise I couldn't replicate this issue and the import worked fine w/ the same tsconfig.json being loaded. Unfortunately I can't share the original repo, but maybe someone with deep knowledge of inner TypeScript could help me here. I debugged deeper into the actual part where the .ts files get compiled into JS during runtime and noticed that the schema.ts file gets compiled differently in both projects. Here are the differences:

![image](https://user-images.githubusercontent.com/938316/57880360-39c85a00-7827-11e9-9c02-e9407972c434.png)

Basically, in the broken project, for some reason the var __importDefault function isn't generated at the beginning of the file and thus the require('~/graphql/typeDefs/typeDefs) import doesn't get wrapped with it and it can't find it using the custom path definition. The tsconfig.json is identical between both projects and I debugged them both the same way:

Broken proj:
 npx --node-arg=--inspect-brk graphql-codegen --config codegen.yml --project ./packages /backend/tsconfig.json

Working proj:
npx --node-arg=--inspect-brk graphql-codegen --config codegen.yml --project tsconfig.json

The tsconfig looks like this in the broken proj:
```
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2018",
    "module": "commonjs",
    "esModuleInterop": true,
    "baseUrl": "./src",
    "paths": {
      "~/*": ["*"]
    },
    "typeRoots": [
      "./node_modules/@types",
      "./typings",
      "../../node_modules/@types"
    ],
    "lib": ["es2015", "es2016", "es2017", "es2018"],
    "outDir": "build"
  },
  "extends": "../../tsconfig.base.json"
}
```

And it looks like this in the working proj:
```
{
  "compilerOptions": {
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es2018",
    "module": "commonjs",
    "esModuleInterop": true,
    "baseUrl": "./src",
    "paths": {
      "~/*": ["*"],
      "@gql/*": ["subfolder/*"]
    },
    "typeRoots": [
      "./node_modules/@types",
      "./typings",
      "../../node_modules/@types"
    ],
    "lib": ["es2015", "es2016", "es2017", "es2018"],
    "outDir": "build"
  },
  "extends": "../../went/tsconfig.base.json"
}
```

Both of them extend the  exact same tsconfig.base.json file:
```
{
  "compilerOptions": {
    // "noEmit": true,
    "strict": true,
    "allowJs": true,
    "moduleResolution": "node",
    "allowSyntheticDefaultImports": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "skipLibCheck": true
  }
}
```

Codegen.yml in the broken proj:
```
overwrite: true
schema: packages/backend/src/graphql/schema.ts
generates:
  packages/backend/src/graphql/generated/types.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
require:
  - ts-node/register
  - tsconfig-paths/register
```

Codegen.yml in the working proj:
```
overwrite: true
schema: src/schema.ts
generates:
  src/generated/types.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
require:
  - ts-node/register
  - tsconfig-paths/register
```

Hopefully you guys have any ideas cause I'm digging deep in the compiler and close to giving up
