### ISSUE TITLE
typescript-compatibility doesn't work with typescript-react-apollo's withHOC: false

### ISSUE THREAD

**Issue by jrr** [dotansimha/graphql-code-generator#1876]
**Describe the bug**
Using `typescript-compatibility` and `typescript-react-apollo` with `withHOC: false`:

```yaml
generates:
  types.gen.tsx:
    config:
      noGraphqlTag: false
      strict: true
    schema:
      - "schema.graphql"
    documents:
      - "documents/*.graphql"
    plugins:
      - typescript:
      - typescript-operations
      - typescript-react-apollo:
          withComponent: false
          withHOC: false
      - typescript-compatibility
```

I get a generated line like this:
`export type Props = EmployeeCreateWidgetsProps;`, with a squiggle under the right side:

```
types.gen.tsx:90:23 - error TS2304: Cannot find name 'EmployeeCreateWidgetsProps'.

90   export type Props = EmployeeCreateWidgetsProps;
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~
```
**To Reproduce**

clone https://github.com/jrr/gql-codegen-issue, yarn install and `yarn run gql-gen -o`, then open types.gen.tsx.

Using latest stable packages.
