### ISSUE TITLE
Wrong import paths with `near-operation-file` preset (on Windows)

### ISSUE THREAD

**Issue by vhenzl** [dotansimha/graphql-code-generator#1892]
In the recent canary version, with new `near-operation-file` preset, import paths in "near" files are malformed. 

My guess is it that has something to do with Windows file separator, but I wasn't able to replicate it consistently as I got two different behaviours. Either the relative path contains backslashes: 
```js
import * as Types from '..\..\..\__generated__/types';`
```
or there aren't any slashes at all:
```js
import * as Types from "......__generated__/types";
```

Two different projects, the same machine. 

**`codegen.yml` config file:**

```yml
overwrite: true
schema: "schema.graphql"
documents: 'src/**/*.{graphql,tsx}'
generates:
  src/__generated__/types.ts:
    plugins:
      - "typescript"
  src/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: __generated__/types.ts
    plugins:
      - typescript-operations
```

**Environment:**

- OS: Windows 10
- `@graphql-codegen/...@1.1.4-alpha-62ee81ed.50`: 
- NodeJS: v10.15.3
