### ISSUE TITLE
1.2.0: add plugin prepends all root configs; non-string values cause error

### ISSUE THREAD

**Issue by jrr** [dotansimha/graphql-code-generator#1896]
**Describe the bug**
1.2.0 does this:

```
$> gql-gen -o
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate modules/client/graphql/types.gen.tsx
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → a.startsWith is not a function
    ✔ Generate modules/client/graphql/client-types.gen.ts
    ✔ Generate modules/graphql-api/server-types.gen.ts


 Found 1 error

  ✖ modules/client/graphql/types.gen.tsx
    TypeError: a.startsWith is not a function


Something went wrong
```

I suspect it may have broken with this change https://github.com/dotansimha/graphql-code-generator/pull/1869, as it's the only instance of `a.startsWith` I could find in the repo.

I haven't gotten to the bottom of this yet, but here's a mostly-minimized repro config:

```yml
generates:
  modules/client/graphql/types.gen.tsx:
    config:
      strict: true
    schema:
      - "modules/graphql-api/schema.graphql"
      - "modules/client/graphql/schema.graphql"
    documents:
      - "modules/client/graphql/*/*.graphql"
    plugins:
      - add:
          - // hello
      - typescript
```

It looks like perhaps there's some interaction of `strict: true` and the _add_ plugin; remove either one and the error goes away.
