### ISSUE TITLE
Add `@types/graphql` as peer dependency in `typescript-operations` (and document it)

### ISSUE THREAD

**Issue by deklanw** [dotansimha/graphql-code-generator#1899]
**Describe the bug**
All of my mutation hook functions have return type `Promise<any>` in VSCode

E.g.
```
  const logout = useLogoutMutation();

...

  const result = await logout();
```

`logout` has type `MutationFn<LogoutMutation, LogoutMutationVariables>`
`result` has type `any`

But, then if I give `logout` a type manually
```
  const logout: MutationFn<
    LogoutMutation,
    LogoutMutationVariables
  > = useLogoutMutation();
```
**This time with `MutationFn` coming from `react-apollo`** everything works fine: `result` has a good type.

So, it seems that somewhere in react-apollo-hook's `MutationFn` something is going wrong?

**To Reproduce**

Versions:
```
    "@graphql-codegen/cli": "^1.2.0",
    "@graphql-codegen/typescript": "^1.2.0",
    "@graphql-codegen/typescript-operations": "^1.2.0",
    "@graphql-codegen/typescript-react-apollo": "^1.2.0",

...
    "typescript": "3.4.5",
```

config:
```
overwrite: true
schema: 'http://localhost:4000/graphql'
documents: 'src/graphql/**/*.{ts,tsx}'
generates:
  src/generated/graphql.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withMutationFn: true
      withComponent: false
      withHOC: false
      withHooks: true
```
