### ISSUE TITLE
Allow `,` as a delimiter for a type implementing multiple interfaces 

### ISSUE THREAD

**Issue by philiiiiiipp** [dotansimha/graphql-code-generator#1916]
**Describe the bug**
 

AWS AppSync is using `,` to delimit multiple interfaces for the same type

E.g. 

```graphql
interface A {
  a: String
}

interface B {
  b: String
}

type AB implements A, B {
  a: String
  b: String
}
``` 

It seems like this is some non standard way of doing things, as the latest version of the [June 2018 graphql spec](https://graphql.github.io/graphql-spec/June2018/#sec-Interfaces) is using `&` instead of `,`. However apollo is also allowing the `,` syntax suggesting to me that this might have been "the way to do it"  at one point. 

I do not see AWS changing this anytime soon, so I am wondering if its a good idea to add this behavior. ( It would at least help me a lot )

**To Reproduce**

1. My GraphQL schema:

```graphql
interface A {
  a: String
}

interface B {
  b: String
}

type AB implements A, B {
  a: String
  b: String
}
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
schema:
  - ./src/appsync/schema/appsync-schema.graphql
  - ./src/appsync/schema/.generated.appsync.graphql
scalars:
  AWSDateTime: string
  AWSJSON: string
generates:
  ./src/appsync/schema/types.flow.js:
    plugins:
      - flow
    config:
      useFlowReadOnlyTypes: true
      useFlowExactObjects: true
      scalars:
        AWSDateTime: string
        AWSJSON: string

```

**Expected behavior**

Preferrably I would have `,` and `&` handled the same way.
