### ISSUE TITLE
Types of client resolvers should inherit some from the main schema

### ISSUE THREAD

**Issue by const86** [dotansimha/graphql-code-generator#1918]
Client schema extends some types with new properties. At the very least it extends in such way one of `Query`, `Mutation`, or `Subscription`. Then it may add totally new types.

Main resolvers are not affected by client schema in any way. Interfaces are generated from the main schema only. So far so good.

Client resolvers are actually affected by both main and client schema. But that is a bit more complex than simple merging schemas and working from that single merged schema:

1. List of required resolvers must be constructed from _client schema_ only. This is important when you want to `avoidOptionals: true` in resolvers plugin.
2. Parent types (first argument of resolvers) must be taken from the _main schema_. When the client (or apollo-link-state) runs client resolver, it passes the network response as the input. Which has the shape defined in main schema of course. It is arguable if actually using that input in client resolvers is good or bad, but it is what it is. There is a bonus catch here. Parent object will have only fields selected by particular operation, so it varies in runtime. In other words, the types should be recursively wrapped in `Partial`.
3. Result types of resolvers are the types from merged schema. Whew, that is done right today.
4. Extending inputs doesn't seem to work (nor it appears useful to me), so nothing to do here. Probably warn or fail in case it's detected.

**Comment by dotansimha** [comment]
@const86 I think you can generate 2 resolvers signature files, one for client schema and one for server schema (and each section in `generates` can have it's own configuration).

Something like that:

```yml
generates:
   client/src/resolvers.ts:
       schema: client/src/client-schema.graphql
       config:
          avoidOptionals: true
       plugins: 
          - typescript
          - typescript-resolvers

   server/src/resolvers.ts:
       schema: server/src/server-schema.graphql
       plugins: 
          - typescript
          - typescript-resolvers
```

Or I'm missing something?

**Comment by const86** [comment]
Yes, two sets of interfaces are most likely needed anyway. One for the server, one for the client. What I meant, is one level deeper. The client resolver interfaces in general are affected by both server and client schema.
You can get away with the your config in simple cases when client schema does not extend any types from server schema and only adds top level operations that return client private types.
In more complex cases both schemas come to play in a non-trivial way. You can not simply merge the schema and work from that without tracking what come from which schema. Current config and CLI work only in such simple fashion.
I can put together a sample project. It would take a few hours to keep it clear and short...
We have such 'client extensions' in our project. On one hand, it'd nice to have perfect interfaces even for such cases (though it's not too annoying, we already have workarounds).
On the other hand, I have a feeling that such extensions are signs of bad design. In which case the whole thought should be rephrased: in case of overlap is detected between client and server schema, should a warning about potential mess.

**Comment by veeramarni** [comment]
I'm interested in this case as well as I need to split the types between server and client. I believe adding `parentSchema` options like below might help. Any thoughts?


```
generates:
   client/src/resolvers.ts:
       parentSchema: server/src/server-schema.graphql
       schema: client/src/client-schema.graphql
      parentSchemaConfig: 
           packageName: server-package
       config:
          avoidOptionals: true
       plugins: 
          - typescript
          - typescript-resolvers
```

and the generated typescript would like
```
#// generated-model.ts
import { ParentType } from 'server-package'

export interface ClientType implements ParentType {
  clientCustom: string
}

```

**Comment by kamilkisiela** [comment]
```yaml
generates:
  client/src/resolvers.ts:
    schema:
      - server/schema.graphql
      - client/schema.graphql
    plugins:
      - typescript
      - typescript-resolvers
```

GraphQL Code Generator supports multiple schemas, maybe simply merging client and server solves the issue?
