### ISSUE TITLE
Update Document How To Use Headers in `.yml` file

### ISSUE THREAD

**Issue by jcmoore0** [dotansimha/graphql-code-generator#1933]
**Describe the bug**
 

**To Reproduce**

1. Example `codegen.yml` config file:

```
schema: 
  - "http://localhost:4000":
      headers:
      Authorization: "Bearer [KEY]"
generates:
  ./src/app/graphql/generated/gql-gen-schema.json:
    plugins:
      - "introspection"
```

**Expected behavior**
Headers are parsed and passed.

**Additional context**
This example is not correct.   Headers need to be an object or array.

This works: 

```
schema: 
  - "http://localhost:4000":
      headers: {Authorization: "Bearer [KEY]"}
generates:
  ./src/app/graphql/generated/gql-gen-schema.json:
    plugins:
      - "introspection"
```

Please update docs.
Thanks,

**Comment by KyleMcNutt** [comment]
Also it would be really great to see an example of how to use this in a the programmatic API. Bearer token key's in our case will change very often, so we programmaticaly retrieve them, and need to feed them into the `codegen` function (https://graphql-code-generator.com/docs/getting-started/programmatic-usage). How to do that, would be a great thing to include in the docs!

**Comment by dotansimha** [comment]
@jcmoore0 The example in https://graphql-code-generator.com/docs/getting-started/schema-field#url is valid, just make sure you file indentation is valid (because i effects `yml` files).

You example has missing spaces before `Authorization`.

@KyleMcNutt The programatic usage accepts `GraphQLSchema` as an input, so it has anything to do with headers. 
You can use `loadSchema` from `graphql-toolkit` in order to load your schema from a url (and pass `headers`).

**Comment by KyleMcNutt** [comment]
@dotansimha Then the docs should be updated to make that more clear. As is, I assumed the `schema` field in the programmatic API would take any of the same params as the `schema` prop in the YAML file.

**Comment by swillis12** [comment]
So far with every example I've tried I can't get the headers to work. Who has this working that can share their yaml file?

**Comment by dotansimha** [comment]
@swillis12 can you please share your `codegen.yml` file? It's tricky because you need to verify your whitespaces in YAML files.

**Comment by kuncevic** [comment]
Is there anyway to pass the Authorization key from command line?

**Comment by ardatan** [comment]
You can use env variables @kuncevic

**Comment by kuncevic** [comment]
> You can use env variables @kuncevic
can you elaborate more on that?
and here is more input - I have npm script:
```
”gql:introspect": "npm run generate -- --config projects/shared-library/src/lib/graphql/config/introspect.yml”
```

my `introspect.yml` contain an Authorization token
`Authorization: "Bearer xyz..."`

So, I want somehow to pass that token trough the npm script instead having that hard coded in my  `introspect.yml` file

**Comment by ardatan** [comment]
I mean combining these two;
https://graphql-code-generator.com/docs/getting-started/codegen-config#environment-variables
and
https://graphql-code-generator.com/docs/getting-started/schema-field#url
```yml
schema: 
  - "http://localhost:4000":
      headers:
      Authorization: "Bearer ${AUTH_TOKEN}"
```

So you can pass authentication token using env variables like;
```yml
AUTH_TOKEN=... graphql-codegen ...
```

**Comment by kuncevic** [comment]
@ardatan great, thanks for your help!

**Comment by matthewdfleming** [comment]
> Also it would be really great to see an example of how to use this in a the programmatic API. Bearer token key's in our case will change very often, so we programmaticaly retrieve them, and need to feed them into the `codegen` function (https://graphql-code-generator.com/docs/getting-started/programmatic-usage). How to do that, would be a great thing to include in the docs!

I'm using this to add some dynamic headers to the context when using the Mesh SDK programmatically.
Let's say I have a handler with operationHeaders like so:
```
 - name: WhateverYouCallThis
    handler:
      graphql:
        endpoint: '{env.ENDPOINT_URL}'
        operationHeaders:
          # Please do not use capital letters while getting the headers
          # Use "{context.headers['x-my-api-token']}" if you want just the value of the header
          "userToken": "{context.headers['authorization']}"
```

To add that 'authorization' header to the context via the generated SDK, I used:

```typescript
  const sdk = getMeshSDK({
    headers: {
      // the context of this sdk call is from an api with a query param named token
      authorization: req.query['token'],
    },
  });
```
So if I hit the api route like this for example: http://localhost:3000/api?token=blah
the `context.headers['authorization']` in the call to the WhateverYouCallThis handler would be `blah`
