### ISSUE TITLE
flow does not use scalar JSON

### ISSUE THREAD

**Issue by seeden** [dotansimha/graphql-code-generator#1946]
for next config
```yml
# codegen.yml
schema: 
  - http://local.mydomain.com:3000/graphql
  - ./src/graphql/client.graphql
documents: ./src/**/*.graphql
overwrite: true
scalars:
  DateTime: Date
  JSON: "{ [key: string]: any }"
generates:
  ./src/graphql/fragmentTypes.json:
    plugins:
      - fragment-matcher
  ./src/graphql/types.js:
    plugins:
      - flow
    config:
      useFlowReadOnlyTypes: true
      useFlowExactObjects: true
      scalars:
        DateTime: Date
        JSON: "{ [key: string]: any }"
```

I see 
```sh
GraphQLDocumentError: Unknown type "JSON". Did you mean "AWSJSON"?
      at ./src/graphql/mutations/createBearerTokenByFacebook.graphql:1:49
```

I tried JSON: { [key: string]: any } as well. But without any success

1. My GraphQL schema:

```graphql
mutation createBearerTokenByFacebook ($profile: JSON!, $signedRequest: String!) {
  token: createBearerTokenByFacebook(profile: $profile, signedRequest: $signedRequest) {
    type
    value
  }
}
```

**Expected behavior**
Used JSON scalar

**Environment:**

- OS: macosx
    "@graphql-codegen/cli": "^1.2.0",
    "@graphql-codegen/flow": "^1.2.0",
    "@graphql-codegen/fragment-matcher": "^1.2.0",
- NodeJS: 12.1.0
