### ISSUE TITLE
Bug with Add plugin placement

### ISSUE THREAD

**Issue by ryanditjia** [dotansimha/graphql-code-generator#1976]
**Describe the bug**
`Add` plugin’s placement config doesn’t seem to work, it generates the following file:

```ts
declare namespace GraphQL { // okay here
  append // problem: it literally types out append
} // followed by what’s inside `content`
export type Maybe<T> = T | null
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string
  String: string
  Boolean: boolean
  Int: number
  Float: number
  /** A date string, such as 2007-12-03, compliant with the ISO 8601 standard for
   * representation of dates and times using the Gregorian calendar.
   */
  Date: any
  /** The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf). */
  JSON: any
}

// rest of file
```

**To Reproduce**

1. My GraphQL schema: Gatsby
2. My GraphQL operations: Gatsby

3. My `codegen.yml` config file:

```yml
schema: http://localhost:8000/___graphql
documents: ./src/**/*.{ts,tsx}
generates:
  ./src/types/graphql.ts:
    plugins:
      - add:
          content: 'declare namespace GraphQL {'
      - add:
          placement: 'append'
          content: '}'
      - typescript
      - typescript-operations

```

**Expected behavior**
```ts
declare namespace GraphQL { // prepend
export type Maybe<T> = T | null
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string
  String: string
  Boolean: boolean
  Int: number
  Float: number
  /** A date string, such as 2007-12-03, compliant with the ISO 8601 standard for
   * representation of dates and times using the Gregorian calendar.
   */
  Date: any
  /** The `JSON` scalar type represents JSON values as specified by [ECMA-404](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf). */
  JSON: any
}

// rest of file
} // append
```

**Environment:**

- OS: macOS 10.13.6
- `@graphql-codegen/...`: 1.2.0
- NodeJS: 12.4.0, also same result with 11.15.0
