### ISSUE TITLE
near-operation-file output is messy

### ISSUE THREAD

**Issue by jrr** [dotansimha/graphql-code-generator#1984]
**Describe the bug**

Using the [near-operation-file](https://graphql-code-generator.com/docs/presets/near-operation-file) preset, I get output like this:

```
jrr@jrrmbp ~/asdf (feature/foo)> gql-gen -o
  ✔ Parse configuration
  ❯ Generate outputs
  ✔ Parse configuration
  ❯ Generate outputs
    ✔ Generate modules/client/graphql/types.gen.ts
    ❯ Generate to modules/ (using EXPERIMENTAL preset "near-operation-file")
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
  ✔ Parse configuration
  ❯ Generate outputs
    ✔ Generate modules/client/graphql/types.gen.ts
    ❯ Generate to modules/ (using EXPERIMENTAL preset "near-operation-file")
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
  ✔ Parse configuration
( ... snip ... )
  ❯ Generate outputs
    ✔ Generate modules/client/graphql/types.gen.ts
    ❯ Generate to modules/ (using EXPERIMENTAL preset "near-operation-file")
No parser and no filepath given, using 'babel' the parser now but this will throw an error in the future. Please specify a parser or a filepath so one can be inferred.
```

There are a few issues to talk about here:
1) The output that's given is redundant and not very useful. (I currently get 21 "Generate outputs" lines, and it doesn't actually mention what files are getting generated 😬)
2) Is it still "EXPERIMENTAL"? The docs didn't warn against using it, and the generated code seems fine ;)
2) The babel parser error (which goes to stderr and disappears when running `gql-gen` interactively)

Here's the relevant bit of my codegen.yml:

```yml
  modules/:
    preset: near-operation-file
    presetConfig:
      extension: .gen.ts
      baseTypesPath: client/graphql/types.gen.ts
    schema:
      - "modules/graphql-api/schema.graphql"
      - "modules/client/graphql/schema.graphql"
    documents:
      - "modules/client/graphql/*/*.graphql"
    plugins:
      - typescript-operations
      - typescript-react-apollo:
          withHOC: false
          withComponent: false
apollo#configuration
      - typescript-compatibility:
          strict: true
```

**Expected behavior**
The output fits within a page and doesn't show errors or experimental warnings.

**Environment:**

- macOS 10.14.5
- `@graphql-codegen/...`: 1.2.1 for all the packages
- NodeJS: v10.15.3

Hopefully this is enough information to expose the problems, but I can try to create a repro repo if needed.
