### ISSUE TITLE
Syntax Error: Unexpected Name "declare"

### ISSUE THREAD

**Issue by bobinrinder** [dotansimha/graphql-code-generator#1992]
**Describe the bug**
```
graphql-codegen --config codegen.yml

  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/generated/graphql.ts
      ✔ Load GraphQL schemas
      ✖ Load GraphQL documents
        → Syntax Error: Unexpected Name "declare"
        Generate
    ❯ Generate ./graphql.schema.json
      ✔ Load GraphQL schemas
      ✖ Load GraphQL documents
        → Syntax Error: Unexpected Name "declare"
        Generate


 Found 2 errors

  ✖ node_modules/graphql-toolkit/types/asyncro.d.graphql
    Syntax Error: Unexpected Name "declare"

    node_modules/graphql-toolkit/types/asyncro.d.graphql (1:1)
    1: declare module 'asyncro' {
       ^
    2:   type AsyncFn<T> = () => PromiseLike<T>;

  ✖ node_modules/graphql-toolkit/types/asyncro.d.graphql
    Syntax Error: Unexpected Name "declare"

    node_modules/graphql-toolkit/types/asyncro.d.graphql (1:1)
    1: declare module 'asyncro' {
       ^
    2:   type AsyncFn<T> = () => PromiseLike<T>;
```

**To Reproduce**

1. My GraphQL schema:
happens with any schema/service

2. My GraphQL operations:
happens with any operations

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "http://localhost:4000"
documents: "**/*.graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript-react-apollo"
  ./graphql.schema.json:
    plugins:
      - "introspection"
```

**Expected behavior**
Successful script run.

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: tried v12 and v10

**Additional context**
