### ISSUE TITLE
Send authorization token with generated service

### ISSUE THREAD

**Issue by rogerg93** [dotansimha/graphql-code-generator#2029]
Is it possible to send an authorization token with the generated services? What I would like to do is send user's authorization token with each request to the GraphQL server so that I can get back only the data which this user should see.

**Comment by dotansimha** [comment]
Hi @rogerg93 
It has nothing to do with the codegen, it's related only to the runtime library you use in your client-side (apollo/relay/url, each one has a different way of implementing auth). 

The codegen only generates types or code for you, and has nothing to do with authentication.

**Comment by frenchtoast747** [comment]
I'm trying to use my production schema in order to generate a local introspection schema for the Apollo introspection fragment matcher, but the graphql endpoint is protected by authentication. How can I send my authentication token, in a header, along with the generate command?

**Comment by ardatan** [comment]
You can generate it using a script, then set it as an environmental variable. Then use this env variable to send to codegen as an  `Authorization` header.
Or you can use codegen programatically to generate a token
https://graphql-code-generator.com/docs/getting-started/schema-field#url

**Comment by anup-a** [comment]
Simple Example -

`codegen.yml`
```
schema:
  - http://localhost:3000/graphql:
      headers:
        Authorization: YOUR-TOKEN-HERE
```

**Comment by rmlevangelio** [comment]
The problem with this approach is you are adding your token inside the codebase and it's not ideal to put secrets in code. Is there a way to get the token from the app itself and use as variable here?

**Comment by ma-jahn** [comment]
@rmlevangelio 

you should be able to access env variables within your codegen.yml.

so sth like the following should help you out:

`codegen.yml`
```
schema:
  - http://localhost:3000/graphql:
      headers:
        Authorization: "Bearer: ${API_TOKEN}"
```

```
API_TOKEN="YOUR_ACTUAL_TOKEN" yarn graphql-codegen --config codegen.yml
```


With this setup you can embed certain processes to actually create a token or use your CI Variables.

**Comment by rmlevangelio** [comment]
All good, this works. Thank you @ma-jahn

**Comment by heinrichdude** [comment]
For me the Authorization portion of the YAML needed to be as follows ...

Authorization: "Bearer ${TOKEN}"

... as in NO colon after Bearer.

**Comment by dotansimha** [comment]
> For me the Authorization portion of the YAML needed to be as follows ...
> 
> Authorization: "Bearer ${TOKEN}"
> 
> ... as in NO colon after Bearer.

So just do: 

```
schema:
  - http://localhost:3000/graphql:
      headers:
        Authorization: "Bearer ${API_TOKEN}"
```

?
