### ISSUE TITLE
typescript-resolvers: maximum call stack size exceeded

### ISSUE THREAD

**Issue by yoavain-sundaysky** [dotansimha/graphql-code-generator#2030]
**Describe the bug**
typescript-resolvers is getting "maximum call stack size exceeded" error when there are 2 types pointing at each other.

Example:
```graphql
type Account {
	id: ID!
	name: String!
	programs: [Program!]!
}

type Program {
	id: ID!
	name: String!
	account: Account!
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema:
  - ./src/graphql/**/*.graphql
generates:
  ./generated/graphqlGeneratedTypes/graphqlServer.ts:
    config:
      typesPrefix: "Gql"
      defaultMapper: Partial<{T}>
      namingConvention:
        typeNames: change-case#pascalCase
        enumValues: change-case#upperCase
    plugins:
      - typescript
      - typescript-resolvers
```

- OS: Windwos
- `@graphql-codegen/1.3.0`
- NodeJS: 10.x

Worked with 1.2.1
