### ISSUE TITLE
Union is broken by declarationKind: 'interface'

### ISSUE THREAD

**Issue by leethree** [dotansimha/graphql-code-generator#2034]
**Describe the bug**
 
GraphQL Union will become broken code when generating Typescript types.

**To Reproduce**

1. My GraphQL schema:

```graphql
type SpeechTranscriptionData {
}

type SpeechWordScoreData {
}

union ConfidenceData = SpeechTranscriptionData | SpeechWordScoreData
```

3. My `codegen.yml` config file:

```yml
plugins:
      - "typescript"
    config:
      declarationKind: 'interface'
```

**Expected behavior**

The generated type should not have syntax error.

**Actual behavior**

Syntax error:

```ts
export interface ConfidenceData SpeechTranscriptionData | SpeechWordScoreData
```

**Environment:**

- OS: macOS
- `@graphql-codegen/...`: v1.3.0
- NodeJS: v10.15.0

**Additional context**

See #1923

**Comment by dotansimha** [comment]
You are right, @leethree , you can workaround that at the moment with the following:

```
    config:
      declarationKind:
         scalar: interface 
         input: interface 
         type: interface 
         arguments: interface 
         interface: interface 
         union: type 
```

I think we can't really use `interface` to `union` because we cant put `|` in TypeScript interfaces, so we must use `type` aliases. @benquarmby what do you think?
