### ISSUE TITLE
Unable to find template plugin matching typescript-operations

### ISSUE THREAD

**Issue by warrendodsworth** [dotansimha/graphql-code-generator#2043]
**Describe the bug**
New Angular Cli project
Run npm init
run 
standard install 

**To Reproduce**

1. My GraphQL schema:
- too big 

2. My GraphQL operations:

```graphql
graphql-codegen init
graphql-codegen --config codegen.yml
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "http://apollot:8972/samples/graphql/service"
documents: "src/**/*.graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-apollo-angular"
      - "typescript-graphql-files-modules"

```

**Expected behavior**
Standard generate result

**Environment:**
    "@graphql-codegen/typescript": "1.3.0",
    "@graphql-codegen/typescript-apollo-angular": "1.3.0",
    "@graphql-codegen/typescript-graphql-files-modules": "1.3.0",
    "@graphql-codegen/typescript-operations": "1.3.0",

Global cli package @graphql-codegen/cli 1.3.0

- OS: Windows 10
- `@graphql-codegen/...`: 
- NodeJS: 8.9.3 

**Additional context**

![image](https://user-images.githubusercontent.com/1066996/59898622-fc15ad00-9434-11e9-9efd-f61b8d994b47.png)

**Comment by dotansimha** [comment]
Hi @warrendodsworth ! 
Are you sure all dependencies are installed correctly? Did you ran `yarn` or `npm install` after adding the plugins to `package.json`? 
Can you please try to create a small reproduction in a repository?

**Comment by warrendodsworth** [comment]
Hi @dotansimha,
Thanks for getting back to me so quickly mate
Yes, I did run **npm i** after adding the plugins using **graphql-codegen init**

I've created a small repo to reproduce the issue
https://github.com/warrendodsworth/web-graphql-codegen-reproduce-bug

**Comment by dotansimha** [comment]
Hi @warrendodsworth , I noticed the following in your repo:
- Missing dependency `@graphql-codegen/cli`.
- `typescript-graphql-files-modules` requires extensions `d.ts` so I recommend using it separately.
- `fragment-matcher` is better used in a separate file.

You config should look like that:
```yml
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-apollo-angular"

  src/generated/modules.d.ts:
    plugins:
      - typescript-graphql-files-modules
      
  src/generated/fragment-matcher.json:
    plugins:
      - "fragment-matcher"
```

I couldn't reproduce your issue with the reproduction repo. Tried with Node 10 and NPM (tried to install dependencies using `yarn install` and `npm install`) - it worked for me.

**Comment by capaj** [comment]
I got the same error just now. Installed this: 
![image](https://user-images.githubusercontent.com/1305378/62761830-f37e4200-ba87-11e9-9c42-21d03fc75660.png)

and my yaml looks like:
```yml
overwrite: true
schema: 'gqlSchemas/private.graphql'

generates:
  front-end/src/generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
```
