### ISSUE TITLE
[Question]Avoid having to use no non null assertion everywhere with Gatsby

### ISSUE THREAD

**Issue by abumalick** [dotansimha/graphql-code-generator#2051]
It is my first time using graphql-codegen in a project, thank you very much for providing this tool.

I am working on a starter for Gatsby with typescript, and I am using graphql-codegen to generate the types for gatsby's graphql server.

It works well but all the fields are of type `Maybe<T>`, I am not sure why, the data is there in the API and is not null.

So in my code I have to add a lot of *non null assertion* like this:
```js
  const {
    canonicalUrl,
    companyName,
    siteTitle,
  } = layoutQuery.site!.siteMetadata!
  return (
    <>
      <Header siteTitle={siteTitle!} />
      <main>{children}</main>
      <footer>
        © {new Date().getFullYear()} Copyright{' '}
        <a href={canonicalUrl!}>{companyName}</a> - All rights reserved
```

I feel it is a dirty way to handle this problem and I wonder if you have an advice for improving my code.

**Describe the solution you'd like**

A solution that feels right.

**Describe alternatives you've considered**

I tried to make the checks manually like this:
```js
const siteMetadata = layoutQuery.site && layoutQuery.site.siteMetadata
  const companyName = siteMetadata ? siteMetadata.companyName : ''
  const canonicalUrl = siteMetadata ? siteMetadata.canonicalUrl : ''
  const siteTitle = siteMetadata ? siteMetadata.siteTitle : ''
  return (
    <>
      <Header siteTitle={siteTitle || ''} />
      <main>{children}</main>
      <footer>
        © {new Date().getFullYear()} Copyright{' '}
        <a href={canonicalUrl || ''}>{companyName || ''}</a> - All rights
        reserved
      </footer>
    </>
  )
```

But I feel it is **very** verbose. 

**Additional context**

Here is a link to this code in the repository:
https://github.com/abumalick/gatsby-typescript-material-rebass-starter/blob/master/src/components/Layout.tsx#L23-L34

And here is the generated types:
https://github.com/abumalick/gatsby-typescript-material-rebass-starter/blob/master/src/types/gatsbyGraphql.ts#L2162

My config:
```yml
overwrite: true
schema: 'http://localhost:8000/___graphql'
documents:
  - ./src/**/*.{ts,tsx}
  - ./node_modules/gatsby-*/**/*.js
generates:
  src/types/gatsbyGraphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
    config:
      avoidOptionals: true

```
