### ISSUE TITLE
external enumValues with typesPrefix won't work together

### ISSUE THREAD

**Issue by veeramarni** [dotansimha/graphql-code-generator#2082]
**Describe the bug**
 

If we have `typesPrefix` set to some value and `enumValues` point to a file then `import` value in the generated output won't have required type prefix and hence type validation fails.

**To Reproduce**

1. My GraphQL schema:

```graphql

```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
# Put your schema here
.....
    config:
        enumValues:
          MyEnum: ./files#MyEnum
        typesPrefix: I
...
```

Generated Output

```
import { MyEnum } from "./files";
export type IResolversTypes = {
....
MyEnum: IMyEnum
}
```

**Expected behavior**

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**
