### ISSUE TITLE
Support for Apollo Federation directives

### ISSUE THREAD

**Issue by jsangilve** [dotansimha/graphql-code-generator#2086]
Is there any way to generate types for a schema using Apollo Federation directives? `@key`, `@external`, etc?

I tried to generate them but it doesn't seem to work:

For example:

```graphql
extend type User @key(fields: "id") {
  id: ID! @external
}

type UserRole {
  type: UserType!
  user: Driver 
}
```

```bash
Error: Cannot extend type "User" because it is not defined. Did you mean "UserRole"?
    Unknown directive "key".
    Unknown directive "external".
    Unknown type "User". Did you mean "UserRole"?
```

**Environment:**

- OS: 
- `@graphql-codegen/...`: 1.3.1
- NodeJS: 10.15

**Comment by dotansimha** [comment]
Hi @jsangilve ! 
How do you load your schema? Can you please share you `codegen.yml`?
I think Apollo Federation is using the directives only during it's build process, and strip it while serving the schema.

You can add a file with all the directives (`federation-directives.graphql`):

```graphql
directive @external on FIELD_DEFINITION
directive @requires(fields: _FieldSet!) on FIELD_DEFINITION
directive @provides(fields: _FieldSet!) on FIELD_DEFINITION
directive @key(fields: _FieldSet!) on OBJECT | INTERFACE
directive @extends on OBJECT
```

Then, load it as part of your schema:

```yml
schema: 
  - http://remote-schema/graphql
  - federation-directives.graphql
```

**Comment by jsangilve** [comment]
Thanks for your reply @dotansimha. Will try asap

**Comment by dotansimha** [comment]
@jsangilve any update? :)

**Comment by jsangilve** [comment]
Hi @dotansimha! 

Sorry for the late reply.

I tried your suggestion and the errors for `@key` and `@external` directives are gone, but we still have trouble with the types and plus `_FieldSet` param (as declared within the directives).

```
Error: Cannot extend type "User" because it is not defined. Did you mean "UserRole"?
    Unknown type "User". Did you mean "UserRole"?
    Unknown type "_FieldSet".
    Unknown type "_FieldSet".
    Unknown type "_FieldSet".
```

```yaml
# codegen.yml
schema: 
  - resources/api.graphql
  - resources/federation-directives.graphql
overwrite: true
generates:
  src/api/types.ts:
    config:
      contextType: ./getContext#ApiContext
      namingConvention:
        enumValues: change-case#upperCase
    plugins:
      - add: "/* tslint:disable */"
      - time
      - typescript-resolvers
```
