### ISSUE TITLE
Gatsbyjs with Apollo

### ISSUE THREAD

**Issue by endigo** [dotansimha/graphql-code-generator#2092]
There are 2 types of queries, mutations, and subscription.

How to generate types not depending on each other.

```yml
overwrite: true
generates:
 # for Gatsby.js
  src/generated/graphqlTypes.ts:
    schema: http://localhost:8000/__graphql
    documents:
      - ./src/**/*.{ts,tsx}
      - ./node_modules/gatsby-*/**/*.js
    plugins:
      - "typescript"
    config:
      gqlImport: gatsby#graphql
   # for react-apollo
  src/generated/types.ts:
    schema:
      - http://graphql.example.com/graphql:
    documents: ./src/**/*.{ts,tsx}
    plugins:
      - "typescript"
      - "typescript-operations"

```
```js
// gatsby-config.js
{
      resolve: "gatsby-source-graphql",
      options: {
        typeName: "hasura",
        fieldName: "hasura",
        createLink: () => {
          return createHttpLink({
            uri: process.env.GATSBY_BACKEND_ENDPOINT + "/v1/graphql",
          });
        }
      }
    },
```

```ts
// apollo mutation
const mutation = gql`
  mutation CREATE_ORGANIZATION_REQUEST($data: organizations_insert_input!) {
    insert_organizations(objects: [$data]) {
      returning {
        id
        name
      }
    }
  }
`;
```
Error is
``` bash
GraphQLDocumentError: Unknown type "organizations_insert_input". Did you m
ean "hasura_organizations_insert_input", "hasura_files_insert_input", "hasura_orga
nizations_set_input", "hasura_authors_insert_input", or "hasura_roles_insert_input
"?
```
```

**Comment by dotansimha** [comment]
Hi @endigo 
Are you sure your schema contains the `input organizations_insert_input`? It seems like it doesn't getting loaded from your schema. Can you find it in GraphiQL/Playground docs?

**Comment by endigo** [comment]
Sure, my schema contains the input.

I used ```gatsby-source-graphql``` with gatsby config.
And I use ```apollo-graphql``` with clientside. So 2 different access to my graphql endpoint.

Queries, mutations are 2 different rootType.
```ts
// with-gatsby
query {
  hasura {
    products {
....
```

```ts
// with-apollo
// there is no hasura type
query {
  products {
....
```

**Comment by dotansimha** [comment]
I understand, but note that the Codegen only loads the schema you provide, and then run `validate` (or `graphql`) with your documents. It means that there is a document in your code that uses types that does not exists in your schema. 
Can you please create a repo/sandbox with reproduction?

**Comment by endigo** [comment]
Here is the repo
```
https://github.com/endigo/gatsby-apollo-demo
```

**Comment by dotansimha** [comment]
@endigo I think your client side is doing some transformations and manipulations to your documents, and create a different query in runtime. 
I tried to run your example locally, and I opened `/__graphql` and searched for this input type: `organizations_insert_input` - it does not exists. 
The codegen only consumes the final GraphQL schema, and your operations as you provide them. If your client consumer code does manipulations to the query before running it - it might not work with the codegen. 

I even tried to run your exact operation, and got the same error as the codegen:

![image](https://user-images.githubusercontent.com/3680083/60753598-9e10ca00-9fdd-11e9-895b-5f950283a4dd.png)

**Comment by endigo** [comment]
Yes, there is no ```organizations_insert_input``` type because that's a demo. You should find ```products_insert_input```.

**Comment by endigo** [comment]
I need to generate type for hasura and apollo.

There is 2 endpoint.
```https://gatsby-apollo-demo.herokuapp.com/v1/graphql```
```http://localhost:8000/___graphql```

**Comment by endigo** [comment]
```graphql``` is imported from ```gatsby```

```gql``` is imported from ```graphql-tag```

**Comment by endigo** [comment]
You can access hasura console with this address
https://gatsby-apollo-demo.herokuapp.com/console

**Comment by dotansimha** [comment]
Ok, so you have 2 different schemas that doesn't have anything to do with each other? And you want to merge them before or not? 
Do you consume them as 2 separate endpoints, or as one? 
I'm not really sure, but it seems like you are mixing a few things here.
If you wish to have 2 output files, that are not depending on each other, just specify `schema` and `documents` in each one of them.

The codegen can't separate the files found with `./src/**/*.{ts,tsx}`. You tried to specify the same glob so it collects all documents.
You should tell the codegen which documents belong to which endpoint schema.

```yml
  src/generated/graphqlTypes.ts:
    schema: http://localhost:8000/__graphql
    documents:
      - ./src/gatsby-operations/**/*.{ts,tsx}
      - ./node_modules/gatsby-*/**/*.js
    plugins:
      - "typescript"
    config:
      gqlImport: gatsby#graphql
   # for react-apollo
  src/generated/types.ts:
    schema:
      - http://graphql.example.com/graphql:
    documents: ./src/hasura-operations/**/*.{ts,tsx}
    plugins:
      - "typescript"
      - "typescript-operations"
```
