### ISSUE TITLE
[graphql-tag-pluck] `No file specified: unexpected token` when using JSX in `.js` files

### ISSUE THREAD

**Issue by vonwao** [dotansimha/graphql-code-generator#2093]
**Describe the bug**

  √ Parse configuration
  > Generate outputs
    > Generate ./packages/graphql/types.tsx
      √ Load GraphQL schemas
      × Load GraphQL documents
        → Unexpected token (7:31)
        Generate

 Found 1 error

  × ./packages/graphql/types.tsx
    SyntaxError: Unexpected token (7:31)

1. My GraphQL schema:

N/A, this is happening in parsing documents

2. My GraphQL operations:

I have a bunch in different files

3. My `codegen.yml` config file:

```yml
schema: ../stream_graphql/packages/*/*.graphql
documents:
  - ./packages/*/*.js
overwrite: true
generates:
  ./packages/graphql/types.tsx:
    plugins:
      - add: '/* eslint-disable */'
      - typescript
      - typescript-operations
      - typescript-react-apollo
    # The combined options of all provided plug-ins
    # More information about the options below:
    # graphql-code-generator.com/docs/plugins/typescript-react-apollo#configuration
    config:
      withHOC: false
      withHooks: true
      withComponent: false
```

**Expected behavior**
expecting to see a filename of where the unexpected token was.

**Comment by vonwao** [comment]
I figured out that the errors I was getting was because my files were named .js instead of .jsx.  Is that expected?  Is there a way to treat all files as JSX so I don't have to rename all my files?  Thanks.

**Comment by dotansimha** [comment]
@vonwao which version of the codegen do you use? 
It was an issue with `graphql-tag-pluck`, but I think we already solved it.

**Comment by jedmao** [comment]
@dotansimha I'm having the exact same error with the following versions:
```json
    "@graphql-codegen/cli": "^1.4.0",
    "@graphql-codegen/introspection": "^1.4.0",
    "@graphql-codegen/typescript": "^1.4.0",
    "@graphql-codegen/typescript-graphql-files-modules": "^1.4.0",
    "@graphql-codegen/typescript-operations": "^1.4.0",
    "@graphql-codegen/typescript-resolvers": "^1.4.0",
    "graphql": "^14.4.2",
    "graphql-tag-pluck": "^0.8.3",
```
And my `codegen.yml` file (which worked before) is as follows:
```yml
overwrite: true
schema: 'server/src/schemas/**/*.gql'
documents: 'src/**/*.{ts,tsx}'
generates:
  src/models/generated.tsx:
    - typescript
    - typescript-operations
  server/models.ts:
    - typescript
    - typescript-resolvers
pluckConfig:
  modules:
    - name: 'babel-plugin-relay/macro'
      identifier: 'graphql'
```
