### ISSUE TITLE
Slow performance with large schemas

### ISSUE THREAD

**Issue by mxstbr** [dotansimha/graphql-code-generator#2105]
**Describe the bug**

When generating code from large GraphQL schemas, running graphql codegen takes > 25s, which is way too slow.

**To Reproduce**

Generate schema types and some queries from the official GitHub GraphQL API, which is _very_ large:

```YAML
overwrite: true
schema:
  - http://api.github.com/graphql:
      headers:
        Authorization: Bearer ${GITHUB_PERSONAL_ACCESS_TOKEN}
documents: "src/**/*.graphql"
generates:
  src/graphql-schema-types.generated.ts:
    plugins:
      - typescript
    config:
      immutableTypes: false
  src/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: "graphql-schema-types.generated.ts"
      extension: ".generated.tsx"
    plugins:
      - add: |
          // eslint-disable
          // ⚠️ DO NOT EDIT ⚠️
          // This file is automatically generated, run yarn run graphql:codegen to update
      - "typescript-operations"
      - "typescript-urql"
    config:
      immutableTypes: false
      withComponent: false
      withHooks: true
  web/src/graphql-types.generated.d.ts:
      plugins:
      - add: |
          // eslint-disable
          // ⚠️ DO NOT EDIT ⚠️
          // This file is automatically generated, run yarn run graphql:codegen to update
      - "typescript-graphql-files-modules"
```

You are going to need to get a GitHub personal access token from your settings and insert . that where it says `${GITHUB_PERSONAL_ACCESS_TOKEN}`. A potential example query could be something like

```GraphQL
{
  viewer {
    id
  }
}
```

**Expected behavior**

Graphql codegen's performance should be related to how many queries/mutations/subscriptions it needs to generate code for, not how large the input schema is.
