### ISSUE TITLE
skip parameter not taking expression for boolean

### ISSUE THREAD

**Issue by wangsongiam** [dotansimha/graphql-code-generator#2145]
**Describe the bug**
 

When using version `1.3.1` with `withHooks`, the input type for render props query component is not taking `boolean` type for `skip` param type, instead, I see `{ variables: {...}; skip?: false } | { skip: true }`. So skip can only be set with `true` or `false`. 

This will break common expression like `!undefined` or `!a && b`. 

eg.
```
<Get_FooComponent variables={{...}} skip={!a && !b}>
```

**To Reproduce**

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
# Put your YML here
generates:
  src/_generated/graphql.tsx:
    documents:
      - src/components/**/*.{ts,tsx}
      - src/queries/**/*.{ts,tsx}
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withHooks: true

```

**Expected behavior**

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**
