### ISSUE TITLE
singleFile option for EnumValues

### ISSUE THREAD

**Issue by veeramarni** [dotansimha/graphql-code-generator#2164]
**Describe the bug**
 
When using `singleFile` options for Enum Values, we get below generated `enums`.

Also, document missing about this topic #2038 . 
```
import { __TypeKind } from "./enum";
import { __DirectiveLocation } from "./enum";
```
*To Reproduce**

3. My `codegen.yml` config file:

```yml
# Put your YML here
  packages/sample-client-state/src/interfaces/generated-models.ts:
    documents: "packages/sample-client-state/src/**/*.gql"
    schema: 
      - ./packages/sample-client-state/src/**/*.graphql
    config:
      enumValues: ./enum
      constEnums: true
```

**Expected behavior**

Should not generate them as they are not defined by the user.

**Environment:**

- `@graphql-codegen/...`:  1.4.0

**Additional context**
