### ISSUE TITLE
Gatsby Queries Types

### ISSUE THREAD

**Issue by altano** [dotansimha/graphql-code-generator#2170]
This is less of a bug report and more of a question: I'm writing GatsbyJS components that look like this:

```js
export default (response) => {
  const product = response.data.productsJson
  return (...)
}

export const query = graphql`
  query MyQuery {
    ...
  }
`
```

Is there a graphql-code-generator plugin that will let me type the `response` object in my component? I have a codegen.yml that looks like:

```yml
overwrite: true
schema: http://localhost:8000/__graphiql
generates:
  types/generated/graphql/types.tsx:
    documents:
      - ./src/**/*.{ts,tsx}
      - ./node_modules/gatsby-*/**/*.js
    config:
      gqlImport: gatsby#graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
  types/generated/graphql/graphql.d.ts:
    documents:
      - ./src/**/*.graphql
    plugins:
      - typescript-graphql-files-modules
```

And it's generating all sorts of types successfully, including Apollo ones, but I don't see any types that come close to just describing the response data.
