### ISSUE TITLE
[TypeScript Resolvers] feat: Generate Interface types without field resolvers

### ISSUE THREAD

**Issue by rynobax** [dotansimha/graphql-code-generator#2194]
**Is your feature request related to a problem? Please describe.**
When attempting to generate types for an existing graphql server, I am having trouble getting the generated types for interfaces to match my implementation.

On my server I only specify a `__resolveType` resolver for my interface type, and let the implementing types provide the revolvers for the shared fields.  However, when I generate types, the interface type requires that a resolver for all fields be provided.

<details>
<summary>Example</summary>

```graphql
interface Animal {
  color: String!
}

type Dog implements Animal {
  color: String!
  bark: String!
}

type Cat implements Animal {
  color: String!
  meow: String!
}
```

```ts
const resolvers: Resolvers = {
  Cat: {
    color: e => e.color,
    meow: e => e.noise,
  },
  Dog: {
    color: e => e.color,
    bark: e => e.noise,
  },
  Animal: {
    __resolveType: e => (e.dog ? "Dog" : "Cat")
    // Property 'color' is missing in type '{ __resolveType: () => "Cat"; }' but required in type 'AnimalResolvers<any, Animal>'
  },
```

</details>

**Describe the solution you'd like**

I would like to specify in my configuration that I would like interface resolver types to only require a `__resolveType` field.

I would be happy to work on adding the functionality if I could get some confirmation this is a feature worth adding, and not just me doing something wrong 😄 .

**Comment by kamilkisiela** [comment]
I reproduced what you have within a test-case: https://github.com/dotansimha/graphql-code-generator/commit/08ded8010e575890055a08925e5ecff0882a8caa

Could you tell me how your `codegen.yml` looks like?

**Comment by dotansimha** [comment]
As @kamilkisiela said, the generated signature doesn't force you to implement the resolvers for the interface's fields.

**Comment by rynobax** [comment]
Full codegen.yml:

```
schema: src/graphql/schema.graphql
generates:
  ./src/types/graphql.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      rootValueType: undefined
      contextType: ~/graphql/context#Context
      maybeValue: T | null | undefined
      avoidOptionals: true
      showUnusedMappers: true
      noSchemaStitching: true
      skipTypename: true
      enumsAsTypes: true
      namingConvention:
        enumValues: keep
      mappers:
        // Lots of mappers
```

I'm guessing it's due to `avoidOptionals`?

I can take a look tonight and update the test to match what I want.

**Comment by dotansimha** [comment]
@rynobax yeah the `avoidOptionals` is causing it, you can remove it for the `typescript-resolver` plugin. If you need to for `typescript` plugin only, you can do: 

```
schema: src/graphql/schema.graphql
generates:
  ./src/types/graphql.ts:
    plugins:
      - typescript:
		avoidOptionals: true
      - typescript-resolvers
    config:
      rootValueType: undefined
      contextType: ~/graphql/context#Context
      maybeValue: T | null | undefined
      showUnusedMappers: true
      noSchemaStitching: true
      skipTypename: true
      enumsAsTypes: true
      namingConvention:
        enumValues: keep
      mappers:
        // Lots of mappers
```
