### ISSUE TITLE
typescript-mongodb outputs raw `ID` types from `additionalFields`

### ISSUE THREAD

**Issue by smeijer** [dotansimha/graphql-code-generator#2217]
**Describe the bug**
When adding `additionalFields` with `typescript-mongodb`, the `field type` is resolved as `${type}` instead of the expected `Scalars[${type}]`

**To Reproduce**

https://codesandbox.io/s/2bd6r

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User @entity(
    additionalFields: [
        { path: "userId", type: ID },
    ]
) {
    id: ID! @column
    username: String! @column
    email: String!
}
```

2. My GraphQL operations:

*irrelevant*

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-mongodb
    config:
      dbTypeSuffix: Entity
      dbInterfaceSuffix: Entity
      objectIdType: string
```

**Expected behavior**
I expect the generated `userId` field to have a type `Scalars[ID]` and not just the undefined `ID` type. Or in this specific case even `string`, as `objectIdType` is set to `string`, but that's open for debate.

The real output is:

```graphql
export type User = {
  __typename?: "User";
  id: Scalars["ID"];
  username: Scalars["String"];
  email: Scalars["String"];
};

export type UserEntity = {
  id: string;
  username: string;
  userId: ID;
};
```

Expected:
```graphql
export type UserEntity = {
  id: string;
  username: string;
  userId: IDScalars["ID"]
};
```

or

```graphql
export type UserEntity = {
  id: string;
  username: string;
  userId: string;
};
```

**Environment:**

```
- OS: CodeSandbox
- NodeJS: v10.16.0
- @graphql-codegen/add: 1.3.1
- @graphql-codegen/cli: 1.3.1
- @graphql-codegen/typescript: 1.3.1
- @graphql-codegen/typescript-mongodb: 1.4.0
- @graphql-codegen/typescript-operations: 1.3.1
- @graphql-codegen/typescript-react-apollo: 1.4.0
- graphql: 14.3.1
```
