### ISSUE TITLE
Can't override ResolverTypeWrapper with mappers

### ISSUE THREAD

**Issue by ellipticaldoor** [dotansimha/graphql-code-generator#2236]
**Describe the bug**
 I want to override ResolverTypeWrapper.

By default looks like this:
``` typescript
export type ResolverTypeWrapper<T> = Promise<T> | T;
```

But I want it like this:
``` typescript
export type ResolverTypeWrapper<T> = Promise<DeepPartial<T>> | DeepPartial<T>;
```

**To Reproduce**
If you try this on the **codegen.yml** to override ResolverTypeWrapper it will not work

``` yaml
generates:
  src/generated/apollo/index.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
    config:
      mappers:
        ResolverTypeWrapper: Promise<DeepPartial<T>> | DeepPartial<T>
```

I am doing something wrong?
