### ISSUE TITLE
Duplicated types in monorepository with multiple servers sharing types

### ISSUE THREAD

**Issue by SoyYoRafa** [dotansimha/graphql-code-generator#2241]
**Is your feature request related to a problem? Please describe.**

Hi,
We have a monorepository with multiple graphql servers and their respective client libraries. Additionally, some basic types, inputs, and enums need to be shared between servers. Currently, we are forced to generate duplicate typings in servers with graphql codegen because each generated file contains all of the types. It gets more tricky when one server is a client of a different server and they share a type/enum. Additionally, each file generated contains a `Scalars` type causes a lot of conflicts so we have to manually reexport types. To be more clear, take the following graphql files as an example:

sharedTypes.graphql
serverAqueries.graphql
serverBqueries.graphql
clientAdocuments.graphql
clientBdocuments.graphql

where sharedTypes.graphql contains types that are used in all files serverAqueries.graphql, serverBqueries.graphql, clientAdocuments.graphql, clientBdocuments.graphql.

**Describe the solution you'd like**
If graphql codegen creates one generated file per unique graphql file and generate the respective imports in TypeScript, then duplicate types would be eliminated. With the output above, graphql codgen would generate:

scalars.ts
sharedTypes.ts
serverAqueries.ts
serverBqueries.ts
clientAdocuments.ts
clientBdocuments.ts

**Describe alternatives you've considered**

**Comment by dotansimha** [comment]
Hi @SoyYoRafa 
You didn't include your codegen version, codegen config and your schemas or documents.
First, let's separate the `.graphql` files to 2 types: schema files and documents files. They shouldn't get mixed up. schema files should be loaded in `schema:` field in your config file, and operations files should be loaded in `documents:` section. 
The codegen generates a single file every time (excluding `near-operation-file` preset). It means that it doesn't matter how many schema files or schemas in general you have - you'll get only a single file. If you wish to have type per repository inside your monorepo, you need to specify multiple outputs and have a schema and document per each output:

```yml
generates:
   packages/A/output.ts:
     schema: packages/A/**/*.graphql
     plugins:
        - typescript
   packages/B/output.ts:
     schema: packages/B/**/*.graphql
     plugins:
        - typescript
   packages/client/output.tsx: # client might need all schemas loaded, so we load it from A and B
     schema:
        - packages/A/**/*.graphql
        - packages/B/**/*.graphql
     documents: packages/client/**/*.graphql
     plugins:
        - typescript
        - typescript-operations
```

Other than that, we have `near-operation-file` that can generate output per each operation file, but I don't think that's the case here.

**Comment by SoyYoRafa** [comment]
Hi,
We are on version 1.4.0. I cannot share the schema or configuration due to various constraints. I am going to try to explain the challenge a bit differently. If this doesn't convey the issue clearly, I will create a new simple project that illustrates the issue but it may take me a couple of days.

Imagine you have a server A and server B, both of which have two different GraphQL schemas but the schemas share `enum X` and `type Y`. Now, please consider the following two scenarios:

1. Server A is a client of server B. This means that the schema of server A generates TypeScript file containing `enum X` and `Scalars`. The document querying server B also generates a TypeScript file containing `enum X` and `Scalars`. When we try to re-export the types, we have collisions on enum X and Scalars.

2. Server A and Server B need to share a library C. Library C uses the TypeScript interface for `type Y`. Schemas for server A and server B each generate an interface for `type Y`. When we try to re-export the types, there is a collision on `type Y` and `Scalars`. Additionally, which duplicate interface should library C use?

In order to avoid this collisions and ambiguity, we need a way to only generate one `enum X`, `type Y` interface, and `Scalars` type across all the schemas and documents in one codegen.yml

**Comment by dotansimha** [comment]
@SoyYoRafa 
The codegen basically generates a single file from a single schema. If you have multiple schemas, it will merge it into one schema. If you have two schemas with `enum X` - the codegen will merge it and there will be only one `enum` generated .

I think I need a reproduction of the issue in a repo...

**Comment by SoyYoRafa** [comment]
Are you saying we should use a single output file for every server schema and every document in the repository? That is an idea I hadn't considered. The only quirk there is that `type Query`, `type Mutation` and `type Subscription` shouldn't be merged but I don't think the interfaces for these three are used.

```
generates:
   src/types.ts
     schema:
        - schemas/A/**/*.graphql
        - schemas/B/**/*.graphql
        - schemas/shared/**/*.graphql
     documents: documents/**/*.graphql
     plugins:
        - typescript
        - typescript-operations
```

**Comment by dotansimha** [comment]
No exactly, I'm saying you can have a different file per each schema, and a merged schemas for the operations (because it might need the entire schema to operate). 
But if a single file works for you - why not using it as well? the codegen knows how to merge any type of schemas into one.

And why the root type shouldn't be merged?

**Comment by SoyYoRafa** [comment]
Server A and Server B have different schemas and each serve different queries. They simply share some basic types and enums. There cannot be duplicates for `enum X`, they internally share libraries using `enum X`

#### Server A
```
type Query {
  get: MyData
}
enum X { 
 .. 
}
type MyData {
  type: X!
}
```

#### Server B
```
type Query {
  compute(type: X!, arg: Float!): Float!
}
enum X { 
 .. 
}
```

The merged root query is the one below. However, server A nor server B should have the interface for this because they simply don't service the merged schema.

```
type Query {
  get: MyData
  compute(type: X!, arg: Float!): Float!
}
```

**Comment by dotansimha** [comment]
I see. so you have 2 servers and a shared package with common schema, right?

First, make sure that your codegen is installed and used from the root directory of the monorepo.

You can do the following to generate basic types per each server: (if you wish, you can also use `typescript-resolver` for resolvers signature) 

```yml
generates:
   packages/A/types.ts # Types for server A
     schema:
       - packages/shared/**/*.graphql
       - packages/A/**/*.graphql
     plugins:
        - typescript
   packages/B/types.ts # Types for server B
     schema:
       - packages/shared/**/*.graphql
       - packages/B/**/*.graphql
     plugins:
        - typescript
```

If server B consumes server A and have queries for it, you can generate another output file, that consumes server A schema and uses the operations declared in server B:

```
   packages/B/operations.ts
     schema:
       - packages/shared/**/*.graphql
       - packages/A/**/*.graphql
     operations: packages/B/operations/**/*.graphql
     plugins:
        - typescript
        - typescript-operations
```

If you have a client-side (i used react in this example) that consumes the complete schema (of both servers) from a single endpoint, you can generate types for it using the entire merged schema:

```
   packages/client/types.tsx
     schema:
       - packages/shared/**/*.graphql
       - packages/A/**/*.graphql
       - packages/B/**/*.graphql
     operations: packages/client/**/*.tsx
     plugins:
        - typescript
        - typescript-operations
        - typescript-react-apollo
```

Does this helps? or I'm still missing something?
