### ISSUE TITLE
Bumping graphql-typescript-codegen-resolvers from 0.14.5 to 0.18.2 by dependabot `Maybe` type not found

### ISSUE THREAD

**Issue by dmi3y** [dotansimha/graphql-code-generator#2247]
**Describe the bug**
After upgrading to 0.18.2 and regenerating types I see bunch of errors about missing Maybe type:

```
typings/types.d.ts:3966:33 - error TS2304: Cannot find name 'Maybe'.

3966     bayIndex?: BayIndexResolver<Maybe<number>, TypeParent, TContext>;
                                     ~~~~~

typings/types.d.ts:3968:41 - error TS2304: Cannot find name 'Maybe'.

3968     serialNumber?: SerialNumberResolver<Maybe<string>, TypeParent, TContext>;
                                             ~~~~~

typings/types.d.ts:3972:9 - error TS2304: Cannot find name 'Maybe'.

3972     R = Maybe<number>,
             ~~~~~

typings/types.d.ts:3977:9 - error TS2304: Cannot find name 'Maybe'.

3977     R = Maybe<boolean>,
             ~~~~~

typings/types.d.ts:3982:9 - error TS2304: Cannot find name 'Maybe'.

3982     R = Maybe<number>,
             ~~~~~

typings/types.d.ts:3987:9 - error TS2304: Cannot find name 'Maybe'.

3987     R = Maybe<string>,
             ~~~~~


Found 554 errors.
```

3. My `codegen.yml` config file:

```yml
schema:
  - http://localhost:8090/graphql
overwrite: true
config:
  contextType: ./context#IResolversContext
  mappers:
    FlightCommand: ./models/flightCommand#IFlightCommandParent
    User: ./models/user#IUserParent
    Vehicle: ./models/vehicle#IVehicleParent
    VehicleStatusMessage: ./models/vehicleStatusMessage#IVehicleStatusMessageParent
generates:
  ./typings/types.d.ts:
    plugins:
      - add: |
          /**
          * ¡THIS IS AN AUTOGENERATED FILE, DO NOT ATTEMPT TO MODIFY ☭!
          * 
          * Use `yarn graphql:generate` and commit this file.
          * Optionally, pass the `--watch` flag during development.
          */
      - typescript-common
      - typescript-server
      - typescript-resolvers

```

If I switch back to the 0.14.5 and regenerate types it is working good.

**Environment:**

- OS: MacOS
- `@graphql-codegen/...`: 0.18.2
- NodeJS: 11.1.0

Thank you!
