### ISSUE TITLE
React hooks not generated

### ISSUE THREAD

**Issue by jcelliott** [dotansimha/graphql-code-generator#2262]
**Describe the bug**

With codegen configuration that I expect to generate React hooks, there are no hooks in the generated output. I'm using `hooksImportFrom: "@apollo/react-hooks"`, but the issue happens with or without that configuration set.

**To Reproduce**

I've reproduced the issue in this codesandbox:
https://codesandbox.io/embed/graphql-codegen-hooks-issue-2nswv.

Look at the generated `types.tsx` file and verify there are no hook functions.

**Comment by dotansimha** [comment]
Hi @jcelliott ! 
Your config syntax is not correct, the `-` creates array instead of object with keys. It should be: 

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.tsx:
    plugins:
      - typescript
      - typescript-operations
      - "typescript-react-apollo"
    config:
      withHooks: true
      withHOC: false
      withComponent: false
      hooksImportFrom: "@apollo/react-hooks"
```
