### ISSUE TITLE
Missing import Types

### ISSUE THREAD

**Issue by andreyvital** [dotansimha/graphql-code-generator#2276]
**Describe the bug**
 
Doesn't import "Types" if you spread only fragments

**To Reproduce**

1. My GraphQL operations:

```TSX
export default gql`
  query AssetTickerBySymbol($tickerSymbol: String!) {
    assetByTickerSymbol(tickerSymbol: $tickerSymbol) {
      ... on A {
        ...FragmentA
      }
      ... on B {
        ...FragmentB
      }
      ... on C {
        ...FragmentC
      }
    }
  }

  ${FragmentA}
  ${FragmentB}
  ${FragmentC}
`;
```

2. My `codegen.yml` config file:

```yml
schema: http://localhost:25256

generates:
  types/introspection-result.ts:
    plugins:
      - "fragment-matcher"

  types/graphql-types.ts:
    plugins:
      - "typescript"
      - "typescript-operations"

    config:
      typesPrefix: I
      immutableTypes: false
      skipTypename: false
      avoidOptionals: true
      nonOptionalTypename: true

  .:
    documents: "lib/{queries,fragments}/**/*.ts"
    preset: near-operation-file

    presetConfig:
      extension: .generated.ts
      baseTypesPath: ./types/graphql-types.ts

    plugins:
      - typescript-operations

    config:
      typesPrefix: I
      avoidOptionals: true
      nonOptionalTypename: true
```

**Expected behavior**
As you can see, I don't have any selection other than the fragments' spread. The resulting file (near-operation-file) doesn't generate the `import * as Types` accordingly. It needs to be generated because the argument `tickerSymbol` refers to a String:

```TSX
export type IAssetTickerBySymbolQueryVariables = {
  tickerSymbol: Types.Scalars["String"];
};
```

I guess it is because of this function: https://github.com/dotansimha/graphql-code-generator/blob/master/packages/presets/near-operation-file/src/utils.ts#L69-L85

It isn't accounting for arguments and is probably failing to detect fragment spreads. Hence we don't get the import: https://github.com/dotansimha/graphql-code-generator/blob/master/packages/presets/near-operation-file/src/index.ts#L170-L172. I could be wrong, though. Just a guesss!

Thanks for all the work. Love this project.
