### ISSUE TITLE
Config to allow `undefined` in typescript resolver output

### ISSUE THREAD

**Issue by DennisKo** [dotansimha/graphql-code-generator#2279]
**Is your feature request related to a problem? Please describe.**

https://github.com/dotansimha/graphql-code-generator/issues/1012 already describes my feature request perfectly. It was also already implemented afterwards but the option somehow is not available anymore?

Edit: I looked around a bit more and found that it is called `maybeValue` now https://graphql-code-generator.com/docs/plugins/typescript#maybevalue-string-default-value-t-null . So if you are using typeorm's `entity.findOne(1)` for example you can use maybeValue like that:

```
generates:
  src/generated/graphql.ts:
    config:
      maybeValue: T | null | undefined
    plugins:
      - "typescript"
      - "typescript-resolvers"
```
