### ISSUE TITLE
How to get autocomplete from response data?

### ISSUE THREAD

**Issue by 18601673727** [dotansimha/graphql-code-generator#2288]
Hello! Sorry for my poor English, getting into the question directly:

codegen.yml
```yml
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
config:
  withHooks: true
  withResultType: true
  withMutationFn: true
  withMutationOptionsType: true
  withHOC : false
  withComponent: false
  reactApolloVersion: 3
  reactApolloImportFrom: "@apollo/react-common"
  hooksImportFrom: "@apollo/react-hooks"
```
package.json
```json
"@types/graphql": "^14.2.3",
"@apollo/react-hooks": "0.1.0-beta.11",
"@apollo/react-common": "0.1.0-beta.9",
"@graphql-codegen/typescript": "^1.4.1-alpha-0046bee3.76",
"@graphql-codegen/typescript-operations": "^1.4.1-alpha-0046bee3.76",
"@graphql-codegen/typescript-react-apollo": "^1.4.1-alpha-0046bee3.76",
```
TagFormComponent
```ts
const [saveTags, ...rest]: [SaveTagsMutationFn, any] = useSaveTagsMutation()

const onSubmit = async (payload: Tags_Insert_Input) => {
  const response = await saveTags({     // <- No type hints from `response`
    variables: { objects: [ payload ] }
  })
  console.log(response) // { data: { insert_tags: { affected_rows: 1, __typename: "tags_mutation_response" } } }
  console.log(rest) // [ { called: false, loading: false } ]
}
```
The data could be saved into database, but how to get type hintings or autocompletes all the old friends back?

Any help will be much appreciated, thanks!
