### ISSUE TITLE
Types not being generated for gql files with imports

### ISSUE THREAD

**Issue by joshlam** [dotansimha/graphql-code-generator#2290]
Note that this is using `1.4.1-alpha-906f6449.78` 

**Describe the bug**
 

It looks like files that import other fragments aren't getting types generated.

Config:
```
overwrite: true
schema: path/to/schema
documents: src/**/*.gql
generates:
    codegen/graphql.d.ts:
        plugins:
            - 'typescript'
            - 'typescript-operations'
        config:
            namingConvention:
                enumValues: keep
                typeNames: change-case#pascalCase
            preResolveTypes: true
            typesPrefix: I
    codegen/graphql.schema.json:
        plugins:
            - 'fragment-matcher'
```

If I have two files

`src/fragments/clickEventInfo.gql`:
```
fragment clickEventInfo on ClickEvent {
  __typename
  .
  .
  .
}
```
and
`src/fragments/blah.gql`:
```
#import 'src/fragments/clickEventInfo.gql'

fragment blah on Blah {
  clickEvent {
    ...clickEventInfo
  }
}
```

A type will only be generated for the `IClickEventInfoFragment`.

**Expected behavior**

Types to be generated for all documents
