### ISSUE TITLE
typescript-react-apollo - component definitions are not generated when mutation has no arguments

### ISSUE THREAD

**Issue by iFallUpHill** [dotansimha/graphql-code-generator#2310]
**Describe the bug**
I think it might be similar to #1449? If my mutation definition doesn't have any arguments, React component is generated. I also want to preface by saying that I'm pretty new to GraphQL in general, so hopefully this isn't just an error on my end.

**To Reproduce**

Use './schema.json' as schema
Use './src/**/*.{ts,tsx}' as documents
Run the following command: gql-gen generate

config.yml
```yml
overwrite: true
schema: "http://localhost:4000/graphql"
documents: "graphql/**/*.ts"
generates:
  generated/apolloComponents.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
config:
  withHooks: true
  withResultType: true
  reactApolloVersion: 3
  reactApolloImportFrom: "@apollo/react-common"
  hooksImportFrom: "@apollo/react-hooks"
```

frontend
```js
export const resendConfirmUserMutation = gql`
    mutation resendConfirmUser() {
        resendConfirmUser
    }
`;
```

backend
```ts
@Resolver()
export class ResendConfirmUser {
    @Mutation(() => Boolean)
    async resendConfirmUser(@Ctx() ctx: MyContext): Promise<boolean> {
        //... some stuff
        return true;
    }
}
```
**Expected behavior**
generate a React component for this mutation

**Environment:**

- OS: macOS 10.14.6
- NodeJS: v12.6 
```json
    "@graphql-codegen/cli": "^1.5.0",
    "@graphql-codegen/typescript": "1.5.0",
    "@graphql-codegen/typescript-operations": "1.5.0",
    "@graphql-codegen/typescript-react-apollo": "1.5.0",
```

**Additional context**
This only seems to happen when there's no arguments at all in my mutation. Also now that I think about it, it's probably not the most sound idea to have a mutation that takes no arguments :/
