### ISSUE TITLE
`globby` returns inconsistent order of found files 

### ISSUE THREAD

**Issue by yoavain-sundaysky** [dotansimha/graphql-code-generator#2311]
**Describe the bug**
Each time I'm running the graphql-codegen, I get a different result.
All results are valid, but order of types changes.

This creates 2 problems for us.
1. We think we need to commit generated files each time we run the tool.
2. I wrote a test that makes sure all developers are running the tool and commit the new generated files, and the test is broken now..

I went over your changes from 1.4 to 1.5 and my guess is this:
You replaced glob with globby, and from a quick search I found this bug that suggests that globby results are non-deterministic:
https://github.com/sindresorhus/globby/issues/131

**To Reproduce**
1. Run graphql-codegen, commit result.
2. Run graphql-codegen again, check for changes.

Our schema is too complex to share, but if you can't reproduce it, I'll try to create a live sandbox.

My `codegen.yml` config file:
```yml
overwrite: true
schema:
  - ./server/graphql/**/*.graphql
documents:
  - ./client/**/*.graphql
generates:
  ./common/graphqlGeneratedTypes/graphqlClient.tsx:
    config:
      withComponent: false
      typesPrefix: "GqlClient"
      nonOptionalTypename: true
      namingConvention:
        typeNames: change-case#pascalCase
        enumValues: change-case#upperCase
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
```

**Expected behavior**
consistent generated files.

**Environment:**

- OS: Windows
- `@graphql-codegen/1.5.0`: 
- NodeJS: 10.x
