### ISSUE TITLE
nullable fields are `T | null | undefined` instead of `T | null`

### ISSUE THREAD

**Issue by LarsJK** [dotansimha/graphql-code-generator#2314]
**Describe the bug**
nullable fields are `T | null | undefined` instead of `T | null`

**To Reproduce**

1. My GraphQL schema:

```graphql
type Character {
  name: String!
  nickname: String
}
```

2. My `codegen.yml` config file:

```yml
overwrite: true
schema: "http://localhost:4000/graphql"
documents: "src/**/*.graphql"
generates:
  src/generated/graphql.generated.tsx:
    config:
      skipTypename: true
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
```

**Expected behavior**
I expect the generated models nickname property to be `T | null`:

**Expected**
```ts
type Character = {
  name: Scalars['String'],
  nickname: Maybe<Scalars['String']>,
}
```

not `T | null | undefined`:

**Actual**
```ts
type Character = {
  name: Scalars['String'],
  nickname?: Maybe<Scalars['String']>,
}
```

**Environment:**

- OS: macOS Mojave
- "@graphql-codegen/cli": "^1.5.0",
- "@graphql-codegen/typescript": "1.5.0",
- "@graphql-codegen/typescript-operations": "^1.5.0",
- "@graphql-codegen/typescript-react-apollo": "1.5.0",
- NodeJS: v11.10.1

**Additional context**
I saw issue #138 and understand people have different opinions on this. But we also have the config: `maybeValue` which you can use to set Maybe to be `T | null | undefined`..
Maybe the models properties could be reverted back to no-undefined and the default for `maybeValue` could be changed to `T | null | undefined`...?
