### ISSUE TITLE
When using withHooks we seeing a space as `use<queryName>Lazy Query` instead of one word

### ISSUE THREAD

**Issue by veeramarni** [dotansimha/graphql-code-generator#2396]
**Describe the bug**
 

The generated code has a `space` like below.
```
      export function useTodoStateLazy Query(baseOptions?: ApolloReactHooks.LazyQueryHookOptions<SchemaTypes.ITodoStateQuery, SchemaTypes.ITodoStateQueryVariables>) {
        return ApolloReactHooks.useLazyQuery<SchemaTypes.ITodoStateQuery, SchemaTypes.ITodoStateQueryVariables>(TodoStateDocument, baseOptions);
      };

```

**To Reproduce**

3. My `codegen.yml` config file:

```yml
  models.tsx:
    documents: "packages/files-client-state/src/**/*.gql"
    schema: 
      - ./packages/client-state/src/**/*.graphql
      - ./packages-modules/module/server/src/graphql/**/*.graphql
    config:
        namingConvention: keep
        typesPrefix: I
        withMutationFn: true
        withHOC: true
        withComponent: true
        withHooks: true
    preset: "@cdmbase/import-types-preset"
    presetConfig:
      typesPath: "core"
      importTypesNamespace: SchemaTypes
```

**Expected behavior**

```
      export function useTodoStateLazy Query(baseOptions?: ApolloReactHooks.LazyQueryHookOptions<SchemaTypes.ITodoStateQuery, SchemaTypes.ITodoStateQueryVariables>) {
        return ApolloReactHooks.useLazyQuery<SchemaTypes.ITodoStateQuery, SchemaTypes.ITodoStateQueryVariables>(TodoStateDocument, baseOptions);
      };

```
**Environment:**

- OS: 
- `@graphql-codegen/...`:  1.6.1
- NodeJS: 

**Additional context**
