### ISSUE TITLE
1.5.0+ is inconsistent in output when used with prettier

### ISSUE THREAD

**Issue by nathanchapman** [dotansimha/graphql-code-generator#2402]
**Describe the bug**
 

Using 1.5.0 and above results in a constant diff in output after each run.
I tested this both with 1.5.0 (prettier output, no hooks) and with the new hooks in released in 1.6.0 to format the generated file with prettier.

After each run, the generated file will diff only in ordering/sorting of type declarations and fields. This does not occur in graphql-codegen@1.4.0 and below. The diff only being changes with sorting seemed weird to me, given the "rationale" of prettier: https://prettier.io/docs/en/rationale.html#what-prettier-is-not-concerned-about

I removed prettier and tested again and this doesn't occur. The output is consistent.

Hopefully, this helps with tracking it down!

**To Reproduce**

Update to 1.5.0, run `codegen` while using `prettier` to format.
Stage the files. Run codegen again. There's a diff. Repeat.

I'm using prettier@1.18.2

1. My GraphQL schema:

Unable to share 😞 

2. My GraphQL operations:

Unable to share 😞

3. My `codegen.yml` config file:

With 1.6.0 and above:
```yml
overwrite: true
schema: src/schemas/**/typeDefs.ts
generates:
  ./src/types/codegen.ts:
    hooks:
      afterOneFileWrite:
        - prettier --write
    config:
      useIndexSignature: true
      contextType: ./GraphQLContext#GraphQLContext
      namingConvention:
        enumValues: change-case#upperCase
    plugins:
      - typescript
      - typescript-resolvers
```

With 1.5.0 and below:
```yml
overwrite: true
schema: src/schemas/**/typeDefs.ts
generates:
  ./src/types/codegen.ts:
    config:
      useIndexSignature: true
      contextType: ./GraphQLContext#GraphQLContext
      namingConvention:
        enumValues: change-case#upperCase
    plugins:
      - typescript
      - typescript-resolvers
```

**Expected behavior**

Expect no diff in generated file when GraphQL typeDef files haven't changed

**Environment:**

- OS: macOS Mojave 10.14.5
- `@graphql-codegen/...`: 1.5.0 and above
- NodeJS: v10.16.0

**Additional context**
