### ISSUE TITLE
Schema not exclude

### ISSUE THREAD

**Issue by CANHBK** [dotansimha/graphql-code-generator#2410]
**Describe the bug**
Can't specify schema files to exclude

**To Reproduce**

- Generate at first time will working
- Generate at second time will not work
```Error
√ Parse configuration
  > Generate outputs
    > Generate src/generated/graphql.generated.ts
      × Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate


 Found 1 error

  × src/generated/graphql.generated.ts
    Failed to load schema from !**/*.generated.ts:

        Unable to find any GraphQL type defintions for the following pointers: ! 
**/*.generated.ts
        Error: Unable to find any GraphQL type defintions for the following poin 
ters: !**/*.generated.ts
    at Object.loadTypedefs 
(C:\Users\Canh\Documents\Project\Mandevices\mandevices\server\services\post\node 
_modules\graphql-toolkit\dist\commonjs\loaders\load-typedefs.js:78:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:757:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

        GraphQL Code Generator supports:
          - ES Modules and CommonJS exports (export as default or named export " 
schema")
          - Introspection JSON File
          - URL of GraphQL endpoint
          - Multiple files with type definitions (glob expression)
          - String in config file

        Try to use one of above options and run codegen again.
```
1. My GraphQL schema:

```graphql
type Query {
		posts: [Post!]!
	}
	type Post @key(fields: "id") {
		id: ID!
		title: String
	}
```

2. My GraphQL operations:

```graphql
Query: {
		posts: () => {
			return [
				{
					id: "abc",
					title: "Sach"
				}
			];
		}
	},
	Post: {
		// @ts-ignore
		__resolveReference(post, { fetchPostById }) {
			return fetchPostById(post.id);
		}
	}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: 
  - './src/**/*.ts'
  - '!**/*.generated.ts'
documents: null
generates:
  src/generated/graphql.generated.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
    config:
      federation: true
      noSchemaStitching: true
```

**Expected behavior**
Files should be generated

**Environment:**

- OS:  Window 10 1903 build 18362.295
- `@graphql-codegen/...`: 1..6.1
- NodeJS: 10.15.3
