### ISSUE TITLE
`typescript-document-nodes` doesn't generate type defs

### ISSUE THREAD

**Issue by leebenson** [dotansimha/graphql-code-generator#2440]
This may be outside of its use-case, but given `schema` and `type` definitions, the `typescript-document-nodes` plugin generates a mostly blank output file:

**codegen.yml**

```yaml
schema: schema/**/*.graphql
generates:
  ./src/graphql/index.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      useIndexSignature: true
  ./src/graphql/schema.ts:
    plugins:
      - typescript-document-nodes
    config:
      noGraphQLTag: true
```

Output:

```ts
import { DocumentNode } from 'graphql';
```

☝️ no definitions.

I'm guessing the plugin is targeted at client-side queries rather than server type definitions; is there an equivalent for the server?

Thanks in advance!
