### ISSUE TITLE
Some operations/fragments validations are being skipped by `graphql-toolkit`

### ISSUE THREAD

**Issue by merisbahti** [dotansimha/graphql-code-generator#2452]
**Describe the bug**
The query (`Query`) gets the `__typename` `'Query' & 'Pizzeria'`, which is impossible.

**To Reproduce**
https://codesandbox.io/s/magical-dirac-nzc4c

1. My GraphQL schema:

```graphql
type OtherStuff {
  foo: String
}

type Pizzeria {
  id: Int,
  name: String,
  location: String,
}

type Query {
  otherStuff: OtherStuff
}
```
fragment:
```graphql
fragment pizzeriaFragment on Pizzeria {
  name
}
```

2. My GraphQL operations:

```graphql
query searchPage {
  otherStuff {
    foo
  }
  ...pizzeriaFragment 
}
```

3. My `codegen.yml` config file:

```yml
schema: src/schemas/*.graphql
generates:
  ./src/types.ts:
    documents:
      - src/queries/*.graphql
    plugins:
      - typescript
      - typescript-operations
    config:
      enumsAsTypes: true
      skipTypename: false
      preResolveTypes: true
```

**Expected behavior**
The type of SearchPageQuery should _not_ be `'Query' & 'Pizzeria'`.
**Environment:**

Sandbox

**Additional context**
