### ISSUE TITLE
Typescript generated with errors

### ISSUE THREAD

**Issue by PedroLamas** [dotansimha/graphql-code-generator#2489]
**Describe the bug**
With the latest versions, I am getting some errors in my generated typescript files.

Notice the final `|  |  |  |  |  |  |  |` on the following generated code:

```javascript
export type PostMdxFragment = (
  Pick<Mdx, 'id' | 'body' | 'excerpt'>
  & { fields: Maybe<Pick<MdxFields, 'slug'>>, frontmatter: Maybe<(
    Pick<MdxFrontmatter, 'categories' | 'date' | 'dateFormatted' | 'last_modified_at' | 'layout' | 'tags' | 'title'>
    & { image: Maybe<(
      Pick<File, 'publicURL'>
      & { childImageSharp: Maybe<{ fluid: Maybe<Pick<ImageSharpFluid, 'presentationWidth'>
          & GatsbyImageSharpFluid_WithWebpFragment
        > }> }
    )> }
  )>, file: Maybe<Pick<File, 'base'> |  |  |  |  |  |  |  | > }
);
```

**To Reproduce**

1. clone/download this repo: https://github.com/PedroLamas/pedrolamas.com
2. run `yarn` to install dependencies
3. run `yarn develop` to start
4. on a second terminal, run ` yarn codegen`
5. check the generated "src\utils\graphql.generated.ts" file, and look for the bit in the example above.

1. My GraphQL schema:

Mostly inferred from my typescript code, but after running `yarn develop` from the steps above, you can access it via http://localhost:8000/__graphql

2. My GraphQL operations:

(Inferred from typescript)

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: 'http://localhost:8000/___graphql'
documents:
  - ./src/**/*.{ts,tsx}
  - ./node_modules/gatsby-*/**/*.js
generates:
  src/utils/graphql.generated.ts:
    config:
      skipTypename: true
      enumsAsTypes: true
    plugins:
      - 'typescript'
      - 'typescript-operations'
  #     - "typescript-react-apollo"
  # ./graphql.schema.json:
  #   plugins:
  #     - "introspection"
```

**Expected behavior**

Generate typescript code without errors!

**Environment:**

- OS: Windows 10 version 1903 (build 18362.10015)
- `@graphql-codegen/...`: 1.6.1
- NodeJS: 10.15.3
