### ISSUE TITLE
@graphql-codegen/introspection fails with federated schema

### ISSUE THREAD

**Issue by gerwinbrunner** [dotansimha/graphql-code-generator#2492]
I'm having federated microservices that are exposed thru ApolloGateway.
The `imports/gen/graphql.ts` is generated successfully, but generating `imports/gen/introspection-schema.json` fails with the following error:

```
$ meteor npx graphql-codegen
  ✔ Parse configuration
  ❯ Generate outputs
    ✔ Generate imports/gen/graphql.ts
    ❯ Generate imports/gen/introspection-schema.json
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Unknown directive "external".

 Found 1 error

  ✖ imports/gen/introspection-schema.json
    Error: Unknown directive "key".
    Unknown directive "external".
    Unknown directive "external".
    Unknown directive "key".
    Unknown directive "external".
    Unknown directive "external".
    Unknown directive "key".
    Unknown directive "external".
    Unknown directive "external".
```

codegen.yml:

```
schema: "imports/microservices/**/schema.js"
overwrite: true
documents: "imports/ui/**/*.tsx"
federation: true
generates:
  imports/gen/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - typescript-resolvers
    config:
      federation: true
      withHOC: false
      withComponent: false
      withHooks: true
      withMutationFn: true
      hooksImportFrom: "@apollo/react-hooks"
  imports/gen/introspection-schema.json:
    plugins:
      - introspection
```
Any idea how I can add the federation opjects?
