### ISSUE TITLE
Missing `import` statements in autogenerated files cause TypeScript errors

### ISSUE THREAD

**Issue by rafeca** [dotansimha/graphql-code-generator#2497]
**Describe the bug**

On v1.7.0, the `near-operation-file` preset doesn't add the required `import` statement for the schema types in some situations, causing TypeScript errors.

This seems to happen whenever an operation is not using any schema type directly, but the generator code still inserts `Types.Maybe` for nullable fields.

This problem has been introduced in v1.7.0.

**To Reproduce**

Open the following CodeSandbox, where the issue is reproducible: https://codesandbox.io/s/graphql-codegen-issue-template-fbe2g?fontsize=14&module=%2Fsrc%2FgetUser.generated.ts

1. My GraphQL schema:

```graphql
interface Node {
  id: ID!
}

type User implements Node {
  id: ID!
  login: String!
  name: String
}

type Query {
  user: User
}
```

2. My GraphQL operations:

```graphql
query getUser {
  user {
    ...user
  }
}
```

```graphql
fragment user on User {
  id
  login
  name
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "schema.graphql"
documents: "src/**/*.graphql"
generates:
  src/graphql-schema-types.generated.ts:
    plugins:
      - typescript
  src/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: "graphql-schema-types.generated.ts"
    plugins:
      - "typescript-operations"
    config:
      withComponent: false
      withHooks: true
```

**Expected behavior**

I expect the generated files to not have any TypeScript error. The `getUser.generated.tsx` file has the following contents:

```tsx
import { UserFragment } from './User.generated';
export type GetUserQueryVariables = {};


export type GetUserQuery = (
  { __typename?: 'Query' }
  & { user: Types.Maybe<{ __typename?: 'User' }
    & UserFragment
  > }
);
```

(notice the missing `import * as types from "./graphql-schema-types.generated.ts";`).

**Environment:**

- OS: OSX
- `@graphql-codegen` v1.7.0
- NodeJS: v12

**Additional context**

The issue seems to have been caused by https://github.com/dotansimha/graphql-code-generator/pull/2458
