### ISSUE TITLE
`federation: true` ERROR: Directive key: Couldn't find type key in any of the schemas.

### ISSUE THREAD

**Issue by jasmo2** [dotansimha/graphql-code-generator#2505]
**`federation: true` flag is not working on codegen**
 

**To Reproduce**
Install Codegen use the script below in _codesandbox.io_ visualize the error.
`Directive key: Couldn't find type key in any of the schemas.`

> [https://codesandbox.io/s/federation-issues-edtu4](https://codesandbox.io/s/federation-issues-edtu4)

• My `codegen.yml` config file:

```yml
overwrite: true
documents: null
generates:
  src/__types__/index.ts:
    schema:
      - src/schema/operations.graphql
      - src/schema/schema.graphql
    plugins:
      - add: // tslint:disable
      - typescript-resolvers
      - typescript
    config:
      federation: true
```

**Expected behavior**

**Environment:**

- OS: MACOS 10.14.6
•
``` "@graphql-codegen/cli": "^1.7.0",
    "@graphql-codegen/typescript": "^1.7.0",
    "@graphql-codegen/typescript-graphql-files-modules": "^1.7.0",
    "@graphql-codegen/typescript-operations": "^1.7.0",
    "@graphql-codegen/typescript-resolvers": "^1.7.0",
    "@graphql-codegen/visitor-plugin-common": "^1.7.0"
```
- NodeJS: 
**v10.16.3**
