### ISSUE TITLE
Can't generate from schema defined in TS

### ISSUE THREAD

**Issue by deser** [dotansimha/graphql-code-generator#2518]
**Describe the bug**
I have defined next schema.js file:
```
require('@babel/register')({ extensions: ['.js', '.ts', '.tsx'] }); // Need to explicitly tell babel/register which extensions to handle until this is completed: https://github.com/babel/babel/issues/8652
require('app-module-path').addPath('./src');

const aSCh = require('server/graphql/schema').default;

module.exports = aSCh;
```

Schema is valid, when I run this code through `node schema.js` it executes ok and print's me schema. But when I try to run through `graphql-codegen --config gqlcodegen.yml` it fails. If I make introspection schema from  `'server/graphql/schema'`, put it into file.json and then run codegen against json file - it works well. 
Also, it works quite well when I generate schema from URL

1. My GraphQL schema:

```graphql
# confidential
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: genIntrospectionSchema.js
documents: null
generates:
    src/shared/types/GraphQLSchema.ts:
        plugins:
            - 'typescript'
            - 'typescript-resolvers'
        config:
            typesPrefix: GQL

```

**Expected behavior**
Schema is generated well. 

**Environment:**

- OS: Windows 10
- `@graphql-codegen/...`: 1.7.0
- NodeJS: 10.16.1
