### ISSUE TITLE
Type duplications 

### ISSUE THREAD

**Issue by deser** [dotansimha/graphql-code-generator#2519]
**Describe the bug**
With valid schema type duplications are generated. See pic below:
![image](https://user-images.githubusercontent.com/3010698/64519457-d0e87e80-d2fc-11e9-93e8-ca2b785eadd4.png)

```yml
overwrite: true
schema: http://localhost:3000/api/v1/data
documents: null
generates:
    src/shared/types/GraphQLSchema.ts:
        plugins:
            - 'typescript'
            - 'typescript-resolvers'
        config:
            typesPrefix: GQL

```

- OS: Windows 10
- `@graphql-codegen/...`: 1.7.0
- NodeJS: 10.16.1
