### ISSUE TITLE
`importDocumentNodeExternallyFrom: near-operation-file` should strip file extension

### ISSUE THREAD

**Issue by Swatinem** [dotansimha/graphql-code-generator#2548]
**Describe the bug**
 

The generated code imports files with their full filename, which leads to a TypeScript Error:
```
[…]/AccountActivation.generated.tsx:5:29 - error TS2691: An import path cannot end with a '.tsx' extension. Consider importing './AccountActivation' instead.

5 import * as Operations from './AccountActivation.tsx'
                              ~~~~~~~~~~~~~~~~~~~~~~~~~
```

**To Reproduce**

1. My `codegen.yml` config file:

```yml
generates:
  /schema.generated.ts:
    schema: /cached-auth.graphql
    plugins:
      - typescript
      - add: *add
  /:
    schema: /cached-auth.graphql
    documents:
      - **/*.{ts,tsx}
      - '!**/*.generated.{ts,tsx}'
      - '!**/*.d.ts'
    preset: near-operation-file
    presetConfig:
      extension: .generated.tsx
      baseTypesPath: schema.generated.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo

config:
  documentMode: external
  importDocumentNodeExternallyFrom: near-operation-file
```

**Expected behavior**

file extensions should be stripped to silence TS :-)

**Environment:**

- OS: arch
- `@graphql-codegen/...`:  1.7.0
- NodeJS: 10.15

**Additional context**
