### ISSUE TITLE
Unused Imports Generated - "import * as React from 'react'"

### ISSUE THREAD

**Issue by seanharr11** [dotansimha/graphql-code-generator#2559]
**Describe the bug**
When using the 'typescript-react-apollo' plugin, unused imports are generated. While [this PR](https://github.com/dotansimha/graphql-code-generator/pull/750/commits/2b4b25acfab3b936ecfbe7983e4e7020664ca352) addressed the issue initially, there is a separate case for `ReactApolloHooks` is in fact "used", while `React` is **NOT**.

**To Reproduce**

*Just add `typescript-react-apollo` to `codegen.yml` (see (3) below).*

1. My GraphQL schema:

```graphql
N/A
```

2. My GraphQL operations:

```graphql
N/A
```

3. My `codegen.yml` config file:

```yml
# Put your YML here
schema: ./src/graphql/**/*.ts
overwrite: true
require:
  - ts-node/register
generates:
  ../client/src/types/index.tsx:
    schema: ../client/src/graphql/typeDefs/*.ts
    documents: ../client/src/graphql/**/*.graphql
    plugins:
      - add: "/** @jsx jsx */\nimport { jsx } from '@emotion/core';\n"
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
      - "fragment-matcher"
    config:
      scalars:
        Date: string
        Time: string
        DateTime: Date
      avoidOptionals: true
      namingConvention:
        typeNames: change-case#pascalCase
        enumValues: change-case#camelCase
      withHooks: true
      skipTypename: true
```

**Expected behavior**
`import React as * from 'react'` should not get added to the file...TBH I'm not sure what cases you'd need `React` to be defined in the codegen output file.

**Environment:**

- OS: Mac OS 10.14.6
- `@graphql-codegen/...`:  **1.2.0**
- NodeJS: **v.12.3.1**

**Additional context**

**Comment by seanharr11** [comment]
For those stumbling upon this issue from lots of Google searches, you can hack around this by adding this `DummyVarToAvoidUnusedImports` "plugin" to your `codegen.yml` as follows:

```
  ../client/src/types/index.tsx:
    schema: ../client/src/graphql/typeDefs/*.ts
    documents: ../client/src/graphql/**/*.graphql
    plugins:
      - add: "/** @jsx jsx */\nimport { jsx } from '@emotion/core';\n"
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
      - "fragment-matcher"
      - add: "export type DummyVarToAvoidUnusedImports = React.ReactNode"
```
