### ISSUE TITLE
Duplicated generated types with near-operation-file preset

### ISSUE THREAD

**Issue by djflex68** [dotansimha/graphql-code-generator#2587]
Hello,

I'm having some trouble getting near-operation-file preset to work.
I've built a small demo here : 
https://stackblitz.com/edit/typescript-4shuse

When generating the code (using npm run gql-codegen), I'm getting 2 files as expected :
- baseTypes that exports some core types `(export type Circuit` , `export type Device`...)
- data.graphql.generated that exports my queries (ConfigurableServiceByIdGQL, ChangeActivationStatusGQL...) but also **Circuit , Device... again**, which is **not** the expected behaviour.

Please also notice that the `import * as Types from '../base-types';` generated at file start, is never used in that generated file.

I've been spending hours on that, but did not find what I've been doing wrong.
Any help is appreciated :)

Thanks

**Comment by dotansimha** [comment]
@djflex68 
You specified `typescript` plugin for the `near-fragment-file` preset as well. 

Can you please try:

```yml
overwrite: true
schema: ./schema.json
documents: src/**/*.graphql.ts
generates:
  ./src/base-types.ts:
    plugins:
      - typescript  
      - fragment-matcher
    config:
      avoidOptionals: true
      immutableTypes: true
      preResolveTypes: true

  ./src/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: base-types.ts
    plugins:
      - typescript-operations
      - typescript-compatibility
      - typescript-apollo-angular
    config:
      avoidOptionals: true
      immutableTypes: true
      preResolveTypes: true
```
