### ISSUE TITLE
Using fragments (with near-operation-file?) is non-deterministic

### ISSUE THREAD

**Issue by Swatinem** [dotansimha/graphql-code-generator#2589]
**Describe the bug**
 

I tried to dedupe some code which was using all the same props from a Union type into using a fragment.
In code, I use the fragment just via its name (no extra imports or similar).

But the codegen output is non-deterministic. Some of my components get the correct fragment output, while others don’t.

Strangely enough, we have a failure on CI related to this, and I got it to reproduce locally one, but after re-running codegen, I only get correct results, which makes it super strange and further proves that there is some non-determinism here…

The *correct* output is similar to this:

```ts
import { MyFragmentDoc } from '../MyFragment.generated';
import { MyFragment } from '../MyFragment.generated';

export type MyMutation = { myMutation: ({  } | {  })
    & MyFragment
   };

export const MyMutationDocument = gql`
    mutation MyMutation {
  myMutation {
    ...MyFragment
  }
}
    ${MyFragmentDoc}`;
```

**To Reproduce**

I minified this quite a bit from our usecase, so I hope it still makes sense…

1. My GraphQL schema:

```graphql

type A {
  a: String!
}

type B {
  a: String!
}

union MyUnion = A | B
```

2. My GraphQL operations:

```ts
// File A
export const MyFragment = gql`
  fragment MyFragment on MyUnion {
    __typename
    ... on A {
      a
    }
    ... on B {
      b
    }
  }
`

// File B
export const MyMutation = gql`
  mutation MyMutation {
    myMutation {
      ...MyFragment
    }
  }
`
```

3. My `codegen.yml` config file:

```yml

# some aliases used below to keep the config DRY
aliases:
  plugins: &plugins
    - typescript
  plugins-preset: &plugins-preset
    - typescript-operations
    - typescript-react-apollo
    - add:
        placement: 'append'
        content: 'export { Types as _ };'

generates:
  ./src/schema.generated.ts:
    schema: ./cached-schema.graphql
    plugins: *plugins
  ./src/:
    schema: ./cached-schema.graphql
    documents:
      - ./src/**/*.{ts,tsx}
      - '!**/*.generated.{ts,tsx}'
      - '!**/*.d.ts'
    preset: near-operation-file
    presetConfig:
      extension: .generated.tsx
      baseTypesPath: schema.generated.ts
    plugins: *plugins-preset

# generic config shared by all…
config:
  # typescript:
  skipTypename: true

  # typescript-operations:
  preResolveTypes: true
  dedupeOperationSuffix: true

  # typescript-react-apollo:
  # pending https://github.com/dotansimha/graphql-code-generator/issues/2548 :-(
  #documentMode: external
  #importDocumentNodeExternallyFrom: near-operation-file

  withComponent: true
  withHOC: false
  withHooks: true
  withMutationFn: true
  reactApolloVersion: 3
```

**Expected behavior**

The codegen should always produce the same output

**Environment:**

- OS: arch
- `@graphql-codegen/...`: 1.7.0
- NodeJS: 10.15

**Additional context**
