### ISSUE TITLE
@client directive won't generate useMutation hooks

### ISSUE THREAD

**Issue by tafelito** [dotansimha/graphql-code-generator#2609]
I have some client queries and mutations in a local schema. I implemented all the local resolvers but when I run the codegen, even tho I don't get any errors, only the useQuery hooks are generated but none of the mutations are. I don't have any errors so I'm not sure where to look into

client-schema.ts
```js
const typeDefs = gql`
  directive @client(always: Boolean) on FIELD

  extend type Query {
    isLoggedIn: Boolean!
    cartItems: [CartItemLocal!]!
  }

  extend type Product {
    isInCart: Boolean!
  }

  type CartItemLocal {
    productId: ID!
    quantity: Float!
  }

  extend type Mutation {
    addOrRemoveFromCartLocal(productId: ID!, quantity: Float!): [CartItemLocal]!
  }
`;
```

mutations.ts
```js
export const TOGGLE_LOCAL_CART = gql`
  mutation addOrRemoveFromCartLocal($productId: ID!, quantity: Float!) {
    addOrRemoveFromCartLocal(productId: $productId, quantity: $quantity) @client {
      productId
      quantity
    }
  }
`;
```

queries.ts
```js
export const IS_LOGGED_IN = gql`
  query IsUserLoggedIn {
    isLoggedIn @client(always: true)
  }
`;

export const GET_CART_ITEMS = gql`
  query GetCartItems {
    cartItemsLocal @client {
      productId
      quantity
    }
  }
`;

export const GET_PRODUCT = gql`
  query product($id: ID!) {
    product(where: { id: $id }) {
      isInCart @client
      ...ProductData
    }
  }
  ${PRODUCT_DATA}
`;
```

resolvers.ts
```js
const resolvers: Resolvers<Context> = {
  Query: {

    isLoggedIn: () => {
      return !!parseCookies().token;
    },
  },
  Mutation: {
    addOrRemoveFromCartLocal: (_, { productId, quantity }, { cache }) => {
      const data = cache.readQuery<GetCartItemsQuery>({
        query: GET_CART_ITEMS,
      });
      const newData = {
        cartItemsLocal:
          data && data.cartItemsLocal.find(p => p.productId === productId)
            ? data.cartItemsLocal.filter(p => p.productId !== productId)
            : [{ productId, quantity }],
      };
      cache.writeQuery({ query: GET_CART_ITEMS, data: newData });
      return newData.cartItemsLocal;
    },
  },
  Product: {
    isInCart: (product, args, { cache }) => {
      const data = cache.readQuery<GetCartItemsQuery>({
        query: GET_CART_ITEMS,
      });
      return data
        ? !!data.cartItemsLocal.find(p => p.productId == product.id)
        : false;
    },
  },
};
```

codegen.yml
```yml
overwrite: true
schema:
  - http://localhost:4000/graphql
  - graphql/client-schema.ts
documents: 'graphql/**/*.ts'
generates:
  generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-resolvers'
      - 'typescript-react-apollo'
    config:
      reactApolloVersion: 3
      withHooks: true
      withHOC: false
      withComponent: false
      withMutationFn: false
```

and this is one of the queries hooks generated

```js
export const IsUserLoggedInDocument = gql`
  query IsUserLoggedIn {
    isLoggedIn @client(always: true)
  }
`;

export function useIsUserLoggedInQuery(
  baseOptions?: ApolloReactHooks.QueryHookOptions<
    IsUserLoggedInQuery,
    IsUserLoggedInQueryVariables
  >,
) {
  return ApolloReactHooks.useQuery<
    IsUserLoggedInQuery,
    IsUserLoggedInQueryVariables
  >(IsUserLoggedInDocument, baseOptions);
}
export type IsUserLoggedInQueryHookResult = ReturnType<
  typeof useIsUserLoggedInQuery
>;
export type IsUserLoggedInQueryResult = ApolloReactCommon.QueryResult<
  IsUserLoggedInQuery,
  IsUserLoggedInQueryVariables
>;
```

**Environment:**

- `@graphql-codegen/...`: 1.7.0 

**Additional context**
If I remove the local mutations, all the mutations hooks ARE generated
