### ISSUE TITLE
1.7.0 much slower than 1.6.1

### ISSUE THREAD

**Issue by dmarkow** [dotansimha/graphql-code-generator#2614]
**Describe the bug**
 
On 1.6.1, generating types took just a few seconds:
```
$ graphql-codegen --config codegen.yml
  ✔ Parse configuration
  ✔ Generate outputs
✨  Done in 1.84s.
```

Upgrading the cli and core packages to 1.7.0 produces identical output, but runs much slower:

```
$ graphql-codegen --config codegen.yml
  ✔ Parse configuration
  ✔ Generate outputs
✨  Done in 30.45s.
```

**To Reproduce**

1. My GraphQL schema:

Way too large to post

2. My GraphQL operations:

Way too large

3. My `codegen.yml` config file:

```yml
overwrite: true
schema:
  - http://localhost:4000/graphql:
      headers:
        Authorization: "Bearer [my token]"
documents: "frontend/queries/**/*.gql"
generates:
  frontend/types/generated.d.ts:
    plugins:
      - add: "/* eslint-disable */\n"
      - "typescript"
      - "typescript-operations"
config:
  nonOptionalTypename: true
```

**Expected behavior**

The speed it had in 1.6.1. Running this in watch mode means a 30 second feedback loop every time I make a change to one of my graphql files.

**Environment:**

- OS: macOS 10.14.6
- `@graphql-codegen/core`: 1.7.0
- `@graphql-codegen/cli`: 1.7.0
- introspection and typescript-operations packages at either 1.6.1 or 1.7.0 (same issue either way)
- NodeJS: 12.10.0
