### ISSUE TITLE
TypeScript Operations should have declarationKind option

### ISSUE THREAD

**Issue by klemenoslaj** [dotansimha/graphql-code-generator#2616]
**Is your feature request related to a problem? Please describe.**

Currently [TypeScript Operations](https://graphql-code-generator.com/docs/plugins/typescript-operations) doesn't have or doesn't respect the `declarationKind` option (_e.g. `declarationKind: "interface"_).

This can quickly become a show stopper for any monorepo due to the following issue I reported to TypeScript as well: https://github.com/microsoft/TypeScript/issues/32653 (_will be fixed, milestone 3.7.0_)

**Describe the solution you'd like**

Respect `declarationKind` option, the same as `@graphql-codegen/typescript` does.

**Describe alternatives you've considered**

Not much can be done but to maybe extend all the types from generated document with custom interfaces.

**Comment by klemenoslaj** [comment]
TypeScript moved the milestone from 3.7 to 3.8 for this [issue](https://github.com/microsoft/TypeScript/issues/32653).

Since `graphql-code-generator` does not support interfaces I have no way around that TS bug, thus cannot use this code generator.

Is there any way I can help perhaps?

**Comment by dotansimha** [comment]
@klemenoslaj Sorry for the inconvenience :( PRs are welcome, I think in order to support this we might need some changes in the base visitor for operations (`packages/plugins/other/visitor-plugin-common/src/base-documents-visitor.ts`).

**Comment by dotansimha** [comment]
Available long time ago, we can close this one :)

**Comment by klemenoslaj** [comment]
@dotansimha is this really working? I installed latest versions and created the following configuration:

```yml
overwrite: true
schema: 'http://localhost:4000/graphql'
documents: 'projects/**/*.graphql.ts'
generates:
  generated/types.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
    config:
      avoidOptionals: true
      dedupeOperationSuffix: true
      immutableTypes: true
      preResolveTypes: true
      nonOptionalTypename: true
      constEnums: true
      strict: true
      declarationKind: 'interface'
```

While `interfaces` are used quite extensively, they are not used for any GraphQL document type, like Query, Subscription, Mutation - types are used.
