### ISSUE TITLE
federation bug: Cannot find name 'ReferenceResolver'.

### ISSUE THREAD

**Issue by ForbesLindesay** [dotansimha/graphql-code-generator#2676]
**Describe the bug**
 

When federation is enabled, you now get the error: `Cannot find name 'ReferenceResolver'.`

**To Reproduce**

[![Edit graphql-codegen-issue-template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/graphql-codegen-issue-template-wdfcr?fontsize=14)

1. run yarn generate
2. run yarn typecheck

My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User @key(fields: "id") {
    id: ID!
    username: String!
    email: String!
}
```

My `codegen.yml` config file:

```yml
schema: schema.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      federation: true
```

**Expected behavior**

It should output the type, https://github.com/dotansimha/graphql-code-generator/blob/587599f47336afff05e42f2cd11c74c69bd5ab40/packages/plugins/typescript/resolvers/src/index.ts#L90-L96 depends on a property that doesn't get set until after the rest of the code is generated.

**Comment by dotansimha** [comment]
@ForbesLindesay Can you please try to move the federation config upper?

```
schema: schema.graphql
config:
  federation: true
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-resolvers
```

@kamilkisiela

**Comment by zhenxzheng** [comment]
@dotansimha, I see the same bug with v1.8. moving config federation to upper didn't help

**Comment by dotansimha** [comment]
@kamilkisiela can you please take a look? ❤️

**Comment by ruanyl** [comment]
I have the same issue, running codegen v1.8.1
even after moving the config upper, it doesn't help

**Comment by ruanyl** [comment]
@dotansimha was it `GraphQLReferenceResolver` from
https://github.com/apollographql/apollo-server/blob/d5015f4ea00cadb2a74b09956344e6f65c084629/packages/apollo-federation/src/types.ts#L57

**Comment by ruanyl** [comment]
The workaround that I have now is to declare it in `global.d.ts`
```
import {GraphQLResolveInfo} from 'graphql';

declare global {
  type ReferenceResolver<TReference = object, TContext = any, ResolverInfo = GraphQLResolveInfo> = (
    reference: TReference,
    context: TContext,
    info: ResolverInfo
  ) => any;
}
```

**Comment by lkleuver** [comment]
somehow @ruanyl's fix didn't work consistently.
Currently using a slightly modified approach: 

```
plugins:
  - add: 'import {ReferenceResolver} from "./fix";'
  - typescript
  - typescript-resolvers
```

with fix.ts:
```import { GraphQLResolveInfo } from "graphql";

export type ReferenceResolver<TResult, TReference, TContext> = (
  reference: TReference,
  context: TContext,
  info: GraphQLResolveInfo
) => Promise<TResult> | TResult;
```

**Comment by dotansimha** [comment]
@kamilkisiela fixed it in: https://github.com/dotansimha/graphql-code-generator/pull/2760 

Alpha available: `1.8.2-alpha-f9569d0c.47`, can you please try it? @ForbesLindesay @lkleuver @ruanyl

**Comment by lkleuver** [comment]
@dotansimha tried it and seems to work :D awesome!
`"@graphql-codegen/typescript-resolvers": "1.8.2-alpha-f9569d0c.47",`

**Comment by dotansimha** [comment]
Fixed in 1.8.2.

**Comment by nadilas** [comment]
I'm sorry, I'm am on 1.11.2 and the ReferenceResolver doesn't get included, wherever I put the `federation: true`:

```yaml
overwrite: true
schema: "http://localhost:4001"
config:
  federation: true
#documents: "**/*.graphql"
generates:
  "@types/graphql.d.ts":
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-resolvers"
      - "typescript-graphql-files-modules"
    config:
      federation: true
```
