### ISSUE TITLE
enum prefix disable not working

### ISSUE THREAD

**Issue by veeramarni** [dotansimha/graphql-code-generator#2679]
**Describe the bug**
 
When using the following options for`enum`, it generates correctly without a prefix but they are referred with the prefix at `export type IResolversTypes` and typescript compilation fails.

```
  config:
    typesPrefix: I
    enumPrefix: false
```

**To Reproduce**

1. My GraphQL schema:

```graphql
enum GroupLocation {
    FIRST
    LAST
    NEXT
    PREVIOUS
}
```

3. My `codegen.yml` config file:

```yml
generates:
  package/generated-model/generated-model.ts:
    schema:
      - servers/backend-server/src/api/root-schema.graphqls
    documents: 
      - packages-modules/extension/browser/src/graphql/**/*.gql
    config:
        noNamespaces: true
        contextType: ../apollo-context#MyContext
        typesPrefix: I
        enumPrefix: false
        namingConvention: keep
        constEnums: true
        withMutationFn: false
        withHOC: false
        withComponent: false
    plugins:
      - add: |
          /* tslint:disable */
      - typescript
      - typescript-operations
      - typescript-resolvers
      - typescript-react-apollo
```

Output

```
/** Mapping between all available schema types and the resolvers types */
export type IResolversTypes = {
GroupLocation: IGroupLocation,
.....
}

```
**Expected behavior**

No prefix when referring to Enums.

**Environment:**

- OS: 
- `@graphql-codegen/...`:  1.8.0
- NodeJS:
