### ISSUE TITLE
Missing `__typename` when explicitly set 

### ISSUE THREAD

**Issue by ooflorent** [dotansimha/graphql-code-generator#2683]
When generating the TypeScript definitions by `typescript-operations` with `nonOptionalTypename=false` and `skipTypename=true`, `__typename` is missing for the type definitions **even if it is explicitly requested in the query**.

It is possible that it is the intended behavior. If it is, is there a way to achieve this?

**To Reproduce**

1. GraphQL schema:

```graphql
# Not relevant for the issue
```

2. GraphQL operations:

```graphql
query search($search: String!) {
  search(first: 10, search: $search) {
    nodes {
      __typename
      id
      ... on Movie {
        title
      }
      ... on Person {
        name
      }
    }
  }
}

```

3. `codegen.yml` config file:

```yml
schema: schema.json
overwrite: true
generates:
  src/graphql.tsx:
    documents: 'src/**/*.gql'
    plugins:
      - typescript
      - typescript-operations
    config:
      nonOptionalTypename: false
      skipTypename: true
      preResolveTypes: true
```

**Expected behavior**

`__typename` should be generated when explicitly requested.

**Additional context**

`__typename` was correctly generated in `1.7.0`.

**Environment:**

- OS: macOS 10.14.6
- `@graphql-codegen/add`: 1.8.0
- `@graphql-codegen/cli`: 1.8.0
- `@graphql-codegen/fragment-matcher`: 1.8.0
- `@graphql-codegen/typescript`: 1.8.0
- `@graphql-codegen/typescript-operations`: 1.8.0
- NodeJS: 12.10.0
