### ISSUE TITLE
Types namespace missing when using flow-operations and near-operation-file-preset

### ISSUE THREAD

**Issue by lingard** [dotansimha/graphql-code-generator#2693]
**Describe the bug**
Imported types namespace are missing when using flow-operations and near-operation-file-preset. It gets added to the scalars in the query variables but not in the query definition.

```js
// @flow
import * as SchemaTypes from '../types';

type $Pick<Origin: Object, Keys: Object> = $ObjMapi<Keys, <Key>(k: Key) => $ElementType<Origin, Key>>;

export type UserQueryVariables = {
  id: $ElementType<SchemaTypes.Scalars, 'ID'>
};

export type UserQuery = ({
    ...{ __typename?: 'Query' },
  ...{| user: ({
      ...{ __typename?: 'User' },
    ...$Pick<User, {| id: *, username: *, email: * |}>
  }) |}
});

```

**To Reproduce**

https://codesandbox.io/s/graphql-codegen-issue-template-lrsir

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```graphql
query user($id: ID!) {
    user(id: $id) {
        id
        username
        email
    }
}

```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: '**.operations.graphql'
generates:
  types.js:
    plugins:
      - flow
  ./:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: types.js
      extension: .generated.js
      importTypesNamespace: SchemaTypes
    plugins:
      - add: // @flow
      - flow-operations
```

**Expected behavior**
The types used in the operation type definitions should use the imported type namespace, e.g;

```diff
// @flow
import * as SchemaTypes from '../types';

type $Pick<Origin: Object, Keys: Object> = $ObjMapi<Keys, <Key>(k: Key) => $ElementType<Origin, Key>>;

export type UserQueryVariables = {
  id: $ElementType<SchemaTypes.Scalars, 'ID'>
};

export type UserQuery = ({
    ...{ __typename?: 'Query' },
  ...{| user: ({
      ...{ __typename?: 'User' },
-       ...$Pick<User, {| id: *, username: *, email: * |}>
+      ...$Pick<SchemaTypes.User, {| id: *, username: *, email: * |}>
  }) |}
});

```

**Environment:**

- OS: 
- `@graphql-codegen/...`: 1.8.1
- NodeJS: >8
