### ISSUE TITLE
Invalid TypeScript definitions generated

### ISSUE THREAD

**Issue by ooflorent** [dotansimha/graphql-code-generator#2699]
**Describe the bug**

Invalid TypeScript definitions are generated.

```ts
export type GetMovieQuery = { node:  };
                                   ^
```

**To Reproduce**

1. My GraphQL schema:

```graphql
type Query {
  node(gid: ID!): Node
}

interface Node {
  gid: ID!
}

interface Entity {
  gid: ID!
  active: Boolean!
} 

type Movie implements Node, Entity {
  gid: ID!
  active: Boolean!
  name: String!
}
```

2. My GraphQL operations:

```graphql
query getMovie($gid: ID!) {
  node(gid: $gid) {
    ... on Entity {
      gid
    }
  }
}
```

3. My `codegen.yml` config file:

```yml
schema: var/schema.json
overwrite: true
generates:
  assets/graphql/types.tsx:
    documents: 'assets/**/*.gql'
    plugins:
      - typescript
      - typescript-operations
    config:
      nonOptionalTypename: false
      skipTypename: true
      preResolveTypes: true
```

**Expected behavior**

`types.tsx` should be a valid TS file.

**Environment:**

- OS: macOS 10.14.6
- `@graphql-codegen/add`: 1.8.1
- `@graphql-codegen/cli`: 1.8.1
- `@graphql-codegen/fragment-matcher`: 1.8.1
- `@graphql-codegen/typescript`: 1.8.1
- `@graphql-codegen/typescript-operations`: 1.8.1
- NodeJS: 12.10.0
