### ISSUE TITLE
ExperimentalWarning since upgrade to >=1.8.0

### ISSUE THREAD

**Issue by levrik** [dotansimha/graphql-code-generator#2701]
**Describe the bug**

Since upgrading to >=1.8.0 of `@graphql-codegen/cli`, `@graphql-codegen/typescript-operations` and `@graphql-codegen/typescript-react-apollo`, I'm getting this warning displayed: `(node:73362) ExperimentalWarning: Readable[Symbol.asyncIterator] is an experimental feature. This feature could change at any time`

I'm using the latest Node LTS (v10.16.3) and the following configuration:

```yaml
schema: schema.graphql
documents: src/queries/**/*.graphql
generates:
  src/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      scalars:
        Upload: File
      declarationKind: interface
      noGraphQLTag: true
      withHOC: false
      withComponent: false
      withHooks: true
      skipTypename: true
```

**Expected behavior**

I wouldn't expect warnings for experimental features popping up. Maybe the feature is stable in latest Node (v12.x) but I would expect a package to work without problems and warnings also on the latest Node LTS.
