### ISSUE TITLE
Is there a way to generate queries?

### ISSUE THREAD

**Issue by groege** [dotansimha/graphql-code-generator#2702]
I was able to generate classes i.e.:
```
export type QueryRoot = {
   __typename?: 'QueryRoot',
  transportOrderViews?: Maybe<TransportOrderViewConnection>,
};
```
and so on...

it also generates the filters:

```
export type QueryRootTransportOrderViewsArgs = {
  after?: Maybe<Scalars['String']>,
  first?: Maybe<Scalars['Int']>
};
```

but is there a way to generate something like this?

```
interface TransportOrderViewsQuery {
    filters: QueryRootTransportOrderViewsArgs;
    fields?: ["totalCount", { items: TransportOrderViews }, ...etc...];
}

interface TransportOrderViews {
    fields?: ["transportOrderNumber", addresses: Addresses, ...etc...];
}

interface Addresses {
    filters: TransportOrderViewsAddressesArgs;
    fields?: ["adressName", ...etc...]
}

createTransportOrderViewsQuery(queryOptions: TransportOrderViewsQuery): string { ... }
```

So I can create queries type-safe with all filters and the columns i want in the result.

So far I wasn't able to find anything like it in the docs and issues, so any pointers would be awesome.

Thanks!

**Comment by lukasluecke** [comment]
What does your config look like right now? You can generate types for queries and mutations by passing in your GraphQL documents.

**Comment by groege** [comment]
So I'm actually using graphql-dotnet, so I used a npm plugin to generate the schema file I've uploaded
[schema.zip](https://github.com/dotansimha/graphql-code-generator/files/3702240/schema.zip)

Also here is my codegen.yml:
```
schema: http://10.0.0.94:52526/graphql
generates:
  ./ts/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-resolvers
    overwrite: true
    config:
      scalars:
        AnyGraphType: Date | number | string | boolean
        Date: Date
        DateTime: Date
        DoubleGraphType: number
        Byte: Uint8Array
        DateTimeOffset: Date
        Decimal: number
        Milliseconds: number
        SByte: number
        Seconds: number
        Short: number
        UInt: number
        ULong: number
        Uri: URL
        UShort: number
```
(Seems like i'll have to implement resolvers as well..)
