### ISSUE TITLE
The CLI error report is missing necessary information

### ISSUE THREAD

**Issue by ruanyl** [dotansimha/graphql-code-generator#2723]
**Describe the bug**
Getting this error while running the CLI tool to generate typescript types, but it doesn't provide any useful information
```
[17:40:26] Generate [started]
[17:40:27] Generate [failed]
[17:40:27] → Plugin "typescript-react-apollo" validation failed:
[17:40:27] Generate ./src/generatedTypes.ts [failed]
[17:40:27] → Plugin "typescript-react-apollo" validation failed:
[17:40:27] Generate outputs [failed]
```

**This is the codegen.yml**, the problem is that the generated file extension must be `*.tsx`, while I put `*.ts`
```
schema:
  - ${SCHEMA_PATH}:
      headers:
        authorization: ${AUTH_TOKEN}
documents: ./src/**/*.graphql.ts
generates:
  ./src/generatedTypes.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: true
      withHOC: false
      withMutationFn: false
      documentMode: external
      importDocumentNodeExternallyFrom: near-operation-file
```

The actual error if I log the error manually:
```
Error: Plugin "react-apollo" requires extension to be ".tsx"!
    at Object.exports.validate (/Users/ruanyl/project/graphql-client-demo/node_modules/@graphql-codegen/typescript-react-apollo/src/index.ts:204:13)
    at Object.executePlugin (/Users/ruanyl/project/graphql-client-demo/node_modules/@graphql-codegen/core/src/execute-plugin.ts:42:20)
    at /Users/ruanyl/project/graphql-client-demo/node_modules/@graphql-codegen/core/src/codegen.ts:71:28
    at Array.map (<anonymous>)
    at Object.codegen (/Users/ruanyl/project/graphql-client-demo/node_modules/@graphql-codegen/core/src/codegen.ts:58:21)
    at process (/Users/ruanyl/project/graphql-client-demo/node_modules/@graphql-codegen/cli/src/codegen.ts:245:40)
    at async Promise.all (index 0)
    at /Users/ruanyl/project/graphql-client-demo/node_modules/@graphql-codegen/cli/src/codegen.ts:253:23
    at Task.task (/Users/ruanyl/project/graphql-client-demo/node_modules/@graphql-codegen/cli/src/codegen.ts:19:9)
```
