### ISSUE TITLE
Query and QueryResolvers generate incomplete types

### ISSUE THREAD

**Issue by chemoish** [dotansimha/graphql-code-generator#2731]
**Describe the bug**

`Query` and `QueryResolvers` only generate the types for `type Query`. `extend type Query` seem to be ignored.

This worked in `1.7.0`, but has stopped working in `1.8.0`.

**To Reproduce**

1. My GraphQL schema:

```graphql
# Put your schema here

type Query {
  foo: String
}

extend type Query {
  bar: String
}
```

Will generate:

```
export type Query = {
   __typename?: 'Query',
  foo?: Maybe<Scalars['String']>,
};

export type QueryResolvers<ContextType = any, ParentType extends ResolversParentTypes['Query'] = ResolversParentTypes['Query']> = {
  foo?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>,
};
```

However,

```graphql
# Put your schema here

type Query {
  foo: String
  bar: String
}
```

Will generate: 

```
export type Query = {
   __typename?: 'Query',
  foo?: Maybe<Scalars['String']>,
  bar?: Maybe<Scalars['String']>,
};

export type QueryResolvers<ContextType = any, ParentType extends ResolversParentTypes['Query'] = ResolversParentTypes['Query']> = {
  foo?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>,
  bar?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>,
};
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
schema: ./src/schema.tsx
generates:
  ./src/resolvers.types.tsx:
    config:
      avoidOptionals: false
      noSchemaStitching: true
      enumsAsTypes: true
    plugins:
      - typescript
      - typescript-resolvers
require:
  - ../../../../../util/register.js
```

**Expected behavior**

Expect `extend type Query` to merge with `type Query` and generate types properly.

**Environment:**

- OS: macOS Mojave `10.14.6`
- `@graphql-codegen/^1.8.0`: 
- NodeJS: `10.16.0`

**Additional context**

Here is my `schema.tsx` file.

```
import {makeExecutableSchema} from 'graphql-tools';

const schema = makeExecutableSchema({
  typeDefs: [`
    type Query {
      foo: String
    }

    extend type Query {
      bar: String
    }
  `], 

  resolvers: […],
});
```
