### ISSUE TITLE
Generate types for the fields I actually select

### ISSUE THREAD

**Issue by justin-capalbo** [dotansimha/graphql-code-generator#2735]
**Is your feature request related to a problem? Please describe.**

Maybe my queries are too nested, but that's one of the powerful aspects of GraphQL.  I'm coming from apollo-cli's client codegen, which will generate types for every complex/nested type that I'm specifying in my query.  For example, a query like this:

```
query BlogpostQuery($filters: BlogPostFilters) {
    blogPosts(filters: $filters) {
        posts {
            author {
                name 
            }
            body
            datePosted
        }
    }
}
```

I would receive a few types without having to do any kind of nested referencing of types.  These generated types have no reference to the "master" type from the schema, e.g. Pick<BlogPost, "author" | "body" | "datePosted">[].

```
type BlogpostQuery_blogPosts_posts = {
    author: BlogPostsQuery_blogPosts_posts_author;
    body: string;
    datePosted: string;
}

type BlodpostQuery_blogPosts_posts_author = {
    name: string;
}
```

**Describe the solution you'd like**
What this would allow me to do is to simply import the type for the nesting level of the query that I want to work with at that moment (e.g. for defining a callback or a prop for a lower level component), rather than being forced to re-declare a type and "drill down" multiple levels from the parent type (which is defined using a series of nested Pick<T> types).

**Describe alternatives you've considered**
We've had to try things in our project like:
`type PostRecord = BlogPostsQuery["posts"][0];`
But in our opinion this is verbose and unnecessary compared to simply importing a type that's going to be compiled away at build time anwyay (nothing to send to the client, little cost to generate and export).

Has this come up in discussions previously?

**Comment by justin-capalbo** [comment]
I realized I should have included this:

`codegen.yml`
```
overwrite: true
schema: https://path.to.graphql.schema
documents:
  - "src/**/*.tsx"
  - "!src/generated/**/*.*"
config:
  skipTypename: true
  withHooks: true
  withHOC: false
  withComponent: false
generates:
  ./src/generated/types.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
```
