### ISSUE TITLE
typescript-operations: Unknown directive 'client'

### ISSUE THREAD

**Issue by dizel3d** [dotansimha/graphql-code-generator#2736]
`@graphql-codegen/typescript-operations` with `flattenGeneratedTypes: true` fails with an error:
```
    - Unknown directive 'client'.

      /sandbox/document.graphql:5:30
      4 | mutation MyMutation ($file: Blob!) {
      5 |     uploadImage(file: $file) @client
        |                              ^
      6 | }
```

**To Reproduce**

https://codesandbox.io/s/graphql-codegen-issue-template-5wg2v
Run `yarn codegen`

**Document**
```graphql
mutation MyMutation ($file: Blob!) {
    uploadImage(file: $file) @client
}
```

**Schema**
```graphql
scalar Blob

type Mutation {
    uploadImage(file: Blob!): String!
}

type Query {
    getImage: String!
}
```

**Config**
```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      flattenGeneratedTypes: true
```
