### ISSUE TITLE
[Schema Parser?] Extending root operations in schemas is not working if "# import" is used

### ISSUE THREAD

**Issue by eddeee888** [dotansimha/graphql-code-generator#2745]
## Problem
When extending schemas, the `# import ...` at the top of my second schema causes the generation process to fail. This happens for at least `fragment-matcher` and `typescript-graphql-files-modules` plugins.

## Example
For example, I have 2 schemas: `schema.graphql` and `projects.graphql`:

1. My main schema - `schema.graphql`:
```graphql
type Query
type Mutation
type Subscription
```

2. My second schema -`projects.graphql`:
```graphql
# import * from 'schema.graphql'

extend type Query {
    project(id: ID!): Project!
}

extend type Mutation {
    createProject(name: String!): Project!
}

extend type Subscription {
    projectChanges: [Project!]!
}

type Project {
    id: ID!
    title: String!
    description: String!
}
```

3. My `codegen.yml` config file (order of the schemas doesn't seem to matter):
```yaml
overwrite: true
schema: 
  - projects.graphql
  - schema.graphql
  
generates:
  src/webpack/__generated__/types.ts:
    plugins:
      - typescript
      
  src/webpack/__generated__/introspection-result.ts:
    plugins:
      - fragment-matcher

  src/webpack/__generated__/operations.d.ts:
    documents:
      - src/webpack/**/*.graphql
    plugins:
      - typescript-graphql-files-modules
```

Running codegen will give me this error:
```
Error: Type Query must define one or more fields.

    Type Mutation must define one or more fields.

    Type Subscription must define one or more fields.
        at assertValidSchema (/sandbox/node_modules/graphql/type/validate.js:80:11)
        at assertValidExecutionArguments (/sandbox/node_modules/graphql/execution/execute.js:146:35)
        at executeImpl (/sandbox/node_modules/graphql/execution/execute.js:67:3)
        at Object.execute (/sandbox/node_modules/graphql/execution/execute.js:62:35)
        at Object.exports.plugin (/sandbox/node_modules/@graphql-codegen/fragment-matcher/dist/commonjs/index.js:22:
43)
        at Object.executePlugin (/sandbox/node_modules/@graphql-codegen/core/dist/commonjs/execute-plugin.js:32:41)
```

Removing the `# import ...` statement works! But it should not fail the first place I think 🤔 

You can see this behaviour here: [example codesandbox](https://codesandbox.io/s/gcg-18-experiments-v2-uq5he)

Running `yarn gg` should show the errors. Removing the `# import ...` in `projects.graphql` and it works!

## Expected behavior

It should work with or without `# import ...` statements

## Environment
- "@graphql-codegen/cli": "1.8.1"
- "@graphql-codegen/fragment-matcher": "1.8.1"
- "@graphql-codegen/typescript-graphql-files-modules": "^1.8.1"
- "@graphql-codegen/typescript": "1.8.1" ( This actually works! I wonder what the difference is? )
- NodeJS: v10.16.0
