### ISSUE TITLE
flow-operations generates semi exact types

### ISSUE THREAD

**Issue by vasilich6107** [dotansimha/graphql-code-generator#2772]
**Describe the bug**
The generated types are somehow not fully exact

**To Reproduce**
Generate types with flow operaions

1. My GraphQL schema:

```graphql
type Query {
    getReportDefaults: ReportDefaults!
}

type ReportDefaults {
    arrival: Destination
    dateFrom: String
    dateTo: String
    departure: Destination
    type: ReportType
    voyageNumber: String
}

type Destination {
    id: ID!
    name: String!
    type:String!
}
```

2. My GraphQL operations:

```graphql
query getReportDefaults {
        getReportDefaults {
            dateFrom
            dateTo
            voyageNumber
            type
            departure {
                id
                name
                type
            }
            arrival {
                id
                name
                type
            }
        }
    }
```

3. My `codegen.yml` config file:

```yml
overwrite: true
generates:
  src/types/graphql.js:
    schema: {
      "[URL]": {
        headers: {
          Authorization: 'Bearer ...'
        }
      }
    }
    documents:
      - "./src/apollo/queries/reports.js"
    plugins:
      - "flow"
      - "flow-operations"
    config:
      scalars:
        DateTime: string
      skipTypename: false
      nonOptionalTypename: true
      useFlowExactObjects: true
```

**Expected behavior**
```
export type GetReportDefaultsQuery = {|
    ...{| __typename: 'Query' |},
    ...{|
        getReportDefaults: {|
            ...{| __typename: 'ReportDefaults' |},
            ...ReportDefaultsFragment
        |}
    |}
|};

export type ReportDefaultsFragment = {|
    ...{| __typename: 'ReportDefaults' |},
    ...$Pick<ReportDefaults, {| dateFrom: *, dateTo: *, voyageNumber: *, type: * |}>,
    ...{|
        departure: ?{|
            ...{ __typename: 'Destination' },
            ...DestinationFragment
        |},
        arrival: ?{|
            ...{| __typename: 'Destination' |},
            ...DestinationFragment
        |}
    |}
|};
```

**Actual behavior(a lot of pipes are missing)** 
```
export type GetReportDefaultsQuery = {
    ...{ __typename: 'Query' },
    ...{|
        getReportDefaults: {
            ...{ __typename: 'ReportDefaults' },
            ...ReportDefaultsFragment
        }
    |}
};

export type ReportDefaultsFragment = {
    ...{ __typename: 'ReportDefaults' },
    ...$Pick<ReportDefaults, {| dateFrom: *, dateTo: *, voyageNumber: *, type: * |}>,
    ...{|
        departure: ?{
            ...{ __typename: 'Destination' },
            ...DestinationFragment
        },
        arrival: ?{
            ...{ __typename: 'Destination' },
            ...DestinationFragment
        }
    |}
};
```

**Environment:**

- OS: MacOs Catalina
- `@graphql-codegen/...`: 1.8.1
- NodeJS: 10

**Additional context**
