### ISSUE TITLE
improper escaping in string literals

### ISSUE THREAD

**Issue by tyler-johnson** [dotansimha/graphql-code-generator#2779]
**Describe the bug**

Escaped characters in string literals in queries are output directly into the JS template string, which gets interpreted in JS, resulting in a bad GraphQL document.

As an example, we have some endpoints that accept a JSON string and in many cases it's easiest to hardcode this JSON string into the query itself.

**To Reproduce**

1. My GraphQL schema:

```graphql
scalar PermissionQuery

type Query {
  canAccess(permissionQuery: PermissionQuery): Boolean!
}
```

2. My GraphQL operations:

```graphql
query canAccessOrganizations {
  organization: canAccess(permissionQuery: "\"organization:read\"")
  profile: canAccess(permissionQuery: "\"profile:read\"")
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "graphql-codegen.schema.js"
documents: "client/graphql/*.graphql"
generates:
  client/graphql.ts:
    plugins:
      - add: "/* eslint-disable */"
      - "typescript-operations"
      - "typescript"
      - "typescript-urql"
    config:
      withHooks: true
      withHOC: false
      withComponent: false
      preResolveTypes: true
```

**Expected behavior**

Well this is what is produced, which seems fine, but JS escaping rules make it invalid:

```js
export const CanAccessOrganizationsDocument = gql`
    query canAccessOrganizations {
  organization: canAccess(permissionQuery: "\"organization:read\"")
  profile: canAccess(permissionQuery: "\"profile:read\"")
}
    `;
```

The correct output should be:

```js
export const CanAccessOrganizationsDocument = gql`
    query canAccessOrganizations {
  organization: canAccess(permissionQuery: "\\"organization:read\\"")
  profile: canAccess(permissionQuery: "\\"profile:read\\"")
}
    `;
```

Of course, the simple fix for us is to add three escapes into the original query, but if that query were to be run in a GraphQL playground it would be invalid. This why I believe this to be a bug in graphql-codegen.

**Environment:**

- OS: Mac OS X 10.14
- NodeJS: v12.10.0
- "@graphql-codegen/cli": "^1.5.0"
- "@graphql-codegen/add": "^1.5.0"
- "@graphql-codegen/typescript": "^1.5.0"
- "@graphql-codegen/typescript-operations": "^1.5.0"
- "@graphql-codegen/typescript-urql": "^1.5.0"

**Additional context**
