### ISSUE TITLE
Union Type fields of same name with differing types are incorrectly considered invalid

### ISSUE THREAD

**Issue by jefflewis** [dotansimha/graphql-code-generator#2781]
**Describe the bug**
The codegen should allow for the differing type of name between the to union types.

**To Reproduce**
See example at codesandbox.

https://codesandbox.io/s/graphql-codegen-issue-template-hxp3g

1. My GraphQL schema:

```graphql
type Query {
  ListItems: [ItemUnion]
}

union ItemUnion = Product | ProductVariant

type Product {
  id: ID!
  name: String!
}

type ProductVariant {
  id: ID!
  name: String
}
```

2. My GraphQL operations:

```graphql
query ListItems {
    ListItems {
        ... on Product {
            id
            name
        }

        ... on ProductVariant {
            id
            name
        }
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations

```

**Expected behavior**
Successful generation of types.

**Environment:**
- codegen v. 1.8.1
