### ISSUE TITLE
The imported file name is NOT correct with near-operation-file

### ISSUE THREAD

**Issue by ruanyl** [dotansimha/graphql-code-generator#2818]
**Codegen version: 1.8.1**

My document files are named with `module.graphql.ts`

1. My GraphQL schema:

My `codegen.yml` config file:

```yml
schema: ./schema.json
documents: ./src/**/*.graphql.ts
generates:
  ./src/javascript/app/modules/generatedTypes.tsx:
    plugins:
      - typescript
  ./src/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.tsx
      baseTypesPath: ./path/to/generatedTypes.tsx
    plugins:
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: false
      withHOC: false
      withComponent: true
      withMutationFn: false
      documentMode: external
      importDocumentNodeExternallyFrom: near-operation-file
```
In the generated file: `module.generated.tsx`, the import statement is:
```
import * as Operations from './module';
```
but it should be:
```
import * as Operations from './module.graphql';
```
