### ISSUE TITLE
Cannot export as PascalCase, keeps inserting underscores

### ISSUE THREAD

**Issue by tsujp** [dotansimha/graphql-code-generator#2839]
**Describe the bug**
From what I understand from the docs, this option `transformUnderscore: true` should remove the underscore. Hasura uses postgres under the hood and so postgres convention dictates the use of `_` on tables, properties etc. Graphql codegen seems to be putting those underscores into the names of it's types such that `some_column_on_a_table` becomes `Some_Column_On_A_Table` once it's passed through graphql codegen instead of `SomeColumnOnATable`.

**To Reproduce**

1. Spawn a hello world Hasura instance (GitHub for `Hasura`).
2. Introspect and generate types for the schema.
3. Observe types with `_` in them.

```yaml
overwrite: true
schema:
  - https://some.api/schema:
      headers:
        x-hasura-admin-secret: 1234
generates:
  ./src/graphql/types.d.ts:
      config:
        strict: true
        maybeValue: T | null | undefined
        noNamespaces: true
        namingConvention: change-case#pascalCase
        transformUnderscore: true
        immutableTypes: true
        skipTypename: false
      plugins:
        - typescript
        - typescript-operations
        - typescript-compatibility
```

**Comment by dotansimha** [comment]
@tsujp Which version of the codegen do you use? we recently did some fixes related to `transformUnderscore`. Can you please try the latest? 1.8.2
Can you also try:

```
namingConvention:
    typeNames: change-case#pascalCase
    enumValues: change-case#pascalCase
    transformUnderscore: true
```
