### ISSUE TITLE
Support Environment Variables for schema headers in config

### ISSUE THREAD

**Issue by andycmaj** [dotansimha/graphql-code-generator#2864]
Problem is i cannot use codegen against an authenticated server without resorting to javascript schema file.

eg.

```
schema:
  - http://localhost:8080/v1/graphql:
      headers:
        x-hasura-admin-secret: "${env:HASURA_GRAPHQL_ADMIN_SECRET}"
```

would love to be able to specify an env var in the config yml rather than having to create a schema.js to provide the authenticated schema
