### ISSUE TITLE
"Not all operations have an unique name" error with "near-operation-file" preset

### ISSUE THREAD

**Issue by vasilak** [dotansimha/graphql-code-generator#2890]
**Describe the bug**

I am using the 'near-operation-file' preset to generate types next to the files that have the GraphQL operations. When I try to generate the types again though I get the "Not all operations have an unique name" error, presumably because the generated types are not ignored.

**To Reproduce**

- Use the following config with a query in a `.ts` file.
- Generate the types using `@graphql-codegen`.
- Generate the types again.

My `codegen.yml` config file:

```yml
overwrite: true
schema: 'http://localhost:24000/graphql'
documents:
  - './pages/**/*.{ts,tsx}'
  - './components/**/*.{ts,tsx}'
generates:
  ./generated/graphql/types.ts:
    plugins:
      - 'typescript'
  ./:
    preset: 'near-operation-file'
    presetConfig:
      extension: '.gql.types.tsx'
      baseTypesPath: 'generated/graphql/types.ts'
    plugins:
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withHooks: true
hooks:
  afterAllFileWrite:
    - prettier --write
```

**Expected behavior**

It should work and not error.

**Environment:**

- OS: macOS 10.14.5
- `@graphql-codegen`: 1.8.3
- Node: 11.10.1

**Additional context**

Similar issues I could find:

- https://github.com/dotansimha/graphql-code-generator/issues/1537
- https://github.com/dotansimha/graphql-code-generator/issues/2143

**Comment by dotansimha** [comment]
This was already fixed, but in your use case, you are loading the documents on the root level, and it causes validation to run while generating the `./generated/graphql/types.ts` base file.

You should do something like that: 

```yml
overwrite: true
schema: 'http://localhost:24000/graphql'
generates:
  ./generated/graphql/types.ts:
    plugins:
      - 'typescript'
  ./:
    preset: 'near-operation-file'
    documents:
      - './pages/**/*.{ts,tsx}'
      - './components/**/*.{ts,tsx}'
    presetConfig:
      extension: '.gql.types.tsx'
      baseTypesPath: 'generated/graphql/types.ts'
    plugins:
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withHooks: true
hooks:
  afterAllFileWrite:
    - prettier --write
```

If it's in the root level, then while running `generated/graphql/types.ts`, it causes it to pass documents (and it's not necessary there, build it checks it anyway because of the current plugins architecture). 

@vasilak
