### ISSUE TITLE
"prettier --write" hook is not working

### ISSUE THREAD

**Issue by vasilak** [dotansimha/graphql-code-generator#2891]
**Describe the bug**

I am using the 'near-operation-file' preset to generate types next to the files including GraphQL operations. I have also added an `afterAllFileWrite` hook to run prettier on the generated files but prettier seems to be run only on one of the two files that get generated.

I have also tried using an `afterOneFileWrite` hook instead, but the behavior is the same.

**To Reproduce**

- Use the following config.
- Create two `.ts` files each one including a GraphQL query.
- Add some prettier rules to be run on the generated types.
- Generate the types using `@graphql-codegen`.

My `codegen.yml` config file:

```yml
overwrite: true
schema: 'http://localhost:24000/graphql'
documents:
  - './pages/**/*.{ts,tsx}'
  - './components/**/*.{ts,tsx}'
generates:
  ./generated/graphql/types.ts:
    plugins:
      - 'typescript'
  ./:
    preset: 'near-operation-file'
    presetConfig:
      extension: '.gql.types.tsx'
      baseTypesPath: 'generated/graphql/types.ts'
    plugins:
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withHooks: true
hooks:
  afterAllFileWrite:
    - prettier --write
```

**Expected behavior**

The lifecycle hook should be run for all generated files, not just for one of them.

**Environment:**

- OS: macOS 10.14.5
- `@graphql-codegen`: 1.8.3
- Node: 11.10.1

**Additional context**

N/A

**Comment by dotansimha** [comment]
Thanks @vasilak ! 
We'll check that.

**Comment by sibeliuz** [comment]
For me prettier does not work at all:

`overwrite: true
schema: "http://localhost:4000"
documents: null
generates:
  src/types/graphql.ts:
    config:
      interfacePrefix: "I"
      typesPrefix: "I"
      skipTypename: true
      declarationKind: "interface"
      noNamespaces: true
      withHooks: true
    plugins:
      - add: '/* tslint:disable:jsdoc-format */'
      - typescript
      - typescript-operations
      - typescript-compatibility
    hooks:
      afterOneFileWrite:
        - prettier --write
  ./graphql.schema.json:
    plugins:
      - introspection 
`

**Comment by dotansimha** [comment]
Just tested it with our examples in this repo, and it seems like it works. 
I changed some of the prettier rules and ran in again, it seems like new rules are being applied: 

![image](https://user-images.githubusercontent.com/3680083/69496396-75c92f80-0eda-11ea-8af0-a3bf3bd71035.png)


I think it's related to the level/position of your hooks, can you please try putting it in your root-level of your file?

**Comment by dotansimha** [comment]
Closing for now. 
@vasilak feel free to contact us if it's still relevant :)

**Comment by tafelito** [comment]
@dotansimha I just run into this issue. You're correct, it only works if the hook in the root-level position

**Comment by JaffParker** [comment]
Actually, it doesn't work for me on root level...

```yml
overwrite: true
schema: 'http://localhost:8000/graphql'
documents: 'src/**/*.gql'
generates:
  src/__generated__/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
      - add:
          content: '/* eslint-disable */'
    config:
      reactApolloVersion: 2
  ./graphql.schema.json:
    plugins:
      - 'introspection'

hooks:
  afterAllFileWrite:
    - npx prettier --write
```

Tried both with and without `npx`, same result. In another project where I use yarn, it worked like a charm.

**Comment by JaffParker** [comment]
Interestingly, if I move the hook to the file level (because I only need to format the .ts file), change it to `afterOneFileWrite`, it doesn't throw any error if the command is `prettier --write`, even though my prettier isn't global. Obviously, it does nothing. If I make it `npx prettier --write`, it throws an error and does nothing

**Comment by tafelito** [comment]
this seems to be broken again, adding it to the top level or a after the generates, prettier is never running

**Comment by dotansimha** [comment]
@JaffParker please make sure prettier is not ignoring those files... if it's still relevant, can you please report this in a new issue with a reproduction?

**Comment by rpedroni-sf** [comment]
Had the same problem but the reason was quite arbitrary - when using the `typescript-resolvers` plugin, I was using the `config: context` field with bad value.
➡️ Once this was fixed, `prettier` and `eslint` started working again :)

**Comment by WillSquire** [comment]
Not working at all, at any level:

```yml
hooks:
  afterOneFileWrite:
    - eslint --fix
    - prettier --write
```

Not if I run, or both. No error output.
