### ISSUE TITLE
Receiving error: Unknown type "__Schema". after running graphql-code-generator.

### ISSUE THREAD

**Issue by rlindskog** [dotansimha/graphql-code-generator#2911]
**Describe the bug**
When trying to use type `__Schema!`, `graphql-code-generator` throws the following error: `Unknown type "__Schema".` after "Generate".

**To Reproduce**
-  create a schema with the following type:

```graphql
type Project {
  schema: __Schema!
}
```

- run graphql code generator from the above schema.

1. My GraphQL schema:

```graphql
type Project {
  schema: __Schema!
}
```

2. My GraphQL operations:

N/A

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: ./packages/api/src/schema.graphql
documents: packages/**/*.graphql
generates:
  ./packages/api/src/resolvers/types.ts:
    config:
      contextType: ../types#Context
    plugins:
      - typescript
      - typescript-resolvers
  ./packages/app/src/apollo/index.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      gqlImport: apollo-boost#gql
      withHooks: true
      withComponent: false
      withHOC: false
      reactApolloVersion: 3\
```

**Expected behavior**
To generate typescript types from the `__Schema!` type.

**Environment:**

- OS: Mac OS
- `@graphql-codegen/...`: 1.7.0
- NodeJS: 12.9.1

**Additional context**
Attempting to proxy an introspection from another GraphQL endpoint, not 100% it is going to work as expected.
