### ISSUE TITLE
near-operation-file preset should allow for types to be in external package

### ISSUE THREAD

**Issue by willtrking** [dotansimha/graphql-code-generator#2912]
Internally, we package our generated schema types independently of our generated operations and react components.

We'd like to use the `near-operation-file` preset, and it would be nice if it allowed for types to be imported from an external package. Currently doing something like the following:

```
overwrite: true
schema: './node_modules/@internal/gql/dist/schema/*.graphql'
documents: './graphql/**/*.gql.ts'
generates:
  /:
    preset: near-operation-file
    presetConfig:
      extension: .generated.tsx
      baseTypesPath: '@internal/gql'
      folder: generated
    plugins:
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withHooks: true
      withHOC: false
      reactApolloVersion: 3
```

Ends up with imports as follows

`import * as Types from '../../../../../../../@internal/gql';`

I propose adding a new option, `baseTypesPackage` to allow for this use case. Adding a new option rather then re-purposing the existing `baseTypesPath` would ensure no existing uses of that option break.

I'm happy to submit a PR for this.
