### ISSUE TITLE
Mutation HOC does not change "result.loading" value (React)

### ISSUE THREAD

**Issue by Infonautica** [dotansimha/graphql-code-generator#2917]
**Describe the bug**
I use generated HOC, call it from handler like this.props.systemLogin.mutate()
But during HTTP Request lifecycle i get "loading" value as false

**To Reproduce**
Use mutation HOC in React, call it mutate function and check this.props.result.loading value

My `codegen.yml` config file:
```yml
overwrite: true
schema: "http://devadressurl"
documents: "src/graph/**/*.ts"
generates:
  src/typings/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"

```

**Expected behavior**
result.loading value should change to true, right after http request fired

**Environment:**

- OS: Mac OS Catalina
- `@graphql-codegen/...`: 1.8.3
- NodeJS: 10.16.0

**Additional context**
Using recompose
