### ISSUE TITLE
Typescript template immutable types, missing readonly attribute on __typename

### ISSUE THREAD

**Issue by jonaskello** [dotansimha/graphql-code-generator#296]
When I use CODEGEN_IMMUTABLE_TYPES=true I get this output:

```ts
  export type Query = {
    __typename?: "Query";
    readonly tenants: ReadonlyArray<Tenants>;
    readonly plugins: ReadonlyArray<Plugins>;
  };
```

I guess the `__typename` property should also have a `readonly` attribute in this case?

**Comment by dotansimha** [comment]
Fixed in 0.9.1 :) Thanks @jonaskello !

**Comment by jonaskello** [comment]
I tried 0.9.1 just now and it seems I get the same output as with 0.9.0. The `readonly` flag is missing on the `__typename` fields. At least I think I'm using 0.9.1, it says so in my package.json and yarn.lock, but there is no `gql-gen --version` flag so I cannot be sure :-).

**Comment by lookfirst** [comment]
This is still an issue: v1.6.1

```
generates:
  src/gql/GeneratedServerTypes.ts:
    config:
      contextType: ./Context#Context
      useIndexSignature: true
      immutableTypes: true
      avoidOptionals: false
      nonOptionalTypename: true
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-resolvers"
```

```
export type ResultCursor = {
  __typename: 'ResultCursor',
  readonly edges: ReadonlyArray<Maybe<Edge>>,
  readonly pageInfo: PageInfo,
  readonly totalCount: Scalars['Int'],
};
```
