### ISSUE TITLE
Add option to `typescript-graphql-files-modules` to generate complete paths

### ISSUE THREAD

**Issue by pietdevries94** [dotansimha/graphql-code-generator#2973]
Currently the modules generated for the files have a wildcard as path. Example: `declare module '*/Project.gql' {`

I would like an option to generate the files with the absolute path (`src/graphql/queries/Project.gql`). This way auto-imports will work correctly in VS Code

**Comment by dotansimha** [comment]
I implemented it in this PR: https://github.com/dotansimha/graphql-code-generator/pull/3010

With these changed, you should be able to set now `relativeToCwd: true` to generate a complete path to CWD, and you can customize the prefix (default for `*/`).

@pietdevries94

**Comment by dotansimha** [comment]
Available in 1.9.0

**Comment by tyankatsu0105** [comment]
@dotansimha 
How can I set the option for typescript-files-modules?

**Comment by vhiairrassary** [comment]
@tyankatsu0105 For me it works using something like:
```yaml
generates:
  src/types/graphql.d.ts:
    plugins:
      - 'typescript-graphql-files-modules'

    config:
      relativeToCwd: true
```
