### ISSUE TITLE
[ts-resolvers] Typing of a lazy resolver

### ISSUE THREAD

**Issue by kettanaito** [dotansimha/graphql-code-generator#2974]
**Describe the bug**
 

I have a type `Project` that has a `size` field. When `Project` resolves, it returns a number as a value of the `size` field. However, when I query the `size` field I want to apply an additional resolver to it, to optionally format the value. Formatted value type is String, not Int, therefore there is a type conflict between the intermediate resolved state (from `Project`) and the end state queried by the client (formatted string).

**To Reproduce**

1. My GraphQL schema:

```graphql
enum SizeFormat {
  KB
  MB
}

type FormattableSize {
  size(format: SizeFormat): String!
}

type Project {
  size: FormattableSize
}

type Query {
  project(): Project!
}
```

2. My GraphQL operations:

```graphql
query Example {
  project {
    size # should return 10
  }
}

query AnotherExample {
  project {
    size(format: "MB") # should return "10MB"
  }
}
```

3. My `codegen.yml` config file:

```yml
schema: src/server/schema/**/*.gql
documents: src/client/**/*.gql
generates:
  graphql.schema.ts:
    config:
      contextType: src/server/schema/types/Context#Context
    plugins:
      - typescript
      - typescript-operations
      - typescript-resolvers
```

**Expected behavior**

The `size` field should have an intermediate type signature of `size: number` for internal purposes, and `size: FormattableSize` for public ones.

**Environment:**

- OS: macOS Mojave (10.14.6)
- `@graphql-codegen/...`: 1.7.0
- NodeJS: v10.16.3

**Additional context**

I may be doing such kind of field in a wrong way, so please don't treat this issue as the library's issue per say. I'd be very thankful for any kind of guidance, as I know that such behavior should be possible. Thanks.
