### ISSUE TITLE
How to automatically generate types for hooks' result data field?

### ISSUE THREAD

**Issue by Tbaut** [dotansimha/graphql-code-generator#2977]
Hello

I'm using graphql codegen hooks, which results are of the type: ApolloReactCommon.QueryResult, meaning it's an object that has data, loading and error fields.

Most generally, I'll use the data in other components, where I need to define its type. I currently need to write something like this to get data type:

```ts
type MyPost = MyPostQueryHookResult['data']
```

I would have expected to get this MyPost type created for me. Is there a way to have it generated automatically?

My config:
```yaml
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withHooks: true
```

Note, this is a cross post [from SO](https://stackoverflow.com/questions/58733198/can-graphql-codegen-automatically-generate-types-for-hooks-result-data-field) where I was unlucky, I'll update the question as soon as I get an answer.
