### ISSUE TITLE
 Unable to find any GraphQL type definitions for the following pointers: -"src/**/*.graphql"

### ISSUE THREAD

**Issue by seyaobey** [dotansimha/graphql-code-generator#2979]
**Describe the bug**
I have created a brand new react-native application and I, now, attempt to generate graphql schema from my backend `https://umoja-apps.herokuapp.com/graphql` where it is exposed.
I entered
```
$ graphql-codegen init
```
and followed the steps from the wizard, which produced the below `codegen.yml`:
```
overwrite: true
schema: "https://umoja-apps.herokuapp.com/graphql"
documents: "src/**/*.graphql"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
  ./graphql.schema.json:
    plugins:
      - "introspection"

```

This is the `package.json` script I should run to generate the schema:
```
"schema": "graphql-codegen --config codegen.yml"
```

But the above command fails with the following errors:
```
✖src/generated/graphql.tsx
    Error: Unable to find any GraphQL type definitions for the following pointers: -"src/**/*.graphql"

...

✖ ./graphql.schema.json
    Error: Unable to find any GraphQL type definitions for the following pointers: -"src/**/*.graphql"
```

My backend is a `nestjs` application which exposes a `graphql` interface. My `schema.gql` file has been generated by `type-graphql` which I paste below

1. My GraphQL schema:

```graphql
# -----------------------------------------------
# !!! THIS FILE WAS GENERATED BY TYPE-GRAPHQL !!!
# !!!   DO NOT MODIFY THIS FILE BY YOURSELF   !!!
# -----------------------------------------------

"""Date custom scalar type"""
scalar Date

type Mutation {
  create_user(user: UserInput!): User!
  create_pofficer(pofficer: POfficerCreateInput!): POfficer!
  create_incident(incident: TIncidentInput!): TIncident!
  add_incident_type(incident_type: TIncidentTypeInput!): TIncidentType!
}

type POfficer {
  _id: ID!
  userid: ID!
  user: User!
}

input POfficerCreateInput {
  name: String!
  surname: String!
  phone: String!
}

type Query {
  users: [User!]!
  pofficers: [POfficer!]!
  incidents: [TIncident!]!
  incident_types: [TIncidentType!]!
}

type TIncident {
  _id: ID!
  createdAt: Date!
  incidenttype_id: ID!
  pofficer_id: ID!
  toffender_id: ID
  toffender_phone: String!
  carnumber: String!
  incident_status: String!
  pofficer: POfficer!
  toffender: User!
  incident_type: TIncidentType!
}

input TIncidentInput {
  incidenttype_id: ID!
  pofficer_id: ID!
  toffender_phone: String!
  carnumber: String!
}

type TIncidentType {
  _id: ID!
  name: String!
  description: String
}

input TIncidentTypeInput {
  name: String!
  description: String
}

type User {
  _id: ID!
  name: String!
  surname: String!
  email: String
  phone: String!
}

input UserInput {
  name: String!
  surname: String!
  email: String!
  phone: String!
}


```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "https://umoja-apps.herokuapp.com/graphql"
documents: "src/**/*.graphql"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
  ./graphql.schema.json:
    plugins:
      - "introspection"

```

**Expected behavior**
Should generate typescript types from remote schema

**Environment:**

- OS: Macbook pro high sierra
- `@graphql-codegen/cli`: 1.8.3 
- NodeJS: v12.10.0
