### ISSUE TITLE
LazyQueryHookOptions type is not exported by apollo-client

### ISSUE THREAD

**Issue by capaj** [dotansimha/graphql-code-generator#2999]
**Describe the bug**
I'd like to generate `typescript-react-apollo` hooks, but the output is not correct TS. It tries to define ouput of lazy query hooks as `ApolloReactHooks.LazyQueryHookOptions`, but the problem is that type is not exported.  
``

**To Reproduce**
Steps to reproduce the behavior: just generate

1. My GraphQL schema:

```graphql
not relevant for this ticket
```

2. My GraphQL operations:

```graphql
 query listTags {
    tags {
      id
      name
    }
  }
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: 'gqlSchemas/private.graphql'
documents: 'front-end/**/*.gql'
generates:
  front-end/src/graphql/gqlPrivateSchema.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
  front-end/src/graphql/gqlPrivateSchemaFragments.tsx:
    plugins:
      - fragment-matcher
config:
  withHooks: true
  withHOC: false
  withComponent: false
  apolloReactHooksImportFrom: 'react-apollo'
  reactApolloVersion: 3
  scalars:
    EmailAddressWithTLD: string
    NonNegativeFloat: number
    NonNegativeInt: number
    PositiveInt: number
    DateTime: string

hooks:
  afterOneFileWrite:
    - prettier --write

```

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**
