### ISSUE TITLE
Enums that are only undescore do not properly generate types in the Typescript Plugin

### ISSUE THREAD

**Issue by ChrisW-B** [dotansimha/graphql-code-generator#3027]
**Describe the bug**
When generating types from an enum such as 
```graphql
enum EnumType {
  A
  D
  MH
  MF
  _
  SF
}
```
the typescript plugin fails to correctly declare enums, ommiting the solitary underscore, instead generating

```
export enum EnumType {
  A = 'A',
  D = 'D',
  Mh = 'MH',
   = '_',
  Sf = 'SF'
}
```
which results in an `Unexpected Token` error

**To Reproduce**
- create schema with enum containing value `_`
- use `@graphql-codegen/typescript` to generate a types file
- enum is missing key in generated types

1. My GraphQL schema:

```graphql
enum EnumType {
  A
  D
  MH
  MF
  _
  SF
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: ${API_QUERY_URL} 
documents: ./src/**/*.gql
generates:
  ./schema.graphql:
    plugins:
      - schema-ast

  ./src/schemas/fragments/controlFragmentTypes.json:
    schema: 
    plugins:
      - fragment-matcher

  ./src/schemas/dataModel/control.tsx:
    plugins:
      - typescript

  ./src:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: schemas/dataModel/control.tsx
      extension: .generated.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: true
      withComponent: false
      withHOC: false
      documentMode: external
      importDocumentNodeExternallyFrom: 'near-operation-file'
      addDocBlocks: false
```

**Expected behavior**

enum key should be declared, likely as `_`
**Environment:**

- OS: 
-     `"@graphql-codegen/cli": "^1.8.3",`
   ` "@graphql-codegen/fragment-matcher": "^1.8.3",`
    `"@graphql-codegen/near-operation-file-preset": "^1.8.3",`
    `"@graphql-codegen/schema-ast": "^1.8.3",`
    `"@graphql-codegen/typescript": "^1.8.3",`
    `"@graphql-codegen/typescript-operations": "^1.8.3",`
    `"@graphql-codegen/typescript-react-apollo": "^1.8.3",`
- NodeJS:  v12.13.1 

**Additional context**

**Comment by ardatan** [comment]
`_` is used in snake case like `Snake_Case`. So codegen assumes it is snake cased name. In that case, it'd be better to exclude enums to be pascal cased which is default case in codegen.
https://graphql-code-generator.com/docs/plugins/typescript#usage-example-keep
```yml
config:
  namingConvention:
    enumValues: keep
```
