### ISSUE TITLE
[Federation] can't generate types when federation config is set to true

### ISSUE THREAD

**Issue by Novalis15** [dotansimha/graphql-code-generator#3033]
**Describe the bug**
When federation config is set to true, `graphql-codegen --config codegen.yml` results in an error stating, that codegen was unable to merge GraphQL directive "requires" (See picture below).

**To Reproduce**
Get a copy of the [Apollo-Federation-Demo](https://github.com/apollographql/federation-demo) and initialize every service with graphql-codegen. Create a codegen.yml file as stated below and try to generate types.

My `codegen.yml` config file:

```yml
overwrite: true
schema: "http://localhost:<depending on the Service: 4001, 4002, 4003, 4004>/graphql"
documents: null
generates:
  generated/graphql-types.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
    config:
      federation: true
```

**Expected behavior**
TypeScript types will be generated.

**Environment:**

- OS: Windows 10 Enterprise
- graphql-codegen cli + plugins are all v. 1.9.0
- NodeJS: v 12.13.0

**Additional context**
![generate federation types error](https://user-images.githubusercontent.com/18482238/69750606-6a316f00-114d-11ea-8747-ce92676a45be.png)

**Comment by Otard95** [comment]
+1
OS: Ubuntu 18.04.3 LTS
Same config, same versions, same output.

**Comment by ardatan** [comment]
@Otard95 @Novalis15 Could you remove `federation: true` and try again?

**Comment by Otard95** [comment]
Removing `federation: true` it runs like a charm. However After testing the demo provided and seeing that is worked, it possible my issue has a different source. I'll investigate and get back to you.

**Comment by ardatan** [comment]
@Otard95 In that case, you wouldn't get correct typings for resolvers. Until it gets fixed, I recommend to point actual schema files instead of URL endpoint.

**Comment by Otard95** [comment]
```
overwrite: true
schema: 
  'src/schema/**/*.ts':
    noRequire: true
generates:
  src/generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
    config:
      federation: true
```
Does seem to do the trick.

**Comment by Novalis15** [comment]
As @Otard95 mentioned above, referencing the schema directly let graphql-codegen generate types:

```yml
overwrite: true
schema: './schema.ts'
generates:
  generated/graphql-types.ts:
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
    config:
      federation: true
```

with schema.ts being:
```typescript
import { gql } from "apollo-server";

const typeDefs = gql`
extend type Query {
  me: User
}

type User @key(fields: "id") {
  id: ID!
  name: String
  username: String
}
`;

export default typeDefs
```
