### ISSUE TITLE
Migrating from 0.18.2 to 1.9.1 Cannot find name '*Variables', '*Query', etc

### ISSUE THREAD

**Issue by kuncevic** [dotansimha/graphql-code-generator#3045]
**Describe the bug**
Getting app run time errors (ng start):
```
519   export class GetCourseGQL extends Apollo.Query<GetCourseQuery, GetCourseQueryVariables> {
../graphql/index.ts:519:66 - error TS2304: Cannot find name 'GetCourseQueryVariables'.

519   export class GetCourseGQL extends Apollo.Query<GetCourseQuery, GetCourseQueryVariables> {
../graphql/index.ts:536:51 - error TS2304: Cannot find name 'GetCoursesQuery'.

536   export class GetCoursesGQL extends Apollo.Query<GetCoursesQuery, GetCoursesQueryVariables> {
../graphql/index.ts:536:68 - error TS2304: Cannot find name 'GetCoursesQueryVariables'.

536   export class GetCoursesGQL extends Apollo.Query<GetCoursesQuery, GetCoursesQueryVariables> {
```

**To Reproduce**
```
I had this deps:
    "graphql-code-generator": "^0.18.2",
    "graphql-codegen-apollo-angular-template": "^0.18.2",
    "graphql-codegen-fragment-matcher": "^0.18.2",
    "graphql-codegen-introspection-template": "^0.18.2",
```

that gets changed in to that:
```
    "@graphql-codegen/cli": "^1.9.1",
    "@graphql-codegen/fragment-matcher": "^1.9.1",
    "@graphql-codegen/introspection": "^1.9.1",
    "@graphql-codegen/typescript": "^1.9.1",
    "@graphql-codegen/typescript-apollo-angular": "^1.9.1"
```

and the config that didn't change:
```
schema:
  - "/graphql/schema.json"
overwrite: true
documents:
  - "/graphql/query/*.graphql"
config: {}
generates:
    graphql/index.ts:
    config: {}
    plugins:
      - fragment-matcher
      - "typescript-common"
      - "typescript-client"
      - "typescript-apollo-angular"
require: []
```

schema.json:
[schema.txt](https://github.com/dotansimha/graphql-code-generator/files/3903175/schema.txt)

**Expected behavior**
The error should not take place

**Environment:**

Node: 11.15.0
OS: darwin x64
@graphql-codegen/cli: 1.9.1

**Additional context**
With `git diff` I noticed this change:
```
-export class GetCoursesGQL extends Apollo.Query<
-  GetCourses.Query,
-  GetCourses.Variables
-> {
-  document: any = gql`
+    ${SubjectFragmentDoc}
+${GroupL0FragmentDoc}`;
+
+  @Injectable({
+    providedIn: 'root'
+  })
+  export class GetCourseGQL extends Apollo.Query<GetCourseQuery, GetCourseQueryVariables> {
+    document = GetCourseDocument;
+    
+  }
```
as you can see `GetCourses.Query` became `GetCourseQuery` and `GetCourses.Variables` became `GetCourseQueryVariables` that causing the problem as in the generated code I've got things like 
```
export namespace GetCourses {
  export type Variables = {
    id: string;
  }
```
