### ISSUE TITLE
1.9.1 Duplicate identifiers when using typescirpt plugin

### ISSUE THREAD

**Issue by kuncevic** [dotansimha/graphql-code-generator#3046]
**Describe the bug**
I just added a typescript plugin and start getting duplicate identifier errors all over the place

Duplicate identifier 'Maybe'
Duplicate enums
Duplicate interfaces

**To Reproduce**
Add Typescript plugin
`yarn add -D @graphql-codegen/typescript`
run codegen

codegen.yaml
```
schema:
  - "graphql/schema.json"
overwrite: true
documents:
  - "graphql/query/*.graphql"
config: {}
generates:
  graphql/index.ts:
    config:
    globalNamespace: false
    skipTypename: true
    namingConvention:
      typeNames: change-case#pascalCase
      enumValues: keep
    plugins:
      - 'typescript'
      - fragment-matcher
      - "typescript-common"
      - "typescript-client"
      - "typescript-apollo-angular"

require: []

```

schema.json:
[schema.txt](https://github.com/dotansimha/graphql-code-generator/files/3903175/schema.txt)

**Expected behavior**
Should not produce duplicates

**Environment:**

- Node: 11.15.0
- OS: darwin x64
- @graphql-codegen/cli: 1.9.1
