### ISSUE TITLE
Unable to find field on near-operation-file plugin

### ISSUE THREAD

**Issue by gabrielsch** [dotansimha/graphql-code-generator#3050]
**Describe the bug**
When upgrading to graphql-code-generator 1.8+, near-operation-file-plugin doesn't work anymore. Even though the other generators (schema, typescript-operations) are still working, I don't know how to describe it better because the error is too generic.

```
  ✔ Parse configuration
  ❯ Generate outputs
    ✔ Generate types/introspection-result.ts
    ✔ Generate types/types.ts
    ❯ Generate to . (using EXPERIMENTAL preset "near-operation-file")
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Unable to find field "author" on type "VendorUser"!


 Found 1 error

  ✖ .
    Error: Unable to find field "author" on type "VendorUser"!
```

You can see that it doesn't find the field `author` on type `VendorUser`, but this field doesn't even exist and is not being called on this type.

**To Reproduce**
Upgrade to 1.8+, then run graphql-codegen.

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
schema: http://localhost:4000

generates:
  types/introspection-result.ts:
    plugins:
      - "fragment-matcher"

  types/types.ts:
    plugins:
      - "typescript"
      - "typescript-operations"

    config:
      typesPrefix: I
      immutableTypes: false
      skipTypename: false
      avoidOptionals: true
      nonOptionalTypename: true

  .:
    schema: ./data/schema.json
    documents: "lib/{queries,mutations}/**/*.ts"
    preset: near-operation-file

    presetConfig:
      extension: .generated.ts
      baseTypesPath: ./types/types.ts
      avoidOptionals: true

    plugins:
      - typescript-operations

    config:
      typesPrefix: I
      avoidOptionals: true
      nonOptionalTypename: true
```

**Expected behavior**

**Environment:**

- OS: MacOS
- `@graphql-codegen/1.9`: 
- NodeJS: 13.1.0

**Additional context**
