### ISSUE TITLE
gql not parsed when filename contains [brackets] used in Next.js dynamic routing

### ISSUE THREAD

**Issue by msheakoski** [dotansimha/graphql-code-generator#3058]
**Describe the bug**
gql tags are not parsed by graphql-code-generator when they are located in files or directories that use [Next.js's dynamic filesystem routing conventions](https://nextjs.org/docs#dynamic-routing) such as `pages/[directory]/[mypage].tsx` (basically path contains brackets)

**To Reproduce**
1. create a file `src/pages/[directory]/[mypage].tsx`
2. add a simple query such as
```javascript
gql`query GetDogs { dogs }`
```
3. run graphql-code-generator

Here is a CodeSandbox reproduction:

[![Edit graphql-code-generator](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/graphql-code-generator-el71s?fontsize=14&hidenavigation=1&theme=dark)

**My GraphQL schema:**

```graphql
type Query {
  dogs: [String!]!
}
```

**My `codegen.yml` config file:**

```yaml
schema: src/type-defs.ts
generates:
  src/hooks-generated.tsx:
    documents:
      - src/**/*.ts
      - src/**/*.tsx
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      withComponent: false
      withHOC: false
      withHooks: true
```

**Expected behavior**
`src/hooks-generated.tsx` should contain types for the GetDogs query if it was in a path containing brackets.

I believe this is the same issue that Next.js encountered with Prettier not being able to handle paths with brackets. They ended up having to use [shell-quote](https://www.npmjs.com/package/shell-quote) to properly escape the paths, something about it interfering with globbing maybe?

[Here is a file showing how Next.js fixed it.](https://github.com/zeit/next.js/blob/canary/lint-staged.config.js)

**Environment:**

- OS: MacOS Catalina
- `@graphql-codegen/...`: 1.9.1
- NodeJS: 13.2.0
