### ISSUE TITLE
Nested object in fragment unexpectedly not optional

### ISSUE THREAD

**Issue by KieranHarper** [dotansimha/graphql-code-generator#3060]
**Describe the bug**
I have an entity that has optional entities as fields, and this is reflected in the type generated for that entity. However if I use a fragment to query, then the type generated for the fragment loses the ? and no longer matches.

Unless I'm misunderstanding something, I would expect a fragment that fully specifies all the fields of an entity to exactly match the type generated for the field itself.

**To Reproduce**

1. My GraphQL schema:

```graphql
type Address {
  street: String!
  suburb: String!
}

type User {
  id: String!
  address: Address # <-- optional
}

type Query {
  user(id: String!): User
}

schema {
  query: Query
}
```

2. My GraphQL operations:

```graphql
fragment AddressFields on Address {
  street
  suburb
}

fragment UserFields on User {
  id
  address {
    ...AddressFields
  }
}

query getUser($id: String!) {
  user(id: $id) {
    ...UserFields
  }
}
```

3. My `codegen.yml` config file:

```yml
schema: "schema.graphql"
documents: "operations.graphql"
generates:
  types.ts:
    - typescript
    - typescript-operations:
        preResolveTypes: true
        dedupeOperationSuffix: true
    - typescript-react-apollo:
        reactApolloVersion: 2
        withHooks: true
        withHOC: false
        withComponent: false
```

4. Minimal example that will complain because of type mismatching:
```typescript
import { User, UserFieldsFragment } from "./types";

const userMapper = (user: User): UserFieldsFragment => {
  return user;
};
```

tsc says:
```
error TS2322: Type 'User' is not assignable to type 'UserFieldsFragment'.
Property 'address' is optional in type 'User' but required in type 'UserFieldsFragment'.
```

**Expected behavior**
For `UserFieldsFragment` to declare `address` as ?

**Environment:**

- OS: MacOS Mojave
- `@graphql-codegen/...`: 1.9.1
- NodeJS: 11.13.0
