### ISSUE TITLE
Minor naming inconsistency

### ISSUE THREAD

**Issue by tobias-kuendig** [dotansimha/graphql-code-generator#3080]
Given the following query:

```qraphql
query tree($parent: Int!) {
    systemTree(parent: $parent) {
        ...fields
    }
}
```

using this config:

```yml
overwrite: true
schema: "schema/*.graphql*"
documents: "*.gql"
config:
    declarationKind: 'interface'
generates:
    src/common/graphql/types.d.ts:
        config:
            preResolveTypes: true
        plugins:
        - "typescript"
        - "typescript-operations"
```

The following types are generated:

```ts
export type TreeQuery = { /* ... */ }

export type TreeQueryVariables = {
  parent: Scalars['Int']
};

export interface QuerySystemTreeArgs {
  parent: Scalars['Int']
}
```

It seems like the `query` uses a postfix `TreeQuery` where the arguments use a prefix `QuerySystemTreeArgs`. 

It would be nice if this naming schema was the same both times:

```
TreeQuery
TreeQueryVariables
SystemTreeQueryArgs
```

Is this configurable?
