### ISSUE TITLE
Make near-operation-file language agnostic

### ISSUE THREAD

**Issue by micimize** [dotansimha/graphql-code-generator#3091]
**Problem**
I want to use `near-operation-file` for dart type generation, but `baseTypesPath` generates a js-specific import.

**Solution**
It could be made language agnostic by offering an `importTemplateString` config that could look something like
```js
`import "${baseTypesPath}" as ${importTypesNamespace}`
// or for simply overriding with a literal
`import 'package:my_package/base_types.dart';` // dart absolute import
```

**Comment by dotansimha** [comment]
You are right, we should do that :) 
Which plugin are you trying to use with that?

**Comment by micimize** [comment]
@dotansimha I'm reworking [graphql-to-dart](https://github.com/micimize/graphql-to-dart) to work via `near-operation-file`

**Comment by micimize** [comment]
We could use a simple template interpolation helper:
```javascript
function interpolateTemplate(template, params) {
  const names = Object.keys(params);
  const vals = Object.values(params);
  return new Function(...names, `return \`${template}\`;`)(...vals);
}
interpolateTemplate('${foo} bar', { foo: 'biz' })
```

**Comment by micimize** [comment]
Hacking around this with `add` for now
```yaml
      - add: |-
          // GENERATED CODE - DO NOT MODIFY BY HAND

          import 'package:savvy_app/graphql/schema.dart';
          /*
      - add: 
          placement: 'content'
          content: '*/'
```
