### ISSUE TITLE
Unexpected TS error on generated hook

### ISSUE THREAD

**Issue by carlosherrera1113** [dotansimha/graphql-code-generator#3101]
**Describe the bug**
Having an issue with the generated hook. I should be able to pass to the hook the necessary options as arguments as described [here](https://www.apollographql.com/docs/react/api/react-hooks/#options-2). However, typescript is throwing the error:  Expected 0-1 arguments, but got 2. ts(2554). 

1. My GraphQL schema:

```graphql
type Query {
  feed(filter: String, skip: Int, first: Int, orderBy: LinkOrderByInput): Feed!
}

type Mutation {
  post(url: String!, description: String!): Link!
  signUp(email: String!, password: String!, name: String!): AuthPayload!
  login(email: String!, password: String!): AuthPayload!
  vote(linkId: ID!): Vote!
}

type Feed {
  links: [Link!]!
  count: Int!
}

type AuthPayload {
  token: String!
  user: User!
}

type User {
  id: ID!
  name: String!
  email: String!
  links: [Link!]
}

type Link {
  id: ID!
  description: String!
  url: String!
  postedBy: User
  votes: [Vote!]
}

type Subscription {
  newLink: Link!
  newVote: Vote!
}

type Vote {
  id: ID!
  link: Link
  user: User
}

enum LinkOrderByInput {
  description_ASC
  description_DESC
  url_ASC
  url_DESC
  createdAt_ASC
  createdAt_DESC
}
```

2. My GraphQL operations:

```graphql
const POST_MUTATION = gql`
mutation Post($description: String!, $url: String!) {
    post(description: $description, url: $url) {
      url
      postedBy {
          name
      }
      id
      description
    }
  }
`;
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "http://localhost:4000"
documents: "./src/components/**/*.{ts,tsx}"
generates:
  src/generated/graphql.tsx:
      plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
      config:
        withHooks: true
        withHOC: false
        withComponent: false
```

**Expected behavior**

I should be able to pass whatever options necessary without typescript throwing an error.

```javascript
const [postMutation] = usePostMutation(POST_MUTATION, { onCompleted: () => history.push('./') });
```

**Environment:**

- OS: MacOS Catalina
- "@graphql-codegen/cli": "^1.8.2",
    "@graphql-codegen/typescript": "1.8.2",
    "@graphql-codegen/typescript-operations": "1.8.2",
    "@graphql-codegen/typescript-react-apollo": "1.8.2"
- NodeJS: v10.16.0

**Additional context**

<img width="1069" alt="Screen Shot 2019-12-09 at 6 33 14 PM" src="https://user-images.githubusercontent.com/46267105/70484756-748b2b80-1ab2-11ea-9350-9322b980bf03.png">
