### ISSUE TITLE
import-types-preset prefixes all types (react-apollo)

### ISSUE THREAD

**Issue by LTMXcitrus** [dotansimha/graphql-code-generator#3105]
**Describe the bug**

It clearly seems to be related to https://github.com/dotansimha/graphql-code-generator/issues/2742. But as the OP says it should be resolved, I made the decision to create a new issue.

When I migrate from 1.7.0 to 1.9.1, all types in the generated graphql.tsx are prefixed with the 'Types' (default value of presetConfig.importTypesNamespace).

Before, only my own types were prefixed but not the generated typed (**Query, **QueryVariables).

**To Reproduce**

1. My GraphQL schema:

```graphql
type FinancialPeriod {
  id: ID!
  startDate: String!
  endDate: String!
  duration: Int!
  incomeStatement: IncomeStatement!
  tva: Tva!
}
```

2. My GraphQL operations:

```graphql
query FinancialPeriods($structureId: ID!) {
  financialPeriods(structureId: $structureId) {
    ...financialPeriodFields
  }
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: '../gateway/schema/schema.graphql'

react-plugins: &react-plugins
  - add: |
      /* tslint:disable */
      /* eslint-disable */
  - typescript-operations
  - typescript-react-apollo

config:
  scalars:
    JSON: '{ [key: string]: any }'
generates:
  packages/types/src/generated/types.ts:
    plugins:
      - typescript
  packages/app/src/generated/graphql.tsx:
    documents: packages/app/src/**/*.graphql
    config:
      withHooks: true
      withMutationOptionsType: true
      withComponent: false
      withHOC: false
    preset: import-types
    presetConfig:
      typesPath: '@fa-metier/types'
    plugins: *react-plugins
  packages/admin/src/generated/graphql.tsx:
    documents: packages/admin/src/**/*.graphql
    config:
      withHooks: true
      withMutationOptionsType: true
      withComponent: false
      withHOC: false
    preset: import-types
    presetConfig:
      typesPath: '@fa-metier/types'
    plugins: *react-plugins
```

**Expected behavior**

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**

    "@graphql-codegen/cli": "^1.9.1",

    "@graphql-codegen/plugin-helpers": "^1.9.1",

    "@graphql-codegen/import-types-preset": "^1.9.1",

    "@graphql-codegen/introspection": "1.9.1",

    "@graphql-codegen/near-operation-file-preset": "^1.9.1",

    "@graphql-codegen/typescript": "1.9.1",

    "@graphql-codegen/typescript-operations": "1.9.1",

    "@graphql-codegen/typescript-react-apollo": "1.9.1",

**Comment by dotansimha** [comment]
`import-types` assumes that you are creating importing all types from the external file. it means that `typescript` and `typescript-operations` should be together, and `ts-react-apollo` should executed with the preset:

```
schema: schema.graphql
documents: document.graphql

react-plugins: &react-plugins
  - add: |
      /* tslint:disable */
      /* eslint-disable */
  - typescript-react-apollo

config:
  scalars:
    JSON: '{ [key: string]: any }'
generates:
  ./generated/types.ts:
    plugins:
      - typescript
      - typescript-operations
  ./generated/graphql.tsx:
    config:
      withHooks: true
      withMutationOptionsType: true
      withComponent: false
      withHOC: false
    preset: import-types
    presetConfig:
      typesPath: './types'
    plugins: *react-plugins
```

If someone wants to improve this behaviour, feel free to open a PR :)
