### ISSUE TITLE
import-types-preset doesn't work with typescript-resolvers plugin

### ISSUE THREAD

**Issue by mgustus** [dotansimha/graphql-code-generator#3106]
**Describe the bug**
When using `import-types` with `typescript-resolvers` plugin, the corresponding `Types` import is created in the generated file, but the imported variable is never used.

**To Reproduce**

Reproduced here:
https://codesandbox.io/s/mik-graphql-codegen-issue-template-wdr7w

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
        email
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
overwrite: true
generates:
  graphql-types.ts:
    plugins:
      - typescript
  graphql-resolvers.ts:
    preset: import-types
    presetConfig:
      typesPath: ./graphql-types
    plugins:
      - typescript-resolvers
```

4. Generated code:

Result of running codegen -> broken code. The type `User` doesn't exist. `Types.User` should be used instead of `User`.
```typescript
import * as Types from './graphql-types';

export type ResolversTypes = {
  User: ResolverTypeWrapper<User>
};
```

**Expected behavior**
`Types.User` should be used instead of `User` in `graphql-resolvers.ts`.
