### ISSUE TITLE
Wrong typings for React Hooks

### ISSUE THREAD

**Issue by judehunter** [dotansimha/graphql-code-generator#3121]
**Describe the bug**
`baseOptions: ReactApolloHooks.QueryHookOptions<PersonQueryVariable>` (described bellow) has wrong type parameters. Intellisense shows that the first parameter for `QueryHookOptions` is `TData` and the second one is `TVariables`
Obviously, the first parameter should be the query type:
```ts
baseOptions: ReactApolloHooks.QueryHookOptions<PersonQuery, PersonQueryVariables>
```

**Reproduce:**
Given a query:
```gql
query person($handle: String!){
  person(handle: $handle){
    name
  }
}
```
The following types are generated:
```ts
export type Person = {
  name: Scalars['String']
}

export type PersonQueryVariables = {
  handle: Scalars['String']
};

export type PersonQuery = ({ __typename?: 'Query' } & { person: Maybe<({ __typename?: 'Person' } & Pick<Person, 'name'>)> });

export const PersonDocument = gql`
  query person($handle: String!) {
    person(handle: $handle) {
      name
    }
  }
`;

export function usePersonQuery(
  baseOptions?: ReactApolloHooks.QueryHookOptions<PersonQueryVariables>
) {
  return ReactApolloHooks.useQuery<PersonQuery, PersonQueryVariables>(PersonDocument, baseOptions);
}
```

Intellisense shows an incompatible types error, because it assumes `baseOptions` is of type
```ts
ReactApolloHooks.QueryHookOptions<PersonQueryVariables, Record<string, any>>
```
because the first type parameter is omitted in the generated code.

**Expected behavior**
The generated code should type `baseOptions` correctly (as mentioned above)

**Environment:**

- OS: W10
```json
"@graphql-codegen/cli": "^1.9.1",
"@graphql-codegen/typescript": "^1.0.0",
"@graphql-codegen/typescript-operations": "^1.0.0",
"@graphql-codegen/typescript-react-apollo": "^1.0.0"
```
- NodeJS: v11.13.0

codegen.yml:
```yml
overwrite: true
schema: "http://localhost:4000/graphql"
documents: "graphql/**/*.ts"
generates:
  lib/apolloComponents.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withHooks: true
      withHOC: false
      withComponent: false
      hooksImportFrom: "@apollo/react-hooks"
```
