### ISSUE TITLE
wrong imports for react apollo hooks

### ISSUE THREAD

**Issue by tafelito** [dotansimha/graphql-code-generator#3129]
**Describe the bug**
imports for ApolloReactCommon and ApolloReactHooks are being imported from the wrong package in the latest version `(1.9.1)`

```js
import * as ApolloReactCommon from '@apollo/client';
import * as ApolloReactHooks from '@apollo/client';
``` 

**To Reproduce**
use version 1.9.1 with this config

```
"@graphql-codegen/cli": "^1.9.1",
"@graphql-codegen/typescript": "^1.9.1",
"@graphql-codegen/typescript-operations": "^1.9.1",
"@graphql-codegen/typescript-react-apollo": "^1.9.1",
"@graphql-codegen/typescript-resolvers": "^1.9.1",
```

```
overwrite: true
schema:
  - ${GRAPHQL_ENDPOINT}:
      headers:
        ....
documents: './graphql/**/*.graphql'
generates:
  ./graphql/generated/graphql.tsx:
    hooks:
    afterOneFileWrite:
      - prettier --write
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      reactApolloVersion: 3
      withHooks: true
      withHOC: false
      withComponent: false
      withMutationFn: false
```

using  `hooksImportFrom: '@apollo/react-hooks'` doesn't change anything

**Expected behavior**
```
import * as ApolloReactCommon from '@apollo/react-common';
import * as ApolloReactHooks from '@apollo/react-hooks';
```

**Environment:**

- OS: 
- `@graphql-codegen/...`: 1.9.1
- NodeJS: v12.12.0

**Additional context**
This works perfectly fine with version 1.7.0
