### ISSUE TITLE
lazyHook created not accepting all options

### ISSUE THREAD

**Issue by maapteh** [dotansimha/graphql-code-generator#3152]
I'm using codegen `1.8.1` and have apollo hooks setup but not the new client yet. The auto-generated hooks are working correctly with TypeScript.

But on lazy hooks, I can only call them with the context and variables but not all other options you normally have on (lazy) queries.

So I'm missing `fetchPolicy` as option for example.

**To Reproduce**

Using the following config:

```
schema:
    - 'http://{SNIP}/graphql'
    - './client-schema.graphql'
overwrite: true
require:
    - ts-node/../../codegen-interpreter.ts
documents:
    [
        './src/common/**/*.graphql.ts',
        './src/common/graphql/queries/*.ts',
        './src/common/graphql/fragments/*.ts',
    ]
config:
    namingConvention:
        enumValues: change-case#upperCase
generates:
    src/common/graphql/_generated-types.ts:
        config:
            noNamespaces: true
        plugins:
            - add: "/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */\n"
            - 'typescript'
            - 'typescript-operations'
    src/common/graphql/_generated-types-server.ts:
        config:
            noNamespaces: true
        plugins:
            - add: "/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */\n"
            - 'typescript'
    src/common/graphql/_generated-hooks.tsx:
        plugins:
            - add: "/** eslint-disable */\n/** AUTO GENERATED, DO NOT EDIT OVERHERE */"
            - typescript
            - typescript-operations
            - typescript-react-apollo
        config:
            reactApolloVersion: 3
            reactApolloImportFrom: '@apollo/react-hooks'
            withComponent: false
            withHOC: false
            withHooks: true
    src/common/graphql/_generated-fragment-types.ts:
        plugins:
            - 'fragment-matcher'
```

lazy generated hook used:

`const [getCards, { data, loading }] = useGetProductCardsByNameLazyQuery();`

now getCards only has options to pass variables or context, but all other options defined https://www.apollographql.com/docs/react/api/react-hooks/#uselazyquery are not possible to set.
