### ISSUE TITLE
Can't use directive within overrideType

### ISSUE THREAD

**Issue by damianfrizzi** [dotansimha/graphql-code-generator#3159]
Not sure if this is a bug or the expected behaviour. Please let me know if this should be a feature request.

**Describe the bug**
When using `typescript-mongodb` it isn't possible to use directives within `overrideType`

**To Reproduce**
See Expected behavior

1. My GraphQL schema:

```graphql
type User @entity {
  projects: [String!] @column(overrideType: "@id")
}
```

2. My GraphQL operations:

```graphql
* Irelevant
```

3. My `codegen.yml` config file:

```yml
overwrite: true
generates:
  # Workaround https://github.com/dotansimha/graphql-code-generator/issues/3117
  generated/db.ts:
    schema: 'graphql/**/*.db.graphql'
    plugins:
      - add: import { Maybe } from './graphql.server';
      - 'typescript-mongodb'
    config:
      namingConvention:
        enumValues: keep
  generated/graphql.server.ts:
    schema: 'graphql/**/*.schema.graphql'
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
    config:
      namingConvention:
        enumValues: keep
  generated/graphql.client.tsx:
    schema: 'graphql/**/*.schema.graphql'
    documents: 'components/**/*.graphql'
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withHooks: true
      withComponent: false
      withHOC: false
      skipTypename: true
      namingConvention:
        enumValues: keep
```

**Expected behavior**
The schema above generates:
```
export type UserDbObject = {
  projects?: @id[],
};
```
I would expect it to generate the following though:
```
export type UserDbObject = {
  projects?: ObjectID[],
};
```

It's possible to workaround this by hardcoding ObjectID[]:
````
projects: [String!] @column(overrideType: "ObjectID[]")
````

**Environment:**

- OS: 
- `@graphql-codegen/typescript-mongodb": "1.9.1"`
- `"@graphql-codegen/add": "1.9.1"`
- `"@graphql-codegen/cli": "1.9.1"`
- `"@graphql-codegen/typescript": "1.9.1"`
- `"@graphql-codegen/typescript-graphql-files-modules": "1.9.1"`
- `"@graphql-codegen/typescript-operations": "1.9.1"`
- `"@graphql-codegen/typescript-react-apollo": "1.9.1"`
- `"@graphql-codegen/typescript-resolvers": "1.9.1"`
- NodeJS: v10.16.0

**Additional context**
-
