### ISSUE TITLE
React Hooks not generating

### ISSUE THREAD

**Issue by AdiBev** [dotansimha/graphql-code-generator#3216]
Hi,
Whenever I'm generating the file I cannot see my react hooks to import. I also have noticed in the generated file it is not importing any other library other than graphql-tag.
**To Reproduce**

My GraphQL operations:

```graphql
import gql from "graphql-tag";

export const QUERY_COUNTRY = gql`
query {
  continents {
    code
    name
  }
}
`;

```

My `codegen.yml` config file:

```yml
overwrite: true
schema: "https://countries.trevorblades.com"
documents: "src/**/*.ts"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withHooks: true

```

**Expected behavior**
Expected to get the generated hooks but only getting typed definations.

**Environment:**

- OS: Windows

Currently getting the data from here [link](https://countries.trevorblades.com/)
