### ISSUE TITLE
Mappers option is not work with generic type after upgrade to 1.10.0

### ISSUE THREAD

**Issue by keepcosmos** [dotansimha/graphql-code-generator#3224]
**Describe the bug**
 
mapping option is not work with generic type after upgrade to 1.10.0 (It works on 1.9.1)

**To Reproduce**

1. My `codegen.yml` config file:

```yml
# Put your YML here
generates:
  src/graphqls/types.ts:
    config:
      mappers:
          Article: "models#Article"
          ArticleFeed: "models#Feed<Article>"
``` 

**Expected behavior**

```ts
import { Article, Feed } from 'models'
```

but it generate
```ts
import { Article, Feed<Article> } from 'models'
```
