### ISSUE TITLE
 Error: upperCase couldn't be found in module upper-case!

### ISSUE THREAD

**Issue by OneCyrus** [dotansimha/graphql-code-generator#3246]
**Describe the bug**
 Error: upperCase couldn't be found in module upper-case!

![image](https://user-images.githubusercontent.com/7747800/71896857-1f941100-3155-11ea-87f2-f0fac3afd61a.png)

**To Reproduce**
use namingConvention like 

```
 config: {
    strict: true,
    namingConvention: {
      default: "change-case#pascalCase",
      enumValues: "change-case#upperCase"
    }
  },
```

**Comment by ardatan** [comment]
Until we fix it, could you install `upper-case` npm package in your project?

**Comment by OneCyrus** [comment]
upper-case was already installed though version 1.x. after upgrading to 2.x it's running now.

**Comment by umutyerebakmaz** [comment]
I made the last update. to ensure that I deleted the node_modules folders and reinstalled all packages. I have that same problem.

**Comment by ardatan** [comment]
@OneCyrus @umutyerebakmaz Could you try with the canary version `1.11.2-alpha-6bc83503.0`?

**Comment by dotansimha** [comment]
Fixed in `v1.12.0`

**Comment by anault** [comment]
I'm having this issue using 1.15.5.

output:
```
> graphql-codegen --config codegen.yml --watch

  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/generated/graphql.tsx
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → undefined couldn't be found in module upper-case!


 Found 1 error

  ✖ src/generated/graphql.tsx
    Error: undefined couldn't be found in module upper-case!
        at Object.resolveExternalModuleAndFn (/Users/anault/Projects/apollo-project/client/node_modules/@graphql-codegen/plugin-helpers/index.cjs.js:27:15)
```

codegen.yml:
```
overwrite: true
schema: "../server/schema.graphql"
documents: "src/**/*.graphql"
generates:
  src/generated/graphql.tsx:
    config:
      reactApolloVersion: 3
      withHooks: true
      withComponent: false
      withHOC: false
      namingConvention:
        enumValues: upper-case
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo

```
