### ISSUE TITLE
Docblocks disappeared in versions ^1.10.0

### ISSUE THREAD

**Issue by toverux** [dotansimha/graphql-code-generator#3249]
**Describing the bug**

In versions <1.10.0, types generated by the `typescript` plugin had docblocks with descriptions coming from the API.

After upgrading to latest, those comments are missing from the generated file. I found that this happens since 1.10.0 but nothing in the Releases tab or issues seems to mention any change about this. 

My diff looks like this, for hundreds of types:

```diff
-/** A connection to a list of items. */
 export type AppletConnection = {
   readonly __typename?: 'AppletConnection',
-  /** Total object count. */
   readonly count: Scalars['Int'],
-  /** Information to aid in pagination. */
   readonly pageInfo: PageInfo,
-  /** Information to aid in pagination. */
   readonly edges: ReadonlyArray<AppletEdge>,
 };

-/** An edge in a connection. */
 export type AppletEdge = {
   readonly __typename?: 'AppletEdge',
-  /** The item at the end of the edge */
   readonly node: Applet,
-  /** A cursor for use in pagination */
   readonly cursor: Scalars['String'],
 };

-/** List of items with pagination. */
 export type AppletPagination = {
   readonly __typename?: 'AppletPagination',
-  /** Total object count. */
   readonly count?: Maybe<Scalars['Int']>,
-  /** Array of objects. */
   readonly items?: Maybe<ReadonlyArray<Maybe<Applet>>>,
-  /** Information to aid in pagination. */
   readonly pageInfo: PaginationInfo,
 };
```

Of course, I verified that the descriptions are still in the API, and when I'm coming back to versions prior to ^1.10.0, doc blocks are back.

**To reproduce**

My `codegen.yml` config file:

```yml
schema: "http://localhost:9000/graphql"
generates:
  projects/lib.browser.{redacted}/graphql.generated.ts:
    documents: projects/lib.browser.{redacted}/**/*.graphql
    plugins:
      - add: |
          // /!\ This file is auto-generated by graphql-code-generator. Do not edit by hand.
          // tslint:disable
          // ...line above is mainly for IDE support, see webpack configs where this file is excluded
      - typescript
      - typescript-operations
      - typescript-apollo-angular
    config:
      immutableTypes: true
      scalars:
        MongoID: string
        JSON: any
        Date: string
        JSONObject: '{ [key: string]: any }'
        Success: "'success'"
```

Dependencies (managed by yarn, lock file confirms latest version is installed) :

```json
{
    "@graphql-codegen/add": "^1.11.0",
    "@graphql-codegen/cli": "^1.11.0",
    "@graphql-codegen/typescript": "^1.11.0",
    "@graphql-codegen/typescript-apollo-angular": "^1.11.0",
    "@graphql-codegen/typescript-operations": "^1.11.0"
}
```

**Comment by leethree** [comment]
yes I'm seeing the same issue. all the descriptions are gone.

**Comment by anfinil** [comment]
I have the same problem.

**Comment by koenpunt** [comment]
The problem is probably introduced in https://github.com/ardatan/graphql-toolkit, since that library handles the schema loading etc.

**Comment by falkenhawk** [comment]
also "description" fields are empty now in a generated graphql schema.json

**Comment by ardatan** [comment]
Could you try with the following canary version?
`1.11.3-alpha-aba86640.34`

**Comment by falkenhawk** [comment]
Version `1.11.3-alpha-aba86640.34` does not fix the issue for me.

**Comment by ardatan** [comment]
@falkenhawk Could you share a reproduction on codesandbox so I can debug?

**Comment by dotansimha** [comment]
@falkenhawk ?

**Comment by falkenhawk** [comment]
I'd love to, but I am swamped at the moment... I can share my codegen config file, if that's of any help:
```yaml
overwrite: true
schema: ${GRAPHQL_URL:http://micro.test/api/graphql}
config:
  namingConvention:
    enumValues: change-case#upperCase
generates:
  ./graphql.schema.json:
    plugins:
      - introspection
  packages/common/gen/graphql.fragments.json:
    plugins:
      - fragment-matcher
  packages/common/src/service.graphql.ts:
    plugins:
      - typescript
hooks:
  afterOneFileWrite:
    - prettier --write
```

And I have comments attached to my fields in my schema e.g.
```
type User {
  "Some description for the field"
  something: Boolean
}
```

Descriptions are missing from both `graphql.schema.json` (as "description" property of an entity) and `service.graphql.ts` (as docblock comments):

```
          {
            "name": "followers",
            // in 1.9.1: "description": "Some description for the field",
            "description": "",
            "args": [],
            "type": { (...) },
            "isDeprecated": false,
            "deprecationReason": null
          },
```

It seems that "descriptions" are not being retrieved properly from an url endpoint. The last version I had this working was 1.9.1, so I am staying on that for the time being.
