### ISSUE TITLE
react-apollo has no exported member "MutationProps"

### ISSUE THREAD

**Issue by NiccoloCase** [dotansimha/graphql-code-generator#3261]
The one in the title is the error react gives me regarding the auto file generated by this tool.
My configuration file is this: 
```
overwrite: true
schema:
  - "http://localhost:3000/graphql"
  - ./src/graphql/client-schema.graphql
documents: "src/graphql/**/*.ts"
generates:
  src/graphql/generated.tsx:
    config:
      noNamespaces: true
      contextType: ../graphql/context#MyContext
      withHooks: true
      withComponent: true

    plugins:
      - add: '/* eslint-disable */'
      - "typescript-common"
      - "typescript-client"
      - "typescript-react-apollo"
      - "typescript-server"
      - "typescript-resolvers"
```
Instead the installed packages are these:
```
    "graphql-code-generator": "^0.18.2",
    "graphql-codegen-add": "^0.18.2",
    "graphql-codegen-typescript-client": "^0.18.2",
    "graphql-codegen-typescript-common": "^0.18.2",
    "graphql-codegen-typescript-react-apollo": "^0.18.2",
    "graphql-codegen-typescript-resolvers": "^0.18.2",
    "graphql-codegen-typescript-server": "^0.18.2"
```
I managed to solve this problem by downgrading the "react-apollo" package realizing that in a working project the only different version was that of this package. So I replaced version 3.1.3 with version 2.5.8.
I'd like to know if there is another solution that doesn't involve downgrading. 
Thanks in advance.
