### ISSUE TITLE
Get "Query root type must be provided." error when query type

### ISSUE THREAD

**Issue by xjiangiao** [dotansimha/graphql-code-generator#3268]
**Describe the bug**
Get error when schema's query root type's name isn't "Query".

The code will generate without error when the Query root type name is "Query"

**To Reproduce**
https://codesandbox.io/s/festive-firefly-vle63?fontsize=14&hidenavigation=1&theme=dark
just generate the code

1. My GraphQL schema:

```graphql
type QueryRoot {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}

schema {
  query: QueryRoot
  # query: Query
}

```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
        email
    }
}

```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "./schema.graphql"
documents: "src/**/*.graphql"
generates:
  src/app/graphql/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-apollo-angular
```

**Expected behavior**

Generate query code of apollo angular.
**Environment:**

- OS: Window 10
- `@graphql-codegen/...`: 1.11.2
- NodeJS: 12

**Additional context**
