### ISSUE TITLE
Missing types for several queries

### ISSUE THREAD

**Issue by lensbart** [dotansimha/graphql-code-generator#3280]
Hello,

Thanks for making this tool, it seems very ergonomic.

However, I’m running into an issue when generating TypeScript types for my queries, mutations & subscriptions:

```yaml
# See https://graphql-code-generator.com
schema:
  - ./app/schema/**/typeDefs.graphql
  - ./server/schema/private/**/*.graphql
documents:
  - './app/**/*.graphql'
overwrite: true
generates:
  ./shared/types/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      immutableTypes: true
```

This one leaves out several queries, for example one query located at `./app/pages/Book/graphql/book.graphql`. When we explicitly include the file:

```yaml
# See https://graphql-code-generator.com
schema:
  - ./app/schema/**/typeDefs.graphql
  - ./server/schema/private/**/*.graphql
documents:
  - './app/**/*.graphql'
  - './app/pages/Book/graphql/book.graphql' # added, everything else identical
overwrite: true
generates:
  ./shared/types/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      immutableTypes: true
```

we get an error when running the CLI script: **`Not all operations have an unique name: [name of explicitly included query]`**

Note that the name of this query appears only once throughout the codebase. The script outputs a list of GraphQL fragment files which are imported by the query located at `./app/pages/Book/graphql/book.graphql`.
