### ISSUE TITLE
Type Query must define one or more fields when #import-ing extension

### ISSUE THREAD

**Issue by Li357** [dotansimha/graphql-code-generator#3321]
**Describe the bug**

When trying to generate types for schema, using an empty Query type then importing another file that includes an extension Query leads to an error saying that `Query` must define one or more fields.

**To Reproduce**

GraphQL schema (`schema.graphql`):

```graphql
# import * from "users.graphql"

type Query
```

Inside `users.graphql`:

```graphql
extend type Query {
  users: [User!]!
}

type User {
  name: String!
}
```

3. `codegen.yml` config file:

```yml
schema: api/graphql/schema.graphql
generates:
  common/types/schema.ts:
    plugins:
      - typescript
      - typescript-resolvers
```

**Expected behavior**

Since `users.graphql` extends Query I was expecting the type generation to work as expected, but it's telling me Query needs one or more fields. Is this a `graphql-import` issue? I've tried different import variants (`#import "users.graphql"`, `#import User from "users.graphql"`) to no avail.

**Environment:**

- OS: macOS 10.15.1
- `@graphql-codegen/...`: 1.11.2
- NodeJS: 11.15.0
