### ISSUE TITLE
Incorrect "Not all operations have an unique name" on 1.11.2

### ISSUE THREAD

**Issue by benjie** [dotansimha/graphql-code-generator#3326]
**Describe the bug**

1.11.2 is incorrectly stating "Not all operations have an unique name" when I attempt to run codegen; 1.8.3 was working fine.

**To Reproduce**

Codegen works fine on the Graphile Starter `codegen-fine` branch: https://github.com/graphile/starter/tree/codegen-fine

However, when we upgrade graphql-codegen from 1.8.3 to 1.11.2 we get the aforementioned error; see: https://github.com/graphile/starter/tree/codegen-bad which is one commit ahead of `codegen-fine`.

I've dug into this further; see "Additional context"

Running `graphql-codegen` results in:

```
 ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate index.tsx
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Not all operations have an unique name: AddEmail


 Found 1 error

  ✖ index.tsx
    Not all operations have an unique name
  
    * AddEmail found in:
  
          - /home/benjie/Dev/starter/@app/client/src/graphql/AddEmail.graphql
          - /home/benjie/Dev/starter/@app/client/src/graphql/DeleteEmail.graphql
          - /home/benjie/Dev/starter/@app/client/src/graphql/EmailsForm_User.graphql
          - /home/benjie/Dev/starter/@app/client/src/graphql/SettingsEmails.graphql
          - /home/benjie/Dev/starter/@app/client/src/graphql/SettingsProfile.graphql
    Error: Not all operations have an unique name: AddEmail
        at validateDuplicateDocuments (/home/benjie/Dev/starter/node_modules/@graphql-codegen/core/index.cjs.js:200:1
5)
        at Object.codegen (/home/benjie/Dev/starter/node_modules/@graphql-codegen/core/index.cjs.js:59:9)
        at process (/home/benjie/Dev/starter/node_modules/@graphql-codegen/cli/bin.js:783:67)
        at Array.map (<anonymous>)
        at /home/benjie/Dev/starter/node_modules/@graphql-codegen/cli/bin.js:790:63
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async Task.task (/home/benjie/Dev/starter/node_modules/@graphql-codegen/cli/bin.js:582:17)
    Error: Not all operations have an unique name: AddEmail
        at validateDuplicateDocuments (/home/benjie/Dev/starter/node_modules/@graphql-codegen/core/index.cjs.js:200:1
5)
        at Object.codegen (/home/benjie/Dev/starter/node_modules/@graphql-codegen/core/index.cjs.js:59:9)
        at process (/home/benjie/Dev/starter/node_modules/@graphql-codegen/cli/bin.js:783:67)
        at Array.map (<anonymous>)
        at /home/benjie/Dev/starter/node_modules/@graphql-codegen/cli/bin.js:790:63
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async Task.task (/home/benjie/Dev/starter/node_modules/@graphql-codegen/cli/bin.js:582:17)
```

**Expected behavior**

Codegen should run as expected (since all my operations are uniquely named)

**Environment:**

- OS: `Ubuntu 18.04.3 LTS`
- NodeJS: `v12.13.1`

```
    "@graphql-codegen/add": "^1.11.2",
    "@graphql-codegen/cli": "^1.11.2",
    "@graphql-codegen/typescript": "^1.11.2",
    "@graphql-codegen/typescript-operations": "^1.11.2",
    "@graphql-codegen/typescript-react-apollo": "1.11.2"
```

**Additional context**

I investigated further using the Node debugger because this issue is bizarre. I ended up here:

![Screenshot_20200120_104824](https://user-images.githubusercontent.com/129910/72721488-156e0b80-3b74-11ea-8676-e76e932a5bc2.png)

Note that the `rawSDL` value for this entry has an import and `mutation DeleteEmail`; however the `definitions` entry contains an operation and a fragment, the operation is named `AddEmail` which **is not sourced from this file**. The imported fragment [can be seen here](https://github.com/graphile/starter/blob/codegen-bad/@app/client/src/graphql/EmailsForm_UserEmail.graphql) but doesn't contain any operations:

```graphql
fragment EmailsForm_UserEmail on UserEmail {
  id
  email
  isVerified
  isPrimary
  createdAt
}
```

Interestingly this fragment IS [used by the `AddEmail` operation](https://github.com/graphile/starter/blob/codegen-bad/@app/client/src/graphql/AddEmail.graphql), so it looks like the re-used fragment is causing the file/operations to be interpretted incorrectly.

**Comment by lorado** [comment]
Same here. Version `1.9.1` works fine, in Version `1.10.0` I get following error in my project: 

> Error: 
          Import statement is not valid: import '../../fragments/Paginator.gql'
          If you want to have comments starting with '# import', please use ''' instead!
          You can only have 'import' statements in the following pattern;
          # import [Type].[Field] from [File]

With `1.12.2` I get following error:

> Not all operations have an unique name
    * GetConsultancies found in:
    - .../graphql/ressources/consultancies/GetConsultancies.gql
    - .../graphql/ressources/consultancies/GetConsultancyForView.gql
    - .../graphql/ressources/consultants/GetConsultantForView.gql
    - .../graphql/ressources/consultants/GetConsultants.gql
    - .../graphql/ressources/functionings/GetFunctionings.gql
    - .../graphql/ressources/industries/GetIndustries.gql
    - .../graphql/ressources/itSkills/GetItSkills.gql
    - .../graphql/ressources/qualifications/GetQualifications.gql

And I named queries like the file names. Got to stay with Version `1.9.1` ATM

**Comment by ardatan** [comment]
Could you try the following?
```yml
schema: ...
documents:
    - your-documents-pointer:
          skipGraphQLImport: true
```

**Comment by lorado** [comment]
@ardatan I just found it in other issue. Tried it out, and for 1.11.2 it didn't help

here is my config:

```yml
overwrite: true
schema: "http://localhost/graphql"
documents:
  - "./graphql/**/*.gql":
    skipGraphQLImport: true
generates:
  graphql/GQLTypes.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      scalars:
        ObfId: number
        Json: "{ [key: string]: any }"
```

**Comment by benjie** [comment]
@ardatan Assuming I've got the YAML sigils in the correct places, this doesn't seem to have made any difference:

![Screenshot_20200120_170633](https://user-images.githubusercontent.com/129910/72745285-52072a80-3ba7-11ea-970d-a8c3ba958660.png)

**Comment by ardatan** [comment]
Fix available in canary version;
`1.11.3-alpha-841a8693.43`

**Comment by will-hart** [comment]
I get a similar issue with updating from `1.9.1` to `1.11.2` or `1.11.3-alpha-f3691f38.45`

```
Found 1 error

    GraphQLError: RelayParser: Encountered duplicate definitions for one or more documents: each document must have a unique name. 

Duplicated documents:
    - ((all the fragments defined in fragments.graphql))

        at createUserError (\node_modules\relay-compiler\lib\core\CompilerError.js:31:10)
        at new RelayParser (\node_modules\relay-compiler\lib\core\RelayParser.js:115:13)
        at \node_modules\relay-compiler\lib\core\RelayParser.js:81:18
        at Object.run (\node_modules\relay-compiler\lib\core\GraphQLCompilerProfiler.js:55:30)
        at Object.transform (\node_modules\relay-compiler\lib\core\RelayParser.js:80:19)
        at Object.optimizeOperations (\node_modules\@graphql-codegen\visitor-plugin-common\index.cjs.js:2223:49)
        at executePlugin (\node_modules\@graphql-codegen\core\index.cjs.js:50:41)
        at Promise.all.options.plugins.map (\node_modules\@graphql-codegen\core\index.cjs.js:106:30)
        at Array.map (<anonymous>)
        at Object.codegen (\node_modules\@graphql-codegen\core\index.cjs.js:96:54)
```

It appears to break on the fragments which are defined in a separate file. This is my config

```
overwrite: true
schema: "schema.gql"
documents:
  - "path/to/packages/*.gql":
      skipGraphQLImport: true
generates:
  path/to/packages/generatedTypes.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
    config:
      namingConvention:
        typeNames: change-case#pascalCase
        enumValues: change-case#upperCase
      preResolveTypes: true
      flattenGeneratedTypes: true
      skipTypename: true
      declarationKind: 'interface'
      typesPrefix: I
      enumPrefix: false
  path/to/packages/generatedOperations.ts:
    plugins:
      - "typescript-document-nodes"
    config:
      namingConvention:
        typeNames: change-case#pascalCase
        enumValues: change-case#upperCase
      nameSuffix: "Document"
      skipTypename: true
```
