### ISSUE TITLE
transformUnderscore option cuts underscore from property starting with number

### ISSUE THREAD

**Issue by ali4heydari** [dotansimha/graphql-code-generator#3395]
**Describe the bug**
I use GraphQL code generator with Next.js and Wordpress. After running generation with following config I get TypeScript syntax error because transformUnderscore removes underscore without paying attention to next character type.
**To Reproduce**

1. My GraphQL schema:

```graphql
enum MediaItemSizeEnum {
  LARGE
  MEDIUM
  MEDIUM_LARGE
  POST_THUMBNAIL
  THUMBNAIL
  TWENTYTWENTY_FULLSCREEN
  _1536X1536
  _2048X2048
}
...
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "http://localhost:3000/__graphql"
generates:
  src/types/graphql/index.tsx:
    documents: '{src,pages}/**/*{.ts,.tsx,.graphql}'
    hooks:
      afterOneFileWrite:
        - tslint --fix -c tslint.json 'src/types/graphql/**/*{.ts,.tsx}'
    plugins:
#      - add:
#          content: 'declare namespace GraphQL {'
#      - add:
#          placement: append
#          content: '}'
      - typescript
      - typescript-operations
      - typescript-resolvers
      - typescript-urql
    config:
#      skipTypename: true
#      typesPrefix: I
      withHooks: true
      scalars:
        DateTime: Date
        JSON: "{ [key: string]: any }"
      namingConvention:
        transformUnderscore: true
  graphql.schema.json:
    plugins:
      - introspection

```

**Expected behavior**

```typescript
export enum MediaItemSizeEnum {
  Large = 'LARGE',
  Medium = 'MEDIUM',
  MediumLarge = 'MEDIUM_LARGE',
  PostThumbnail = 'POST_THUMBNAIL',
  Thumbnail = 'THUMBNAIL',
  TwentytwentyFullscreen = 'TWENTYTWENTY_FULLSCREEN',
  _1536X1536 = '_1536X1536',
  _2048X2048 = '_2048X2048',
}
...
```

**Actual behavior**
```typescript
export enum MediaItemSizeEnum {
  Large = 'LARGE',
  Medium = 'MEDIUM',
  MediumLarge = 'MEDIUM_LARGE',
  PostThumbnail = 'POST_THUMBNAIL',
  Thumbnail = 'THUMBNAIL',
  TwentytwentyFullscreen = 'TWENTYTWENTY_FULLSCREEN',
  1536X1536 = '_1536X1536', // error
  2048X2048 = '_2048X2048', // error
}
...
```
**Environment:**

- OS: 
    + Windows 10 pro
    + version 1909
    + OS build 18363.592
- `@graphql-codegen/...`:
```json
 "devDependencies": {
    "@graphql-codegen/add": "^1.11.2",
    "@graphql-codegen/cli": "^1.11.2",
    "@graphql-codegen/introspection": "1.11.2",
    "@graphql-codegen/typescript": "1.11.2",
    "@graphql-codegen/typescript-document-nodes": "^1.11.2",
    "@graphql-codegen/typescript-operations": "^1.11.2",
    "@graphql-codegen/typescript-react-apollo": "1.11.2",
    "@graphql-codegen/typescript-resolvers": "^1.11.2",
    "@graphql-codegen/typescript-urql": "^1.11.2",
...
}
...
``` 
- NodeJS: `v12.13.1`

**Additional context**
