### ISSUE TITLE
Error: Cannot find module 'upper-case-first'

### ISSUE THREAD

**Issue by dusan-dragon** [dotansimha/graphql-code-generator#3411]
**Describe the bug**
We were using:
```
config:
      strict: true
      namingConvention:
        typeNames: change-case#upperCaseFirst
        enumValues: keep
```

**To Reproduce**

**Expected behavior**
The chosen letter case should work without error

**Environment:**

- OS: 
- `@graphql-codegen/...` : 0.12.1 
- NodeJS: v12.11.1

**Additional context**

As a workaround you can do `npm install upper-case-first`
