### ISSUE TITLE
TypeError: Options arg must be an object with version >1.11.2

### ISSUE THREAD

**Issue by Tbaut** [dotansimha/graphql-code-generator#3414]
**Describe the bug**
`graphql-codegen --require dotenv/config --config codegen.yml` throws a:
"TypeError: Options arg must be an object" with a config that is working well on 1.11.2

**To Reproduce**
I'm using the following codegen.yml:
```yml
overwrite: true
generates:
  src/generated/auth-graphql.tsx:
    schema:
      - https://fakeql.com/graphql/fab1e22356629cb5a07dfb7ff568ddd5
    documents: 
      - "src/services/**/*.{ts,tsx}"
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withComponent: false
      withHOC: false
      withHooks: true
      withResultType: true
```

OS: 
- "@graphql-codegen/cli": "1.12.2"
- "@graphql-codegen/typescript": "1.12.2"
- "@graphql-codegen/typescript-operations": "1.12.2"
- "@graphql-codegen/typescript-react-apollo": "1.12.2"  

NodeJS: 12.14.1

**Comment by ardatan** [comment]
@Tbaut I tried to reproduce it but I couldn't. Could you help to reproduce the issue?
https://codesandbox.io/s/focused-lumiere-3kdvx

**Comment by Tbaut** [comment]
Thanks for the super quick answer, it's solved in 1.12.1 (I originally had this error as well: https://github.com/dotansimha/graphql-code-generator/issues/3407)

**Comment by kapral18** [comment]
Have the same error with v1.12.2

```yml
schema: http://localhost:8000/___graphql
documents:
    - ./src/**/*.{ts,tsx}
    - ./node_modules/gatsby*/!(node_modules)/**/*.js
generates:
    ./src/types/generated/index.ts:
        config:
            skipTypename: true
            scalars:
                Date: string
                JSON: "{ [key: string]: any }"
            namingConvention:
                enumValues: keep
            declarationKind: "interface"
        plugins:
            - typescript
            - typescript-operations

```
