### ISSUE TITLE
Updating typescript-operations from 1.9.1 to 1.12.1 broke our build

### ISSUE THREAD

**Issue by 0xClpz** [dotansimha/graphql-code-generator#3445]
**Describe the bug**
when running the graphql code generator we end up with the following output
```
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate packages/web/src/graphql/types.codegen.tsx
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Cannot read property 'definitions' of undefined
    ✔ Generate packages/web/schema.json


 Found 1 error

  ✖ packages/web/src/graphql/types.codegen.tsx
    TypeError: Cannot read property 'definitions' of undefined
        at /Users/antonio/dev/shippr/node_modules/graphql/utilities/concatAST.js:21:18
        at Array.flatMap (<anonymous>)
        at flatMap (/Users/antonio/dev/shippr/node_modules/graphql/polyfills/flatMap.js:13:24)
        at Object.concatAST (/Users/antonio/dev/shippr/node_modules/graphql/utilities/concatAST.js:20:39)
        at Object.plugin (/Users/antonio/dev/shippr/node_modules/@graphql-codegen/typescript-operations/index.cjs.js:107:28)
        at executePlugin (/Users/antonio/dev/shippr/node_modules/@graphql-codegen/core/index.cjs.js:50:41)
        at /Users/antonio/dev/shippr/node_modules/@graphql-codegen/core/index.cjs.js:106:30
        at Array.map (<anonymous>)
        at Object.codegen (/Users/antonio/dev/shippr/node_modules/@graphql-codegen/core/index.cjs.js:96:54)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async process (/Users/antonio/dev/shippr/node_modules/@graphql-codegen/cli/bin.js:783:56)
        at async Promise.all (index 0)
        at async /Users/antonio/dev/shippr/node_modules/@graphql-codegen/cli/bin.js:790:37
        at async Task.task (/Users/antonio/dev/shippr/node_modules/@graphql-codegen/cli/bin.js:582:17)
    TypeError: Cannot read property 'definitions' of undefined
        at /Users/antonio/dev/shippr/node_modules/graphql/utilities/concatAST.js:21:18
        at Array.flatMap (<anonymous>)
        at flatMap (/Users/antonio/dev/shippr/node_modules/graphql/polyfills/flatMap.js:13:24)
        at Object.concatAST (/Users/antonio/dev/shippr/node_modules/graphql/utilities/concatAST.js:20:39)
        at Object.plugin (/Users/antonio/dev/shippr/node_modules/@graphql-codegen/typescript-operations/index.cjs.js:107:28)
        at executePlugin (/Users/antonio/dev/shippr/node_modules/@graphql-codegen/core/index.cjs.js:50:41)
        at /Users/antonio/dev/shippr/node_modules/@graphql-codegen/core/index.cjs.js:106:30
        at Array.map (<anonymous>)
        at Object.codegen (/Users/antonio/dev/shippr/node_modules/@graphql-codegen/core/index.cjs.js:96:54)
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
        at async process (/Users/antonio/dev/shippr/node_modules/@graphql-codegen/cli/bin.js:783:56)
        at async Promise.all (index 0)
        at async /Users/antonio/dev/shippr/node_modules/@graphql-codegen/cli/bin.js:790:37
        at async Task.task (/Users/antonio/dev/shippr/node_modules/@graphql-codegen/cli/bin.js:582:17)


Something went wrong
error Command failed with exit code 1.
```
**To Reproduce**

When running codegen on it, it crashes, reverting to 1.9.1 fixes it

1. My GraphQL schema:

2. My GraphQL operations:

3. My `codegen.yml` config file:

```yml
schema: packages/backend/src/graphql/schema.graphql
documents:
  - packages/web/src/**/*.ts
  - packages/web/src/**/*.tsx
overwrite: true
generates:
  packages/web/src/graphql/types.codegen.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-resolvers
      - typescript-react-apollo
    config:
      withHooks: true
      withComponent: false
      withHOC: false
  packages/web/schema.json:
    plugins:
      - introspection
```

**Expected behavior**

**Environment:**

- OS: 
- `@graphql-codegen/cli`: 1.11.2
- NodeJS: 12.13.1

**Additional context**
I can't copy paste my graphql schema for privacy reasons, let me know if you want me to try and get a minimal reproduction up

**Comment by dotansimha** [comment]
@ardatan can you please take a look? it seems like an issue with toolkit?

**Comment by henry-young** [comment]
I've had a similar issue upgrading from 1.8.3 to 1.12.1. However I can generate code but it doesn't generate the `import { ExampleFragmentDoc } from './ExampleFragment.generated` in the generated query file. See below my codegen.yml config.
```yaml
overwrite: true
schema:
  - "schema.graphql"
config: {}
documents:
  - "src/**/*.graphql"
generates:
  src/graphql-types.ts:
    - typescript
  src/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.tsx
      baseTypesPath: graphql-types.ts
    config:
      noNamespaces: true
      withHooks: true
      withHOC: false
      hooksImportFrom: react-apollo
    plugins:
      - add: '/* eslint-disable import/first */'
      - typescript-operations
      - typescript-react-apollo
  src/introspection-result.ts:
    plugins:
      - fragment-matcher
require: []
```
