### ISSUE TITLE
Cannot query meta fields when using presets

### ISSUE THREAD

**Issue by mjbcopland** [dotansimha/graphql-code-generator#3459]
**Describe the bug**

`isUsingTypes()` does not handle meta fields.

> Error: Unable to find field "__schema" on type "Query"!

**To Reproduce**

1. My GraphQL schema:

```graphql
scalar Placeholder

type Query {
  placeholder: Placeholder
}
```

2. My GraphQL operations:

```graphql
query Query {
  __schema {
    __typename
  }
}
```

3. My `codegen.yml` config file:

```yml
schema:
  - src/schema.graphql

documents:
  - src/document.graphql

generates:
  src/types.ts:
    plugins:
      - typescript
  src/operations.ts:
    plugins:
      - typescript-operations
    preset: import-types
    presetConfig:
      typesPath: ./types
```

**Expected behavior**

**Environment:**

- OS: macOS Catalina 10.15.1
- ```json
  "@graphql-codegen/cli": "^1.12.2",
  "@graphql-codegen/import-types-preset": "^1.12.2",
  "@graphql-codegen/typescript": "^1.12.2",
  "@graphql-codegen/typescript-operations": "^1.12.2"
  ```
- NodeJS: v12.14.1
