### ISSUE TITLE
Duplicate import gql from 'graphql-tag'

### ISSUE THREAD

**Issue by polRk** [dotansimha/graphql-code-generator#3504]
Duplicate `import gql from 'graphql-tag'`
<img width="514" alt="Снимок экрана 2020-02-14 в 11 58 10 AM" src="https://user-images.githubusercontent.com/39828645/74516342-46e2b880-4f21-11ea-82bc-cd9994d31d75.png">
<img width="505" alt="Снимок экрана 2020-02-14 в 11 58 47 AM" src="https://user-images.githubusercontent.com/39828645/74516399-5d890f80-4f21-11ea-84a3-22df0f3627d5.png">

codegen.yml

```yaml


overwrite: true

documents: "src/**/*.graphql"

config:
  skipTypename: true
  avoidOptionals:
    inputValue: false
    object: true
  strict: true
  preResolveTypes: true
  scalars:
    timestamptz: string
    uuid: string
    jsonb: "{ [key: string]: any }"

generates:
  src/generate.ts:
    plugins:
      - add: '/* eslint:disable */'
      - "typescript"
      - "typescript-operations"
      - "typescript-document-nodes"
      - "typescript-graphql-request"
```
