### ISSUE TITLE
typescript-operations does not use the types from the typescript plugin

### ISSUE THREAD

**Issue by praneetloke** [dotansimha/graphql-code-generator#3514]
I am not sure if what I am seeing is a bug or more of a lack of my own understanding. I should preface this by saying that I haven't been working with GQL for very long.

With the following `codegen.yml` file:

```yaml
schema: http://localhost:3000/graphql
documents: src/api/documents/**/*.gql
generates:
  ./src/api/graphql-client.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-apollo-angular
    config:
      maybeValue: T | null | undefined
      declarationKind: "interface"
      preResolveTypes: true
      skipTypename: true
```

I expect the generated `graphql-client.ts` file to contain:
* TS interfaces for types in the schema (`typescript` plugin)
* Queries and Mutations from my documents to use the types generated from `typescript` plugin (`typescript-operations` plugin)
* Angular services to be generated from the operations emitted by `typescript-operations` (`typescript-apollo-angular` plugin)

It mostly works as expected, except the operations that are generated seem to _not_ use the types generated by the `typescript` plugin. Instead, the operations have inline definitions of the result of each operation. For example, here's a query a type called Project, which contains a "parent" type:

```graphql
query projects{
    projects{
        id
        name
        isCurrent
        estimatedStart
        estimatedEnd
        actualStart
        actualEnd
        parentObject1{
          ...
        }
    }
}
```
The generated Angular service:

```ts
  @Injectable({
    providedIn: 'root'
  })
  export class ProjectsGQL extends Apollo.Query<ProjectsQuery, ProjectsQueryVariables> {
    document = ProjectsDocument;
    
  }
```

and the definition for `ProjectsQuery`:

```ts
export type ProjectsQuery = 
{
projects: Array<{ 
  id: string,
  name: string,
  isCurrent: boolean,
  estimatedStart: any,
  estimatedEnd: any,
  actualStart: Maybe<any>,
  actualEnd: Maybe<any>,
  parentObject:<{...}>
}>
};
```
However, there is a type interface for `Project` that is generated from the schema:
```ts
export interface Project {
  id: Scalars['String'],
  name: Scalars['String'],
  isCurrent: Scalars['Boolean'],
  estimatedStart: Scalars['Date'],
  estimatedEnd: Scalars['Date'],
  actualStart?: Maybe<Scalars['Date']>,
  actualEnd?: Maybe<Scalars['Date']>,
  parentObject: ParentObjectType,
}
```

My question is, why doesn't `ProjectsQuery` use the `Project` type? I would have expected it to simply be:

```graphql
export type ProjectsQuery = { projects: Array<Project> };
```

Hope I explained what I am seeing correctly. Also, thank you very much for your efforts into making this tool available to us!
