### ISSUE TITLE
typescript-graphql-files-module doesn't work with typescript

### ISSUE THREAD

**Issue by stevemao** [dotansimha/graphql-code-generator#3547]
If I use typescript, typescript-operations and typescript-graphql-files-modules in the same file, it cannot find module '../graphql/a.graphql'

```
schema: http://example.com/graphql
documents: [./graphql/**/*.graphql]
generates:
  ./types/graphql.d.ts:
    plugins:
      - typescript-graphql-files-modules
      - typescript
      - typescript-operations
```

but if I write

```
schema: http://example.com/graphql
documents: [./graphql/**/*.graphql]
generates:
  ./types/graphql.d.ts:
    plugins:
      - typescript-graphql-files-modules
  ./types/types.d.ts:
    plugins:
      - typescript
      - typescript-operations
```

The problem is gone. However it should be possible to put all types in the same file.
