### ISSUE TITLE
Watch mode do not update output with JavaScript export schema type

### ISSUE THREAD

**Issue by melounek** [dotansimha/graphql-code-generator#3560]
I have the same issue as @grezxune mentioned in here: https://github.com/dotansimha/graphql-code-generator/issues/1609#issuecomment-554584784

Watching files works, *but output is untouched on change*

with this config
```
schema: src/graph/schema.ts
require:
    - ts-node/register
watch:
    - src/graph/nodes/**/*.ts
overwrite: true
generates:
    src/graph/gen-types.ts:
        plugins:
            - typescript
```

btw: I didn't find any docs about the wildcard-path passed to `watch` argument.

**Comment by debrice** [comment]
I have the same issue with typescript, it does not refresh the generated type unless I restart codegen or edit my config file (codegen.yml).

```
overwrite: true
schema: "http://localhost:4000"
documents: null
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
  ./graphql.schema.json:
    plugins:
      - "introspection"

```
