### ISSUE TITLE
Possible fragment bug introduced in v1.13.0

### ISSUE THREAD

**Issue by tuurbo** [dotansimha/graphql-code-generator#3612]
**Describe the bug**
As of v1.13.0 i'm getting ```GraphQL error: Unknown fragment "Me".``` Looks like if a fragment has the same name as a query the fragment is not included in the operation. If I rename ```Me``` to ```MeFoo``` it will add ```MeFoo``` to the operation.

**To Reproduce**

1. My GraphQL schema:
```graphql
fragment Staff on Staff {
    id
    username
    name
}

fragment Me on Staff {
    settings
    permissions
}

query Me {
    staff {
        ...Staff
        ...Me
    }
}
```

2. My GraphQL operations:
```graphql
query Me {
    staff {
        ...Staff
        ...Me
        __typename
    }
}

fragment Staff on Staff {
    id
    username
    name
    __typename
}

#
# <------ Missing 'Me' fragment.
# 
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema:
  - "http://localhost.loc/graphql":
documents: "./src/app/**/*.graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-apollo-angular"

```

**Expected behavior**

**Environment:**

- OS: Windows 10
- `@graphql-codegen/1.13.0`: 
- NodeJS: v13.10.1

**Additional context**
