### ISSUE TITLE
export enum as string type

### ISSUE THREAD

**Issue by suhailbinnisar** [dotansimha/graphql-code-generator#3627]
I have an enum
```javascript
enum Role {
  USER
  ADMIN
}
```
currently, it is generating as 
```javascript
export enum Role {
  USER = 'USER'
  ADMIN = 'ADMIN'
}
```

but I would like to get  it as:
```javascript
export type Role = 'USER' | 'ADMIN'
```

**Comment by darkbasic** [comment]
You're looking for the `enumsAsTypes` option, see https://graphql-code-generator.com/docs/plugins/typescript

**Comment by suhailbinnisar** [comment]
it's still generating in this format:
```javascript
export enum Role {
  USER = 'USER'
  ADMIN = 'ADMIN'
}
```
i tried both **plugin** level and **global** level

**Comment by dotansimha** [comment]
@suhailbinnisar `enumsAsTypes` should work. Can you please share you configuration? Which version do you use?

**Comment by suhailbinnisar** [comment]
My codegen.yml
```yml
schema: http://localhost:4000/

config:
  scalars:
    DateTime: Date
    JSON: { [key: string]: any }
  skipTypename: true
  nonOptionalTypename: true
  namingConvention:
    typeNames: change-case#pascalCase
    enumValues: change-case#upperCase

overwrite: true
documents: "./xsomepath/graphql/**/*.ts"

generates:
  ./somepath/index.d.ts:
    plugins:
      - typescript
  ./somepath2/resolvers-types.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      enumAsType: true
      contextType: interfaces/common#IResolverContext
  ./somepath3/Components.tsx:
    plugins:
      - typescript-operations
      - typescript-react-apollo
    config:
      withHooks: true
      withComponents: false
  ./somepath4/index.d.ts:
    plugins:
      - typescript
```

partial screenshot of generated file

![Screenshot from 2020-03-12 15-40-24](https://user-images.githubusercontent.com/61163044/76509273-da9f9a00-6477-11ea-984b-d6acf0d982fb.png)
