### ISSUE TITLE
Nested enum import - typescript

### ISSUE THREAD

**Issue by bennyKY** [dotansimha/graphql-code-generator#3641]
In order to describe an external enum mapping we need to mention:

The required enum (placed in server/proto/service_pb.d.ts):
```ts
export namespace EmailOnlyLoginRequest {
   export enum LoginOrigin {
      AGENT_REGISTRATION = 0,
    }
}

```

gql-schema:
```ts
enum LoginOrigin {
    AGENT_REGISTRATION
}
```

codegen.yml - **there is no way to import nested enum in namespace**
```yaml
config:
  enumValues:
      LoginOrigin: server/proto/service_pb#EmailOnlyLoginRequest.LoginOrigin
```

will generate in graphql.ts:
`import { EmailOnlyLoginRequest as LoginOrigin } from 'server/proto/service_pb';`

which is obviously wrong, it refer to the namespace rather than the enum itself.
