### ISSUE TITLE
Cannot use cli if installed globally

### ISSUE THREAD

**Issue by remorses** [dotansimha/graphql-code-generator#3660]
**Describe the bug**
When i try to generate using the plugins installed as global packages i get
```
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./frontend/support/generatedGraphql.ts
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → spurious results.
```
If i enable debug with `DEBUG=*`
```
Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.
```

**To Reproduce**
Install the plugins and cli globally and try to generate anything

**Comment by remorses** [comment]
I think this is because you check that the grapqhl module is the same for the generated packages and the cli,

can you remove this check?
there are so many cases where the graphql packages are different,

i was using the following config in a monorepo and was working quite well
```
overwrite: true
schema: http://localhost:8080/graphql

schemaPath: frontend/schema.graphql

documents: 
  - ./frontend/*.gql
  - ./cli/*.gql
generates:
    ./frontend/schema.graphql:
        - schema-ast
    ./frontend/support/generatedGraphql.ts:
        plugins:
            - 'typescript'
            - 'typescript-operations'
            - 'typescript-graphql-request'
    ./cli/src/generatedGraphql.ts:
        plugins:
            - 'typescript'
            - 'typescript-operations'
            - 'typescript-graphql-request'
    ./api/src/generatedGraphql.ts:
        plugins:
            - 'typescript'
```

As you can see there is no way i can use the same graphql module for all packages here
