### ISSUE TITLE
CLI started crashing with 1.13.1 with Dependency Cycle Found

### ISSUE THREAD

**Issue by capaj** [dotansimha/graphql-code-generator#3666]
**Describe the bug**

this error started to show on `1.13.1`:
```
> gql-gen --config codegen.yml

  ✔ Parse configuration
  ✖ Generate outputs
    → Dependency Cycle Found: front-end/src/graphql/gqlPrivateSchema.tsx -> front-end/src/graphql/gqlPublicSchema.tsx -> front-end/src/graphql/gqlPrivateSch
…
  Dependency Cycle Found: front-end/src/graphql/gqlPrivateSchema.tsx -> front-end/src/graphql/gqlPublicSchema.tsx -> front-end/src/graphql/gqlPrivateSchema.
tsx

Error: Dependency Cycle Found: front-end/src/graphql/gqlPrivateSchema.tsx -> front-end/src/graphql/gqlPublicSchema.tsx -> front-end/src/graphql/gqlPrivateSc
hema.tsx
    at /home/capaj/work-repos/looop/project-alpha/node_modules/dependency-graph/lib/dep_graph.js:43:17
    at /home/capaj/work-repos/looop/project-alpha/node_modules/dependency-graph/lib/dep_graph.js:268:11
    at Array.forEach (<anonymous>)
    at DepGraph.overallOrder (/home/capaj/work-repos/looop/project-alpha/node_modules/dependency-graph/lib/dep_graph.js:267:14)
    at Task.task (/home/capaj/work-repos/looop/project-alpha/node_modules/@graphql-codegen/cli/bin.js:830:42)
    at /home/capaj/work-repos/looop/project-alpha/node_modules/listr/lib/task.js:167:30
```

**To Reproduce**
just run `gql-gen --config codegen.yml`

1. My GraphQL schema:

I can share if needed, but it's quite big, so it's better if I send it over as an archive

2. My GraphQL operations:

I can share if needed, but it's quite big, so it's better if I send it over as an archive

3. My `codegen.yml` config file:

```yml
overwrite: true

generates:
  front-end/src/graphql/gqlPrivateSchema.tsx:
    schema: "gqlSchemas/private.graphql"
    documents:
      - "front-end/**/*.gql"
      - "!front-end/src/app-admin/**"
      - "!front-end/src/pages/auth/**/*.gql"
      - "!front-end/src/components/utils/update-popup/*.gql"
      - "!front-end/src/index/receptionist/*.gql"
      - "!front-end/src/pages/user/operations/public/*.gql"
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - add: "/* THIS IS A GENERATED FILE, DO NOT EDIT */"
  front-end/src/graphql/gqlPublicSchema.tsx:
    schema: "gqlSchemas/public.graphql"
    documents:
      - "front-end/src/pages/auth/**/*.gql"
      - "front-end/src/components/utils/update-popup/*.gql"
      - "front-end/src/index/receptionist/*.gql"
      - "front-end/src/pages/user/operations/public/*.gql"
      - "!front-end/src/app-admin/**"
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - add: "/* THIS IS A GENERATED FILE, DO NOT EDIT */"
  front-end/src/app-admin/graphql/gqlSuperuserSchema.tsx:
    schema: "gqlSchemas/superuser.graphql"
    documents:
      - "front-end/src/app-admin/**"
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - add: "/* THIS IS A GENERATED FILE, DO NOT EDIT */"
  front-end/src/graphql/gqlPrivateSchemaFragments.tsx:
    schema: "gqlSchemas/private.graphql"
    plugins:
      - fragment-matcher
      - add: "/* THIS IS A GENERATED FILE, DO NOT EDIT */"
config:
  withHooks: true
  withHOC: false
  withComponent: false
  apolloReactHooksImportFrom: "./apolloHooksWithThrowingQuery"
  reactApolloVersion: 3
  scalars:
    EmailAddressWithTLD: string
    NonNegativeFloat: number
    NonNegativeInt: number
    PositiveInt: number
    DateTime: string
  namingConvention:
    enumValues: keep
hooks:
  afterOneFileWrite:
    - prettier --write

```

**Expected behavior**
No cycle should be found as on `1.13.0`

**Environment:**

- OS: Ubuntu 19.10
- `@graphql-codegen/...`: 1.13.1
- NodeJS: 12.14.1

**Additional context**

We do share Graphql object types between these two schemas, but it was never a problem before.
