### ISSUE TITLE
Unable to generate requests from a sdl schema

### ISSUE THREAD

**Issue by ericvergnaud** [dotansimha/graphql-code-generator#3698]
**Describe the bug**
Unable to generate requests from a sdl schema

**To Reproduce**
This schema is self contained, no extra document.
I use the typescript and typescript-graphql-request plugins

When I 'generate', it does generate code, but the `getSdk` function does not expose anything.
When I add the schema in the documents section, it complains 'Unable to find any GraphQL types...'

What am I missing?

1. My GraphQL schema:

```graphql
schema {
    query: AllQueries
}

type AllQueries {
    fetchString: String
}
```

2. My GraphQL operations:

described in the schema

3. My `codegen.yml` config file:

```yml
schema: my_schema.graphql
generates:
  my_source_file.d.ts
    plugins:
       - typescript
       - typescript-graphql-request
```

**Expected behavior**
the generated file would expose a `fetchString` function

**Environment:**

- OS: win10
- `@graphql-codegen/1.13.1`: 
- NodeJS: 13.3.0

**Additional context**
I am just looking at generating a ts client that can call any of the queries and mutations exposed by the schema.
If I add `documents: my_schema.graphql` in the yaml, it complains about 'Unable to find any GraphQL type definitions...'
