### ISSUE TITLE
Unable to find any GraphQL type definitions for the following pointers

### ISSUE THREAD

**Issue by AruXc** [dotansimha/graphql-code-generator#3722]
**Describe the bug**
Unable to find any GraphQL type definitions for the following pointers

I found #2979  to resolve my issue

It must be add a query in my server?

**To Reproduce**

1. My GraphQL schema:

```graphql
        type Notice {
          id: ID
          phone: String
          content: String
          status: String
          apply_time: String
          task_time: String
          refkey: String
          seq_length: Int
          source: String
          info: MessageInfo
        }
        type MessageInfo {
          date: String
          name: String
          chr_no: String
          bed_no: String
          pt_phone: String
          status: String
          lab: Lab
        }
        type Lab {
          item_id: String
          value: String
        }
        type Notices {
          notices(id: ID): [Notice]
        }
        query GetNotices {
          notices(id: "123456") {
            id
          }
        }
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
schema: http://localhost:4000/graphql
documents: services/**/*.service.ts
generates:
  generated/types.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-resolvers
    config: 
      typesPrefix: GQL
```

**Expected behavior**

**Environment:**

- OS: 10.15.4
-   "@graphql-codegen/cli": "^1.13.1",
    "@graphql-codegen/typescript": "^1.13.1",
    "@graphql-codegen/typescript-operations": "^1.13.1",
    "@graphql-codegen/typescript-resolvers": "^1.13.1",
- NodeJS: moleculer-apollo-server 

**Additional context**
In my service just have resolver and types now, no mutations

I want to generate type, but will get `Unable to find any GraphQL type definitions for the following pointers` error

and I don't want to add a useless query in my service code, how can I do?
