### ISSUE TITLE
Vue Apollo generated types always require variables/options

### ISSUE THREAD

**Issue by rebolyte** [dotansimha/graphql-code-generator#3733]
**Describe the bug**

Using the awesome @graphql-codegen/typescript-vue-apollo plugin from @iskanderbroere, the generated code has typing errors. Specifically, it requires that variables and options be defined for all queries:

```ts
type ReactiveFunctionGetMeQuery = () => GqlGetMeQueryVariables
export function useGetMeQuery(variables?: GqlGetMeQueryVariables | VueCompositionApi.Ref<GqlGetMeQueryVariables> | ReactiveFunctionGetMeQuery, baseOptions?: VueApolloComposable.UseQueryOptions<GqlGetMeQuery, GqlGetMeQueryVariables>) {
          return VueApolloComposable.useQuery<GqlGetMeQuery, GqlGetMeQueryVariables>(GetMeDocument, variables, baseOptions);
        }
export type GetMeQueryCompositionFunctionResult = ReturnType<typeof useGetMeQuery>;
```

Error: `Argument of type 'GqlGetMeQueryVariables | Ref<GqlGetMeQueryVariables> | ReactiveFunctionGetMeQuery | undefined' is not assignable to parameter of type 'GqlGetMeQueryVariables | Ref<GqlGetMeQueryVariables> | ReactiveFunction<GqlGetMeQueryVariables>'.
  Type 'undefined' is not assignable to type 'GqlGetMeQueryVariables | Ref<GqlGetMeQueryVariables> | ReactiveFunction<GqlGetMeQueryVariables>'.`

**To Reproduce**

1. My GraphQL schema:

```graphql
extend type Query {
  me: UserPayload!
}

type UserPayload {
  user: User!
}

type User {
  userId: ID!
  username: String
  email: String
  firstName: String
  lastName: String
  role: UserRole!
  isDisabled: Boolean!
  createdAt: Date!
  lastUpdated: Date!
}

enum UserRole {
  SUPERADMIN
  ADMIN
  USER
}
```

2. My GraphQL operations:

```graphql
export const GET_ME = gql`
query getMe {
  me {
    user {
      userId
      username
      email
      firstName
      lastName
      role
    }
  }
}`;
```

3. My `codegen.yml` config file:

```yml
schema:
  - http://localhost:4000/graphql:
      headers:
        Authorization: Bearer eyJra...

generates:
  ./packages/web-client/src/__generated__/gql.ts:
    documents: ./packages/web-client/src/graphql/**/*.ts
    config:
      typesPrefix: Gql
      scalars:
        ID: bigint
        Date: string
      useIndexSignature: true
      maybeValue: T | undefined
      withCompositionFunctions: true
      addDocBlocks: false
    plugins:
      - typescript
      - typescript-operations
      - typescript-vue-apollo
```

**Expected behavior**

Queries without variables would have the correct corresponding types. 😁 

**Environment:**

- OS: Win10
- `@graphql-codegen/...`: 1.13.1
- NodeJS: 12.8.1
- `@vue/apollo-composable`: 4.0.0-alpha.6

**Additional context**

This seems to have been introduced with the overloads added in @vue/apollo-composable v4.0.0-alpha.5 in vuejs/vue-apollo#895.
