### ISSUE TITLE
(node:16743) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of undefined

### ISSUE THREAD

**Issue by guiaramos** [dotansimha/graphql-code-generator#3738]
**Describe the bug**
TypeError: Cannot read property 'close' of undefined

**To Reproduce**
when running `graphql-codegen --config codegen.yml`

1. My GraphQL schema:

```graphql
type Action {
  description: String
  id: ID!
  status: TaskStatus
  userAccountable: Profile
  userResponsible: Profile
}

enum ActionStatus {
  APPROVED
  COMPLETED
  PENDING
}

type ActivityLog {
  createdAt: String
  id: ID
  log: String
  task: Task
}

type Cabinet {
  drawers: [Drawer]
  id: ID!
}

type Comment {
  author: Profile
  createdAt: String
  deletedAt: String
  description: String
  file: String
  id: ID
  updatedAt: String
}

type Company {
  affiliates: CompanyAffiliates!
  createdAt: String!
  deletedAt: String!
  departments: [Department]!
  id: ID!
  updatedAt: String!
}

type CompanyAffiliates {
  bosses: [Profile]!
  guests: [Profile]!
  id: ID!
  maintainers: [Profile]!
  owners: [Profile]!
  staffs: [Profile]!
}

type Department {
  affiliates: [DepartmentAffiliates]!
  children: [Department]!
  createdAt: String!
  deletedAt: String!
  id: ID!
  parents: [Department]!
  updatedAt: String!
}

type DepartmentAffiliates {
  bosses: [Profile]!
  guests: [Profile]!
  id: ID!
  maintainers: [Profile]!
  staffs: [Profile]!
}

type Drawer {
  drawers: [Drawer]
  id: ID!
}

type Login {
  count: Int!
  id: ID!
}

type Mutation {
  createAccessToken(refreshToken: String!): TokenModel
  createUser(email: String!, password: String!): Return!

  # User
  loginUser(email: String!, password: String!): TokenModel!
}

type Plan {
  createdAt: String
  deletedYn: Boolean
  description: String!
  id: ID!
  name: String!
  pricing: [Pricing!]!
  updatedAt: String
}

# ### Plans ####
enum PLAN_PRICING_TYPE {
  MONTHLY
  YEARLY
}

type Preferences {
  id: ID!
  profileVisibleTf: Boolean
}

type Pricing {
  benefit: String!
  createdAt: String
  deletedYn: Boolean
  description: String!
  id: ID!
  price: Float!
  type: PLAN_PRICING_TYPE!
  updatedAt: String
}

type Profile {
  createdAt: String!
  deletedAt: String!
  dob: String
  email: String!
  id: ID!
  login: Login!
  name: String!
  plan: Plan!
  preferences: Preferences
  safeUser: SafeUser!
  subscribedAt: String!
  updatedAt: String!
  workspaces: [Workspace!]!
}

type Project {
  afilliates: ProjectAffiliates
  description: String
  endAt: String
  id: ID!
  name: String
  startAt: String
  status: ProjectStatus
}

type ProjectAffiliates {
  admins: [Profile]!
  guests: [Profile]!
  id: ID!
  members: [Profile]!
}

enum ProjectStatus {
  ACTIVE
  CANCELLED
  COMPLETED
  NOSTATUS
  ONHOLD
  PLANNED
}

type Query {
  # User
  fetchMe: Profile!
  fetchUser(userId: String!): Profile!
}

type Return {
  error: String
  ok: Boolean!
}

type SafeUser {
  createdAt: String!
  deletedYn: Boolean
  email: String!
  id: ID!

  # password: String!
  profiles: [Profile!]!
  updatedAt: String!
}

type Seed {
  id: ID!
  timeline: Timeline
}

type Subscription {
  _id: ID!
  createdAt: String
  deletedYn: Boolean
  endDate: String!
  paymentId: ID
  planId: Plan!
  startDate: String!
  status: SUBSCRIPTION_STATES_ENUM!
  updatedAt: String
  userId: ID!
}

# ### Subscription ####
enum SUBSCRIPTION_STATES_ENUM {
  ACTIVE
  CANCELED
  INCOMPLETE
  INCOMPLETE_EXPIRED
  PAST_DUE
  TRIALING
  UNPAID
}

type Task {
  actions: [Action]
  cabinet: Cabinet
  createdAt: String
  deletedAt: String
  description: String
  endAt: String
  files: [String]
  id: ID!
  project: Project
  seed: Seed
  startAt: String
  status: TaskStatus
  title: String
  updatedAt: String
  users: TaskUsers
}

enum TaskStatus {
  CANCELED
  COMPLETED
  ONGOING
  PENDING
}

type TaskUsers {
  accountable: Profile!
  informs: [Profile]!
  request: Profile
  responsibles: [Profile]!
}

type Timeline {
  activityLog: [ActivityLog]
  comments: [Comment]
}

type Token {
  accessedAt: String!
  createdAt: String!
  id: String!
  updatedAt: String!
  userId: String!
}

type TokenModel {
  accessToken: String!
  refreshToken: String
}

type User {
  createdAt: String!
  deletedAt: String!
  deletedYn: Boolean
  email: String!
  id: ID!
  password: String!
  profiles: [Profile!]!
  updatedAt: String!
}

type Workspace {
  company: Company
  id: ID!
  profiles: [Profile]
  projects: [Project]!
  type: WorkspaceType!
}

enum WorkspaceType {
  CORPORATE
  PERSONAL
}

```

2. My GraphQL operations:

```graphql
None
```

3. My `codegen.yml` config file:

```yml
overwrite: true
watch: true
schema:
  - ./src/**/*.graphql
require:
  - ts-node/register
documents: null
hooks:
  afterAllFileWrite:
    - eslint --fix
generates:
  ./src/types/graphql.ts:
    plugins:
      - add: // Auto Generated. Please don't edit, the changes will be overwritten
      - "typescript"
      - "typescript-resolvers"
    config:
      useIndexSignature: true
      typesPrefix: I
      skipTypename: true
      enumsAsTypes: true
      namingConvention:
        typeNames: pascal-case#pascalCase
        enumValues: upper-case#upperCase
    generates:

  ./src/types/schema.graphql:
    plugins:
      - schema-ast
    config:
      commentDescriptions: true
```

**Expected behavior**

**Environment:**

- OS: macOS Catalina version 10.15.3
- `@graphql-codegen/...`:  
    "@graphql-codegen/add": "^1.13.1",
    "@graphql-codegen/cli": "^1.13.1",
    "@graphql-codegen/introspection": "^1.13.1",
    "@graphql-codegen/schema-ast": "^1.13.1",
    "@graphql-codegen/typescript": "^1.13.1",
    "@graphql-codegen/typescript-resolvers": "^1.13.1",
- NodeJS: v13.11.0
**Additional context**
