### ISSUE TITLE
Single import for @apollo/client

### ISSUE THREAD

**Issue by huv1k** [dotansimha/graphql-code-generator#3767]
**Is your feature request related to a problem? Please describe.**
Right now `typescript-react-apollo` with `reactApolloVersion: 3` generates duplicate imports. This is a problem with `eslint` rule `no-duplicate-imports`. 

```ts
import * as ApolloReactCommon from '@apollo/client';
import * as ApolloReactHooks from '@apollo/client';
```

**Describe the solution you'd like**
Provide a single import for `@apollo/client` to prevent problems with linters. 
```ts
import * as ApolloClient from '@apollo/client';
```

**Comment by mehmetnyarar** [comment]
For `"@apollo/client": "^3.0.0-beta.41"`, this seems to work for now:

codegen.yml:

```yml
config:
  apolloReactHooksImportFrom: '@apollo/client'
```

**Comment by vladinator1000** [comment]
@mehmetnyarar I don't lint the file anyway, if anyone is looking for a quick fix, here's my config
```yml
schema: ../yupty-api/server/graphql/**/*.schema.ts
documents:
  - src/**/*{mut,mutation,query,subscription,frag,fragment}.{ts,tsx}
overwrite: true
generates:
  ./src/graphql/generated.tsx:
    plugins:
      - add: '/* eslint-disable */'
      - typescript
      - typescript-operations
      - typescript-react-apollo
    # The combined options of all provided plug-ins
    # More information about the options below:
    # graphql-code-generator.com/docs/plugins/typescript-react-apollo#configuration
    config:
      withHooks: true
      withHOC: false
      withComponent: false
      apolloReactHooksImportFrom: '@apollo/client'
      apolloReactCommonImportFrom: '@apollo/client'
      
```
