### ISSUE TITLE
Unable to find template plugin matching 'typescript-operations'

### ISSUE THREAD

**Issue by jasonlor** [dotansimha/graphql-code-generator#3769]
Can't run graphql-codegen due to typescript-operations and introspection despite them being in devDependencies of package.json.

```
graphql-codegen
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate interfaces/sdk.ts
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Unable to find template plugin matching typescript-operations
    ❯ Generate ./graphql.schema.json
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Unable to find template plugin matching introspection


 Found 2 errors

  ✖ ./graphql.schema.json
    Unable to find template plugin matching 'introspection'
    Install one of the following packages:


    - @graphql-codegen/introspection
    - @graphql-codegen/introspection-template
    - @graphql-codegen/introspection-plugin
    - graphql-codegen-introspection
    - graphql-codegen-introspection-template
    - graphql-codegen-introspection-plugin
    - codegen-introspection
    - codegen-introspection-template
    - introspection

  ✖ interfaces/sdk.ts
    Unable to find template plugin matching 'typescript-operations'
    Install one of the following packages:


    - @graphql-codegen/typescript-operations
    - @graphql-codegen/typescript-operations-template
    - @graphql-codegen/typescript-operations-plugin
    - graphql-codegen-typescript-operations
    - graphql-codegen-typescript-operations-template
    - graphql-codegen-typescript-operations-plugin
    - codegen-typescript-operations
    - codegen-typescript-operations-template
    - typescript-operations


```

**To Reproduce**
graphql-codegen init
yarn gql

I've tried

rm -rf node_modules and reinstalling, no difference.

**package.json**
    "gql": "graphql-codegen --config codegen.yml",

  "devDependencies": {
    "@graphql-codegen/cli": "^1.13.1",
    "@graphql-codegen/introspection": "^1.13.1",
    "@graphql-codegen/typescript": "^1.13.1",
    "@graphql-codegen/typescript-graphql-files-modules": "1.3.1",
    "@graphql-codegen/typescript-graphql-request": "1.13.1",
    "@graphql-codegen/typescript-operations": "1.3.1",
    "typescript": "^3.8.3"

codegen.yml
```yml
overwrite: true
schema:
  - https://*.:
      headers:
        Authorization: Bearer *
documents: "interfaces/**/*.graphql"
generates:
  interfaces/sdk.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-graphql-files-modules"
  ./graphql.schema.json:
    plugins:
      - "introspection"
```

**Environment:**

- OS: 
- NodeJS: 12.16.1
