### ISSUE TITLE
Support for graphql-config

### ISSUE THREAD

**Issue by FredyC** [dotansimha/graphql-code-generator#382]
Instead of arbitrary `gqlgen.json` config, I suggest adding optional support for [graphql-config](https://github.com/prismagraphql/graphql-config). I think it's a good path for crossing gaps between various tooling approaches.

 * Configuration at one place which makes it easier to reuse for other projects.
 * Multiple projects with a different configuration in one file
 * Built-in support for YAML format is a nice addition.

```yaml
projects:
  MyProject:
    schemaPath: schema.graphql
    extensions:
      gqlgen:
        template: graphql-codegen-typescript-template
        skipSchema: true
        documents:
          - src/**/*.gql
      endpoints:
        dev:
          url: 'https://your-app.com/graphql'
```

Config can be per project with possible overrides for an endpoint if necessary. It would always grab local schema file as specified. I believe that downloading schema updates should be a more controlled and I prefer to use a more robust tool [graphql-cli](https://github.com/graphql-cli/graphql-cli) for that job. Ultimately, it would be possible to create a plugin for this CLI tool and essentially run `gqlgen` as a part of the process which would be really awesome.

There is an obvious clash with current `--project` option which would be rather ambiguous. I am not entirely sure how to approach that. Suggestions?
