### ISSUE TITLE
1.13.1 -> 1.13.2 removes comments from schema

### ISSUE THREAD

**Issue by SimenB** [dotansimha/graphql-code-generator#3825]
**Describe the bug**
Comments from the schema are gone in the generated code.

**To Reproduce**

<!--
#############
#############
PLEASE READ THE FOLLOWING:
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type Query {
  # A name!
  name: String!
}
```

2. My GraphQL operations:

```graphql
# none
```

3. My `codegen.yml` config file:

```yml
generates:
  ./gqltypes.ts:
    schema: ./schema.graphql
    plugins:
      - 'typescript'
```

**Expected behavior**
1.13.1 generates comments

```ts
export type Maybe<T> = T | null;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
};

export type Query = {
   __typename?: 'Query';
  /** A name! */
  name: Scalars['String'];
};
```

1.13.2 does not

```diff
diff --git i/gqltypes.ts w/gqltypes.ts
index 41d3dfebf..3172daf0e 100644
--- i/gqltypes.ts
+++ w/gqltypes.ts
@@ -10,6 +10,5 @@ export type Scalars = {
 
 export type Query = {
    __typename?: 'Query';
-  /** A name! */
   name: Scalars['String'];
 };
```

**Environment:**

- OS: macOS
- `@graphql-codegen/...`:  1.13.2
- NodeJS: 12.16.1

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by ardatan** [comment]
Could you add commentDescriptions option like below and try again?
```yaml
generates:
  ./gqltypes.ts:
    schema: 
        - ./schema.graphql:
              commentDescriptions: true
    plugins:
      - 'typescript'
```

**Comment by SimenB** [comment]
That makes no difference

**Comment by ardatan** [comment]
In GraphQL Spec, comments with `#` are deprecated so you need to use `"""` descriptions instead.
You can see here;
https://github.com/graphql/graphql-js/pull/927

Not sure if we change the behavior because supporting both descriptions and comments might break things. @dotansimha 

Maybe the following would work;
```
generates:
  ./gqltypes.ts:
    schema: ./schema.graphql:
    plugins:
      - 'typescript'
    config:
       commentDescriptions: true
```
