### ISSUE TITLE
How to add ID to resolved custom scalar

### ISSUE THREAD

**Issue by zicodeng** [dotansimha/graphql-code-generator#3827]
How do I add optional `Scalars['ID']` to resolved type?

Consider the following type definitions:

```graphql
type User {
  id: ID!
  name: String!
}

type Asset {
  id: ID!
  uploader: User!
}
```
Currently, it generates:

```ts
interface User {
  id: Scalars['ID'];
  name: Scalars['ID'];
}

interface Asset {
  id: Scalars['ID'];
  uploader: User
}
```
What I want: 

```ts
interface Asset {
  id: Scalars['ID'];
  uploader: ID | User
}
```

Why? because on the server-side, I might want to use this type before `Asset.uploader` is resolved to `User`

How do I achieve it? I feel like it should be a common use case, but didn't find a doc for it

Thanks in advance

**Comment by ardatan** [comment]
You can override default types for scalars using `scalars` option. You can find the documentation below.
https://graphql-code-generator.com/docs/plugins/typescript#scalars-scalarsmap

**Comment by zicodeng** [comment]
Hi @ardatan I tried the option but it doesn't seem to work. Below is my config:

```
generates:
  src/gql/__generated__/types.ts:
    config:
      scalars:
        User: ID
    plugins:
      - 'typescript'
```
