### ISSUE TITLE
Option scalars not working

### ISSUE THREAD

**Issue by zicodeng** [dotansimha/graphql-code-generator#3832]
**Describe the bug**
 

**To Reproduce**

<!--
#############
#############
PLEASE READ THE FOLLOWING:
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type User {
  id: ID!
  name: String!
}

type Asset {
  id: ID!
  uploader: User!
}
```
Currently, it generates:

```ts
interface User {
  id: Scalars['ID'];
  name: Scalars['ID'];
}

interface Asset {
  id: Scalars['ID'];
  uploader: User
}
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
generates:
  src/gql/__generated__/types.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      skipTypename: true
      scalars:
        User: ID
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

```ts
interface Asset {
  id: Scalars['ID'];
  uploader: ID
}
```

If I understand how this option works correctly, `User` should be replaced with `ID` 🤔 

**Environment:**

- OS: 
    "@graphql-codegen/cli": "^1.13.2",
    "@graphql-codegen/introspection": "1.13.2",
    "@graphql-codegen/typescript": "^1.13.2",
    "@graphql-codegen/typescript-resolvers": "^1.13.2",
- NodeJS: v13.11.0

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by zicodeng** [comment]
Related: https://github.com/dotansimha/graphql-code-generator/issues/3827 and https://github.com/dotansimha/graphql-code-generator/issues/2342

**Comment by ardatan** [comment]
Could you try the following;
```yaml
generates:
  src/gql/__generated__/types.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      skipTypename: true
      mappers:
        User: Scalars['ID']
```
