### ISSUE TITLE
Question: Why are Apollo queries being ignored, but not Gatsby queries?

### ISSUE THREAD

**Issue by davidleger95** [dotansimha/graphql-code-generator#3853]
I'm trying to generate types based on my Apollo queries. This will generate types for the schema currently but not types for individual queries that are tagged with `gql`. The config for generating types form Gatsby queries (tagged with `graphql`) works fine.

For some reason, it's ignoring the Apollo queries and just outputting the generic types for the schema. Is there something I'm missing?

```yml
generates:
  # ignore this first config, it's for the gatsby types and it works fine
  ./src/types/graphql.ts:
    schema: schema.json
    documents:
      - ./src/**/*.{ts,tsx}
      - ./node_modules/gatsby-*/**/*.js
    pluckConfig:
      modules:
        - name: 'gatsby'
          identifier: 'graphql'
    overwrite: true
    config:
      namingConvention:
        enumValues: keep
    hooks:
      afterOneFileWrite:
        - prettier --write
    plugins:
      - typescript
      - typescript-operations
  # here's the one for apollo queries that doesn't work
  ./src/types/apollo-graphql.ts:
    schema: functions/schema.js
    overwrite: true
    documents:
      - ./src/**/*.{ts,tsx}:
        noRequire: true
    pluckConfig: # this doesn't seem to do anything
      modules:
        - name: '@apollo/client'
          identifier: 'gql'
    hooks:
      afterOneFileWrite:
        - prettier --write
    plugins:
      - typescript
      - typescript-operations
```
