### ISSUE TITLE
Question: how to import types from Urigo/graphql-scalars?

### ISSUE THREAD

**Issue by Sladuca** [dotansimha/graphql-code-generator#3857]
Hi,

I'm using types defined in [graphql-scalars](https://github.com/Urigo/graphql-scalars) in my schema. For example, my schema has:

```graphql
type User {
  id: ID!
  name: String!
  email: EmailAddress!
  verified: Boolean!
  type: UserType!
  userData: UserData
}
```
where `EmailAddress` is defined by `graphql-scalars`.  I've spent a lot of time trying to import the types, and it would be awesome if someone were able to help.

Right now it always fails with:

```
 Failed to load schema from src/schema.graphql:

        Type "EmailAddress" not found in document.
        Error: Type "EmailAddress" not found in document.
```

Here's my `codegen.yml`:

```yaml
overwrite: true
schema: "src/schema.graphql"
documents: null
generates:
  src/gen/graphql.ts:
    preset: import-types
    presetConfig:
      typesPath: src/scalars.ts
    plugins:
      - "typescript"
      - "typescript-resolvers"
      - "typescript-document-nodes"
  ./graphql.schema.json:
    plugins:
      - "introspection"
```

and `src/scalars.ts`

```typescript
export { 
  EmailAddressResolver,
  EmailAddressTypeDefinition,
  URLResolver,
  URLTypeDefinition,
  DateTimeResolver,
  DateTimeTypeDefinition,
  PostalCodeResolver,
  PostalCodeTypeDefinition,
  PhoneNumberResolver,
  PhoneNumberTypeDefinition
} from 'graphql-scalars';
```

Thank you in advance - this tool is awesome!
