### ISSUE TITLE
[Plugin Request] Mongoose models?

### ISSUE THREAD

**Issue by dandv** [dotansimha/graphql-code-generator#3859]
Background: I saw in #179 that @blissi mentioned a mongoose template. Where can one find that? I don't see mongoose among the examples in the [live demo](https://graphql-code-generator.com/#live-demo), or among [the plugins](https://graphql-code-generator.com/docs/plugins/).

Mongoose is quite popular, so I'm surprised there's no generator for it. Do people use something else? There are a 6+ [libraries trying to unify the definitions between TypeScript classes and mongoose models](https://stackoverflow.com/questions/34482136/mongoose-the-typescript-way/61154023#61154023) so it seems there would definitely be a need for a mongoose generator.

**Comment by myhendry** [comment]
@dandv I understand if you were to add in typescript-mongodb under plugins, it will type your mongoose models

**codegen.yml**
```
overwrite: true
schema: "http://localhost:4000/graphql"
documents: null
generates:
  src/__generated__/types.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
      - "typescript-mongodb"
  ./graphql.schema.json:
    plugins:
      - "introspection"

```
