### ISSUE TITLE
generated hooks don't take defaultOptions of your client into account

### ISSUE THREAD

**Issue by maapteh** [dotansimha/graphql-code-generator#3867]
**Describe the bug**
In my Apollo client i have set defaultOptions with an errorPolicy: 'all' for query and mutation which is used to prevent the treewalker to actually throw an error on any ssr Error :)

But the generated hook doesn't use these defaults at al,l while if i simply use useQuery from their package it works correctly. I didnt look further in the code but wanted to file the bug first

**To Reproduce**
Use defaultOptions in your Apollo client

```
    const client = new ApolloClient({
        cache,
        resolvers: {},
        ...SNIP
        queryDeduplication: true,
        defaultOptions: {
            mutate: {
                errorPolicy: 'all',
            },
            query: {
                errorPolicy: 'all',
            },
        },
    });
```

Now let one of your queries throw an error on graphql side. Normally the error should be picked up. But when using the generated hook it will not pick it up and literally throw the error while treewalking.

3. My `codegen.yml` config file:

```yml
schema:
    - 'https://ah-graphql-playground.tst.k8s.ecom.ahold.nl/graphql'
overwrite: true
require:
    - ts-node/../../codegen-interpreter.ts
documents:
    [
        './src/common/**/*.graphql.ts',
        './src/graphql/queries/*.ts',
        './src/graphql/fragments/*.ts',
    ]
config:
    namingConvention:
        enumValues: change-case#upperCase
generates:
    src/graphql/_generated-types.ts:
        config:
            noNamespaces: true
            avoidOptionals: true
        plugins:
            - add: "/* THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */\n"
            - 'typescript'
            - 'typescript-operations'
    src/graphql/_generated-hooks.tsx:
        plugins:
            - add: "/* eslint-disable */\n/* AUTO GENERATED, DO NOT EDIT OVERHERE */"
            - typescript
            - typescript-operations
            - typescript-react-apollo
        config:
            reactApolloVersion: 2
            reactApolloImportFrom: '@apollo/react-hooks'
            withComponent: false
            withHOC: false
            withHooks: true
            avoidOptionals: true
    src/graphql/_generated-fragment-types.ts:
        plugins:
            - 'fragment-matcher'

```

**Expected behavior**
Having the client defaultOptions being the default options :)

**Environment:**
```
        "@graphql-codegen/add": "1.12.2",
        "@graphql-codegen/cli": "1.12.2",
        "@graphql-codegen/fragment-matcher": "1.12.2",
        "@graphql-codegen/schema-ast": "1.12.2",
        "@graphql-codegen/time": "1.12.2",
        "@graphql-codegen/typescript-operations": "1.12.2",
        "@graphql-codegen/typescript-react-apollo": "1.12.2",
        "@graphql-codegen/typescript-resolvers": "1.12.2",
```
