### ISSUE TITLE
Field wrapper doesn't wrap types in array

### ISSUE THREAD

**Issue by alex-knyazev** [dotansimha/graphql-code-generator#3882]
When I set fieldWrapper I expect that Types in Arrays will be wrapped too

**To Reproduce**

My `codegen.yml` config file:

```yml
    config:
      skipTypename: true
      wrapFieldDefinitions: true
      fieldWrapperValue: 'T | { valueOf(): T }'
      maybeValue: T | undefined
      typesPrefix: API_
      namingConvention:
        typeNames: pascal-case#pascalCase
        enumValues: camel-case#camelCase
```

My GraphQL type:

```javascript

const CustomersPayload = new GraphQLObjectType({
  name: 'CustomersPayload',
  fields: () => ({
    edges: {
      type: GraphQLNonNull(GraphQLList(GraphQLNonNull(Customer))),
    },
  }),
})
```

**Generated type**
```
export type API_CustomersPayload = {
  edges: FieldWrapper<Array<API_Customer>>
}
```

**Expected behavior**
Should generate 
```
export type API_CustomersPayload = {
  edges: Array<FieldWrapper<API_Customer>>
}
```
**Environment:**

- `@graphql-codegen/packages/typescript/typescript`: 
- NodeJS:
