### ISSUE TITLE
Federation: Split types by services?

### ISSUE THREAD

**Issue by sarink** [dotansimha/graphql-code-generator#3892]
The [docs](https://graphql-code-generator.com/docs/generated-config/base-resolvers-visitor#federation-boolean-default-value-false) show that there's a `federation: true` config flag. Is there any explanation on what this actually does?

Specifically, what I'm wondering is, assume a folder structure like:
```
gateway.ts
- services
  - service-a
    resolvers.ts
    typedefs.ts
    server.ts
  - service-b
    resolvers.ts
    typedefs.ts
    server.ts
```
How should we generate a different set of types for each service? And what about common typedefs/functionality?

What is the recommended federation setup/approach?

Thanks!

**Comment by dotansimha** [comment]
@kamilkisiela what do you think?

**Comment by fvanwijk** [comment]
I found out that you have to generate types per service, because a single service shouldn't be aware of the other services.
If you want to generate types for a client, you can generate them based on all (federated) schemas.

There seems to be a 'project' flag/setting but it is not documented, so I'm not sure how to use it.
What I do is to create a codegen.yml per service with some duplication.

**Comment by kamilkisiela** [comment]
Following the Federation spec means each service does not need to be aware of each other.

```yaml
generates:
  ./services/a.ts:
    schema: ./services/a.graphql
    config: 
      federation: true
  ./services/b.ts:
    schema: ./services/b.graphql
    config: 
      federation: true
  ./web/types.ts:
    schema: ./services/*.graphql
    config: 
      federation: true
```
