### ISSUE TITLE
Codegen with 2 outputs: 1 succeeds, 1 fails but both not written to file

### ISSUE THREAD

**Issue by eyalw** [dotansimha/graphql-code-generator#3900]
**Describe the bug**
I have two outputs, one schema-ast, the other typescript types. 
both run in the same config, the schema completes with a green checkmark, the typescript fails (as expected, because of an intentional code error). But the schema is not written to file although it says it did.

![image](https://user-images.githubusercontent.com/608669/79739321-b781c900-8306-11ea-895f-a73ec6e8c93b.png)
As you can see, 2 outputs, one finishes with success, the other fails. but the successful output is not written to file either. It is important the schema outputs correctly even though the typescript output does not, because i use the schema for eslint/vscode-autocompletion to fix the error.

**To Reproduce**
Just use 2 outputs have one fail the other succeed.

1. My GraphQL schema:

```graphql
# not relevant
```

2. My GraphQL operations:

```graphql
# not relevant
```

3. My `codegen.yml` config file:

```yml
schema:
  # Stitch all other microservices schemas into one
  # We are being as specific as we can, not to watch hundreds of files, because then CPU goes 100%
  - '../gqlgen/**/*.graphql'
  # Define Apollo custom directives that eslint doesn't know about so we don't get errors
  - './apolloFederationSpec.graphql'
overwrite: true
generates:
  ./schema.generated.graphql:
    plugins:
      - 'schema-ast'
    config:
      includeDirectives: true
  ./src/@generated/graphqlTypes.ts:
    documents:
      - './src/**/*.{ts,tsx}'
      # Exclude the generated files, so we don't get duplications
      - '!./src/@generated/**'
    plugins:
      - typescript
      - typescript-operations
      # for useQuery hooks:
      - typescript-react-apollo
      # for client-side mocks in apollo
      - typescript-resolvers
    # See: graphql-code-generator.com/docs/plugins/typescript-react-apollo#configuration
    config:
      # scalar => TS type mapping
      scalars:
        DateTime: number
        JSON: string
      withHOC: false
      withHooks: true
      withComponent: false
      reactApolloVersion: 3

```

**Expected behavior**

**Environment:**

- OS: Mac OS 10.15.4
- NodeJS: 12.14.1
"@graphql-codegen/cli": "^1.13.3",
    "@graphql-codegen/introspection": "1.13.3",
    "@graphql-codegen/schema-ast": "^1.13.3",
    "@graphql-codegen/typescript": "1.13.3",
    "@graphql-codegen/typescript-operations": "1.13.3",
    "@graphql-codegen/typescript-react-apollo": "1.13.3",
    "@graphql-codegen/typescript-resolvers": "^1.13.3",
