### ISSUE TITLE
SyntaxError: 'return' outside of function

### ISSUE THREAD

**Issue by smashercosmo** [dotansimha/graphql-code-generator#3913]
**Describe the bug**
After regenerating package-lock started getting this error
```
> graphql-codegen --config codegen.yml

  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./src/types/generated/graphql.ts
      ✔ Load GraphQL schemas
      ✖ Load GraphQL documents
        → 'return' outside of function (13:4)
        Generate


 Found 1 error

  ✖ ./src/types/generated/graphql.ts
    SyntaxError: 'return' outside of function (13:4)
        at Object._raise (/Users/path-to-project/node_modules/@babel/parser/lib/index.js:742:17)
        at Object.raiseWithData (/Users/path-to-project/node_modules/@babel/parser/lib/index.js:735:17)
```

**To Reproduce**

I'm using graphql-code-generator with Gatsby

```yml
overwrite: true
schema: "http://localhost:8000/___graphql"
documents:
  - ./src/**/*.{ts,tsx}
  - ./node_modules/gatsby-*/**/*.js
generates:
  ./src/types/generated/graphql.ts:
    hooks:
      afterOneFileWrite:
        - prettier --write
    plugins:
      - typescript
      - typescript-operations
config:
  namingConvention:
    enumValues: keep
  avoidOptionals: true
  immutableTypes: true
  maybeValue: T
```

**Environment:**

  System:
    OS: macOS Mojave 10.14
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.113
    Firefox: 72.0.2
    Safari: 12.0
  npmPackages:
    gatsby: 2.20.23
    @graphql-codegen/cli: 1.13.2
    @graphql-codegen/introspection: 1.13.2
    @graphql-codegen/typescript: 1.13.2
    @graphql-codegen/typescript-operations: 1.13.2
