### ISSUE TITLE
Custom Scalars option not working

### ISSUE THREAD

**Issue by binier** [dotansimha/graphql-code-generator#3962]
**Describe the bug**
@graphql-codegen/typescript scalars config not working. I believe I tried every possible way to include scalars config in codegen.yml but none work.

```
Error: Type "DateTime" not found in document.
```

**To Reproduce**
live sandbox: https://codesandbox.io/s/keen-knuth-iscus

1. My GraphQL schema:

```graphql
type User {
  date: DateTime
}
```

2. My `codegen.yml` config file (not sure which definition is correct, so added all possible ones. have tried separately each one too):

```yml
schema: schema.graphql
documents: document.graphql
scalars:
  DateTime: Date
config:
  scalars:
    DateTime: Date
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
    scalars:
      DateTime: Date
    config:
      scalars:
        DateTime: Date
```

**Expected behavior**
should add DateTime to scalars and not crash.

**Environment:**
- `@graphql-codegen/...`: 1.13.3
