### ISSUE TITLE
[urql] should respect omitOperationSuffix and typesPrefix options

### ISSUE THREAD

**Issue by FredyC** [dotansimha/graphql-code-generator#3968]
**Describe the bug**
I am used to prefixing my operations with `Q/M/S/F` so I opted enabled option `omitOperationSuffix`. Unfortunately, the urql plugin doesn't consider that and uses wrong type names., Also for a reason, I like to prefix types with `T` which is ignored by plugin as well. 

https://github.com/dotansimha/graphql-code-generator/blob/db1db14ad43bdd876b4eab053d41b074b872359c/packages/plugins/typescript/urql/src/visitor.ts#L87

**To Reproduce**

I tried to reproduce in codesandbox, but it's giving me weird errors: https://codesandbox.io/s/affectionate-montalcini-zcpsv?file=/codegen.yml

<!--
#############
#############
PLEASE READ THE FOLLOWING:
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    email: String!
}
```

2. My GraphQL operations:

```graphql
# Put your operations here
query user {
    user(id: 1) {
        id
        email
    }
}
```

3. My `codegen.yml` config file:

```yml
# Put your YML here
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-urql
    config:
      typesPrefix: T
      omitOperationSuffix: true
      withComponent: false
      withHooks: true
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

The emitted types should not use operation type suffix when `omitOperationSuffix` is enabled. And `typesPrefix` should be respected.
