### ISSUE TITLE
Mappers are not used for union types

### ISSUE THREAD

**Issue by darkbasic** [dotansimha/graphql-code-generator#3979]
GraphQL schema:
```graphql
type A {
  id: ID!
  a: Int!
}

type B {
  id: ID!
  b: Int!
}

union AOrB = A | B
```

codegen config:
```yml
mappers:
  A: ./types#MyA
  B: ./types#MyB
```

**Expected behavior**

The union `AOrB` type should be automatically mapped to `MyA | MyB`, but it doesn't.
A quick workaround is to manually map it like this:

```yml
mappers:
  A: ./types#MyA
  B: ./types#MyB
  AOrB: ./types#MyAOrB
```

where `MyAOrB` is simply `MyA | MyB`.
