### ISSUE TITLE
init does not work out of the box

### ISSUE THREAD

**Issue by theogravity** [dotansimha/graphql-code-generator#3992]
I executed `npx graphql-codegen init` for just a backend server

I have a `schema.graphql` file i've built, and the generated `codegen.yml` reads like this:

```
overwrite: true
schema: "schema.graphql"
documents: null
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
  ./graphql.schema.json:
    plugins:
      - "introspection"
```

when I run the generate command, I get

```
  ✖ src/generated/graphql.ts
    Unable to find template plugin matching 'typescript-resolvers'
    Install one of the following packages:
    - @graphql-codegen/typescript-resolvers

...

  ✖ ./graphql.schema.json
    Unable to find template plugin matching 'introspection'
    Install one of the following packages:
    - @graphql-codegen/introspection
...
```

the init script added to my `package.json` (I have run `npm i` to make sure it's installed):

```
    "@graphql-codegen/typescript": "1.13.5",
    "@graphql-codegen/typescript-resolvers": "1.13.5",
    "@graphql-codegen/introspection": "1.13.5"
```

so I'm not clear what's missing here.

node version `12.16.1`, using npm `6.13.4`
