### ISSUE TITLE
Unused fragment imports

### ISSUE THREAD

**Issue by andreyvital** [dotansimha/graphql-code-generator#4000]
**Describe the bug**
If you have a fragment that imports other fragments, the generated code contains unused imports.

**To Reproduce**

1. My GraphQL operations:

```TS
export default gql`
  fragment AssetDiscussionCommentFields on AssetDiscussionComment {
    _id
    shortId
    bodyAsPlainText
    postedAt

    viewerCanDestroy
    viewerCanEdit
    viewerCanReply

    ...LockableCommentFields
    ...PinnableCommentFields
    ...EditableCommentFields
    ...ReactableFields
  }

  ${LockableCommentFields}
  ${PinnableCommentFields}
  ${EditableCommentFields}
  ${CommentOrReplyAuthorFields}
  ${ReactableFields}
`;
```

2. My `codegen.yml` config file:

```yml
schema: http://localhost:25256

generates:
  types/introspection-result.ts:
    plugins:
      - "fragment-matcher"

  types/graphql-types.ts:
    plugins:
      - "typescript"
      - "typescript-operations"

    config:
      typesPrefix: I
      immutableTypes: false
      skipTypename: false
      avoidOptionals: true
      nonOptionalTypename: true

  .:
    documents: "{components,lib}/**/*.ts"
    preset: near-operation-file

    presetConfig:
      extension: .generated.ts
      baseTypesPath: ./types/graphql-types.ts

    plugins:
      - typescript-operations

    config:
      typesPrefix: I
      avoidOptionals: true
      nonOptionalTypename: true
      namingConvention:
        typeNames: pascal-case#pascalCase
        enumValues: upper-case#upperCase
        transformUnderscore: true
```

**Expected behavior**
The generated code shouldn't import unused fragments.

- OS: 
```JSON
"@graphql-codegen/cli": "^1.13.5",
"@graphql-codegen/fragment-matcher": "^1.13.5",
"@graphql-codegen/near-operation-file-preset": "^1.13.5",
"@graphql-codegen/typescript": "^1.13.5",
"@graphql-codegen/typescript-operations": "^1.13.5"
```
