### ISSUE TITLE
Duplicate import from @apollo/client

### ISSUE THREAD

**Issue by oceandrama** [dotansimha/graphql-code-generator#4008]
Config
```
plugins:
  - "typescript"
  - "typescript-operations"
  - "typescript-react-apollo"
config:
  reactApolloVersion: 3
  withComponent: false
  withHOC: false
  withHooks: true
  withMutationFn: false
  withMutationOptionsType: false
  withResultType: false
```
Result
```
import gql from 'graphql-tag';
import * as ApolloReactCommon from '@apollo/client';
import * as ApolloReactHooks from '@apollo/client';
```
Repro - https://codesandbox.io/s/sad-joliot-cb7t8?file=/types.ts

Expect
1. No double import
2. Using gql from `@apollo/client`

> The gql template tag should now be imported from the @apollo/client package, rather than the graphql-tag package. Although the graphql-tag package still works for now, future versions of @apollo/client may change the implementation details of gql without a major version bump.
https://github.com/apollographql/apollo-client/pull/5451

**Comment by ardatan** [comment]
So what's the issue in current generated file? Is there any problem with the functionality?

**Comment by oceandrama** [comment]
I have 3 non-fixable eslint and typescript errors
`'ApolloReactCommon' is declared but its value is never read.ts(6133)`
`'ApolloReactCommon' is defined but never used.eslint@typescript-eslint/no-unused-vars`
`'\node_modules\@apollo\client\apollo-client.cjs.js' imported multiple times.eslintimport/no-duplicates`

**Comment by ardatan** [comment]
I think those are linting errors and not effective in terms of functionality. So you can do the following to bypass those warnings and errors.
```
plugins:
  - add: /* eslint-disable */ 
  - "typescript"
  - "typescript-operations"
  - "typescript-react-apollo"
config:
  reactApolloVersion: 3
  withComponent: false
  withHOC: false
  withHooks: true
  withMutationFn: false
  withMutationOptionsType: false
  withResultType: false
```
