### ISSUE TITLE
Typescript resolver mappers not replacing all instances of mapped type

### ISSUE THREAD

**Issue by danfernand** [dotansimha/graphql-code-generator#4021]
**Describe the bug**

There is an issue where I am using typescript resolvers plugin and when setting up mappers to replace types not all instances of the type are being replaced

**To Reproduce**

If I create a mapper for `SomeConnection` using `codegen.yml` it only replaces the connection from the main query, not the one in NewThing

<!--
#############
#############
PLEASE READ THE FOLLOWING:
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type Query {
    someQuery(
      someInput: ID!
  ): SomeConnection
  newQuery(
    newInput: ID!
  ): NewConnection
}

type SomeConnection {
  something: Something
}

type Something {
  somethingElse: SomethingElse
}

type SomethingElse {
  field1: String
  field2: String
}

type NewConnection {
  newThing:  NewThing
}

type NewThing {
  someConnection(someInput: ID!): SomeConnection
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.json
skipGraphQLImport: true
generates:
  packages/graphql-server/src/types/resolverTypes.ts:
    config:
      contextType: ../util/context#ContextGen
      noSchemaStitching: true
      skipTypename: true
      namingConvention:
        typeNames: change-case#pascalCase
        enumValues: keep
      mappers: # these are my real types
        DeliveryScope: ./mappers#DeliveryScopeWithArgs
        DeliveryScopesConnection: ./mappers#DeliveryScopesConnectionWithArgs
        DeliveryScopeRule: ./mappers#DeliveryScopeRuleWithArgs
        DeliveryScopeRulesConnection: ./mappers#DeliveryScopeRulesConnectionWithArgs
      scalars:
        Upload: "Promise<FileUpload>"
    plugins:
      - add: "/* eslint-disable */"
      - add: 'import { FileUpload } from "graphql-upload";'
      - typescript
      - typescript-resolvers
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

```
    "@graphql-codegen/add": "^1.13.5",
    "@graphql-codegen/cli": "^1.13.5",
    "@graphql-codegen/typescript": "^1.13.5",
    "@graphql-codegen/typescript-operations": "^1.13.5",
    "@graphql-codegen/typescript-react-apollo": "^1.13.5",
    "@graphql-codegen/typescript-resolvers": "1.13.5",
```

- OS: MacOs Mojave 10.14.6
- NodeJS: v12.16.1

**Additional context**
<!-- Add any other context about the problem here. -->
