### ISSUE TITLE
Enums with different multiple casings generate invalid typescript

### ISSUE THREAD

**Issue by nickcarenza** [dotansimha/graphql-code-generator#4043]
**Describe the bug**
GraphQL schemas with multiple differently-cased enum values generates invalid typescript.

Using Braintree graphql schema https://github.com/braintree/graphql-api/blob/master/schema.graphql

**To Reproduce**

https://codesandbox.io/s/gifted-mirzakhani-dc4px?file=/types.ts

1. My GraphQL schema:

```graphql
enum ClientConfigurationEnvironment {
  DEVELOPMENT
  PRODUCTION
  QA
  SANDBOX
  TEST
  development
  production
  qa
  sandbox
  test
}
```

2. My GraphQL operations: N/A

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
generates:
  types.ts:
    plugins:
      - typescript
```

**Expected behavior**

Typescript output:
```typescript
enum ClientConfigurationEnvironment {
  "DEVELOPMENT",
  "PRODUCTION",
  "QA",
  "SANDBOX",
  "TEST",
  "development",
  "production",
  "qa",
  "sandbox",
  "test",
}
```

**Actual Behavior**
```typescript
export enum ClientConfigurationEnvironment {
  Development = 'DEVELOPMENT',
  Production = 'PRODUCTION',
  Qa = 'QA',
  Sandbox = 'SANDBOX',
  Test = 'TEST',
  Development = 'development',
  Production = 'production',
  Qa = 'qa',
  Sandbox = 'sandbox',
  Test = 'test'
}
```

**Comment by nickcarenza** [comment]
It looks like there are already configuration options in place to deal with this sort of thing.

```yaml
generates:
  src/sdk.ts:
    plugins:
      - typescript
    config:
      namingConvention: keep
```
