### ISSUE TITLE
Type generation doesn't work properly with a federated approach

### ISSUE THREAD

**Issue by gabrielmendezc** [dotansimha/graphql-code-generator#4062]
This is my codegen.yml:

```yml
schema: './src/graphql/schema.graphql'
documents: null
generates:
  src/graphql/generated.ts:
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
    config:
      federation: true
```

However, there's no __resolveReference or any other federation related types being generated so I have to manually type that which isn't ideal whatsoever.

Here's a reproduction of the issue https://codesandbox.io/s/festive-leaf-ko9ou?file=/types.ts
