### ISSUE TITLE
[typescript-resolvers] Only require model field resolvers for fields absent/mismatched in mappers

### ISSUE THREAD

**Issue by affanshahid** [dotansimha/graphql-code-generator#4069]
Say I have the following schema:
```graphql
type Todo {
    id: ID!
    text: String!
    done: Boolean!
    author: User!
}

type User {
    id: ID!
    name: String!
}
```

and I am using the following model mapper for Todo:
```ts
export type Todo = {
  id: string
  text: string
  done: boolean
  userId: string
}
```

When I generate resolver types (with `avoidOptionals: true`) it will generate types that require me to add field-resolvers for each field in Todo. 

Apollo server takes the object property with the same name if a field-resolver is not provided, so technically the only **required** field-resolver should be for the `user` field since its missing in the mapper type.

Is there a way I can generate resolver-types that behave like I described?

**Comment by dotansimha** [comment]
@affanshahid you can turn of `avoidOptionals` only for the resolvers plugin, this way:

```yml
generates:
  resolvers.ts:
    plugins:
      - typescript:
          avoidOptionals: true
      - typescript-resolvers:
          avoidOptionals: false
```
