### ISSUE TITLE
add with content options does not work as documented

### ISSUE THREAD

**Issue by anark** [dotansimha/graphql-code-generator#4074]
**Describe the bug**
I'm trying to use the 'add' module to add content to the output.  

When I try to use the add plugin without a content key(see below)and just a string it works fine
```
plugins:
  - add: "import { gql } from '@apollo/client'"
  - add: "export default gql`"
  - schema-ast
```

 however if I try to use add with a content key as documented in https://graphql-code-generator.com/docs/plugins/add I get Error: Add plugin, missing content

```
plugins:
  - add: "import { gql } from '@apollo/client'"
  - add: "export default gql`"
  - schema-ast
  - add:
    content: "`"
    placement: 'append'
```

```
    Error: Add plugin, missing content
        at Object.plugin (/Users/andrewnarkewicz/Development/sky-pilot/node_modules/@graphql-codegen/add/index.cjs.js:27:15)
 
```

However if you double indent the content option it will work.  It is quite confusing that the content and placement options need to be double indented and hard to tell when viewing the docs that that was the requirement.

```
plugins:
  - add: "import { gql } from '@apollo/client'"
  - add: "export default gql`"
  - schema-ast
  - add:
      content: "`"
      placement: 'append'
```

**To Reproduce**
add
```
  - add:
    content: "Added Content"
```
to your codegen.ym
<!--
#############
#############
PLEASE READ THE FOLLOWING:
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->
https://codesandbox.io/s/clever-sara-5ufb2?file=/codegen.yml

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
Expect types file to be created with the "Added Content".

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**
<!-- Add any other context about the problem here. -->
