### ISSUE TITLE
Codegen doesn't recoginize types from external files

### ISSUE THREAD

**Issue by fetis** [dotansimha/graphql-code-generator#4109]
Hello

I'm generating server types directly from .ts files with the next config
```yaml
overwrite: true
schema:
  - "./src/**/*.typedefs.ts"
  - "./src/**/*.schema.ts"
generates:
  ./src/models/types.ts:
    plugins:
      - add: "/* tslint:disable */"
      - "typescript"
```

my typedefs are split across several files

`test.schema.ts`
```
  type Address {
    countryCode: CountryCode
  }

  ${countryCodeTypeDef}
```

`countrycode.typedefs.ts`  
```typescript
export const countryCodeTypeDef = gql`
  enum CountryCode {
    FR
    DE
    SE
  }
`;
```

with this configuration, Apollo Server starts perfectly but when I generate server types I get next error
```
  ✖ ./src/models/types.ts
    Failed to load schema from ./src/**/*.typedefs.ts,./src/**/*.schema.ts:

        Unknown type: "CountryCode".
        Error: Unknown type: "CountryCode".
``` 

**Expected behavior**

I expect the types to be generated normally

**Environment**
- OS: MacOS
- "@graphql-codegen/cli": "^1.14.0",: 
- NodeJS: v12.4.0
