### ISSUE TITLE
Resolver type of interface

### ISSUE THREAD

**Issue by jer-sen** [dotansimha/graphql-code-generator#4131]
```
type B1 implements B  {
	prop1: String!
	prop: String!
}

type B2 implements B {
	prop2: String!
	prop: String!
}

interface B {
	prop: String!
}

type A {
	b: B
}

extend type Query {
	getA: A!
}
```

gives the following type:

```
export type A = {
  readonly __typename?: 'A';
  readonly b: Maybe<B>;
};
```

but should give that instead:

```
export type A = {
  readonly __typename?: 'A';
  readonly b: Maybe<B1 | B2>;
};
```

**Comment by dotansimha** [comment]
@jer-sen which plugins do you use? can you please share your `codegen.yml` file? and also the GraphQL operations you are using. Also, which version of codegen do you use?

**Comment by jer-sen** [comment]
My `codegen.yml` looks like:

```
schema: // Cf code provided with issue
documents: // Non relevant, the issue involves schema types, not operations
generates:
  serverTypes.ts:
    plugins:
      typescript:
        avoidOptionals:
          field: true
          inputValue: false
          object: true
      typescript-resolvers:
        avoidOptionals: false
    config:
      immutableTypes: true
      useIndexSignature: true
      namingConvention:
        enumValues: upper-case#upperCase
```

Versions:

```
+-- @graphql-codegen/add@1.14.0
+-- @graphql-codegen/cli@1.14.0
+-- @graphql-codegen/fragment-matcher@1.14.0
+-- @graphql-codegen/introspection@1.14.0
+-- @graphql-codegen/schema-ast@1.14.0
+-- @graphql-codegen/typescript@1.14.0
+-- @graphql-codegen/typescript-document-nodes@1.14.0
+-- @graphql-codegen/typescript-operations@1.14.0
+-- @graphql-codegen/typescript-resolvers@1.14.0
+-- graphql@15.0.0
```

I will follow issue template next time. Sorry for this one.
