### ISSUE TITLE
typescript-resolvers - Type mismatch with apolloClient's resolvers

### ISSUE THREAD

**Issue by jazzdragon** [dotansimha/graphql-code-generator#4137]
**Describe the bug**

After generating types from my resolvers the `resolvers` field in `new apolloClient()` complains for types being mismatched:

Error:(92, 5) TS2322: Type 'Resolvers<any>' is not assignable to type 'Resolvers | Resolvers[] | undefined'.
  Type 'Resolvers<any>' is not assignable to type 'Resolvers'.
    Property 'Mutation' is incompatible with index signature.
      Type 'MutationResolvers<any, {}> | undefined' is not assignable to type '{ [field: string]: Resolver; }'.
        Type 'undefined' is not assignable to type '{ [field: string]: Resolver; }'.

**To Reproduce**

Create an apollo client instance with resolvers and a generated resolvers type from codegen.

1. My GraphQL schema:

```graphql
directive @client on FIELD

type Mutation {
  sayHi: String!
}
```

2. My GraphQL operations:

```graphql
mutation sayHi {
  sayHi @client
}
```

3. My `codegen.yml` config file:

```yml
config:
  withHOC: false
  withHooks: true
  withComponent: false
  hooksImportFrom: "@apollo/react-hooks"
generates:
  src/types/resolvers.ts:
    overwrite: true
    schema: ./local.graphql
    plugins:
      - typescript
      - typescript-resolvers
```

**Expected behavior**
The resolver types should match to the apollo one without errors

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**
Apollo's type definition is here: https://github.com/apollographql/apollo-client/blob/version-2.6/packages/apollo-client/src/core/types.ts#L50
