### ISSUE TITLE
Consume Schema from Apollo Graph Manager

### ISSUE THREAD

**Issue by mikefisher84** [dotansimha/graphql-code-generator#4171]
Apollo Engine/Graph Manager is the published source of truth for our GraphQL schema. I'd like to automatically generate my typescript types based on the information in Apollo Engine/Graph Manager

**Describe the solution you'd like**
I'd like for graphql-code-generator to be able to pull down the schema from Apollo Engine/Graph Manager. I'd also like to be able to specific the schema variant if possible. 

**Describe alternatives you've considered**
Using Apollo CLI for type generation

If this is already possible my apologies!

**Comment by ardatan** [comment]
@mikefisher84 
We already have this feature for a while;
https://github.com/dotansimha/graphql-code-generator/issues/3047

**Comment by mikefisher84** [comment]
Thanks for the heads up! This feature doesn't seem to be documented.

**Comment by ardatan** [comment]
Yes you're right. We haven't documented it yet :( Default value for endpoint has been added but I think it is not in the codegen yet.
I'll take a look at the issue and keep you posted.

**Comment by ardatan** [comment]
@mikefisher84 Could you fix the indentation like below;
```
schema:
  - apollo-engine:
       engine:
         apiKey: ${APOLLO_KEY}
       client:
         service:garbanzo@current
overwrite: true
generates:
  ./src/graphql/generated/introspection-result.ts:
    plugins:
      - fragment-matcher
```

**Comment by mikefisher84** [comment]
Thanks Adra! I just copy and pasted what you wrote and now have a new error: 


```
 graphql-codegen --config codegen.yml
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./src/graphql/generated/introspection-result.ts
      ✖ Load GraphQL schemas
        → Failed to load schema
        Load GraphQL documents
        Generate


 Found 1 error

  ✖ ./src/graphql/generated/introspection-result.ts
    Failed to load schema from apollo-engine:

        Only absolute URLs are supported
        TypeError: Only absolute URLs are supported


        GraphQL Code Generator supports:
          - ES Modules and CommonJS exports (export as default or named export "schema")
          - Introspection JSON File
          - URL of GraphQL endpoint
          - Multiple files with type definitions (glob expression)
          - String in config file

        Try to use one of above options and run codegen again.
    Error: Failed to load schema
        at loadSchema (app/node_modules/@graphql-codegen/cli/bin.js:406:15)
    Error: Failed to load schema
        at loadSchema (app/node_modules/@graphql-codegen/cli/bin.js:406:15)
```

**Comment by ardatan** [comment]
Are you using the latest version of codegen?
@mikefisher84

**Comment by mikefisher84** [comment]
Ha nope I wasn't @ardatan I updated and am getting a new error

```
✖ ./src/graphql/generated/introspection-result.ts
    Failed to load schema from apollo-engine:

            Variable "$tag" of required type "String!" was not provided.
    Variable "$id" of required type "ID!" was not provided.
            Error: Variable "$tag" of required type "String!" was not provided.
    Variable "$id" of required type "ID!" was not provided.
        at ApolloEngineLoader.load (app/node_modules/@graphql-tools/apollo-engine-loader/index.cjs.js:41:19)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async loadFile (app/node_modules/@graphql-tools/load/index.cjs.js:48:24)
        at async app/node_modules/@graphql-tools/load/index.cjs.js:425:24
    
            GraphQL Code Generator supports:
              - ES Modules and CommonJS exports (export as default or named export "schema")
              - Introspection JSON File
              - URL of GraphQL endpoint
              - Multiple files with type definitions (glob expression)
              - String in config file
```

I just looked at the changelog for `v1.15` and noticed this section 
```
Introduce automatic JSON schema validation and auto complete for your codegen.yml. 
If you are using VSCode, make sure you have this extension installed: 
https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml
```

So I installed the yaml plugin in VS Code and I'm getting two yaml linting errors. 
# Property engine is not allowed
# Property client is not allowed
```
schema:
  - apollo-engine:
      engine: # Property engine is not allowed
        apiKey: ${APOLLO_KEY}
      client: service:garbanzo@current # Property client is not allowed
```

**Comment by dotansimha** [comment]
@mikefisher84 I'll fix that later, you can ignore that error for now, it's just a IDE validation.

**Comment by mikefisher84** [comment]
Thanks @dotansimha however it still seems to not generate the types with the config that @ardatan posted. 

```
 Variable "$tag" of required type "String!" was not provided.
    Variable "$id" of required type "ID!" was not provided.
            Error: Variable "$tag" of required type "String!" was not provided.
    Variable "$id" of required type "ID!" was not provided.
```

**Comment by ardatan** [comment]
```

**Comment by ardatan** [comment]
Could you try the following?
```
schema:
  - apollo-engine: 
      engine:
        apiKey: ${APOLLO_KEY}
      graph: service:garbanzo
      variant: current
```
