### ISSUE TITLE
Headers not sending correctly to Hasura Endpoint

### ISSUE THREAD

**Issue by seanaye** [dotansimha/graphql-code-generator#4223]
**Describe the bug**
I have followed the docs to setup sending the `x-hasura-admin-secret` header to my hasura endpoint. It can produce generated output for unauthenticated queries but not for ones that require authentication. It appears as if the header is not being set correctly

**To Reproduce**
1. 
```yml
schema:
  - "my_endpoint":
    headers: 
      x-hasura-admin-secret: "my_secret"
documents: "gql/**/*.graphql"
generates:
  src/types/apiTypes.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-vue-apollo"
    config:
      withCompositionFunctions: true
```
2. Make authenticated request to a hasura endpoint

These exact headers are set in a GraphQL playground which has no issues retrieving authenticated schema. I would create a sandbox but I don't want to expose my endpoint or admin secret.

Again just to reiterate, generation works fine for unauthenticated queries/mutations but authenticated ones fail with `GraphQLDocumentError: Cannot query field "insert_users" on type "mutation_root"` which is expected behaviour when Hasura receives an unauthenticated request. This means headers are not being set correctly since I have a running GraphQL playground with the same headers that make the same requests without problems

**Expected behavior**
Codegen should return and generate functions without error

**Environment:**

- OS: 
- `@graphql-codegen/`: ^1.15.3

**Comment by ardatan** [comment]
Indentation seems wrong in your configuration file `headers` should be under your endpoint url like below.
```yaml
schema:
  - "my_endpoint":
        headers: 
             x-hasura-admin-secret: "my_secret"
documents: "gql/**/*.graphql"
generates:
  src/types/apiTypes.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-vue-apollo"
    config:
      withCompositionFunctions: true
```
