### ISSUE TITLE
Near operation fails to import fragment query with `typescript-document-nodes` plugin

### ISSUE THREAD

**Issue by johnnyBira** [dotansimha/graphql-code-generator#4233]
**Describe the bug**
Near operation file fails to import fragment query.
I have a directory where I wish to store queries and fragment which I want to reuse in my near operation files.
Queries generated from fragments in this direcotry are not imported correctly by files generated from near operation files. The type is imported correctly from this correct directory, but the queries are not.

**To Reproduce**
As you can tell the type `AllUserFieldsFragment` is imported correctly but `AllUserFields` is not, and is high lighted as an error on line 14 in this generated file.
https://codesandbox.io/s/smoosh-haze-j5j28?file=/src/graphql/fragments.generated.ts:170-191
![image](https://user-images.githubusercontent.com/23634023/84604109-fc078c00-ae93-11ea-96a2-f80810503811.png)

-->

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```graphql
# common/reusable fragment locaed in src/graphql/fragments.graphql
fragment allUserFields on User {
    id
    username
    email
}

# query in near operation file located in src/components/Test
query GetUser {
    user(id: 1234) {
      ...allUserFields
    }
}

```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: schema.graphql
generates:
  ../www-common/fragmentTypes.json:
    plugins:
      - fragment-matcher
  src/@types/graphql.generated.ts:
    plugins:
      - "typescript"
  ./graphql.schema.json:
    plugins:
      - "introspection"
  ./:
    documents: "src/**/*.graphql"
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: src/@types/graphql.generated.ts
    plugins:
      - "typescript-document-nodes"
      - "typescript-operations"

```

**Expected behavior**
The graphql query should be imported in the same manner as the type.

**Environment:**

- OS: 
- `@graphql-codegen/...`: `1.15.2`
- NodeJS: `v10.20.1`

Thank you for a great product!
I really enjoy using GraphQL Code Generator and following it's development
