### ISSUE TITLE
Namespace import doesn't work with babel typescript

### ISSUE THREAD

**Issue by gaelollivier** [dotansimha/graphql-code-generator#4236]
Since [this change](https://github.com/dotansimha/graphql-code-generator/pull/3651) introduced in `v1.13.1`, enum imports use the `import = ` typescript syntax, which is not supported by `@babel/plugin-transform-typescript` (see caveat 3: https://babeljs.io/docs/en/next/babel-plugin-transform-typescript.html#caveats)

I use `@babel/plugin-transform-typescript` to run my typescript tests with Jest, so I'm stuck with `1.12.2` for now.

**To Reproduce**

1. My GraphQL schema:

```graphql
enum SomeEnum {
  ...
}
```

2. My `codegen.yml` config file:

```yml
generates:
  ./graphql-types.ts:
    plugins:
      - 'typescript'
config:
  enumValues:
    SomeEnum: './myFile#MyEnum'
```

**Output import statement**

```ts
import { MyEnum } from './myFile/MyEnum';
import SomeEnum = MyEnum;
```

**Expected import statement**
```ts
import { MyEnum as SomeEnum } from './myFile/MyEnum';
// or:
import { MyEnum } from './myFile/MyEnum';
type SomeEnum = MyEnum;
```
