### ISSUE TITLE
set typesPrefix and enumPrefix doesn't work with typescript-resolvers

### ISSUE THREAD

**Issue by Godsenal** [dotansimha/graphql-code-generator#4249]
**Describe the bug**
 
When enumPrefix is set to `false` typescript-resolver doesn't use prefixed type name  even if typesPrefix is set to `T`.

**To Reproduce**

1. set enumPrefix to `false`
2. set typesPrefix to `T`
3. graphql-codegen

Here is codesandbox.

https://codesandbox.io/s/quirky-proskuriakova-yyexo?file=/types.ts

<!--
#############
#############
PLEASE READ THE FOLLOWING:
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
# Put your schema here
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations: (**Not related to this issue**)

```graphql
query user {
    user(id: 1) {
        id
        username
        email
    }
}
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    config:
      typesPrefix: T
      enumPrefix: false
    plugins:
      - typescript
      - typescript-operations
      - typescript-resolvers

# Put your YML here
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

generated resolver type should use prefixed type.

**Environment:**

- OS: macOS 10.15.4 catalina
- "@graphql-codegen/cli": "^1.15.3",
- "@graphql-codegen/typescript": "^1.15.3",
- "@graphql-codegen/typescript-resolvers": "^1.15.3"
- NodeJS: v10.20.1

**Additional context**
<!-- Add any other context about the problem here. -->
