### ISSUE TITLE
c-sharp-operations is not producing response type classes

### ISSUE THREAD

**Issue by organic-scholar** [dotansimha/graphql-code-generator#4256]
**Describe the bug**
@graphql-codegen/c-sharp-operations is not producing response type classes

**Comment by cklam2** [comment]
These are generated by the "c-sharp" plugin so include that one in your yml config.

```
generates:
  src/main/c-sharp/my-org/my-app/Operations.cs:
    plugins:
      - c-sharp
      - c-sharp-operations
```

**Comment by organic-scholar** [comment]
`query CurrentUser {
    viewer {
        name
        email
    }
}`

For above query from https://api.github.com/graphql

it generates


`namespace GraphQLCodeGen {

    public class CurrentUserGql{

      public static GraphQLRequest getCurrentUserGql() {
        return new GraphQLRequest {
          Query = CurrentUserDocument,
          OperationName = "CurrentUser"
        };
      }
      
      public static string CurrentUserDocument = @"
    query CurrentUser {
  viewer {
    name
    email
  }
}
    ";
    }
    
}`

And a bunch of other types after I added c-sharp in plugins list.

**Comment by cklam2** [comment]
Yup, and [here](https://graphql-code-generator.com/docs/plugins/c-sharp-operations) you can see how to use it.

In your case should be something like
```
var response = await client.SendQueryAsync<Types.Query>(CurrentUserGql.getCurrentUserGql());
var name = response.Data.CurrentUser.viewer.name;
```

**Comment by cklam2** [comment]
If you think there is still an issue with this then please provide the following data:

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
# Put your YML here
```

4. Expected output / current output

Without this info it's hard to understand the problem.

**Comment by organic-scholar** [comment]
1. My GraphQL schema:

```graphql
https://api.github.com/grpahql
```

2. My GraphQL operations:

```graphql
query CurrentUser {
    viewer {
        name
        email
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
generates:
  ./Generated/GqlOperations.cs:
    plugins:
      - c-sharp
      - c-sharp-operations
config:
  querySuffix: Gql
  mutationSuffix: Gql
```

**Expected behavior**
The generated code contains too many extra types that are unused and it throwing errors during compile time. 
 GqlOperations.cs(1963, 18): [CS1585] Member modifier 'ref' must precede the member type and name.

Can code be trimmed down to types that are only used in operations? Also, I have no control over namespace of generated code i.e fixed to GraphQLCodeGen


**Environment:**

- OS: Mac OS Catalina
- `@graphql-codegen/...`: 1.15.3
- NodeJS: 

**Additional context**
