### ISSUE TITLE
Trailing underscore in fragment spread sub types

### ISSUE THREAD

**Issue by DanielHuisman** [dotansimha/graphql-code-generator#4263]
**Describe the bug**
The generated sub types for fragment spreads end with a trailing underscore, e.g. `MandateFragment_DigitalMandate_`. The expected behaviour is generating the name without the trailing underscore, e.g. `MandateFragment_DigitalMandate`.

**To Reproduce**

<!--
#############
#############
PLEASE READ THE FOLLOWING:
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

https://codesandbox.io/s/graphql-codegen-fragment-spread-bug-1yovy?file=/types.ts

1. My GraphQL schema:

```graphql
type Query {
    mandates: [Mandate!]!
}

interface Mandate {
    id: ID!
    reason: String!
}

type DigitalMandate implements Mandate {
    id: ID!
    reason: String!
    code: String!
}

type PaperMandate implements Mandate {
    id: ID!
    reason: String!
    file: String!
}
```

2. My GraphQL operations:

```graphql
fragment MandateFragment on Mandate {
    id
    reason

    ...DigitalMandateFragment
    ...PaperMandateFragment
}

fragment DigitalMandateFragment on DigitalMandate {
    code
}

fragment PaperMandateFragment on PaperMandate {
    file
}

query GetMandates {
    mandates {
        ...MandateFragment
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      dedupeOperationSuffix: true
      exportFragmentSpreadSubTypes: true
      namingConvention: keep
```

**Expected behavior**
The name should not end with a trailing underscore, so `MandateFragment_DigitalMandate` instead of `MandateFragment_DigitalMandate`.

**Environment:**

- OS: Ubuntu 18.04
- `@graphql-codegen/...`: 1.15.4
- NodeJS: 14.4.0 (or 10.20.1 in the CodeSandbox)

**Additional context**
-
