### ISSUE TITLE
`withRefetchFn` depends on ApolloReactHoc.withQuery which is not exported in Apollo 3

### ISSUE THREAD

**Issue by aldegoeij** [dotansimha/graphql-code-generator#4278]
**Describe the bug**
graphql-code-generator generates correct functions for use with refetchQueries, however when using it in a React Native app I get a `TypeError: ApolloReactHoc.withQuery is not a function` when on Apollo 3 (beta)

I did some digging and looks like apollo 3 deprecates `@apollo/react-hoc` functionality (which is a apollo 2 compatible lib)

Looking for help to figure out how to get this to work on apollo 3 if it is not `graphql-code-generator` related.

Stacktrace:

```javascript
TypeError: ApolloReactHoc.withQuery is not a function. (In 'ApolloReactHoc.withQuery(ListMyThingsDocument, _objectSpread({
      alias: 'listMyThings'
    }, operationOptions))', 'ApolloReactHoc.withQuery' is undefined)

withListMyThings
    components.tsx:538:11
self.getObservableFromLink.subscribe$argument_0.complete
    apollo-client.cjs.js:2496:75
notifySubscription
    Observable.js:145:15
onNotify
    Observable.js:179:20
complete
    Observable.js:245:14
forEach
    [native code]:0
iterateObserversSafely
    apollo-client.cjs.js:585:4
_this.handlers.complete
    apollo-client.cjs.js:2082:46
notifySubscription
    Observable.js:145:15
onNotify
    Observable.js:179:20
complete
    Observable.js:245:14
fetcher.then.then.then$argument_0
    apollo-client.cjs.js:1269:16
tryCallOne
    core.js:37:13
setImmediate$argument_0
    core.js:123:24
_callTimer
    JSTimers.js:135:14
_callImmediatesPass
    JSTimers.js:183:16
callImmediates
    JSTimers.js:446:30
callImmediates
    [native code]:0
__callImmediates
    MessageQueue.js:396:6
__guard$argument_0
    MessageQueue.js:144:6
__guard
    MessageQueue.js:373:10
flushedQueue
    MessageQueue.js:143:4
flushedQueue
    [native code]:0
invokeCallbackAndReturnFlushedQueue
    [native code]:0
```

**To Reproduce**

Using any generated tsx components file with plugin `typescript-react-apollo` and `withRefetchFn: true`

```javascript
// generated components.tsx
import gql from 'graphql-tag';
import * as React from 'react';
import * as ApolloReactCommon from '@apollo/client';
import * as ApolloReactComponents from '@apollo/client';
import * as ApolloReactHoc from '@apollo/client';
import * as ApolloReactHooks from '@apollo/client';

// ...

// Some mutation function
export function useCreateThingMutation(baseOptions?: ApolloReactHooks.MutationHookOptions<CreateThingMutation, CreateThingMutationVariables>) {
        return ApolloReactHooks.useMutation<CreateThingMutation, CreateThingMutationVariables>(CreateThingDocument, baseOptions);
      }

//...

// The refetch function
export function withListMyThings<TProps, TChildProps = {}, TDataName extends string = 'data'>(operationOptions?: ApolloReactHoc.OperationOption<
  TProps,
  ListMyThingsQuery,
  ListMyThingsQueryVariables,
  ListMyThingsProps<TChildProps, TDataName>>) {
    return ApolloReactHoc.withQuery<TProps, ListMyThingsQuery, ListMyThingsQueryVariables, ListMyThingsProps<TChildProps, TDataName>>(ListMyThingsDocument, {
      alias: 'listMyThings',
      ...operationOptions
    });
};
```

```javascript
// app.js
const [createThing, { loading, data, error }] = useCreateThingMutation({
  variables: { input: { title: "Thing 1" } },
  refetchQueries: withListMyThings,
});

// Some trigger, click, button, etc
createThing();
```

On triggering of `createThing()` the mutation completes succesfully, but the refetch throws above error.

1. My GraphQL schema:

2. My GraphQL operations:

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: ./src/graphql/**/*.schema.graphql
generates:
  ./src/graphql/types/resolvers.ts:
    documents: null
    plugins:
      - typescript
      - typescript-resolvers
    config:
      defaultMapper: Partial<{T}>
      useIndexSignature: true
  ./src/graphql/client/types.ts:
    documents: ./src/graphql/**/*.operation.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-document-nodes
    config:
      nameSuffix: "Document"
  ./src/graphql/client/components.tsx:
    documents: ./src/graphql/**/*.operation.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      reactApolloVersion: 3
      withHooks: true
      withRefetchFn: true
```

**Expected behavior**
Expect refetch function to work as the query itself (in non-refetch fashion) works like a charm. The generated file is clearly referencing a function that is no longer exposed in Apollo 3 (or included.

**Environment:**

- OS: macOS
- `@apollo/client`: 
- NodeJS: 14
