### ISSUE TITLE
TypeScript Generated Definition Contains More Than Just What Queried

### ISSUE THREAD

**Issue by MrDesjardins** [dotansimha/graphql-code-generator#4373]
**Describe the bug**
When performing a generation of TypeScript from a schema that is a file to a document that contain only a subset of all the type in the schema, the generated TypeScript contains all the type of the schema instead of only the subset used in the document.

**To Reproduce**
Configuration of codegen.yml
```
schema: "./allSchema.graphql"
documents: "./oneFieldQuery.graphql"
overwrite: true
generates:
    ./generated/mytype.ts:
        config:
            maybeValue: T | undefined
            preResolveTypes: true
            avoidOptionals: true
        plugins:
            - typescript
            - typescript-operations
            - add:
                  content:
                      - "/* tslint:disable */"
require: ["ts-node/register"]
```

**Environment:**

- OS: MacOS
- `@graphql-codegen/...`: Tried with 1.15 and 1.17
- NodeJS: v14.4.0
