### ISSUE TITLE
[near-operation-file] Continually generates new files instead of overwriting the existing file

### ISSUE THREAD

**Issue by aniravi24** [dotansimha/graphql-code-generator#4387]
**Describe the bug**
 
The near-operation-file preset generates files correctly the first time. However, every time after that, an extra extension is appended onto the filename. For example, if you have a file called mutation.generated.tsx, the next run will create a file called mutation.generated.generated.tsx, then mutation.generated.generated.generated.tsx, and so on and so forth.

**To Reproduce**
1. Use the codegen.yml listed below and try to run `graphgl-codegen --config codegen.yml` more than once.
<!--
#############
#############
PLEASE READ THE FOLLOWING:
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: schema.graphql
documents: 'src/**/*.{ts,tsx}'
generates:
  src/types.ts:
    plugins:
      - typescript
    config:
      avoidOptionals: true
  src/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.tsx
      baseTypesPath: types.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
    config:
      withHOC: false
      withHooks: true
      withComponent: false
      reactApolloVersion: 3
      avoidOptionals: true
      exportFragmentSpreadSubTypes: true
      preResolveTypes: true
config:
  scalars:
    DateTime: 'string'
    JSON: '{ [key: string]: any }'
    BigInt: 'string'
    Cursor: 'string'
    JwtToken: 'string'
    UUID: 'string'
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
The types.ts file it generates will be correct. That gets overwritten each time correctly. Any files that end with .generated.tsx will keep duplicating .generated as a prefix. Run the command once, you might get a file like `mutations.generated.tsx`. Run it again, and you'll get another file like `mutations.generated.generated.tsx`. It keeps adding that prefix each run.
**Environment:**

- OS: ArchLinux
- `@graphql-codegen/...`: 1.17.0
- NodeJS: 12.16

**Additional context**
<!-- Add any other context about the problem here. -->
Here's what my file tree looks like after a few runs.
![image](https://user-images.githubusercontent.com/5902976/87849123-e9211680-c89a-11ea-8c19-96c84bb4698d.png)
