### ISSUE TITLE
schema-ast produces empty GraphQL docblock comments

### ISSUE THREAD

**Issue by toverux** [dotansimha/graphql-code-generator#4393]
**Describe the bug**

For some of my types, the ast-schema plugin generates docblocks comments that are empty: 
![image](https://user-images.githubusercontent.com/1343250/87874971-4d90c280-c9ce-11ea-9ec4-30ca55aec4e2.png)

Some types that do not have a description do not have those empty comments.

That wouldn't be much annoying if they didn't make the parser of the JS GraphQL WebStorm plugin fail the parsing (to workaround, I am now using `commentDescriptions: true` and everything is fine).

3. My `codegen.yml` config file:

```yml
schema: "http://localhost:3001/graphql"

generates:
  schema.graphql:
    plugins:
      - schema-ast
```

**Expected behavior**

I guess the generator does not put a comment block if it receives null for the comment from the introspection query.
It should also do the same for empty strings.

**Environment:**

- `@graphql-codegen/...`: everything in version `1.17.0`
