### ISSUE TITLE
Better error logging - unhelpful error messages

### ISSUE THREAD

**Issue by trompx** [dotansimha/graphql-code-generator#4399]
**Is your feature request related to a problem? Please describe.**
I just inherited a codebase and running graphql-codegen, I get unclear messages that don't help me to diagnose where the error come from.

``` ts
 graphql-codegen
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/generated/graphql.ts
      ✔ Load GraphQL schemas
      ✖ Load GraphQL documents
        → Unexpected token (24:39)
        Generate

 Found 1 error

  ✖ src/generated/graphql.ts
    SyntaxError: Unexpected token (24:39)
    at Object._raise (/project1/node_modules/@babel/parser/lib/index.js:746:17)
    at Object.raiseWithData (/project1/node_modules/@babel/parser/lib/index.js:739:17)
    at Object.raise (/project1/node_modules/@babel/parser/lib/index.js:733:17)
    at Object.unexpected (/project1/node_modules/@babel/parser/lib/index.js:8807:16)
    at Object.parseIdentifierName (/project1/node_modules/@babel/parser/lib/index.js:10823:18)
    at Object._raise (/project1/node_modules/@babel/parser/lib/index.js:746:17)
    at Object.raiseWithData (/project1/node_modules/@babel/parser/lib/index.js:7
    at Object.parseIdentifier (/project1/node_modules/@babel/parser/lib/index.js:10800:23)
    ... (bunch of other unhelpful lines from node_modules/babe/parser)
```

**Describe the solution you'd like**
It would be great if the file + line of the code provoking the error could be logged.

**Additional context**
graphql-code-generator : 1.17.0
graphql : 15.3.0

codegen.yml:
  ```
schema: http://localhost:3000/api/graphql
documents:
  - ./src/**/*.tsx
  - ./src/**/*.ts
overwrite: true

generates:
  src/generated/graphql.ts:
    config:
      withHooks: true
      withComponent: false
      withHOC: false
      withMutationFn: false
      gqlImport: "@apollo/client#gql"
      reactApolloVersion: 3
      apolloReactCommonImportFrom: "@apollo/client"
      apolloReactHooksImportFrom: "@apollo/client"
    plugins:
      - add: /* eslint-disable */
      - typescript
      - typescript-operations
      - typescript-react-apollo
```
