### ISSUE TITLE
"Schema must contain uniquely named types but contains multiple types named" Error

### ISSUE THREAD

**Issue by tonypee** [dotansimha/graphql-code-generator#4411]
Im getting the error: "Schema must contain uniquely named types but contains multiple types named "Transform"."
When as far as i can tell there is only a single interface called 'Transform' 

I get this when loading it from the remote server, or when parsing local schema

Schema: https://gist.github.com/tonypee/836877757dbbe9d519b796815c98f376

SDL: https://gist.github.com/tonypee/24fa9a5b2eef5ceeb4098f953ae16be0

```
overwrite: true
schema: "schema.json"
documents: "src/**/*.graphql"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
  ./graphql.schema.json:
    plugins:
      - "introspection"

```

Hopefully im just doing something silly
