### ISSUE TITLE
[typescript-vue-apollo] has no exported member `UseMutationOptionsWithVariables`

### ISSUE THREAD

**Issue by liaoliaojun** [dotansimha/graphql-code-generator#4444]
**Describe the bug**
 
 Error：has no exported member `VueApolloComposable.UseMutationOptionsWithVariables`
![image](https://user-images.githubusercontent.com/22748955/88632917-df8f7e00-d0e6-11ea-9c51-e12d1555cc1e.png)

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
 https://github.com/dotansimha/graphql-code-generator/blob/master/dev-test/githunt/schema.json
```

2. My GraphQL operations:

```graphql
  typescript-vue-apollo
```

3. My `codegen.yml` config file:

```yml
  ./dev-test/githunt/types.vueApollo.ts:
    schema: ./dev-test/githunt/schema.json
    documents: ./dev-test/githunt/**/*.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-vue-apollo
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS:  Win10
- `@graphql-codegen/...`: 1.17.4
- NodeJS:  v12.18.1

**Additional context**
<!-- Add any other context about the problem here. -->
