### ISSUE TITLE
unused base types from operations.ts file in generated hooks

### ISSUE THREAD

**Issue by pramodsvidyarthi** [dotansimha/graphql-code-generator#4486]
**Describe the bug**
when using typescript-urql plugin along with import-types preset the generated hooks are not using the base types from the generated operations.ts file

1. My GraphQL schema:

```graphql
type Mutation {
  createUser(email: String!, name: String!): User!
}

type Post {
  author: User
  authorId: Int!
  content: String
  id: Int!
  published: Boolean!
  title: String!
}

type Query {
  getAllPosts: [Post!]!
  getAllUsers: [User!]!
  getUserByEmail(email: String): User!
}

type User {
  email: String!
  id: Int!
  name: String!
  posts: [Post!]
}

```

2. My GraphQL operations:

```graphql
query getAllUsers {
  getAllUsers {
    id
    name
    email
    posts {
      title
      content
      author {
        name
      }
    }
  }
}

```

3. My `codegen.yml` config file:

```yml
# inspired from https://github.com/danilowoz/ts-gql-jsx/blob/master/codegen.yml
overwrite: true
schema: 'http://localhost:3000/api'

hooks:
  afterAllFileWrite:
    - eslint --fix

generates:
  generated/schemas.ts:
    documents: 'graphql/**/*.graphql'
    plugins:
      - typescript

  generated/operations.ts:
    documents: 'graphql/**/*.graphql'
    preset: import-types
    presetConfig:
      typesPath: ./schemas
      importTypesNamespace: SchemaTypes
    plugins:
      - typescript-operations

  generated/hooks.ts:
    documents: 'graphql/**/*.graphql'
    preset: import-types
    presetConfig:
      typesPath: ./operations
      importTypesNamespace: OperationTypes
    plugins:
      - typescript-urql
    config:
      withHOC: false
      withComponent: false
      withHooks: true

```

**Expected behavior**
the generated hooks.ts file must use the imported base types from the operations.ts file

**Environment:**

- OS: 
- `@graphql-codegen/cli: 1.17.6`  
- `@graphql-codegen/typescript-urql: 1.17.6`

**Additional context**
![image](https://user-images.githubusercontent.com/8534915/89193628-e1b07b80-d5c3-11ea-8f96-0dbdd4bac428.png)

**Comment by chanlito** [comment]
@dotansimha  I think I'm facing a similar issue, but I'm trying with TypedDocumentNode.

Below is my cofig.

```yaml
schema:
  - http://localhost:4000/graphql
  - ./src/graphql/schema.graphql
documents:
  - ./src/graphql/fragments.ts
  - ./src/graphql/mutations.ts
  - ./src/graphql/queries.ts
  - ./src/graphql/subscriptions.ts
generates:
  ./src/generated/schema.ts:
    plugins:
      - typescript
    config:
      enumsAsTypes: true
  ./src/generated/operations.ts:
    presetConfig:
      typesPath: ./schema
      importTypesNamespace: SchemaTypes
    plugins:
      - typescript-operations
  ./src/generated/typed-documents.ts:
    preset: import-types
    presetConfig:
      typesPath: ./operations
      importTypesNamespace: OperationTypes
    plugins:
      - typed-document-node
  ./src/generated/fragments.ts:
    plugins:
      - fragment-matcher
```
