### ISSUE TITLE
TypeScript Resolvers - Apollo Federation Broken

### ISSUE THREAD

**Issue by rherber** [dotansimha/graphql-code-generator#4493]
**Describe the bug**
Upgraded from 1.16.3 to 1.17.7 and all resolvers resolving a federated type broke.

**To Reproduce**
Attempt to compile TypeScript files using generated types and resolvers.

1. My GraphQL schema:

Schema from service 1
```graphql
 extend type Query {
    getRoomType(id: String!): RoomType
    getRoomTypes(destination: String!): [RoomType]
  }

  type RoomType @key(fields: "id") @key(fields: "operaCode operaPropertyCode") {
    propertyId: String!
    operaCode: String!
    property: Property!
    id: String!
    name: String!
    active: Boolean
    operaPropertyCode: String @deprecated(reason: "Not intended for client use.")
  }

  extend type Property @key(fields: "id") {
    id: String! @external
    roomTypes: [RoomType!]
  }
```

Schema from service 2
```graphql
 extend type Query {
    getProperty(id: String!): Property
    getProperties(destination: String = "all"): [Property!]!
  }

  type Property @key(fields: "id") @key(fields: "operaPropertyCode operaRoomTypeCode") {
    id: String!
    propertyId: String!
    path: String!
    detailPageBrandURL: String
    detailPageCorpURL: String
    operaPropertyCode: String
    name: String!
    images: Images
    shortName: String
    region: String!
    regionName: String
    timezone: String
    websiteUrl: String
    emailAddress: String
    phoneNumber: PropertyPhoneNumber!
    propertyAddress: PropertyAddress!
    digitalKeyVendor: String @deprecated(reason: "digitalKeyVendor is now at the room level instead of property.")
    operaRoomTypeCode: String @deprecated(reason: "Not intended for client use.")
  }

  type PropertyPhoneNumber {
    generalLabel: String
    generalNumber: String
    reservationsLabel: String
    reservationsNumber: String
    additionalPhone1Label: String
    additionalPhone1Number: String
    cabanasNumber: String
  }

  type PropertyAddress {
    streetAddress: String
    addressLocality: String
    addressRegion: String
    postalCode: String
    addressCountry: String
  }
```

2. My GraphQL operations:

N/A. Issue is on TypeScript compilation

3. My `codegen.yml` config file:

```yml
generates:
  # Property Service
  packages/gql-types/src/schema/property/schemaTypes.generated.ts:
    schema:
      - ./services/property/src/schema.ts
    config:
      federation: true
      typesPrefix: PropertySchema
      useIndexSignature: true
      noSchemaStitching: true
      defaultMapper: Partial<{T}>
      mappers:
        Property: ../../content/index#PropertyWithRoomTypeKey
    plugins:
      - typescript
      - typescript-resolvers

  # Room type services
  packages/gql-types/src/schema/room-type/schemaTypes.generated.ts:
    schema:
      - ./services/room-type/src/schema.ts
    config:
      federation: true
      typesPrefix: RoomTypeSchema
      useIndexSignature: true
      noSchemaStitching: true
      defaultMapper: Partial<{T}>
      mappers:
        Property: ../stubs#PropertyStub
    plugins:
      - typescript
      - typescript-resolvers

hooks:
  afterAllFileWrite:
    - prettier --write

```

**Expected behavior**
TypeScript files should compile as they did with version 1.16.3

**Environment:**

- OS: Windows 10
- `@graphql-codegen/...`: 1.17.7
- NodeJS: 12.16.3
- TypeScript 3.9.6
- Apollo gateway/federation: 0.19.0
- graphql: 15.3.0

**Additional context**
Example resolver causing problems for service with schema 1:
```typescript
import { RoomTypeSchemaResolvers } from ''; //generated types file

export const resolvers: RoomTypeSchemaResolvers<any> = {
  Query: {
  RoomType: {
    property(roomType) {
      return { __typename: 'Property', id: roomType.propertyId };
    }
  }
};
```

Error:
```
Property 'propertyId' does not exist on type '({ __typename: "RoomType"; } & GraphQLRecursivePick<Partial<Pick<RoomTypeSchemaRoomType, "__typename" | "propertyId" | "operaCode" | "id" | "name" | "images" | "active" | "attributes" | "operaPropertyCode"> & { ...; }>, { ...; }>) | ({ ...; } & GraphQLRecursivePick<...>)'.
  Property 'propertyId' does not exist on type '{ __typename: "RoomType"; } & GraphQLRecursivePick<Partial<Pick<RoomTypeSchemaRoomType, "__typename" | "propertyId" | "operaCode" | "id" | "name" | "images" | "active" | "attributes" | "operaPropertyCode"> & { ...; }>, { ...; }>'.
```

interfaces for mappers:
```typescript
export type PropertyWithRoomTypeKey = Property & {
  operaRoomTypeCode?: string;
};

export interface Property {
  path: string;
  detailPageCorpURL: string;
  detailPageBrandURL: string;
  propertyId: string;
  id: string;
  name: string;
  location: Location;
  shortName: string;
  region: string;
  regionName: string;
  propertyAddress: PropertyAddress;
  timezone: string;
  websiteUrl: string;
  emailAddress: string;
  emailContactInfo: string;
  phoneNumber: PropertyPhoneNumber;
  corporateSortOrder: string;
  termsAndConditions: string;
  checkinTime: string;
  checkoutTime: string;
  petsAllowed: boolean;
  smokingAllowed: boolean;
  operaPropertyCode: string;
  reopenDate: string;
  digitalKeyVendor: string;
  contentType: string;
}

export interface PropertyAddress {
  streetAddress: string;
  addressLocality: string;
  addressRegion: string;
  postalCode: string;
  addressCountry: string;
}

export interface PropertyPhoneNumber {
  generalLabel: string;
  generalNumber: string;
  reservationsLabel: string;
  reservationsNumber: string;
  additionalPhone1Label: string;
  additionalPhone1Number: string;
  additionalPhone2Label: string;
  additionalPhone2Number: string;
  cabanasNumber: string;
}
```

```typescript
export interface PropertyStub {
  __typename: string;
  id?: string;
  operaPropertyCode?: string;
  operaRoomTypeCode?: string;
}
```
