### ISSUE TITLE
v2 apollo-react plugin enforces tsx by default

### ISSUE THREAD

**Issue by SimenB** [dotansimha/graphql-code-generator#4499]
**Describe the bug**

https://github.com/dotansimha/graphql-code-generator/releases/tag/%40graphql-codegen%2Ftypescript-react-apollo%402.0.0 says `withComponent: false` is the default behavior, but that forces the generated file to be `tsx` instead of `ts`.

https://github.com/dotansimha/graphql-code-generator/blob/8f31a9a9d74f556975e5bdb3c92dc8da8a578be6/packages/plugins/typescript/react-apollo/src/index.ts#L36-L51

Adding an explicit `withComponent: false` fixes the issue

**To Reproduce**

1. My GraphQL schema:

N/A

2. My GraphQL operations:

N/A

3. My `codegen.yml` config file:

```yml
config:
  reactApolloVersion: 2
generates:
  src/:
    schema:
      - schema.graphql
    documents: src/**/*.graphql
    preset: near-operation-file
    presetConfig:
      baseTypesPath: gqltypes.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
```

**Expected behavior**

**Environment:**

- OS: macOS
- `@graphql-codegen/...`: 1.17.7 plus v2 of react apollo 
- NodeJS: 12.18.1

**Additional context**
