### ISSUE TITLE
Unused gql import on typescript-react-apollo@2.0.4 with external documents

### ISSUE THREAD

**Issue by YvanGuidoin** [dotansimha/graphql-code-generator#4515]
**Describe the bug**
The update on gql import from @apollo/client package generates `const gql = Apollo.gql` unused on every file, as we import graphql files through webpack.

**To Reproduce**

https://codesandbox.io/s/graphql-codegen-bug-reproduce-kpbp6?file=/src/document.generated.tsx

1. My GraphQL schema:

Irrelevant

2. My GraphQL operations:

Irrelevant

3. My `codegen.yml` config file:

```yml
generates:
  src/graphql_definitions.ts:
    plugins:
      - "typescript"
  src/graphqldeclarations.d.ts:
    plugins:
      - "typescript-graphql-files-modules"
  src/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.tsx
      baseTypesPath: graphql_definitions.ts
    plugins:
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withMutationFn: true
      withRefetchFn: true
      documentMode: external
      importDocumentNodeExternallyFrom: near-operation-file
config:
  avoidOptionals: false
  immutableTypes: false
  # useTypeImports: true
  pureMagicComment: true
```

**Expected behavior**
If documentNode is external, the import of gql should be ignored I guess?

**Environment:**

- OS: Ubuntu 20.04
- `@graphql-codegen/typescript-react-apollo`: 2.0.4 
- NodeJS: 14
