### ISSUE TITLE
'Add' plugin adds an empty line

### ISSUE THREAD

**Issue by borekb** [dotansimha/graphql-code-generator#4528]
I'm constructing a `schema.graphql` file with the AST plugin and also want to add a comment to the top. This is from my `codegen.yml`:

```yaml
generates:
  schema.graphql:
    schema:
      - schema-source.ts
    plugins:
      - schema-ast
      - add:
          content: '# Generated - DO NOT EDIT'
```

Besides prepending the content, it also appends an empty line which feels like a bug to me:

![Screenshot 2020-08-06 at 10 17 13](https://user-images.githubusercontent.com/101152/89508485-463f2680-d7ce-11ea-9968-a4c29249b13b.png)
