### ISSUE TITLE
gql import

### ISSUE THREAD

**Issue by elge70** [dotansimha/graphql-code-generator#4530]
When typescript code is generated, there is a duplicate defn of gql which is giving me compilation error

My config file is attached.

```ts
import { GraphQLResolveInfo } from 'graphql';
import * as Apollo from '@apollo/client';
**import gql from 'graphql-tag';**
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type RequireFields<T, K extends keyof T> = { [X in Exclude<keyof T, K>]?: T[X] } &
    { [P in K]-?: NonNullable<T[P]> };
**const gql = Apollo.gql;**
/** All built-in and custom scalars, mapped to their actual values */
```

`codegen.yml`
```yml
overwrite: true
schema: 'src/Views/Schema/*.graphql'
documents: 'src/**/*.gql'
generates:
    src/Views/Gql/graphql.ts:
        plugins:
            - 'typescript'
            - 'typescript-operations'
            - 'typescript-react-apollo'
            - 'typescript-resolvers'
            - 'typescript-document-nodes'

config:
    namePrefix: 'gql'
    typesPrefix: I
    withMutation: true
    withHOC: false
    withHooks: true
    withRefetchFn: true
    withComponent: false
    reactApolloVersion: 3
    withResultType: true
    withMutationOptionsType: true
    useIndexSignature: true
    namingConvention:
        typeNames: pascal-case#pascalCase
        enumValues: upper-case#upperCase

hooks:
    afterOneFileWrite:
        - prettier --write
```
