### ISSUE TITLE
Composition function options type for mutation generated by typescript-vue-apollo is not correct

### ISSUE THREAD

**Issue by mlesin** [dotansimha/graphql-code-generator#4540]
**Describe the bug**
Generated composition function for useMutation options type should be `UseMutationOptions<..> | ReactiveFunction<UseMutationOptions<...>>` instead of `UseMutationOptions<..>`

**To Reproduce**
Just generate a mutation function with parameters:
https://codesandbox.io/s/youthful-cerf-ebfbk

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type Mutation {
    adduser(username: String!, email: String!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}

schema {
  query: Query
  mutation: Mutation
}
```

2. My GraphQL operations:

```graphql
mutation adduser ($username: String!, $email: String!) {
  adduser(username: $username, email: $email) {
    id
    username
    email
  }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-vue-apollo
    config:
      withCompositionFunctions: true
```

**Expected behavior**
options type of generated function should contain type variant with `ReactiveFunction<...>`
```ts
export function useAdduserMutation(options: 
    | VueApolloComposable.UseMutationOptions<AdduserMutation, AdduserMutationVariables>
    | ReactiveFunction<VueApolloComposable.UseMutationOptions<AdduserMutation, AdduserMutationVariables>>) {
        return VueApolloComposable.useMutation<AdduserMutation, AdduserMutationVariables>(AdduserDocument, options);
}
```
for now, it generates the following:
```ts
export function useAdduserMutation(options: VueApolloComposable.UseMutationOptions<AdduserMutation, AdduserMutationVariables>) {
    return VueApolloComposable.useMutation<AdduserMutation, AdduserMutationVariables>(AdduserDocument, options);
}
```

**Environment:**

- OS: any
- `@graphql-codegen/typescript-vue-apollo`: 1.17.7
- NodeJS: 14.7.0
