### ISSUE TITLE
Wrong enum types when working with number strings or number 0

### ISSUE THREAD

**Issue by KillerCodeMonkey** [dotansimha/graphql-code-generator#4564]
**Describe the bug**

1. when creating an enum value with number value `0` it is handle as null or not set and will result in the value-key
2. when working with number strings they are parsed as ints, which leads to wrong results

**To Reproduce**

1. Number 0 or String-Number  0 is not handled correctly

```TS
new GraphQLEnumType({
  name: 'MyEnum',
  values: {
    'missing': {
      value: 0
    }
})
```

will result in

```TS
export enum MyEnum {
  Missing = 'missing'
}
```

correct is

```TS
export enum MyEnum {
  Missing = 0
}
```

2. when working with number strings

```TS
new GraphQLEnumType({
  name: 'MyEnum',
  values: {
    'available': {
      value: '01'
    },
    'somethingElse': {
      value: '99'
    }
})
```

results in enum with mixed types (strings and numbers)

```TS
export enum MyEnum {
  Available = '01',
  SomethingElse = 99
}
```

should be

```TS
export enum MyEnum {
  Available = '01',
  SomethingElse = '99'
}
```

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

not necessary for it

2. My GraphQL operations:

not necessary

3. My `codegen.yml` config file:

```yml
# Put your YML here
overwrite: true
schema: 'src/server/graphql/schema.ts'
documents: 'src/app/**/*.{ts,tsx}'
generates:
  src/app/graphql/generated/graphql.tsx:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withHooks: true
      scalars:
        Date: string
        DateTime: string
require:
  - ts-node/register

```

**Expected behavior**
1. `0 ` is handles as `0` and not as not set.
2. Strings are strings and should not be touched (at least per default)

**Environment:**

- OS: MacOS 10.15.5
- @graphql-codegen/cli: 1.17.7
- @graphql-codegen/typescript: 1.17.7
- @graphql-codegen/typescript-operations: 1.17.7
- @graphql-codegen/typescript-react-apollo: 2.0.4
- NodeJS: 12.13.0

**Additional context**
<!-- Add any other context about the problem here. -->
