### ISSUE TITLE
pluckConfig not ignoring other query tags

### ISSUE THREAD

**Issue by carstenblt** [dotansimha/graphql-code-generator#4586]
I tried all different combinations of `pluckConfig` with `module` and `globalIdentifier`, at the root of my `codegen.yml` and under `generates` but it always still parses my gatsby `graphql` tags as well and fails.

My `codegen.yml` config file:

```yml
schema:
  - https://backend

generates:
  src/__generated__/apollo-types.tsx:
    pluckConfig:
      modules:
        - name: apollo-boost
          identifier: gql
    documents:
      - src/components/**/*.{ts,tsx}
    plugins:
      - typescript
      - typescript-resolvers
      - typescript-operations
      - typescript-react-apollo
```

My Typescript:

```
import { graphql } from "gatsby";
import { gql } from "apollo-boost";

const query = graphql`
  query {
    backend {
      someQuery
  }
  `
const otherQuery = await AClient.query({
      query: gql`{
          someOtherQuery
      }
      `
    });
```

**Expected behavior**
Ignoring all other graphql tags, except `gql` imported from `apollo-boost`

**Environment:**

- OS: macOS
- `@graphql-codegen/cli`: 1.17.8
- NodeJS: v13.13.0

**Comment by dotansimha** [comment]
I think this one is more relevant for `@graphql-tools`. @ardatan ?

**Comment by carstenblt** [comment]
@ardatan https://codesandbox.io/s/exciting-thunder-gcf0l

example.js contains two queries, one with gatsby's `graphql` tag, one with Apollo's `gql` tag. pluckConfig should work so only the `gql` query is checked. However the invalid query I wrote with `graphql` throws an error.

**Comment by sarink** [comment]
If you try to use any of the built-in identifiers, they will conflict with one another, because many tools are hardcoded to look for `gql`, `graphql`, and `/* GraphQL */`, so you first need to disable all of these possibilities, and then come up with your own. This is also why you must disable the magic comment.
```
  pluckConfig:
    modules:
      - name: src/gql-tag  # name of your import, eg mine is `import { apfmgql } from 'src/gql-tag'`
        identifier: apfmgql
    gqlMagicComment: __never__
```
```
import gql-tag from 'graphql-tag';

export const apfmgql = gqltag;
```
Finally, later on, to get syntax highlighting in your IDE (vscode is again hardcoded to look for `gql`, `graphql`, and `/* GraphQL */`, you _will_ need the magic comment (but since you overrode codegen's, it won't try to parse it).
```
export const MY_QUERY = apfmgql/* GraphQL */`
  query SomeQuery {
    ...
  }
`;
```
