### ISSUE TITLE
[urql] gqlImport option doesn't work and docs have typo

### ISSUE THREAD

**Issue by earksiinni** [dotansimha/graphql-code-generator#4598]
**Describe the bug**
The `gqlImport` config option for the urql plugin doesn't seem to have any effect. I tried to change it but `gql` is still being imported from `graphql-tag` in my generated files.

Separately, there's a [typo in the docs](https://graphql-code-generator.com/docs/plugins/typescript-urql). It claims that the default value for `gqlImport` is `gql#graphql-tag`. However, the subsequent examples place the imported member after the hash, i.e. `graphql.macro#gql` and `gatsby#graphql`, which is inconsistent with the format used in the default value.

**To Reproduce**
Steps to reproduce the behavior: https://codesandbox.io/s/charming-wildflower-90hcg

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
        email
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-urql:
        gqlImport: 'my-import#gql'
```

**Expected behavior**

The generated `types.tsx` file should import `gql` from `my-import`, but instead it imports from the default `graphql-tag`.

Furthermore, the docs should have an explanation of what each side of the hash in the examples for `gqlImport` signifies and the examples given should be consistent.

**Environment:**

- OS: macOS 10.15.3
- `@graphql-codegen/...`:
```json
{
  "@graphql-codegen/add": "1.17.0",
  "@graphql-codegen/cli": "1.17.0",
  "@graphql-codegen/typescript": "1.17.0",
  "@graphql-codegen/typescript-operations": "1.17.0",
  "@graphql-codegen/typescript-urql": "2.0.1",
  "graphql": "15.3.0"
}
```
- NodeJS: 10.16.3

**Additional context**
N/A

**Comment by dotansimha** [comment]
@earksiinni can you please try to indent it correctly as yaml object?
```
schema: schema.graphql
documents: document.graphql
generates:
  types.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-urql:
          gqlImport: 'my-import#gql'
```

Or, move it higher?

```
schema: schema.graphql
documents: document.graphql
generates:
  types.tsx:
    config:
      gqlImport: 'my-import#gql'
    plugins:
      - typescript
      - typescript-operations
      - typescript-urql
```
