### ISSUE TITLE
Type suffix placed incorrectly in aguments type

### ISSUE THREAD

**Issue by petrzjunior** [dotansimha/graphql-code-generator#4687]
**Describe the bug**
This is excerpt from the generated TypeScript definition:
```typescript
export type UserQL = {
  __typename?: 'User';
  _id: Scalars['ID'];
};
export type QueryuserArgsQL = {
  _id: Scalars['ID'];
};
export type QueryResolversQL<ContextType = ExpressContext, ParentType extends ResolversParentTypesQL['Query'] = ResolversParentTypesQL['Query']> = {
  user?: Resolver<Maybe<ResolversTypesQL['User']>, ParentType, ContextType, RequireFields<QueryQLuserArgs, '_id'>>;
};
```
**To reproduce**
https://codesandbox.io/s/eloquent-sara-rt4wo?file=/types.ts

The config option `typesSuffix: QL` started placing suffix in the wrong place: `QueryQLuserArgs` vs. `QueryuserArgsQL`.  Sufficies in the rest of the file is fine.

1. My GraphQL schema:

```graphql
type User {
	_id: ID!
}
type Query {
	user(_id: ID!): User
}
```

3. My `codegen.yml` config file:

```yml
generates:
  src/schema/generated.ts:
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
    config:
      typesSuffix: QL
```

**Expected behavior**

**Environment:**

- NodeJS: 14
- `@graphql-codegen/cli@1.17.8`
- `@graphql-codegen/core@1.17.8`
- `@graphql-codegen/typescript@^1.17.8`
