### ISSUE TITLE
When federation is enabled for a type, its resolvers have a wrong ParentType

### ISSUE THREAD

**Issue by KoltesDigital** [dotansimha/graphql-code-generator#4722]
The goal of `__resolveReference` is to return a model object which is internal to the current service. Its return type is then the parent type of related resolver functions. However the current parent type for resolvers is an extract of the real parent type (via `GraphQLRecursivePick`). It shouldn't.

**To Reproduce**

See https://codesandbox.io/s/bitter-https-7yboj

1. My GraphQL schema:

```graphql
extend type User @key(fields: "id") {
    id: ID! @external
    fullName: String!
}
```

2. My GraphQL operations:

None

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: null
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      federation: true
      mappers:
        User: ./models#User
      mapperTypeSuffix: ParentType
      noSchemaStitching: true
      useTypeImports: true
```

**Expected behavior**

This file (`user-resolvers.ts`) should compile:

```ts
import { UserResolvers } from "./types";

export const __resolveReference: UserResolvers["__resolveReference"] = (
  externalUser
) => ({
  id: externalUser.id,
  firstName: "John",
  lastName: "Doe"
});

export const fullName: UserResolvers["fullName"] = (user) =>
  `${user.firstName} ${user.lastName}`;
```

But it does not. The cause is `UserResolvers` is:

```ts
export type UserResolvers<ContextType = any, ParentType extends ResolversParentTypes['User'] = ResolversParentTypes['User']> = {
  __resolveReference?: ReferenceResolver<Maybe<ResolversTypes['User']>, { __typename: 'User' } & GraphQLRecursivePick<ParentType, {"id":true}>, ContextType>;

  fullName?: Resolver<ResolversTypes['String'], { __typename: 'User' } & GraphQLRecursivePick<ParentType, {"id":true}>, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType>;
};
```

whereas it should be

```ts
export type UserResolvers<ContextType = any, ParentType extends ResolversParentTypes['User'] = ResolversParentTypes['User']> = {
  __resolveReference?: ReferenceResolver<Maybe<ParentType>, { __typename: 'User' } & GraphQLRecursivePick<ParentType, {"id":true}>, ContextType>;

  fullName?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType>;
};
```

**Environment:**

- OS: Win10 x64
- `@graphql-codegen/...`: latest as of writing
- NodeJS: v14.8.0
