### ISSUE TITLE
Multiple @key directives not supported when type is extended

### ISSUE THREAD

**Issue by Micahnator** [dotansimha/graphql-code-generator#4739]
**Describe the bug**
When a graphql type definition has multiple `@key` directives (as in for Apollo Federation) AND that same type is extended elsewhere in the same schema being parsed by by the code generator, only the last directive is included in the output. I'm seeing this in both the schema-ast and typescript-resolvers plugin outputs. 

**To Reproduce**
Steps to reproduce the behavior: Apply multiple `@key` directives to a type and elsewhere in the schema add fields to the type using the `extend` keyword. Use the schema-ast plugin to generate a parsed version of the schema and observe that only the last `@key` directive is in the output file. Make sure to configure both the 'federation' and 'includeDirectives' options configured to 'true'.

I've setup a codesandbox where this can be observed: https://codesandbox.io/s/zen-boyd-t8dls
Note: You can see all the directives successfully being included by commenting out the part of the schema that adds the 'phone' field to the User.

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User @key(fields: "id") @key(fields: "username") @key(fields: "email") {
    id: ID!
    username: String!
    email: String!
}

extend type User {
    phone: String!
}
```

2. My GraphQL operations:
N/A

3. My `codegen.yml` config file:

```yml
# From the codesandbox linked above
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      federation: true
  output.graphql:
    plugins:
      - schema-ast
    config:
      includeDirectives: true
      federation: true
```

**Expected behavior**
The output should support having more than one `key` directive even when the type is extended elsewhere

**Environment:**

- OS: Windows 10
- `@graphql-codegen/...`: 1.17.8
- NodeJS: 10.22.0

**Additional context**
<!-- Add any other context about the problem here. -->
