### ISSUE TITLE
[typescript-graphql-request ] importDocumentNodeExternallyFrom lost type prefix

### ISSUE THREAD

**Issue by qiwang97** [dotansimha/graphql-code-generator#4748]
i use this config
```yml
  src/services/generated/schema.ts:
    plugins:
      - typescript
    config:
      skipTypename: true
  src/services/generated/operations.ts:
    preset: import-types
    presetConfig:
      typesPath: ./schema
    plugins:
      - typescript-operations
    config:
      skipTypename: true
  src/services/generated/request.ts:
    plugins:
      - typescript-graphql-request
    config:
      documentMode: external
      importDocumentNodeExternallyFrom: ./operations
```
But importDocumentNodeExternallyFrom doesnot work. The Operations prefix is lost like this:
```ts
import { GraphQLClient } from 'graphql-request'
import { print } from 'graphql'
import * as Operations from './operations'

export type SdkFunctionWrapper = <T>(action: () => Promise<T>) => Promise<T>

const defaultWrapper: SdkFunctionWrapper = sdkFunction => sdkFunction()
export function getSdk(client: GraphQLClient, withWrapper: SdkFunctionWrapper = defaultWrapper) {
  return {
    Upload(variables: UploadMutationVariables): Promise<UploadMutation> {
      return withWrapper(() => client.request<UploadMutation>(print(UploadDocument), variables))
    },
  }
}
```
`UploadMutationVariables` should be `Operations.UploadMutationVariables`.

@dotansimha   Anything to do to solve it?

Here is the [reproduction demo](https://github.com/qiwang97/graphql-code-generator-issues-4748)
