### ISSUE TITLE
typescript-graphql-request -> rawRequest mode, missing "Header" import

### ISSUE THREAD

**Issue by kdong007** [dotansimha/graphql-code-generator#4793]
**Describe the bug**
Sandbox link: https://codesandbox.io/s/cocky-lumiere-2e9np?file=/package.json

for plugin `typescript-graphql-request` 
```typescript
import { Headers } from 'graphql-request/dist/types.dom';
```
 is needed in generated file when rawRequest: true

**To Reproduce**

just run codegen

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
scalar DateTime

type ServerStatus {
    time: DateTime!
    env: String!
    isDBConnected: Boolean!
}

type Query {
    serverStatus: ServerStatus!
}

```

2. My GraphQL operations:

```graphql
query getServerStatus {
    serverStatus {
        time
        isDBConnected
        env
    }
}

```

3. My `codegen.yml` config file:

```yml
# Put your YML here
overwrite: true
schema: "./schema.graphql"
documents: "./document.graphql"
generates:
  operations.generated.ts:
    config:
      rawRequest: true
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request

```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

```typescript
import { Headers } from 'graphql-request/dist/types.dom';
```
is needed in generated file when `rawRequest: true`


**Additional context**
<!-- Add any other context about the problem here. -->

@ardatan were you the one did this features? 
https://github.com/dotansimha/graphql-code-generator/blame/cc8a0a59a9fa824943c3ceaaa4c8483bfd108d06/packages/plugins/typescript/graphql-request/src/visitor.ts 
line 87
