### ISSUE TITLE
Unable to find typescript-named-operations-object

### ISSUE THREAD

**Issue by javiertury** [dotansimha/graphql-code-generator#4794]
**Describe the bug**

Codegen can't find the plugin "typescript-named-operations-object"

```
    Unable to find template plugin matching 'typescript-named-operations-object'
    Install one of the following packages:

    - @graphql-codegen/typescript-named-operations-object
    - @graphql-codegen/typescript-named-operations-object-template
    - @graphql-codegen/typescript-named-operations-object-plugin
    - graphql-codegen-typescript-named-operations-object
    - graphql-codegen-typescript-named-operations-object-template
    - graphql-codegen-typescript-named-operations-object-plugin
    - codegen-typescript-named-operations-object
    - codegen-typescript-named-operations-object-template
    - typescript-named-operations-object
    Error: Unable to find template plugin matching typescript-named-op
erations-object
        at getPluginByName (<project_path>/node_modules/@graphql-codegen/cli/bin.js:295:11)
    Error: Unable to find template plugin matching typescript-named-op
erations-object
        at getPluginByName (<project_path>/node_modules/@graphql-codegen/cli/bin.js:295:11)
```

**To Reproduce**

```bash
$ yarn add -D @graphql-codegen/named-operations-object
```

Run codegen with `typescript-named-operations-object` plugin

1. My GraphQL schema:

Any

2. My GraphQL operations:

Any

3. My `codegen.yml` config file:

Here I'm following the documentation. The recommended name for the plugin is `typescript-named-operations-object`

```yml
overwrite: true
schema: <schema>
documents: ./src/*.graphql
generates:
  src/queries.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-document-nodes"
      - "typescript-named-operations-object"
```

**Expected behavior**

I would expect codegen to run normally.

**Workaround**

Instead of following the documentation, if I replace `typescript-named-operations-object` with `named-operations-object` it just works.

```yml
overwrite: true
schema: <schema>
documents: ./src/*.graphql
generates:
  src/queries.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-document-nodes"
      - "named-operations-object"
```
