### ISSUE TITLE
Custom scalars inside a fragment are turned into `any` when `preResolveTypes: true`

### ISSUE THREAD

**Issue by CarlosGines** [dotansimha/graphql-code-generator#4861]
**Describe the bug**
Custom scalars inside a fragment are turned into `any` when `preResolveTypes: true`

**To Reproduce**
Check live: https://codesandbox.io/s/elegant-haibt-30ppy

1. My GraphQL schema:

```graphql
scalar Date

type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
    createdAt: Date!
}
```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        ...UserFragment
    }
}

fragment UserFragment on User {
    username
    email
    createdAt
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript:
          scalars:
            Date: string
      - typescript-operations:
          preResolveTypes: true
```

**Expected behavior**
`UserFragmentFragment['createdAt']` should be `Scalars['Date']`, but it is `any`

**Environment:**

- OS: macOS 10.15.6
- `@graphql-codegen/...`: 

      "@graphql-codegen/cli": "^1.17.10",
      "@graphql-codegen/typescript": "^1.17.10",
      "@graphql-codegen/typescript-operations": "^1.17.8",

- NodeJS: 12.16.1

**Comment by dotansimha** [comment]
@CarlosGines you are using the per-plugin configuration, so `scalars` config is only available for `typescript` plugin and not for the `typescript-operations`.

Please use:

```
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    config:
      scalars:
        Date: string
    plugins:
      - typescript
      - typescript-operations:
          preResolveTypes: true
```
