### ISSUE TITLE
Allow to specify an apollo-client in the typescript-react-apollo plugin

### ISSUE THREAD

**Issue by SamuelC54** [dotansimha/graphql-code-generator#4862]
**Is your feature request related to a problem? Please describe.**

I really like the generated hooks that typescript-react-apollo provide and it makes my code really more clean than before but I think it could be improved if it had a way to specify the ApolloClient in the option for the hooks generated.

What it look right now:
```
  import { useAnnotationsAddMutation } from 'ApiNumber3';

  const [annotationAdd, annotationAddResult] = useAnnotationsAddMutation({
    client: getApiNumber3Client(),
  });
```

**Describe the solution you'd like**

I wish that in the config you could specify the client that the hooks gonna use like this:
```
schema: http://localhost:3006/gql
documents: 'src/apiNumber3/**/*.gql'
generates:
  __generated/apiNumber3.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
   config:
     apolloClient: 'apiNumber3'
```
To make the client props optional instead of required for me
```
  import { useAnnotationsAddMutation } from 'ApiNumber3';

  const [annotationAdd, annotationAddResult] = useAnnotationsAddMutation();
```

**Additional context**

Because I have in my project multiple apollo API I cannot only use an ApolloProvider like this, I have to specify the client in the hooks props. 

```
ReactDOM.render(
  <ApolloProvider client={client}>
    <MyRootComponent />
  </ApolloProvider>,
  document.getElementById('root'),
);
```
_https://www.apollographql.com/docs/react/api/react/hooks/_
