### ISSUE TITLE
Angular >9 breaks codegen

### ISSUE THREAD

**Issue by oskarious** [dotansimha/graphql-code-generator#4865]
**Describe the bug**
 
We are in the process of upgrading our angular environment from 8 -> 10. For angular 8, we have been able to generate the services fine, but as soon as we upgraded to 9, we started running in to issues. What seem to be happening is that any and all .gql file, during the generation, wants to reference a completely unrelated fragment. 

The error is variations of this
`...graphql/admin/getCacheHealth.gql:8:5
        GraphQLDocumentError: Fragment "adminUserFields" cannot be spread here as objects of type "User" can never be of
 type "AdminUser".`
where `getCacheHealth.gql` looks like
```
query getCacheHealth {
  cacheHealth {
    ...cacheFields
  }
}
```

and cacheFields is defined in `fragmentCacheInfo.gql` as
```
fragment cacheFields on CacheInfo {
      stats {
      keys
      hits
      misses
      ksize
      vsize
    }
    keys
}
```
I looked through older issues, but could not find anything that concretely references what is happening to us.

**To Reproduce**
I'll try and get a repo with a reproduction, but as this is a live, prod project it could be challenging. 

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

My `codegen.yml` config file:

```yml
overwrite: true
schema: http://localhost:4000/graphql
documents: ./src/graphql/**/*.gql
generates:
  ./src/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-apollo-angular
      - fragment-matcher
    config:
      skipTypename: true
      namingConvention: change-case#pascalCase
      transformUndercase: true
  ./src/generated/introspection.json:
    plugins:
      - fragment-matcher
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
Codegen should generate angular services in angular 9 and up.

**Environment:**
- "graphql": "^14.4.2",
- "graphql-tag": "^2.10.0",
- "@graphql-codegen/cli": "^1.4.0",
- "@graphql-codegen/fragment-matcher": "^1.7.0",
- "@graphql-codegen/typescript": "^1.4.0",
- "@graphql-codegen/typescript-apollo-angular": "^1.4.0",
- "@graphql-codegen/typescript-operations": "^1.4.0",
- NodeJS: 12.18.4

**Additional context**
<!-- Add any other context about the problem here. -->
