### ISSUE TITLE
Sequential-dependent codegen breaks with output-file level documents

### ISSUE THREAD

**Issue by warent** [dotansimha/graphql-code-generator#4871]
**Describe the bug**
The following config works:

```
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
  resolvers.ts:
    documents: "./types.ts"
    plugins:
      - typescript
      - typescript-resolvers
```

The following config does not work:

```
schema: schema.graphql
generates:
  types.ts:
    documents: document.graphql
    plugins:
      - typescript
      - typescript-operations
  resolvers.ts:
    documents: "./types.ts"
    plugins:
      - typescript
      - typescript-resolvers
```

And produces this error:

```
Found 1 error

  ✖ resolvers.ts
    Error:
          Unable to find any GraphQL type definitions for the following pointers:

              - ./types.ts

        at prepareResult (/sandbox/node_modules/@graphql-tools/load/index.cjs.js:590:15)
        at loadTypedefs (/sandbox/node_modules/@graphql-tools/load/index.cjs.js:555:12)
    Error:
          Unable to find any GraphQL type definitions for the following pointers:

              - ./types.ts

        at prepareResult (/sandbox/node_modules/@graphql-tools/load/index.cjs.js:590:15)
        at loadTypedefs (/sandbox/node_modules/@graphql-tools/load/index.cjs.js:555:12)
```

Yet it works fine if you remove the resolvers.ts definition:

```
schema: schema.graphql
generates:
  types.ts:
    documents: document.graphql
    plugins:
      - typescript
      - typescript-operations
```

By moving `documents` to `types.ts`, the `resolvers.ts` definition suddenly thinks that `types.ts` is invalid, even though it is valid.

**To Reproduce**

https://codesandbox.io/s/delicate-butterfly-2f9wz?file=/codegen.yml

**Expected behavior**

Behavior should be identical for both configurations, i.e. it should generate the code normally.

**Comment by warent** [comment]
FYI in my local environment I can work around this by commenting out the "resolvers.ts" section to first generate the types.ts, and then generating the resolvers.ts after. For some reason this workaround doesn't work in the sandbox environment.

**Comment by dotansimha** [comment]
@warent can you please explain the motivation behind using `documents: "./types.ts"` ? This file will contain only TypeScript types for base types (`typescript` plugin) and typescript operations types (`typescript-operations` plugin, based on the `documents` section). 
Also, why do you need to load GrpahQL operations for your 2nd output file that creates resolvers signature? It seems like a misuse of codegen.

**Comment by warent** [comment]
The example I provided is not telling the full story. It looks more like this:

```
schema: schema.graphql
generates:
  types.ts:
    documents: document.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
  resolvers.ts:
    documents: "./types.ts"
    plugins:
      - typescript
      - typescript-resolvers
```

i.e. we're using `types.ts` for frontend code with typescript-react-apollo, and `resolvers.ts` for backend Node.js code.

Should we be doing something else?

**Comment by warent** [comment]
Also note we're using a third party library that utilizes the resolvers.ts file

**Comment by dotansimha** [comment]
Got it, so what's the reason for passing `document` for the 2nd output file?

```yaml
schema: schema.graphql
generates:
  types.ts:
    documents: document.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
  resolvers.ts:
    documents: "./types.ts"                                     ##   <<< this one doesnt make sense here
    plugins:
      - typescript
      - typescript-resolvers
```

I'm asking because both `typescript` and  `typescript-resolvers` doesn't have anything to do with `document`  - both types are dealing with schema types, and not your operations.

Your setup seems correct except for the line I specified (it can be removed). Putting the schema on the top level is great (so it will be available for both output files), and the `document` only for the one that generates operation types is also a good direction.
