### ISSUE TITLE
'Types' is declared but its value is never read

### ISSUE THREAD

**Issue by Fi1osof** [dotansimha/graphql-code-generator#4900]
**Describe the bug**
 

When generate separated files for fragments, added 
import * as Types from './types'; 
in any case, ever Types does not using.

Generated code:
```ts

# Never use cause fragment does not have Maybe<> fields
import * as Types from './types';

import { gql } from '@apollo/client';
export type TopicsConnectionTopicFragment = { __typename?: 'Resource', id: string, updatedAt: any, name: string, uri: string };

export const TopicsConnectionTopicFragmentDoc = gql`
    fragment topicsConnectionTopic on Resource {
  id
  updatedAt
  name
  uri
}
    `;
```

**To Reproduce**

```js
function createQueriesMap(filesMap: any) {
  let documentsString = ''
  for (const contents of filesMap.values()) {
    documentsString += contents + '\n'
  }

  const definitions = parse(documentsString).definitions

  const queriesAndFragments = definitions.filter(
    ({ kind }) =>
      kind === 'OperationDefinition' || kind === 'FragmentDefinition'
  ) as Array<ExecutableDefinitionNode>

  const queriesMap = new Map()
  queriesAndFragments.forEach((definition) => {
    if (definition.name && definition.loc) {
      const name = definition.name.value
      const oldText = queriesMap.get(name)
      if (!oldText) {
        queriesMap.set(
          name,
          documentsString.substring(definition.loc.start, definition.loc.end)
        )
      } else {
        const newText = documentsString.substring(
          definition.loc.start,
          definition.loc.end
        )
        if (
          oldText.replace(/\r/g, '').trim() !==
          newText.replace(/\r/g, '').trim()
        ) {
          throw new Error(`duplicate definitions ${name}`)
        }
      }
    }
  })
  return queriesMap
}
```

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
# Put your schema here
fragment topicsConnectionTopic on Resource {
  id
  updatedAt
  name
  uri
}
```


3. My `codegen conf` config file:

```js
const codegenConfig = {
  plugins: [
    {
      add: {
        content: prependText.join(''),
      },
    },
    'typescript-operations',
    'typescript-react-apollo',
  ],
  preset: 'near-operation-file',
  presetConfig: {
    extension: '.ts',
    baseTypesPath: './types.ts',
  },
  config: {
    withHOC: false,
    withHooks: true,
    withComponent: false,
    preResolveTypes: true,
    exportFragmentSpreadSubTypes: true,
  },
}
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by dotansimha** [comment]
I assume this is something to do with `isUsingTypes` method. PRs are welcome :D

**Comment by tim-field** [comment]
Hi just wondering if the bug label could be added to this?  I suspect this is preventing a fair few people from upgrading

**Comment by pleunv** [comment]
Just ran into this as well while trying to integrate this. Anyone happen to have found a workaround for this, by any chance? :)

**Comment by pleunv** [comment]
What I can observe so far:

When using the `near-operation-file` preset, the generator appears to ignore the custom scalars types defined in the schema file for all the fields in the selection sets, and instead maps the custom types to `any` (or whichever type is set as `defaultScalarType`) rather than to `Types.Scalars['MyCustomScalar']`. The `isUsingTypes()` does correctly infer that the custom type is defined by the main schema, resulting in the code assuming that the Types file needs to be be imported. This import is then not actually used in the type definition and triggers the `'Types' is declared but its value is never read` error mentioned above.

The scalar mapping *is* somehow correct in the variable types. We're for example getting:
```TypeScript
export type GetEditUserFormQueryVariables = Types.Exact<{
  userId: Types.Scalars['GUID']; // Correct
}>;

export type GetEditUserFormQuery = {
  __typename: 'Query';
  extendedUser: {
    __typename: 'ExtendedUser';
    id: string; // Incorrect, should be Types.Scalars['GUID']
  } | null;
};
```

For reference, my config below. You'd expect the bottom scalar definition to be unnecessary since it should resolve to the `Types`, but if not set it maps everything to `any`.

```yaml
schema: schema.json
generates:
  src/typings/_custom/api.generated.d.ts:
    plugins:
      - typescript
    config:
      enumsAsTypes: true
      defaultScalarType: unknown
      scalars:
        DateTime: string
        DateTimeOffset: string
        Decimal: number
        GUID: string
  src/:
    documents: 'src/**/*.gql'
    preset: near-operation-file
    presetConfig:
      baseTypesPath: typings/_custom/api.generated.d.ts
    plugins:
      - typescript-operations
      - typed-document-node
    config:
      scalars:
        DateTime: string
        DateTimeOffset: string
        Decimal: number
        GUID: string
```

**Comment by pleunv** [comment]
> Just ran into this as well while trying to integrate graphql-code-generator. Anyone happen to have found a workaround for this, by any chance? 🙂

The issue can be worked around by simply changing the `ScalarsMap` in my example above from

```yaml
config:
    scalars:
      DateTime: string
      DateTimeOffset: string
      Decimal: number
      GUID: string
```
to
```yaml
config:
    scalars:
      DateTime: Types.Scalars['DateTime']
      DateTimeOffset: Types.Scalars['DateTimeOffset']
      Decimal: Types.Scalars['Decimal']
      GUID: Types.Scalars['GUID']
```
This will use the import that's already in place and should work around the TS error in the first post.

**Comment by aaronadamsCA** [comment]
I also figured out another workaround. You can't do this:

```yml
config:
  scalars:
    CustomType: import("custom-type-lib").CustomType
generates:
  src/graphql.generated.d.ts:
    plugins:
      - typescript
  src/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: graphql.generated.d.ts
      extension: .graphql.generated.ts
    plugins:
      - typescript-operations
```

Instead you must currently do this:

```yml
generates:
  src/graphql.generated.d.ts:
    plugins:
      - typescript
    config:
      scalars:
        CustomType: import("custom-type-lib").CustomType
  src/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: graphql.generated.d.ts
      extension: .graphql.generated.ts
    plugins:
      - typescript-operations
    config:
      scalars:
        CustomType: Types.Scalars["CustomType"]
```
