### ISSUE TITLE
Double // @flow comment added to generated file

### ISSUE THREAD

**Issue by FezVrasta** [dotansimha/graphql-code-generator#4911]
**Describe the bug**
 

Hi, when I enable `flow` and `flow-operations` plugins at the same time, two `// @flow` headers are added to the `graphql.js` file.

**To Reproduce**

I tried to edit the template but it doesn't seem to work with the Flow plugins.

https://codesandbox.io/s/wizardly-paper-wsqgl?file=/document.graphql

1. My GraphQL schema:

```graphql
Not relevant for the issue
```

2. My GraphQL operations:

```graphql
Not relevant for the issue
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: 'allSchema.graphql'
generates:
  ./src/generated/graphql.js:
    documents: 'queries/*.js'
    plugins:
      - flow
      - flow-operations
```

**Expected behavior**

**Environment:**

- OS: macOS Catalina
- `@graphql-codegen/flow`: same as codesandbox
- `@graphql-codegen/flow-operations`: same as codesandbox
- NodeJS: 14.5.0

**Additional context**
