### ISSUE TITLE
Hooks generated with near-operation-file do not use the correct operation's name in typescript

### ISSUE THREAD

**Issue by Nicoowr** [dotansimha/graphql-code-generator#4980]
**Describe the bug**
First of all, thanks for this amazing tool!
I'd like to generate my hooks in multiple files using the plugin `near-operation-file`, without duplicating the document nodes. I use this config snippet (the full codegen.yml file is below): 
```yml
config:
      documentMode: external
      importDocumentNodeExternallyFrom: near-operation-file
      reactApolloVersion: 2
```

For example, the following hook is generated: 
```typescript
export function useUserQuery(baseOptions?: ApolloReactHooks.QueryHookOptions<UserQuery, UserQueryVariables>) {
        return ApolloReactHooks.useQuery<UserQuery, UserQueryVariables>(Operations.user, baseOptions);
      }
```

The problem is that `Operations.user` does not exist, the original operation, which is in a TS file, is this one: 

```typescript
export const query = gql`
  query user {
    user(id: 1) {
      id
      username
      email
    }
  }
`;
```
Hence, `Operations.query` should be used.

**To Reproduce**
The examples above come from this sandbox: https://codesandbox.io/s/quirky-engelbart-vn2rx
The steps are:
- Write the query in a TS file, with a gql tag and a `const` name which is not the same as the operation's name
- Run `yarn generate` with the related `codegen.yml`

1. My GraphQL schema:
The schema in the sandbox is:
```graphql
type Query {
    user(id: ID!): User!
    allUsers: [User!]!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:
I wrote the operation in a TS file with a tag from `graphql-tag`:
```typescript
export const query = gql`
  query user {
    user(id: 1) {
      id
      username
      email
    }
  }
`;
```

3. My `codegen.yml` config file:

```yml
overwrite: true

schema: "schema.graphql"
documents: "ovrlib/graphql/**/*.ts"

generates:
  types/__generated__/types.ts:
    plugins:
      - "typescript"
  ovrlib/graphql/:

    preset: near-operation-file
    presetConfig:
      baseTypesPath: ../../types/__generated__/types.ts
    plugins:
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      documentMode: external #documentNodeImportFragments
      importDocumentNodeExternallyFrom: near-operation-file
      reactApolloVersion: 2
```

**Expected behavior**
I expect the generated hooks to use the correct name: 
```typescript
export function useUserQuery(baseOptions?: ApolloReactHooks.QueryHookOptions<UserQuery, UserQueryVariables>) {
        return ApolloReactHooks.useQuery<UserQuery, UserQueryVariables>(Operations.query, baseOptions);
      }
```

**Environment:**

- OS: MacOS 10.15.7 Catalina
- `@graphql-codegen/...`: 
```
    "@graphql-codegen/add": "1.17.0",
    "@graphql-codegen/cli": "1.17.0",
    "@graphql-codegen/near-operation-file-preset": "^1.17.11",
    "@graphql-codegen/typescript": "1.17.0",
    "@graphql-codegen/typescript-operations": "1.17.0",
    "@graphql-codegen/typescript-react-apollo": "^2.0.7",
```
- NodeJS: 12.18.0

**Additional context**
I guess the problem is related to the fact I'm writing my operations in TS files, whereas you expect them to be written in a .graphql file. If this is the case, do you think this is a feature request easy to handle? I could take care of it :)
