### ISSUE TITLE
Ability to suppress generation of FragmentDocs

### ISSUE THREAD

**Issue by cancan101** [dotansimha/graphql-code-generator#4981]
I am using the codegen to generate only the typescript types and hence do not need the various `FragmentDocs`. Is there any way to prevent their generation?

I have this in my config now, so the `FragmentDocs` should not be needed:
```yml
skipTypename: true
withHooks: false
withHOC: false
withComponent: false
withMutationFn: false
```
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

I have tried various options for `documentMode` but none them of seem to entirely prevent this output.

**Additional context**
