### ISSUE TITLE
Inconsistent behavior when configuring via codegen.yml and graphqlrc

### ISSUE THREAD

**Issue by tvvignesh** [dotansimha/graphql-code-generator#5013]
**Describe the bug**
Hi. I was on my move from `codegen.yml` to using `.graphqlrc.yml` for all config for codegen, VSCode graphql and so on.

While doing so, I noticed that the same config behaved differently when using `codegen.yml` and when using `graphql-config`

eg:

**This works:** (codegen.yml)

```yml
schema:
  - './packages/modules/**/schema/**/*.gql'
generates:
  ./packages/core/src/generated/global.gql.types.generated.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-resolvers
      - add:
          placement: prepend
          content: "import { DeepPartial } from 'utility-types';"
    config:
      defaultMapper: DeepPartial<{T}>
      federation: true
watch: true
overwrite: true
```

**This does not** (graphqlrc)

```yml
projects:
  globalgql:
    config:
      federation: true
    schema:
      - "./packages/modules/**/schema/**/*.gql"
    extensions:
      codegen:
        generates:
          ./packages/core/src/generated/global.gql.types.generated.ts:
            plugins:
              - typescript
              - typescript-operations
              - typescript-resolvers
              - add:
                  placement: prepend
                  content: "import { DeepPartial } from 'utility-types';"
            config:
              federation: true
              defaultMapper: DeepPartial<{T}>
```

I get schema validation error:

```
Error: Cannot extend type "AccountSchema" because it is not defined.

    Unknown directive "@key".

    Unknown directive "@external".

    Unknown directive "@key".

    Unknown type "AccountSchema".

    Cannot extend type "Mutation" because it is not defined.

    Cannot extend type "Query" because it is not defined.

    Unknown directive "@key".

    Unknown directive "@key".

    Unknown type "Query".

    Unknown type "Mutation".
        at assertValidSDL (/data/tc/projects/mlp/tc-services-global/tc-svc-auth/node_modules/.pnpm/graphql@15.4.0/node_modules/graphql/validation/validate.js:107:
11)
        at Object.buildASTSchema (/data/tc/projects/mlp/tc-services-global/tc-svc-auth/node_modules/.pnpm/graphql@15.4.0/node_modules/graphql/utilities/buildASTSc
hema.js:45:34)
        at makeSchema (/data/tc/projects/mlp/tc-services-global/tc-svc-auth/node_modules/.pnpm/@graphql-tools/merge@6.2.5_graphql@15.4.0/node_modules/@graphql-too
ls/merge/index.cjs.js:976:99)
        at Object.mergeSchemasAsync (/data/tc/projects/mlp/tc-services-global/tc-svc-auth/node_modules/.pnpm/@graphql-tools/merge@6.2.5_graphql@15.4.0/node_module
s/@graphql-tools/merge/index.cjs.js:967:12)
        at async Object.loadSchema (/data/tc/projects/mlp/tc-services-global/tc-svc-auth/node_modules/.pnpm/@graphql-tools/load@6.2.5_graphql@15.4.0/node_modules/
@graphql-tools/load/index.cjs.js:650:20)
        at async /data/tc/projects/mlp/tc-services-global/tc-svc-auth/node_modules/.pnpm/@graphql-codegen/cli@1.19.0_graphql@15.4.0/node_modules/@graphql-codegen/
cli/bin.js:845:55
        at async Task.task (/data/tc/projects/mlp/tc-services-global/tc-svc-auth/node_modules/.pnpm/@graphql-codegen/cli@1.19.0_graphql@15.4.0/node_modules/@graph
ql-codegen/cli/bin.js:698:17)
```

After discussing with @ardatan I also tried adding `assumeValid: true` and `assumeValidSDL: true` and still had the same issue.

**Environment:**

- OS: Windows 10 Home host, Ubuntu 20.04 remote

```
"@graphql-codegen/add": "^2.0.1",
"@graphql-codegen/cli": "^1.19.0",
"@graphql-codegen/typed-document-node": "^1.17.9",
"@graphql-codegen/typescript": "^1.17.10",
"@graphql-codegen/typescript-operations": "^1.17.8",
"@graphql-codegen/typescript-resolvers": "^1.17.10",
```
- NodeJS: v14.14.0

**Additional context**

This might also be somewhat related to https://github.com/graphql/vscode-graphql/issues/250 since VSCode GraphQL also uses `graphql-config` and I have the same error there with `graphqlrc` file
