### ISSUE TITLE
default config file generated by graphql-cli is different from by codegen cli

### ISSUE THREAD

**Issue by Diluka** [dotansimha/graphql-code-generator#5044]
missing plugin `typescript-operations` and generated file missing type declaration but has reference raising an error

`graphql init` _generated into existed project frontend only and I only changed the file path_
```yml
# .graphqlrc.yml
schema: ./schema.graphql
documents: ./src/**/*.graphql
extensions:
  codegen:
    generates:
      ./src/generated/graphql.ts:
        plugins:
          - typescript
          - typescript-apollo-angular

```

`npx graphql-codegen init`
```yml
# codegen.yml
overwrite: true
schema: "http://localhost/graphql"
documents: "src/**/*.graphql"
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-apollo-angular"
```
