### ISSUE TITLE
TypeScript - Bad syntax generated due to private interface

### ISSUE THREAD

**Issue by ArrayKnight** [dotansimha/graphql-code-generator#5074]
**Describe the bug**
When a public query would return a private interface (due to a mistake in the public schema), the Codegen CLI "successfully" completes, but creates a type definition file with invalid (syntactically incorrect) types/interfaces (`Maybe<Array<Maybe<>>>`).

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type Foo = { ... } # Private type which should be public but isn't (setting in CMSs public GraphQL schema)

type Query = {
    foos(id: String): [Foo]
}
```

2. My GraphQL operations:

```graphql
query Foos($id: String) {
    foos(id: $id) { ... }
}
```

3. My `codegen.yml` config file:

```yml
schema: ${GRAPHQL_SCHEMA_URL}
documents:
    - 'src/**/*.{ts,tsx}'
    - '!src/graphql/*'
generates:
    src/graphql/index.tsx:
        plugins:
            - typescript
            - typescript-operations
            - fragment-matcher
        config:
            avoidOptionals: true
            nonOptionalTypename: true

```

4. My `src/graphql/index.tsx`:

```typescript
export type FoosQuery = (
    { __typename: 'Query' } &
    { foos: Maybe<Array<Maybe<>>> } // <-- Missing interface due to private type, would be Pick<Foo, '...'> if it were public
)
```

**Expected behavior**
Codegen CLI should throw an error detailing that there is a missing/private type that it can't write and then not output a file

**Environment:**

- OS: Windows 10
- "@graphql-codegen/cli": "^1.19.1",
- "@graphql-codegen/fragment-matcher": "^2.0.0",
- "@graphql-codegen/schema-ast": "^1.18.0",
- "@graphql-codegen/typescript": "^1.17.11",
- "@graphql-codegen/typescript-operations": "^1.17.9",
- NodeJS: 13.11.0
