### ISSUE TITLE
GraphQL Codegen with Modules preset

### ISSUE THREAD

**Issue by tvvignesh** [dotansimha/graphql-code-generator#5136]
Hi. I am trying to use Codegen with the GraphQL Modules preset as documented here: https://graphql-code-generator.com/docs/presets/graphql-modules

The thing is, the generation works well (both the overall types and module specific types), but I have a problem.

I have a separate `tsconfig` and `package.json` file for every module and use it with `PNPM workspaces` making it completely isolated and my packages structure look something like this:

<img width="250" alt="1" src="https://user-images.githubusercontent.com/1165845/100347602-a40cae00-300b-11eb-82a7-19d0db030a85.png">

What I wanted to do was put the overall types into the `core` folder and module specific file inside the specific module within the `modules` folder so that I can import like this.

`import * as Types from "@timecampus/core";` where `@timecampus/core` is the name of my workspace package which I import into every module.

Now, if I try adding a config like this:

```ts
codegen:
        generates:
          ./packages/modules/:
            schema: ./packages/modules/*/schema/*.gql
            preset: graphql-modules
            presetConfig:
              baseTypesPath: ../core/src/generated/global.gql.types.generated.ts
              filename: src/generated/module.generated.ts
```

This happens:
1. The import becomes `import * as Types from "../../../../core/src/core/src/generated/global.gql.types.generated";` (Notice 2 `core/src` here).
2. If I manually edit the path to correct it, I get this error since the `core` folder is outside my module folder:

<img width="586" alt="1" src="https://user-images.githubusercontent.com/1165845/100348133-7ffd9c80-300c-11eb-9d49-f2f566e22391.png">

**What I want to do:**

1. Generate the overall types in the core folder
2. Generate the module specific types in the module folder
3. Import the overall types from the core folder like this: `import * as Types from "@timecampus/core";` (by providing my own import override)

This way all the issues would be sorted out. Thanks.

**Comment by dotansimha** [comment]
Oh interesting :) the thing here - we can't know how to resolve that file within your workspace. 

I think maybe we can do like we are doing with other presets. We allow to override the import path of the base types. I think this should work for you right?

**Comment by tvvignesh** [comment]
@dotansimha Since everything else is working without any issues, I should be good to go if I am just able to override the import. Don't need anything else. 

I am not sure what you are talking about when you say "We allow to override the import path of the base types" though since I am not able to see that in the docs. Thanks.

**Comment by dotansimha** [comment]
Implemented in: https://github.com/dotansimha/graphql-code-generator/commit/6b708b69ac8b0aa784d771589148107ed6d10522 

Available in `@graphql-codegen/graphql-modules-preset@1.1.0`.

Given your example, this is how it should look like:

```
presetConfig:
  importBaseTypesFrom: "@timecampus/core"
```

**Comment by tvvignesh** [comment]
@dotansimha Hi. Just tested it out and it works great.

It is just that if I use `@timecampus/core` it does `import * as Types from "@timecampus/core";` but I am doing a named export within the `core` module as `export * as GQLTypes from './generated/global.gql.types.generated.js';` and was expecting something along the lines of `import { GQLTypes as Types } from "@timecampus/core";` since it is otherwise invalid but currently, there is no option to configure like that.

But to overcome this, I have changed my config like this now importing the file itself rather than the index of the `core` package:

```yml
./packages/modules/:
            schema: ./packages/modules/*/schema/*.gql
            preset: graphql-modules
            presetConfig:
              baseTypesPath: ../core/src/generated/global.gql.types.generated.ts
              filename: src/generated/module.generated.ts
              importBaseTypesFrom: "@timecampus/core/src/generated/global.gql.types.generated"
              importTypesNamespace: "Types"
```

Thanks.
