### ISSUE TITLE
Cli inline config or configuration in `package.json`

### ISSUE THREAD

**Issue by JounQin** [dotansimha/graphql-code-generator#5140]
**Is your feature request related to a problem? Please describe.**

Sometimes, the configuration is just so small and I'd prefer to add it into `package.json` or even use cli inline config instead:

```yaml
overwrite: true
schema: "schema.graphql"
generates:
  schema.d.ts:
    plugins:
      - "typescript"
```

**Describe the solution you'd like**

As title, config inline or in `package.json`.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A
