### ISSUE TITLE
Pass the client in the codgen.yml, when using graphql-request with react-query

### ISSUE THREAD

**Issue by yassinebridi** [dotansimha/graphql-code-generator#5156]
**Is your feature request related to a problem? Please describe.**

When using `react-query` plugin with `graphql-request`, it requires you to always pass the client in the generated query like in the provided example:
```ts
import { useMyQuery } from './generated';
import { client } from './my-graphql-request-client';

export const MyComponent = () => {
  const { status, data, error, isFetching } = useMyQuery(client, {});
};
``` 

**Describe the solution you'd like**
It would be cool to pass the client in the `codegen.yml`, like for the example you do with the fetch option:
```yml
plugins:
  - add:
     content: "import { endpointUrl, fetchParams } from './my-config';"
  - typescript
  - typescript-operations
  - typescript-react-query
config:
  fetcher:
    endpoint: 'endpointUrl'
    fetchParams: 'fetchParams'
```
