### ISSUE TITLE
React-query's mutations variables are not optional

### ISSUE THREAD

**Issue by yassinebridi** [dotansimha/graphql-code-generator#5157]
**Describe the bug**
 
Using mutations with react-query, requires you to specify variables in advance, which is not always desirable:
```ts
const [login] = useLoginMutation(client, { username: "", password: "" })
```
Unlike the react-apollo plugin which makes specifying variables in a more declarative way like this:
```ts
const [login] = useLoginMutation(client)

// Then provide variables when time comes.
const res = await login({
  username,
  password
});
```

**Environment:**
```yml
plugins:
  - typescript
  - typescript-operations
  - typescript-react-query
config:
  fetcher: graphql-request
```
