### ISSUE TITLE
type generation breaks on @graphql-codegen/typescript-react-apollo@2.2.1 

### ISSUE THREAD

**Issue by lauromueller** [dotansimha/graphql-code-generator#5166]
Before describing the bug, let me just drop a big "thank you" for this code generator. Saves a lot of time and headache when managing our React + Apollo app 🙂 

**Describe the bug**

We currently use `@graphql-codegen/typescript-react-apollo@2.1.1` to generate graphql types and helper hooks for the Apollo Client serving our application. So far everything is working fine, however, when trying to update to version 2.2.1, the generated types start to contain several `[object Object]` instances. 

More precisely, this happens within generated `Pick<...>` types. For example, suppose I have the following type definition:

```graphql
type MyType {
  myFirstField: String;
  mySecondField: String;
}

extend type Query {
  myObject: MyType
}

query getMyTypeFirstField {
  myObject {
    myFirstField
  }
}
```

Then the result of running the generator outputs a broken type definition: 

```typescript
export type MyTypeFields = Maybe<{ __typename: 'MyType' } & Pick<MyType, '[object Object]'>>
```

The expected output would be:

```typescript
export type MyTypeFields = Maybe<{ __typename: 'MyType' } & Pick<MyType, 'myFirstField'>>
```

My guess is that this is related to https://github.com/dotansimha/graphql-code-generator/pull/5104, as the definitions for `MakeOptional` were updated and `MakeMaybe` was introduced.

My `codegen.yml` config file:

```yml
overwrite: true
hooks:
  afterAllFileWrite:
    - "yarn prettier:fix"
schema:
  - "src/types/cache/cacheTypeDefs.ts"
documents:
  - "src/**/*.ts"
generates:
  src/types/generated/cacheTypes.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
  ./graphql.schema.json:
    plugins:
      - "introspection"
```
