### ISSUE TITLE
Duplicate fragment names (in multiple files) causes command to fail

### ISSUE THREAD

**Issue by joesaunderson** [dotansimha/graphql-code-generator#5196]
**Describe the bug**
I have two separate queries, with separate fragments (named the same).

These queries are in different directories within my project, so I would expect both of them to create separate `EntityFragment` types in the generated files.

Instead, I receive this error:

```
yarn run v1.22.4
$ graphql-codegen --config codegen.yml
Multiple fragments with the name(s) "entity" were found.
Multiple fragments with the name(s) "entity" were found.
Not all fragments have an unique name: entity
Not all fragments have an unique name: entity
Something went wrong
error Command failed with exit code 1.
```

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

File 1:
```graphql
fragment entity on Entity {
    id
    somefield
}
```

File 2:
```graphql
fragment entity on Entity {
    id
    someotherfield
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
errorsOnly: true
schema:
    - schema.graphql:
          loader: "./app/scripts/webpack/graphql-schema.js"
documents: "src/**/*.graphql"
generates:
    src/js/shared/@types/graphql.d.ts:
        plugins:
            - "typescript"
        config:
            skipTypename: true
            useTypeImports: true
            declarationKind: "interface"
    src/:
        preset: near-operation-file
        presetConfig:
            extension: .generated.ts
            baseTypesPath: js/shared/@types/graphql.ts
        plugins:
            - "typescript-operations"
            - "typed-document-node"
        config:
            skipTypename: true
            declarationKind: "interface"

```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS: Ubuntu
```json
        "@graphql-codegen/cli": "1.19.1",
        "@graphql-codegen/near-operation-file-preset": "^1.17.12",
        "@graphql-codegen/typed-document-node": "^1.17.10",
        "@graphql-codegen/typescript": "1.17.11",
        "@graphql-codegen/typescript-operations": "1.17.9",
```
- NodeJS: 14.7.0

**Additional context**
<!-- Add any other context about the problem here. -->

**Comment by dotansimha** [comment]
Can you please try to move `documents: "src/**/*.graphql"` to the `src/:` section?

**Comment by joesaunderson** [comment]
> Can you please try to move `documents: "src/**/*.graphql"` to the `src/:` section? 
> 
> 

- Sorry I'm not following, do you mean like this:

```
generates:
    src/js/shared/@types/graphql.d.ts:
        plugins:
            - "typescript"
        config:
            skipTypename: true
            useTypeImports: true
            declarationKind: "interface"
    src/:
        documents: "src/**/*.graphql"
        preset: near-operation-file
        presetConfig:
            extension: .generated.ts
            baseTypesPath: js/shared/@types/graphql.ts
        plugins:
            - "typescript-operations"
            - "typed-document-node"
        config:
            skipTypename: true
            declarationKind: "interface"

```
