### ISSUE TITLE
Unable to find template plugin matching 'typescript-operations'

### ISSUE THREAD

**Issue by JonasMS** [dotansimha/graphql-code-generator#5228]
**Describe the bug**
Running `graphql-codegen --config gqlgen.yml` results in the following error `Unable to find template plugin matching 'typescript-operations'`.

I know that other issues on this error have been created. None of the solutions that have worked for others work for me. Notably, I'm the only person on my team w/ this issue which leads me to think that there's an issue with my environment (but I'm not sure).

By adding logging to the `@graphql-codegen/cli` code I can see that when the error above is triggered, another error is being ignored: `Error: Cannot find module 'graphql-toolkit'`. Installing `graphql-toolkit`, as mentioned in one of the previous issues on this error, results in a different error:

```
TypeError: Cannot read property 'definitions' of undefined
        at /Users/jonas/Documents/debtsy/web/node_modules/graphql/utilities/concatAST.js:21:18
        at Array.flatMap (<anonymous>)
```

I've been able to resolve this issue by prepending `^` to all the plugins in `package.json`, thus insuring they're all up to date. Unfortunately, comparing with a teammate, it's evident that my gqlgen produces different generated code than my teammates. This results in a bunch of TS errors.

**To Reproduce**
[Sandbox](https://codesandbox.io/s/goofy-almeida-cmxq3?file=/package.json)
note: using npm

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: ../debtsy/generated/schema.gql
documents: "src/**/*.gql"
generates:
  src/generated/fragmentTypes.json:
    plugins:
      - fragment-matcher
    config:
      apolloClientVersion: 3
  src/generated/graphql.tsx:
    plugins:
      - add:
          content: import {PIIString} from "../utils/PIIString";
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      reactApolloVersion: 3
      apolloReactHooksImportFrom: "@apollo/client"
      apolloReactCommonImportFrom: "@apollo/client"
      withHooks: true
      noGraphQLTag: true
      withHOC: false
      withComponent: false
      scalars:
        PIIString: PIIString
  src/generated/fieldpolicies.tsx:
    plugins:
      - fieldpolicies.js
    config:
      fieldMapping:
        PIIString:
          read: "(value: string) => new PIIString(value)"
          merge: "(existing: string, value: any) => value instanceof PIIString ? value.dangerousGetPIIValue() : value"
      imports:
        - import { PIIString } from "../utils/PIIString";
```

**Expected behavior**
Generate code w/out errors and that matches my teammates.

**Environment:**

- OS: OS X Catalina 10.15.7
- `@graphql-codegen/...`: 
- NodeJS: 14.15.1
- NPM: 6.14.8
