### ISSUE TITLE
All generated Fragments have [object Object]

### ISSUE THREAD

**Issue by Slmii** [dotansimha/graphql-code-generator#5239]
**Describe the bug**
 
Since today my generated `graphql Fragment` have values of `[object Object]`. I never encountered this issue before. This only happens with fragments.

![image](https://user-images.githubusercontent.com/9927849/101912205-b832dc80-3bc1-11eb-9b8c-22111bae131f.png)
![image](https://user-images.githubusercontent.com/9927849/101912451-0d6eee00-3bc2-11eb-9a77-fa5afaa7b6ea.png)

Everything used to work fine but since today after running `grapqhl-codegen` this happened. The graphql server works fine, nothing wrong with that. In the playground I get back the expected results without any errors.

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
query Me {
	me {
		...Me
	}
}
fragment Me on User {
	id
	email
	name
	role
}

query MyTrips {
	myTrips {
		...Trip
	}
}
fragment Trip on Trip {
	id
	uuid
	userId
	name
	description
	public
	dateFrom
	dateTo
	adults
	children
	infants
	backgroundUrl
	createdAt
	updatedAt
	isInFavorite
	locations {
		...Location
	}
	preparations {
		...Preparation
	}
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: 'http://localhost:4000/graphql'
documents: 'src/graphql/**/*.graphql'
generates:
    src/generated/graphql.tsx:
        plugins:
            - 'typescript'
            - 'typescript-operations'
            - 'typescript-react-apollo'
        config:
            withHooks: true
            withRefetchFn: true
```
4. My npm command:
`"generate": "graphql-codegen --config codegen.yml"`

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
Not have to `[object Object]` as shown in the above images

**Environment:**

- OS: Windows 10
```js
"@graphql-codegen/cli": "1.19.0",
"@graphql-codegen/typescript": "1.17.11",
"@graphql-codegen/typescript-operations": "1.17.8",
"@graphql-codegen/typescript-react-apollo": "^2.0.7",
```
- NodeJS: 

**Additional context**
<!-- Add any other context about the problem here. -->
Even tho the types are wrong the data is still there. Example if I log this `data?.myTrips.trips` it will show the data correctly, its just the typing that are messed up now.
