### ISSUE TITLE
no config in experimental graphql-modules generation

### ISSUE THREAD

**Issue by maapteh** [dotansimha/graphql-code-generator#5242]
In the old schema creation we had this config:

```
        config:
            constEnums: true
            avoidOptionals: true
            namingConvention:
                enumValues: change-case#upperCase
```

then enums became exportable as const enums. Now the new graphql-modules option creates the complete schema but i cant set any config. So i lost all my enums basically. I can create the other as well, but why having two schemas :)

btw really cool to see the progress on the suite!

**Comment by dotansimha** [comment]
Hi! 
Thank you for reporting it. 
We do allow custom configurations, but not for enums customizations.

In this new preset, we generate main types file with everything in it, and then generate types file per graphql-module, with the contribution of it to the result schema. 

Since [TypeScript enums are nominal types](https://basarat.gitbook.io/typescript/main-1/nominaltyping#:~:text=%E2%80%8BEnums%20in%20TypeScript%20offer,that%20are%20otherwise%20structurally%20compatible.), we can define the entire enum in the main file, and the pick specific values from it. 
The only way to allow this kind of flow where main types files defined everything and each module types file takes what it needs is to use const string enums, instead of `enum`.

Do you think there is another way to solve that?

**Comment by maapteh** [comment]
No not really unfortunately. I hope to work on it next year since now i only have three working days left :)

**Comment by maapteh** [comment]
What i do saw, not related to this issue, but for me its weird to see typings getting created like in the docs..

When i changed:
```
        presetConfig:
            filename: generated-types/module-types.d.ts
```

and tested if the declaration now can be picked up with this change in creation file:

```
declare namespace ProductModule {

  import * as Types from "../../../generated-types/_graphql";
  import * as gm from "graphql-modules";

  interface DefinedFields {
```

Then i dont have to import anything, which is in my opinion better :)

So my resolver will look like:

```
import { ProductDataloader } from '../providers/product.dataloader';

export const resolvers: ProductModule.Resolvers = {
    Query: {
        product: async (
            _: any,
            { id }: any,
            { injector }: GraphQLModules.Context,
        ) => {
            return injector.get(ProductDataloader).load(id);
        },
```

No imports needed :)

**Comment by jjangga0214** [comment]
@dotansimha 
@maapteh 
> The only way to allow this kind of flow where main types files defined everything and each module types file takes what it needs is to use const string enums, instead of enum.
>
> Do you think there is another way to solve that?

What if just copy-pasting? 
Let `enum` be declared in main file, and each module types 'paste' it, not 'pick' it.

**Comment by jjangga0214** [comment]
### Workaround for other folks

`config: enumsAsTypes: false` of plugin `typescript` does not work with `graphql-modules` preset.

So, you can generate typescript `enum` only with `typescript` (without `graphql-modules`).
Then, you can configure `config: enumsValues` on `graphql-modules` generation.

```yaml
overwrite: true
generates:
  ./src/generated/graphql/self-enum.ts:
    schema:
      - ./src/graphql/module/*/*.graphql:
          commentDescriptions: true
    plugins:
      - typescript
    config:
      typesPrefix: Gql
  ./src/graphql/module:
    schema:
      - ./src/graphql/module/*/*.graphql:
          commentDescriptions: true
    preset: graphql-modules
    presetConfig:
      baseTypesPath: ../../generated/graphql/self.ts # Where to create the complete schema types
      filename: generated.ts # Where to create each module types
    plugins:
      - typescript
      - typescript-resolvers
    config:
      typesPrefix: Gql
      # enumsAsTypes: false # This does not work. 
      enumValues:
        foo ./self-enum#GqlFoo
        bar ./self-enum#GqlBar
```

```ts
import { YourModule } from './generated'
import { GqlFooEnum, GqlBarEnum } from '..path/to/generated/self-enum'

// import enum types independently, but they are compatible with graphql-modules' generated enums.
```
