### ISSUE TITLE
Missing generation of union types (typescript-type-graphql)

### ISSUE THREAD

**Issue by bridges-wood** [dotansimha/graphql-code-generator#5254]
**Describe the bug**
typescript-type-graphql plugin does not generate the necessary `createUnionType` function when generating a union type.

**To Reproduce**
Use a union type as a property of a document and generate using the typescript-type-graphql plugin.

https://codesandbox.io/s/strange-northcutt-ki24s?file=/types.ts

1. My GraphQL schema:

```graphql
type ALevel {
	subject: ALevelSubject!
	grade: ALevelGrade!
}

type BTEC {
	subject: String!
	grade: BTECGrade!
}

union Qualification = ALevel | BTEC

type Information {
	qualifications: [Qualification!]!
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: './src/*.gql'
generates:
../graphql/src/qlModels.ts:
    plugins:
      - typescript-type-graphql
    config:
      namingConvention: keep
```

**Expected behavior**
a `createUnionType` function is generated for each union type.

**Environment:**

- OS: Ubuntu 20.04
- `@graphql-codegen/cli`: 1.19.4
- `@graphql-codegen/typescript-type-graphql`: 1.18.2
- NodeJS: 14.15.1
