### ISSUE TITLE
Custom Types Returned from Directives Not Working

### ISSUE THREAD

**Issue by mikefisher84** [dotansimha/graphql-code-generator#5264]
**Describe the bug**

Our app uses a custom `@email` directive that does some extra validation and returns a type of `Email` 

```ts
export class EmailType extends GraphQLScalarType {
  constructor(type: GraphQLScalarType) {
    super({
      name: 'Email',
      parseValue: (value) => {
        if (!validateEmail(value)) {
          throw new UserInputError('Email address failed validation');
        }

        return type.parseValue(value);
      },
      serialize: (value) => type.serialize(value),
      parseLiteral: (ast) => {
        if (ast.kind === Kind.STRING && !validateEmail(ast.value)) {
          throw new UserInputError('Email address failed validation');
        }

        return type.parseLiteral(ast, {});
      },
    });
  }
}
```

Our schema is defined like this: 

```gql
input UserInput {
  email: String! @email
  firstName: String!
  lastName: String!
}
```

Codegen outputs types that look like: 

```ts
export type CreateUserInput = {
  email: Scalars['String'];
  firstName: Scalars['String'];
  lastName: Scalars['String'];
};
```

This makes sense because it's the custom directive javascript code that returns the `Email` type. 

Our problem is we use Apollo Studio and `ApolloServerPluginSchemaReporting` to report our schema to Apollo Studio. Apollo while running evaluates our UserInputType as: 

```graphql
input UserInput {
  email: Email
  firstName: String!
  lastName: String!
};
```

However in CI when we do schema validation we get failures because our `graphql-codgen` schema shows those types as simply`String` and not type `Email` 

I've done a lot of digging and I can't seem to find a proper way to remedy this. Can codegen convert `@email` directives to the correct interpolated type? 

1. My GraphQL schema:

```graphql
input UserInput {
  email: String! @email
  firstName: String!
  lastName: String!
}
```

3. My `codegen.yml` config file:

```yml
schema:
  - 'src/graphql/**/schema.ts'
  - 'src/graphql/**/regexp.ts'
  - 'src/graphql/directives/email.ts'
  - 'src/graphql/directives/length.ts'
generates:
  src/graphql/generated/graphql.ts:
    config:
      contextType: '@graphql/index#Context'
      enumsAsTypes: true
      noSchemaStitching: true
      # https://graphql-code-generator.com/docs/plugins/typescript-resolvers#mappers---overwrite-parents-and-resolved-values
      scalars:
        Cursor: ../scalar_types#Cursor
        Date: ../scalar_types#DayString
        DateTime: ../scalar_types#DateTimeString
        PositiveFloat: ../scalar_types#PositiveFloat
        PositiveInt: ../scalar_types#PositiveInt
        NonNegativeFloat: ../scalar_types#NonNegativeFloat
        NonNegativeInt: ../scalar_types#NonNegativeInt
        RegExp: RegExp
      useIndexSignature: true
    plugins:
      - add: |
          /* eslint-disable */
          /* THIS IS A GENERATED FILE, DO NOT EDIT. */
      - 'typescript'
      - 'typescript-resolvers'
  src/graphql/generated/schema.graphql:
    plugins:
      - schema-ast
    config:
      includeDirectives: true
  src/graphql/generated/schema.json:
    plugins:
      - introspection
    config:
      minify: false

```

**Comment by dotansimha** [comment]
Hi @mikefisher84 ,
This is a very specific use-case, where you use a directive to manipulate the schema? Where is it done? Because it seems like your are referring to a schemaDirective that changes the schema? 

Btw, why not use a scalar called `Email` and do this kind of validation there? you'll get the same result with a statically defined type.

**Comment by mikefisher84** [comment]
Hey @dotansimha thanks for getting back to me and I can't say I completely disagree with you regarding the custom `Email` scalar. However I'm basically following an example out of the Apollo documentation around custom directives verbatim, so I'm surprised I'm the first person to have this issue. Also while I only mentioned the `@email` use case in my ticket we also have an identical `@length` custom directive as described below. 

If you look at the Apollo docs around implementing [custom directives](https://www.apollographql.com/docs/apollo-server/schema/creating-directives/#enforcing-value-restrictions). They create a `@length(8)` directive to enforce a maximum length of a string. 

Which they define like this 

```graphql
  type Book {
    title: String @length(max: 50)
  }
```

They have a class that creates the logic for the directive: 
```ts
class LengthDirective extends SchemaDirectiveVisitor {
  visitInputFieldDefinition(field) {
    this.wrapType(field);
  }

  visitFieldDefinition(field) {
    this.wrapType(field);
  }

  // Replace field.type with a custom GraphQLScalarType that enforces the
  // length restriction.
  wrapType(field) {
    if (
      field.type instanceof GraphQLNonNull &&
      field.type.ofType instanceof GraphQLScalarType
    ) {
      field.type = new GraphQLNonNull(
        new LimitedLengthType(field.type.ofType, this.args.max),
      );
    } else if (field.type instanceof GraphQLScalarType) {
      field.type = new LimitedLengthType(field.type, this.args.max);
    } else {
      throw new Error(`Not a scalar type: ${field.type}`);
    }
  }
}
```

Then they have a class that returns a different type for anything that is decorated with the @length directive. 

```ts
class LimitedLengthType extends GraphQLScalarType {
  constructor(type, maxLength) {
    super({
      name: `LengthAtMost${maxLength}`,

      // For more information about GraphQLScalar type (de)serialization,
      // see the graphql-js implementation:
      // https://github.com/graphql/graphql-js/blob/31ae8a8e8312/src/type/definition.js#L425-L446

      serialize(value) {
        value = type.serialize(value);
        assert.isAtMost(value.length, maxLength);
        return value;
      },

      parseValue(value) {
        return type.parseValue(value);
      },

      parseLiteral(ast) {
        return type.parseLiteral(ast);
      },
    });
  }
}
```

Specifically this line is where the new scalar is being created. 
`name: `LengthAtMost${maxLength}`,`

So you could see in this example it wouldn't be very scalable to make a custom scalar for every MaxLength type in the app as you'd have to create: `MaxLength6`, `MaxLength8` so on and so forth for every potential argument your `@length()` directive could support. .

**Comment by dotansimha** [comment]
Got it. But still, it's a custom way to declare your schema. I do agree that it's needed, since you can't pass arguments to scalars. In case of an email, scalar fits perfectly. 
In case of more complex examples, like the one you shared, it is needed.

To workaround that, you can tell codegen to load your schema from a code file, and tell it to ignore plucking. This will result in `require` to your file, and get the actual schema from your code (after all modifications). 
Take a look at this page: https://graphql-code-generator.com/docs/getting-started/schema-field#code-files (note `noPluck` config). 

Then, make sure to point codegen to a file (preferably, a single `.ts` file) that exports the ready, modified, `GraphQLSchema` object.

**Comment by mikefisher84** [comment]
Thanks @dotansimha ! I'm working on implementing that solution but it seems when I add noPluck codegen throws cli errors. 

```
src/graphql/generated/graphql.ts
    Failed to load schema from src/graphql/**/schema.ts,src/graphql/**/regexp.ts,src/graphql/directives/email.ts,src/graphql/directives/length.ts:

        Unable to load from file "/Users/mike/app/src/graphql/directives/length.ts": Cannot use import statement outside a module
        Error: Unable to load from file "/Users/mike/app/src/graphql/directives/length.ts": Cannot use import statement outside a module
    at tryToLoadFromExport (/Users/mike/app/node_modules/@graphql-tools/code-file-loader/index.cjs.js:143:15)
```

The top of my codegen yml now looks like this: 

```yml
schema:
  # This glob pattern searches for all schema.ts files with gql tags to generate the schema.
  # We also need to include the custom regexs and directives to properly generate schema and types
  - 'src/graphql/**/schema.ts'
  - 'src/graphql/**/regexp.ts'
  - 'src/graphql/directives/email.ts' 
  - 'src/graphql/directives/length.ts': 
      noPluck: true
```

And my custom directive code for length looks like this: 

```ts
import {gql, UserInputError, SchemaDirectiveVisitor} from 'apollo-server-express';
import {
  GraphQLInputField,
  GraphQLNonNull,
  GraphQLScalarType,
  isWrappingType,
  isNamedType,
} from 'graphql';
import {Kind} from 'graphql/language';

export const lengthTypeDef = gql`
  directive @length(min: Int, max: Int) on INPUT_FIELD_DEFINITION
`;

const validate = (value: string, args: {min: number; max?: number}): void => {
  const {min, max} = args;
  const lengthValue = value.length;

  if (max && lengthValue > max) {
    throw new UserInputError(`Password can't have more than ${max} characters`);
  }

  if (lengthValue < min) {
    throw new UserInputError(`Password must be ${min} characters or more`);
  }
};

interface LengthTypeArgs {
  min: number;
  max?: number;
}

export class LengthType extends GraphQLScalarType {
  constructor(type: GraphQLScalarType, args: LengthTypeArgs) {
    super({
      name: `LengthMin${args.min}${args.max ? `'Max' ${args.max}` : ''}`,
      parseValue: (value) => {
        validate(value, args);

        return type.parseValue(value);
      },
      serialize: (value) => type.serialize(value),
      parseLiteral: (ast) => {
        if (ast.kind === Kind.STRING) {
          validate(ast.value, args);
        }

        return type.parseLiteral(ast, {});
      },
    });
  }
}

class LengthDirective extends SchemaDirectiveVisitor {
  visitInputFieldDefinition(field: GraphQLInputField): void {
    this.wrapType(field);
  }

  wrapType(field: GraphQLInputField): void {
    if (field.type instanceof GraphQLNonNull && field.type.ofType instanceof GraphQLScalarType) {
      field.type = new GraphQLNonNull(
        new LengthType(field.type.ofType, this.args as LengthTypeArgs),
      );
    } else if (field.type instanceof GraphQLScalarType) {
      field.type = new LengthType(field.type, this.args as LengthTypeArgs);
    } else {
      throw new Error(`Not a scalar type: ${field.type}`);
    }

    const typeMap = this.schema.getTypeMap();
    let {type} = field;

    if (isWrappingType(type)) {
      type = type.ofType;
    }

    if (isNamedType(type)) {
      typeMap[type.name] = type;
    }
  }
}

export default LengthDirective;
```

Any ideas??

**Comment by dotansimha** [comment]
Try something like that: 

```
  - 'src/graphql/codegne-schema.ts': 
      noPluck: true
```

Then, inside `codegne-schema.ts`, make sure to load all other files, do your schema changes, and export a ready-to-use `GraphQLSchema`. 

For the specific error you got, I think you need `require` field set because of TS. See: https://graphql-code-generator.com/docs/getting-started/require-field#typescript-support

**Comment by mikefisher84** [comment]
Awesome thanks Dotan! Really appreciate the help. I'll give this a shot.

**Comment by ardatan** [comment]
Closing this issue for now. Feel free to create a new one if this is still relevant.

**Comment by MiroslavPetrik** [comment]
I think this issue is not solved and should be reopened.

I had the same problem with the package `graphql-constraint-directive`

E.g. for minimal input for a hello world query:

```gql
type Query {
  hello(name: String! @constraint(minLength: 3)): String!
}
```
I get  the custom scalar in my schema:
```
type Query {
  hello(name: name_String_NotNull_minLength_3!): String!
}
```
This causes the generator fail for my FE query


```
query Hello($name: String!) {
  hello(name: $name)
}
```
due to the mismatch of scalar:

```
Error 0: GraphQLDocumentError: Variable "$name" of type "String!" used in position expecting type "nameOrIco_String_NotNull_minLength_3!".
```

So my current solution is to define the scalar explicitly in the config to map it to string.

```
overwrite: true
schema: ${API_URL}/graphql
documents: 'src/graphql/**/*.graphql'
generates:
  src/generated/graphqlClient.ts:
    noPluck: true
    config:
      strictScalars: true
      scalars:
        Date: number
        nameOrIco_String_NotNull_minLength_3: string // HERE
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
```

I should not need to do such manual step...
