### ISSUE TITLE
Cannot find name 'Exact'

### ISSUE THREAD

**Issue by joshbedo** [dotansimha/graphql-code-generator#5273]
**Describe the bug**
I'm running `npm run gql` to generate the code but I'm seeing this as an application error. Not really sure why it can't find 'Exact' or how to fix it.
```
TypeScript error in /Users/joshbedo/Desktop/projects/influencial-1.0/client/src/gql/generated/graphql.tsx(92,41):
Cannot find name 'Exact'.  TS2304

    90 | };
    91 |
  > 92 | export type RegisterMutationVariables = Exact<{
       |                                         ^
    93 |   email: Scalars['String'];
    94 |   password: Scalars['String'];
    95 |   confirmation: Scalars['String'];
```

codegen.yml

```
overwrite: true
schema: "http://localhost:4000/graphql"
documents: "src/gql/*.graphql"
generates:
  src/gql/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      withHOC: false
      withComponent: false
      withHooks: true
      reactApolloVersion: 3
```

package.json

```
{
  "name": "client",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@apollo/client": "^3.0.0-rc.4",
    "@apollo/link-error": "^2.0.0-beta.3",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "@types/jest": "^24.9.1",
    "@types/node": "^12.12.47",
    "@types/react": "^16.9.36",
    "@types/react-dom": "^16.9.8",
    "graphql": "^15.1.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1",
    "typescript": "^3.7.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "gql": "graphql-codegen --config codegen.yml"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@graphql-codegen/cli": "1.15.3",
    "@graphql-codegen/typescript": "1.15.3",
    "@graphql-codegen/typescript-operations": "^1.15.3",
    "@graphql-codegen/typescript-react-apollo": "^1.15.3",
    "@types/graphql": "^14.5.0",
    "@types/react-router-dom": "^5.1.5"
  }
}
```

**Comment by dotansimha** [comment]
Please update to latest versions of codegen cli and plugins and try again. Let me know if it needs to be reopened.

**Comment by tubbo** [comment]
I'm still having this issue.

**Error:**
```
Failed to compile.

./src/operations.ts:2:45
Type error: Cannot find name 'Exact'.

  1 | import gql from 'graphql-tag';
> 2 | export type ConnectVoiceMutationVariables = Exact<{ [key: string]: never; }>;
```

**codegen.yml**:
```yaml
overwrite: true
schema: "http://localhost:8080/graphql"
documents: "src/**/*.gql"
generates:
  src/models.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
      - "fragment-matcher"
  src/operations.ts:
    plugins:
      - "typescript-operations"
      - "typescript-document-nodes"
  ./graphql.schema.json:
    plugins:
      - "introspection"
```

**package.json:**
```json
{
    "devDependencies": {
        "@graphql-codegen/cli": "^1.19.4",
        "@graphql-codegen/fragment-matcher": "^2.0.1",
        "@graphql-codegen/introspection": "^1.18.1",
        "@graphql-codegen/typescript": "^1.19.0",
        "@graphql-codegen/typescript-document-nodes": "^1.17.9",
        "@graphql-codegen/typescript-graphql-files-modules": "^1.18.1",
        "@graphql-codegen/typescript-operations": "^1.17.12",
        "@graphql-codegen/typescript-react-apollo": "^2.2.1",
    }
}
```

I'm using this with NextJS. Doesn't seem to get in the way of `next dev`, but when I try `next build` that's when I get the compilation error.
