### ISSUE TITLE
Error when i try to auto generate graphql file

### ISSUE THREAD

**Issue by Israel001** [dotansimha/graphql-code-generator#5275]
**Describe the bug**
 

I have an issue with this library when i try to convert a working `json` configuration into `yml` in order to make use of environment variables.

Here is the contents of the working `json` configuration:

```json
{
  "overwrite": true,
  "generates": {
    "generated/graphql.tsx": {
      "schema": [
        {
          "https://abcd.myshopify.com/api/graphql": {
            "headers": {
              "X-Shopify-Storefront-Access-Token": "1234567890abcdefghijklmnopqr"
            }
          }
        }
      ],
      "documents": "graphql/**/*.graphql",
      "plugins": [
        "typescript",
        "typescript-operations",
        "typescript-react-apollo"
      ]
    }
  }
}
``` 
Since there is no way to make use of `env` variables in the json files, so i tried to convert the above config into `yml` format as shown below:
```yml
schema:
  - ${SHOP}/api/graphql:
      headers:
        X-Shopify-Storefront-Access-Token: ${X-Shopify-Storefront-Access-Token}
documents: ./graphql/**/*.graphql
generates:
  ./generated/graphql.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
```
When i run the `graphql-codegen` command with the `yml` config, i get an error saying: `invalid json response body at https:abcd.myshopify.com/api/graphql reason: Unexpected end of JSON input`. Please why does this happen and how can i fix it?

**To Reproduce**
1. Create a new project
2. Create a `codegen.yml` file with the contents provided aboce
3. Install the following packages: `@graphql-codegen/cli (v1.19.4)`, `@graphql-codegen/typescript (v1.19.0)`, `@graphql-codegen/typescript-operations (v1.17.12)`, `@graphql-codegen/typescript-react-apollo (v2.2.1)`, `dotenv (v8.2.0)`
4. Create a `.env` file with the needed variables in `codegen.yml`
5. Run the following command: `graphql-codegen -r dotenv/config`

I don't really understand what i am suppose to do with the sandbox stuff but i created one here: https://codesandbox.io/s/goofy-hill-06mz9?file=/codegen.yml
<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

I am using Shopify API so i have no schema

2. My GraphQL operations:

I don't think the issue has anything to do with my graphql operations but this is one of them.

```graphql
fragment product on Product {
  title
  description
  images(first: 1) {
    edges {
      node {
        altText
        transformedSrc
      }
    }
  }
  options {
    id
    name
    values
  }
  variants(first: 250) {
    edges {
      node {
        id
        title
        selectedOptions {
          name
          value
        }
      }
    }
  }
}

query product($handle: String!) {
  productByHandle(handle: $handle) {
    ...product
  }
}
```

3. My `codegen.yml` config file:

```yml
schema:
  - ${SHOP}/api/graphql:
      headers:
        X-Shopify-Storefront-Access-Token: ${X-Shopify-Storefront-Access-Token}
documents: ./graphql/**/*.graphql
generates:
  ./generated/graphql.tsx:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
I expected the library to successfully generate a graphql file with the provided `yml` configuration.

**Environment:**

- OS: Ubuntu 
- `@graphql-codegen/cli`: ^1.19.4
- `@graphql-codegen/typescript`: ^1.19.0
- `@graphql-codegen/typescript-operations`: ^1.17.12
- `@graphql-codegen/typescript-react-apollo`: ^2.2.1 
- NodeJS: 12.x

**Additional context**
<!-- Add any other context about the problem here. -->

There is no additional context.
