### ISSUE TITLE
GraphQL Modules preset fails when there are multiple schema entries in config

### ISSUE THREAD

**Issue by tvvignesh** [dotansimha/graphql-code-generator#5289]
**Describe the bug**
I use `graphql-modules` preset with codegen and it works well. It fails when my `.graphqlrc.yml` file has multiple entries for schema. That is,

**This works:**

```yml
config:
      assumeValidSDL: true
      assumeValid: true
    schema:
      # - './packages/core/gql/directive.gql'
      # - './packages/core/gql/core.gql'
      - './packages/modules/**/schema/*.gql'
    extensions:
      codegen:
        generates:
          ./packages/modules/:
            schema: ./packages/modules/*/schema/*.gql
            preset: graphql-modules
 ```

**This doesn't:**

```yml
config:
      assumeValidSDL: true
      assumeValid: true
    schema:
      - './packages/core/gql/directive.gql'
      - './packages/core/gql/core.gql'
      - './packages/modules/**/schema/*.gql'
     extensions:
      codegen:
        generates:
          ./packages/modules/:
            schema: ./packages/modules/*/schema/*.gql
            preset: graphql-modules
```

I get this error when running codegen:

<img width="773" alt="1" src="https://user-images.githubusercontent.com/1165845/102632483-302a7500-4175-11eb-96f3-ad2f1d38f82b.PNG">

The files do exist in the right locations and are valid.

I am not sure if this is an error or is expected. Have separated service and module codegen into 2 separate projects to get this working now. In the above case, there are some GQL files which does not make sense within modules, so I have it outside the modules and was doing codegen for both in the same project causing the error.

**Deps:**

```
"@graphql-codegen/add": "^2.0.2",
"@graphql-codegen/cli": "^1.19.4",
"@graphql-codegen/graphql-modules-preset": "^1.1.0",
"@graphql-codegen/typescript": "^1.19.0",
"@graphql-codegen/typescript-operations": "^1.17.12",
"@graphql-codegen/typescript-resolvers": "^1.18.0",
```

**CC:** @dotansimha
