### ISSUE TITLE
generate near-operation-file with single operations file

### ISSUE THREAD

**Issue by correttojs** [dotansimha/graphql-code-generator#5332]
hi,

I would like to generate the types and operations globally (one single file), and the typed-document as near-operation-file. 
This configuration would be similar to this one, and the typed-document should import the operations from the `types.tsx` file. 

```

    src/@types/codegen/types.tsx:
        plugins:
            - 'typescript'
            - 'typescript-operations'
    src/:
        preset: near-operation-file
        presetConfig:
            extension: .generated.ts
            baseTypesPath: '@types/codegen/types'
        plugins:
            # - 'typescript'
            # - 'typescript-operations'
            - 'typed-document-node'
        config:
            exportFragmentSpreadSubTypes: true
            documentMode: graphQLTag

```

The reason is many operations are duplicated with the near-operation-file strategy, but I'd still like to split the generated documents

**Comment by correttojs** [comment]
I see 

```
   src/@types/codegen/types.tsx:
        plugins:
            - 'typescript'
            - 'typescript-operations'
    src/:
        preset: near-operation-file
        presetConfig:
            extension: .generated.ts
            baseTypesPath: '@types/codegen/types'
        plugins:
            # - 'typescript'
            - 'typescript-operations'
            - 'typed-document-node'
        config:
            exportFragmentSpreadSubTypes: true
            documentMode: graphQLTag
```

would already provide the solution I'm looking for
