### ISSUE TITLE
Use typescript-graphql-request and typescript-react-apollo in parallel

### ISSUE THREAD

**Issue by Schwefelhexa** [dotansimha/graphql-code-generator#5343]
**Describe the bug**
`typescript-graphql-request` and `typescript-react-apollo` both generate query documents, resulting in an `Identifier has already been declared` error from TypeScript.

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

See [this repro](https://codesandbox.io/s/amazing-keller-cy45k?file=/types.ts:2294-2306).
`UserDocument` gets declared twice in `types.ts`, once on line 46 and once on line 81, throwing an error.

My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
      - typescript-graphql-request
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
The should be an option to stop one of the plugins from declaring documents.

**Environment:**

- OS: Windows 10
- `@graphql-codegen/...`: Same as [repro](https://codesandbox.io/s/amazing-keller-cy45k?file=/types.ts:2294-2306).
- NodeJS: v14.15.0
