### ISSUE TITLE
Wrong variables type generated for array fields

### ISSUE THREAD

**Issue by forehalo** [dotansimha/graphql-code-generator#5352]
**Describe the bug**
 
Wrong type generated

**To Reproduce**
https://codesandbox.io/s/misty-forest-h519g?file=/types.ts

1. My GraphQL schema:

```graphql
type Query {
    search(queries: [String!]!): [User!]!
}

type User {
    id: ID!
    username: String!
    email: String!
}

```

2. My GraphQL operations:

```graphql
query search($queries: [String!]!) {
    search(queries: $queries) {
        id
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations

```

outputs:
```ts
export type SearchQueryVariables = Exact<{
  queries: Array<Scalars['String']> | Scalars['String'];
}>;
```

**Expected behavior**

the `queries` field for `SearchQueryVariables` should be `Array<Scalars['String']>` instead of `Array<Scalars['String']> | Scalars['String']`

**Environment:**

- OS: 
- `@graphql-codegen/typescript`: 1.20.0 
- - `@graphql-codegen/typescript-operations`: 1.17.13
- - `@graphql-codegen/cli`: 1.20.0 
- NodeJS: v10.23.0

**Additional context**
