### ISSUE TITLE
Duplicate identifier NumericComparisonEx

### ISSUE THREAD

**Issue by ShawnToubeau** [dotansimha/graphql-code-generator#5357]
**Describe the bug**
 
Hello, my team has been running into an issue where any of our tracked SQL functions that return an array of numerics causes codegen to generate duplication comparison expressions (see image below). I haven't been able to find anything else online so guidance would be very appreciate! Ty

**To Reproduce**

1. Create and track an sql function that returns an array of numerics.
2. Run codegen and you should get a similar error.

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
n/a
```

2. My GraphQL operations:

```graphql
n/a
```

3. My `codegen.yml` config file:

```yml
schema:
    - ${DEV_GRAPHQL_URL}:
        headers:
            X-HASURA-ACCESS-KEY: ${HASURA_SECRET}
config:
    reactApolloVersion: 3
    transformUnderscore: true
    namingConvention:
        typeNames: change-case#pascalCase
        enumValues: change-case#upperCase
    dedupeOperationSuffix: true
    withComponent: false
    withResultType: true
    withHooks: true
    withHOC: false
documents:
    - ./src/**/*.graphql
    - ./src/**/*.gql
    - '!./src/lib/gqlTypes.tsx'
generates:
    ./src/lib/gqlTypes.ts:
         - typescript
    ./src/:
        preset: near-operation-file
        presetConfig:
            extension: .generated.tsx
            baseTypesPath: ./lib/gqlTypes.ts
        plugins:
            - typescript-operations
            - typescript-react-apollo
overwrite: true
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

Codegen should only generate one comparison expression.

**Environment:**

- OS: MacOS Catalina 10.15.7  
- "@graphql-codegen/cli": "1.19.4",
    "@graphql-codegen/near-operation-file-preset": "1.17.13",
    "@graphql-codegen/time": "2.0.2",
    "@graphql-codegen/typescript": "1.19.0",
    "@graphql-codegen/typescript-operations": "1.17.12",
    "@graphql-codegen/typescript-react-apollo": "2.2.1",
- NodeJS: 12.18.0

**Additional context**
<!-- Add any other context about the problem here. -->
Error with the duplicate expressions.
![image](https://user-images.githubusercontent.com/22332636/103589071-97a42c80-4eb8-11eb-8609-a4f6d524bf86.png)
