### ISSUE TITLE
Are custom plugins still supported?

### ISSUE THREAD

**Issue by PLJNS** [dotansimha/graphql-code-generator#5366]
**Describe the bug**

These directions do not appear to work anymore: https://graphql-code-generator.com/docs/custom-codegen/write-your-plugin

**To Reproduce**

Create my-plugin.js:

```
module.exports = {
  plugin: (schema, documents, config) => {
    return "Hi!";
  },
};
```

Create config:

```
schema: "./graphql/schema.gql"
documents:
  - "./graphql/documents/**/*.gql"
  - "./graphql/custom/**/*.gql"
overwrite: true
generates:
  ./graphql/output.ts:
    plugins:
      - my-plugin.js
  ```

Run:

```
graphql-codegen --config codegen.yml
```

**Expected behavior**

I expect a file called output.ts with Hi!

I see:

```
    Unable to find template plugin matching 'my-plugin.js'
    Install one of the following packages:


    - @graphql-codegen/my-plugin.js
    - @graphql-codegen/my-plugin.js-template
    - @graphql-codegen/my-plugin.js-plugin
    - graphql-codegen-my-plugin.js
    - graphql-codegen-my-plugin.js-template
    - graphql-codegen-my-plugin.js-plugin
    - codegen-my-plugin.js
    - codegen-my-plugin.js-template
    - my-plugin.js
    Error: Unable to find template plugin matching my-plugin.js
        at getPluginByName (/home/pljns/Desktop/bakedeck-frontend/node_modules/@graphql-codegen/cli/bin.js:328:11)
    Error: Unable to find template plugin matching my-plugin.js
        at getPluginByName (/home/pljns/Desktop/bakedeck-frontend/node_modules/@graphql-codegen/cli/bin.js:328:11)
  ```

**Environment:**

- OS: Ubuntu
- `@graphql-codegen/...`: 1.19.4
- NodeJS: v12.18.3

**Additional context**
