### ISSUE TITLE
[typescript-graphql-request] Missing Headers type import

### ISSUE THREAD

**Issue by joshuaavalon** [dotansimha/graphql-code-generator#5370]
**Describe the bug**
 

**To Reproduce**

1. My GraphQL schema:

```graphql
type Foo {
  id: ID!
}

type Query {
  foo: Foo!
}
```

2. My GraphQL operations:

```graphql
query test {
  foo {
    id
  }
}
```

3. My `codegen.yml` config file:

```yml
schema: ./schema.gql
documents: ./src/**/*.gql
overwrite: true
generates:
  ./src/index.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
    config:
      rawRequest: false
      skipTypename: true
      namingConvention:
        transformUnderscore: true

```

**Expected behavior**
Generate TypeScript code without any errors.

**Environment:**

- OS: Windows 10
- `@graphql-codegen/...`: 
```json
{
    "@graphql-codegen/cli": "^1.20.0",
    "@graphql-codegen/introspection": "^1.18.1",
    "@graphql-codegen/typescript": "^1.20.0",
    "@graphql-codegen/typescript-operations": "^1.17.13",
    "@graphql-codegen/typescript-graphql-request": "^3.0.0",
    "graphql": "^15.4.0"
}
```
- NodeJS: 14

**Additional context**

I think it is related to #4793 because it import `Headers` when `rawRequest: true` but not by default or `rawRequest: false`.
