### ISSUE TITLE
How namingConventions works (fix bug or update documentation needed)

### ISSUE THREAD

**Issue by vladop** [dotansimha/graphql-code-generator#5372]
**Describe the bug**
How to make c# properties start with uppercase as per convention

**To Reproduce**
Easiest way is to go to homepage and just past this yml configuration like in this forked sandbox

overwrite: true
schema: schema.graphql
generates:
  MyTypes.cs:
    plugins:
      - c-sharp
    config:
      namespaceName: MyCompany.MyNamespace
      namingConvention: pascal-case#pascalCase

https://codesandbox.io/s/infallible-tdd-f35jg?file=/codegen.yml

1. My GraphQL schema:

```graphql
# Put your schema here
```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: schema.graphql
generates:
  MyTypes.cs:
    plugins:
      - c-sharp
    config:
      namespaceName: MyCompany.MyNamespace
      namingConvention: pascal-case#pascalCase
```

**Expected behavior**
I would like to not to get errors when passed namingConvention parametar using c-sharp plugin.
I want to get properties start with upper case letter. I lost 2 hours on such a simple thing !!

**Environment:**

- OS: Windows 10
- `@graphql-codegen/...`: 
- NodeJS:  14.15.4

**Comment by kraegpoeth** [comment]
I strugled with this as well! So +1 for updating the docs!

Got it to work with this:
 ```
   config:
      declarationKind: 'interface'
      typesPrefix: I
      namingConvention:
        enumValues: upper-case#upperCase
```

and you can use at least the following: 
`pascal-case#PascalCase`, `lower-case#lowerCase`, `upper-case#upperCase`

Hope it helps! :)
