### ISSUE TITLE
CSharp plugin argument classes not created

### ISSUE THREAD

**Issue by vladop** [dotansimha/graphql-code-generator#5380]
**Describe the bug**
There are not created argument classes when using c sharp plugin

**To Reproduce**
Extremely simple. Just compare homepage of this project (default is typescript in yml file ) to this for example

overwrite: true
schema: schema.graphql
generates:
  RimacCmvdsClient.Models/Models.cs:
    plugins:
      - c-sharp
    config:
        namespaceName: e
        scalars:
            DateTime: DateTime
 
QuerySearchArgs is missing !

Sandbox has timeouts but reproducing this is trivial. Just on home page of this site use c-sharp plugin

1. My GraphQL schema:

```graphql
scalar Date

schema {
  query: Query
}

type Query {
  me: User!
  user(id: ID!): User
  allUsers: [User]
  search(term: String!): [SearchResult!]!
  myChats: [Chat!]!
}

enum Role {
  USER,
  ADMIN,
}

interface Node {
  id: ID!
}

union SearchResult = User | Chat | ChatMessage

type User implements Node {
  id: ID!
  username: String!
  email: String!
  role: Role!
}

type Chat implements Node {
  id: ID!
  users: [User!]!
  messages: [ChatMessage!]!
}

type ChatMessage implements Node {
  id: ID!
  content: String!
  time: Date!
  user: User!
}

```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: schema.graphql
generates:
  RimacCmvdsClient.Models/Models.cs:
    plugins:
      - c-sharp
    config:
        namespaceName: e
        scalars:
            DateTime: DateTime
```

**Expected behavior**
Created argument classes for arguments like in typescript plugin (classes with Args sufix)

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS:  14.15.4

**Additional context**
