### ISSUE TITLE
Plugin graphql-request fails on unnamed query without a good explanation

### ISSUE THREAD

**Issue by adarnon** [dotansimha/graphql-code-generator#5386]
**Describe the bug**
Create a `.graphql` query file, with a single unnamed query.
Enable `graphql-request` codegen plugin.
Run `yarn generate`.

The error message is:
```
$ graphql-codegen --config ./codegen.yml
  ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate types.ts
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Cannot read property 'value' of undefined


 Found 1 error

  ✖ types.ts
    TypeError: Cannot read property 'value' of undefined
        at allPossibleActions._operationsToInclude.map.o (/sandbox/node_modules/@graphql-codegen
/typescript-graphql-request/index.cjs.js:61:39)
        at Array.map (<anonymous>)
        at GraphQLRequestVisitor.get sdkContent [as sdkContent] (/sandbox/node_modules/@graphql-
codegen/typescript-graphql-request/index.cjs.js:49:14)
        at Object.plugin (/sandbox/node_modules/@graphql-codegen/typescript-graphql-request/inde
x.cjs.js:97:21)
        at executePlugin (/sandbox/node_modules/@graphql-codegen/core/index.cjs.js:36:35)
    TypeError: Cannot read property 'value' of undefined
        at allPossibleActions._operationsToInclude.map.o (/sandbox/node_modules/@graphql-codegen
/typescript-graphql-request/index.cjs.js:61:39)
        at Array.map (<anonymous>)
        at GraphQLRequestVisitor.get sdkContent [as sdkContent] (/sandbox/node_modules/@graphql-
codegen/typescript-graphql-request/index.cjs.js:49:14)
        at Object.plugin (/sandbox/node_modules/@graphql-codegen/typescript-graphql-request/inde
x.cjs.js:97:21)
        at executePlugin (/sandbox/node_modules/@graphql-codegen/core/index.cjs.js:36:35)


Something went wrong
error Command failed with exit code 1.
```

It makes sense why an unnamed query isn't supported, but I'd expect a more detailed explanation.

**To Reproduce**

See this sandbox link: https://codesandbox.io/s/empty-hooks-1rcs5

**Expected behavior**

The plugin should print a non-generic "undefined" error message, but say something along the lines "unnamed queries are unsupported"

**Comment by canpoyrazoglu** [comment]
I'm just trying to integrate graphql-code-generator into my existing project and I'm having the same. Here is my config:

```
overwrite: true
schema: "http://myapp.com:4301/graphql"
documents: "meta/graphql/**/*.graphql"
generates:
  src/services/myapp/graph/types.d.ts:
    plugins:
      - "typescript"
  src/services/myapp/graph/graphql.ts:
    plugins:
      - "typescript-document-nodes"
      - "typescript-operations"
      - "fragment-matcher"
      - "typescript-graphql-request"
  meta/graphql/schema.json:
    plugins:
      - "introspection"
```

I've also tried putting all (types and operations etc) into the same file instead of two, but nothing changed, result is the same.
