### ISSUE TITLE
Automatically exclude schema from documents

### ISSUE THREAD

**Issue by mxstbr** [dotansimha/graphql-code-generator#5409]
**Describe the bug**

My codegen configuration looks like this:

```yml
schema: ./src/graphql/schema/schema.graphql
documents: "**/*.graphql"
```

Running graphql-codegen causes the following error:

```
      Unable to find any GraphQL type definitions for the following pointers:
        
          - src/graphql/schema/schema.graphql
```

After quite a bit of playing around I realised why this is happening: graphql-codegen is trying to read either a query or mutation from `src/graphql/schema/schema.graphql`! 🤦 

I have fixed this by changing my config to the following:

```yml
schema: ./src/graphql/schema/schema.graphql
documents:
  - "**/*.graphql"
  - "!src/graphql/schema/schema.graphql"
```

However, it seems really backwards that graphql-codegen would even _attempt_ to parse the `schema`. It knows it's a schema! Let's just not parse it?!

**Expected behavior**

Don't fail if the `documents` glob includes the `schema` file.
