### ISSUE TITLE
[Template Request] Template for typescript + graphql-shield

### ISSUE THREAD

**Issue by alexk111** [dotansimha/graphql-code-generator#541]
Graphql-shield is a permission layer for graphql servers: https://github.com/maticzav/graphql-shield 

It's configured by defining a schema middleware:

*permissions/index.ts*:
```ts
import { shield } from 'graphql-shield';
import * as rules from './rules';

const schemaPermissions = {
  Query: {
    me: rules.isAuthenticated,
  },
  Mutation: {
    editProfile: rules.isAuthenticated,
  }
};

export const permissions = shield(schemaPermissions);
```

*permissions/rules.ts*:
```ts
import { rule } from 'graphql-shield';
import { GQLContext } from '@core/gql/context';

export const isAuthenticated = rule()(async (parent, args, ctx: GQLContext, info) => {
  return !!ctx.me;
});
```

As seen on the example, generated type definitions for ```schemaPermissions``` would mostly be a copy of Resolvers' type definitions. The only difference is that instead of ```me?: MeResolver<UserAccount | null, any, Context>;```, it should have something like ```me?: Rule```.

**Comment by dotansimha** [comment]
Hi @alexk111, thanks for reporting it.
It's a very specific use case, any chance you want to create a template for it? or modify the existing template and create a PR?

**Comment by dotansimha** [comment]
Hi @alexk111 
We got a new `resolvers` template now, that let's you override the `parent` and `context` types. I think it might be useful for this use-case :) 
Please re-open if you think we should support `graphql-shield` in a different way.

**Comment by Sytten** [comment]
I was able to make it work 90% of the time with the following config:
```yaml
generates:
  src/generated/shared.ts:
    plugins:
      - 'typescript'
    config:
      enumsAsConst: true
      useTypeImports: true
  src/generated/permissions.ts:
    preset: import-types
    presetConfig:
      typesPath: ./shared
    plugins:
      - add:
          content: "import type { ShieldRule } from 'graphql-shield/dist/types';"
      - add:
          content: "import type * as Types from './shared';"
      - 'typescript-resolvers'
    config:
      useTypeImports: true
      customResolverFn: 'ShieldRule'
      resolverTypeSuffix: Permissions
      allResolversTypeName: Permissions
      allowParentTypeOverride: true
      makeResolverTypeCallable: true
      wrapFieldDefinitions: false
      skipTypename: true
  src/generated/resolvers.ts:
    preset: import-types
    presetConfig:
      typesPath: ./shared
    plugins:
      - add:
          content: "import type * as Types from './shared';"
      - 'typescript-resolvers'
    config:
      useTypeImports: true
      contextType: '~/context#Context'
      mapperTypeSuffix: Model
      mappers:
        MyType: '~/mytypes#MyType'
```

The only thing that doesn't work is the `'*'` since I was not able to inject it in the fields of the `Resolvers` objects.
