### ISSUE TITLE
Add ability to extend mapper types

### ISSUE THREAD

**Issue by alexandernanberg** [dotansimha/graphql-code-generator#5437]
**Is your feature request related to a problem? Please describe.**

Overwriting the entire type isn't always a good solution. If you use relay connections you end up writing a lot of custom types which defeats the purpose of this package. 

The core problem I have is that I want to make all fields except `id` optional, since the others will be resolved in the `User` resolver

E.g. if my schema looks like this

```graphql
type Query {
  user(id: ID!): User!
}

type User {
  id: ID!
  name: String!
}

```

and 

```js
const resolvers = {
  Query: {
    user(parent, args) {
      const id = db.findUserId(args.id)
      // returning just ID should be OK here
      return { id }
    }
  },
  User: {
    name(parent) {
      return db.findUserName(parent.id)
    }
  }
}
```

Even better would be to just change the type for the QueryResolver, since name shouldn't be optional in the `User` resolver

**Describe the solution you'd like**

I think it would be very neat if you could extend the mapper type, similar to the `defaultMapper` option.

So for my use-case I could do

```yml
config:
  mappers:
    User: <Pick{T}, 'id'> & Partial<{T}>
```

**Describe alternatives you've considered**

Not sure, is there are any good alternatives?

**Additional context**

N/A

**Comment by dotansimha** [comment]
I'm not sure that there is anything that prevents you from doing exactly what you said, just with a more custom way, with `add` plugin: 

```yaml
plugins:
  - add: 
  	  content: "import { User } from './my-types';"
  - typescript
  - typescript-resolvers
config:
  mappers:
    User: "Partial<Omit<User, 'id'>>"
```

You can also use `resolverTypeWrapperSignature` feature to wrap all resolvers types and mappers with specific signature:

```yaml
config:
  resolverTypeWrapperSignature: "T | Promise<T> | Partial<T> | Promise<Partial<T>>"
  mappers:
	User: User#my-file
```
