### ISSUE TITLE
typescript-react-query failing to parse process.env

### ISSUE THREAD

**Issue by jonathanstanley** [dotansimha/graphql-code-generator#5449]
**Description**
`@graphql-codegen/typescript-react-query` [documentation](https://graphql-code-generator.com/docs/plugins/typescript-react-query) indicates `process.env` or other variables may be used within the `codegen.yml`

this works for the fetcher `endpoint`, but fails with `fetchParams`

**To Reproduce**
[See codesandbox](https://codesandbox.io/s/graphql-codegen-react-query-env-be8w1?file=/types.ts:171-477) for reproduced behavior

**Expected behavior**
should produce:
```ts
const res = await fetch(process.env.ENDPOINT as string, {
      ...
      headers: {apikey:process.env.APIKEY},
      ...
    });
```

instead produces (note the "" in the headers JSON)
```ts
const res = await fetch(process.env.ENDPOINT as string, {
      ...
      headers: {"apikey":"process.env.APIKEY"},
      ...
    });
```

**Additional context**
The failure is caused by  `JSON.stringify(...)` which produces JSON rather than javascript object literal notation.  [See the source code here](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/react-query/src/fetcher-fetch-hardcoded.ts#L28).

It is important that generated/committed code should not include API keys / sensitive information for security.  

**Posible solutions**

1. clarify documentation that `process.env` may only be used for the endpoint. 
2. modify `getFetchParams` to allow variables, such as by returning a string representation of Javascript Object Literal Notation (ie drop the double-quotes where appropriate). 

The first would be fast, but not great for security. I haven't thought of a great way to do the latter.

[My original post in discussion](https://github.com/dotansimha/graphql-code-generator/discussions/5443#discussion-1978089)

**Comment by dankremniov** [comment]
The issue extends to the use of custom variables from user code as well.

[The documentation](https://graphql-code-generator.com/docs/plugins/typescript-react-query#using-fetch-with-codegen-configuration) says you can use the following config:
```
schema: MY_SCHEMA_PATH
documents: './src/**/*.graphql'
generates:
  ./generates.ts:
    plugins:
      - add:
          content: "import { endpointUrl, fetchParams } from './my-config';"
      - typescript
      - typescript-operations
      - typescript-react-query
    config:
      fetcher:
        endpoint: 'endpointUrl'
        fetchParams: 'fetchParams'
```

However, the results is:
```
function fetcher<TData, TVariables>(query: string, variables?: TVariables) {
  return async (): Promise<TData> => {
    const res = await fetch(endpointUrl as string, {
      0: 'f',
      1: 'e',
      2: 't',
      3: 'c',
      4: 'h',
      5: 'P',
      6: 'a',
      7: 'r',
      8: 'a',
      9: 'm',
      10: 's',
      method: 'POST',
      body: JSON.stringify({ query, variables }),
    });

    const json = await res.json();

    if (json.errors) {
      const { message } = json.errors[0];

      throw new Error(message);
    }

    return json.data;
  };
}
```

**Comment by paolotiu** [comment]
Attempted in #6408

**Comment by n1ru4l** [comment]
I think we should solve this issue by actually fixing the type of the config options provided.

e.g. `fetchParams` is of type `Record<string, any>`, but I think it should instead be of type `string`.

That would allow providing the following configuration:

```yaml
schema: MY_SCHEMA_PATH
documents: "./src/**/*.graphql"
generates:
  ./generates.ts:
    plugins:
      - add:
          content: "import { endpointUrl, fetchParams } from './my-config';"
      - typescript
      - typescript-operations
      - typescript-react-query
    config:
      fetcher:
        endpoint: "endpointUrl"
        fetchParams: "fetchParams"
```

And would also allow usage of environment variables easily:

```yaml
schema: MY_SCHEMA_PATH
documents: './src/**/*.graphql'
generates:
  ./generates.ts:
    plugins:
      - add:
          content: "import { endpointUrl, fetchParams } from './my-config';"
      - typescript
      - typescript-operations
      - typescript-react-query
    config:
      fetcher:
        endpoint: 'endpointUrl'
        # Multiline string
        fetchParams: >
          {
            headers: {
              apiKey: process.env.APIKEY,
              somethingElse: process.env.SOMETHING,
            },
        }
```

This would be a breaking change but address all the issues, without having to do hacks similar to https://github.com/dotansimha/graphql-code-generator/pull/6408/files
