### ISSUE TITLE
Query with @skip directive not including correct type inside of Maybe<>

### ISSUE THREAD

**Issue by dmarkow** [dotansimha/graphql-code-generator#5453]
**Describe the bug**
After updating typescript-operations to 1.17.4, when using skip on a query, the return type is incorrect. This worked correctly in typescript-operations 1.17.3.

```gql
query Reports($skip: Boolean!) {
  reports @skip(if: $skip) {
    id
  }
}
```

As of today's updates, it's generating this. Note that `reports` is not showing that it is an array, but is now correctly showing as optional due to the `@skip` directive.

```ts
export type ReportsQuery = (
  { __typename: 'RootQueryType' }
  & { reports?: Types.Maybe<(
    { __typename: 'Report' }
    & Pick<Types.Report, 'id'>
  )> }
);
```

Before today's updates, it generated this (correct array type, but not showing that it's optional due to the `@skip` directive):

```ts
export type ReportsQuery = (
  { __typename: 'RootQueryType' }
  & { reports: Array<(
    { __typename: 'Report' }
    & Pick<Types.Report, 'id'>
  )> }
);
```

So I think the correct result is a cross of the two: `Types.Maybe<Array<({__typename: "Report"} & Pick<Types.Report, 'id'>)>>` ?

Working dependencies:

```js
"@graphql-codegen/add": "2.0.2",
"@graphql-codegen/cli": "1.20.0",
"@graphql-codegen/introspection": "1.18.1",
"@graphql-codegen/near-operation-file-preset": "1.17.13",
"@graphql-codegen/typescript-operations": "1.17.13",
```

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type Report {
  id: ID!
}
```

2. My GraphQL operations:

```graphql
type Query {
  reports: [Report!]!
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema:
  - http://localhost:4000/graphql:
      headers:
        Authorization: "Bearer ...."
documents: "src/queries/**/*.gql"
generates:
  src/types/generated.d.ts:
    plugins:
      - add:
          content: "/* eslint-disable */\n"
      - "typescript"
  src/:
    preset: near-operation-file
    presetConfig:
      extension: ".d.ts"
      baseTypesPath: types/generated.d.ts
    plugins:
      - add:
          content: "/* eslint-disable */\n"
      - "typescript-operations"
config:
  nonOptionalTypename: true
  scalars:
    Decimal: string
    MyDecimal: string
    IntegerInput: number | string
    FloatInput: number | string
    ErlDate: string
    Date: string
    DateTime: string
```

**Expected behavior**
`Types.Maybe<Array<({__typename: "Report"} & Pick<Types.Report, 'id'>)>>` as the returned type.

**Environment:**

- OS: macOS 11.1
- "@graphql-codegen/add": "2.0.2",
- "@graphql-codegen/cli": "1.20.1",
- "@graphql-codegen/introspection": "1.18.1",
- "@graphql-codegen/near-operation-file-preset": "^1.17.13",
- "@graphql-codegen/typescript-operations": "1.17.14",
- NodeJS: 14.15.4
