### ISSUE TITLE
str.replace is not a function

### ISSUE THREAD

**Issue by mlenser** [dotansimha/graphql-code-generator#5466]
**Describe the bug**
We are receiving an error when generating our types from graphql (via gatsby) that `str.replace is not a function`

This is caused by the code change https://github.com/dotansimha/graphql-code-generator/commit/4444348d2b5c0e7ece9228f7bc7d14a4846811d6#diff-8844b3ecdf140eb2ba14e334b38d77fdc379b3c1dc3b3046a3e0dd5ce1668ac0R7

![Screenshot 2021-01-29 at 11 27 33](https://user-images.githubusercontent.com/235857/106264395-e29a3100-6225-11eb-9bce-09f4c827e1e9.png)

**To Reproduce**

Creating a reproducable case will be quite difficult. Maybe the issue can be debugged based on the link to the code change?

If not, I can spend some time to try to create a reproducable case.

1. My GraphQL schema:

Schema ia quite large

2. My GraphQL operations:

Many opertaions

3. My `codegen.yml` config file:

```yml
overwrite: true
schema:
  - '${SCHEMA_HOST:https://SITE}/api/graphql'
  - 'src/utils/resolvers.ts'
documents:
  - 'src/**/*.{js,ts,tsx}'
generates:
  src/__generated__/graphql.introspection.json:
    plugins:
      - 'fragment-matcher'
  src/__generated__/graphql.schema.json:
    plugins:
      - 'introspection'
    hooks:
      afterOneFileWrite:
        - sort-json
  src/__generated__/graphql.apollo.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
hooks:
  afterAllFileWrite:
    - prettier --write
```

**Expected behavior**

Generating types does not error

**Environment:**

- OS: Happens on windows, mac, and linux
- `@graphql-codegen/...`: 
  - @graphql-codegen/cli@1.20.1
  - @graphql-codegen/fragment-matcher@2.0.1
  - @graphql-codegen/introspection@1.18.1
  - @graphql-codegen/typescript-react-apollo@2.2.1
- NodeJS: v14.8.0

**Comment by mlenser** [comment]
I am also experiencing this `str.replace is not a function` on another project which is much smaller in scope when using `gatsby-plugin-typegen@2.2.4`.

**Comment by Israel-Or** [comment]
@ardatan 
Happened to me also when generating code via mongoose plugin:
Steps to reproduce it:
.meshrc.yaml:
```
require: [ts-node/register]

sources:
  - name: melio
    handler:
      mysql:
        host: localhost
        port: 3306
        user: user
        password: pass
        database: myDb
  - name: mongoose
    handler:
      mongoose:
        connectionString: mongodb://localhost:27017/myDb
        models:
          - name: Task
            path: ./src/models/task.model.ts#Task

```
Task.model.ts
```
import { Document, model, Schema, Types } from 'mongoose';
import TaskStatusEnum from '../enums/taskStatus.enum';
import { TimelineType } from '../enums/timeLineType.enum';

interface Timeline {
  type: TimelineType[];
  userId: Types.ObjectId;
  data: Date;
}

interface ITask {
  ruleId: Types.ObjectId;
  entityId: string;
  payload?: unknown;
  status: TaskStatusEnum;
  relatedRules?: Types.ObjectId[];
  timeline?: Timeline[];
}

interface ITaskDoc extends ITask, Document {}

interface ITaskModel extends ITask {
  _id?: Types.ObjectId;
}

const TaskSchema: Schema = new Schema(
  {
    entityId: {
      type: String,
      required: true
    },
    payload: {
      type: Object,
      required: false
    },
    status: {
      type: TaskStatusEnum,
      required: true
    },
    relatedRules: {
      type: [Types.ObjectId],
      required: false
    },
    timeline: {
      type: [Object],
      required: false
    },
    ruleId: {
      type: Types.ObjectId,
      required: true
    }
  },
  { timestamps: true }
);
const Task = model<ITaskDoc>('Task', TaskSchema);
export { ITaskModel, Timeline, Task };

```
and then:
`graphql-mesh serve`

The error is:
TypeError: str.replace is not a function
    at escapeString (/Users/myName/sherlock-viewer-server/dist/plugins/other/visitor-plugin-common/src/enum-values.js:5:16)
    at parseEnumValues (/Users/myName/sherlock-viewer-server/dist/plugins/other/visitor-plugin-common/src/enum-values.js:18:68)
    at new BaseTypesVisitor (/Users/myName/sherlock-viewer-server/dist/plugins/other/visitor-plugin-common/src/base-types-visitor.js:15:25)
    at new TsVisitor (/Users/myName/sherlock-viewer-server/dist/plugins/typescript/typescript/src/visitor.js:10:9)
    at Object.plugin (/Users/myName/sherlock-viewer-server/dist/plugins/typescript/typescript/src/index.js:9:21)
    at executePlugin (/Users/myName/sherlock-viewer-server/dist/graphql-codegen-core/src/execute-plugin.js:31:35)
    at Promise.all.options.plugins.map (/Users/myName/sherlock-viewer-server/dist/graphql-codegen-core/src/codegen.js:77:30)
    at Array.map (<anonymous>)
    at Object.codegen (/Users/myName/sherlock-viewer-server/dist/graphql-codegen-core/src/codegen.js:67:54)
    at generateTsTypes (/Users/myName/sherlock-viewer-server/node_modules/@graphql-mesh/cli/bin.js:131:17)
    at Object.yargs.help.option.option.command.command.command.command [as handler] (/Users/myName/sherlock-viewer-server/node_modules/@graphql-mesh/cli/bin.js:677:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
