### ISSUE TITLE
bug: default values should not create `Maybe` types

### ISSUE THREAD

**Issue by dnalborczyk** [dotansimha/graphql-code-generator#5476]
**Describe the bug**

default input values should not create `Maybe` types, as they can't be nullable.

plugins used:
`typescript`
`typescript-resolvers`

have not tried this with `typescript-operations` yet.

**To Reproduce**

```graphql
input FooInput {
  bar: String = "foo"
}

extend type Query {
  foo(bar: String = "foo"): Boolean
}
```

generates ambient types;

```ts
export type FooInput = {
  bar?: Maybe<Scalars['String']>;
};

export type QueryFooArgs = {
  bar?: Maybe<Scalars['String']>;
};
```

expected:

```typescript
export type FooInput = {
  value: Scalars['String'];
};

export type QueryFooArgs = {
  bar: Scalars['String'];
};
```

```yml
generates:
  dist/typings.d.ts:
    config:
      contextType: Context
      enumsAsTypes: true
      noSchemaStitching: true
      # immutableTypes: true # TODO
      useIndexSignature: true
      useTypeImports: true
    hooks:
      afterOneFileWrite:
        - prettier --write
    plugins:
      - typescript
      - typescript-resolvers
overwrite: true
schema:
  - ./schema/**/*.graphql
```

**Expected behavior**

**Environment:**

- OS: macOS 11
- NodeJS: **v15.7.0**

similar behavior:

https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcAUBDA-IgvIgchTgIEpEBvAKEUQCcBTKEOpDKgXyA

```typescript
function foo(a? = 'foo') {
  return a
}

// exception: Parameter cannot have question mark and initializer.(1015)
```

on that note, `graphql-js` seems to be fine with either notation, although it doesn't make much sense. not sure if it's a `graphql` spec oversight or a `graphql-js` bug. I'll file an issue over there as well.

```
extend type Query {
  foo(bar: String! = "Foo"): Boolean
}
```
