### ISSUE TITLE
useTypeImports doesn't work with graphql-request fetcher

### ISSUE THREAD

**Issue by bkilrain** [dotansimha/graphql-code-generator#5478]
**Describe the bug**

When using the `useTypeImports` flag in codegen.yml, an import from `graphql-request` does not adhere to the flag.

**To Reproduce**

A reproducible example in code sandbox is here: https://codesandbox.io/s/sweet-shtern-1wrvw?file=/codegen.yml

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}

```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
        email
    }
}

```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-react-query
      - typescript-operations
      - typescript-resolvers
    config:
      useTypeImports: true
      fetcher: graphql-request

```

**Expected behavior**

In the generated file, this import:
```
import { GraphQLClient } from 'graphql-request';
```

should instead be:
```
import type { GraphQLClient } from 'graphql-request';

```

**Environment:**

- OS: MacOS
- `@graphql-codegen/...`: latest minor versions
- NodeJS: v12.18.3

**Additional context**
