### ISSUE TITLE
[React Query] Cannot find name 'TData'

### ISSUE THREAD

**Issue by merelinguist** [dotansimha/graphql-code-generator#5480]
**Describe the bug**
Generating a simple query executes successfully with the CLI, but produces broken TypeScript:

```tsx
...
export const useDeckQuery = <
      TData = DeckQuery,
      TError = unknown
    >(
      dataSource: { endpoint: string, fetchParams?: RequestInit }, 
      variables: DeckQueryVariables, 
      options?: UseQueryOptions<DeckQuery, TError, TData>
    ) => 
    useQuery<DeckQuery, TError, TData>(
      ['Deck', variables],
      fetcher<DeckQuery, DeckQueryVariables>(dataSource.endpoint, dataSource.fetchParams || {}, DeckDocument, variables),
      options
    );
```

With the following errors:

```
JSX element 'TData' has no corresponding closing tag.ts(17008)
Cannot find name 'TData'.ts(2304)
```

**To Reproduce**
See a reproduction here: https://github.com/merelinguist/codegen-test

1. My GraphQL schema:

```graphql
# Exposes a URL that specifies the behaviour of this scalar.
directive @specifiedBy(
  # The URL that specifies the behaviour of this scalar.
  url: String!
) on SCALAR
type AuthPayload {
  token: String
  user: User
}

type Deck {
  id: String!
  name: String!
  user: User!
}

type Mutation {
  createDeck(name: String!): Deck
  register(email: String!, password: String!): AuthPayload
  login(email: String!, password: String!): AuthPayload
}

type Query {
  me: User
  decks: [Deck]
  deck(id: String): Deck
}

type User {
  id: String!
  email: String!
  decks: [Deck!]!
}
```

2. My GraphQL operations:

```graphql
query Deck($id: String!) {
    deck(id: $id) {
	    id
		name
	}
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
# schema: "http://localhost:4000/graphql"
schema: schema.graphql
documents: "src/graphql/**/*.graphql"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - typescript-react-query
```

**Expected behavior**
When I run `graphql-codegen`, it produces valid TypeScript.

**Environment:**

- OS: MacOS
- NodeJS: v14.15.2
