### ISSUE TITLE
Error: Cannot find module '@vue/compiler-dom'

### ISSUE THREAD

**Issue by EvgenBabenko** [dotansimha/graphql-code-generator#5487]
![Screenshot_2](https://user-images.githubusercontent.com/29785853/106779207-723d4680-664f-11eb-9c9a-61c0ad6f999a.png)

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->


3. My `codegen.yml` config file:

```yml
schema: ${SCHEMA_PATH}
generates:
  src/models/dto/gql.ts:
    plugins:
      - typescript
config:
  # maybeValue: T
  skipTypename: true
  # avoidOptionals: true
  # avoidOptionals:
  #   inputValue: true
  #   object: false
  scalars:
    Long: number
    Instant: string

```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS: win10
- "@graphql-codegen/cli": "1.19.0",
- "@graphql-codegen/typescript": "1.17.11",
- "graphql": "15.4.0",
- NodeJS: v12.14.1

**Additional context**
<!-- Add any other context about the problem here. -->
