### ISSUE TITLE
TypeError: value.includes is not a function on passing custom fetch

### ISSUE THREAD

**Issue by vitorcamachoo** [dotansimha/graphql-code-generator#5524]
**Describe the bug**
 
When passing a custom fetch to `typescript-react-query` I gave the following error:

![Screenshot 2021-02-09 at 16 39 57](https://user-images.githubusercontent.com/20595956/107396187-735df000-6af5-11eb-9edd-06bc34c9ea21.png)

**To Reproduce**
With the following configuration:

```yaml
overwrite: true
schema: "[url]"
documents: "**/*.graphql"
generates:
  libs/backoffice/api/graphql-schema.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-query"
    config:
      fetcher:
        func: ./libs/backoffice/api/graphql-client.ts#fetchData
```
<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure sure fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "https://dev-api.yacooba.live/graphql"
documents: "**/*.graphql"
generates:
  libs/backoffice/api/graphql-schema.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-query"
    config:
      fetcher:
        func: ./libs/backoffice/api/graphql-client.ts#fetchData
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS: MacOS Big Sur 11.1
-  "@graphql-codegen/cli": "1.20.1",
-  "@graphql-codegen/introspection": "1.18.1", 
-  "@graphql-codegen/typescript": "1.20.2",
-  "@graphql-codegen/typescript-graphql-request": "^3.0.1",
-  "@graphql-codegen/typescript-operations": "1.17.14",
-   "@graphql-codegen/typescript-react-apollo": "2.2.1",
-  "@graphql-codegen/typescript-react-query": "^1.1.0",
-  NodeJS: v15.3.0

**Additional context**
<!-- Add any other context about the problem here. -->
