### ISSUE TITLE
[C# operations] treat C# keywords

### ISSUE THREAD

**Issue by fialazd2** [dotansimha/graphql-code-generator#5556]
**Describe the bug**
C# operations can generate fields which are in collision with C# keywords (i.e. "case"). We use "case" in our schema.

**To Reproduce**
1. Generate C# operations.

1. My GraphQL schema:

```graphql
scalar Date

schema {
  query: Query
}

type Query {
  me: case!
  case(id: ID!): case
  allcases: [case]
  search(term: String!): [SearchResult!]!
  myChats: [Chat!]!
}

enum Role {
  case,
  ADMIN,
}

interface Node {
  id: ID!
}

union SearchResult = case | Chat | ChatMessage

type case implements Node {
  id: ID!
  casename: String!
  email: String!
  role: Role!
}

type Chat implements Node {
  id: ID!
  cases: [case!]!
  messages: [ChatMessage!]!
}

type ChatMessage implements Node {
  id: ID!
  content: String!
  time: Date!
  case: case!
}
```

2. My GraphQL operations:

```graphql
query findUser($caseId: ID!) {
  case(id: $caseId) {
    ...UserFields
  }
}

fragment UserFields on case {
  id
  casename
  role
}
```

3. My `codegen.yml` config file:

```yml
generates:
  src/main/c-sharp/my-org/my-app/Operations.cs:
    plugins:
      - c-sharp-operations
    config:
      typesafeOperation: true
```

**Expected behavior**
C# keywords like "case" should be prefixed with @ => `@case`

**Environment:**

- OS: 
- `@graphql-codegen/c-sharp-operations`: 
- NodeJS: 

**Additional context**
