### ISSUE TITLE
[typescript-react-query] Unecessary fetcher definition on fragment-only file with near-operation-file-preset

### ISSUE THREAD

**Issue by jvcmanke** [dotansimha/graphql-code-generator#5599]
**Describe the bug**
`typescript-react-query` plugin generates `fetcher` without necessity on files containing only fragments with `near-operation-file-preset`.

Two things happen in this case:
* The `client` type is not imported when using `fetcher: graphql-request` resulting in a type error;
* The fetcher is unused and thus resulting in a warning when using typescript's `noUnusedLocals` or most linter configurations.

**To Reproduce**

1. Use the `typescript-react-query` plugin with the `near-operation-file-preset`.
2. Create a graphql file with only a fragment.
3. Run `graphql-code-generator`.

[Reproduction Sandbox](https://codesandbox.io/s/clever-cache-30ikt?file=/src/document.graphql.ts)

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```graphql
fragment UserData on User {
    id
    username
}
```

3. My `codegen.yml` config file:

```yml
schema: ./schema.graphql
documents: ./src/document.graphql
generates:
  src/generated/graphql.d.ts:
    plugins:
      - typescript
  src/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: generated/graphql.d.ts
      extension: .graphql.ts
    plugins:
      - typescript-operations
      - typescript-react-query
    config:
      fetcher: graphql-request
```

4. My result file:

```typescript
import * as Types from './generated/graphql.d';


function fetcher<TData, TVariables>(client: GraphQLClient, query: string, variables?: TVariables) {
  return async (): Promise<TData> => client.request<TData, TVariables>(query, variables);
}
export type UserDataFragment = (
  { __typename?: 'User' }
  & Pick<Types.User, 'id' | 'username'>
);

export const UserDataFragmentDoc = `
    fragment UserData on User {
  id
  username
}
    `;
```

**Expected behavior**
The plugin should omit the fetcher declaration when there are no operations on the file.

**Environment:**

- OS: Windows
- `@graphql-codegen/typescript-react-query`: v1.2.1
- `@graphql-codegen/near-operation-file-preset`: v1.17.13
- NodeJS: v14.15.5

**Additional context**
