### ISSUE TITLE
`importsNotUsedAsValues` is not properly handled when using near-operation-file and custom hooks

### ISSUE THREAD

**Issue by mvestergaard** [dotansimha/graphql-code-generator#5633]
**Describe the bug**
When using `near-operation-file` and `apolloReactHooksImportFrom` the import from `@apollo/client` does not use `import type` which causes an error when `importsNotUsedAsValues` is set to `error`

**To Reproduce**
Sandbox reproducing the behavior https://codesandbox.io/s/reverent-liskov-ctzvc?file=/document.generated.tsx:91-132

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
        email
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
generates:
  schema.ts:
    plugins:
        - typescript
  ./:
    documents: document.graphql
    preset: near-operation-file
    presetConfig:
      extension: .generated.tsx
      baseTypesPath: ./schema.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
    config:
      apolloReactHooksImportFrom: ./hooks.ts
      documentMode: external
      importDocumentNodeExternallyFrom: near-operation-file
      useTypeImports: true
```

**Expected behavior**
The line:
```ts
import * as Apollo from '@apollo/client';
```
should instead be:
```ts
import type * as Apollo from '@apollo/client';
```
because only types are being used from that import

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**
<!-- Add any other context about the problem here. -->
