### ISSUE TITLE
Interface resolvers should have only __resolveType method

### ISSUE THREAD

**Issue by skk2142** [dotansimha/graphql-code-generator#5648]
**Describe the bug**
When a Graphql interface is resolved, the resolvers of only the implementing type (returned by __resolveType method of the interface) are called. The resolvers of the interface is never called (expect the `__resolveType` method). Therefore, the interface resolver should only require the implementation of `resolveType` field. However, current version require the interface resolver to implement every field of the interface. I tried using `useImplementingTypes: true` option but that didn't do anything. 
```
"@graphql-codegen/cli": "^1.21.1",
"@graphql-codegen/typescript": "^1.21.0",
"@graphql-codegen/typescript-resolvers": "^1.18.2",
```
```yml
schema: ''
generates:
./src/generated/codegen-server.ts:
    schema:
      - 'src/schema-shared.graphql'
      - 'src/schema.graphql'
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
    config:
      contextType: ../types#Context
      useIndexSignature: true
      avoidOptionals: true
      showUnusedMappers: true
      useImplementingTypes: true
      # optionalResolveType: true
      noSchemaStitching: true
      federation: true
      nonOptionalTypename: true
      mappers:
        Comment: ../types#CommentMapper
        Commentable: ../types#NodeMapper
        Likeable: ../types#NodeMapper
        Node: ../types#NodeMapper
        Bookmarkable: ../types#NodeMapper
        Flaggable: ../types#NodeMapper
        CommentConnection: ../types#CommentConnectionMapper
```
