### ISSUE TITLE
[cli] can't send custom http headers to server during introspection

### ISSUE THREAD

**Issue by mscharley** [dotansimha/graphql-code-generator#5655]
**Describe the bug**
 

After updating to 1.21.1, from 1.20.1. The only version that is changing in this upgrade is for `@graphql-codegen/cli`.

When generating an API client, the introspection step fails. The messages are reminiscent of when I first setup this codegen when I didn't include the custom headers. The other servers I use codegen against that do not have custom HTTP headers are working fine.

The only error message I've been able to get out of the CLI, even with `DEBUG=1` and `VERBOSE=1` is:

```
Failed to find any GraphQL type definitions in: https://api.newrelic.com/graphql - Invalid MIME type
[12:25:45] Load GraphQL schemas [failed]
[12:25:45] → Failed to load schema
[12:25:45] Generate ./src/app/graphql/requests/newrelic.ts [failed]
[12:25:45] → Failed to load schema
```

**To Reproduce**

I can't include my live API credentials but you should be able to reproduce this with any server that only allows introspection when certain HTTP headers are included.

1. My GraphQL schema:

```graphql
# N/A
```

2. My GraphQL operations:

```graphql
fragment entity on Entity {
  __typename
  name
  guid
  entityType
  tags {
    key
    values
  }
  ... on SyntheticMonitorEntity {
    monitorType
    monitorId
    monitoredUrl
    period
  }
}
fragment entityOutline on EntityOutline {
  __typename
  name
  guid
  entityType
  tags {
    key
    values
  }
  ... on SyntheticMonitorEntityOutline {
    monitorType
    monitorId
    monitoredUrl
    period
  }
}
query entitySearch($query: EntitySearchQueryBuilder!) {
  actor {
    entitySearch(queryBuilder: $query) {
      results {
        entities {
          ...entityOutline
        }
        nextCursor
      }
    }
  }
}
query getEntity($id: EntityGuid!) {
  actor {
    entity(guid: $id) {
      ...entity
    }
  }
}
mutation tagEntity ($guid: EntityGuid!, $tags: [TaggingTagInput!]!){
  taggingAddTagsToEntity(guid: $guid, tags: $tags) {
    errors {
      message
      type
    }
  }
}
mutation untagEntity ($guid: EntityGuid!, $tags: [String!]!) {
  taggingDeleteTagFromEntity(guid: $guid, tagKeys: $tags) {
    errors {
      message
      type
    }
  }
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
documents: []

generates:
  ./src/app/graphql/requests/newrelic.ts:
    schema:
      - "https://api.newrelic.com/graphql":
          headers:
            API-Key: ${NEWRELIC_PERSONAL_TOKEN}
            Content-Type: application/json
    documents: "./src/app/graphql/requests/newrelic/*.graphql"
    config:
      avoidOptionals: true
      constEnums: true
      enumsAsTypes: true
      noSchemaStitching: true
      immutableTypes: true
    plugins:
      - typescript
      - typescript-operations
      - "@graphql-codegen/typescript-graphql-request"
require: []
```

**Expected behavior**

For the headers to be included and the graphql introspection to happen successfully.

**Environment:**

- OS: OSX 10.15
- `@graphql-codegen/cli`: "^1.21.1"
- `@graphql-codegen/typescript`: "^1.21.0"
- `@graphql-codegen/typescript-graphql-request`: "^3.0.2"
- `@graphql-codegen/typescript-operations`: "^1.17.14"
- `@graphql-codegen/typescript-resolvers`: "^1.18.2"
- NodeJS: 12.x

**Additional context**
