### ISSUE TITLE
Config schema for avoidOptionals seems to be incorrect.

### ISSUE THREAD

**Issue by ryan-rushton** [dotansimha/graphql-code-generator#5718]
**Describe the bug**
 

When using finer config for avoidOptionals VsCode reports the config as an error. This appears to be coming from an incorrectly defined yaml schema.

**To Reproduce**
1. Define your `config.yml` with an object of config values as per the included config
2. Open `config.yml` in VsCode

![Screen Shot 2021-03-16 at 3 01 15 pm](https://user-images.githubusercontent.com/7344652/111254821-f41a8980-8669-11eb-81f0-c743113796da.png)

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

N/A

2. My GraphQL operations:

N/A

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: './src/graphql/types/[!index]*.ts'
hooks:
  afterAllFileWrite:
    - yarn prettier --write
generates:
  src/generated/types.ts:
    config:
      useIndexSignature: true
      allowParentTypeOverride: true
      noSchemaStitching: true
      contextType: ../graphql/context#Context
      noRequire: true
      avoidOptionals:
        field: false
        inputValue: true
        object: true
        defaultValue: true
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

The config entered to be valid.

**Environment:**

- OS: macOS
```json
"@graphql-codegen/cli": "1.21.2",
"@graphql-codegen/typescript": "1.21.1",
"@graphql-codegen/typescript-resolvers": "1.19.0",
```
- NodeJS: 15.8.0

**Additional context**
<!-- Add any other context about the problem here. -->
N/A
