### ISSUE TITLE
[typescript-react-query] Allow to use useInfiniteQuery

### ISSUE THREAD

**Issue by iksent** [dotansimha/graphql-code-generator#5720]
It will be great to have a possibility to use [useInfiniteQuery](https://react-query.tanstack.com/reference/useInfiniteQuery#_top).

**Describe the solution you'd like**
We can provide an option to enable generation of `useInfiniteQuery` in addition to `useQuery`

```
generates:
  ./src/Graphql/generated.ts:
    schema: ...
    documents: src/Graphql/result.graphql
    config:
      createInfiniteQueries: true
...
```

**Query looks like this now:**

```
export const useGetStatisticsQuery = <TData = GetStatisticsQuery, TError = unknown>(
  variables?: GetStatisticsQueryVariables,
  options?: UseQueryOptions<GetStatisticsQuery, TError, TData>,
) =>
  useQuery<GetStatisticsQuery, TError, TData>(
    ['getStatistics', variables],
    fetcher<GetStatisticsQuery, GetStatisticsQueryVariables>(
      GetStatisticsDocument,
      variables,
    ),
    options,
  )
```

So it will generate also:

```
export const useGetStatisticsInfiniteQuery = <TData = GetStatisticsQuery, TError = unknown>(
  variables?: GetStatisticsQueryVariables,
  options?: UseInfiniteQueryOptions<GetStatisticsQuery, TError, TData>,
) =>
  useInfiniteQuery<GetStatisticsQuery, TError, TData>(
    ['getStatistics', variables],
    fetcher<GetStatisticsQuery, GetStatisticsQueryVariables>(
      GetStatisticsDocument,
      variables,
    ),
    options,
  )

```
