### ISSUE TITLE
Let return type of __resolveType be string sometimes

### ISSUE THREAD

**Issue by jjangga0214** [dotansimha/graphql-code-generator#5755]
**Is your feature request related to a problem? Please describe.**

I am implementing Relay-spec-compliant Apollo Federation.
There is an interface `Node`, and each 'implementing services' (Apollo Federation term. Designating (micro) services behind Apollo Gateway.) has several ObjectDefinitionTypes implementing `Node` interface.

Let's say I have `serviceA` with `Foo` and `Bar` Object types of `Node`, while `serviceB` with `Bar`(referencing external type) and `Qux` of `Node`. Then a resolver(below) for `Node` in `serviceA` works well with graphql-code-generator. 

```ts
const Node: NodeResolvers = {
  __resolveType: ({ id }) => {
    if (Math.random() > 0.5) {
      return 'Foo'
    }
    return 'Bar'
  },
}
```

However, a resolver below does not.

```ts
// in another module
export type DecodedGqlId = {
  version: 1
  service: string
  type: string
  identifier: string
}

export function decodeGqlId(id: string): DecodedGqlId {
  return ... // some deserialization and parsing logic here. 
}

// in resolver module
const Node: NodeResolvers = {
  __resolveType: ({ id }) => {
    const { type } = decodeGqlId(id).
    return type
  },
}
```

This is because `__resolveType` returns `string`, not `'Foo' | 'Bar'`. This is good for a single server, but becomes a problem in this case, for Apollo Federation. The function `decodeGqlId` is used by another service, `serviceB`, as well, so its return type can't be narrowed. 

In result, `//@ts-ignore` is commented in every implementing services' `Node` resolver, which is not so ideal.

**Describe the solution you'd like**

When `federation: true`, let `__resolveType` return 'string', not concrete types.

```yaml
    plugins:
      - typescript-resolvers
    config:
      federation: true
```

**Describe alternatives you've considered**

Introducing a new config.

```yaml
    plugins:
      - typescript-resolvers
    config:
      __resolveType:
        returnType : string // 'implementation' is default
```
