### ISSUE TITLE
Cannot query field ... on type "RootType"

### ISSUE THREAD

**Issue by lkleuver** [dotansimha/graphql-code-generator#5756]
Sorry for not following the template. I can't reproduce it with the same codebase (assumption) on a different laptop.

on a long-running project, I've updated all packages to their latest versions and now for the life of me, can't get graphql-codegen to work anymore.

I get an error for all my operations "Cannot query field" 
Even when I go back to the exact same setup for codegen as before it throws the same errors.

When I only run the introspection plugin it works, also on another laptop with the old code the codegen works so I think I can rule out it has to do with the graphql server (Hasura).

My question is:
Does anybody have some pointers where I need to start looking?
I just don't know where to start.

I've tried:
- almost all different graphql versions
- a lot of different versions of the various graphql-codegen packages
- reinstalling packages
- restarting my laptop
- pulling out my scarce hair

The only piece of usefull information in the error output is:
```
new AggregateError (/Users/les/projects/spatialexplorers/dagenapp/node_modules/@ardatan/aggregate-error/index.cjs.js:141:24)
    at Object.checkValidationErrors (/Users/les/projects/spatialexplorers/dagenapp/node_modules/@graphql-codegen/core/node_modules/@graphql-tools/utils/index.cjs.js:517:15)
```

config file:
```
schema:
  - ${GRAPHQL_HOST}:
      headers:
        x-hasura-admin-secret: ${HASURA_ADMIN_SECRET}
documents: "./packages/app/query/**/*.graphql"
generates:
  ./packages/app/types/gen.tsx:
    - typescript
    - typescript-operations
    - typescript-react-apollo
```
cmd:
```
"scripts": {
    "generate": "DEBUG=1 graphql-codegen -r dotenv/config"
  },
```
