### ISSUE TITLE
Introspection/schema-ast not generating queries/mutations from documents

### ISSUE THREAD

**Issue by kennandavison** [dotansimha/graphql-code-generator#5789]
**Describe the bug**
Expecting hasura.ts, hasura.json and hasura.graphql to grab queries/mutations from documents. Only hasura.ts seems to do so. Am I missing something?

Edit: Do introspection/schema-ast not support documents? If not, any hints on generating these with my queries/mutations?

My `codegen.yml` config file:

```yml
generates:
  ./common/src/graphql/types/hasura.ts:
    config:
      withHooks: true
    schema:
      - ${HASURA_GRAPHQL_ENDPOINT}:
          headers:
            x-hasura-admin-secret: ${HASURA_GRAPHQL_ADMIN_SECRET}
    documents:
      - '**/graphql/hasura/**/*.{ts,tsx}'
      - '**/graphql/hasura.{ts,tsx}'
      - '!**/node_modules'
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
  ./common/src/graphql/schemas/hasura.json:
    schema:
      - ${HASURA_GRAPHQL_ENDPOINT}:
          headers:
            x-hasura-admin-secret: ${HASURA_GRAPHQL_ADMIN_SECRET}
    documents:
      - '**/graphql/hasura/**/*.{ts,tsx}'
      - '**/graphql/hasura.{ts,tsx}'
      - '!**/node_modules'
    plugins:
      - introspection
    config:
      minify: true
  ./common/src/graphql/schemas/hasura.graphql:
    schema:
      - ${HASURA_GRAPHQL_ENDPOINT}:
          headers:
            x-hasura-admin-secret: ${HASURA_GRAPHQL_ADMIN_SECRET}
    documents:
      - '**/graphql/hasura/**/*.{ts,tsx}'
      - '**/graphql/hasura.{ts,tsx}'
      - '!**/node_modules'
    plugins:
      - schema-ast
```

**Environment:**

`@graphql-codegen/...`: 
"@graphql-codegen/cli": "^1.20.0",
"@graphql-codegen/introspection": "^1.18.1",
"@graphql-codegen/schema-ast": "^1.18.1",
"@graphql-codegen/typescript": "^1.20.0",
"@graphql-codegen/typescript-operations": "^1.17.13",
"@graphql-codegen/typescript-react-apollo": "^2.2.1"
