### ISSUE TITLE
Argument of type 'DocumentNode' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by cmonty** [dotansimha/graphql-code-generator#5798]
**Describe the bug**
As of `@​graphql-codegen/typescript-graphql-request` 3.1.0 generated code no longer calls `print` when calling `rawRequest`. This breaks the request and tries to send AST instead of the query.

**To Reproduce**

https://codesandbox.io/s/suspicious-kirch-bsv3x?file=/types.ts

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
overwrite: true
generates:
  types.ts:
    config:
      rawRequest: true
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
```

**Expected behavior**
There are not type errors in `types.ts`

**Environment:**

- OS: MacOS 11.2.1
- `@​graphql-codegen/typescript-graphql-request 3.1.0 `: 
- NodeJS: 14.16.0

**Additional context**
https://github.com/dotansimha/graphql-code-generator/pull/5618
https://github.com/dotansimha/graphql-code-generator/issues/5614
