### ISSUE TITLE
Enum becomes typescript string when using graphql-modules preset

### ISSUE THREAD

**Issue by jjangga0214** [dotansimha/graphql-code-generator#5799]
**Describe the bug**
By default, graphql-code-generator converts GraphQL enums to typescript enums when using `typescript` plugin.

However, when using `graphql-modules` preset with `typescript` plugin, GraphQL enum becomes a typescript string.

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
enum Foo {
    HELLO_WORLD
    HI_THERE
}
```

2. My `codegen.yml` config file:

```yml
generates:
  ./src/graphql/module:
    schema: ./src/graphql/module/*/*.graphql
    preset: graphql-modules
    presetConfig:
      baseTypesPath: ../../generated/graphql/self.ts
      filename: generated.ts
    plugins:
      - typescript
      - typescript-resolvers
```

**Expected behavior**

I expected it makes typescript enum like the one below.

```typescript
export enum Foo {
  HelloWorld = 'HELLO_WORLD',
  HiThere = 'HI_THERE'
}
```

However, it actually creates a typescript string like the one below.

```typescript
export type Foo =
  | 'HELLO_WORLD'
  | 'HI_THERE';
```

I am using multiple codegen configs with Apollo Federation, and this breaking inconsistency results incompatible type.  

**Environment:**

- OS: Ubuntu 20.04.
- "@graphql-codegen/cli": "^1.21.3"
- "@graphql-codegen/graphql-modules-preset": "^1.2.4"
- "@graphql-codegen/typescript": "^1.21.1"
- "@graphql-codegen/typescript-resolvers": "^1.19.0"
- NodeJS: v14.16.0

<!-- **Additional context** -->
<!-- Add any other context about the problem here. -->
