### ISSUE TITLE
Plugin csharp, nullable DateTime field is generated as mandatory

### ISSUE THREAD

**Issue by kondratov-saritasa** [dotansimha/graphql-code-generator#5859]
Plugin csharp, nullable DateTime field is generated as mandatory

Steps to reproduce:
1. Use SDL:
```
type Test {
  dateOptional: DateTime
  dateMandatory: DateTime!
}

scalar DateTime
```
2. Use codegen.yaml:
```
schema: schema.graphql
generates:
  Model.cs:
    plugins:
      - c-sharp
    config:
      className: Model
      scalars:
        DateTime: DateTime
```
3. generate

Result:
```
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using GraphQL;

namespace GraphQLCodeGen {
  public class Model {
    
    #region Test
    public class Test {
      #region members
      [JsonProperty("dateOptional")]
      public DateTime dateOptional { get; set; } // <-- should be optional
    
      [JsonProperty("dateMandatory")]
      public DateTime dateMandatory { get; set; }
      #endregion
    }
    #endregion
  }
  
}
```

Expected result:
```
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using GraphQL;

namespace GraphQLCodeGen {
  public class Model {
    
    #region Test
    public class Test {
      #region members
      [JsonProperty("dateOptional")]
      public DateTime? dateOptional { get; set; }
    
      [JsonProperty("dateMandatory")]
      public DateTime dateMandatory { get; set; }
      #endregion
    }
    #endregion
  }
  
}

```
