### ISSUE TITLE
typescript-react-query plugin should expose document for hooks

### ISSUE THREAD

**Issue by lynxtaa** [dotansimha/graphql-code-generator#5862]
**Is your feature request related to a problem? Please describe.**

In typescript-react-query plugin there's an option to expose query keys for hooks. I'd like to expose document as well to make writing custom hooks easier. Example:

```ts
interface UseQueryFn<
  TData extends Record<string, any>,
  TVariables extends Record<string, any>
> {
  (variables: TVariables, options?: UseQueryOptions<TData>): unknown
  getKey: (variables: TVariables) => unknown[]
  document: string // this what I want to expose
}

function useFetchGraphQLQuery<
  TData extends Record<string, any>,
  TVariables extends Record<string, any>
>(
  useQuery: UseQueryFn<TData, TVariables>,
): (variables: TVariables, options?: FetchQueryOptions<TData, Error>) => Promise<TData> {
  const queryClient = useQueryClient()

  return useCallback(
    (variables, options) =>
      queryClient.fetchQuery(
        useQuery.getKey(variables),
        () => gqlRequest<TData, TVariables>(useQuery.document, variables),
        options,
    ),
    [useQuery, queryClient],
  )
}

// Then using it like this:

const getUser = useFetchGraphQLQuery(useGetUser)

async function onClick() {
  const user = await getUser({ id: 1 })
}
```

**Describe the solution you'd like**
I'd like to add an option `exposeDocument`. Created PR: https://github.com/dotansimha/graphql-code-generator/pull/5863

**Comment by ardatan** [comment]
There are other plugins that expose documents like `typed-document-node`. I am not sure if this is the case of this plugin.

**Comment by lynxtaa** [comment]
@ardatan  Yes, document node is already exposed but it's not tied to a particular hook, so right now I how to write:

```ts
function useFetchGraphQLQuery<
  TData extends Record<string, any>,
  TVariables extends Record<string, any>
>(
  useQuery: UseQueryFn<TData, TVariables>,
  query: string
): (variables: TVariables, options?: FetchQueryOptions<TData, Error>) => Promise<TData> {
  const queryClient = useQueryClient()

  return useCallback(
    (variables, options) =>
      queryClient.fetchQuery(
        useQuery.getKey(variables),
        () => gqlRequest<TData, TVariables>(query, variables),
        options,
    ),
    [useQuery, query, queryClient],
  )
}

const getUser = useFetchGraphQLQuery(useGetUser, GetUserDocument)
```

It requires more attention and can be error prone

**Comment by ardatan** [comment]
@lynxtaa So you can use `TypedDocumentNode` plugin to generate `TypedDocumentNode` and the signature can be like below;
```
function useFetchGraphQLQuery<
  TData extends Record<string, any>,
  TVariables extends Record<string, any>
>(
  useQuery: UseQueryFn<TData, TVariables>,
  query: TypedDocumentNode<TData, TVariables>
)
```
So you can make sure the document is correct thanks to `TypedDocumentNode`

**Comment by lynxtaa** [comment]
I didn't know about `TypedDocumentNode` and it looks really neat, thank you! But I think it'll be much easier from the development perspective to infer a query from a passed hook:
1. Requires passing less arguments to custom hooks
2. No need to install typed-document-node
3. No need to generate `TypedDocumentNode` for each query since it's much more rare usage cases like `queryClient.fetchQuery`, `queryClient.prefetchQuery`
4. Now I have to stringify `DocumentNode` to make a request

It seems to be an overkill it my case. It's a small addition to a plugin and it'll be very useful

**Comment by lynxtaa** [comment]
Also I've experimented with `typed-document-node` with `typescript-react-query` and it produces clashing exports:

![Снимок экрана 2021-04-18 125558](https://user-images.githubusercontent.com/22496946/115141526-80431680-a045-11eb-88b0-4059241a0977.png)

My config is:
```yml
overwrite: true
schema: 'https://rickandmortyapi.com/graphql'
documents: '{hooks,lib,pages}/**/*.{ts,tsx,graphql}'
generates:
  lib/graphql-queries.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
      - typescript-react-query
    config:
      errorType: Error
      skipTypename: true
      exposeQueryKeys: true
      avoidOptionals:
        field: true
        inputValue: false
        object: false
        defaultValue: false
      fetcher:
        func: './gqlFetcher#gqlFetcher'
        isReactHook: false
```

Am I missing something?
