### ISSUE TITLE
Please make sure that your codegen config file contains either the “schema” field

### ISSUE THREAD

**Issue by softshipper** [dotansimha/graphql-code-generator#5903]
Hi all 

I use https://www.graphql-code-generator.com/ to generate code for graphql query client. The configuration `codegen.yml` file looks as follows:
```
overwrite: true
generates:
  ./generated/provider.ts:
    documents: "graphql/providers/**/*.graphql"
    schema: "http://localhost:4000"
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
  ./graphql.schema.json:
    plugins:
      - "introspection"
```

Running `npm run codegen` I am getting the following error message:

```
graphql-codegen --config codegen.yml

  ✖ Parse configuration
    → Invalid Codegen Configuration!
    Generate outputs
  Invalid Codegen Configuration!

        Please make sure that your codegen config file contains either the "schema" field 
        or every generated file has its own "schema" field.
        
        It should looks like that:
        schema:
          - my-schema.graphql

        or:
        generates:
          path/to/output:
            schema: my-schema.graphql
```
As you can see above, I have put the field `schema` in the `codegen.yml` file. Regarding the documentation, it is possible to point either on root or on per-output file level:

https://www.graphql-code-generator.com/docs/getting-started/schema-field#root-level

In my case, I have done it on per-output file level. What am I doing wrong?

Best regards
