### ISSUE TITLE
TypeError: value.includes is not a function when using custom fetch function

### ISSUE THREAD

**Issue by pfaffle** [dotansimha/graphql-code-generator#5910]
**Describe the bug**
 
When passing a custom fetch to `typescript-react-query` I got the following error:

```
$ graphql-codegen -c src/@tw/scm/codegen.yaml
  √ Parse configuration
  > Generate outputs
    > Generate src/@tw/scm/query/graphql.ts
      √ Load GraphQL schemas
      √ Load GraphQL documents
      × Generate
        → value.includes is not a function


 Found 1 error

  × src/@tw/scm/query/graphql.ts

TypeError: value.includes is not a function
        at isExternalMapper (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\visitor-plugin-common\index.cjs.js:144:18)
        at Object.parseMapper (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\visitor-plugin-common\index.cjs.js:64:9)
        at new CustomMapperFetcher (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\typescript-react-query\index.cjs.js:169:44)
        at ReactQueryVisitor.createFetcher (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\typescript-react-query\index.cjs.js:236:16)
        at new ReactQueryVisitor (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\typescript-react-query\index.cjs.js:220:29)
        at Object.plugin (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\typescript-react-query\index.cjs.js:277:21)
        at executePlugin (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\core\index.cjs.js:38:35)
        at async C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\core\index.cjs.js:116:24
        at async Promise.all (index 3)
        at async Object.codegen (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\core\index.cjs.js:106:20)
    TypeError: value.includes is not a function
        at isExternalMapper (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\visitor-plugin-common\index.cjs.js:144:18)
        at Object.parseMapper (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\visitor-plugin-common\index.cjs.js:64:9)
        at new CustomMapperFetcher (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\typescript-react-query\index.cjs.js:169:44)
        at ReactQueryVisitor.createFetcher (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\typescript-react-query\index.cjs.js:236:16)
        at new ReactQueryVisitor (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\typescript-react-query\index.cjs.js:220:29)
        at Object.plugin (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\typescript-react-query\index.cjs.js:277:21)
        at executePlugin (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\core\index.cjs.js:38:35)
        at async C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\core\index.cjs.js:116:24
        at async Promise.all (index 3)
        at async Object.codegen (C:\Users\pfaffle\git\ui\node_modules\@graphql-codegen\core\index.cjs.js:106:20)


Something went wrong
error Command failed with exit code 1.
```
**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: 'src/@tw/scm/schema.graphql'
documents: 'src/@tw/scm/queries/*.graphql'
config:
  nonOptionalTypename: true
  fetcher:
    func: 'src/@tw/scm/util/util.ts#useFetchData'
    isReactHook: true
generates:
  src/@tw/scm/query/graphql.ts:
    plugins:
      - add:
          content:
            - '/* DO NOT EDIT! This file is auto-generated by graphql-code-generator - see `codegen.yaml` */'
            - '/* eslint-disable @typescript-eslint/ban-types,no-duplicate-imports */'
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-query'
hooks:
  afterOneFileWrite:
    - prettier --write
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS: Windows 10.0.19042
- "@graphql-codegen/add": "^2.0.2",
- "@graphql-codegen/cli": "1.21.2",
- "@graphql-codegen/typescript": "1.21.1",
- "@graphql-codegen/typescript-operations": "1.17.15",
- "@graphql-codegen/typescript-react-apollo": "2.2.2",
- "@graphql-codegen/typescript-react-query": "0.1.1",
- NodeJS: v12.18.4

**Additional context**
<!-- Add any other context about the problem here. -->
Looks like the same issue described in https://github.com/dotansimha/graphql-code-generator/issues/5524. I tested the recommendation in that issue, and while it does cause `graphql-codegen` to run without errors, that solution doesn't work for me because my fetcher is a React Hook and I need the generated code to treat it as one.
