### ISSUE TITLE
Support dynamic "generates" keys for filenames

### ISSUE THREAD

**Issue by jonnyasmar** [dotansimha/graphql-code-generator#5913]
**Is your feature request related to a problem? Please describe.**

I have a project with different gql files that represent queries/mutations for different facets of my application. To make these work with Typescript imports, the declaration files need to match the gql filename.

**Describe the solution you'd like**

I would like to generate declarations for these files via `typescript-graphql-files-modules` that matched the filename of the gql file so that Typescript's module resolution would pick these up when importing them. Perhaps an api like this would get the job done:

```yaml
schema: "src/graph/schema.graphql"
documents: "src/graph/**/*.gql"
generates:
  src/graph/[filename].d.ts: # where filename represents the document's filename (minus the extension)
    plugins:
      - "typescript-graphql-files-modules"
```

**Describe alternatives you've considered**

Haven't figured out a workable alternative, yet.
