### ISSUE TITLE
Get multiple schemas without merging

### ISSUE THREAD

**Issue by skk2142** [dotansimha/graphql-code-generator#5928]
Apollo federation exposes a function to validate composition of federated schemas. However, this requires the separate type definitions of the each schema without merging them. Currently graphql codegen automatically merges the schemas when creating a plugin. May be we can add an option to get the raw type definitions without merging?

**Comment by ardatan** [comment]
You can generate seperate files for each service like below;
```yaml
generates:
   a-service.ts:
       schema: pointertoservicea
       plugins:
         - typescript
         - typescript-resolvers
       config:
          federation: true
   b-service.ts:
       schema: pointertoserviceb
       plugins:
         - typescript
         - typescript-resolvers
       config:
          federation: true

```
