### ISSUE TITLE
Types for input objects should not have a prototype

### ISSUE THREAD

**Issue by bezreyhan** [dotansimha/graphql-code-generator#5964]
**Describe the bug**
 
The Javascript object that is returned for mutation inputs does not have a prototype but this is not reflected in the generated types. 

See issue here: https://github.com/ardatan/graphql-tools/issues/1374

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->


2. My GraphQL operations:

```graphql
{
  Mutation: {
    someMutation(_, { input }) {
        input.hasOwnProperty() // this will throw an error since input does not have a prototype
    } 
  }
}
```

3. My `codegen.yml` config file:
```yml
overwrite: true
schema: '...'
documents: null
generates:
  src/...
    config:
      noSchemaStitching: true
      useIndexSignature: true
      namingConvention:
        enumValues: 'change-case#upperCase'
    plugins:
      - add:
          content: '/* tslint:disable */'
      - 'typescript'
      - 'typescript-resolvers'
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->
Can we create a special type for object-inputs to null out all of their prototype fields?
