### ISSUE TITLE
[typescript-resolvers] Missings args types in QueryResolvers

### ISSUE THREAD

**Issue by olso** [dotansimha/graphql-code-generator#5968]
**Describe the bug**
 

Args (my case `limit`) are not generated on `QueryResolvers["landing"]`

They are generated on `LandingResolvers` tho

The query works in runtime of course

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type City implements Node {
    id: ID!
    isFeatured: Boolean!
    name: String!
  }

type Query {
    landing: Landing
}

type Landing {
    # This is generated for LandingResolvers, but not for QueryResolvers["landing"]
    featuredCities(limit: Int!): [City!]!
  }

```

2. My GraphQL operations:

```graphql
query {
  landing {
    featuredCities(limit: 2) {
      code
    }
  }
}
```

3. My `codegen.yml` config file:

```yml
schema: http://localhost:8081/graphql

config:
  noSchemaStitching: true
  optionalInfoArgument: true
  federation: false
  useTypeImports: true
  # useIndexSignature: true
  maybeValue: T | null | undefined
  contextType: ./ApolloContext#ApolloContext
  # also check web repo codegen.yml for scalars
  scalars:
    DateTime: string
    Date: string
    Time24H: string
    Money: string
  mappers:
    City: ./GeneratedDb#City as CityDb

generates:
  src/types/GeneratedGql.ts:
    plugins:
      - typescript
      - typescript-resolvers

```

4. Generated types:

```ts
export type QueryResolvers<ContextType = ApolloContext, ParentType extends ResolversParentTypes['Query'] = ResolversParentTypes['Query']> = ResolversObject<{
  landing?: Resolver<Maybe<ResolversTypes['Landing']>, ParentType, ContextType>;
}>;

/** Mapping between all available schema types and the resolvers types */
export type ResolversTypes = ResolversObject<{
  Landing: ResolverTypeWrapper<Omit<Landing, 'featuredCities'> & { featuredCities: Array<ResolversTypes['City']> }>;
}>;

/**
 * Here the args are missing
 */
export type LandingResolvers<ContextType = ApolloContext, ParentType extends ResolversParentTypes['Landing'] = ResolversParentTypes['Landing']> = ResolversObject<{
  featuredCities?: Resolver<Array<ResolversTypes['City']>, ParentType, ContextType, RequireFields<LandingFeaturedCitiesArgs, 'limit'>>;
}>;
```

```ts
export const query: QueryResolvers["landing"] = () => ({
  /**
   * Here limit is any / untyped
   */
  featuredCities: ({ limit }) =>
    getCityBase().where({ isFeatured: true }).limit(makeLimit(limit)).orderBy("name", "asc"),
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS: macOS 11.2
- `@graphql-codegen/...`: 
- ├─ @graphql-codegen/cli@1.21.4
├─ @graphql-codegen/core@1.17.9
├─ @graphql-codegen/plugin-helpers@1.18.5
├─ @graphql-codegen/typescript-resolvers@1.19.1
├─ @graphql-codegen/typescript@1.22.0
├─ @graphql-codegen/visitor-plugin-common@1.20.0
- NodeJS: 14
- TS: typescript@4.2.4

**Additional context**
<!-- Add any other context about the problem here. -->
