### ISSUE TITLE
Name "__v" must not begin with "__", which is reserved by GraphQL introspection.

### ISSUE THREAD

**Issue by mehmetnyarar** [dotansimha/graphql-code-generator#5980]
We use `__v` field from MongoDB in our GraphQL type definitions. I can't generate Flow types due to the following error:

> Name "__v" must not begin with "__", which is reserved by GraphQL introspection.
>   at assertValidSchema (root/node_modules/graphql/type/validate.js:69:11)
>   at Object.validate (root/node_modules/graphql/validation/validate.js:51:35)
>   at root/node_modules/@graphql-codegen/core/node_modules/@graphql-tools/utils/index.cjs.js:494:32
>   at Array.map (<anonymous>)
>   at Object.validateGraphQlDocuments (root/node_modules/@graphql-codegen/core/node_modules/@graphql-tools/utils/index.cjs.js:48
>   0:37)
>   at Object.codegen (root/node_modules/@graphql-codegen/core/index.cjs.js:95:36)
>   at process (root/node_modules/@graphql-codegen/cli/bin.js:942:67)
>   at Array.map (<anonymous>)
>   at root/node_modules/@graphql-codegen/cli/bin.js:949:63
>   at async Task.task (root/node_modules/@graphql-codegen/cli/bin.js:727:17)

This is a very critical field in our exiting application, many comparisons are made based on it. Refactoring the code may not be a solution, so how can I solve this?

1. My GraphQL schema:

```graphql
type MyType {
  __v: Int!
}
```

3. My `codegen.yml` config file:

```yaml
overwrite: true
schema: 'http://localhost:8000/introspection'
documents: 'src/**/queries.js'
generates:
    src/generated/graphql.js:
        plugins:
            - 'flow'
            - 'flow-operations'
    ./graphql.schema.json:
        plugins:
            - 'introspection'
```

Environment:

Mac OS Big Sur 11.3.1
Node 12.21.0

package.json:

"@graphql-codegen/cli": "1.21.4",
"@graphql-codegen/flow-operations": "1.18.8",
"@graphql-codegen/flow": "1.19.0",
"@graphql-codegen/introspection": "1.18.2"
