### ISSUE TITLE
Mapped types are dropped when combined with unions at non-trivial depth.

### ISSUE THREAD

**Issue by jacob-indieocean** [dotansimha/graphql-code-generator#5998]
**Describe the bug**
The resolver type for a type that contains a type that contains a union of types that are mapped, drops knowledge of the mapped type.

That a mouthful, but here is a minimal reproduction:

**To Reproduce**
LIve Code Sandbox: https://codesandbox.io/s/inspiring-shape-ts0t5

1. My GraphQL schema:
```graphql
type Query {
    feed: FeedConnection!
}

type FeedConnection {
    edge:FeedEdge
}

type FeedEdge {
    node: FeedNode
}

union FeedNode = PostFeedNode | PhotoFeedNode

type PostFeedNode {
    text:String
}

type PhotoFeedNode {
    url:String
}
```

2. My GraphQL operations:
N/A

3. My `codegen.yml` config file:
```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-resolvers
    config:
      mappers:
        PostFeedNode: ./model#PostFeedNodeModel
        PhotoFeedNode: ./model#PhotoFeedNodeModel
```

**Expected behavior**
The resolver type should be:
`FeedConnection:ResolverTypeWrapper<Omit<FeedConnection, 'edge'> & { node?: Maybe<ResolversTypes['FeedEdge']> }>;`

But the generated type is:
`FeedConnection: ResolverTypeWrapper<FeedConnection>;`
