### ISSUE TITLE
[typescript-react-apollo] TypesSuffix is also used on operations

### ISSUE THREAD

**Issue by ImLuze** [dotansimha/graphql-code-generator#6001]
**Describe the bug**
When I generate react-apollo hooks with a `TypesSuffix` configured. The `TypesSuffix` is also used in the name of the hook. I'm not entirely sure if this is considered a bug, but it feels weird to me that the `TypesSuffix` is used on anything other than types.

**To Reproduce**
[CodeSandbox reproduction](https://codesandbox.io/s/zealous-bardeen-b4o3c?file=/types.ts)
Notice the `typesSuffix` in the type names as well as the function names.

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
        email
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      typesSuffix: Type
```

**Expected behavior**
Only the types should have the `Type` suffix:
Expect:
```
export type UserQueryType ...
export function useUserQuery ...
```
instead of:
```
export type UserQueryType ...
export function useUserQueryType ...
```

**Environment:**

- OS: MacOS 11.3
- `@graphql-codegen/add`: 2.0.2
- `@graphql-codegen/cli`: 1.20.1
- `@graphql-codegen/typescript`: 1.21.0
- `@graphql-codegen/typescript-operations`:  1.17.14
- `@graphql-codegen/typescript-react-apollo`: 2.2.4
- NodeJS: 14.3.0
