### ISSUE TITLE
Lifecycle Hooks - expand capabilities

### ISSUE THREAD

**Issue by jycouet** [dotansimha/graphql-code-generator#6076]
Today you can do: 
```yml
hooks:
  afterAllFileWrite:
    - prettier --write
```
And it will run prettier after the hook `afterAllFileWrite`. All great!

---

But it seems that you can use only your `.bin` scripts:

![image](https://user-images.githubusercontent.com/5312607/120372724-d29b7680-c317-11eb-9611-7290b468130e.png)

---

**I would love to have:**

- The posibility to run another script from my `package.json`, like: `yarn myScript` or `myScript`
- The posibility to run a node script directly

Like:
```yml
hooks:
  afterAllFileWrite:
    - prettier --write                                  # Working :)
    - yarn myScript                                     # Not working
    - node tools/graphql-codegen-modules-merge-resolver # Not working
```
