### ISSUE TITLE
Only first lifecycle hook runs

### ISSUE THREAD

**Issue by doomsower** [dotansimha/graphql-code-generator#6091]
**Describe the bug**
When `beforeDone` lifecycle hook is a list, only the first hook runs

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema:
  - './packages/schema/schema/*.graphql'
documents:
  # Shared fragments, used both by frontend and by backend tests
  - ./packages/schema/fragments/*.gql
generates:
  # Common types shared by backend, web frontend and mobile are generated in schema package
  # Common validation schemas are also in schema package
  ./packages/schema/src/__generated__/types.ts:
    # ...

config:
  preResolveTypes: true

hooks:
  afterAllFileWrite:
    - prettier --write
  beforeDone:
    - touch a.txt
    - touch b.txt

```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

I expect both files `a.txt` and `b.txt` to be created. However, only `a.txt` is created

**Environment:**

- OS: MacOS Catalina 10.15.7
- ```    "@graphql-codegen/add": "^2.0.2",
    "@graphql-codegen/cli": "^1.21.5",
    "@graphql-codegen/import-types-preset": "^1.18.2",
    "@graphql-codegen/near-operation-file-preset": "^1.18.1",
    "@graphql-codegen/typescript": "^1.22.1",
    "@graphql-codegen/typescript-document-nodes": "^1.17.12",
    "@graphql-codegen/typescript-operations": "^1.18.0",
    "@graphql-codegen/typescript-react-apollo": "^2.2.5",
    "@graphql-codegen/typescript-resolvers": "^1.19.2",
``` 
- NodeJS: 14.17.0

**Additional context**
<!-- Add any other context about the problem here. -->
