### ISSUE TITLE
Different typing for input and output scalar

### ISSUE THREAD

**Issue by Sytten** [dotansimha/graphql-code-generator#6097]
Currently when mapping a scalar for server side typing, there is only a one-to-one relation. But in reality the scalar are usually more permissive in what they accept. For exemple, the `ID` scalar can serialize basically integers and even objects.
So it would be nice to be able to set a different type for input and output.

**Describe the solution you'd like**
Using the scalar map:
```yaml
config:
  scalars:
    ID: 
      input: string
      output: string | number
```

**Describe alternatives you've considered**
None at the moment, you have to cast it in the resolver.
