### ISSUE TITLE
Fragments do not combine arrays correctly

### ISSUE THREAD

**Issue by chrbala** [dotansimha/graphql-code-generator#6149]
**Describe the bug**
Including multiple fragments that contain the same arrays results in the types getting combined at the array level. TS doesn't know how to merge these correctly. That is ``Array<TypeA> & Array<TypeB>`` is not equivalent to ``Array<TypeA & TypeB>`` because TS doesn't merge arrays.

**To Reproduce**
This repro has the bug fully reproducible.

https://github.com/chrbala/apollo-bug-repro/tree/codegen-merge-arrays

1. My GraphQL schema:

```graphql
type Item {
  string: String!
  number: Int!
}

type Query {
  items: [Item!]!
}
```

2. My GraphQL operations:

```graphql
query Page {
  ...String
  ...Number
}

fragment String on Query {
  items {
    string
  }
}

fragment Number on Query {
  items {
    number
  }
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "src/schema.js"
documents: "src/**/*.tsx"
generates:
  src/generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
```

**Expected behavior**
You should be able to access both the ``string`` and ``number`` properties on ``items``, but you can only access string. If you switch the order of ``...String`` and ``...Number``, then you can only access number. 

The generated fragment is
```ts
export type PageQuery = (
  { __typename?: 'Query' }
  & NumberFragment
  & StringFragment
);
```

But for it to work correctly in TS, it would need to be more like
```
export type PageQuery = (
  { __typename?: 'Query' }
  & {
    items: Array<NumberFragment['items'][0] & StringFragment['items'][0]>
  }
);
```

**Environment:**

- OS: OSX 10.14.6
- Codegen
    "@graphql-codegen/cli": "1.21.5",
    "@graphql-codegen/introspection": "1.18.2",
    "@graphql-codegen/typescript": "1.22.1",
    "@graphql-codegen/typescript-operations": "1.18.0",
    "@graphql-codegen/typescript-react-apollo": "2.2.5",
- NodeJS: v12.13.1
