### ISSUE TITLE
maximum call stack size exceeded

### ISSUE THREAD

**Issue by jemink** [dotansimha/graphql-code-generator#6167]
I am getting below error while running graphql-codegen
```
$ graphql-codegen
  √ Parse configuration
  > Generate outputs
    > Generate hasura/schema.json
      √ Load GraphQL schemas
      √ Load GraphQL documents
      × Generate
        →         at C:/tests/graphql/user.graphql:20:29
    > Generate libs/graphql/generated/graphql.tsx
      √ Load GraphQL schemas
      √ Load GraphQL documents
      × Generate
        →         at C:/tests/graphql/user.graphql:20:29
Maximum call stack size exceeded
```
My codegen.yml config file:
```

overwrite: true
schema: hasura/schema.graphql
documents: ['libs/graphql/*.graphql', 'libs/graphql/crm-mutation/*.graphql']
generates:
  hasura/schema.json:
    plugins:
      - introspection
  libs/graphql/generated/graphql.tsx:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withHooks: true
      withRefetchFn: false
      withComponent: false
      withMutationOptionsType: true
      withMutationFn: true
      addDocBlocks: true
      addOperationExport: true
      withResultType: true
```
OS: Windows
"@graphql-codegen/add": "2.0.2",
"@graphql-codegen/cli": "1.21.2",
"@graphql-codegen/fragment-matcher": "2.0.1",
"@graphql-codegen/introspection": "1.18.2",
"@graphql-codegen/plugin-helpers": "1.18.3",
"@graphql-codegen/schema-ast": "1.18.1",
"@graphql-codegen/typescript": "1.21.1",
"@graphql-codegen/typescript-document-nodes": "1.17.10",
"@graphql-codegen/typescript-graphql-files-modules": "1.18.1",
"@graphql-codegen/typescript-operations": "1.17.15",
"@graphql-codegen/typescript-react-apollo": "2.2.3",
"@graphql-codegen/typescript-resolvers": "1.19.0",
node:- v14.15.4
