### ISSUE TITLE
[typescript-react-query] Argument of type 'Promise<TData>' is not assignable to parameter of type 'QueryFunction<TData, QueryKey>'.

### ISSUE THREAD

**Issue by iamyuu** [dotansimha/graphql-code-generator#6168]
**Describe the bug**
 
it's just a small bug, just need `() =>` before fetcher

When running `npx tsc` it throws an error and the error is in the generated file

<img width="1008" alt="Screen Shot 2021-06-22 at 15 52 05" src="https://user-images.githubusercontent.com/45778229/122894890-cd0eda80-d371-11eb-8dbb-8e692759f11f.png">

And when starting (Vite) dev server (not sure other module bundlers) in the console has an error: `Missing queryFn`

**To Reproduce**
- Init codegen
- Install and add `typescript-react-query`
- Config to use custom fetcher
- Add `tsconfig` file
- And then just generate

Check out reproduce: 
- [codesandbox](https://codesandbox.io/s/graphql-code-generator-react-query-reproduce-2wnmj?file=/types.ts:1330-1406)
- [repository](https://github.com/iamyuu/react-poc)

My `codegen.yml` config file:

```yml
overwrite: true
schema: 'http://localhost:8000/graphql'
documents: 'src/**/*.graphql'
generates:
  src/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-query
    config:
      fetcher:
        func: '../utils/api-client#graphqlRequest'
```

**Expected behavior**

Add `() =>` before custom fetch, after that the error will disappear

```diff
useQuery<ProfileQuery, TError, TData>(
	['profile', variables],
-	graphqlRequest<ProfileQuery, ProfileQueryVariables>(ProfileDocument, variables),
+	() => graphqlRequest<ProfileQuery, ProfileQueryVariables>(ProfileDocument, variables),
	options
);
```

**Environment:**

- `@graphql-codegen/typescript-react-query`: `1.3.3`
