### ISSUE TITLE
& in path causes .graphql files not to be found

### ISSUE THREAD

**Issue by WillSquire** [dotansimha/graphql-code-generator#6174]
**Describe the bug**
If an `&` character is the a parent directory that codegen is running in it will produce the error `Unable to find any GraphQL type definitions for the following pointers using schema file`.

**To Reproduce**
Put the whole project in a folder containing `&` character. I.e. `something & something` directory.

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

My `codegen.yml` config file:

```yml
overwrite: true
schema: "../schema/schema.graphql"
documents: "src/**/*.graphql"
generates:
  src/middleware/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
```

**Expected behavior**
Escape the `&` character properly in whatever part of the script is causing the issue...

**Environment:**

- OS: macOS
- NodeJS: v14.15.0
```
"@graphql-codegen/add": "2.0.2",
"@graphql-codegen/cli": "1.21.5",
"@graphql-codegen/typescript": "1.22.3",
"@graphql-codegen/typescript-operations": "1.18.2",
"@graphql-codegen/typescript-react-apollo": "2.2.7",
```
