### ISSUE TITLE
Duplicate identifier for gitlab graphql api

### ISSUE THREAD

**Issue by mantou132** [dotansimha/graphql-code-generator#6188]
Duplicate Identifier when I use Gitlab's GraphQL API, codegen.yml: 
```yml
generates:
  src/generated/operations.ts:
    # POST
    schema: https://gitlab.com/api/graphql
    documents: "src/services/*.graphql"
    hooks:
      afterOneFileWrite:
        - eslint --fix
    plugins:
      - typescript
      - typescript-operations
      - typescript-document-nodes
    config:
      maybeValue: T
      gqlImport: graphql-tag#gql
```

src/services/gitlab.graphql:
```
query getGroups {
  currentUser {
    name
    groupMemberships {
      edges {
        node {
          id
          group {
            id
            name
          }
        }
      }
    }
  }
}
```

<img width="842" alt="Screen Shot 2021-06-25 at 2 50 12 PM" src="https://user-images.githubusercontent.com/3841872/123382555-a72d4400-d5c4-11eb-933d-151727de160b.png">
