### ISSUE TITLE
Missing imports with dedupeFragments and file imports

### ISSUE THREAD

**Issue by ertrzyiks** [dotansimha/graphql-code-generator#6217]
**Describe the bug**

When I set `dedupeFragments: true` and use .graphql files with `#import `syntax, the generated typed document node refers to fragment docs that are not imported.

**To Reproduce**

https://codesandbox.io/s/romantic-gareth-q9tqv?file=/operations/document.ts

Note that `...MyGroupFragmentFragmentDoc.definitions` is injected to the definition but `MyGroupFragmentFragmentDoc` is not available in the generated module.

1. My GraphQL schema:

```graphql
schema {
  query: Query
}

type Query {
  animals: [Animal!]!
}

type Group {
  id: ID!
  name: String!
}
type Animal { 
  id: ID! 
  name: String!
  group: Group  
}
```

2. My GraphQL operations:

```graphql
#import "./fragments/MyAnimalFragment.graphql"

query Test {
  animals { ...MyAnimalFragment }
}
```

```graphql
#import "./fragments/MyGroupFragment.graphql"

fragment MyAnimalFragment on Animal {
  name
  group {
    ...MyGroupFragment
  }
}
```

```graphql
fragment MyGroupFragment on Group {
   id
   name
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: operations/**/*.graphql
generates:
  types.ts:        
    plugins:
      - typescript
    config:
      skipTypename: true

  operations:
    preset: 'near-operation-file'
    presetConfig:
      extension: '.ts'
      baseTypesPath: '../types'
        
    plugins:
      - typescript-operations
      - typed-document-node
    config:
      skipTypename: true
      dedupeFragments: true
      exportFragmentSpreadSubTypes: true

```

**Expected behavior**
Generated typed document imports all needed dependencies

**Environment:**
```
"@graphql-codegen/add": "1.13.3",
"@graphql-codegen/cli": "1.21.6",
"@graphql-codegen/near-operation-file-preset": "1.18.4",
"@graphql-codegen/typed-document-node": "1.18.9",
"@graphql-codegen/typescript": "1.22.4",
"@graphql-codegen/typescript-operations": "1.18.3",
```
