### ISSUE TITLE
urql-graphcache: 'schema' does not exist in type 'GraphCacheConfig' 

### ISSUE THREAD

**Issue by taneba** [dotansimha/graphql-code-generator#6228]
**Describe the bug**
Type error detected when pass an introspected schema to cacheExchange.

```
cacheExchange<GraphCacheConfig>({
  schema: introspection as IntrospectionData,  // -> type error: 'schema' does not exist in type 'GraphCacheConfig' 
```

**To Reproduce**

sandbox: https://codesandbox.io/s/nervous-ride-n7zrs?file=/index.ts

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
        email
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-urql-graphcache
```
4. pass your introspected schema to cacheExchange

```
  cacheExchange<GraphCacheConfig>({
    schema: schema as IntrospectionData,
  })
```

**Expected behavior**
Passing schema doesn't cause type error.

**Environment:**

-   "@graphql-codegen/add": "2.0.2"
-   "@graphql-codegen/cli": "1.20.1"
-   "@graphql-codegen/typescript": "1.21.0"
-   "@graphql-codegen/typescript-operations": "1.17.14"
-   "@graphql-codegen/typescript-urql-graphcache": "1.0.6"
-  "@urql/exchange-graphcache": "4.1.4"

- NodeJS: v14.16.1
