### ISSUE TITLE
Missing imports with dedupeFragments and nested fragments structure

### ISSUE THREAD

**Issue by ertrzyiks** [dotansimha/graphql-code-generator#6245]
**Describe the bug**
Follow-up to #6217

When I set dedupeFragments: true and use .graphql files with #import syntax, the generated typed document node refers to fragment docs that are not imported.

Since `@graphql-codegen/near-operation-file-preset@1.18.5-alpha-6aadbeff.0` it happens only in cases when we have a fragment importing another fragment with deep nesting level.

**To Reproduce**

https://codesandbox.io/s/gracious-sea-1ge8l?file=/operations/document.ts:1045-1076

1. My GraphQL schema:

```graphql
schema {
  query: Query
}

type Query {
  animals: [Animal!]!
}

type Group {
  id: ID!
  name: String!
}
type Animal { 
  id: ID! 
  name: String!
  group: Group  
}

```

2. My GraphQL operations:

**document.graphql**
```graphql
#import "./fragments/MyAnimalFragment.graphql"

query Test {
  animals { ...MyAnimalFragment }
}
```

**fragments/MyAnimalFragment.graphql**
```graphql
#import "./MyGroupFragment.graphql"

fragment MyAnimalFragment on Animal {
  name
  group {
    ...MyGroupFragment
  }
}
```

**fragments/MyGroupFragment.graphql**
```graphql
#import "./AnotherGroupFragment.graphql"

fragment MyGroupFragment on Group {
   ...AnotherGroupFragment
   name
}
```

**fragments/AnotherGroupFragment.graphql**
```graphql
fragment AnotherGroupFragment on Group {
   id
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: operations/**/*.graphql
generates:
  types.ts:        
    plugins:
      - typescript
    config:
      skipTypename: true

  operations:
    preset: 'near-operation-file'
    presetConfig:
      extension: '.ts'
      baseTypesPath: '../types'
        
    plugins:
      - typescript-operations
      - typed-document-node
    config:
      skipTypename: true
      dedupeFragments: true
      exportFragmentSpreadSubTypes: true

```

**Expected behavior**
All dependencies are imported in the generated file

**Environment:**
"@graphql-codegen/add": "1.13.3",
"@graphql-codegen/cli": "1.21.6",
"@graphql-codegen/near-operation-file-preset": "1.18.5-alpha-6aadbeff.0",
"@graphql-codegen/typed-document-node": "1.18.9",
"@graphql-codegen/typescript": "1.22.4",
"@graphql-codegen/typescript-operations": "1.18.3",

**Comment by dotansimha** [comment]
@ertrzyiks maybe we can continue the discussion on the original issue? it's still open :)

**Comment by dotansimha** [comment]
@ertrzyiks can you please try the alpha release from https://github.com/dotansimha/graphql-code-generator/pull/6290 ?

**Comment by ertrzyiks** [comment]
@dotansimha sure, I will check as soon as it's available. From what I see the alpha package is current missing https://github.com/dotansimha/graphql-code-generator/pull/6290#issuecomment-877768244

**Comment by ertrzyiks** [comment]
@dotansimha @gilgardosh confirmed, `@graphql-codegen/near-operation-file-preset@1.18.6-alpha-96980211a.0` works like a charm in my codebase

**Comment by rzane** [comment]
I was having the same issue, so I upgraded to `@graphql-codegen/near-operation-file-preset@1.18.6-alpha-96980211a.0`. I'm having a different issue now.

Here's a CodeSandbox that demonstrates what I'm seeing: https://codesandbox.io/s/gql-gen-issue-6245-0uyyf?file=/book.ts

#### schema.graphql
```graphql
type Address {
  city: String
}

type Author {
  address: Address
}

type Book {
  author: Author
}

type Query {
  book: Book
}
```

#### book.graphql
```graphql
fragment Book on Book {
  author {
    ...Author
  }
}

query Book {
  book {
    ...Book
  }
}
```

#### author.graphql
```graphql
fragment Address on Address {
  city
}

fragment Author on Author {
  address {
    ...Address
  }
}
```

#### codegen.yml
```yaml
schema: schema.graphql
generates:
  ./types.ts:
    plugins:
      - typescript
  ./:
    documents:
      - book.graphql
      - author.graphql
    preset: near-operation-file
    presetConfig:
      baseTypesPath: types
      extension: ".ts"
    plugins:
      - typescript-operations
      - typed-document-node
    config:
      dedupeFragments: true
```

The resulting `book.ts` references `AddressFragmentDoc`, but `AddressFragmentDoc` has not been imported.
