### ISSUE TITLE
TypeScript enum array plugin

### ISSUE THREAD

**Issue by marocchino** [dotansimha/graphql-code-generator#6258]
I need const generator for enum.

For example I have this schema.

```graphql
enum Permission {
  READ
  WRITE
  EXECUTE
}
```

and config like this:

```yaml
overwrite: true
schema: 'schema.graphql'
documents:
  - 'queries/*.graphql'
generates:
  generated-graphql.ts:
    plugins:
      - typescript:
          enumsAsTypes: true
  generated-const.ts:
    plugins:
      - typescript-enum-array:
          importFrom: './generated-graphql'
```

Then, this plugin will generate:

```ts
import { Permission } from 'somepath';

const PERMISSION: Permission[] = ['READ', 'WRITE', 'EXECUTE'];
```

This plugin will be useful when cast string to union types.
