### ISSUE TITLE
Documentation issue regarding programmatic usage

### ISSUE THREAD

**Issue by nmokkenstorm** [dotansimha/graphql-code-generator#6263]
**Describe the bug**
Programmatic usage of codegen in a Typescript/Node context doesn't work as documented: two required keys are missing and the fs module is not imported. I think the proper fix is to change the code, but right now the documentation is wrong.

**To Reproduce**
Copy [these examples](https://www.graphql-code-generator.com/docs/getting-started/programmatic-usage) in an index.ts file, and try to run it using `tsc && node index.ts`

1. My GraphQL schema:

```graphql
N/A
```

2. My GraphQL operations:

N/A

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "https://XXX/graphql.json"
documents: null
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
  ./graphql.schema.json:
    plugins:
      - "introspection"
```

**Expected behavior**
Types should be correct and/or reflect real world usage, fs should not fail

**Environment:**

- OS: macOS Big Sur 11.4
- "@graphql-codegen/cli": "1.21.6",
- "@graphql-codegen/introspection": "1.18.2",
- "@graphql-codegen/typescript": "1.22.4",
- NodeJS: v15.14.0

**Additional context**
[I made a PR here ](https://github.com/dotansimha/graphql-code-generator/pull/6264) to fix the documentation issue, but as mentioned I think the types _should_ be optional and the behaviour should reflect that. I'd be willing to amend my PR to reflect that.
