### ISSUE TITLE
All the fields are optional in resolvers

### ISSUE THREAD

**Issue by AndriaHRT** [dotansimha/graphql-code-generator#6280]
For this schema example:

```typescript
type FolderDashboard {
  id: ID!
  name: String!
  size: Int
}
```
Only `size` field is non-nullable (or optional).

So i have the generated corresponding interface where only `size` is optional _(expected)_:

```typescript
export interface FolderDashboard {
  readonly __typename?: 'FolderDashboard';
  readonly id: FieldWrapper<Scalars['ID']>;
  readonly name: FieldWrapper<Scalars['String']>;
  readonly size?: Maybe<FieldWrapper<Scalars['Int']>>;
}
```
But in the generated associated resolver all the fields are marked as optional:

```typescript
export type FolderDashboardResolvers<ContextType = Context, ParentType extends ResolversParentTypes['FolderDashboard'] = ResolversParentTypes['FolderDashboard']> = {
  id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  size?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
}
```

My config file:

```yml
overwrite: true
schema: ./src/graphql/schema.graphql
generates:
  src/graphql/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-resolvers"
    config:
      immutableTypes: true
      wrapFieldDefinitions: true
      allowParentTypeOverride: false
      contextType: ../../Context#Context
      declarationKind:
        type: "interface"
        input: "interface"
      mappers:
        User: ../models#UserModel
        Role: ../models#RoleModel
        Discussion: ../models#DiscussionModel
        MessageFile: ../models#FileModel
        Folder: ../models#FolderModel
        Message: ../models#MessageModel
        FolderPermission: ../models#PermissionModel
        PlacePermission: ../models#PlacePermissionModel
        DiscussionSeen: ../models#DiscussionSeenModel
        DocumentSeen: ../models#DocumentSeenModel
        Download: ../models#DownloadModel
        DueDate: ../models#DueDateModel
        GDriveMessage: ../models#GDriveMessageModel
        NotificationCenter: ../models#NotificationCenterModel
        TopicOperation: ../models#OperationModel
        Place: ../models#PlaceModel
        PublicFolder: ../models#FolderModel
        Todo: ../models#TodoModel
        TopicParticipant: ../models#TopicPermissionModel

```

 
**Solution expected**

So I'd like to have an option for having resolver fields having similar optional state as the type itself:

```typescript
export type FolderDashboardResolvers<ContextType = Context, ParentType extends ResolversParentTypes['FolderDashboard'] = ResolversParentTypes['FolderDashboard']> = {
  id: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
  name: Resolver<ResolversTypes['String'], ParentType, ContextType>;
  size?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
  __isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};
```

**Comment by dotansimha** [comment]
You can use `avoidOptionals` for that (https://www.graphql-code-generator.com/docs/plugins/typescript-resolvers)

**Comment by AndriaHRT** [comment]
@dotansimha It seems that these options make everything optional or non-optional (depending on the options), right?

**Comment by dotansimha** [comment]
> @dotansimha It seems that options in `avoidOptionals` make everything optional or non-optional (depending on the options), right?

Yeah, there are some customization and sub-configuration for that flag. Note that you can also customize it specifically for the `typescript-resolvers` plugin without effecting other plugins: 

```
plugins:
  - typescript
  - typescript-resolvers:
      avoidOptionals: true
```

Since resolvers are always optional in graphql-js, we don't have a way to enforce specific resolvers to be non-optionals.
