### ISSUE TITLE
Not compatible with graphql-config@3 when multiple projects are defined in the .graphqlrc.yml

### ISSUE THREAD

**Issue by waterdrop01** [dotansimha/graphql-code-generator#6282]
**Describe the bug**
here is the content of my `.graphqlrc.yml`:

```
projects:
  first:
    schema: ./first.graphql
    documents: ./src/first-gql.js
    extensions:
      codegen:
        generates:
        ./first.graphql:
          plugins:
            - schema-ast
      endpoints:
        default:
          url: https://first
  second:
    schema: ./second.graphql
    documents: ./src/second-gql.js
    extensions:
      codegen:
        generates:
        ./second.graphql:
          plugins:
            - schema-ast
      endpoints:
        default:
          url: https://second
```
But when running `npx codegen generate` it throws the error: 
```
Project 'default' not found
```
And if naming the first project `default`, then it throws the error:
```
✖ Parse configuration
    → Invalid Codegen Configuration!
    Generate outputs
  Invalid Codegen Configuration!

        Please make sure that your codegen config file contains the "generates" field, with a specification for the plugins you need.
        
        It should looks like that:

        schema:
          - my-schema.graphql
        generates:
          my-file.ts:
            - plugin1
            - plugin2
            - plugin3
```
And if moving the generate key up, then it throws:
```
Unable to find Codegen config file!
```
**Expected behavior**

I expect `graphql-code-generator` to fully support `graphql-config` options.

I'm currently solving this by creating one `project.codegen.yml` config file per project. But it's kind of de-deduplicating graphql config in two different places (which kind of defeat why graphql-config was created in the first place no? :)

**Environment:**

- OS: Ubuntu 20.04
- NodeJS: 16.4

Thanks for your help!

**Comment by FeliciaAKelley** [comment]
i agree.... Trying to fix this issue.. 

Graphql  works on fb base...

**Comment by dotansimha** [comment]
I think we look for the `default` project by default, can you please try to add `--project first` to your CLI command? Seems like we do support it (https://github.com/dotansimha/graphql-code-generator/blob/6a95377706eec019d04807f735d4cedc888c42d0/packages/graphql-codegen-cli/src/config.ts#L213)

**Comment by waterdrop01** [comment]
Ok, there's a catch 22 here:

For this config:
```
projects:
  first:
    schema: ./first.graphql
    documents: ./src/first-gql.js
    extensions:
      codegen:
        generates:
        ./first.graphql:
          plugins:
            - schema-ast
      endpoints:
        default:
          url: https://first
  second:
    schema: ./second.graphql
    documents: ./src/second-gql.js
    extensions:
      codegen:
        generates:
        ./second.graphql:
          plugins:
            - schema-ast
      endpoints:
        default:
          url: https://second
```
If I run `npx graphql-codegen generate --project first` it throws:
```
✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./first.graphql
      ✖ Load GraphQL schemas
        →           - ./first.graphql
        Load GraphQL documents
        Generate


 Found 1 error

  ✖ ./first.graphql
    Error: 
          Unable to find any GraphQL type definitions for the following pointers:
        
              - ./first.graphql
```
Now if I put the graphql endpoint url as the value of the `schema` field like this:
```
projects:
  first:
    schema: https://first
    documents: ./src/first-gql.js
    extensions:
      codegen:
        generates:
        ./first.graphql:
          plugins:
            - schema-ast
      endpoints:
        default:
          url: https://first
  second:
    schema: https://second
    documents: ./src/second-gql.js
    extensions:
      codegen:
        generates:
        ./second.graphql:
          plugins:
            - schema-ast
      endpoints:
        default:
          url: https://second
```
Then `npx graphql-codegen generate --project first` works! 

BUT, `npx eslint ./src/first-gql.js` throws an error now:
```
/home/me/code/github.com/project/repo/node_modules/node-fetch/lib/index.js:1222
                        throw new TypeError('Expected signal to be an instanceof AbortSignal');
                        ^

TypeError: Expected signal to be an instanceof AbortSignal
```
I guess that `graphql-code-generator` should generate from the `extenstion -> endpoint -> url` value instead?

My use case is pretty simple: **I want to regularly locally download latest version of the remote .graphql schema, in order to benefit from eslint warnings.** 

Preferably using one unified config file: `.graphqlrc.yml` :)

Thanks !

**Comment by dotansimha** [comment]
You can't use dependencies within codegen config outputs, since each one is standalone.
You can use separate config files for generating outputs that depends on each other.

**Comment by moshest** [comment]
It happened to me too. I would prefer if codegen can run on all projects when running `generate` or `watch`

**Comment by Urigo** [comment]
@moshest did you check the discussion here and saw if that helped you?
https://github.com/B2o5T/graphql-eslint/issues/526

**Comment by moshest** [comment]
Can't see how it relevant @Urigo...

I ended up using the default project as a workaround:

```yml
projects:
  # codegen is not supporting multiple projects yet:
  # https://github.com/dotansimha/graphql-code-generator/issues/6282
  default:
    schema: services/a-service/lib/schema.graphql
    extensions:
      codegen:
        generates:
          services/b-service/queries/graphql.codegen.tsx:
            schema: services/a-service/lib/schema2.graphql
            documents: 'services/b-service/**/*.graphql'
            plugins:
              - typescript
              - typescript-operations
              - typescript-resolvers
              - typescript-react-apollo
              - fragment-matcher
              - typescript-apollo-client-helpers

          services/c-service/src/queries/graphql.codegen.tsx:
            documents: 'services/c-service/src/**/*.graphql'
            plugins:
              - typescript
              - typescript-operations
              - typed-document-node

  b-service:
    schema: 'services/a-service/lib/schema2.graphql'
    documents: 'services/b-service/**/*.graphql'
    extensions:
      codegen:
        generates:
          services/b-service/queries/graphql.codegen.tsx:
            plugins:
              - typescript
              - typescript-operations
              - typescript-resolvers
              - typescript-react-apollo
              - fragment-matcher
              - typescript-apollo-client-helpers

  c-service:
    schema: 'services/c-service/lib/schema.graphql'
    documents: 'services/c-service/src/**/*.graphql'
    extensions:
      codegen:
        generates:
          services/c-service/src/queries/graphql.codegen.tsx:
            plugins:
              - typescript
              - typescript-operations
              - typed-document-node
```

It allows me to run `graphql-codegen` on the default project by default and if needed I can run it on specific project like this: `graphql-codegen --project b-service`

The only downside is that we have duplicate configuration on the default project. I really wish codegen will able to support this flow and merge all configuration to one if no project provided.
