### ISSUE TITLE
2 space tabs breaks `@graphql-codegen/add`

### ISSUE THREAD

**Issue by incompletude** [dotansimha/graphql-code-generator#6283]
Seems like a 2 space tab breaks `@graphql-codegen/add`.

This works

```
overwrite: true
schema: "schema"
documents: "src/operations/**/*.gql"
generates:
  src/operations/index.ts:
    plugins:
      - add:
            content: "/* eslint-disable */"
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      skipTypename: true
      withHooks: true
      withHOC: false
      withComponent: false

```

This don't 
`Configuration provided for 'add' plugin is invalid: "content" is missing!`

```
overwrite: true
schema: "schema"
documents: "src/operations/**/*.gql"
generates:
  src/operations/index.ts:
    plugins:
      - add:
          content: "/* eslint-disable */"
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      skipTypename: true
      withHooks: true
      withHOC: false
      withComponent: false

```
