### ISSUE TITLE
[typescript-resolvers] Unable to call resolvers in tests in version 1.20.0

### ISSUE THREAD

**Issue by mvanalphen** [dotansimha/graphql-code-generator#6310]
**Describe the bug**
Prior to version 1.20.0, we were able to import and call resolvers in our tests to verify their behaviour. However, as of version 1.20.0 of `typescript-resolvers`, we are no longer able to call the resolvers. 

I believe this may be a result of https://github.com/dotansimha/graphql-code-generator/pull/6281, which allows for resolvers to either be of type `ResolverFn` or `ResolverWithResolve`.

The following error is thrown:
```
This expression is not callable.
  Not all constituents of type 'Resolver<Maybe<ResolverTypeWrapper<Example>>, {}, Context, RequireFields<QueryExampleArgs, "input">>' are callable.
    Type 'ResolverWithResolve<Maybe<ResolverTypeWrapper<Example>>, {}, Context, RequireFields<QueryExampleArgs, "input">>' has no call signatures.
```

**To Reproduce**

My `codegen.yml` config file:

```yml
overwrite: true
schema: src/graphql/**/*.gql
documents: null
generates:
  src/generated/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
    config:
      contextType: ../config#Context
      federation: true
      namingConvention:
        enumValues: keep
      noSchemaStitching: true
      optionalInfoArgument: true
      useIndexSignature: true

hooks:
  afterAllFileWrite:
    - yarn prettier -w
    - yarn eslint --fix || true
```

**Expected behavior**
Ideally, we should be able to call our tests as we did in the past. Or is there some way to indicate that the resolvers are always of type `ResolverFn`?

**Environment:**

- OS: Windows 10
- `@graphql-codegen/typescript-resolvers`: 1.20.0 
- NodeJS: 14.15.0
