### ISSUE TITLE
Plugin Level configuration not validating in vscode

### ISSUE THREAD

**Issue by willsoto** [dotansimha/graphql-code-generator#6314]
**Describe the bug**

When adding configuration per plugin, the schema is considered invalid

<img width="673" alt="Screen Shot 2021-07-14 at 4 59 05 PM" src="https://user-images.githubusercontent.com/2791730/125692829-cbf2490d-13ce-4654-858f-8c83553a2dac.png">

**To Reproduce**

**Code sandbox doesn't seem to validate the schema, so no code sandbox applies**

1. My GraphQL schema:

Not applicable

2. My GraphQL operations:

Not applicable

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "src/core/graphql/schema.graphql"
# These are used to automatically generate the various React hooks we use from documents
documents:
  - "src/**/*.graphql"
hooks:
  afterOneFileWrite:
    - prettier --write

generates:
  src/core/graphql/schema.ts:
    - typescript:
        declarationKind: "interface"
        enumsAsTypes: true
        defaultScalarType: unknown
        skipTypename: true
    - "typescript-operations":
        declarationKind: "interface"
        avoidOptionals: true
        defaultScalarType: unknown
```

**Expected behavior**

I would expect to be able to get autocomplete / validation in vscode as [suggested in the documentation](https://www.graphql-code-generator.com/docs/getting-started/codegen-config) when inputting a valid config. The CLI command generates the correct output, so the config is technically correct, it's just the YAML schema that doesn't seem to support [plugin level configuration](https://www.graphql-code-generator.com/docs/getting-started/config-field#plugin-level)

**Environment:**

- OS: MacOS
- `@graphql-codegen/...`: 
```
"@graphql-codegen/cli": "~1.21.7",
"@graphql-codegen/typescript": "~1.23.0",
"@graphql-codegen/typescript-operations": "~1.18.4",
```

- NodeJS: v14.17.0

**Additional context**
Using [RedHat YAML plugin](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) as suggested by docs. v0.21.1 which is the latest version at the time of this writing.
