### ISSUE TITLE
Getting error on codegen

### ISSUE THREAD

**Issue by FBurner** [dotansimha/graphql-code-generator#6338]
**Describe the bug**
Getting error:     Unable to find any GraphQL type definitions for the following pointers:

**To Reproduce**
Use url graphql done with nestjs 
having following codeyen.yml
```
# Endpoint API, the following URL is a example
schema: https://jobs-api-gateway.breitseite-dev.io/graphql
overwrite: true
# Format files
hooks:
  afterAllFileWrite:
    - prettier --write
generates:
  # Get schemas from server
  src/queries/autogenerate/schemas.tsx:
    documents: 'src/queries/**/**.gql'
    plugins:
      - typescript
  # Create operations based on queries
  src/queries/autogenerate/operations.tsx:
    documents: 'src/queries/**/**.gql'
    preset: import-types
    presetConfig:
      typesPath: ./schemas
    plugins:
      - typescript-operations
  # 1. Export GraphQL documents
  # 2. React interface
  src/queries/autogenerate/hooks.tsx:
    documents: 'src/queries/**/**.gql'
    preset: import-types
    presetConfig:
      typesPath: ./operations
    plugins:
      - typescript-react-apollo
    config:
      # Optionals
      withHOC: false
      withComponent: false
      withHooks: true
```

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
input AddPositionLocationInput {
  _id: String!
  positionLocation: CreatePositionLocationInput!
}

type Address {
  postalCode: String
  name: String
  formattedAddress: String
  countrySubDivisions: [String!]
}

input AddressListInput {
  type: String!
  postalCode: String!
  addressLocality: String!
}

type Amount {
  value: Float!
  currency: String!
}

type CareerLevel {
  id: Id
}

type Communication {
  _id: String!
  phone: [Phone!]
  address: [Address!]
  email: [Email!]
}

type CountrySubDivisions {
  type: String
  value: String
}

input CreateAddressInput {
  type: String!
  postalCode: String!
  addressLocality: String!
}

input CreateAmountInput {
  value: Float!
  currency: String!
}

input CreateCareerLevelInput {
  id: CreateIdInput!
}

input CreateCommunicationInput {
  phone: [CreatePhoneInput!]
  address: [CreateAddressInput!]
  email: [CreateEmailInput!]
}

input CreateEmailInput {
  address: String
  name: String
  useCode: String
}

input CreateGeoLocationInput {
  latitude: Float
  longitude: Float
}

input CreateIdInput {
  value: String!
}

input CreateJobListInput {
  jobs: [String!]!
}

input CreateNameInput {
  given: String
  family: String
}

input CreateOfferedRemunerationPackageInput {
  range: CreateRangeInput!
}

input CreateOrganizationInput {
  name: String
  communication: CreateCommunicationInput
  description: CreateAddressInput
  users: [CreateUserInput!]
}

input CreatePersonContactInput {
  primaryLanguage: String
  name: CreateNameInput
}

input CreatePhoneInput {
  formattedNumber: String
  name: String
  areaDialingCode: String
  countryDialingCode: String
  phoneExtension: String
  dialNumber: String
}

input CreatePositionLocationInput {
  postalCode: String!
  line: String!
  countryCode: String!
  city: String!
  formattedAddress: String
  geoLocation: CreateGeoLocationInput
}

input CreatePositionProfileInput {
  profileName: String!
  careerLevels: [CreateCareerLevelInput!]!
  positionLocation: [CreatePositionLocationInput!]!
  offeredRemunerationPackage: CreateOfferedRemunerationPackageInput!
  user: UserInput!
}

input CreateRangeInput {
  minimumAmount: CreateAmountInput!
  maximumAmount: CreateAmountInput!
}

input CreateUserInput {
  primaryLanguage: String
  name: CreateNameInput
}

# A date-time string at UTC, such as 2019-12-03T09:54:33Z, compliant with the date-time format.
scalar DateTime

type Email {
  address: String
  name: String
  useCode: String
}

type ExtendedPositionClassifications {
  name: String
  value: String
  countryCode: String
}

type GeoLocation {
  latitude: Float
  longitude: Float
}

type Id {
  value: String
  agencyUri: String
  description: String
  schemeVersionId: String
  schemeLink: String
  schemeAgencyId: String
}

input IntSelectorInput {
  gt: Int!
  lt: Int!
}

type JobCategories {
  id: Id
}

type JobList {
  _id: ID!
  jobs: [PositionProfile!]!
}

input ListJobLocationInput {
  _id: String!
  address: AddressListInput!
  longitude: Int!
  latitude: Int!
}

input ListOrganisationWhereInput {
  name: StringSelectorInput!
}

input ListPersonContactInput {
  name: StringSelectorInput!
}

input ListPositionProfileWhereInput {
  baseSalary: IntSelectorInput!
  title: StringSelectorInput!
  _id: StringSelectorInput!
}

input ListUserWhereInput {
  name: StringSelectorInput!
}

type Mutation {
  createOneUser(input: CreateUserInput!): User!
  addPhoneToUser(createPhoneInput: CreatePhoneInput!, id: String!): Phone!
  createOneOrganisation(input: CreateOrganizationInput!): Organisation!
  addUserToOrganisation(userId: String!, id: String!): User!
  createOnePersonContact(input: CreatePersonContactInput!): PersonContact!
  createOneJob(input: CreatePositionProfileInput!): PositionProfile!
  addLocation(
    addPositionLocationInput: AddPositionLocationInput!
  ): PositionLocation!
  createOneJobList(input: CreateJobListInput!): JobList!
  createOneJobLocation(payload: CreatePositionLocationInput!): PositionLocation!
  updateOneJobLocation(payload: UpdateJobLocationInput!): PositionLocation!
  deleteJobLocation(_id: String!): PositionLocation!
}

type Name {
  given: String
  family: String
}

type OfferedRemunerationPackage {
  range: Range
}

type Organisation {
  _id: ID!
  name: String
  communication: Communication
  users(populate: Boolean!): [User!]
}

type PersonContact {
  _id: ID!
  name: Name
  communication(populate: Boolean!): Communication!
}

type Phone {
  formattedNumber: String
  name: String
  areaDialingCode: String
  countryDialingCode: String
  phoneExtension: String
  dialNumber: String
}

type PositionClassification {
  _id: String!
  extendedPositionClassifications: [ExtendedPositionClassifications!]
}

type PositionLocation {
  _id: String!
  name: String
  line: String
  postalCode: String
  countryCode: String
  city: String!
  formattedAddress: String
  referenceLocation: String
  geoLocation: GeoLocation
  countrySubDivisions: [CountrySubDivisions!]
  created: DateTime!
  updated: DateTime!
}

type PositionProfile {
  _id: String!
  profileName: String
  careerLevels: [CareerLevel!]
  positionClassification: PositionClassification
  alternateIds: [Id!]
  jobCategories: [JobCategories!]
  relocation: Relocation
  travel: Travel
  user: User!
  remoteWork: RemoteWork
  shiftSchedules: [ShiftSchedule!]
  positionOfferingTypes: [String!]
  offeredRemunerationPackage: OfferedRemunerationPackage!
  positionLocation(populate: Boolean!): [PositionLocation!]
  created: DateTime!
  updated: DateTime!
}

type Query {
  listUsers(where: ListUserWhereInput): [User!]!
  getUserById(_id: String!): User!
  listOrganisations(where: ListOrganisationWhereInput): [Organisation!]!
  getOrganisationById(_id: String!): Organisation!
  listPersonContacts(where: ListPersonContactInput): [PersonContact!]!
  getPersonContactById(_id: String!): PersonContact!
  listJobs(where: ListPositionProfileWhereInput): [PositionProfile!]!
  getJobById(_id: String!): PositionProfile!
  listJobLists: [JobList!]!
  getJobListById(_id: String!): JobList!
  jobLocation(_id: String!): PositionLocation!
  jobLocations(filters: ListJobLocationInput): PositionLocation!
}

type Range {
  minimumAmount: Amount
  maximumAmount: Amount
}

type Relocation {
  willingToRelocateIndicator: Boolean
  descriptions: [String!]
}

type RemoteWork {
  restrictionDetails: String
  remoteWorkIndicator: Boolean
  remoteEligibilityRequirement: String
  workLocationCodes: [String!]
}

type ShiftSchedule {
  code: String
  id: Id
}

input StringSelectorInput {
  in: [String!]!
  eq: String!
}

type Travel {
  descriptions: [String!]
}

input UpdateJobLocationInput {
  postalCode: String
  line: String
  countryCode: String
  city: String
  formattedAddress: String
  geoLocation: CreateGeoLocationInput
  _id: String!
}

type User {
  _id: ID!
  name: Name
  communication(populate: Boolean!): Communication
}

input UserInput {
  _id: String!
}

```

2. My GraphQL operations:
dont know what you mean by graphl operation


3. My `codegen.yml` config file:

```yml
# Endpoint API, the following URL is a example
schema: https://jobs-api-gateway.breitseite-dev.io/graphql
overwrite: true
# Format files
hooks:
  afterAllFileWrite:
    - prettier --write
generates:
  # Get schemas from server
  src/queries/autogenerate/schemas.tsx:
    documents: 'src/queries/**/**.gql'
    plugins:
      - typescript
  # Create operations based on queries
  src/queries/autogenerate/operations.tsx:
    documents: 'src/queries/**/**.gql'
    preset: import-types
    presetConfig:
      typesPath: ./schemas
    plugins:
      - typescript-operations
  # 1. Export GraphQL documents
  # 2. React interface
  src/queries/autogenerate/hooks.tsx:
    documents: 'src/queries/**/**.gql'
    preset: import-types
    presetConfig:
      typesPath: ./operations
    plugins:
      - typescript-react-apollo
    config:
      # Optionals
      withHOC: false
      withComponent: false
      withHooks: true
```

**Expected behavior**
Genreating react hooks

**Environment:**

- OS: ubuntu 
-  "@graphql-codegen/cli": "^1.21.7",
    "@graphql-codegen/import-types-preset": "^1.18.6",
    "@graphql-codegen/typescript": "^1.23.0",
    "@graphql-codegen/typescript-operations": "^1.18.4",
    "@graphql-codegen/typescript-react-apollo": "^2.3.1",
- NodeJS: 14
