### ISSUE TITLE
SyntaxError: Identifier 'builders' has already been declared (9:3)

### ISSUE THREAD

**Issue by eden-lane** [dotansimha/graphql-code-generator#6339]
**Describe the bug**
I'm trying to generate code from my ts files with graphql queries, but I get this error:
```
SyntaxError: Identifier 'builders' has already been declared (9:3)
        at Object._raise (/usr/src/app/client/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:776:17)
        at Object.raiseWithData (/usr/src/app/client/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:769:17)
        at Object.raise (/usr/src/app/client/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:737:17)
        at TypeScriptScopeHandler.checkRedeclarationInScope (/usr/src/app/client/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:1392:
12)
        at TypeScriptScopeHandler.declareName (/usr/src/app/client/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:1358:12)
        at TypeScriptScopeHandler.declareName (/usr/src/app/client/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:5081:11)
        at Object.checkLVal (/usr/src/app/client/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:9742:24)
        at Object.checkLVal (/usr/src/app/client/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:7298:15)
        at Object.parseVarId (/usr/src/app/client/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:12531:10)
        at Object.parseVarId (/usr/src/app/client/node_modules/@graphql-tools/graphql-tag-pluck/node_modules/@babel/parser/lib/index.js:7126:11)
```

**To Reproduce**
I've tried to reproduce the error, but I got a new one. in codesandbox I get
```
TypeError: Cannot read property 'buildError' of undefined
```
https://codesandbox.io/s/zen-platform-dowef?file=/schema.gql

2. My GraphQL operations:
```ts
import { gql } from '@apollo/client';

export const FULL_TASK = gql`
  fragment FullTask on Task {
    id
    title
    isCompleted
    isStarred
    atMyDay
    startDate
    startDateTime
    endDate
    endDateTime
    rrule
    missing
    recurringTaskId
    project {
      id
      title
      icon
      color
      backgroundColor
    }
  }
`;

```

```ts
import { gql } from '@apollo/client';

export const DELETE_TASK_MUTATION = gql`
  mutation deleteTask($taskId: String!) {
    deleteTask(taskId: $taskId) {
      ...FullTask
    }
  }
`;

```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "./schema.gql"
documents:
  - "./**/*.gql"
  - "./**/*.ts"
generates:
  generated.tsx:
    schema: "http://server:3000/graphql"
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"

```

**Expected behavior**
It should generate code without any errors

**Environment:**

```
"@apollo/client": "3.3.11",
"@graphql-codegen/cli": "1.21.4",
"@graphql-codegen/introspection": "1.18.1",
"@graphql-codegen/typescript": "1.21.0",
"@graphql-codegen/typescript-operations": "1.17.14",
"@graphql-codegen/typescript-react-apollo": "2.2.1",
```

**Comment by domanskyi** [comment]
Have the same error:
package.json:
```
    "@graphql-codegen/cli": "^1.21.7",
    "@graphql-codegen/fragment-matcher": "^2.0.1",
    "@graphql-codegen/introspection": "^1.18.2",
    "@graphql-codegen/typescript": "^1.23.0",
    "@graphql-codegen/typescript-document-nodes": "^1.17.16",
    "@graphql-codegen/typescript-graphql-files-modules": "^1.18.1",
    "@graphql-codegen/typescript-operations": "^1.18.4",
    "@graphql-codegen/typescript-react-apollo": "^2.3.1",
    "@graphql-codegen/urql-introspection": "^1.3.1",
```
codegen.yml:
```yml
overwrite: true
schema: 'http://p8.local/escheriql'
documents: './**/*.{tsx,ts}'
generates:
  '@types/escher-schema.d.ts':
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
      - 'typescript-graphql-files-modules'
      - 'typescript-document-nodes'
      - 'fragment-matcher'
      - 'urql-introspection'
    config:
      noExport: true
```
query example:
```js
export const QUERY= gql`
  query GetStarBySlug($slug: String!) {
    allArtists(slug: $slug, status: "public") {
      edges {
        node {
          id
        }
      }
    }
  }
`
```
