### ISSUE TITLE
typescript-react-query: dedupeOperationSuffix doesn't dedupe hook names

### ISSUE THREAD

**Issue by nbudin** [dotansimha/graphql-code-generator#6368]
**Describe the bug**
When using the react-query plugin, the generated hooks don't respect the `dedupeOperationSuffix` config option.  For example, a query called `NotificationsQuery` will result in a hook called `useNotificationsQueryQuery`, even with `dedupeOperationSuffix` set to true.

**To Reproduce**

https://codesandbox.io/s/react-query-operation-suffix-deduping-bug-repro-c8r58

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```graphql
query UserQuery {
    user(id: 1) {
        id
        username
        email
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-query
    config:
      dedupeOperationSuffix: true
```

**Expected behavior**
I expect it to generate a hook called `useUserQuery`, but it instead generates a hook called `useUserQueryQuery`.

**Environment:**

- OS: macOS 11.5.1
- `@graphql-codegen/typescript-react-query`: 1.3.5
- NodeJS: 14.16.1

**Additional context**
I have a potential fix for the issue in a fork: https://github.com/nbudin/graphql-code-generator/commit/8c9a37f40de7ecd6364e8aef9c4e01d0aeca9338
