### ISSUE TITLE
Using dedupeFragments on schemas with nested types results in duplicated fragments

### ISSUE THREAD

**Issue by desbrowne** [dotansimha/graphql-code-generator#6381]
**Describe the bug**
I have a schema that has a type (Person) nested at multiple places. The output includes duplicated fragments when using `dedupeFragments: true`. I'm using `@graphql-codegen/near-operation-file-preset@1.18.6`

**To Reproduce**

https://codesandbox.io/s/gql-gen-issue-dedup-iu026?file=/meeting.graphql

1. My GraphQL schema:

```graphql
type Person {
  name: String!
  email: String!
  phone: String
}

type Team {
  name: String!
  people: [Person!]!
}

type Meeting {
  name: String!
  people: [Person!]!
  team: Team!
}

type Query {
  meeting: Meeting!
}
```

2. My GraphQL operations:

**meeting.graphql**
```graphql
query {
  meeting {
    ...Meeting
  }
}

fragment Meeting on Meeting {
  name
  people {
    ...Person
  }
  team {
    ...Team
  }
}
```

**team.graphql**
```graphql
fragment Team on Team {
  name
  people {
    ...Person
  }
}
```

**person.graphql**
```graphql
fragment Person on Person {
  name
  email
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
generates:
  ./types.ts:
    plugins:
      - typescript
  ./:
    documents:
      - meeting.graphql
      - team.graphql
      - person.graphql
    preset: near-operation-file
    presetConfig:
      baseTypesPath: types
      extension: ".ts"
    plugins:
      - typescript-operations
      - typescript-urql
    config:
      dedupeFragments: true
```

**Expected behavior**
Fragments are not duplicated. 

Maybe the fragments should be included only in the operations, not in other fragments?

**Environment:**
"@graphql-codegen/cli": "1.21.8",
"@graphql-codegen/near-operation-file-preset": "1.18.6",
"@graphql-codegen/typescript": "1.23.0",
"@graphql-codegen/typescript-operations": "1.18.4",
"@graphql-codegen/typescript-urql": "2.0.11",
"@graphql-typed-document-node/core": "3.1.0",
"graphql": "15.5.1",
"graphql-tag": "2.12.5",
"typescript": "4.3.5"

**Additional context**

**team.ts** includes `PersonFragmentDoc`
```ts
export const TeamFragmentDoc = gql`
    fragment Team on Team {
  name
  people {
    ...Person
  }
}
    ${PersonFragmentDoc}`;
```

In **meeting.ts** `PersonFragmentDoc` and `TeamFragmentDoc` are included in the doc and fragment. `TeamFragmentDoc` also includes `PersonFragmentDoc`, leading to multiple duplicate fragments in `Document`. 
```ts
export const MeetingFragmentDoc = gql`
    fragment Meeting on Meeting {
  name
  people {
    ...Person
  }
  team {
    ...Team
  }
}
    ${PersonFragmentDoc}
${TeamFragmentDoc}`;
export const Document = gql`
    {
  meeting {
    ...Meeting
  }
}
    ${MeetingFragmentDoc}
${PersonFragmentDoc}
${TeamFragmentDoc}`;
```
