### ISSUE TITLE
Manually sort fields

### ISSUE THREAD

**Issue by canac** [dotansimha/graphql-code-generator#6427]
I'm using the [MongoDB Realm GraphQL API](https://docs.mongodb.com/realm/graphql/) in my app. For some reason, the field order in its introspection API is unstable. It returns the fields in a different order every time it is queried. That makes my generated codegen file change with every run just to reorder the fields even when there are no real changes.

**Describe the solution you'd like**
I would like to have a way to manually specify a sort order on the types and fields returned from the introspection order. The sort order could just be a simple lexicographical sort. It just needs to be stable.

I'm not familiar with this codebase, but if the maintainers are OK with this addition and can point me in the right direction, I'd be willing to put together a PR for it.

**Describe alternatives you've considered**
Since I don't have control over the API, I can't add sorting on the GraphQL server level. Fixing at the gql-codegen level is the only option.

**Additional context**
Here's the relevant parts of my `config.yml`:

```yml
overwrite: true
schema:
  - https://realm.mongodb.com/api/client/v2.0/app/bible-reading-dkzas/graphql:
      headers:
        apiKey: pAYdlNmjB6bJlYgeWoPg7SYFZeeEaugHrPzIBv44FWVWnmuk4mIfaPSgBaoAw5v1
generates:
  src/generated/graphql.ts:
    plugins:
      - typescript
```
