### ISSUE TITLE
v2: generating code only for the last query inside a file

### ISSUE THREAD

**Issue by violabg** [dotansimha/graphql-code-generator#6439]
I have a ts file with multiple queries like this

```ts
import { gql } from "graphql-request";

export const GET_EVENTS = gql`
  query getEvents {
    events {
      items {
        id
        slug
        title
      }
    }
  }
`;

export const GET_EVENTS_BY_SLUG = gql`
  query getEventsBySlug($slug: String) {
    events(slug: $slug) {
      items {
        code
        description
        end_date
        hero_image
        id
        main_video
        slug
        start_date
        title
        sessions {
          description
          end_date
          host_name
          id
          start_date
          title
          webex_id
          webex_pass
        }
      }
    }
  }
`;

export const GET_IMAGE_BY_ID = gql`
  query getImageById($id: Int!) {
    image(id: $id) {
      id
      image
      src
      title
    }
  }
`;
export const GET_FILE_BY_ID = gql`
  query getFileById($id: Int!) {
    file(id: $id) {
      id
      src
      title
    }
  }
`;
export const GET_LINK_BY_ID = gql`
  query getLinkById($id: Int!) {
    link(id: $id) {
      href
      id
      target
      title
    }
  }
`;
export const GET_MODELTHREED_BY_ID = gql`
  query getModelthreedById($id: Int!) {
    modelthreed(id: $id) {
      id
      src
      title
    }
  }
`;
```

my codegen.yml is like this:

```yml
overwrite: true
schema: ".../tetrapak_graphql"
documents:
  - "src/gql/**/!(*.generated).{ts,tsx}"
generates:
  src/gql/generated-types.ts: 
    plugins: 
      - "typescript"
  src/gql/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: generated-types.ts
    plugins:
      - "typescript-operations"
      - "typescript-react-query"
    config:
      fetcher: graphql-request
      exposeQueryKeys: true

```

before **version 2** my generated files had the code for all queries, but since **version 2**, the generated files contains only the code for the last query, in the case above **getModelthreedById**

```ts
import * as Types from '../../generated-types';

import { GraphQLClient } from 'graphql-request';
import { useQuery, UseQueryOptions } from 'react-query';

function fetcher<TData, TVariables>(client: GraphQLClient, query: string, variables?: TVariables) {
  return async (): Promise<TData> => client.request<TData, TVariables>(query, variables);
}
export type GetModelthreedByIdQueryVariables = Types.Exact<{
  id: Types.Scalars['Int'];
}>;


export type GetModelthreedByIdQuery = { __typename?: 'Query', modelthreed?: Types.Maybe<{ __typename?: 'Modelthreed', id: number, src?: Types.Maybe<string>, title?: Types.Maybe<string> }> };


export const GetModelthreedByIdDocument = `
    query getModelthreedById($id: Int!) {
  modelthreed(id: $id) {
    id
    src
    title
  }
}
    `;
export const useGetModelthreedByIdQuery = <
      TData = GetModelthreedByIdQuery,
      TError = unknown
    >(
      client: GraphQLClient, 
      variables: GetModelthreedByIdQueryVariables, 
      options?: UseQueryOptions<GetModelthreedByIdQuery, TError, TData>
    ) => 
    useQuery<GetModelthreedByIdQuery, TError, TData>(
      ['getModelthreedById', variables],
      fetcher<GetModelthreedByIdQuery, GetModelthreedByIdQueryVariables>(client, GetModelthreedByIdDocument, variables),
      options
    );
useGetModelthreedByIdQuery.getKey = (variables: GetModelthreedByIdQueryVariables) => ['getModelthreedById', variables];
```

is there a new way to configure the codegen.yml or is a bug?

woking in 

"@graphql-codegen/cli": "^1.21.8",
    "@graphql-codegen/introspection": "^1.18.2",
    "@graphql-codegen/near-operation-file-preset": "^1.18.6",
    "@graphql-codegen/typescript": "^1.23.0",
    "@graphql-codegen/typescript-operations": "^1.18.4",
    "@graphql-codegen/typescript-react-query": "^1.3.5",

not working with

"@graphql-codegen/cli": "^2.0.1",
    "@graphql-codegen/introspection": "^2.0.0",
    "@graphql-codegen/near-operation-file-preset": "^2.0.0",
    "@graphql-codegen/typescript": "^2.0.0",
    "@graphql-codegen/typescript-operations": "^2.0.1",
    "@graphql-codegen/typescript-react-query": "^2.0.0",</div>
