### ISSUE TITLE
With near-operation-file-preset, graphql-code-generator generates imports of fragment declared in same .ts file

### ISSUE THREAD

**Issue by nbudin** [dotansimha/graphql-code-generator#6520]
If a fragment is declared and used in the same .ts file, `near-operation-file-preset` seems to cause graphql-code-generator to put a self-import at the top of the generated operations file.  So far I have tried this with `typescript-graphql-request`, `typescript-react-apollo`, and `typescript-react-query`, and they all exhibit this same behavior, so I think it's happening at a deeper level, possibly in `plugin-helpers`.

For example, with `typescript-graphql-request`, we get the following (irrelevant generated code omitted):

```typescript
import { UserFieldsFragmentDoc } from './document.generated';
export type UserFieldsFragment = { __typename?: 'User', username: string, email: string };

export type UserQueryVariables = Types.Exact<{ [key: string]: never; }>;


export type UserQuery = { __typename?: 'Query', user: { __typename?: 'User', id: string, username: string, email: string } };

export const UserFieldsFragmentDoc = gql`
    fragment userFields on User {
  username
  email
}
    `;
```

Note that UserFieldsFragmentDoc is imported _from this file_ and then declared later on in the file.  TypeScript considers this an error.

**To Reproduce**
I've reproduced this behavior in https://codesandbox.io/s/stoic-minsky-0l3bg.

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```typescript
import { gql } from "@apollo/client";

export const userFields = gql`
  fragment userFields on User {
    username
    email
  }
`;

export const userQuery = gql`
  query user {
    user(id: 1) {
      id
      ...userFields
    }
  }

  ${userFields}
`;
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.ts
generates:
  types.generated.ts:
    plugins:
      - typescript
  .:
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: types.ts
    plugins:
      - typescript-operations
      - typescript-graphql-request
```

**Expected behavior**
I expected it to generate code that would compile, but it didn't (because the code imported `userFragment` from itself and then declared it as an exported const).

**Environment:**

- OS: macOS 11.5.1
- `@graphql-codegen/cli`: 2.1.1
- `@graphql-codegen/near-operation-file-preset`: 2.1.0
- `@graphql-codegen/typescript`: 2.1.0
- `@graphql-codegen/typescript-graphql-request`: 4.1.0
- `@graphql-codegen/typescript-operations`: 2.1.0
- NodeJS: 14.16.1

**Additional context**
I've submitted a PR with a fix: #6522
