### ISSUE TITLE
schema-ast does not comment descriptions at the same time as including directives

### ISSUE THREAD

**Issue by mstykow** [dotansimha/graphql-code-generator#6529]
**Describe the bug**
As soon as `includeDirectives` is set to true, the value of `commentDescriptions` no longer matters: comments will always be generated as docstrings.

**To Reproduce**
```
overwrite: true
schema:
  - './graph/**/*.graphql'
  - '!./graph/schema.graphql'
generates:
  ./graph/schema.graphql:
    plugins:
      - 'schema-ast'
      - add:
          content:
            - '/**'
            - ' * NOTE: THIS IS AN AUTO-GENERATED FILE. DO NOT MODIFY DIRECTLY.'
            - ' */'
    config:
      commentDescriptions: true
      includeDirectives: true
```

**Expected behavior**
It is possible to include directives and comment descriptions at the same time.

**Environment:**

- OS: Ubuntu 20.04
"@graphql-codegen/add": "^2.0.2",
"@graphql-codegen/cli": "^1.21.6",
"@graphql-codegen/fragment-matcher": "^2.0.1",
"@graphql-codegen/schema-ast": "^2.1.0",
"@graphql-codegen/typed-document-node": "^1.18.9",
"@graphql-codegen/typescript": "^1.22.4",
"@graphql-codegen/typescript-apollo-client-helpers": "^1.1.9",
"@graphql-codegen/typescript-operations": "^1.18.3",
"@graphql-codegen/typescript-react-apollo": "^2.3.0",
"graphql": "^15.5.1",
- NodeJS: 14.x
