### ISSUE TITLE
Cannot generate types if ```typeDefs``` are imported from local package monorepo

### ISSUE THREAD

**Issue by sunaulo-suhail** [dotansimha/graphql-code-generator#6531]
**Describe the bug**
I am using monorepo where I have to share the **type definitions** between packages. So I have defined common graphql type definition in a separate package. But while generating the schema ```code-generator``` could not find the schemas imported from the shared module.

**To Reproduce**
1. Create a monorepo with a **shared** packages let's say ```@demo/schema```  and a application package let's say ```@demo/web```
2. Add ```@demo/schema``` to ```@demo/web```
3. Create a simple enum let's say ```UserRole``` inside ```@demo/schema``` and build the ```@demo/schema``` shared package
4. Create a simple **apollo-server** inside ```@demo/web``` and import that **enum** in ```@demo/web``` and simply run the server.
5. Run the apollo server
6. Generate the schema with the following config
  ```yml
  # all the juicy stuff
  schema: http://localhost:3000
  # all other juicy stuff
  ```
7. This should work but when running with the following config it won't work
  ```yml
  # all the juicy stuff
  schema:
    - "./packages/web-api/schema/*.ts":
        noRequire: true
  # all other juicy stuff
  ```

### Code Sanobx link: [Sandbox](https://codesandbox.io/s/unruffled-shannon-2ie9j?file=/package.json)

My `codegen.yml` config file:

```yml
schema: 
  - "./packages/web-api/schema/*.ts":
      noRequire: true
generates:
  ./packages/web-api/generated.ts:
    plugins:
      - typescript
      - typescript-resolvers
```

**Expected behavior**

**Environment:**

- OS: Linux/Mac
- `@graphql-codegen/cli`: 1.20.0
- `@graphql-codegen/typescript`: 1.21.0
- `@graphql-codegen/typescript`: 1.17.4
- NodeJS: 

**Additional context**
Please help me with this.
