### ISSUE TITLE
Double type when type and extend type are in the same module

### ISSUE THREAD

**Issue by jycouet** [dotansimha/graphql-code-generator#6534]
**Describe the bug**
I'm in a graphQL module context, and my `codegen.yml` look like:
```yml
generates:
  ./packages/api/src/graphql-modules/:
    preset: graphql-modules
    presetConfig:
      baseTypesPath: ../_gen/graphql.ts
      filename: _gen/module-types.ts
    plugins:
      - typescript
      - typescript-resolvers
```

I have one file `TYPE.AccountGroup.gql`
```gql
type AccountGroup {
  id: String
  nom: String
}
```

AND
another one  `EX_TYPE.AccountGroup.accounts.gql`
```gql
extend type AccountGroup {
  accounts: [Account!]!
}
```

After the code gen run, in _gen/module-types.ts, I have the type AccountGroup twice :open_mouth: .

I think that it's coming by the fact that in the same module, the type and an extension as well!

**To Reproduce**
I created a repo: https://github.com/jycouet/sveltekit-modules/tree/fix/codeGen
