### ISSUE TITLE
Missing dependency in @graphql-codegen/plugin-helpers

### ISSUE THREAD

**Issue by kubijo** [dotansimha/graphql-code-generator#6542]
**Describe the bug**
You have a broken dependency tree (at least) for the package `@graphql-codegen/plugin-helpers`

**[Codesandbox](https://codesandbox.io/s/graphql-codegen-cli-on-yarn-berry-x6xk5)**

**Environment:**

- `@graphql-codegen/cli`: `2.1.1`
- `@graphql-codegen/typescript`: `2.1.1`
- `@graphql-codegen/visitor-plugin-common`: `2.1.1`
- `NodeJS`: `v14.17.0`
- `Yarn`: `3.0.0`

**Additional context**
This started when I upgraded from `2.0.1` to `2.1.1`
```
Error: @graphql-codegen/plugin-helpers tried to access @graphql-codegen/visitor-plugin-common, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
```

Adding following to `.yarnrc.yml` fixes it, but that's a hack, not a fix
```yaml
packageExtensions:
  "@graphql-codegen/plugin-helpers@*":
    dependencies:
      "@graphql-codegen/visitor-plugin-common": 2.1.1
```
