### ISSUE TITLE
[typescript-urql-graphcache] typesPrefix and typesSuffix options are not worked

### ISSUE THREAD

**Issue by shiwano** [dotansimha/graphql-code-generator#6544]
**Describe the bug**
When using the `typescript-urql-graphcache` plugin, the generated types don't respect the `typesPrefix` and `typesSuffix` config options. For example, the type `User` will not be renamed even if the `typesPrefix` and `typesSuffix` are set.

**To Reproduce**

https://codesandbox.io/s/distracted-shape-xl8ik?file=/types.ts

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type Mutation {
    createUser: User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```graphql
# None.
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-urql-graphcache
    config:
      typesPrefix: 'Prefix'
      typesSuffix: 'Suffix'
```

**Expected behavior**

I expect it to generate a type called `PrefixUserSuffix`, but it instead generates a type called `User`.

**Environment:**

- OS: macOS 11.5.1
- @graphql-codegen/typescript-urql-graphcache: 2.1.1
- NodeJS: v16.6.2

**Additional context**
None.
