### ISSUE TITLE
With near-operation-file-preset, queries using multiple fragments can generate duplicate imports

### ISSUE THREAD

**Issue by nbudin** [dotansimha/graphql-code-generator#6546]
**Describe the bug**
In a project using near-operation-file-preset that has two files with operations A and B, and B uses fragments from A in a certain way, the resulting generated file for B will contain duplicate imports of the same symbols from the generated file for A.  This is an error in TypeScript.

In particular, the way I've found to reproduce this behavior is:

* A contains fragments A1 and A2.  A2 is a superset of A1 and uses A1 as part of its definition.
* B contains operations B1 and B2.  B1 uses A1 as part of its definition; B2 uses both A1 and A2 in different parts of its definition.

The resulting generated file for B will have two import statements for A.  One of them imports the A1 document, the other imports both the A1 and A2 documents.  Because A1 is imported twice, it's an error.

**To Reproduce**
https://codesandbox.io/s/proud-bird-jx23b

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

userFields.ts:
```typescript
import { gql } from "graphql-tag";

export const usernameFragment = gql`
  fragment usernameFragment on User {
    username
  }
`;

export const userFields = gql`
  fragment userFields on User {
    ...usernameFragment
    email
  }

  ${usernameFragment}
`;
```

document.ts:
```typescript
import { gql } from "graphql-tag";
import { userFields, usernameFragment } from "./userFields";

export const limitedUserFieldsQuery = gql`
  query user {
    user(id: 1) {
      ...usernameFragment
    }
  }

  ${usernameFragment}
`;

export const userAndFriendQuery = gql`
  query allUserFields {
    user(id: 1) {
      ...userFields
    }

    friend: user(id: 2) {
      ...usernameFragment
    }
  }

  ${userFields}
  ${usernameFragment}
`;
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: 
  - '*.ts'
  - '!*.generated.ts'
generates:
  types.generated.ts:
    plugins:
      - typescript
  .:
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: types.ts
    plugins:
      - typescript-operations
      - typescript-graphql-request
```

**Expected behavior**
I expect each symbol to be imported only once per file.

**Environment:**

- OS: macOS 11.5.1
- `@graphql-codegen/cli`: 2.1.1
- `@graphql-codegen/near-operation-file-preset`: 2.1.1
- `@graphql-codegen/typescript`: 2.1.1
- `@graphql-codegen/typescript-graphql-request`: 4.1.1
- `@graphql-codegen/typescript-operations`: 2.1.1
- NodeJS: 14.16.1

**Additional context**
I'm going to see if I can fix this in a PR.
