### ISSUE TITLE
typescript-generic-sdk: Cannot read property 'value' of undefined 

### ISSUE THREAD

**Issue by djpate** [dotansimha/graphql-code-generator#6551]
When attempting to generate with the SDK plugin, it fails without given any clear error of what is wrong.

**stacktrace**
```
TypeError: Cannot read property 'value' of undefined
        at /home/pate/work/kmsat-frontend/node_modules/@graphql-codegen/typescript-generic-sdk/index.js:45:35
        at Array.map (<anonymous>)
        at GenericSdkVisitor.get sdkContent [as sdkContent] (/home/pate/work/kmsat-frontend/node_modules/@graphql-codegen/typescript-generic-sdk/index.js:40:14)
        at Object.plugin (/home/pate/work/kmsat-frontend/node_modules/@graphql-codegen/typescript-generic-sdk/index.js:80:21)
        at executePlugin (/home/pate/work/kmsat-frontend/node_modules/@graphql-codegen/core/index.js:38:35)
        at async /home/pate/work/kmsat-frontend/node_modules/@graphql-codegen/core/index.js:116:24
        at async Promise.all (index 2)
        at async Object.codegen (/home/pate/work/kmsat-frontend/node_modules/@graphql-codegen/core/index.js:106:20)
        at async process (/home/pate/work/kmsat-frontend/node_modules/@graphql-codegen/cli/bin.js:1003:56)
        at async Promise.all (index 0)
```

I cannot really help given a repro steps since I have hundreds of gql files and no idea what is the issue. 

Generation works fine without the plugin.

**To Reproduce**

3. My `codegen.yml` config file:

```
hooks:
  afterAllFileWrite:
    - prettier --write
overwrite: true
schema: 'http://localhost:3000/graphql'
documents:
  - 'src/graphql/mutations/foo/**/*.graphql'
  - 'src/graphql/queries/foo/**/*.graphql'
generates:
  src/graphql/queries/foo/index.d.ts:
    plugins:
      - 'typescript-graphql-files-modules'
  src/graphql/generated/foo/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-generic-sdk'
  src/graphql/graphql.schema.json:
    plugins:
      - 'introspection'
```

**Expected behavior**
A clear error or at least pointing to which gql file is causing an issue.

**Environment:**

- OS: Linux
- `@graphql-codegen/2.1.1`: 
- NodeJS: 16
