### ISSUE TITLE
[typescript] non nullable GraphQL inputs with default values should NOT be optional for BE code

### ISSUE THREAD

**Issue by HunderlineK** [dotansimha/graphql-code-generator#6559]
**Describe the bug**
If the default value for a non-nullable field is set, the generated output marks the field as optional i.e. suffixed with `?`

**To Reproduce**

1. My GraphQL schema:

```graphql
ordersSearch(
    size: Int! = 10
    offset: Int! = 0
)
```

2. My GraphQL operations:

```graphql
ordersSearch
```

3. My `codegen.yml` config file:

```yml
generates:
    schema:

    plugins:
      - typescript
      - typescript-resolvers
    config:
      federation: true
      contextType: ...
      constEnums: false
      enumsAsTypes: false
      numericEnums: false
      futureProofEnums: false
      enumsAsConst: false
      onlyOperationTypes: false
      immutableTypes: false
      maybeValue: T | null
      noExport: false
      enumPrefix: true
      fieldWrapperValue: T
      wrapFieldDefinitions: false
      skipTypename: false
      nonOptionalTypename: false
      useTypeImports: false
```

**Expected behavior**
The type generated for inputs with default values i.e. `size` and `offset` should NOT be optional for the typing used in the back-end service, because the value will never be undefined.

**Environment:**

- OS: macOS Big Sur
- `@graphql-codegen/...`: `^1.20.1`
- NodeJS: V14

**Additional context**
This is related to another MR: https://github.com/dotansimha/graphql-code-generator/issues/4273

I suspect the request in that MR was based on the assumption that code-gen is only used in the front-end/client application, but we use it in the back end. So there should be a configuration for deciding how the default is treated.
