### ISSUE TITLE
typescript-urql plugin generates not working code

### ISSUE THREAD

**Issue by frederikhors** [dotansimha/graphql-code-generator#6584]
**Describe the bug**

I'm using the plugin `@graphql-codegen/typescript-urql@3.1.2`.

It works but generates code like:

```ts
import { DocumentNode } from "graphql";
// ...
export const MyDocument = {
	kind: "Document",
	definitions: [
		{
			kind: "OperationDefinition",
			operation: "query",
      // ...
    }
	],
} as unknown as DocumentNode;
```

This is a problem because SvelteKit throws with:

`The requested module '/node_modules/.vite/graphql.js?v=b4a54645' does not provide an export named 'DocumentNode'`.

Which is correct because `DocumentNode` here is a type and the first line should be instead:

```ts
import type { DocumentNode } from "graphql";
```

**To Reproduce**

REPL: https://codesandbox.io/s/codegen-typescript-urql-issue-documentmode-oqwsm

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```graphql
query user {
  user(id: 1) {
      id
      username
      email
  }
}
```

3. My `codegen.yml` config file:

```yml
schema: ./schema.graphql
generates:
  ./types.ts:
    documents: ./**/*.graphql
    plugins:
      - typescript-urql
    config:
      withHooks: false
      documentMode: documentNode
```

**Environment:**

- OS: Windows 10
- `@graphql-codegen/cli": "2.1.1`
- NodeJS: 14
