### ISSUE TITLE
Cannot generate types for operations inside TypeScript `.tsx` files

### ISSUE THREAD

**Issue by thisisxvr** [dotansimha/graphql-code-generator#6592]
**Describe the bug**
Operations that are colocated inside `.tsx` files are not being parsed by the plugins. However, if the operation is defined directly in the `codegen.yaml`, it works fine.

**To Reproduce**
A codesandbox with my package versions and configuration be found here: https://codesandbox.io/s/happy-pasteur-plx2y.
However, the issue is not being replicated in the codesandbox.

1. My GraphQL schema:

```graphql
enum EntityType {
  CONTACT
  ORGANISATION
  CONTRACT
  ACTIVITY
  TERMSHEET
}

interface BaseEntity {
  id: ID!
  type: EntityType!
  isDeleted: Boolean
  updatedBy: PartialContact!
  createdBy: PartialContact!
  _ts: Int
}

interface BaseContract {
  borrowers: [Borrower!]!
  amount: Float!
  issueDate: Int!
  maturityDate: Int!
  isinNumber: String
  template: ContractTemplate!
  investors: [Investor!]!
  series: String!
  status: ContractStatus!
  contractId: ID
}

type PartialContact {
  id: ID!
  givenName: String!
  familyName: String!
}

type Borrower {
  id: ID!
  name: String!
}

enum PaymentStructure {
  FIXED
  FLOATING_RATE
}

enum PaymentStructureType {
  INTEREST
  AMORTISING
}

enum ContractTemplate {
  TAMMY
  GLEN
}

type Investor {
  id: ID!
  name: String!
  allocation: Float!
  amount: Float!
  total: Int
  settlementAmount: Float
  settlementDate: Float
  isAccepted: Boolean
  reviewedAt: Float
}

enum LeaseType {
  FIXED
  CPI
  MARKET
}

enum Frequency {
  WEEKLY
  FORTNIGHTLY
  MONTHLY
  QUARTERLY
  YEARLY
}

type Lease {
  paymentFrequency: Frequency!
  value: Float!
  type: LeaseType!
}

enum SplitType {
  GENERAL
  MAINTENANCE
  SPECIAL
  INVESTOR
}

type Split {
  type: SplitType!
  rate: Float!
}

type Property {
  address: String!
  tenant: String!
  lease: Lease!
  splits: [Split!]!
}

enum ContractStatus {
  PROPOSED
  INVESTOR_ADDED
  ACCEPTED
  RATE_SET
  REVIEWED
  SETTLED
  EFFECTIVE
  MATURED
  EARLY_TERMINATION
}

type TAMMYContract implements BaseEntity & BaseContract {
  id: ID!
  contractId: ID
  type: EntityType!
  borrowers: [Borrower!]!
  amount: Float!
  paymentStructure: PaymentStructure
  paymentStructureType: PaymentStructureType
  additionalPaymentFeature: String
  yieldCalculationMechanism: String
  accrualYield: String
  issuePrice: String
  prepaidInterest: Float
  issueDate: Int!
  maturityDate: Int!
  isinNumber: String
  template: ContractTemplate!
  property: Property
  investors: [Investor!]!
  series: String!
  status: ContractStatus!
  isDeleted: Boolean
  updatedBy: PartialContact!
  createdBy: PartialContact!
  _ts: Int
}

type GLENContract implements BaseEntity & BaseContract {
  id: ID!
  contractId: ID
  type: EntityType!
  borrowers: [Borrower!]!
  amount: Float!
  paymentStructure: PaymentStructure
  paymentStructureType: PaymentStructureType
  additionalPaymentFeature: String
  prepaidInterest: Float
  issueDate: Int!
  maturityDate: Int!
  isinNumber: String
  template: ContractTemplate!
  property: Property
  investors: [Investor!]!
  series: String!
  status: ContractStatus!
  isDeleted: Boolean
  updatedBy: PartialContact!
  createdBy: PartialContact!
  _ts: Int
}

union Contract = TAMMYContract | GLENContract

input ReviewContractInput {
  id: ID!
  isAccepted: Boolean!
}

type Mutation {
  reviewContract(input: ReviewContractInput): Contract
}

type Query {
  contract(id: ID!): Contract
  contracts: [Contract!]
}
```

2. My GraphQL operations:
```ts
export const LIST_CONTRACTS_QUERY = gql`
  query ContractsTableQuery {
    contracts {
      ... on BaseEntity {
        id
        type
      }
      ... on BaseContract {
        series
        issueDate
        maturityDate
        contractId
        amount
        status
        template
        borrowers {
          id
          name
        }
      }
    }
  }
`;
```

3. My `codegen.yml` config file:

```yml
schema: http://localhost:7071/api/graphql
generates:
  # Generates types for the useQuery, useMutation etc. apollo hooks
  ./src/graphql/operations.ts:
    documents:
      - src/**/!(*.d).{ts,tsx}
      # - "query TestQuery { contracts { ... on BaseEntity { id type } } }"
    plugins:
      - typescript-operations
      - typescript-react-apollo
      - add:
          content: |
            /** THIS FILE IS AUTO-GENERATED **/
            /** DO NOT EDIT **/
  # Types for the API
  ./src/graphql/types.ts:
    plugins:
      - typescript
      - add:
          content: |
            /** THIS FILE IS AUTO-GENERATED **/
            /** DO NOT EDIT **/
  # Generates the `possibleTypes` field required by apollo-client
  ./src/graphql/fragment-matcher.ts:
    plugins:
      - fragment-matcher
      - add:
          content: |
            /** THIS FILE IS AUTO-GENERATED **/
            /** DO NOT EDIT **/
config:
  addDocBlocks: true
  immutableTypes: true
  namingConvention:
    enumValues: keep
```

**Expected behavior**
`/src/graphql/operations.ts` contains types for the `gql` tagged operations in my `.tsx` files, including the `LIST_CONTRACTS_QUERY` sample given above. 

**Environment:**
- OS: macOS Bug Sur 11.4
-    `@graphql-codegen/add`: "^3.1.0",
-    `@graphql-codegen/cli`: "^2.1.1",
-    `@graphql-codegen/fragment-matcher`: "^3.1.0",
-    `@graphql-codegen/typescript`: "^2.1.1",
-    `@graphql-codegen/typescript-operations`: "^2.1.2",
-    `@graphql-codegen/typescript-react-apollo`: "^3.1.2",
-    `@graphql-codegen/visitor-plugin-common`: "^2.1.1",
- NodeJS: 14.17.0

**Additional context**
In the above `codegen.yaml` you can see a `query TestQuery { contracts { ... on BaseEntity { id type } } }` document that has been commented out. The operation types for this are being successfully generated (when it is not commented), but the operations inside `.tsx` files give an error: 
```
 Unable to find any GraphQL type definitions for the following pointers:
        
              - src/**/!(*.d).{ts,tsx}
 ```
