### ISSUE TITLE
generated Input and response  type are snake case.

### ISSUE THREAD

**Issue by HT-Moh** [dotansimha/graphql-code-generator#6597]
Why the code generated is for graphql input and response types are snake case ? instead the operations (hooks) are generated correctly

![image](https://user-images.githubusercontent.com/34759569/131552836-10c78e4d-4f96-428f-9420-8f16e5549b2b.png)
![image](https://user-images.githubusercontent.com/34759569/131553264-1adf59b7-f11c-46fa-8eec-12581ae74bab.png)

I am using nextjs `"^11.1.0",` + hasura + prisma

my codegen config file is :
```
schema:
  - "http://localhost:8888/v1/graphql":
      headers:
        x-hasura-admin-secret: secret@123
documents:
  - "./**/*.graphql"
watch: true
config:
  scalars:
    DateTime: Date
    JSON: "{ [key: string]: any }"
    timestamptz: string
    numeric: number
overwrite: true
generates:
  ./generated/graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
    config:
      maybeValue: T | undefined
      withHooks: true
      withComponent: false
      withHOC: false
    hooks:
      afterOneFileWrite:
        - prettier --write
  ./graphql.schema.json:
    plugins:
      - "introspection"
```
how can I fix this?
