### ISSUE TITLE
fragment-matcher generated code is wrongly indented

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [dotansimha/graphql-code-generator#6600]
**Describe the bug**

When using the fragment-matcher plugin against a graphql server this is the result of the generated code.
![image](https://user-images.githubusercontent.com/86342787/131652272-994e656a-5a95-4125-9e3d-bb720f8d6159.png)

**To Reproduce**
use fragment-matcher plugin. Possibly have not fragments to match.

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "http://localhost:3000/graphql"
documents: null
generates:
  src/types/graphql-generated.ts:
    plugins:
      - "typescript"
      - "fragment-matcher"
```
