### ISSUE TITLE
Output schema not sorted

### ISSUE THREAD

**Issue by DronBrigadir** [dotansimha/graphql-code-generator#6624]
**Describe the bug**
I add sort: true in graphql-codegen.yml and output schema not sorted

**To Reproduce**
run graphql-codegen --config ./graphql-codegen.yml and output schema won't be sorted

1. My `codegen.yml` config file:

```yml
schema: https://kp-graphql-api.unstable.kp.yandex.net/graphql/
hooks:
    afterOneFileWrite:
        - prettier --write
generates:
    ./src/index.ts:
        plugins:
            - add:
                  content:
                      - '/* eslint-disable import/newline-after-import */'
                      - '/* eslint-disable camelcase */'
                      - '// @generated'
                      - '// This file was automatically generated and should not be edited.'
            - add:
                  placement: 'append'
                  content: export * from './type-names';
            - typescript
            - fragment-matcher
        config:
            avoidOptionals: true
            apolloClientVersion: 3
            sort: true
```

**Expected behavior**
Output schema will be lexicographic sorted

- OS: macOS Catalina version: 0.15.7
- `@graphql-codegen/typescript`: "2.2.0"
