### ISSUE TITLE
inlineFragmentTypes: combine generates import for variables in same file

### ISSUE THREAD

**Issue by tw0517tw** [dotansimha/graphql-code-generator#6641]
**Describe the bug**
 

When using `inlineFragmentTypes: combine` config, codegen will generate `import` statements to import variables in the same file.

**To Reproduce**

see reproducing repo:
https://github.com/tw0517tw/codegen
https://github.com/tw0517tw/codegen/runs/3555409058

Line 3 of generated file is a unnecessary import
https://github.com/tw0517tw/codegen/blob/main/client/foo.fragments.generated.ts#L1-L4

1. My GraphQL schema:

```graphql
type Query {
   greeting:String
   students:[Student]
}

type Student {
   id:ID!
   firstName:String
   lastName:String
   password:String
   collegeId:String
}
```

2. My GraphQL operations:

```ts
import gql from 'graphql-tag';

const bar = gql`
  fragment bar on Student {
    id
    lastName
  }
`;

export default {
  foo: gql`fragment foo on Query {
    greeting

    students{
      id
      firstName

      ...bar
    }

    ${bar}
  }`,

  bar,
};

```

3. My `codegen.yml` config file:

```yml
overwrite: true
generates:
  ./client/graphql.ts:
    schema: "./schema.graphql"
    plugins:
      - typescript

  ./client:
    schema: "./schema.graphql"
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: graphql.ts
    documents:
      - "./client/**/*.fragments.ts"
    plugins:
      - typescript-operations
      - typescript-react-apollo
    config:
      documentMode: external
      importDocumentNodeExternallyFrom: near-operation-file
      inlineFragmentTypes: combine

```

**Expected behavior**

typescript not reporting error.

**Environment:**

- OS: Windows/Linux
- "@graphql-codegen/cli": "^2.2.0",
- "@graphql-codegen/near-operation-file-preset": "^2.1.3",
- "@graphql-codegen/typescript": "^2.2.1",
- "@graphql-codegen/typescript-operations": "^2.1.3",
- "@graphql-codegen/typescript-react-apollo": "^3.1.3",
- "typescript": "^4.4.2"
- NodeJS: 14

**Additional context**
