### ISSUE TITLE
Schema always sorted

### ISSUE THREAD

**Issue by canac** [dotansimha/graphql-code-generator#6649]
**Describe the bug**
Schema is always sorted regardless of the `sort` config.

**To Reproduce**

https://codesandbox.io/s/gql-codegen-sort-5my7k

Note that the config does not set `config: true`, but the generated is still sorted.

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
        email
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
```

**Expected behavior**
I expect that the output won't be sorted because `sort` is not `true` in the config.

**Environment:**

- OS: Codesandbox
- `@graphql-codegen/add`: @2.0.2
- `@graphql-codegen/cli`: @2.2.0
- `@graphql-codegen/typescript`: @1.21.0
- `@graphql-codegen/typescript-operations`: @1.17.14
- NodeJS: v14.17.6
