### ISSUE TITLE
typescript-urql plugin ignores `documentMode`

### ISSUE THREAD

**Issue by mlabrum** [dotansimha/graphql-code-generator#6650]
**Describe the bug**
typescript-urql plugin ignores `documentMode`  `importDocumentNodeExternallyFrom`  and `importOperationTypesFrom` settings

**To Reproduce**
```
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
  urql.ts:
    plugins:
      - "typescript-urql"
    config:
      documentMode: "external"
      importDocumentNodeExternallyFrom: "./types.ts"
```

As you can see here the generated file ignores the external document mode.
https://codesandbox.io/s/confident-dream-l0sd5?file=/urql.ts

**Expected behavior**
To have the generated urql hooks to reference the external type file

This issue looks like the same from https://github.com/dotansimha/graphql-code-generator/pull/4765 and I've used the code from there to fix this issue
