### ISSUE TITLE
skip/include directives do not `avoidOptionals` if field type is a list

### ISSUE THREAD

**Issue by brainkim** [dotansimha/graphql-code-generator#6748]
**Describe the bug**

The `@skip` and `@include` directives seem to be generating optional types for `GraphQLList` fields, even when `avoidOptionals` is true.

**To Reproduce**
https://codesandbox.io/s/practical-swanson-b93wg

1. My GraphQL schema:

```graphql
type Query {
  me: User!
}

type User {
  messages: [Message!]!
}

type Message {
  content: String!
}
```

2. My GraphQL operations:

```graphql
query MyQuery($include: Boolean!) {
  me {
    messages @include(if: $include) {
      content
    }
  }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
config:
  avoidOptionals: true
  nonOptionalTypename: true
```

**Expected behavior**

I expect TypeScript optionals not to be included in the generated output.

**Actual behavior**
```ts
export type MyQueryQuery = (
  { __typename: 'Query' }
  & { me: (
    { __typename: 'User' }
    & { messages?: Maybe<(
      { __typename: 'Message' }
      & Pick<Message, 'content'>
    )> }
  ) }
);
```

`messages` is optional.

**Environment:**

- OS: MacOS Big Sur (11.6)
- "@graphql-codegen/add": "2.0.2",
- "@graphql-codegen/cli": "1.20.1",
- "@graphql-codegen/typescript": "1.21.0",
- "@graphql-codegen/typescript-operations": "1.17.14",
- "graphql": "15.5.0"

**Additional context**

Probably related to this PR: 
https://github.com/dotansimha/graphql-code-generator/pull/5104
