### ISSUE TITLE
`Maybe` is inlined to include `undefined` in `typescript-operations` version 2.1.5

### ISSUE THREAD

**Issue by brainkim** [dotansimha/graphql-code-generator#6757]
**Describe the bug**
 
When using the `preResolveTypes` option, `Maybe` types now include `undefined` in their union starting in version 2.1.5, regardless of any `avoidOptionals` options.
 
**To Reproduce**
https://codesandbox.io/s/amazing-montalcini-kuf9p?file=/codegen.yml
Code Sandbox isn’t inlining Maybes for some reason right now. Maybe the dependencies aren’t updating correctly.

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String
}
```

2. My GraphQL operations:

```graphql
# Put your operations here
query user {
    user(id: 1) {
        id
        username
        email
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      avoidOptionals: true
      preResolveTypes: true
```

**Expected behavior**

The codesandbox isn’t inlining maybes for some reason.
An example change for an operation. `Maybe` is being inlined as `T | null | undefined` even though `avoidOptionals` is true.
```diff
-export type CypressCreateOrgMutation = { newAccount: Maybe<{ __typename: 'Account', id: string }> };
+export type CypressCreateOrgMutation = { newAccount: { __typename: 'Account', id: string } | null | undefined };
````
**Environment:**

```
    "@graphql-codegen/add": "^2.0.2",
    "@graphql-codegen/cli": "2.2.0",
    "@graphql-codegen/plugin-helpers": "^2.1.1",
    "@graphql-codegen/typescript": "^2.2.2",
    "@graphql-codegen/typescript-operations": "^2.1.5",
    "@graphql-codegen/typescript-resolvers": "^1.19.1",
    "@graphql-codegen/visitor-plugin-common": "^2.2.1",
```

**Additional context**
Probably related to this commit: 
https://github.com/dotansimha/graphql-code-generator/commit/25cd11d01ec55d5c6a2a83ebd501abdd1ed2f248

**Comment by gilgardosh** [comment]
Hey again @brainkim ,
Could you run it with this and see if fixed?

@graphql-codegen/typescript-operations@2.1.6-alpha-a376e6942.0
@graphql-codegen/gql-tag-operations-preset@1.1.7-alpha-a376e6942.0

**Comment by oceandrama** [comment]
@gilgardosh This is still incorrect if you use custom `maybeValue`
In my `codegen.yml` `maybeValue` is `T | undefined`, so I shouldn't have `| null` in my types with `preResolveTypes: true`

**Comment by gilgardosh** [comment]
Hi @oceandrama ,
in this case, since `preResolveTypes` is used, no `maybe` should be used in the generated types (neither the original nor the custom `maybeValue`)

**Comment by studiosciences** [comment]
I agree with @gilgardosh. Regardless of `preResolveTypes` or using `Maybe<>`, `typescript-operations` should use the `maybeValue`. The default value is `T | null`, not `T | null | undefined`.

**Comment by yura3d** [comment]
One of the key changes in #6763 is the lines:
https://github.com/dotansimha/graphql-code-generator/blob/dc1beb07c9239fe30aa33fdbc625fbb27d4fd147/packages/plugins/typescript/operations/src/visitor.ts#L53-L54
But `avoidOptionals` is not only boolean. It can be the object to set what kind of definition types should not be optional (`field`, `inputValue`, `object`, `defaultValue`). By these changes it's impossible to left optionals for input values (for example) and avoid them for other definiton types.

**Comment by BarryThePenguin** [comment]
I'm seeing something similar when upgrading from 2.1.4 to 2.1.6, looks like I'm only having an issue with array values.

What was..

```ts
items: Array<Maybe<{ ... }>>
```

..has become..

```ts
items: Array<{ ... } | null | undefined>
```

Given `type Maybe<T> = T | null`, I'd have expected the unwrapped version to be..

```ts
items: Array<{ ... } | null>
```

That's with all the default options for `typescript-operations`

**Comment by lanwin** [comment]
> I agree with @gilgardosh. Regardless of `preResolveTypes` or using `Maybe<>`, `typescript-operations` should use the `maybeValue`. The default value is `T | null`, not `T | null | undefined`.

This is also what I expect. The current version breaks our code.

I also found that avoidOptionals behaves different when used with sub object instead of boolean. The following example you could try out at https://www.graphql-code-generator.com/ (v2.2.0).

#### Schema
```gql
schema {  query: Query }
type Query { username: String }
```
#### Operations
```qgl
{ username }
```
### codegen.yaml - boolean
```yaml
generates:
  types.ts:
    plugins:
      - typescript-operations            
    config:
      preResolveTypes: true
      avoidOptionals: true
```
Output:
```typescript
export type Unnamed_1_Query = { __typename?: 'Query', username: string | null };
```

### codegen.yaml - subobject
```yaml
generates:
  types.ts:
    plugins:
      - typescript-operations            
    config:
      preResolveTypes: true
      avoidOptionals:
        field: true
        inputValue: true
        object: true
        defaultValue: true
```
Output:
```typescript
export type Unnamed_1_Query = { __typename?: 'Query', username: string | null | undefined };
```

--------

I would expect this should output exact the same result? Shouldn't it?

**Comment by dotansimha** [comment]
> > I agree with @gilgardosh. Regardless of `preResolveTypes` or using `Maybe<>`, `typescript-operations` should use the `maybeValue`. The default value is `T | null`, not `T | null | undefined`.
> 
> This is also what I expect. The current version breaks our code.

I agree this makes sense to interpolate the `maybeValue` when `preResolveTypes` is used. @gilgardosh is working on a fix :)

**Comment by Rupert-com** [comment]
I face the same error as @oceandrama


**`codegen.yml`**
``` yml
    config:
      maybeValue: T | undefined
      preResolveTypes: false
```
```
(property) getUser?: {
    __typename?: "User" | undefined;
} & Pick<User, "companySubscription" | "linkedIn" | "name" | "organisation" | "surname" | "title" | "role" | "status" | "_id" | "inputValidateCode" | ... 6 more ... | "Company"> & {
    ...;
}
```
**vs**
**`codegen.yml`**
``` yml
    config:
      maybeValue: T | undefined | null
      preResolveTypes: false
```
```
(property) getUser?: {
    __typename?: "User" | undefined;
} & Pick<User, "surname" | "status" | "inputValidateCode" | "role" | "permission" | "isAllowedToCreateCompany" | "organisation" | "name" | ... 8 more ... | "title"> & {
    ...;
}
```

**Comment by dleavitt** [comment]
FWIW I believe this was introduced by #6642 

My notes from there:

The `preResolveTypes` setting now _changes the types_ generated by the operations plugin (but not those generated by the typescript plugin). @n1ru4l this seems like a bug and is at minimum a breaking change.

The issue is that the "maybe" types are not pre-resolved if `preResolveTypes` is true. Instead a hardcoded value is used: 

https://github.com/dotansimha/graphql-code-generator/blob/6afbbf67c66787b9d7316689438a6519c26c1b7c/packages/plugins/typescript/operations/src/visitor.ts#L52


### Example

```yaml
schema.ts:
  plugins:
    - "typescript"
    - "typescript-operations"
  config:
    maybeValue: T | undefined
    preResolveTypes: # see below
```

```graphql
type User {
  name: string
}
```

```typescript
// preResolveTypes: false
export type User = {
  name?: string | undefined
}

// preResolveTypes: true
// not compatible with the above!
export type User = {
  name?: string | null | undefined
}
```

### Recommendations

Could either a. revert this change or b. try to pre-resolve the maybe type instead of just using a hardcoded default. Something like:

```typescript
if (config.maybeType) {
  return maybeType.replace("T", type);
} else {
  return `${type} | null | undefined`; 
}
```
