### ISSUE TITLE
Types namespace is not imported correctly

### ISSUE THREAD

**Issue by stephenbunch** [dotansimha/graphql-code-generator#6771]
**Describe the bug**
The `Types` namespace is not imported into `frag1.generated.ts`.

 

**To Reproduce**

https://github.com/stephenbunch/graphql-codegen-bugs/tree/bugs/types_import_nested_fragment

1. My GraphQL schema:

```graphql
type Fruit {
    color: Color
}

enum Color {
    BLUE
    RED
}

type Query {
    fruit: Fruit
}
```

2. My GraphQL operations:

`frag1.gql`
```graphql
fragment Frag1 on Fruit {
  ...Frag2
}
```

`frag2.gql`
```graphql
fragment Frag2 on Fruit {
  color
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.gql
documents: 'src/**/*.gql'

generates:
  src/types.generated.ts:
    plugins:
      - typescript

  src/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: types.generated.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo

```

**Expected behavior**
The `Types` namespace should be imported.

**Environment:**

- OS: macOS Big Sur 11.5.2
- `@graphql-codegen/cli`: ^2.2.0
- `@graphql-codegen/near-operation-file-preset`: ^2.1.4
- `@graphql-codegen/typed-document-node`: ^2.1.4
- `@graphql-codegen/typescript-operations`: ^2.1.5
- `@graphql-codegen/typescript-react-apollo`: ^3.1.4
- NodeJS: 15.14.0

**Additional context**
This bug only happens when the nested fragment lives in a separate file. If the fragments all live in the same file, this doesn't happen.
