### ISSUE TITLE
Corrupted operations end up breaking the output of gql-tag-operations

### ISSUE THREAD

**Issue by kamilkisiela** [dotansimha/graphql-code-generator#6884]
**Describe the bug**
When one of the operations is corrupted, codegen and `gql-tag-operations` preset do not print any errors or warnings.

1. My GraphQL schema:

```graphql
type Query {
  me: User!
}

type User {
  id: ID!
  name: String!
}
```

2. My GraphQL operations:

```graphql
{
  me { id }
}
```

```graphql
{
  me { firstName } 
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
generates:
  ./src/graphql:
    documents: ./src/**/*.ts
    preset: gql-tag-operations-preset
```

**Expected behavior**

- error or at least a warning about corrupted operation
- should not affect the generation of other operations

I expect the preset to generate at least the part of code for the valid operation but I get no operations generated.

```typescript
const documents = {
    "{ me { id } }": graphql.whatever,
};

export function gql(source: "{ me { id } }"];
```
