### ISSUE TITLE
[typescript-urql-graphcache] useTypeImports is not respected

### ISSUE THREAD

**Issue by rossng** [dotansimha/graphql-code-generator#6912]
**Describe the bug**

GraphQL Code Generator supports a `useTypeImports` config option for plugins, which ensures that generated code is compatible with TypeScript's `"importsNotUsedAsValues": "error"` option.

However, the `typescript-urql-graphcache` plugin does not respect this option, resulting in the generation of unbuildable TypeScript code in some circumstances.

**To Reproduce**

See https://codesandbox.io/s/quirky-fog-86g3f?file=/types.ts

1. My GraphQL schema:

Not applicable.

2. My GraphQL operations:

Not applicable.

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
config:
  useTypeImports: true
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-urql
      - typescript-urql-graphcache
```

4. My `tsconfig.json` config file:

```json
{
  "compilerOptions": {
    "importsNotUsedAsValues": "error"
  }
}
```

**Expected behavior**

`types.ts` should use `import type` to import the types from `@urql/exchange-graphcache`. Instead it uses `import`, which causes `tsc` to report an error.

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/565371/138970115-15092819-2ce6-40ca-bef6-c714b357e851.png">

**Environment:**

- OS: N/A
- `@graphql-codegen/typescript-urql-graphcache`: 2.1.6
- NodeJS: N/A

**Additional context**

I plan to submit a PR to fix this.
