### ISSUE TITLE
Custom scalars are not resolved correctly when preResolveTypes is true

### ISSUE THREAD

**Issue by davazp** [dotansimha/graphql-code-generator#6914]
**Describe the bug**

When defining custom types referencing files, like

```
  config: {
    scalars: {
      Date: "@app/dates#DateOnly",
    },
```

the generated file by `near-operation-file` will reference the scalar as other primitive types like `DateOnly`,  instead of `Types.Scalars["DateOnly"]`. 

This only works for primitive types, making the types very clean, but not for custom types like this one.

**To Reproduce**
I prepared a sandbox with an example setup:
https://codesandbox.io/s/peaceful-fast-4wsq4?file=/document.generated.tsx

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
scalar Date

type Query {
    today: Date
}
```

2. My GraphQL operations:

```graphql
query test {
    today
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
config:
  scalars:
    Date: "@test-lib#DateOnly"
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
  ./:
    preset: near-operation-file
    presetConfig:
      extension: .generated.tsx
      baseTypesPath: types.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
```

**Expected behavior**
The generated custom type should be valid, probably referencing it like `Types.Scalars["CustomType"]`
