### ISSUE TITLE
Schema glob patterns not throwing errors

### ISSUE THREAD

**Issue by flippidippi** [dotansimha/graphql-code-generator#6929]
**Describe the bug**
 
When doing typescript codegen, using schema as a glob pattern swallows errors, while a list of schema files works. 

**To Reproduce**
Create 2 schemas, 1 with a syntax error and the other without. Using a glob schema will swallow the syntax error and individually listing each schema file with correctly throw the syntax error.

In the example, in `codegen.yml`, the glob route is running by default and swallows the error.
Comment the glob way and uncomment out the list way, save the file, and it will correctly throw the error.
https://codesandbox.io/s/peaceful-snowflake-epsdc?file=/codegen.yml

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
type Query {
  boop Boolean
}
```

```graphql
type Query {
  beep: Boolean
}
```

2. My GraphQL operations:
n/a

3. My `codegen.yml` config file:

```yml
# 1. Swallows errors and only outputs types for `two.gql`
schema: schemas/*.gql

# 2. Correctly throws syntax error for `one.gql`
#schema:
#  - schemas/one.gql
#  - schemas/two.gql


generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS: Linux
- `@graphql-codegen/cli`: 2.2.1
- `@graphql-codegen/typescript`: 2.2.4
- `@graphql-codegen/typescript-operations`: 2.1.8
- `graphql`: 15.7.2
- NodeJS: 14.8.1

**Additional context**
<!-- Add any other context about the problem here. -->
