### ISSUE TITLE
Allow sorting in enums to be disabled

### ISSUE THREAD

**Issue by andbjer** [dotansimha/graphql-code-generator#6935]
**Describe the bug**

My schema contains an enum for `DayOfWeek`:

```gql
enum DayOfWeek {
  SUNDAY
  MONDAY
  TUESDAY
  WEDNESDAY
  THURSDAY
  FRIDAY
  SATURDAY
}
```

When GraphQL Code Generator creates a typescript type for this enum, it will sort the values alphabetically like below:

```ts
export enum DayOfWeek {
  Friday = 'FRIDAY',
  Monday = 'MONDAY',
  Saturday = 'SATURDAY',
  Sunday = 'SUNDAY',
  Thursday = 'THURSDAY',
  Tuesday = 'TUESDAY',
  Wednesday = 'WEDNESDAY'
}
```

This is an issue if you would like to retrieve the index value of the enum:
```ts
const day = Object.values(DayOfWeek).indexOf(obj.dayOfWeek);
```

If the object's day of week is Sunday I would expect `day` to be 0, instead it is 3.

I've tried to look through all of the options for the typescript-plugin, but I have not found an option for disabling sorting on enums.

**To Reproduce**

https://codesandbox.io/s/graphql-code-generator-enum-issue-7788u

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
    planStartDay: DayOfWeek
}

enum DayOfWeek {
  SUNDAY
  MONDAY
  TUESDAY
  WEDNESDAY
  THURSDAY
  FRIDAY
  SATURDAY
}
```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
        email
        planStartDay
    }
}

```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations

```

**Expected behavior**
I would expect the enum values to keep the same index position as in the schema, or at least an option to disable the alphabetical sorting.

**Environment:**

- OS: macOS 11.6
- "@graphql-codegen/add": "3.1.0"
- "@graphql-codegen/cli": "2.2.1"
- "@graphql-codegen/typescript": "2.2.4"
- "@graphql-codegen/typescript-operations": "2.1.8",
- NodeJS: v17.0.1

**Additional context**

**Comment by ardatan** [comment]
We apply sorting not only enum keys but also fields, o ject definitions etc. Currently there is no option to disable sorting for enum values specifically but instead you can disable all kind of sorting with `sort: false`configuration option.

**Comment by andbjer** [comment]
@ardatan thank you! Is that behaviour documented anywhere? I tried specifying `generates.config.sort: false` and `generates.sort: false` but that did not work for me. Only thing that worked was specifying `sort: false` on the root level in `codegen.yml` but that isn't listed as an option [here](https://www.graphql-code-generator.com/docs/getting-started/codegen-config).

I still think it would be nice to have an option to disable sorting for enums. It's easier to browse through the code when it's sorted alphabetically, but it would be great if there was an option that for maintaining the index positioning of the enum values.

**Comment by n1ru4l** [comment]
@andbjer One could argue whether enum values are actually meant to be used like that. The ECMA specification does not clearly state that each js engine has to implement `Object.values` (aka enumeration order of objects) the same way (https://stackoverflow.com/a/52706191).

From a client perspective, an alternative approach could be to have a field on your Query root type that exposes a list of `DayOfWeek` that is in the correct order and that the client can query to get the guaranteed order.

```graphql
type Query {
  daysOfWeek: [DayOfWeek!]!
}
```

I really think this is simply too uncertain to support it as a separate config option.

**Comment by smmoosavi** [comment]
I saw this [doc] and my expectation is `sort: false` should work like this:

```yml
schema: http://localhost:3000/graphql
generates:
  schema.graphql:
    plugins:
      - schema-ast
    config:
      commentDescriptions: true
      sort: false
```

also, it says default is false

> `sort`
> type: `boolean` default: `false`

[doc]: https://www.graphql-code-generator.com/docs/plugins/schema-ast

**Comment by smmoosavi** [comment]
I checked this [code], sort config is not used in the `transformSchemaAST` function, which is weird

[code]: https://github.com/dotansimha/graphql-code-generator/blob/8c83f05ef3038e816c826f57ebbf15c75ebd959b/packages/plugins/other/schema-ast/src/index.ts#L113

**Comment by ardatan** [comment]
@smmoosavi Thank you for the report! We have updated the documentation now. `sort` flag is used in `graphql-tools`.

**Comment by smmoosavi** [comment]
@ardatan 
Can use send the new documentation link?

**Comment by tvvignesh** [comment]
> @ardatan Can use send the new documentation link?

https://www.graphql-code-generator.com/plugins/schema-ast

<img width="247" alt="image" src="https://user-images.githubusercontent.com/1165845/145752991-35482d32-10b6-49b8-8574-f1d776ce0549.png">

Default updated to true. You can manually set it to false to disable sorting

**Comment by andbjer** [comment]
@n1ru4l I was not aware that this could differ from browser to browser. Then I guess the solution you propose is probably the best option.

**Comment by ha-akelius** [comment]
> > @ardatan Can use send the new documentation link?
> 
> https://www.graphql-code-generator.com/plugins/schema-ast
> 
> <img alt="image" width="247" src="https://user-images.githubusercontent.com/1165845/145752991-35482d32-10b6-49b8-8574-f1d776ce0549.png">
> 
> Default updated to true. You can manually set it to false to disable sorting

it didn't work for me :(

could you please provide a complete codegen.yml

this is my codegen.yaml, I don't know what I am missing

```
schema: "schema.graphql"
generates:
  ./src/app/graphql/models/types.ts:
    documents:
      - "./src/app/graphql/**/*.ts"
    plugins:
      - "schema-ast"
      - add:
          content: "/* eslint:disable */\n/* tslint:disable */"
      - "typescript"
      - "typescript-operations"
    config:
      sort: false
      skipTypename: true
      namingConvention:
        enumValues: upper-case#upperCase
```
