### ISSUE TITLE
TypeScript resolvers - Custom  args type

### ISSUE THREAD

**Issue by seancwalsh** [dotansimha/graphql-code-generator#6963]
**Is your feature request related to a problem? Please describe.**

Add config to add custom args type. I work on a project where `user` data is added all resolver args through middleware. This arg is untyped with my current config, because it's not included in the GraphQL schema.

**Describe the solution you'd like**
Very similar to the ability to add custom context type: `contextType: ./types#CustomContext`.

**Describe alternatives you've considered**
I apologise if this is already possible, I couldn't find anything in the [TS resolver docs](https://www.graphql-code-generator.com/docs/plugins/typescript-resolvers) or GH issues. I haven't tried anything in particular, but happy to help with a PR.

**Additional context**
Code examples of what I would like to do.

codegen.yml
```
overwrite: true
schema: "http://localhost/graphql"
generates:
  src/generated/graphql.ts:
    config:
      useIndexSignature: true
      defaultMapper: Partial<{T}>
      contextType: ./types#CustomContext
      # ADD THIS 👇
      argType: ./types#CustomArgs
    plugins:
      - "typescript"
      - "typescript-resolvers"
      - "typescript-document-nodes"
  ./graphql.schema.json:
    plugins:
      - "introspection"
```
./types.ts
```
export type CustomArgs<TArgs> = TArgs & { user: { name: string; email: string } };
```
