### ISSUE TITLE
`avoidOptionals` with `defaultValue: true` makes it impossible to generate object types with optional resolver fields

### ISSUE THREAD

**Issue by noahseger** [dotansimha/graphql-code-generator#7005]
**Describe the bug**

After https://github.com/dotansimha/graphql-code-generator/pull/5113, it is no longer possible to generate `typescript-resolvers` objects with optional properties.

It also appears that query input values with defaults are not correctly interpreted as non-nullable.

**To Reproduce**

See the test I added in https://github.com/dotansimha/graphql-code-generator/pull/7004.

I was also able to reproduce in the sandbox:

https://codesandbox.io/s/optimistic-almeida-crkbo

1. My GraphQL schema:

```graphql
type Query {
    users(id: ID = "test-id", filter: UserFilter = {}): [User!]!
    ping: String!
}

type User {
    id: ID!
    username: String!
    email: String!
}

input UserFilter {
    status: String = "ACTIVE"
}
```

2. My GraphQL operations:

N/A

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
generates:
  resolvers.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      avoidOptionals:
        defaultValue: true
        field: false
        inputValue: false
        object: false
```

**Expected behavior**

I expected the following to be generated:

```ts
export type QueryResolvers<ContextType = any, ParentType extends ResolversParentTypes['Query'] = ResolversParentTypes['Query']> = {
  users?: Resolver<Array<ResolversTypes['User']>, ParentType, ContextType, RequireFields<QueryUsersArgs, 'id' | 'filter'>>;
  ping?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
};
```

But the object fields were required:

```ts
export type QueryResolvers<ContextType = any, ParentType extends ResolversParentTypes['Query'] = ResolversParentTypes['Query']> = {
  users: Resolver<Array<ResolversTypes['User']>, ParentType, ContextType, RequireFields<QueryUsersArgs, 'id' | 'filter'>>;
  ping: Resolver<ResolversTypes['String'], ParentType, ContextType>;
};
```
