### ISSUE TITLE
@graphql-codegen/typescript-react-query addInfiniteQuery and isReactHook throws an error

### ISSUE THREAD

**Issue by jeffdetmer** [dotansimha/graphql-code-generator#7052]
**Describe the bug**
 
There is an issue with the `addInfiniteQuery` functionality of `@graphql-codegen/typescript-react-query`.
When using `addInfiniteQuery: true` and `reactHook: true`, if the custom fetcher function contains another React Hook, 
the generated infinite query throws the following error:

```
Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

**To Reproduce**

- Implement a custom fetcher that is a React Hook that uses a React Hook inside the fetcher and set the `isReactHook` config option to `true`
- Set the `addInfiniteQuery` option to `true`
- attempt to use the infinite query within a React Component

https://codesandbox.io/s/pensive-meadow-g300n

fetcher.ts
```typescript
import { useGraphQLContext } from '../context/graphql';
export const useFetchData = <TData, TVariables>(
  query: string,
): (() => Promise<TData>) => {
  // FAILING: using a hook inside the fetcher
  const { endpoints } = useGraphQLContext();

  // PASSING: mocking the data so we don't use a hook inside the fetcher
  // const endpoints = { spacex: 'https://api.spacex.land/graphql/' };
  return async (variables?: TVariables) => {
    const res = await fetch(endpoints.spacex, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        query,
        variables,
      }),
    });

    const json = await res.json();

    if (json.errors) {
      const { message } = json.errors[0] || 'Error..';
      throw new Error(message);
    }

    return json.data;
  };
};
```

hook usage
```typescript
  const [queryParams] = useState({ limit: 12 });
  const {
    data,
    error,
    fetchNextPage,
    hasNextPage,
    isFetching,
    isFetchingNextPage,
    status,
  } = useInfiniteUsersQuery(
    { limit: queryParams.limit, offset: 0 },
    {
      getNextPageParam: (lastPage, allPages) => {
        return {
          limit: queryParams.limit,
          offset: (allPages.length ?? 0) * (queryParams.limit ?? 1),
        };
      },
    },
  );
```

codegen.yml
```yaml
overwrite: true
schema:
  - https://api.spacex.land/graphql
documents: 'graphql/**/*.graphql'
generates:
  graphql/generated/index.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-query'
    config:
      addInfiniteQuery: true
      pureMagicComment: true
      fetcher:
        func: ../fetcher#useFetchData
        isReactHook: true
  graphql/generated/schema.json:
    plugins:
      - 'introspection'
```

**Expected behavior**

The generated infinite query should execute without issue, same as the normal query, when the fetcher is a React Hook and uses a hook within.

**Environment:**

- OS: Windows/OSX/Linux
- `@graphql-codegen/typescript-react-query`: 3.2.1
- NodeJS: 16

**Additional context**

Removing the React Hook from within the fetcher will allow the infinite query to execute without issue.
