### ISSUE TITLE
[graphql-request] `print` is imported as type

### ISSUE THREAD

**Issue by MichaelDeBoey** [dotansimha/graphql-code-generator#7058]
**Describe the bug**
Ever since #5798 fixed #5798, `print` is imported as type when setting `useTypeImports` config to `true`.
This breaks the generated code.

![](https://user-images.githubusercontent.com/6643991/142858346-37281864-bfe3-43f2-acd7-0f2dcc5f92e2.png)

**To Reproduce**

https://codesandbox.io/s/aged-bird-qfoju?file=/types.ts:1556-1604

1. My GraphQL schema:

```graphql
type Query {
  user(id: ID!): User!
}

type User {
  id: ID!
  username: String!
  email: String!
}
```

2. My GraphQL operations:

```graphql
query user {
  user(id: 1) {
    id
    username
    email
  }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
overwrite: true
generates:
  types.ts:
    config:
      rawRequest: true
      useTypeImports: true
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
```

**Expected behavior**
There are no errors in `types.ts`

**Environment:**

- OS: macOS 11.2.3
- `@graphql-codegen/typescript-graphql-request`: `^4.3.1`
- NodeJS: v16.5.0

**Additional context**
#5798
#5855
