### ISSUE TITLE
typescript-graphql-request ignoring importOperationTypesFrom config option

### ISSUE THREAD

**Issue by chadly** [dotansimha/graphql-code-generator#7114]
**Describe the bug**

The `typescript-graphql-request` plugin is ignoring `importOperationTypesFrom` config option.

**To Reproduce**

`codegen.yml`:

```yaml
schema: "http://example.com"
documents: "**/*.gql"
generates:
  schema.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      onlyOperationTypes: true

  sdk.ts:
    plugins:
      - add:
          content: "import * as Types from './schema';"
      - typescript-graphql-request
    config:
      importOperationTypesFrom: Types
```

**Expected behavior**

I expect it to prefix operation types with `Types.` but it doesn't.
