### ISSUE TITLE
Fetcher endpoint is not inside doubles when using typescript-react-query

### ISSUE THREAD

**Issue by DavideCarvalho** [dotansimha/graphql-code-generator#7190]
**Describe the bug**
 

When generating the code, the endpoint is not inside double quotes, it gives an error as it's not recognized as a string

![image](https://user-images.githubusercontent.com/15630886/145656123-61cbedff-b724-4d4a-90c3-2239e19efde5.png)

**To Reproduce**

Just generate the code with the configuration below

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

Sandbox: https://codesandbox.io/s/goofy-sound-42uge?file=/codegen.yml

I removed some of the codegen.yml content, but the error stays

1. My GraphQL schema:

```graphql
# Put your schema here
```

2. My GraphQL operations:

```graphql
# Put your operations here
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema: "http://localhost:3000/api/graphql"
documents: "apollo/**/*.graphql"
generates:
  apollo/generated.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-query"
    config:
      fetcher:
        endpoint: "/api/graphql"
  ./graphql.schema.json:
    plugins:
      - "introspection"
  mirage/schema.graphql:
    plugins:
      - schema-ast
    config:
      commentDescriptions: true
```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS: 
- `@graphql-codegen/...`: 
- NodeJS: 

**Additional context**
<!-- Add any other context about the problem here. -->
