### ISSUE TITLE
Better interface for custom documents loader

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#7213]
The goal is to keep the current API, but add support for doing: 

```yaml
documents:
   require: "my-file.js"
```

```yaml
documents:
   require: "my-package"
```

> The above already supported today.

We also want to make sure to expose everything the codegen already knows (like the `GraphQLSchema`), so theoretically if someone wants to generate their GraphQL operations, they can do:

```yaml
documents:
   require: "graphql-query-generator"
   config:
      nestingLevel: 2
```
