### ISSUE TITLE
Better config file

### ISSUE THREAD

**Issue by kamilkisiela** [dotansimha/graphql-code-generator#722]
- allow to put all options in config
- also flags and template specific configuration

```yml
schema: ./schema.graphql
out: ./types.ts
template: introspection
# ...
extra: 
  noResolvers: true
```

- support json, yml, js
