### ISSUE TITLE
Cannot read property 'value' of undefined with typescript-react-query enabled

### ISSUE THREAD

**Issue by iamhaaamed** [dotansimha/graphql-code-generator#7229]
**Describe the bug**
I'm just trying to integrate graphql-code-generator with typescript-react-query plugin into my project and having this error:
```
 ✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate src/generated/graphql.tsx
      ✔ Load GraphQL schemas
      ✔ Load GraphQL documents
      ✖ Generate
        → Cannot read property 'value' of undefined

 Found 1 error

  ✖ src/generated/graphql.tsx
    TypeError: Cannot read property 'value' of undefined
        at generateQueryKey (/Users/user/Projects/DrivesAndDetours/node_modules/@graphq
l-codegen/typescript-react-query/index.js:24:31)
```

**To Reproduce**
Create a .graphql file, with a query.
Enable typescript-react-query codegen plugin.
Run yarn generate.

My `codegen.yml` config file:
```yml
overwrite: true
schema: 'schema.graphql'
documents: 'src/graphql'
generates:
  src/generated/graphql.tsx:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-query'
```

**Expected behavior**
should generate graphql.ts
