### ISSUE TITLE
ExperimentalWarning when using with Node LTS (16.13.1)

### ISSUE THREAD

**Issue by RIP21** [dotansimha/graphql-code-generator#7239]
**Describe the bug**
Getting this into the console while running the codegen.

```
(node:32683) ExperimentalWarning: stream/web is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:32683) ExperimentalWarning: buffer.Blob is an experimental feature. This feature could change at any time
```

**To Reproduce**

- Use Node 16.13.1
- Run codegen.yml with the config below.
- For Node 12 warning is not shown.

1. My `codegen.yml` config file:

```yml
schema:
  - http://localhost:4000/graphql:
documents: ./src/**/*.graphql
extensions:
  codegen:
    hooks:
      afterAllFileWrite:
        - prettier --write
    config:
      preResolveTypes: true
      useTypeImports: true
      pureMagicComment: true
    generates:
      schema.graphql:
        plugins:
          - schema-ast
      ./src/packlets/generated/introspection.generated.json:
        plugins:
          - introspection
        config:
          minify: true
          descriptions: false
          schemaDescription: false
      ./src/packlets/generated/graphql-types.generated.ts:
        - typescript
        - add:
            content: /* eslint-disable */
        - add:
            content: "// ####################################+################################################"
        - add:
            content: "// ################# THIS IS GENERATED FILE DO NOT TOUCH!!!!!!!!!!!!####################"
        - add:
            content: "// ####################################-################################################"
        - add:
            content: 'import type { UUID, DateTime, Time, JSON, Timestamp, Email, PhoneNumber, URL, Any, GraphQLDate } from "packlets/graphql/scalars"'
      src/:
        preset: near-operation-file
        presetConfig:
          extension: .generated.ts
          baseTypesPath: packlets/generated/graphql-types.generated.ts
        plugins:
          - typescript-operations
          - typed-document-node
          - add:
              content: /* eslint-disable */
          - add:
              content: "// ####################################+################################################"
          - add:
              content: "// ################# THIS IS GENERATED FILE DO NOT TOUCH!!!!!!!!!!!!####################"
          - add:
              content: "// ####################################-################################################"
```

**Expected behavior**
No warnings in the console.

**Environment:**

- OS: MacOS Monterey 12.0.1
- Versions:
```
    "@graphql-codegen/add": "~3.1.0",
    "@graphql-codegen/cli": "~2.3.0",
    "@graphql-codegen/introspection": "~2.1.0",
    "@graphql-codegen/near-operation-file-preset": "~2.2.2",
    "@graphql-codegen/schema-ast": "~2.4.0",
    "@graphql-codegen/typed-document-node": "~2.2.1",
    "@graphql-codegen/typescript": "~2.4.1",
    "@graphql-codegen/typescript-operations": "~2.2.1"
```
- NodeJS: `16.13.1`
