### ISSUE TITLE
The graphql-request typed SDK live example on the frontpage has a wrong configuration

### ISSUE THREAD

**Issue by fungiboletus** [dotansimha/graphql-code-generator#7339]
Hei,

If you select `graphql-request typed SDK` on the frontpage (https://www.graphql-code-generator.com), `codegen.yml` contains the following configuration:

```yaml
generates:
  sdk.ts:
    plugins:
      - typescript
      - typescript-graphql-request
```

But the genererated code `sdk.ts` is missing some important types because the plugin `typescript-operations` is not loaded. The correct configuration should be the following [according to the plugin documentation](https://www.graphql-code-generator.com/plugins/typescript-graphql-request):
```yaml
generates:
  sdk.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
```
