### ISSUE TITLE
near-operation-file incompatible with `noExport: true`

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [dotansimha/graphql-code-generator#7343]
**Describe the bug**
When choosing to use generated types as global types like `types.d.ts` in the src folder. It does break `near-operation-file` plugin since it tries to import from the types file.

**To Reproduce**
```yaml
schema: <schema>
documents: <documents>
generates:
  src/types.d.ts:
    plugins:
      - '@graphql-codegen/typescript'
      - '@graphql-codegen/typescript-operations'
    config:
      noExport: true
  src/graphql:
    preset: near-operation-file
    presetConfig:
      extension: .generated.ts
      baseTypesPath: '../types.d.ts'
    plugins:
      - '@graphql-codegen/typescript-operations'
```

https://codesandbox.io/s/gifted-agnesi-5lry5?file=/codegen.yml

**Expected behavior**

It should be possible to have a `noExport` in the near-operation-file
