### ISSUE TITLE
[typescript-urql-vue] does not prefix externally loaded DocumentNode and Operations

### ISSUE THREAD

**Issue by benkroeger** [dotansimha/graphql-code-generator#7360]
**Describe the bug**
When using the config option `importDocumentNodeExternallyFrom` with the plugin `typescript-urql-vue`, an import statement is generated - but type names and variables are not prefixed (as e.g. in `typescript-urql`)

**To Reproduce**
[CodeSandbox](https://codesandbox.io/s/laughing-panna-bk263?file=/composition-functions.ts)

line 1 imports `Operations`
line 7: uses `UserQuery` and `UserDocument` without `Operations.` prefix

1. My GraphQL schema:

```graphql
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}

```

2. My GraphQL operations:

```graphql
query user {
    user(id: 1) {
        id
        username
        email
    }
}

```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  document-nodes.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
  composition-functions.ts:
    plugins:
      - typescript-vue-urql
    config:
      documentMode: external
      importDocumentNodeExternallyFrom: './document-nodes'
      importOperationTypesFrom: Operations

```

**Expected behavior**
referenced types and documentNodes to be prefixed with `Operations.`

**Environment:**

- OS: Linux sse-sandbox-bk263 5.4.0-40-generic #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020 x86_64 GNU/Linux
- "@graphql-codegen/typed-document-node": "2.2.2"
- "@graphql-codegen/typescript": "2.4.2"
- "@graphql-codegen/typescript-operations": "2.2.2"
- "@graphql-codegen/typescript-vue-urql": "2.2.2"
- "@graphql-typed-document-node/core": "3.1.1"
- NodeJS: 14.18.1

**Additional context**
