### ISSUE TITLE
TypeError when spreading a fragment on a field of a different type

### ISSUE THREAD

**Issue by cecchi** [dotansimha/graphql-code-generator#7364]
**Describe the bug**

This seems likely to be related to #6874.

We have many union types in our schema, especially to define different groups of identity types (e.g. users, admins, or system users). It is technically valid GraphQL to define a fragment on one of these union types and spread it on a field that is a different union type, as long as the individual members of the union are compatible. 

This worked without issue when using `core@1.17.10` with `visitor-plugin-common@1.21.1`. After upgrading to `core@2.4.0` and `visitor-plugin-common@2.5.2` a `TypeError` is thrown (we are using the `near-operation-file-preset`, if relevant).

**To Reproduce**

Here's a code sandbox demonstrating the issue. I did my best to reduce the issue to the smallest reproduction possible.

https://codesandbox.io/s/silly-pateu-6dzgf?file=/src/document.gql

1. My GraphQL schema:

```graphql
scalar AnyId

### IDENTITIES

type ConsumerUser {
  id: AnyId!
  firstName: String!
  lastName: String!
}

type AdminUser {
  id: AnyId!
  firstName: String!
  lastName: String!
}

type SystemUser {
  id: AnyId!
}

### TICKETS

type Ticket {
  id: AnyId!
  createdBy: TicketAuthor
}

union TicketAuthor = AdminUser | SystemUser
union TicketRequester = ConsumerUser | AdminUser | SystemUser 

### QUERIES

type Query {
  ticket: Ticket!
}
```

2. My GraphQL operations:

```graphql
# This fragment is defined on type TicketRequester: a union of ConsumerUser | AdminUser | SystemUser
fragment TicketRequester on TicketRequester {
  ... on ConsumerUser {
    id
    userFirstName: firstName
    userLastName: lastName
  }
  ... on AdminUser {
    id
    operatorFirstName: firstName
    operatorLastName: lastName
  }
  ... on SystemUser {
    id
  }
}

query Ticket {
  ticket {
    id
    # This field is of type TicketAuthor, NOT TicketRequester
    # TicketAuthor is a union of AdminUser | SystemUser
    createdBy {
      ...TicketRequester
    }
  }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: src/**/*.gql
generates:
  src/generated/types.ts:
    - typescript
  src/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.tsx
      baseTypesPath: generated/types.ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
    config: 
      skipTypename: false
      nonOptionalTypename: true
      avoidOptionals: false
      enumsAsConst: true
      withHOC: false
      withComponent: true
      withHooks: true
      withMutationFn: true
      withResultType: true
      withMutationOptionsType: true
      documentMode: DocumentMode.documentNodeImportFragments
      dedupeFragments: true
      optimizeDocumentNode: true
      skipDocumentsValidation: true
      useTypeImports: true
```

**Expected behavior**
The code generation should succeed, or at a minimum should fail to validate if it's determined that this is invalid GraphQL (our server and previous version of `graphql-codegen` have been fine with this syntax historically). 

**Actual behavior**
```
TypeError: Cannot read property 'type' of undefined
        at /sandbox/node_modules/@graphql-codegen/visitor-plugin-common/index.js:3068:69
        at Array.map (<anonymous>)
        at PreResolveTypesProcessor.transformAliasesPrimitiveFields (/sandbox/node_modules/@graphql-codegen/visitor-plugin-common/index.
js:3058:23)
        at SelectionSetToObject.buildSelectionSetString (/sandbox/node_modules/@graphql-codegen/visitor-plugin-common/index.js:2880:32)
        at /sandbox/node_modules/@graphql-codegen/visitor-plugin-common/index.js:2762:41
        at Array.reduce (<anonymous>)
        at SelectionSetToObject._buildGroupedSelections (/sandbox/node_modules/@graphql-codegen/visitor-plugin-common/index.js:2752:80)
        at SelectionSetToObject.transformSelectionSet (/sandbox/node_modules/@graphql-codegen/visitor-plugin-common/index.js:2921:54)
        at SelectionSetToObject.buildSelectionSetString (/sandbox/node_modules/@graphql-codegen/visitor-plugin-common/index.js:2870:89)
        at /sandbox/node_modules/@graphql-codegen/visitor-plugin-common/index.js:2762:41
```
