### ISSUE TITLE
Typed schema generated with typescript-urql-graphcache plugin doesn't preserve typesPrefix case

### ISSUE THREAD

**Issue by gyermich** [dotansimha/graphql-code-generator#7382]
**Describe the bug**
Typed schema generated with `typescript-urql-graphcache` plugin doesn't preserve `typesPrefix` case (e.g. 'GQL' -> becomes 'Gql'):

**To Reproduce**

1) The `codegen.yml` file:
```yaml
overwrite: true
schema: 'http://localhost:3000/graphql'
documents: 'src/graphql/**/*.graphql'
generates:
  src/generated/graphql.tsx:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-urql'
      - 'typescript-urql-graphcache'
    config:
      typesPrefix: GQL
```

2) Run `graphql-codegen --config codegen.yml`

3) Results:
generated type:

```
export type GQLRating = {
  __typename?: 'Rating';
  id: Scalars['ID'];
  ...
};
```
Generated schema:

```
 Rating?: {
    id?: GraphCacheResolver<WithTypename<GqlRating>,
...
}
```

**Expected behavior**
`typePrefix` case should be preserved in the generated schema:

```
 Rating?: {
    id?: GraphCacheResolver<WithTypename<GQLRating>,
...
}
```
