### ISSUE TITLE
[TypeScript React-Query] isReactHook with custom fetcher in mutations throws React Hook "useFetch" cannot be called inside a callback.

### ISSUE THREAD

**Issue by ilovett** [dotansimha/graphql-code-generator#7404]
**Describe the bug**

Cannot use generated mutation hooks where custom fetcher is a hook because `useFetch` is inside of a callback:

```ts
(variables?: MyMutationVariables) => useFetch<MyMutation, MyMutationVariables>(MyDocument, variables)(),
```

This will throw:

```
React Hook "useFetch" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function  react-hooks/rules-of-hooks
```

Seems to work fine for generated queries since `useFetch` is called in the top level scope.

Suggest the mutation template adds `const fetcher = useFetch();` to the top level scope.

**To Reproduce**

3. My `codegen.yml` config file:

```yml
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-query
    config:
      fetcher: '../apiUtils#useFetch'
      isReactHook: true
```

**Expected behavior**

**Environment:**

@graphql-codegen/typescript-react-query@3.3.1

**codesandbox** 

https://codesandbox.io/s/twilight-surf-i4vuw?file=/types.ts

![image](https://user-images.githubusercontent.com/1776100/150866731-835f3867-f222-46af-bbfa-f699737aa361.png)
