### ISSUE TITLE
react-query + customFetcher generates invalid TypeScript (`TS6133: 'RequestInit' is declared but its value is never read.`)

### ISSUE THREAD

**Issue by sampi** [dotansimha/graphql-code-generator#7444]
**Describe the bug**
`import { RequestInit } from 'graphql-request/dist/types.dom';` is added to generated output even when using a custom fetcher. This is never used, so I'm getting the following error from `tsc`:
```
TS6133: 'RequestInit' is declared but its value is never read.
```

**To Reproduce**

Check the first line of the generated file:
https://codesandbox.io/s/romantic-mirzakhani-57us1?file=/types.ts:0-62

1. use `typescript-react-query`
2. use custom fetcher, like `func: '../fetcher#useFetchData'
3. generate code
4. try to build app

1. My GraphQL schema:

no schema, this is a compile-time error

2. My GraphQL operations:

no operations, this is a compile-time error

3. My `codegen.yml` config file:

```yml
schema:
  - ${REACT_APP_GRAPHQL_ENDPOINT}
documents:
  - './src/**/*.graphql'
overwrite: true
generates:
  src/gql/generated/index.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-query
    config:
      fetcher:
        func: '../fetcher#useFetchData'
        isReactHook: true
        exposeQueryKeys: true
```

**Expected behavior**

**Environment:**

- OS: macOS `12.2` on Apple Silicon
  - `@graphql-codegen/cli`: `2.4.0`
  - `@graphql-codegen/introspection`: `2.1.1`
  - `@graphql-codegen/typescript`: `2.4.2`
  - `@graphql-codegen/typescript-operations`: `2.2.3`
  - `@graphql-codegen/typescript-react-query`: `3.5.0`
- NodeJS: `14.18.3`
- Typescript: `4.5.5`

**Additional context**

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "strictNullChecks": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "sourceMap": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "downlevelIteration": true
  },
  "include": ["src", "types"]
}

```
