### ISSUE TITLE
Optional query input array variable can accept non-array values

### ISSUE THREAD

**Issue by csandanov** [dotansimha/graphql-code-generator#7480]
**Describe the bug**
Optional query array variable can accept non-array value

**To Reproduce**

[Steps to reproduce the behavior:](https://codesandbox.io/s/autumn-sun-i4sq8?file=/types.ts)

1. My GraphQL schema:

```graphql
type Query {
    users(ids: [ID!]): [User!]!
}

type User {
    id: ID!
    username: String!
    email: String!
}

```

2. My GraphQL operations:

```graphql
query users($ids: [ID!]) {
    users(ids: $ids) {
        id
        username
        email
    }
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations

```

4. See `types.ts`: type of `id` field in `UsersQueryVariables` generated as `InputMaybe<Array<Scalars['ID']> | Scalars['ID']>;` despite it being defined as optional array. Before I updated to the latest version it worked fine – generated as `InputMaybe<Array<Scalars['ID']>>`;.

**Expected behavior**

`id` field in `UsersQueryVariables` should have type `InputMaybe<Array<Scalars['ID']>>;`

**Environment:**

- OS: macOS 12.1
- `@graphql-codegen/cli`: 2.5.0
- NodeJS: 17.4.0
