### ISSUE TITLE
Generate Unable to load GraphQL Schemas

### ISSUE THREAD

**Issue by krazyjakee** [dotansimha/graphql-code-generator#7518]
**Describe the bug**
Unable to load GraphQL Schemas

```
  ✖ ./types/graphql.tsx
    Failed to load schema from https://cms.iotdb.com/graphql,loader:

        Cannot read property 'loader' of null
        TypeError: Cannot read property 'loader' of null
    at Array.collectCustomLoader (C:\Users\krazy\Documents\GitHub\iotdb-site\node_modules\@graphql-tools\load\index.js:351:24) 
    at next (C:\Users\krazy\Documents\GitHub\iotdb-site\node_modules\@graphql-tools\load\index.js:172:23)
    at Array.collectDocumentString (C:\Users\krazy\Documents\GitHub\iotdb-site\node_modules\@graphql-tools\load\index.js:348:5)
    at C:\Users\krazy\Documents\GitHub\iotdb-site\node_modules\@graphql-tools\load\index.js:175:15
    at collectSources (C:\Users\krazy\Documents\GitHub\iotdb-site\node_modules\@graphql-tools\load\index.js:261:9)
    at loadTypedefs (C:\Users\krazy\Documents\GitHub\iotdb-site\node_modules\@graphql-tools\load\index.js:512:27)
    at Object.loadSchema (C:\Users\krazy\Documents\GitHub\iotdb-site\node_modules\@graphql-tools\load\index.js:612:27)
    at loadSchema (C:\Users\krazy\Documents\GitHub\iotdb-site\node_modules\@graphql-codegen\cli\bin.js:495:35)
    at CodegenContext.loadSchema (C:\Users\krazy\Documents\GitHub\iotdb-site\node_modules\@graphql-codegen\cli\bin.js:784:32)  
    at C:\Users\krazy\Documents\GitHub\iotdb-site\node_modules\@graphql-codegen\cli\bin.js:1034:79
```

**To Reproduce**
Fork this: https://codesandbox.io/s/confident-bartik-02t5m?file=/codegen.yml
Run `yarn generate` in the terminal

1. My GraphQL schema:

```graphql
https://cms.iotdb.com/graphql
```

2. My GraphQL operations:

```graphql
query LatestHardware {
  hardware(sort: "-date_created", limit: 25) {
    id
    name
    images {
      directus_files_id {
        id
      }
    }
    manufacturer {
      id
      name
    }
    function {
      functions_id {
        id
        name
      }
    }
  }
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true
schema:
  - https://cms.iotdb.com/graphql:
    headers:
      Authorization: "Bearer 1oDO02$2HejI"
documents: "document.graphql"
generates:
  graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
```

**Expected behavior**
Should generate types

**Environment:**

- OS: Windows
"@graphql-codegen/typescript": "2.4.3",
"@graphql-codegen/typescript-operations": "2.3.0",
"@graphql-codegen/typescript-react-apollo": "3.2.5",
"@graphql-codegen/introspection": "2.1.1"
- NodeJS: v14.17.0

**Comment by ardatan** [comment]
I think it is an indentation problem;
```yml
overwrite: true
schema:
  - https://cms.iotdb.com/graphql: ## Here `headers` should be in the next level
      headers:
         Authorization: "Bearer 1oDO02$2HejI"
documents: "document.graphql"
generates:
  graphql.tsx:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-apollo"
```
