### ISSUE TITLE
@graphql-codegen/near-operation-file-preset does not import root Types when a fragment spread a fragment but does not query any fields itself.

### ISSUE THREAD

**Issue by alextuppen** [dotansimha/graphql-code-generator#7547]
**Describe the bug**
Where a parent fragment only spreads child fragment(s), and that child includes an enum, but the parent does not reference fields itself, it only spreads fragments. The near-operation-file preset does not import the root `Types` namespace causing a TypeScript error when the file references the enum with `Types.enum`.

**To Reproduce**
Create a repo with 3 folders, one that contains a root query file, another that contains a fragment that fetches something from the API and a third that spreads the afore mentioned fragment (but does not fetch anything itself). Then spread the second fragment in the query and generate.

Working reproduction: https://codesandbox.io/s/divine-voice-zjt60q?file=/src/fragment/fragment.graphql

1. My GraphQL schema:

```graphql
type Query {
    test: Test
}

type Test {
    UUID: ID
    sampleEnum: SampleEnum
}

enum SampleEnum {
    Foo
    Bar
}
```

2. My GraphQL operations:

```graphql
query test {
    test {
        ...FragmentSpreadFragment
    }
}
```

```graphql
fragment FragmentSpreadFragment on Test {
  # Uncomment this to make the generated file import Types
  # UUID
  ...Fragment
}
```

```graphql
fragment Fragment on Test {
    sampleEnum
}
```

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
documents: 'src/**/*.graphql'
generates:
  src/types.ts:
    plugins:
      - typescript
  src/:
    preset: near-operation-file
    presetConfig:
      extension: .generated.tsx
      baseTypesPath: types.ts
    plugins:
      - typescript-operations
      - typescript-urql

```

**Expected behaviour**
The generated file should include the Types import as it is referenced in the file.

**Environment:**

- OS: macOS 11.6.1
- `@graphql-codegen/...`: All dependencies are latest and match what is used in the reproduction
- NodeJS: 14.8.1

**Additional context**
This requirement came about because I have a React component that is rendered in two places, those two places do not need anything from the API themselves so they just spread their child's fragment.
