### ISSUE TITLE
Typescript Apollo Angular with documentMode external fails to generate

### ISSUE THREAD

**Issue by aspectgfg** [dotansimha/graphql-code-generator#7551]
**Describe the bug**
```
gen/operations/src/ApolloAngular.ts:
    plugins:
      - time
      - typescript-apollo-angular
    config:
      documentMode: external
      importDocumentNodeExternallyFrom: './ops'
```

Results in
```
import * as Operations from './ops';
import { Injectable } from '@angular/core';
import * as Apollo from 'apollo-angular';
// Generated on 2022-02-16T11:46:55-08:00

@Injectable({
  providedIn: 'root',
})
export class ViewerGQL extends Apollo.Query<ViewerQuery, ViewerQueryVariables> {
  document = ViewerDocument;

  constructor(apollo: Apollo.Apollo) {
    super(apollo);
  }
}
```

The workaround for documentMode: external on most libraries is: `typesPrefix: Operations.`

For example:
```
gen/operations/src/GraphQLRequest.ts:
    plugins:
      - time
      - typescript-graphql-request
    config:
      documentMode: external
      importDocumentNodeExternallyFrom: './ops'
      typesPrefix: Operations.
```

When using `typesPrefix: Operations.` in angular, we end up resolving our Operations types correctly, but class names get mangled, and DocumentNodes are still not even prefixed properly:

```
 export class Operations.ViewerGQL extends Apollo.Query<Operations.ViewerQuery, Operations.ViewerQueryVariables> {
    document = ViewerDocument;
    
    constructor(apollo: Apollo.Apollo) {
      super(apollo);
    }
  }
```
Operations.ViewerQuery and Operations.ViewerVariables resolve correctly
the classname Operations.ViewerGQL is an invalid classname
ViewerDocument still fails to resolve, it should have been prefixed with Operations.

Good luck,
z
