### ISSUE TITLE
Typescript Urql fails on documentMode external and does not apply typesPrefix properly

### ISSUE THREAD

**Issue by aspectgfg** [dotansimha/graphql-code-generator#7552]
**Describe the bug**
documentMode external fails to generate properly
current workaround in most libraries is to add a typesPrefix when using documentMode: external

so we add typesPrefix `Operations.`
```
gen/operations/src/Urql.ts:
    plugins:
      - time
      - typescript-urql
    config:
      documentMode: external
      importDocumentNodeExternallyFrom: './ops'
      typesPrefix: Operations.
```

Generates
```
import * as Operations from './ops';
import * as Urql from 'urql';
export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
// Generated on 2022-02-16T12:00:20-08:00


export function useViewerQuery(
  options?: Omit<Urql.UseQueryArgs<Operations.ViewerQueryVariables>, 'query'>
) {
  return Urql.useQuery<Operations.ViewerQuery>({ query: ViewerDocument, ...options });
}
```
operations.ViewerQuery and Operations.ViewerQueryVariables are correct, by ViewerDocument is missing the prefix

To replicate, generate any external operations file and urql

....
Generation result without TypesPrefix, documentMode external, no operation types or document nodes resolve
```
import * as Operations from './ops';
import * as Urql from 'urql';
export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
// Generated on 2022-02-16T12:07:28-08:00

export function useViewerQuery(
  options?: Omit<Urql.UseQueryArgs<ViewerQueryVariables>, 'query'>
) {
  return Urql.useQuery<ViewerQuery>({ query: ViewerDocument, ...options });
}
```
