### ISSUE TITLE
Directive resolver input arguments type ignores enumPrefix = false

### ISSUE THREAD

**Issue by bmarker** [dotansimha/graphql-code-generator#7560]
**Describe the bug**
The generated directive arguments ignore enumPrefix = false. This results in the wrong type name when typesPrefix is set.

**To Reproduce**
https://codesandbox.io/s/pedantic-lalande-q0g1qr?file=/types.ts

Set enumPrefix = false and typesPrefix = I.

Define a directive with an input argument that is an enum and generate the resolvers.

1. My GraphQL schema:

```graphql
enum TestEnum {
    ONE
    TWO
}

directive @debug(in: TestEnum) on FIELD_DEFINITION | OBJECT
```

2. My GraphQL operations:
None

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      typesPrefix: I
      enumPrefix: false
      defaultMapper: unknown
```

Setting `defaultMapper` works around another name collision with the default `IResolversTypes` and `IResolversParentTypes`. Normally I'd map the model types.

**Expected behavior**
Does not add the types prefix to the enum type in the input args type for the directive resolver.

**Environment:**
https://codesandbox.io/s/pedantic-lalande-q0g1qr?file=/types.ts

**Additional context**
I don't actually need the directives so a skip directives option would work as well.
I may be able to get a hook to rename it as a workaround for now.
