### ISSUE TITLE
enumPrefix = false applying to non-enum types

### ISSUE THREAD

**Issue by bmarker** [dotansimha/graphql-code-generator#7562]
**Describe the bug**
The enumPrefix = false config setting is stripping the prefix from non-enum types in `IResolversTypes` and `IResolversParentTypes`.

**To Reproduce**
https://codesandbox.io/s/quirky-proskuriakova-vmpz0v?file=/types.ts

1. My GraphQL schema:

```graphql
type Query {
    user: User!
}

type User {
    name: String!
}
```

2. My GraphQL operations:

None

3. My `codegen.yml` config file:

```yml
schema: schema.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-resolvers
    config:
      typesPrefix: I
      enumPrefix: false
```

**Expected behavior**
Only skip the type prefix for enum types. The type for `User` should match the generated type `IUser`.
```
export type IResolversParentTypes = {
  Boolean: Scalars['Boolean'];
  Query: {};
  String: Scalars['String'];
  User: IUser;
};
```

Instead of:
```
export type IResolversParentTypes = {
  Boolean: Scalars['Boolean'];
  Query: {};
  String: Scalars['String'];
  User: User;
};
```

**Environment:**
https://codesandbox.io/s/quirky-proskuriakova-vmpz0v?file=/types.ts

```
    "@graphql-codegen/add": "^3.1.1",
    "@graphql-codegen/cli": "^2.4.0",
    "@graphql-codegen/typescript": "2.4.5",
    "@graphql-codegen/typescript-resolvers": "2.5.2",
    "graphql": "^16.2.0"
```

**Additional context**
Also happens with `typesSuffix` set and using `{T}` in `defaultMapper`.
