### ISSUE TITLE
Infinite rendering occurs when date or datetime type values are used as arguments.

### ISSUE THREAD

**Issue by mayone-du** [dotansimha/graphql-code-generator#7565]
**Describe the bug**
 

**To Reproduce**

<!--
#############
#############
🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 🛑 STOP! 

PLEASE READ THE FOLLOWING: 
You can use this template to create a live sandbox of the issue: 
https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template
Make sure to fork this template, and run `yarn generate` in the terminal. 
Please make sure the Codegen and plugins version under `package.json` matches yours. 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~ ISSUES WITH A LIVE REPRODUCTION WILL BE ANSWERED QUICKLY ~~~~~~~
~~~~~~ ISSUES WITHOUT REPRODUCTION MIGHT GET CLOSED WITHOUT RESPONSE ~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#############
#############
-->

1. My GraphQL schema:

```graphql
# Put your schema here
type Query {
  test(customArg: String): String
}
```

2. My GraphQL operations:

```graphql
# Put your operations herequery Test($customArg: String!) {
  test(customArg: $customArg)
}
```

3. My `codegen.yml` config file:

```yml
# Put your YML here
schema: http://localhost:4000/graphql/
documents: src/graphql/operations/**/*.graphql
generates:
  src/graphql/schemas/generated/schema.ts:
    plugins:
    - typescript
    - typescript-operations
    - typescript-react-apollo
config:
  namingConvention:
    transformUnderscore: true
  scalars:
    BigInt: bigint
    DateTime: string
    EmailAddress: string

```

**Expected behavior**
<!-- A clear and concise description of what you expected to happen. -->

**Environment:**

- OS: MacOS 12.1
- `@graphql-codegen/...`: 
```
    "@graphql-codegen/cli": "^2.6.1",
    "@graphql-codegen/typescript": "^2.4.3",
    "@graphql-codegen/typescript-operations": "^2.3.0",
    "@graphql-codegen/typescript-react-apollo": "^3.2.5",
```
- NodeJS: 16.11.1

**Additional context**
<!-- Add any other context about the problem here. -->

If you pass dayjs().toISOString() or new Date().toString(), infinite rendering will occur.

With dayjs().toString(), it was not infinite rendering, but it was extra rendering.

I don't know if it's a bug in graphql-code-generator or in GraphQL.js, but I'm sorry if this is the wrong place to post this.
Is there anything I can do to help?
