### ISSUE TITLE
Bug - React "Error: Too many re-renders. React limits the number of renders to prevent an infinite loop."

### ISSUE THREAD

**Issue by GuilhermeSantos001** [dotansimha/graphql-code-generator#7588]
**Describe the bug**
 

**To Reproduce**
I`m called a simple hook, but https://i.imgur.com/Ow80Ias.png.

Not working: https://i.imgur.com/Ow80Ias.png
```Not Working:
const [{ data, error }] = useGetUserInfoQuery({
  variables: {
    auth
  },
  context: {}
});
```

Working: https://i.imgur.com/SN2lWuk.png
```Working:
const [{ data, error }] = useGetUserInfoQuery({
  variables: {
    auth
  }
});
```

1. My GraphQL schema:

```graphql
BIG FILE!
```

2. My GraphQL operations:

```graphql
query GetUserInfo($auth: String!) {
  getUserInfo(auth: $auth) {
    privileges
    privilege
    photoProfile
    username
    email
    name
    surname
    cnpj
    location {
      street
      number
      complement
      district
      state
      city
      zipcode
    }
    updatedToken {
      signature
      token
    }
  }
}
```

3. My `codegen.yml` config file:

```yml
overwrite: true

schema: 'http://localhost/graphql'

documents: './graphql/**/*.gql'

generates:
  src/generated/graphql.tsx:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-urql'
    config:
      withHooks: true

hooks:
  afterAllFileWrite:
    - eslint --fix
```

**Expected behavior**

**Environment:**

- OS: Ubuntu 20.04 LTS
- "@graphql-codegen/cli": "^2.6.2"
- "@graphql-codegen/import-types-preset": "^2.1.12"
- "@graphql-codegen/typescript": "^2.4.5"
- "@graphql-codegen/typescript-operations": "^2.3.2",
- "@graphql-codegen/typescript-urql": "^3.5.3" 
- NodeJS: v16.14.0
