### ISSUE TITLE
If enumValues and enumsAsTypes is set, codegen should emit export type

### ISSUE THREAD

**Issue by alamothe** [dotansimha/graphql-code-generator#7589]
If we set both `enumValues` and `enumsAsTypes`:
```yml
schema: src/schema.json
overwrite: true
generates:
  src/graphql-types.ts:
    config:
      enumsAsTypes: true
      enumValues: ./graphql-enums
    plugins:
      - typescript
```

It will emit exports in the generated file:
```ts
export { CarStatus };
export { ReservationStatus };
// ...
```
Emitting exports is fine, however because these are just types, they will break **babel**. Instead, it needs to be:
```ts
export type { CarStatus };
export type { ReservationStatus };
// ...
```
This should be controlled by `enumsAsTypes` option which is completely logical, even though the enums are not generated by [graphql-code-generator](https://github.com/dotansimha/graphql-code-generator)
