### ISSUE TITLE
typescript-react-query doesn't respect `useTypeImports` from `react-query`

### ISSUE THREAD

**Issue by jonathanstanley** [dotansimha/graphql-code-generator#7666]
### Issue workflow progress

- [ ] 1. The issue provides a reproduction available on [Github](https://github.com/dotansimha/graphql-code-generator-issue-sandbox-template), [Stackblitz](https://stackblitz.com/github/dotansimha/graphql-code-generator-issue-sandbox-template) or [CodeSandbox](https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template)

- [ ] 2. A failing test has been provided

- [x] 3. A local solution has been provided

- [x] 4. A pull request is pending review

---

**Describe the bug**
when using `useTypeImports`, generated code is incorrect.  it should be:

```diff
- import { useQuery, UseQueryOptions, useMutation, UseMutationOptions } from 'react-query';
+ import { useQuery, useMutation } from 'react-query';
+ import type { UseQueryOptions, UseMutationOptions } from 'react-query';
```

**To Reproduce**
caused when config has the following:

- typescript-react-query plugin
- useTypeImports: true

1. My GraphQL schema:

```graphql
# any
```

2. My GraphQL operations:

```graphql
# any
```

3. My `codegen.yml` config file:

```yml
schema:
  - ${APIURL}
documents: "my-codegen-src/*.graphql"
generates:
  my-codegen-out/reactQuery.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-query
      useTypeImports: true
```

**Expected behavior**
Types need to be tracked separately and imports should respect the `useTypeImports` flag.

**Environment:**
-any

**Additional context**
Similar to #7661 (but not identical). Sending PR to fix this.
