### ISSUE TITLE
Vue3 compatibility for vue-apollo-smart-ops

### ISSUE THREAD

**Issue by greydelta** [dotansimha/graphql-code-generator#7678]
**Is your feature request related to a problem? Please describe.**

Currently, [TypeScript Vue Apollo Smart Operations
](https://www.graphql-code-generator.com/plugins/typescript-vue-apollo-smart-ops) imports [vue-apollo-smart-ops](https://www.npmjs.com/package/vue-apollo-smart-ops) upon file generation

The issue is [vue-apollo-smart-ops](https://www.npmjs.com/package/vue-apollo-smart-ops)'s dependency is using [vue-apollo v3](https://www.npmjs.com/package/vue-apollo) (only supports Vue2) and will trigger an error below:

![image](https://user-images.githubusercontent.com/55234616/159527500-0911f373-ced9-490c-8d68-8527a94fcfd1.png)

**Describe the solution you'd like**

Hence, I hope to see [vue-apollo-smart-ops](https://www.npmjs.com/package/vue-apollo-smart-ops)'s dependency updated to [vue-apollo v4](https://v4.apollo.vuejs.org/) with support for Vue3

**Describe alternatives you've considered**

For now, the workaround seems to be using [TypeScript Vue Urql](https://www.graphql-code-generator.com/plugins/typescript-vue-urql) which works well~!

**Additional context**

vue-apollo v4 package in [alpha](https://www.npmjs.com/package/@vue/apollo-option)

**Comment by vknowles-rv** [comment]
Opened a PR to support new vue/vue-apollo versions: https://github.com/equalogic/vue-apollo-smart-ops/pull/161

Hopefully the maintainer is able to review.

Just FYI, it is possible to [provide a custom source to import operations from](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/vue-apollo-smart-ops/src/config.ts#L56). May be possible to fork the branch from the PR above and see how things go. You will need to update where ApolloError imports from via `vueApolloErrorTypeImportFrom`

example

```yaml
generates:
  ./autogenerated/types/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-vue-apollo-smart-ops
    config:
      vueApolloErrorTypeImportFrom: '@apollo/client/core'
```
