### ISSUE TITLE
Invalid document completely halts compilation

### ISSUE THREAD

**Issue by sarink** [dotansimha/graphql-code-generator#7765]
When working in a monorepo and using the following standard configuration:

```
schema: api/src/resolvers/**/*.ts

documents: web/src/**/*.tsx

generates:
  api/src/api-types.ts:
    plugins:
      - typescript
      - typescript-resolvers

  web/src/web-types.ts:
    plugins:
      - typescript
      - typescript-operations
```

If a valid but breaking change is made to an api resolver, the entire compilation process will error when trying to generate the `web-types`, and the new `api-types` will never get created.

Is there some kind of `assumeValidDocuments` flag that can be switched on? This is a confusing workflow for a backend developer
