### ISSUE TITLE
The `typescript-urql-graphcache` plugin does not respect the `import-types` preset configuration

### ISSUE THREAD

**Issue by ka1to1** [dotansimha/graphql-code-generator#7779]
**Describe the bug**

**To Reproduce**

1. My GraphQL schema:
N/A

2. My GraphQL operations:
N/A

3. My `codegen.yml` config file:

```yaml
schema: http://192.168.0.11:8080/graphql
documents: 'src/**/*.graphql'

generates:
  ./src/schema.ts:
    hooks:
      afterOneFileWrite:
        - eslint --fix
    plugins:
      - typescript

    config:
      maybeValue: T | undefined
      useTypeImports: true

  ./src/index.ts:
    preset: import-types

    presetConfig:
      typesPath: ./schema
      importTypesNamespace: Schema

    hooks:
      afterOneFileWrite:
        - eslint --fix

    plugins:
      - typescript-operations
      - typescript-resolvers
      - typed-document-node
      - urql-svelte-operations-store
      - typescript-urql-graphcache

    config:
      maybeValue: T | undefined
      useTypeImports: true

  ./src/schema.graphql:
    plugins:
      - schema-ast
```

**Expected behavior**
Generating `typescript-urql-graphcache` should generate types with the respected namespace (in this case schema) but instead it ignores it.
For example, here is the output generated by another plugin. The namespace is respected (ie. `Schema.Address`)
```ts
export type ResolversTypes = {
  Address: ResolverTypeWrapper<Schema.Address>;
}

Here is the output of `typescript-urql-graphcache`:
```ts
export type GraphCacheKeysConfig = {
  Address?: (data: WithTypename<Address>) => null | string,
```
In this case the namespace is not respected.

**Environment:**

- OS: macOS 12.3
- `@graphql-codegen/...`: 
```json
    {
    "@graphql-codegen/cli": "^1.21.8",
    "@graphql-codegen/import-types-preset": "^2.1.15",
    "@graphql-codegen/near-operation-file-preset": "^2.2.9",
    "@graphql-codegen/schema-ast": "^1.18.3",
    "@graphql-codegen/typed-document-node": "^2.2.8",
    "@graphql-codegen/typescript": "^1.23.0",
    "@graphql-codegen/typescript-operations": "^1.18.4",
    "@graphql-codegen/typescript-resolvers": "^2.6.1",
    "@graphql-codegen/typescript-urql-graphcache": "^2.2.10",
    "@graphql-codegen/urql-svelte-operations-store": "^1.1.15"
    }
```
- NodeJS: 16.5.0

**Additional context**
