### ISSUE TITLE
Can't disable watch mode from CLI

### ISSUE THREAD

**Issue by rohit-gohri** [dotansimha/graphql-code-generator#7780]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a reproduction available on [Github](https://github.com/dotansimha/graphql-code-generator-issue-sandbox-template), [Stackblitz](https://stackblitz.com/github/dotansimha/graphql-code-generator-issue-sandbox-template) or [CodeSandbox](https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template)

_Make sure to fork this template and run `yarn generate` in the terminal._

_Please make sure the Codegen and plugins version under `package.json` matches yours._

https://codesandbox.io/s/cranky-glade-2lgzl1?file=/package.json

- [ ] 2. A failing test has been provided

- [ ] 3. A local solution has been provided

- [ ] 4. A pull request is pending review

---

**Describe the bug**

**To Reproduce**

1. My GraphQL schema:

```graphql
# Not relevant
```

2. My GraphQL operations:

```graphql
# Not relevant
```

3. My `codegen.yml` config file:

```yaml
schema: schema.graphql
documents: document.graphql
# Only change from template
watch: true
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations

```

4. Run `graphql-codegen --config ./codegen.yml --watch false` 

**Expected behavior**

Codegen should run once and exit the process.

**Actual behavior**

Codegen keeps running in watch mode.

**Environment:**

- OS:
- `@graphql-codegen/...`:
- NodeJS:

**Additional context**
