### ISSUE TITLE
fragment type definitions are not imported when `inlineFragmentType: mask` and `near-opeartion-file` preset

### ISSUE THREAD

**Issue by izumin5210** [dotansimha/graphql-code-generator#7798]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [x] 1. The issue provides a reproduction available on [GitHub](https://github.com/dotansimha/graphql-code-generator-issue-sandbox-template), [Stackblitz](https://stackblitz.com/github/dotansimha/graphql-code-generator-issue-sandbox-template) or [CodeSandbox](https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template)

> Make sure to fork this template and run `yarn generate` in the terminal.
>
> Please make sure the Codegen and plugins version under `package.json` matches yours.

- [x] 2. A failing test has been provided
- [x] 3. A local solution has been provided
- [x] 4. A pull request is pending review

---

**Describe the bug**

When `inlineTypeFragment` is set to `mask` and near-operation-file preset is enabled, Fragment type definitions defined in another file are not imported

**To Reproduce**

CodeSandbox: https://codesandbox.io/s/graphql-codegen-typescript-operations-inlinefragmenttypes-mask-import-bug-pbcfpv

1. My GraphQL schema:

```graphql
type Post {
  title: String!
  author: User!
}

type User {
  name: String!
}

type Query {
  posts: [Post!]!
}
```

2. My GraphQL operations:

```ts
// AuthorName.jsx

export const AuthorNameFragment = /* GraphQL */ `
  fragment AuthorName on User {
    name
  }
`;
```

```ts
// PostItem.jsx

import { AuthorNameFragment } from "./AuthorName";

export const PostItemFragment = /* GraphQL */ `
  fragment PostItem on Post {
    author {
      ...AuthorName
    }
  }
  ${AuthorNameFragment}
`;
```

3. My `codegen.yml` config file:

```yaml
schema: schema.graphql
documents: ./src/**/*.jsx
generates:
    ./src/__generated__/graphqlTypes.ts:
      plugins:
        - typescript
    ./src:
      preset: near-operation-file
      presetConfig:
        baseTypesPath: __generated__/graphqlTypes.ts
        folder: __generated__
        extension: .graphql.ts
      plugins:
        - typescript-operations
      config:
        inlineFragmentTypes: mask
```

**Expected behavior**

The `AuthorNameFragment` should be imported, but is not in the generated code
![image](https://user-images.githubusercontent.com/2010175/165523191-f8dee1fa-d713-4658-997f-c7fa4278c28b.png)

**Environment:**

- OS: Linux
- `@graphql-codegen/...`: 
  - @graphql-codegen/cli` 2.6.2
  - @graphql-codegen/near-operation-file-preset` 2.2.9
  - @graphql-codegen/typescript` 2.4.8
  - @graphql-codegen/typescript-operations` 2.3.5
- NodeJS: 14.18.1

**Additional context**
