### ISSUE TITLE
[React Query] addInfiniteQuery option imports QueryFunctionContext without usage

### ISSUE THREAD

**Issue by evancloutier** [dotansimha/graphql-code-generator#7802]
Hi there! I've been having lots of success with code generation using the React Query plugin.

Was adding the `addInfiniteQuery` option into my `codegen.yml` file, and noticed that it imports `QueryFunctionContext` from `react-query` unnecessarily according to my configuration. This sets off my ESLint rules, and I'm currently having to remove the import manually before committing any code.

The line in question is here: https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/react-query/src/visitor.ts

I've provided my `codegen.yml` below – perhaps it is an issue of my custom fetching function? Happy to push up a PR to resolve this.

```yaml
overwrite: true
schema: "http://localhost:4000/v1/graph"
documents: "graphql/**/index.ts"
generates:
  graphql/generated.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "typescript-react-query"
    config:
      addInfiniteQuery: true
      exposeFetcher: true
      exposeMutationKeys: true
      exposeQueryKeys: true
      fetcher:
        func: ../utils/gql-fetch#gqlFetch
      fetchParams:
        headers:
          Content-Type: application/json
      maybeValue: T
    hooks:
      afterOneFileWrite:
        - prettier --write
```
