### ISSUE TITLE
Generated possible types missing correct indentation

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [dotansimha/graphql-code-generator#7816]
**Describe the bug**
Generating an empty possible types file
```js

      export interface PossibleTypesResultData {
        possibleTypes: {
          [key: string]: string[]
        }
      }
      const result: PossibleTypesResultData = {
  "possibleTypes": {}
};
      export default result;
    
```

**To Reproduce**

3. My `codegen.yml` config file:

```yaml
overwrite: true
schema: 'http://localhost:3000/graphql'
documents: ./src/graphql/**/*.ts
generates:
  src/types/graphql-generated.ts:
    plugins:
      - 'fragment-matcher'
 ```

**Expected behavior**

The code should be indented properly
