### ISSUE TITLE
[graphql-modules-preset] Allow implementing `__resolveReference` for Federation Entities

### ISSUE THREAD

**Issue by Ty3uK** [dotansimha/graphql-code-generator#7827]
**Is your feature request related to a problem? Please describe.**

`graphql-modules-preset` doesn't allow to implement `__resolveReference` resolver for Federation Entity

**Describe the solution you'd like**

I want to add `federation` option to config (just like it is in `typescript-resolvers` plugin). Based on this option I will add types with `@key` directive to some array and at to `printResolveSignaturesPerType` function some logic for picking extra field `__resolveReference`

**Describe alternatives you've considered**

I have no alternative thoughts 😬

**Additional context**

With this example schema:

```graphql
type Product @key(fields: "id") @shareable {
    id: ID!
    name: String!
    price: Float!
}
```

I get this generated types:

```ts
/* eslint-disable */
import * as Types from "../../types/graphql.gen";
import * as gm from "graphql-modules";
export namespace ProductModule {
  interface DefinedFields {
    Product: 'id' | 'name' | 'price';
  };
  
  export type Product = Pick<Types.Product, DefinedFields['Product']>;
  
  export type ProductResolvers = Pick<Types.ProductResolvers, DefinedFields['Product'] | '__isTypeOf'>;
  
  export interface Resolvers {
    Product?: ProductResolvers;
  };
  
  export interface MiddlewareMap {
    '*'?: {
      '*'?: gm.Middleware[];
    };
    Product?: {
      '*'?: gm.Middleware[];
      id?: gm.Middleware[];
      name?: gm.Middleware[];
      price?: gm.Middleware[];
    };
  };
}
```

An if I want to implement `__resolveReference` from `typescript-resolvers`, I get this error:

```
src/modules/product/resolvers.ts:7:15 - error TS2322: Type '{ __resolveReference(ref: any, context: any): Promise<Product | null>; }' is not assignable to type 'ProductResolvers'.
  Object literal may only specify known properties, and '__resolveReference' does not exist in type 'ProductResolvers'.

7         async __resolveReference(ref, context) {
                ~~~~~~~~~~~~~~~~~~

  src/modules/product/types.gen.ts:14:5
    14     Product?: ProductResolvers;
           ~~~~~~~
    The expected type comes from property 'Product' which is declared here on type 'Resolvers'

src/modules/product/resolvers.ts:7:34 - error TS7006: Parameter 'ref' implicitly has an 'any' type.

7         async __resolveReference(ref, context) {
                                   ~~~

src/modules/product/resolvers.ts:7:39 - error TS7006: Parameter 'context' implicitly has an 'any' type.

7         async __resolveReference(ref, context) {
                                        ~~~~~~~


Found 3 errors.
```

**Comment by michael-watson** [comment]
Have you tried using the `federation` config option? Example config that worked for me:

```
schema: 
  - './*.graphql'
generates:
  ./__generated__/resolvers-types.ts:
    config:
      useIndexSignature: true
      federation: true
    plugins:
      - typescript
      - typescript-resolvers
```

**Comment by tdreyno** [comment]
This did not work for me. Types for `__resolveReference` are missing in generated output and there is a missing definition for something called `_Service`. my config

```
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
    config:
      useIndexSignature: true
      useTypeImports: true
      contextType: ../models#ContextModel
      mappers:
        Chain: ../models#ChainModel
        NFT: ../models#NFTModel
      federation: true
```
