### ISSUE TITLE
Watch mode does not work with near-operation-file preset

### ISSUE THREAD

**Issue by kylesuss** [dotansimha/graphql-code-generator#7860]
### Issue workflow progress

_Progress of the issue based on the [Contributor Workflow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow)_

- [ ] 1. The issue provides a reproduction available on [GitHub](https://github.com/dotansimha/graphql-code-generator-issue-sandbox-template), [Stackblitz](https://stackblitz.com/github/dotansimha/graphql-code-generator-issue-sandbox-template) or [CodeSandbox](https://codesandbox.io/s/github/dotansimha/graphql-code-generator-issue-sandbox-template)

> Make sure to fork this template and run `yarn generate` in the terminal.
>
> Please make sure the Codegen and plugins version under `package.json` matches yours.

- [ ] 2. A failing test has been provided
- [x] 3. A local solution has been provided
- [ ] 4. A pull request is pending review

---

**Describe the bug**

👋 

We have a config that looks like:

```yml
schema:
  - lib/schema/webapp-schema.graphql
  - lib/schema/graphcms-schema.graphql
generates:
  services/webapp/types.tsx:
    plugins:
      - 'typescript'
  services/webapp/:
    documents:
      - 'services/webapp/{screens,layouts,components,pages,lib,containers,hooks}/**/*.{ts,tsx,js,jsx}'
      - '!**/__generated__/*.*'
      - '!**/__generated__/**/*.*'
    preset: near-operation-file
    presetConfig:
      folder: __generated__
      baseTypesPath: types.tsx
      extension: .tsx
    plugins:
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withHOC: false
      withComponent: false
      useTypeImports: true

```

I am now trying to integrate watch mode & having issues getting it to work with our `documents`. Putting some logging in, I see that when `chokidar.watch` is initialized, there is an ignore path that does not take the `folder` in the `presetConfig` into account:

https://github.com/dotansimha/graphql-code-generator/blob/440172cfe7a5df79c491f14442ab8fa47714b5da/packages/graphql-codegen-cli/src/utils/watcher.ts#L77-L84

So instead of ignoring `services/webapp/**/__generated__/*.tsx`, it ignores `services/webapp/**/*.tsx` which is most of the files I want it to watch.

Is this a bug? Is it only a problem because of the `near-operation-file` preset? Are we doing some config incorrectly?

**Additional context**

Testing locally, I fixed the issue by changing the code sample above to:

```js
const ignored = [];
Object.keys(config.generates)
  .map((filename) => ({
   filename,
    config: pluginHelpers.normalizeOutputParam(config.generates[filename]),
  }))
  .forEach((entry) => {
    if (entry.config.preset) {
      const extension = entry.config.presetConfig && entry.config.presetConfig.extension;
      // Folder stuff below is new
      const folder = (entry.config.presetConfig && entry.config.presetConfig.folder) || '';
      if (extension) {
        ignored.push(path.join(entry.filename, '**', folder, `*${extension}`));
```

**Comment by kylesuss** [comment]
It also seems like I can get what I want by modifying our config to:

```yaml
...
presetConfig:
      folder: __generated__
      baseTypesPath: types.tsx
      extension: .generated.tsx
...
```
Then only the generated files are ignored. Perhaps that's the ideal workflow. I'll close with that in mind!
