### ISSUE TITLE
Option to have `__typename` only required for unions and interfaces

### ISSUE THREAD

**Issue by SimonSimCity** [dotansimha/graphql-code-generator#7866]
**Is your feature request related to a problem? Please describe.**

I'm using apollo as my graphql server, which adds the property `__typename` for every type, excepted for places where I have to define it (unions and interfaces). Saying this, for an apollo server it would be really nice having the option to only having to define the field `__typename` if it cannot be determined by the server.

Using `nonOptionalTypename: true`, I have to define the property for all types. If I have this option disabled, I have to define a function to resolve the type, which I want to skip by `optionalResolveType: true`, because it's really hard for me to ensure the types are correct there, just by using typescript.

**Describe the solution you'd like**

An additional option which makes the property `__typename` required for all untion types and interfaces.

**Describe alternatives you've considered**

Setting `nonOptionalTypename: true` by which I now have to return the property `__typename` even for types where the apollo server could easily determine it by himself.

I also thought of somehow adding a definition of `__typename` to my graphql schema, but that really looks like a hack ...

**Additional context**

One possibility that came to my mind was extending the option `nonOptionalTypename` so I can set it not only to a boolean (`true` or `false`) but also to a string like `UnionAndInterfaces` which would enable this behavior.

**Comment by lensbart** [comment]
I was about to make an issue for exactly this feature request. This would be a very welcome improvement!

For now, it seems like the most typesafe way is to require `__typename` everywhere, which indeed is a bit of a drag.

**Comment by lensbart** [comment]
I found a more or less satisfactory workaround for my use case.

Assuming your union types share a common characteristic, you could do something like this:
```yml
# codegen.yml
generates:
  some/filename:
    config:
      resolverTypeWrapperSignature: "T extends { __typename: TypenameTemplateLiteralType } ? T : Optional<T, '__typename'>"
    plugins:
      - add:
          content:
            - import type { Optional } from 'utility-types'
            - import type { TypenameTemplateLiteralType } from 'src/types'
      - typescript
      - typescript-resolvers
```

```
// src/types.ts

// Should be inlined in `codegen.yml`, awaiting fix: https://github.com/dotansimha/graphql-code-generator/issues/7763
export type TypenameTemplateLiteralType = `${string}Error` | `${string}Payload`
```

This will make `__typename` mandatory on all object types that have a `__typename` ending with either “Error” or “Payload”. This matches my use case where I avoid throwing errors in my resolvers, and instead include them in the domain, with mutations returning e.g. `CreateUserResult = CreateUserPayload | NotAllowedError`.

Hope this helps!
