### ISSUE TITLE
Generate only queries or only mutations

### ISSUE THREAD

**Issue by bitttttten** [dotansimha/graphql-code-generator#7874]
**Is your feature request related to a problem? Please describe.**

I am trying to use a different fetcher for queries and mutations. Perhaps this is a more that I am trying to solve my problem in the wrong way, although still it would be nice to be able to generate _only_ queries or _only_ mutations.

**Describe the solution you'd like**

I would imagine it would be a configurable option in the config that takes "queries" or "mutations".

```yaml
documents: src/**/*.graphql
generates:
    src/generated/queries.ts:
        plugins:
            - typescript
            - typescript-operations
            - typescript-react-query
        config:
            fetcher: "../codegen.fetcher#queryFetcher"
            generate: "queries"
    src/generated/mutations.ts:
        plugins:
            - typescript
            - typescript-operations
            - typescript-react-query
        config:
            fetcher: "../codegen.fetcher#mutationFetcher"
            generate: "mutations"
```
