### ISSUE TITLE
If enumValues is set, codegen should be configurable to skip/omit the export of those enums

### ISSUE THREAD

**Issue by simonmumenthaler** [dotansimha/graphql-code-generator#7905]
If the config for `enumValues` is set that enums are imported instead of defined, the enums are still exported.
```yaml
schema: schema.graphql
config:
  enumValues: ./enums
documents: document.graphql
generates:
  generated-types.ts:
    plugins:
      - typescript
      - typescript-operations
```
-->
```typescript
import { Status } from "./enums";
// ...
export { Status };
// ...
```
Since the file/package exporting the enums must be accessible for the generated file and therefore also for the actual code consuming the generated file, it's basically useless to re-export the enums.

**Describe the solution you'd like**
A configuration like `noEnumExport` would be adequate.

**Sandbox Example**
https://codesandbox.io/s/graphql-codegen-typescript-omit-enum-exports-swdbrp?file=/generated-types.ts
