### ISSUE TITLE
No longer reporting errors in document after upgrading

### ISSUE THREAD

**Issue by ricglz** [dotansimha/graphql-code-generator#8017]
### Describe the bug

I upgraded from:

```
     "@graphql-codegen/add": "^2.0.2",
     "@graphql-codegen/cli": "^1.21.4",
     "@graphql-codegen/typescript": "^1.22.0",
     "@graphql-codegen/typescript-operations": "^1.17.16"
```

to: 

```
    "@graphql-codegen/add": "^3.1.1",
     "@graphql-codegen/cli": "^2.6.2",
     "@graphql-codegen/typescript": "^2.4.11",
     "@graphql-codegen/typescript-operations": "^2.4.0"
```

After doing this, the errors that were in my documents would not be caught

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

# Pre-requisites

## GraphQL schema

```
type Query {
    user(id: ID!): User!
}

type User {
    id: ID!
    username: String!
    email: String!
}
```

## My GraphQL operations

```
query user {
    user(id: 1) {
        id
        username
        email
        i_do_not_exist
    }
}
```

## My Config

```
overwrite: true
schema: "URL_TO_GRAPHQL"
documents: "src/**/*.graphql"
generates:
  src/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: ~@project/schema
      folder: types
      extension: .ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
    config:
      reactApolloVersion: 3
      withHOC: false
      withHooks: true
      withComponent: false
      scalars:
        DateTime: string
```

# Steps

1. run `yarn generate`

### Expected behavior

That the CLI shows that I have an error in my query

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `graphql` version: 16.5.0
- `@graphql-codegen/*` version(s): 2.6.2

### Codegen Config File

```
overwrite: true
schema: "URL_TO_GRAPHQL"
documents: "src/**/*.graphql"
generates:
  src/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: ~@project/schema
      folder: types
      extension: .ts
    plugins:
      - typescript-operations
      - typescript-react-apollo
    config:
      reactApolloVersion: 3
      withHOC: false
      withHooks: true
      withComponent: false
      scalars:
        DateTime: string
```
