### ISSUE TITLE
[typescript-msw] Support usage with import-types-preset

### ISSUE THREAD

**Issue by JohnDaly** [dotansimha/graphql-code-generator#8053]
### Describe the bug

The `@graphql-codegen/typescript-msw` package isn't compatible with `@graphql-codegen/import-types-preset`. The operation types that are generated will not be associated with the import statement that `@graphql-codegen/import-types-preset` provides.

### Your Example Website or App

https://stackblitz.com/edit/github-9ekyl6?file=handlers.ts

### Steps to Reproduce the Bug or Issue

Set up a project with the following configuration:

```yaml
schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
  handlers.ts:
    preset: import-types
    presetConfig:
      typesPath: ./types.ts
    plugins:
      - typescript-msw
```

After generating the code. Check the types in the `handlers.ts` file, they will not be resolved properly.

### Expected behavior

As a user, I expected the operation types created in `typescript-msw` to be hooked up to the types specified by the `import-types` preset. This does not happen.

### Platform

- OS: macOS
- NodeJS: 16.13.0
- `graphql` version: 14.7.0
- `@graphql-codegen/*` version(s): 1.16.3
