### ISSUE TITLE
Input types required filed with default is has optional type

### ISSUE THREAD

**Issue by ZiiMakc** [dotansimha/graphql-code-generator#8129]
### Describe the bug

For schema:
```
type Query {
    test(
        a: Int # can be null
        b: Int = 1  # can be null if user pass null explicitly
        c: Int! # can't be null
        d: Int! = 1 # can't be null
    ): Int!
}
```

Generated types are:
```
export type QueryTestArgs = {
  a?: InputMaybe<Scalars['Int']>;
  b?: InputMaybe<Scalars['Int']>;
  c: Scalars['Int'];
  d?: Scalars['Int']; // should not be optional
};
```

### Your Example Website or App

https://codesandbox.io/s/aged-leftpad-6dcvit

### Steps to Reproduce the Bug or Issue

Sandbox link

### Expected behavior

Generated types are:
```
export type QueryTestArgs = {
  a?: InputMaybe<Scalars['Int']>;
  b?: InputMaybe<Scalars['Int']>;
  c: Scalars['Int'];
  d: Scalars['Int']; // not optional
};
```

### Platform

- sandbox issue template

### Codegen Config File

schema: schema.graphql
documents: document.graphql
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations

**Comment by ZiiMakc** [comment]
Seems I need to set `avoidOptionals` to resolve this:
```
generates:
  path/to/file.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      avoidOptionals: true
```
