### ISSUE TITLE
Failed to load schema, no error output

### ISSUE THREAD

**Issue by taschmidt** [dotansimha/graphql-code-generator#8138]
### Describe the bug

I had a schema from AppSync which includes an AWSJSON scalar type. If I don't define that type, graphql-codegen fails with absolutely no indication of why, just that it "Failed to load schema"

### Your Example Website or App

https://codesandbox.io/s/inspiring-panna-ixxqrr?file=/schema.graphql

### Steps to Reproduce the Bug or Issue

1. Open the codesandbox link.
2. Run `yarn generate`
3. Notice the output:
<img width="339" alt="image" src="https://user-images.githubusercontent.com/228736/180850818-612ac3c3-d23d-46ea-80ac-8793f5b2635d.png">

### Expected behavior

Some sort of error indicating an unresolved type of `AWSJSON`. If I change that prop in the schema to be a `String`, everything works just fine.

### Platform

- OS: macOS
- NodeJS: 16.16.0
- `graphql` version: 16.5.0
- `@graphql-codegen/*` version(s): [e.g. 2.6.2]
    "@graphql-codegen/cli": "^2.9.1",
    "@graphql-codegen/typed-document-node": "^2.3.2",
    "@graphql-codegen/typescript-operations": "^2.5.2",

### Codegen Config File

overwrite: true
schema: 
  - src/generated/foo.graphql
documents: null
generates:
  src/generated/graphql.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
    config:
      preResolveTypes: true

**Comment by elshenak** [comment]
Add AWSJSON scalar to your graphql schema and codegen yaml file like so:


GraphQL Schema:
```
scalar AWSJSON

type Foo {
    bar: AWSJSON
}

```

Codegen.yaml
```
schema: schema.graphql
documents: null
generates:
  types.ts:
    plugins:
      - typescript
      - typescript-operations
    config:
      scalars:
        AWSJSON: string

```
