### ISSUE TITLE
Unknown directive \"@namedClient\"." when using typescript-apollo-angular

### ISSUE THREAD

**Issue by synerp** [dotansimha/graphql-code-generator#8168]
### Describe the bug

I am using multiple named clients as described in https://apollo-angular.com/docs/recipes/multiple-clients/

My codegen.yml is as follows: 

```
schema: ./.schemas/g/Person/schema.gql
documents: "libs/client/**/*.gPerson.graphql"
generates:
  ./.schemas/g/Person/resolvers/resolvers-types.ts:
    plugins:
      - typescript
      - typescript-resolvers

  ./.schemas/g/Person/types/types.ts:
    plugins:
      - typescript

  ./.schemas/g/Person/documents/graphql-operations.ts:
    preset: import-types
    presetConfig:
      typesPath: ../types/types
    plugins:
      - typescript-operations
      - typed-document-node

  ./.schemas/g/Person/gql.services.ts:
    config:
      documentMode: external
      importOperationTypesFrom: Operations
      importDocumentNodeExternallyFrom: '@synerp/client/graphql/gPerson/documents' // graphql-operations.ts
      namedClient: 'gPerson'
    plugins:
      - typescript-apollo-angular
```

When I try to run a query I receive the following error in the browser:

``
{
	"errors": [{
		"message": "Unknown directive \"@namedClient\".",
		"locations": [{
			"line": 1,
			"column": 65
		}],
		"extensions": {
			"code": "GRAPHQL_VALIDATION_FAILED",
			"exception": {
				"stacktrace": ["GraphQLError: Unknown directive \"@namedClient\".", "    at Object.Directive (/home/dev/projects/synergy-evolved-current/node_modules/graphql/validation/rules/KnownDirectivesRule.js:56:11)", "    at Object.enter (/home/dev/projects/synergy-evolved-current/node_modules/graphql/language/visitor.js:301:32)", "    at Object.enter (/home/dev/projects/synergy-evolved-current/node_modules/graphql/utilities/TypeInfo.js:391:27)", "    at visit (/home/dev/projects/synergy-evolved-current/node_modules/graphql/language/visitor.js:197:21)", "    at validate (/home/dev/projects/synergy-evolved-current/node_modules/graphql/validation/validate.js:91:24)", "    at validate (/home/dev/projects/synergy-evolved-current/node_modules/apollo-server-core/src/requestPipeline.ts:473:27)", "    at processGraphQLRequest (/home/dev/projects/synergy-evolved-current/node_modules/apollo-server-core/src/requestPipeline.ts:264:30)", "    at runMicrotasks (<anonymous>)", "    at processTicksAndRejections (node:internal/process/task_queues:96:5)", "    at processHTTPRequest (/home/dev/projects/synergy-evolved-current/node_modules/apollo-server-core/src/runHttpQuery.ts:433:24)"]
			}
		}
	}]
}
``

I am not sure what part of the codegen.yml is missing to get @nameClient to work.

Thanks

-Paul
