### ISSUE TITLE
arrayInputCoercion not working

### ISSUE THREAD

**Issue by charlypoly** [dotansimha/graphql-code-generator#8199]
### Discussed in https://github.com/dotansimha/graphql-code-generator/discussions/8191

<div type='discussions-op-text'>

<sup>Originally posted by **markedwards** August  5, 2022</sup>
I have the following codegen.yml:
```
overwrite: true
schema: "lib/api/schema.graphql"
documents: "lib/api/(fragments|mutations|queries)/**/*.ts?(x)"
generates:
  lib/api/types.ts:
    config:
      avoidOptionals:
        field: true
      namingConvention:
        enumValues: keep
      nonOptionalTypename: true
    plugins:
      - "typescript"
      - "typescript-operations"
```
I'm not seeing arrayInputCoercion applied.  In other words, array properties of input types are generated as only an array, rather than either an array or a single value of the given type.

Does this only work on variables, and not on input types?</div>
