### ISSUE TITLE
Type errors when using the generic SDK plugin

### ISSUE THREAD

**Issue by aradalvand** [dotansimha/graphql-code-generator#8253]
### Describe the bug

I've been using the generic SDK plugin for a long time but recently I updated to the latest version as of the time of writing (3.0.0) and I'm getting type errors:

![image](https://user-images.githubusercontent.com/26527405/185445606-3b29338d-9a55-4e14-9955-4b51bd97df72.png)

The error is:
![image](https://user-images.githubusercontent.com/26527405/185445870-5a60361b-714a-4437-9cf5-3b70f3a7af4f.png)

Basically it's complaining about the fact that the return type of `Requester` is `Promise<R> | AsyncIterable<R>` as opposed to `Promise<T>`. This needs to be fixed somehow, I'm not so sure but I guess `AsyncIterable<R>` is meant for subscriptions, it might be a better idea to separate the requester for queries and mutations from the requester for subscriptions, I don't even have any subscriptions so this change shouldn't have affected users like me, I think.

### Your Example Website or App
https://stackblitz.com/edit/github-3m5p4f-tgad6c?file=types.ts

### Expected behavior

I should work as it used to, no type errors.

### Platform

- OS: Windows 10 + WSL Ubuntu 20.06
- NodeJS: 16.15.1
- `graphql` version: 16.6.0
- `@graphql-codegen/cli` version: 2.11.6
- `@graphql-codegen/typescript` version: 2.7.3
- `@graphql-codegen/typescript-operations` version: 2.5.3
- `@graphql-codegen/typescript-generic-sdk` version: 3.0.0

### Codegen Config File

```yaml
schema: http://localhost:5000/graphql
documents: ./src/lib/graphql/**/*.graphql
generates:
  './src/lib/graphql/generated.ts':
    plugins:
      - typescript
      - typescript-operations
      - typescript-generic-sdk
config:
  scalars:
    DateTime: string
    Date: string
    TimeSpan: string
    Byte: number
    URL: string
  avoidOptionals:
    field: true
  immutableTypes: true
  documentMode: string
  enumsAsTypes: true
  skipTypename: true
```
