### ISSUE TITLE
error loading preset when transpiling TS->ESM

### ISSUE THREAD

**Issue by mikaelkaron** [dotansimha/graphql-code-generator#8358]
### Describe the bug

In relation to 32c1560f1669f6726008226c0e467a7fcc90aa84 where the `err.code` was `ERR_MODULE_NOT_FOUND` in esm instead of `MODULE_NOT_FOUND` - if transpiling via `ts-node` and esm `err.code` is `undefined`. I'm guessing it's because [`ts-node` generates it's own errors](https://github.com/TypeStrong/ts-node/blob/main/dist-raw/node-internal-errors.js#L12) that don't have the `err.code` set.

There's an [upstream issue in `ts-node`](https://github.com/TypeStrong/ts-node/issues/1862) about this, but a temporary fix is to add `err.code !== undefined` [here](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/graphql-codegen-cli/src/plugins.ts#L25)

### Your Example Website or App

...

### Steps to Reproduce the Bug or Issue

1. create config using `@graphql-codegen/near-operation-file`
1. configure typescript to use ESM
1. load schema from `.ts` file via `ts-node` using `NODE_OPTIONS='--loader ts-node/esm' graphql-codegen-esm`

### Expected behavior

`@graphql-codegen/near-operation-file` to be loaded

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `graphql` version: [e.g. 16.3.0]
- `@graphql-codegen/*` version(s): [e.g. 2.6.2]

### Codegen Config File

```yaml
projects:
  operations:
    schema: ./src/graphql/schema/index.ts
    documents:
      - ./src/components/**/*.graphql
    extensions:
      codegen:
        emitLegacyCommonJSImports: false
        generates:
          ./src/components/:
            preset: near-operation-file
            plugins:
              - add:
                  content:
                    - '// this file was auto generated by graphql-codegen'
              - typescript-operations
              - typed-document-node
```
