### ISSUE TITLE
Errors during generation are non-existent 

### ISSUE THREAD

**Issue by chriswetterman** [dotansimha/graphql-code-generator#8366]
### Describe the bug

I've recently updated to v2 of the CLI and the associated plugins. Since then the errors that are reported are not helpful in that only a partial of the error is displayed. This makes tracking down errors **extremely** more challenging. Please see the below screenshots and information. I have used the `debug` and `errorsOnly` flags and they do not provide any additional information toward identifying the reason and therefore cause of the failure.

### Your Example Website or App

None provided

### Steps to Reproduce the Bug or Issue

To reproduce I have the following CLI version and plugins installed which at the time are the most current versions. Create a query/mutation that is incorrect or doesn't exist to cause any error in generation. Review the reported errors.

### Expected behavior

As a user, I am expecting to see detailed enough errors to allow me to track down my errors to resolve. Version 1 of the CLI provided adequate information around errors.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/171418/191061908-2912eccd-47a1-49d6-b757-dabf6b0e4168.png)
![image](https://user-images.githubusercontent.com/171418/191062122-32277dde-93f2-4e6f-b4c8-8a6ce086bf2b.png)

### Platform

- OS: Windows
- NodeJS: 14.18.0
- @graphql-codegen/cli@2.12.0
- @graphql-codegen/typed-document-node@2.3.3
- @graphql-codegen/typescript@2.7.3
- @graphql-codegen/typescript-operations@2.5.3

 To reproduce I have the following CLI version and plugins installed which at the time are the most current versions.

### Codegen Config File

```yml
schema:
  - https://graphql-federated-gateway...../graphql
  - 'schema.graphql'
documents: './src/**/*.graphql'
generates:
  ./src/generated/graphql.tsx:
    config:
      enumsAsConst: true
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
```
