### ISSUE TITLE
No way to make `cache-and-network` the default policy in React-Apollo.

### ISSUE THREAD

**Issue by yuki2006** [dotansimha/graphql-code-generator#8438]
**Is your feature request related to a problem? Please describe.**

Unexecutable code is generated when `cache-and-network` is specified in fetchPolicy.

This policy cannot be used in Mutation, so it cannot be described in common defaultBaseOptions

https://www.apollographql.com/docs/react/data/mutations#fetchpolicy

ref. 
https://github.com/dotansimha/graphql-code-generator/issues/6451

**Describe the solution you'd like**

Query and Mutation would like to be able to write separate policies.

**Additional context**

```
schema: ../backend/graph/*.graphql
documents: ./src/graphql/*.graphql
generates:
  ./src/graphql/generated.ts:
    plugins:
      - typescript
      - typescript-operations
      - typescript-react-apollo
    config:
      defaultBaseOptions:
        fetchPolicy: 'cache-and-network'
```
