### ISSUE TITLE
🐛 BUG: Type mismatch typescript-operations and typescript-vue-apollo

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [dotansimha/graphql-code-generator#8561]
### Describe the bug

When I try to generate vue-apollo operations I get errors on the variables type that there is a mismatch.

### Your Example Website or App

http://example.com

### Steps to Reproduce the Bug or Issue

1. Run codegen
2. Check generated operations

### Expected behavior

The type used for variables should match in typescript operations and vue operations.

### Screenshots or Videos

```
Argument of type 'Exact<{ input?: InputMaybe<INPUTTYPE> | undefined; }> | Ref<Exact<{ input?: InputMaybe<INPUTTYPE> | undefined; }>> | ReactiveFunction<Exact<{ input?: InputMaybe<INPUTTYPE> | undefined; }>>' is not assignable to parameter of type 'VariablesParameter<Exact<{ input?: InputMaybe<INPUTTYPE> | undefined; }>>'.
Translation: I was expecting VariablesParameter<Exact<{ input?: InputMaybe<INPUTTYPE> | undefined; }>>, but you passed Exact<{ input?: InputMaybe<INPUTTYPE> | undefined; }> | Ref<Exact<{ input?: InputMaybe<INPUTTYPE> | undefined; }>> | ReactiveFunction<Exact<{ input?: InputMaybe<INPUTTYPE> | undefined; }>>
```

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `graphql` version: [e.g. 16.3.0]
- `@graphql-codegen/*` version(s): [e.g. 2.6.2]

### Codegen Config File

```yaml
overwrite: true
schema: <schemalocation>
documents: <documentslocation>
generates:
  ./libs/shared/__generated__/src/lib/types.generated.ts:
    plugins:
      - 'typescript'
    config:
      scalars:
        BigInt: bigint
      typesPrefix: 'I'
      withCompositionFunctions: true
      federation: true

  ./libs/shared/__generated__/src/lib/operations.generated.ts:
    preset: 'import-types'
    plugins:
      - 'typescript-operations'
    config:
      dedupeOperationSuffix: true
      dedupeFragments: true
      gqlImport: '@apollo/client/core#gql'
      federation: true
      typesPrefix: I
      useTypeImports: true
    presetConfig:
      typesPath: ./types.generated

  ./libs/shared/__generated__/src/lib/use-graphql-operations.generated.ts:
    preset: 'import-types'
    plugins:
      - 'typescript-vue-apollo'
    config:
      vueCompositionApiImportFrom: vue
      dedupeOperationSuffix: true
      dedupeFragments: true
      typesPrefix: I
      gqlImport: '@apollo/client/core#gql'
      federation: true
      useTypeImports: true
      importOperationTypesFrom: Types
    presetConfig:
      typesPath: ./operations.generated
hooks:
  afterAllFileWrite:
    - prettier --write
    - eslint --fix
```
