### ISSUE TITLE
`client-preset` does not forward `dedupeOperationSuffix`

### ISSUE THREAD

**Issue by ntungare** [dotansimha/graphql-code-generator#8576]
### Describe the bug

The `client-preset` forwards a very small sub-set of configs to the lower level as can be seen [here](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/presets/client/src/index.ts#L85).

This is problematic since I'm not able to set some of the options supported by the the `typescript-operations` [plugin](https://github.com/dotansimha/graphql-code-generator/blob/master/packages/plugins/typescript/operations/src/config.ts).

### Your Example Website or App

https://github.com/ntungare/graphql-codegen-example

### Steps to Reproduce the Bug or Issue

Use the codegen config attached, the effect of the `dedupeOperationSuffix` is not seen.

### Expected behavior

All configs are respected since the preset is just a combination of the plugin.

I'd like to not use the `gql-tag-operations-preset` but this is blocker for that. And the `gql-tag-operations-preset` is supposedly deprecated?

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `"graphql": "^16.6.0"`
- `"graphql-tag": "^2.12.6"`
- `"@graphql-codegen/cli": "^2.13.8"`
- `"@graphql-codegen/gql-tag-operations-preset": "^1.7.0"`

### Codegen Config File

```ts
import type { CodegenConfig } from "@graphql-codegen/cli";

const config: CodegenConfig = {
    generates: {
        "src/generated/": {
            schema: "https://countries.trevorblades.com/",
            documents: "src/query/**/*.ts",
            plugins: [],
            preset: "gql-tag-operations-preset",
            presetConfig: {
                augmentedModuleName: "graphql-tag",
            },
            config: {
                dedupeFragments: true,
                dedupeOperationSuffix: true,
            },
        },
    },
};

export default config;
```

### Additional context

Using the above config the `dedupeFragments` is respected but not the `dedupeOperationSuffix` config.

**Comment by mogelbrod** [comment]
There seems to be a bunch of options that aren't being forwarded right now 😞
While attempting to migrate to client-preset I couldn't find any way to apply the following options:
```yaml
config:
  typesPrefix: I
  enumPrefix: I
  enumsAsTypes: true
  documentVariableSuffix: Doc
  fragmentVariableSuffix: Fragment
  omitOperationSuffix: true
  dedupeFragments: true
  exportFragmentSpreadSubTypes: true
  nonOptionalTypename: true
  flattenGeneratedTypes: false
```
