### ISSUE TITLE
Generating requires bearer token, even though schema is public

### ISSUE THREAD

**Issue by atrauzzi** [dotansimha/graphql-code-generator#8620]
### Which packages are impacted by your issue?

_Not...sure...?_

### Describe the bug

Hey hey!  I'm wondering if it's right when a full GraphQL schema is provided for graphql-codegen to require a bearer token when generating?

My hope was that the full reflection/schema/sdl itself is sufficient to generate without having to make actual calls against the server?

Despite being able to access the sdl endpoint publicly, codegen still ends up erroring out:

```
 Failed to load schema from http://mywebapp.localdev.com/graphql?sdl:
      The current user is not authorized to access this resource.
      GraphQLError: The current user is not authorized to access this resource.
```

### Steps to Reproduce the Bug or Issue

1. Point to any GraphQL schema that has `@authorize` directives on any of its nodes.
2. Attempt to generate.

### Expected behavior

I expect it to generate without requiring a `Bearer ...` token.  But instead, generating fails because for some reason the introspection/schema isn't enough?

### Platform

- OS: Linux (Fedora 37)
- NodeJS: 18.7.0
- `graphql` version: 16.6.0
```
        "@graphql-codegen/cli": "2.13.11",
        "@graphql-codegen/typescript": "^2.8.1",
        "@graphql-codegen/typescript-operations": "^2.5.6",
        "@graphql-codegen/typescript-react-apollo": "^3.3.6",
```
### Codegen Config File

```yaml

---
overwrite: true
schema:
    "http://mywebapp.localdev.com/graphql?sdl":
#        headers:
#            authorization: "Bearer eyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy!"
documents: "./src/GraphQl/Query/**/*.graphql"
generates:
    "./src/GraphQl/generated.ts":
        config:
            withHooks: true
        plugins:
            - typescript
            - typescript-operations
            - typescript-react-apollo
```

**Comment by saihaj** [comment]
Default codegen given a URL will execute an [introspection query](https://github.com/graphql/graphql-js/blob/6b5c8af150350201d0d67f3eb6f6f44cb6f92288/src/utilities/getIntrospectionQuery.ts#L37-L41) and that would require you to provide any auth tokens if necessary.

I understand that you have a route on your API that is providing the schema SDL so you avoid running introspection query. For that try `handleAsSDL: true` option and see if it works 
```yaml
overwrite: true
schema:
   -  "http://mywebapp.localdev.com/graphql?sdl":
       handleAsSDL: true
documents: "./src/GraphQl/Query/**/*.graphql"
generates:
    "./src/GraphQl/generated.ts":
        config:
            withHooks: true
        plugins:
            - typescript
            - typescript-operations
            - typescript-react-apollo
```
