### ISSUE TITLE
resolve import assertions error

### ISSUE THREAD

**Issue by charlypoly** [dotansimha/graphql-code-generator#8630]
### Discussed in https://github.com/dotansimha/graphql-code-generator/discussions/8621

<div type='discussions-op-text'>

<sup>Originally posted by **TomokiMiyauci** November 21, 2022</sup>
The following error occurs when targeting file that uses import assertions.

```bash
This experimental syntax requires enabling the parser plugin: "importAssertions".
````

This seems to be an error from babel, is there any way to resolve this?</div>

**Comment by charlypoly** [comment]
Hi @TomokiMiyauci,

Could you provide a minimal reproduction?

Thanks!

**Comment by TomokiMiyauci** [comment]
@charlypoly Thanks for the work.

codegen.yaml
```yaml
overwrite: true
schema: schema.gql
documents: source.ts
generates:
  generated.ts:
    plugins:
      - typescript
      - typescript-operations
```

source.ts
```ts
import any from "./package.json" assert { type: "json" };

const document = /* graphql */ `query ANY {
  anyValue
}`;
```

package.json

```json
{
  "devDependencies": {
    "@graphql-codegen/cli": "2.13.8",
    "@graphql-codegen/typescript-operations": "^2.5.5",
    "graphql": "^16.6.0",
    "typescript": "^4.8.4"
  }
}
```

tsconfig.json

```json
{
  "compilerOptions": {
    "resolveJsonModule": true
  }
}
```

out

```bash
  ❯ Generate to generated.ts
    ✔ Load GraphQL schemas
    ✖ This experimental syntax requires enabling the parser plugin: "importAssertions". (1:33)
    ◼ Generate
```
