### ISSUE TITLE
[0.14] Move `mergeSchemaFiles` to be an option under `schema`

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#872]
Now it's defined in the root of the config, but it should be under a specific `schema`:

```yml
schema:
    - "**/*.graphql"
           mergeWith: @graphql-modules/export#mergeGraphQlSchemas
```
