### ISSUE TITLE
Schema root types are not merged if named differently

### ISSUE THREAD

**Issue by kdawgwilk** [dotansimha/graphql-code-generator#8735]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-operations

### Describe the bug

When adding multiple schemas in config merging does not take into account differences in root type names when merging the schemas

### Your Example Website or App

https://codesandbox.io/s/gql-codegen-schema-merge-issue-p1w8wt?file=/document.graphql

### Steps to Reproduce the Bug or Issue

Take the following 2 schemas

## schema_a.graphql
```gql
schema {
  query: Query
  mutation: Mutation
}

type Query {
  schemaAField: String
}

type Mutation {
  schemaAMutation: String
}
```

## schema_b.graphql
```gql
schema {
  query: query_root
  mutation: mutation_root
}

type query_root {
  schemaBField: String
}

type mutation_root {
  schemaBMutation: String
}
```

## codegen.yml:
```yml
generates:
  types.ts:
    schema:
      - schema_a.graphql
      - schema_b.graphql
    documents:
      - 'src/**/!(*.d).{ts,tsx}'
    plugins:
      - typescript
      - typescript-operations
```

## src/component.ts
```ts
const COMPONENT_QUERY = gql`
query ComponentQuery {
  schemaAField
}
`
```

Gives this error
```
$ graphql-codegen

✔ Parse Configuration
⚠ Generate outputs
  ❯ Generate lib/graphql_types.ts
    ✔ Load GraphQL schemas
    ✔ Load GraphQL documents
    ✖ GraphQL Document Validation failed with 30 errors;
      Error 0: GraphQLDocumentError: Cannot query field "schemaAField" on type "query_root". Did you mean "schemaBField…
      at /Users/username/Sources/my-app/src/component.ts:3:7
```

### Expected behavior

I expected the root types to be merged even though they are named differently

### Platform

- OS: macOS
- NodeJS: 16.14.0
- `graphql` version: 16.2.0
- `@graphql-codegen/cli`: 2.16.1
- `@graphql-codegen/typescript`: 2.8.5
- `@graphql-codegen/typescript-operations`: 2.5.10

### Codegen Config File

```yml
generates:
  types.ts:
    schema:
      - schema_a.graphql
      - schema_b.graphql
    documents:
      - 'src/**/!(*.d).{ts,tsx}'
    plugins:
      - typescript
      - typescript-operations
```
