### ISSUE TITLE
immutableTypes and noNamespaces in typescript template not working correctly together

### ISSUE THREAD

**Issue by nemcek** [dotansimha/graphql-code-generator#877]
**Describe the bug**
When both `immutableTypes` and `noNamespaces` config options are specified the generated types are wrong (have typos). Each separately works fine.

For example in these generated types the type of `countries` in `CountriesCountries` should be `ReadonlyArray<Countries_Countries>` while there is a typo and the type is `CountriesReadonlyArray<_Countries> | null;`. The `Countries` should by inside `< >` and not at the start.
```graphql
export type CountriesVariables = {};

export type CountriesQuery = {
  readonly __typename?: "Query";

  readonly countries: CountriesCountries;
};

export type CountriesCountries = {
  readonly __typename?: "CountriesPayload";

  readonly countries: CountriesReadonlyArray<_Countries> | null;
};

export type Countries_Countries = {
  readonly __typename?: "Country";

  readonly code: string;

  readonly name: string;
};
```

**To Reproduce**
1. Use `schema.graphql` as schema
2. Use `countriesQuery.graphql` as documents
3. Have `codegen.yml` config file
4. Run the following command: `gql-gen`

**Expected behavior**
The generated type of `countries` in `CountriesCountries` should be `ReadonlyArray<Countries_Countries>`.

**Schema/Documents**
`schema.graphql`:
```graphql
type Country {
  id: Int!
  code: String!
  name: String!
}

type Query {
  countries: CountriesPayload!
}

type CountriesPayload {
  countries: [Country!]
}
```
`countriesQuery.graphql`:
```graphql
query Countries {
  countries {
    countries {
      code
      name
    }
  }
}
```
`codegen.yml`:
```yml
schema:
  - "schema.graphql"
documents:
  - "countriesQuery.graphql"
overwrite: true
generates:
  ./types/api.ts:
    config:
      immutableTypes: true
      noNamespaces: true
    plugins:
      - "typescript-common"
      - "typescript-client"
```

**Environment:**
 - OS: Windows 10
 - Codegen: v0.14.1
 - Node: v8.11.2

**Additional context**
Reproductible scenario in repo: https://github.com/nemcek/gql-gen-ts-template-bug
Run `yarn gen` and check generated types in `/types/api.ts`

**Additional question**
Is there a way to generate interfaces instead of types?
