### ISSUE TITLE
When using importDocumentNodeExternallyFrom: 'near-operation-file' and emitLegacyCommonJSImports: true, it's appending .js to the Operations import path.

### ISSUE THREAD

**Issue by charle692** [dotansimha/graphql-code-generator#8815]
### Which packages are impacted by your issue?

@graphql-codegen/visitor-plugin-common

### Describe the bug

Whenever generating hooks with `@graphql-codegen/typescript-react-apollo` and the following config options:

```yaml
emitLegacyCommonJSImports: true
documentMode: "external"
importDocumentNodeExternallyFrom: "near-operation-file"
```

It's appending `.js` to the Operations import like so (but it shouldn't):
```ts
import type * as Types from '../../../../shared/types/graphqlGenerated.d';

import * as Operations from './Foobar.query.js';
```

The issue originates in `@graphql-codegen/visitor-plugin-common` specifically [this line](https://github.com/dotansimha/graphql-code-generator/blob/5c66efc2d29a2ba1c054141773a80b0818e628be/packages/plugins/other/visitor-plugin-common/src/client-side-base-visitor.ts#L535) where the condition checking if `emitLegacyCommonJSImports` should be inverted according to other examples within the codebase [like here](https://github.com/dotansimha/graphql-code-generator/blob/5ea74e32048f9705dd14a0b06bf42748c6e9244c/packages/presets/gql-tag-operations/src/index.ts#L214). 

The solution here is to just append a `!` to the condition such that it adds the `.js` only when `emitLegacyCommonJSImports` is `false`.

### Your Example Website or App

See MR with specs

### Steps to Reproduce the Bug or Issue

1. Install the following deps:
```json
    "@graphql-codegen/add": "^3.1.1",
    "@graphql-codegen/cli": "^2.6.2",
    "@graphql-codegen/import-types-preset": "^2.1.18",
    "@graphql-codegen/near-operation-file-preset": "^2.5.0",
    "@graphql-codegen/typescript": "^2.4.11",
    "@graphql-codegen/typescript-operations": "^2.5.12",
    "@graphql-codegen/typescript-react-apollo": "^3.3.7",
    "@graphql-codegen/typescript-resolvers": "^2.6.4",
```

2. Use a configuration based on the following:
```yaml
overwrite: true
schema: ./cleanGQLSchema.js
generates:
  <base type path>:
    config:
      useTypeImports: true
    plugins:
      - typescript
 <apollo hooks path>:
    documents:
      - <documents>
    preset: near-operation-file
    presetConfig:
      baseTypesPath: <base type path>
      extension: .generated.tsx
    plugins:
      - typescript-operations
      - typescript-react-apollo
    config:
      gqlImport: "@apollo/client#gql"
      documentMode: "external"
      importDocumentNodeExternallyFrom: "near-operation-file"
```

3. Run the `gql-gen` command and notice how the generated Operations import has `.js` file extension even if `emitLegacyCommonJSImports` isn't specified (defaults to true)

### Expected behavior

Should not append `.js` file extension to Operations import whenever `emitLegacyCommonJSImports` is `true`, `documentMode` is `external` and `importDocumentNodeExternallyFrom` is `near-operation-file`.

### Platform

- OS: macOS
- NodeJS: 16.18.1
- "graphql": "16.5.0"
- "@graphql-codegen/add": "^3.1.1",
- "@graphql-codegen/cli": "^2.6.2",
- "@graphql-codegen/import-types-preset": "^2.1.18",
- "@graphql-codegen/near-operation-file-preset": "^2.5.0",
- "@graphql-codegen/typescript": "^2.4.11",
- "@graphql-codegen/typescript-operations": "^2.5.12",
- "@graphql-codegen/typescript-react-apollo": "^3.3.7",
- "@graphql-codegen/typescript-resolvers": "^2.6.4",

### Additional context

I've created a PR with the fix and specs to ensure the issue doesn't re-appear in the future. Those specs can also be used to confirm there's an issue by running them without the change.
