### ISSUE TITLE
`typescript-graphql-request` adds non-ESM import in generated files

### ISSUE THREAD

**Issue by coeing** [dotansimha/graphql-code-generator#8845]
### Describe the bug

I am using the plugin `typescript-graphql-request` in an ESM package. But this plugin adds this import to all the generated files:

```
import * as Dom from 'graphql-request/dist/types.dom';
```

This is invalid ESM code because it misses the `.js` extension.

There should be an additional check in this place: https://github.com/dotansimha/graphql-code-generator/blob/a18818118c11d834ae41edbd172dbc259817fcb6/packages/plugins/typescript/graphql-request/src/visitor.ts#L46 

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

1. Create ESM project
2. Use typescript-graphql-request plugin
3. Generate code

### Expected behavior

If used in a ESM project or `graphql-codegen-esm` is used the generated code should be valid.

### Platform

- OS: Windows
- NodeJS: 16.17.1
- `graphql` version: 16
- `@graphql-codegen/*` version(s): 2.16.1

### Codegen Config File

overwrite: true
schema: "src/switch/graphql/graphql.schema.json"
config:
  avoidOptionals: false
generates:
  src/switch/SwitchApiClient.generated.ts:
    documents: "src/switch/graphql/*.graphql"
    scalars:
      Upload: ReadStream
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
    config:
      documentMode: string

**Comment by coeing** [comment]
I inspected the code in from typescript-graphql-request in my `node_modules` folder and there is already a check for `emitLegacyCommonJSImports`.

So adding it to my configuration fixed it:
```
overwrite: true
schema: "src/switch/graphql/graphql.schema.json"
config:
  avoidOptionals: false
emitLegacyCommonJSImports: false
generates:
  src/switch/SwitchApiClient.generated.ts:
    documents: "src/switch/graphql/*.graphql"
    scalars:
      Upload: ReadStream
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
    config:
      documentMode: string
```
