### ISSUE TITLE
.js extension is removed when importDocumentNodeExternallyFrom is a (relative) path and emitLegacyCommonJSImports is false

### ISSUE THREAD

**Issue by benkroeger** [dotansimha/graphql-code-generator#8894]
### Which packages are impacted by your issue?

@graphql-codegen/visitor-plugin-common

### Describe the bug

when importing DocumentNodes externally from a path expression that ends with `.js`, this extension is removed from the renerated import statement - even when `emitLegacyCommonJSImports` is set to false

### Your Example Website or App

https://github.com/benkroeger/graphql-code-generator/commits/patch-1

### Steps to Reproduce the Bug or Issue

check out [this commit in my fork](https://github.com/benkroeger/graphql-code-generator/commit/cd1d565ed2994a5f2ba237ee0db81d4f076b1892) and run

```sh
yarn test  packages/plugins/other/visitor-plugin-common/tests/client-side-base-visitor.spec.ts 
```

### Expected behavior

As a developer, I expect the file extension to be preserved on the generated import statement

### Platform

- OS: macOS
- NodeJS: 18.13.0
- `graphql` version: 16.6.0
- `@graphql-codegen/visitor-plugin-common` version(s): 2.13.1

### Codegen Config File

// .graphqlrc.yaml
```yaml
schema:
  ./src/schema.gql
documents:
  - 'src/**/*.graphql'
extensions:
  codegen:
    config:
      arrayInputCoercion: false
      # ? variables in fragments are not yet supported and thus can not be parsed.
      # ? the generated type is always an empty object
      # experimentalFragmentVariables: true
      nonOptionalTypename: true
      scalars:
        DateTime: string
        JSON: Types.JsonValue
        JSONObject: Types.JsonObject
    emitLegacyCommonJSImports: false
    generates:
      src/types/generated.ts:
        preset: import-types
        presetConfig:
          typesPath: './custom-scalars.js'
        plugins:
          - typescript
        config:
          useTypeImports: true
      src/generated-document-nodes.ts:
        preset: import-types
        presetConfig:
          typesPath: './types/index.js'
        plugins:
          - typescript-operations
          - typed-document-node
        config:
          useTypeImports: true
      src/generated-composition-functions.ts:
        plugins:
          - typescript-vue-urql
        config:
          useTypeImports: true
          documentMode: external
          importDocumentNodeExternallyFrom: './generated-document-nodes.js'
          importOperationTypesFrom: Operations
      src/introspected-schema.json:
        plugins:
          - urql-introspection
```

### Additional context

Since this is a more global issue, I didn't provide an entire project to reproduce the issue - and instead forked the repo, added a test and a fix
