### ISSUE TITLE
@graphql-codegen/typescript-operations dedupeFragments doesn't work

### ISSUE THREAD

**Issue by DominicGBauer** [dotansimha/graphql-code-generator#8967]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-operations

### Describe the bug

When adding `dedupFragment: true` to config it doesn't do anything.

`codegen.yml`:
```
  src/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: services/api/types.generated.ts
    plugins:
      - typescript-operations
          dedupFragment: true
```

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

1. Add a graphql query that has duplicated fragments
2. Run the codegen with `dedupFragment: true`

### Expected behavior

As a user I expect fragments to be deduplicated

### Platform

"@graphql-codegen/typescript-operations": "^3.0.0"

### Codegen Config File
```
overwrite: true
schema:
  - "https://api-dev.nomanini.com/graphql":
      headers:
        Authorization: 'Bearer zzz'
        X-Nomanini-Organisation: 'zzz'
documents: 'src/**/*.graphql'
watchConfig:
  usePolling: true
  interval: 1000
generates:
  src/services/redux/api/types.generated.ts:
    plugins:
      - add:
          content: /* eslint-disable */
      - typescript
  src/services/redux/api/mocks.generated.ts:
    plugins:
      - add:
          content: '/* eslint-disable camelcase,no-underscore-dangle,@typescript-eslint/no-use-before-define,@typescript-eslint/no-unused-vars,no-prototype-builtins */'
      - typescript-mock-data:
          typesFile: './types.generated.ts'
          listElementCount: 2
          enumValues: change-case-all#pascalCase
          typenames: keep
  src/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: services/redux/api/types.generated.ts
    config:
      link:
        name: 'nomanini'
        endpoint: 'https://api-dev.nomanini.com/graphql'
    plugins:
      - add:
          content:  import { getEnv } from '@services/utils/general'
      - typescript-operations
          dedupFragment: true
      - typescript-rtk-query:
          importBaseApiFrom: '@services/redux/api/baseApi'
          importBaseApiAlternateName: 'graphqlApi'
          exportHooks: true
          overrideExisting: getEnv() === 'dev'
      - typescript-msw
  .graphql.schema.json:
    plugins:
      - introspection
```
