### ISSUE TITLE
typescript-react-apollo requires extension to be ".tsx"

### ISSUE THREAD

**Issue by Industrial** [dotansimha/graphql-code-generator#900]
**Describe the bug**
Using `graphql-codegen-typescript-react-apollo` doesn't generate a .tsx file.

**To Reproduce**
Schema: https://gist.github.com/Industrial/dd53d2ff16b132cdad8f830c65bf9b20
Config: https://gist.github.com/Industrial/181dcb7721b69f5e5ccb44df119ed54b/292473cca5bab4c9b1953693c9467300f31abdca

**Expected behavior**
a `.tsx` file generated.

**Environment:**
 - OS: linux
 - Codegen: 0.14.1
 - Node: 10.11.0

**Additional context**
Making the config look like this does generate a `tsx` file but no component/react types in there, it's identical to the one where I remove `typescript-react-apollo`.
```
  ./common/domain/datamodel-react.gen.d.tsx:
    plugins:
      - typescript-client
      - typescript-common
      - typescript-server
      - typescript-react-apollo
```

**Comment by dotansimha** [comment]
Hi @Industrial 

The `typescript-react-apollo` and `typescript-client` are for client-side, and they require you to specify `documents` field (pointing to your queries, mutations, subscriptions and fragments).
`typescript-server` is for server side (or, client-side schema, and goes with `typescript-resolvers`). 
Both should be coupled with `typescript-common`.

Also, you can use the same file for `typescript-react-apollo` and `typescript-client` - they extend each other (with `.tsx` extension).

Your config should looks something like that:

```yml
schema: ./common/domain/datamodel-no-annotations.gen.graphql
documents: POINT-TO-YOUR-DOCUMENTS-FILES
overwrite: true
generates:
  ./common/domain/datamodel.gen.ts:
    plugins:
      - typescript-common
      - typescript-server
      - typescript-resolvers

  ./common/domain/react-components.tsx
    plugins:
      - typescript-common
      - typescript-client
      - typescript-react-apollo
```
