### ISSUE TITLE
extend type for local schema not working.

### ISSUE THREAD

**Issue by wesselvdv** [dotansimha/graphql-code-generator#924]
**Describe the bug**
Using the `extend` keyword to extend QueryRoot or MutationRoot types is not working. Instead we have to 'redefine' the MutationRoot and QueryRoot which in turn will be merged by `gql-gen`. This doesn't play ball with the autocomplete of IntelliJ GraphQL plugin. 

We're getting a simple there have been errors in your document.

**To Reproduce**
1. Use the following schema files:

schema.graphqls
```graphql
schema {
  query: QueryRoot
}

type Commander {
  name: String
  rank: Float
}

type QueryRoot {
  commander: Commander
}
```

schema.local.graphqls
```graphql
type Welcome {
  hello: String!
}

extend type QueryRoot {
  welcome: Welcome
}
```

2. Use the following document:

```graphql
query getWelcomeGreet {
  welcome {
    hello
  }
}
```

3. Run gql-gen with the following codegen.yml:

```yaml
schema:
  - 'src/app/**/*.graphqls'
documents:
  - 'src/**/*.graphql'
config: {}
generates:
  src/app/graphql/queries.ts:
    config: {}
    plugins:
      - 'typescript-common'
      - 'typescript-client'
      - 'typescript-apollo-angular'
watch: true
overwrite: true
require: []
```

**Expected behavior**
Expected a successful merged schema with correctly generated types.
