### ISSUE TITLE
Unsupported protocol: github

### ISSUE THREAD

**Issue by kamilbonna** [dotansimha/graphql-code-generator#9273]
### Which packages are impacted by your issue?

@graphql-codegen/cli

### Describe the bug

Hi,

We are using `@graphql-codegen/cli` to generate multiple files based on `schema.graphql` which is stored in a private Github repository. Up to this point everything worked normally, but around two weeks ago, a following error when trying to load the schema from Github started to occur (I've redacted organization and repo name):

```
✔ Parse Configuration
⚠ Generate outputs
  ❯ Generate to src/graphql/generated/schemas.tsx
    ✖
      Failed to load schema from github:<organization>/<repo_name>#main:generated/schema.graphql:
      Failed to find any GraphQL type definitions in: github:<organization>/<repo_name>#main:generated/schema.graphql;
      - Unsupported protocol: github:
      - Unexpected token R in JSON at position 2
      AggregateError: Failed to find any GraphQL type definitions in: github:<organization>/<repo_name>#main:generated/schema.graphql;
      - Unsupported protocol: github:
      - Unexpected token R in JSON at position 2
      at loadFile (/home/.../node_modules/@graphql-codegen/cli/node_modules/@graphql-tools/load/cjs/load-typed…
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async /home/kamil_bonna/Desktop/.../node_modules/@graphql-codegen/cli/node_modules/@graphql-tools/load/cjs/load-typedefs/…
      GraphQL Code Generator supports:
      - ES Modules and CommonJS exports (export as default or named export "schema")
      - Introspection JSON File
      - URL of GraphQL endpoint
      - Multiple files with type definitions (glob expression)
      - String in config file
      Try to use one of above options and run codegen again.
    ◼ Load GraphQL documents
    ◼ Generate
error Command failed with exit code 1.
```

To run codegen we're using `yarn graphql-codegen --config codegen.yml` command and the content of the config file is:

```yml
schema:
  - github:<organization>/<repo_name>#main:generated/schema.graphql:
      token: ${PERSONAL_ACCESS_TOKEN} # Set environment variable
overwrite: true

generates:
  src/graphql/generated/schemas.tsx:
    plugins:
      - typescript

...
```

The problem appeared without any changes for version:
- `"@graphql-codegen/cli": "^2.1.1"`
- I also tested newest version `"@graphql-codegen/cli": "^3.3.0"` which didn't help
- but downgrading to `"@graphql-codegen/cli": "1.21.7"` solved the issue and the generator loads the schema as expected

Because older version is loading the schema I know my access token is valid.

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

1. Install `"@graphql-codegen/cli": "^2.1.1"` or newer 
2. Set attached `codegen.yml` config file 
3. Try to load schema from any private Github repository running `yarn graphql-codegen --config codegen.yml`

### Expected behavior

Schema should load normally and outputs should be generated accordingly but, the `Unsupported protocol: github` error is raised.

### Screenshots or Videos

n/a

### Platform

- OS: Linux 20.04.1-Ubuntu
- NodeJS: "node": "^16"
- `"@graphql-codegen/cli": "^2.1.1"`

### Codegen Config File

```yml
schema:
  - github:<organization>/<repo_name>#main:generated/schema.graphql:
      token: ${PERSONAL_ACCESS_TOKEN} # Set environment variable
overwrite: true

generates:
  src/graphql/generated/schemas.tsx:
    plugins:
      - typescript
```

### Additional context

n/a
