### ISSUE TITLE
typescript-resolvers mappers do not take emit

### ISSUE THREAD

**Issue by ldrick** [dotansimha/graphql-code-generator#9277]
### Which packages are impacted by your issue?

@graphql-codegen/typescript-resolvers

### Describe the bug

Once generating ESM compatible output, imports in Typescript are needed to resolve to <file>.js.
Using `@graphql-codegen/typescript-resolvers` with `mappers` doesn't write the imports correctly, even having `emitLegacyCommonJSImports: false` configured

### Your Example Website or App

https://the-guild.dev/graphql/codegen

### Steps to Reproduce the Bug or Issue

1. Go to https://the-guild.dev/graphql/codegen
2. add this codegen.yml:
```yml
generates:
  resolvers.ts:
    config:
      emitLegacyCommonJSImports: false
      mappers:
        User: ./models#UserDbObject
        Chat: ./models#ChatModel
    plugins:
      - typescript
      - typescript-resolvers
```
3. see the resolvers.ts being generated with this import:
```typescript
import { UserDbObject, ChatModel } from './models';
```

### Expected behavior

resolvers.ts shall be generated with this import:
```typescript
import { UserDbObject, ChatModel } from './models.js';
```

### Platform

- OS: Linux
- NodeJS: 18.15.0
- `graphql` version: 16.6.0
- `@graphql-codegen/typescript` version: 3.0.3
- `@graphql-codegen/typescript-resolvers` version: 3.2.0
