### ISSUE TITLE
Fragment imports broken in latest update

### ISSUE THREAD

**Issue by wassim-k** [dotansimha/graphql-code-generator#9293]
### Which packages are impacted by your issue?

@graphql-codegen/typed-document-node

### Describe the bug

In the most recet update of `@graphql-codegen/visitor-plugin-common v3.1.0` when using `typed-document-node` plugin with `near-operation-file-preset` then fragment imports from other files are missing as shown in the minial production.

### Your Example Website or App

https://stackblitz.com/edit/graphql-codegen-fragment-issue?file=src/user.query.ts

### Steps to Reproduce the Bug or Issue

1. Run `yarn` then `yarn codegen` in the minial reproduction and navigate to `src/user.query.ts` file

### Expected behavior

`UserFragmentDoc` import should be defined at the top of `user.query.ts` file.

### Platform

- Windows
- NodeJS: 16
- `graphql` version: 16.6.0
- @graphql-codegen/cli: ^3.3.0
- @graphql-codegen/near-operation-file-preset: ^2.5.0
- @graphql-codegen/typed-document-node: ^4.0.0
- @graphql-codegen/typescript: ^3.0.3
- @graphql-codegen/typescript-operations: ^3.0.3

### Codegen Config File
```
schema: './schema.graphql'
overwrite: true
config:
  documentMode: graphQLTag
  dedupeOperationSuffix: true
generates:
  ./src/types.ts:
    plugins:
      - typescript
  ./src:
    documents: ./src/**/*.graphql
    preset: near-operation-file
    presetConfig:
      extension: .ts
      baseTypesPath: types
      importTypesNamespace: _
    plugins:
      - typescript-operations
      - typed-document-node
```
