### ISSUE TITLE
Unable to find template plugin matching '-"typescript" -"typescript-operations" -"typescript-urql"'

### ISSUE THREAD

**Issue by saifrahmn** [dotansimha/graphql-code-generator#9331]
### Describe the bug

While running the yarn codegen command. I am getting the following error
`Unable to find template plugin matching '-"typescript" -"typescript-operations" -"typescript-urql"'`
I have installed all the Dependencies required for the code generation. Also mentioned all the Dependencies in package.json

### Your Example Website or App

https://github.com/saifrahmn/reddit-web

### Steps to Reproduce the Bug or Issue

.

### Expected behavior

.

### Screenshots or Videos

.

### Platform

- OS:  Windows 
- NodeJS: [e.g. 18.5.0]
- `graphql` version: [e.g. 16.3.0]
- `@graphql-codegen/*` version(s): [e.g. 2.6.2]

**Comment by eddeee888** [comment]
Hello 👋  Could you try adding a space between the `-` and each of your template please? :)

```yaml
overwrite: true
schema: "http://localhost:4000/graphql"
documents: "src/graphql/**/*.graphql"
generates:
  src/generated/graphql.tsx:
    plugins: 
      - "typescript"
      - "typescript-operations"
      - "typescript-urql"
```
