### ISSUE TITLE
gql-gen runs without errors but no output generated

### ISSUE THREAD

**Issue by asnaseer-resilient** [dotansimha/graphql-code-generator#939]
**Describe the bug**
The code generator is being run via `npm run generate` as recommended in your documentation. I have added this to my `package.json` file:
```
"scripts": {
    "generate": "gql-gen"
  }
```
The generator seems to complete without any errors however there is no output file generated.

**To Reproduce**
1. Use `schema.graphql` shown below
2. Use `codegen.yml` shown below
3. Run the following command: `npm run generate` and you will see output similar to this:
```
hub > npm run generate

> hub@0.0.0 generate /Users/anjumnaseer/workspace/angular/hub
> gql-gen

  ✔ Parse configuration
  ✔ Generate outputs
```

**Expected behavior**
I expect to find the file `schema-types.d.ts`.

**Schema/Documents**
```
type Todo {
	id: ID!
	createdBy: String!
	todo: String!
	urgent: Boolean
}

type Query {
	todos: [Todo!]!
	todo(id: ID!): Todo!
}

type Mutation {
	addTodo(todo: String!, urgent: Boolean = false): Todo
	@aws_auth(cognito_groups: ["God", "Admin"])

	deleteTodo(id: ID!): Todo!
	@aws_auth(cognito_groups: ["God"])
}

type Subscription {
	addedTodo: Todo
	@aws_subscribe(mutations: ["addTodo"])
	
	deletedTodo: Todo
	@aws_subscribe(mutations: ["deleteTodo"])
}

schema {
	query: Query
	mutation: Mutation
	subscription: Subscription
}

directive @aws_auth(cognito_groups: [String]!) on FIELD_DEFINITION

directive @aws_subscribe(mutations: [String]!) on FIELD_DEFINITION
```

**codegen.yml**
```
schema: ./schema.graphql
overwrite: true
generates:
  ./schema-types.d.ts:
    plugins:
      - typescript-common
      - typescript-client
      - typescript-apollo-angular
```

**Environment:**
 - OS: Mac Mojave 10.14.1
 - Codegen:
    "graphql-code-generator": "^0.14.3",
    "graphql-codegen-typescript-apollo-angular": "^0.14.3",
    "graphql-codegen-typescript-client": "^0.14.3",
    "graphql-codegen-typescript-common": "^0.14.3",
 - Node: v8.11.3

**Additional context**
N/A

**Comment by kamilkisiela** [comment]
@asnaseer-resilient you need to provide `documents` in there:

```yml
schema: ./schema.graphql
overwrite: true
documents: ./operations/**/*.graphql # <-- here
generates:
  ./schema-types.d.ts: # <-- here
    plugins:
      - typescript-common
      - typescript-client
      - typescript-apollo-angular
```

Declaration files `*.d.ts` can't have code in them, only interfaces, namespaces and module declarations so using GQL services won't be possible and TS will throw an error.

**Comment by jreeter** [comment]
@kamilkisiela is there any documentation describing what exactly these yaml configuratons mean? I'm also having trouble finding examples of doing basic things.. like generating my own code from a custom template..

**Comment by asnaseer-resilient** [comment]
@kamilkisiela I followed your suggestions and also created a folder named `generated` with a sub-folder named `operations` under that to hold all the generated files. My modified `codegen.yml` is:
```
schema: ./schema.graphql
documents: ./generated/operations/**/*.graphql
overwrite: true
generates:
  ./generated/schema-types.d.ts:
    plugins:
      - typescript-common
      - typescript-client
      - typescript-apollo-angular
```
However, this still fails to generate anything giving me:
```
> npm run generate

> hub@0.0.0 generate /Users/anjumnaseer/workspace/angular/hub
> gql-gen

No files matched for glob expression: ./generated/operations/**/*.graphql
  ✔ Parse configuration
  ✔ Generate outputs
```
