### ISSUE TITLE
Scalar Input Output usage Angular 

### ISSUE THREAD

**Issue by burner** [dotansimha/graphql-code-generator#9492]
### Describe the bug

https://github.com/dotansimha/graphql-code-generator/pull/9375  broke my code in angular 16.

I have a query 
```
query GetDataAt($personId: Int!, $time: DateTime!) {
```

And I was able to call it like this.
```		
const vars = { personId: theId, time: theTime };
		this.theData = new GetDataAtGQL(this.apollo)
			.watch(vars)
```

But now typescript is telling me 

```
Argument of type '{ personId: { input: number; }; time: Date; }' is not assignable to parameter of type 'Exact<{ personId: { input: number; output: number; }; time: { input: any; output: any; }; }>'.
  Types of property 'personId' are incompatible.
    Property 'output' is missing in type '{ input: number; }' but required in type '{ input: number; output: number; }'.
```

Which technically is correct, but is quite annoying as I'm using the variables as input and not as output.

Am I doing something wrong here?

### Your Example Website or App

https://github.com/dotansimha/graphql-code-generator/pull/9375

### Steps to Reproduce the Bug or Issue

any graphql query with arguments on angular

### Expected behavior

to not have to do the conversion by hand.

Maybe by having the scalar definition maybe read

```ts
type intScalar = number | { input: number, output: number | string };
```

### Platform

- OS: [e.g. macOS, Windows, Linux]
- NodeJS: [e.g. 18.5.0]
- `graphql` version: [e.g. 16.3.0]
- `@graphql-codegen/*` version(s): [e.g. 2.6.2]

**Comment by eddeee888** [comment]
Hi @burner, do you mind posting your Codegen Config please and/or a sandbox example please? 🙂

**Comment by synoptase** [comment]
Same issue. Here's my config:
```ts
const generateConfig = async (): Promise<CodegenConfig> => {
  return {
    overwrite: true,
    schema: [
      {
        [process.env.HASURA_GRAPHQL_URL!]: {
          headers: {
            "x-hasura-admin-secret": process.env.HASURA_SECRET!,
          },
        },
      },
    ],
    documents: ["./src/store/api/schema.graphql"],
    generates: {
      "./src/store/api/generated.ts": {
        plugins: [
          "typescript",
          "typescript-operations",
          {
            "typescript-rtk-query": {
              importBaseApiFrom: "./base-api",
              exportHooks: true,
            },
          },
        ],
      },
    },
  };
};
```

**Comment by Drivez** [comment]
Hi I do have the same issue using React when updating to the latest version.
how can i revert and just use the standard types and not these `{ input: string, output: string }`

Config:


```
....
generates:
    src/generated/schema.json:
        plugins:
            - introspection
        config:
            minify: true
    src/generated/possibleTypes.ts:
        plugins:
            - fragment-matcher
        config:
            scalars:
                JsonObject: Record<string, unknown>
                Timestamp: Date
    src/generated/types.ts:
        plugins:
            - typescript
        config:
            scalars:
                JsonObject: Record<string, unknown>
                Timestamp: Date
    src/:
        preset: near-operation-file-preset
        presetConfig:
            baseTypesPath: generated/types.ts
            extension: .ts
            folder: generated
        plugins:
            - typescript-operations
            - typescript-react-apollo
        config:
            scalars:
                JsonObject: Types.Scalars['JsonObject']
                Timestamp: Types.Scalars['Timestamp']
            withHooks: false
```
