### ISSUE TITLE
Multiple schemas with different documents

### ISSUE THREAD

**Issue by OneCyrus** [dotansimha/graphql-code-generator#9525]
### Is your feature request related to a problem? Please describe.

We are using two graphql endpoints in a project. currently we have two codegen configs which only differ in the path to the local schema file, the file which should be generated and a different set of documents.

the schema and generate file can already be specified by the current config-file. but I couldn't find a way to specify different documents for each schema.

### Describe the solution you'd like

similar like for the following generate part

```
generates:
   a-service.ts:
       schema: pointertoservicea
       plugins:
         - typescript
         - typescript-resolvers
       config:
          federation: true
   b-service.ts:
       schema: pointertoserviceb
       plugins:
         - typescript
         - typescript-resolvers
       config:
          federation: true
```

there should be something for documents:
```
documents
  pointertoservicea:
     - a/**/*.graphql
  pointertoserviceb:
     - b/**/*.graphql
```

### Is your feature request related to a problem? Please describe.

multiple schemas in a single project

**Comment by ardatan** [comment]
```yaml
a-service.ts:
  schema: pointertoservicea
  documents: pointertodocumentsa
   plugins:
     - typescript
  
b-service.ts:
  schema: pointertoserviceb
  documents: pointertodocumentsb
   plugins:
     - typescript
  
```
Does this work for you?
