### ISSUE TITLE
"Longest common prefix () is not accessible" on Windows

### ISSUE THREAD

**Issue by srmagura** [dotansimha/graphql-code-generator#9526]
### Which packages are impacted by your issue?

@graphql-codegen/cli

### Describe the bug

On Windows, running `graphql-codegen --watch` prints this warning:

```text
[Watcher] Longest common prefix () is not accessible
[Watcher] Watching current working directory (C:\Projects\oss\bugs\graphql-codegen-windows-repro\app) instead
```

This is problematic if your GraphQL schema file is outside of the directory in which `graphql-codegen` is run.

The issue does not occur on macOS or Linux.

### Your Example Website or App

https://github.com/srmagura/graphql-codegen-windows-repro

### Steps to Reproduce the Bug or Issue

See the README of the GitHub repository.

### Expected behavior

No warnings when running `graphql-codegen --watch`.

### Platform

- OS: Windows 11
- NodeJS: 18.16.0
- `graphql` version: 16.7.1
- `@graphql-codegen/*` version(s): 4.0.1

### Codegen Config File

```yaml
schema: ../schema.gql
documents:
  - "src/**/*.ts?(x)"
  - "!src/gql/**/*"
generates:
  src/gql/:
    preset: client
```
