### ISSUE TITLE
Duplicated 'DocumentNode' import with 'typescript-generic-sdk'

### ISSUE THREAD

**Issue by vincentgilles** [dotansimha/graphql-code-generator#9528]
### Describe the bug

Duplicated `DocumentNode` import when `rawRequest` is setted to `true` and `documentMode` is setted to `documentNode`

### Your Example Website or App

https://noexample.com

### Steps to Reproduce the Bug or Issue

Run `graphql-codegen`

### Expected behavior

`DocumentNode` imported once

### Platform

- OS: Linux
- NodeJS: 18.16.1
- `graphql` version: 15.6.1
- `@graphql-codegen/typescript-generic-sdk` version: 3.1.0

### Codegen Config File

```yaml
schema: schema.graphql'
documents: document.graphql
generates:
    types.ts:
        plugins:
            - typescript
            - typescript-operations
            - typescript-generic-sdk
        config:
            rawRequest: false
            documentMode: documentNode
```
