### ISSUE TITLE
Change Maybe<Array<Maybe<Medias>>> to Array<Maybe<Medias>> because my server not return null. it return empty array

### ISSUE THREAD

**Issue by websitevirtuoso** [dotansimha/graphql-code-generator#9568]
### Is your feature request related to a problem? Please describe.

Does it possible to change this behavior in configuration?

I have next yml configuration
```
overwrite: true
schema: '${VITE_GRAPHQL_HTTP}/public'
generates:
  ./src/plugins/apollo/schemaTypesGenerated.ts:
    schema:
      - ${VITE_GRAPHQL_HTTP}:
          headers:
            Authorization: 'Bearer ${BEARER_TOKEN}'
    plugins:
      - typescript
    config:
      avoidOptionals:
        field: false
        inputValue: false
        object: true
        defaultValue: true
      scalars:
        Date: string
        DateTime: string
        Json: JSON
        Upload: File
    hooks:
      afterOneFileWrite:
        - prettier --config ./.prettierrc ./src/plugins/apollo/schemaTypesGenerated.ts --write
        - eslint --fix ./src/plugins/apollo/schemaTypesGenerated.ts
```

Used next libs for codegen

    "@graphql-codegen/cli": "5.0.0",
    "@graphql-codegen/typescript": "^4.0.1",

### Describe the solution you'd like

I have no idea
