### ISSUE TITLE
TypeScript error TS6133: 'RefType' is declared but its value is never read

### ISSUE THREAD

**Issue by josendf-basetis** [dotansimha/graphql-code-generator#9584]
### Is your feature request related to a problem? Please describe.

Given the following GraphQL schema, having types implementing an interface:

interface Node {
    id: ID!
}

type Country implements Node {
    id: ID!
    countryName: String!
}

type City implements Node {
    id: ID!
    cityName: String!
}

The following type declaration is generated:

/** Mapping of interface types */
export type ResolversInterfaceTypes<RefType extends Record<string, unknown>> = {
    Node: City | Country;
};

The generated type declaration above produces the following TypeScript error:

error TS6133: 'RefType' is declared but its value is never read.

### Describe the solution you'd like

Unused TypeScript type parameters should not be emitted.

**Comment by eddeee888** [comment]
Hello 👋 

There's a similar issue and here's the recommendations: https://github.com/dotansimha/graphql-code-generator/issues/9498#issuecomment-1598550662

Basically, the errors reported are from TS's `noUnusedLocals` and `noUnusedParameters` settings. It's recommended to ignore linting rules in generated files if they get in the way 🙂

**Comment by shellscape** [comment]
@eddeee888 those aren't "linting" errors. That is a literal and legitimate TypeScript configuration option. Also doesn't change the fact that the code generator is creating invalid code per valid TS config.

**Comment by Antcharles22** [comment]
Hey ,
i'm creating a react project and I can't import my JS functions from other pages

**Comment by skizzo** [comment]
Any updates on this?

**Comment by diaes** [comment]
Problem is still there, is there any work planned on this?

**Comment by dannyuttarwar** [comment]
I faced the same issue after updating the dependencies So I fixed using the below steps

1. Created a codegen.yml
2. Disabled the ts-nocheck in same yaml file Like below

```
schema: src/**/*.schema.ts
generates:
  ./src/generated/generatedTypes.ts:
    plugins:
      - add:
          content: |
            /* eslint-disable */
            // @ts-nocheck
      - typescript
      - typescript-resolvers
```
