### ISSUE TITLE
Does not generate Apollo angular query classes anymore

### ISSUE THREAD

**Issue by crissi** [dotansimha/graphql-code-generator#959]
**Describe the bug**
Does not generate Apollo angular templates, like MyQueryGQL, after changing to the new config API. 

**To Reproduce**
Run yarn gql-gen with with indicated config

**Expected behavior**
Generates the GQL

**Schema/Documents**
Config (codegen.ylm):
```yml
schema:
  - "http://api-master.test.ordrestyring.dk/graphql-introspection"
documents:
  - "src/app/**/!(login.gql|graphql)*.{graphql}"
config: {}
generates:
  src/app/generated/graphql.ts:
    config: {}
    plugins:
      - "typescript-apollo-angular"
      - typescript-common
      - typescript-client

require: []
```

versions:
graphql-code-generate: v0.14.5 
graphql-codegen-apollo-angular-template: v0.14.5 

**Environment:**
 - OS: Windows
