### ISSUE TITLE
Resolver cannot return null on nullable query...

### ISSUE THREAD

**Issue by olalonde** [dotansimha/graphql-code-generator#9670]
### Which packages are impacted by your issue?

@graphql-codegen/cli, @graphql-codegen/core

### Describe the bug

```graphql
type Query {
  # health check
  time: Int!
  allUsers: [User!]!
  currentUser: User
  interpreter(id: ID!): Interpreter
}
```

```typescript

src/api/graphql/resolvers/interpreter.ts:44:9 - error TS2322: Type '(_: {}, params: RequireFields<QueryInterpreterArgs, "id">, ctx: GraphQLContext) => Promise<{ userId: string; createdAt: Date; } | null>' is not assignable to type 'Resolver<Maybe<ResolverTypeWrapper<Interpreter>>, {}, GraphQLContext, RequireFields<QueryInterpreterArgs, "id">> | undefined'.
  Type '(_: {}, params: RequireFields<QueryInterpreterArgs, "id">, ctx: GraphQLContext) => Promise<{ userId: string; createdAt: Date; } | null>' is not assignable to type 'ResolverFn<Maybe<ResolverTypeWrapper<Interpreter>>, {}, GraphQLContext, RequireFields<QueryInterpreterArgs, "id">>'.
    Type 'Promise<{ userId: string; createdAt: Date; } | null>' is not assignable to type 'Maybe<ResolverTypeWrapper<Interpreter>> | Promise<Maybe<ResolverTypeWrapper<Interpreter>>>'.
      Type 'Promise<{ userId: string; createdAt: Date; } | null>' is not assignable to type 'Promise<Interpreter>'.
        Type '{ userId: string; createdAt: Date; } | null' is not assignable to type 'Interpreter'.
          Type 'null' is not assignable to type 'Interpreter'.

44   async interpreter(_, params, ctx) {
           ~~~~~~~~~~~
```

```typescript
export const interpreterQueryResolvers: gql.QueryResolvers<GraphQLContext> = {
  async interpreter(_, params, ctx) {
    const interpreter = await findInterpreterById(ctx, parseInt(params.id, 10));
    if (!interpreter) return null;
    return {
      userId: `${interpreter.userId}`,
      createdAt: interpreter.createdAt,
    };
  },
};

```

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

Use my schema , and try to use the generated resolver types.

### Expected behavior

Should allow resolver to return a null value.
<img width="551" alt="Screenshot 2023-09-13 at 2 59 18 AM" src="https://github.com/dotansimha/graphql-code-generator/assets/416585/ebd535f7-29f5-4aa8-9a98-15544a781698">

### Platform

- OS: macOS
- NodeJS: v20.5.0
- `graphql` version:  16.8.0
- `@graphql-codegen/*` version(s): 5.0.0

### Codegen Config File

```yaml
overwrite: true
schema: "./graphql/schema.graphql"
# documents: "./src/api/graphql/schema.graphql"
documents: null
emitLegacyCommonJSImports: false
generates:
  # ./src/api/graphql/generated/client/:
  #   preset: "client-preset"
  ./src/api/graphql/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-resolvers"
    config:
      enumsAsConst: true
```
