### ISSUE TITLE
config.schema.json not valid

### ISSUE THREAD

**Issue by thscott** [dotansimha/graphql-code-generator#9749]
### Describe the bug

The json schema [config.schema.json](https://github.com/dotansimha/graphql-code-generator/blob/master/website/public/config.schema.json) seems to be invalid, so is causing issues in vscode (which tries to validate the codegen.yml file).

This seems to be due to the property types of the FlutterFreezedPluginConfig being invalid, such as:
https://github.com/dotansimha/graphql-code-generator/blob/527da03f1ecbf8de12259342386551792656a8e9/website/public/config.schema.json#L111

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

As above.

### Expected behavior

As above.

### Platform

N/A

**Comment by Urigo** [comment]
@thscott thanks for reporting!
Can you share an example or a reproduction of how it looks on your machine?

**Comment by bradskuse** [comment]
Hey, I have this same issue.  Here is the contents of my codegen.yml 

```yml
schema: './schema.graphql'
generates:
  ./src/__generated__/resolvers-types.ts:
    plugins:
      - 'typescript'
      - 'typescript-resolvers'
    config:
      useIndexSignature: true
      contextType: '../index#MyContext'
```

**Comment by Urigo** [comment]
@bradskuse can you share a repo or a codesandbox with the whole code?

**Comment by leah-willett-ck** [comment]
I'm having the same issue.

**Comment by pete-otaqui** [comment]
This seems to have been introduced in https://github.com/dotansimha/graphql-code-generator-community/pull/47

**Comment by kevinvalk** [comment]
All properties of the `FlutterFreezedPluginConfig` object use type values that are not valid JSON schema types.
![image](https://github.com/dotansimha/graphql-code-generator/assets/3524694/2b5e6760-ead6-4c9c-baa9-ba8e2e105319)

The configuration types are "better" explained in the current documentation https://the-guild.dev/graphql/codegen/plugins/dart/flutter-freezed (or just https://github.com/dotansimha/graphql-code-generator-community/blob/b6c4b0159c53530251dc50040eeac282f6e128e9/packages/plugins/dart/flutter-freezed/src/config/plugin-config.ts). However, they feel "weird" and out of place compared to all other plugins.

The schema has to be updated to reflect the more complex types. For example, for `camelCasedEnums` it should be as below (OR rewritten using "$ref" and keeping the `DartIdentifierCasing`.
```yaml
    "FlutterFreezedPluginConfig": {
      "description": "configure the `flutter-freezed` plugin",
      "type": "object",
      "properties": {
        "camelCasedEnums": {
          "anyOf": [{"type": "boolean"}, {"type": "string", "enum": ["snake_case", "camelCase", "PascalCase"]}],
          "description": "Setting this option to `true` will camelCase enum values as required by Dart's recommended linter.\n\nIf set to false, the original casing as specified in the Graphql Schema is used\n\nYou can also transform the casing by specifying your preferred casing for Enum values.\n\nAvailable options are: `'snake_case'`, `'camelCase'` and `'PascalCase'`\n\nFor consistency, this option applies the same configuration to all Enum Types in the GraphQL Schema\nDefault value: \"true\""
        },
```

That said, I am not sure who "owns" the schema nor how to manage the schema + docs complex types.

**Until this is fixed the schema is literally unusable, so perhaps yanking the `FlutterFreezedPluginConfig` from the schema is the best interim solution?**
