### ISSUE TITLE
[TypeScript] Allow to provide custom naming 

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-code-generator#977]
Currently, there is only one `namingConvention` config, and the goal is to keep the current behavior, but also allow developers to separate it. 

So this will still work:
```yml
namingConvention: module#method
```

But also allow to provide a default naming, with overrides:

```yml
namingConvention:
   default: module#method1
   enumValues: module#method2 
   typeNames: module#method3 
```

**Comment by benafa** [comment]
Is there any way of retaining enum names (rather than having them changed to CamelCase) in the current version?

**Comment by dotansimha** [comment]
@benafa 
There is no option for that currently, until we'll implement and resolve this issue. 

You can use the workaround suggested by @speakerwiggin in: https://github.com/dotansimha/graphql-code-generator/pull/969#issuecomment-443944864, and use `0.15.0-alpha.3c84ac73` version for now.

**Comment by SoyYoRafa** [comment]
Hi,
Will this support a "pass-through" mode? Our team would like strong coupling between our schema casing and TypeScript casing. We do not want anything transforming casing. If not, could you please add it? I can also send a PR on feature/custom-naming-convention.

**Comment by OneCyrus** [comment]
any update on this? the auto renaming broke us. We would prefer a pass-through option as well.

**Comment by dotansimha** [comment]
We are working on it: https://github.com/dotansimha/graphql-code-generator/pull/1092 https://github.com/dotansimha/graphql-code-generator/pull/1136

**Comment by dotansimha** [comment]
Hi @OneCyrus @patrickr @SoyYoRafa @benafa 
We just merged https://github.com/dotansimha/graphql-code-generator/pull/1092 with support for changing the naming convention. 

You can now specify the following config:
```
    config:
      namingConvention:
        default: change-case#pascalCase
        enumValues: change-case#upperCase
```

**Comment by dotansimha** [comment]
Fixed in 0.16.0

**Comment by OneCyrus** [comment]
thanks! the enums are now correctly upper case but we have a new issue with inconsistent naming of the enum itself see #1193

**Comment by SoyYoRafa** [comment]
How do we configure disabling change-case? Is there a no-change-case?

**Comment by gaberudy** [comment]
I discovered looking at the code there is a way to do a no-change-case, you specify `keep` as the option for the namingConvention. Here is my config for example:

```
generates:
  ./src/types/types.ts:
    plugins:
      - typescript-common
      - typescript-server
    config:
      avoidOptionals: true
      namingConvention:
        enumValues: keep
```
