### ISSUE TITLE
Version 0.14.5 doesnt work with config file

### ISSUE THREAD

**Issue by trangcongthanh** [dotansimha/graphql-code-generator#979]
**Describe the bug**
I using version 0.14.5 and it doesn't work with `codegen.yml` file. Always get error message `Flag --schema is missing!`. When downgrade to 0.14.1, it's work as expect.

**To Reproduce**
1. Install version 0.14.5
2. Create codegen.yml
3. Run `gql-gen`
4. Got error `Flag --schema is missing!`
5. Run `gql-gen --config ./codegen.yml`
6. Still got error `Flag --schema is missing!`

**Expected behavior**
It should work as expect

**Environment:**
 - OS: Mac OS Mojave
 - Codegen: 0.14.5
 - Node: v8.11.1

**Additional context**
I'm using yarn workspace, but got no problem with v0.14.1

**Comment by ardatan** [comment]
Could you share your `codegen.yml` file?

**Comment by trangcongthanh** [comment]
> Could you share your `codegen.yml` file?

This content I copied from cli:
```
schema:
  - "MY_SERVER_GRAPHQL/graphql"
documents: []
config: {}
generates:
  ./src/models.ts:
    config: {}
    plugins:
      - "typescript-common"
      - "typescript-client"
      - "typescript-server"
require: []
```

This is my config:
```
schema: MY_SERVER_GRAPHQL/graphql
overwrite: true
generates:
  ./src/models.ts:
    config: 
      imutableTypes: true

    plugins:
      - add:
        - // tslint:disable

      - typescript-common
      - typescript-server
```

Both of them does not work.
