### ISSUE TITLE
Unable to use mongo-db directives along with other code-generator template.

### ISSUE THREAD

**Issue by ganeshpms** [dotansimha/graphql-code-generator#985]
**Describe the bug**
When I try to have the `typescript-Mongodb` code generated, I had to add the Mongo DB directives. I am using the same schema to generate the other typescript types like `typescript-common`, `typescript-server` I am getting error `Unknown directive "entity"`.

**To Reproduce**

```yml
schema: libs/schema/src/graphs/**/*.gql
generates:
    libs/mongodb-client/src/lib/types.ts:

    config:
      enumsAsTypes: true
    plugins:
      - add: // Auto Generated. Please don't edit, the changes will be overwritten
      - time: 
      - typescript-mongodb

    libs/schema/src/lib/types.ts:

    config:
      enumsAsTypes: true
    plugins:
      - add: // Auto Generated. Please don't edit, the changes will be overwritten
      - time: 
      - typescript-common
```

where the '**/*.gql` files are having the mongo db directives.

**Expected behavior**
it should create two output files with mongodb typescript template and common typescript template.

**Schema/Documents**
`type DBObject @entity {
    id: String @id
    name: String @column
}`

**Environment:**
 - OS: Windows 10
 - Codegen:  0.14.5
 - Node: 10.13.0
