### ISSUE TITLE
Number in type name doesn't support scalar mapping

### ISSUE THREAD

**Issue by quolpr** [dotansimha/graphql-code-generator#989]
Codegen config:

```
schema: http://localhost:4001/graphql
documents: ./src/**/*.graphql
overwrite: true
generates:
  ./src/queries.tsx:
    plugins:
      - add: // tslint:disable
      - typescript-common
      - typescript-client	
      - typescript-react-apollo
    config:
      avoidOptionals: true
      scalars:
        Uuid4: string
        DateTime: string
        Json: string
```

`DateTime`, `Json` mapping works good, but it fails on Uuid4.

The generated file:

```
/** The `UUID4` scalar type represents UUID4 compliant string data, represented as UTF-8character sequences. The UUID4 type is most often used to represent uniquehuman-readable ID strings. */
export type Uuid4 = any;

/** The `DateTime` scalar type represents a date and time in the UTCtimezone. The DateTime appears in a JSON response as an ISO8601 formattedstring, including UTC timezone ("Z"). The parsed date and time string willbe converted to UTC and any UTC offset other than 0 will be rejected. */
export type DateTime = string;

/** The `Json` scalar type represents arbitrary json string data, represented as UTF-8character sequences. The Json type is most often used to represent a free-formhuman-readable json string. */
export type Json = string;
```
